### ISSUE TITLE
[WebView] onMessage failing when there are JS warnings and errors on the page

### ISSUE THREAD

**Issue by raiderrobert** [facebook/react-native#10865]
### Description

I'm receiving this error (same as screenshot below): 
```
Setting onMessage on a WebView overrides existing values of window.postMessage, 
but a previous value was defined.
```

![screen shot 2016-11-10 at 3 33 31 pm](https://cloud.githubusercontent.com/assets/806571/20193259/3a8a267a-a75b-11e6-9115-2dc4e96f25cf.png)

That specific error message is found in the code base here: https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L286

### Implementation

I followed the example at this link for onMessage at this link: http://facebook.github.io/react-native/releases/0.37/docs/webview.html#examples

I made a callable `respondToOnMessage` and injected some JavaScript. 

```
class MessagingTest extends React.Component {

    respondToOnMessage = e =>{
        console.log(e);
    };

    render() {
        const jsCode = `window.postMessage('test');`;

        return (
        <WebView
        injectedJavaScript={jsCode}
        source={uri: 'https://www.foo.com/'}}
        onMessage={this.respondToOnMessage}
        />
        )
    }
}
```

### Reproduction

I load the app with this example and I have it pointed to a website (rather not say which one. Sorry.) And the website is emitting 2 errors into the Chrome console when I go there.

```
(index):994 A Parser-blocking, cross-origin script, http://example.com/thing.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

widgets.js:8 Uncaught TypeError: Cannot set property '[object Array]' of undefined(…)
```

Other websites like google.com and github.com are just fine. If you want to replicate it, change the `uri` to yahoo.com

### Additional Information

* React Native version: 0.37
* Platform: iOS 10.1, iPhone 6 emulator
* Operating System: Mac OSX Sierra 10.12.1

**Comment by raiderrobert** [comment]
I should also add that I attempted to replicate the error on Android 7.0 and API 24 using a Nexus_5x emulator, and I got NO error. So this seems to be a platform specific error.

**Comment by sreucherand** [comment]
I'm getting the same error. Seems like this exception is thrown when `window.postMessage` has been overwritten. But since `webViewDidFinishLoad` is called multiple times, it tries to overwrite window.postMessage over and over. Not sure though. Can we have you expertise @jacobp100?

**Comment by jacobp100** [comment]
It’s because the page you’re visiting is overriding `postMessage`, which may be due to a shim. Ping @satya164 for input on how to resolve.

**Comment by sreucherand** [comment]
Well, when I try `String(window.postMessage) === String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage')` on the page I visit, it returns ` true`, so I am guessing `postMessage` has not been overridden.

**Comment by jacobp100** [comment]
Oh I see. The JS is injected after postMessage is overwritten. Your best bet is to fork it then, and I’ll see what I can do about getting this fixed! Sorry. :(

**Comment by persyl** [comment]
I have same error, without injecting any javascript to WebView - just setting WebView-properties:

source={require('../lib/html/somefile.html')}
onMessage={() => console.log('Hello World')}

and in my ../lib/html/somefile.html' I have javascript code doing both window.postMessage() and document.addEventListener("message",.......

Everything worked fine when I had the HTML in a variable "someHtml", like:
source={{html: someHtml}}

So difference seem to be when changing source to HTML-file instead of HTML-string.

Still for me I had other reasons, not related to this, why I really need to read HTML from file instead of string so it would be great to get this issue fixed.

**Comment by cbcye** [comment]
+1, still has this problem

**Comment by lealife** [comment]
+1, I'm getting the same error. When there is a `iframe` on web, it occurs the same error

**Comment by varhp** [comment]
+1，encounter this problem

**Comment by jacobp100** [comment]
Again, there is a pr for this. We're aware this problem is affecting a lot of people.

**Comment by edencakir** [comment]
+1 getting the same error.

**Comment by kyle-ilantzis** [comment]
injectedJavascript should instead be the following

```js
(function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) { 
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() { return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage'); };

  window.postMessage = patchedPostMessage;
})();
```

And then it works! 😄 

And if any one is interested, in my code instead of writing a giant string I did the following

```js
const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) { 
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() { 
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };

  window.postMessage = patchedPostMessage;
};

const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';

...

<WebView injectedJavaScript={patchPostMessageJsCode} />
```

**Comment by mschipperheyn** [comment]
@kyle-ilantzis tried this with RN 0.38.1, but still get the Red Screen. What version of RN are you on?

**Comment by kyle-ilantzis** [comment]
@mschipperheyn I am using RN 0.39.0 

The ios webview code between 0.39 and 0.38 is not different so it is odd you still get the red screen.

https://github.com/facebook/react-native/blob/0.39-stable/React/Views/RCTWebView.m#L280

https://github.com/facebook/react-native/blob/0.38-stable/React/Views/RCTWebView.m#L280

**Comment by abeauvois** [comment]
Same issue with RN 0.40, as soon as we add 'onMessage' props to the WebView.

**Comment by hadrienj** [comment]
Same issue with RN 0.42 with a WebView (without js injection) when I load PouchDB ([6.1.2](https://pouchdb.com/download.html)).

**Comment by skrobek** [comment]
@kyle-ilantzis I'm trying your solution with RN 0.42 but after using it I can't see `onMessage` callback:
```js
pushCredentials = () => {
    if (this.webview) {
      this.webview.postMessage('Post message triggered');
    }
  }


onMessage = (e) => {
    this.setState({ postMessage: e.nativeEvent.data });
};
```

**Comment by kyle-ilantzis** [comment]
@skrobek Do you mean pushCredentials() no longer causes onMessage() to be called?

1. Should it not be:
onMessage={this.onMessage.bind(this)}

2. I never thought that when posting a message from react-native to the webview the webview would call its own onMessage. I thought onMessage is only called when JS code in the webview calls window.postMessage(...)

**Comment by skrobek** [comment]
@kyle-ilantzis Look at the docs example:
```js
class MessagingTest extends React.Component {
  webview = null

  state = {
    messagesReceivedFromWebView: 0,
    message: '',
  }

  onMessage = e => this.setState({
    messagesReceivedFromWebView: this.state.messagesReceivedFromWebView + 1,
    message: e.nativeEvent.data,
  })

  postMessage = () => {
    if (this.webview) {
      this.webview.postMessage('"Hello" from React Native!');
    }
  }

  render(): ReactElement<any> {
    const {messagesReceivedFromWebView, message} = this.state;

    return (
      <View style={[styles.container, { height: 200 }]}>
        <View style={styles.container}>
          <Text>Messages received from web view: {messagesReceivedFromWebView}</Text>
          <Text>{message || '(No message)'}</Text>
          <View style={styles.buttons}>
            <Button text="Send Message to Web View" enabled onPress={this.postMessage} />
          </View>
        </View>
        <View style={styles.container}>
          <WebView
            ref={webview => { this.webview = webview; }}
            style={{
              backgroundColor: BGWASH,
              height: 100,
            }}
            source={require('./messagingtest.html')}
            onMessage={this.onMessage}
          />
        </View>
      </View>
    );
  }
}
```

**Comment by kyle-ilantzis** [comment]
@skrobek Oh no 😱

My objective was to have the JS code in the webview talk to react-native. It was not to have react-native talk to itself through a webview.

patchPostMessage achieved my objective, no more red screen on ios when setting the onMessage property of a webview. JS code in an IOS webview could then talk to react-native

**Comment by skrobek** [comment]
@kyle-ilantzis Yeah. Now I have huge problem because docs cause red screen and your solution helps with the red screen but block `webview.postMessage` - no idea what to do ;-)

**Comment by davidhellsing** [comment]
You could wait for the `onLoad` before passing `onMessage` into the component (passing `null` until the onLoad triggers).

It worked for us, but we have to implement a simple queue in the webview that collects posts until the `onLoad` has triggered, which then triggers another `onLoad` inside the webview using `injectJavaScript`...

```
  onLoad(e) {
    if ( this.state.loaded ) {
      return
    }
    this.setState({ loaded: true }, () => {
      this.bridge.injectJavaScript('window.onLoad()');
    });
  }
  onMessage(payload) {
    console.log('got message from web view', payload)
  }
  render() {
    return (
      <WebView
        onLoad={this.onLoad}
        ref={n => this.bridge = n} 
        source={require('../assets/bridge.html')} 
        javaScriptEnabled={true} 
        onMessage={this.state.loaded ? this.onMessage.bind(this) : null} 
        injectedJavaScript={`window.Init("${this.props.userId}");`}
      />
    )
  }
```

**Comment by kyle-ilantzis** [comment]
@davidhellsing interesting to use the webview onLoad. With the injectedJavascipt solution I still needed to implement a queue in the webview

**Comment by axten** [comment]
The Workarounds are not working for me.
Is someone working on an fix for that?

**Comment by davidhellsing** [comment]
If you feel brave, use a shell script to rename the native `postMessage`:

```
sed -i '' '/@"window.originalPostMessage = window.postMessage;"/d' node_modules/react-native/React/Views/RCTWebView.m
sed -i '' 's/  "window.postMessage = function(data) {/@"window.nativePostMessage = function(data) {/' node_modules/react-native/React/Views/RCTWebView.m
sed -i '' '/"window.originalPostMessage = window.postMessage," +/d' node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java
sed -i '' 's/"window.postMessage = function(data) {" +/"window.nativePostMessage = function(data) {" +/' node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java
```

After running this script (you will need to do it after each `yarn` `npm install`), you can simply use:

```
window.nativePostMessage('it works')
```

inside your webView. IMO, this should be done a long time ago... there is a PR here for basically the same thing: https://github.com/facebook/react-native/pull/12997/files?diff=split

**Comment by davidhellsing** [comment]
I gave up on this and made a shell script that patches native code: https://github.com/facebook/react-native/issues/10865#issuecomment-302661876

Works flawlessly.

**Comment by 0x6e6562** [comment]
@davidhellsing Nice patch :-)

This appears to be working for me on iOS with RN 0.44 (haven't tried it on Android yet).

**Comment by shenzhenjinma** [comment]
please see http://68xg.com/reactnative/82.html

**Comment by axten** [comment]
@davidhellsing this sed script is not working on android
it seems that react native android uses pre compiled sources and the change to the java file has no effect.
this is where i go so far https://facebook.github.io/react-native/docs/android-building-from-source.html

messing the second day in a row with this bug...shit

**Comment by davidgross** [comment]
Just ran into this today, would really like to have a resolution for our project.

**Comment by untungs** [comment]
In my project this red screen doesn't appear for non-debug build and the web page I'm using still works without any issue. While in debug build I could just dismiss the red screen and continue. But It's kinda annoying and who knows when an issue's gonna popping up in non-debug build. Please fix.

**Comment by MrLoh** [comment]
Is this gonna be fixed, it's super annoying and there are plenty suggestions for a solution?.

**Comment by probedb** [comment]
Just ran into this today too. I can see the website load in the app and then I get this error. Has completely halted work on our app.

**Comment by MrLoh** [comment]
the solution from @kyle-ilantzis works well. I just wrote a patched WebView class for myself, feel free to use. This class also automatically JSON encodes and decodes the messages. 

```js
import React from 'react'
import { WebView } from 'react-native'

// fix https://github.com/facebook/react-native/issues/10865
const patchPostMessageJsCode = `(${String(function() {
    var originalPostMessage = window.postMessage
    var patchedPostMessage = function(message, targetOrigin, transfer) {
        originalPostMessage(message, targetOrigin, transfer)
    }
    patchedPostMessage.toString = function() {
        return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage')
    }
    window.postMessage = patchedPostMessage
})})();`

export default class MessageWebView extends React.Component {
    constructor(props) {
        super(props)
        this.postMessage = this.postMessage.bind(this)
    }
    postMessage(action) {
        this.WebView.postMessage(JSON.stringify(action))
    }
    render() {
        const { html, source, url, onMessage, ...props } = this.props
        return (
            <WebView
                {...props}
                injectedJavaScript={patchPostMessageJsCode}
                source={source ? source : html ? { html } : url}
                ref={x => {this.WebView = x}}
                javaScriptEnabled
                onMessage={e => onMessage(JSON.parse(e.nativeEvent.data))}
            />
        )
    }
}
```

**Comment by probedb** [comment]
@kyle-ilantzis Am I missing something from my code? I have implemented it as per your example, I have put debug code into the site I use inside the WebView so I can see it sends the postMessage, however nothing happens in the react-native app :/

    const patchPostMessageFunction = function() {
      var originalPostMessage = window.postMessage;

      var patchedPostMessage = function(message, targetOrigin, transfer) { 
        originalPostMessage(message, targetOrigin, transfer);
      };

      patchedPostMessage.toString = function() { 
        return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
      };

      window.postMessage = patchedPostMessage;
    };

    const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';

    _onMessage(e) {
      deviceLog.log('_onMessage')

      const {messageType, messageData} = e.nativeEvent.data

      deviceLog.log(messageType, messageData)
      switch (messageType) {
        case'registeredUser':
          Intercom.registerIdentifiedUser({ userId: messageData.customerId })
          break;
        case'unregisteredUser':
          Intercom.registerUnidentifiedUser()
          break;
      }
    }
    render() {
      return (
        <View style={[styles.container]}>
          <LogView inverted={false} multiExpanded timeStampFormat='HH:mm:ss'></LogView>
          <WebView
            ref={WEBVIEW_REF}
            automaticallyAdjustContentInsets={false}
            style={styles.webView}
            source={{uri: this.state.url}}
            javaScriptEnabled
            domStorageEnabled
            decelerationRate="normal"
            startInLoadingState
            scalesPageToFit={this.state.scalesPageToFit}
            onShouldStartLoadWithRequest={this._onShouldStartLoadWithRequest}
            onNavigationStateChange={this._onNavigationStateChange}
            onMessage={this._onMessage}
            injectedJavaScript={patchPostMessageJsCode}
          />
        </View>
      )
    }

The `deviceLog` above is not registering anything. I know it works as everything else that uses it works. Also in my `constructor()` I have:

    this._onMessage = this._onMessage.bind(this)

Any thoughts anyone? It's the last step in my app that I need to do :)

**Comment by kyle-ilantzis** [comment]
@probedb so you no longer have the red error screen? Next problem is most likely that react native has not loaded into the webview.

Maybe the site calls postMessage before react native has attached hooks into the webview

To be sure that this is the reason, sourround your site's postMessage with a timeout

setTimeout( 
function() { windown.postMessage(...)  }
, 
2000 ) 

You can get more details below (where I also particupated in the discussion ;) )

https://github.com/facebook/react-native/issues/11594

**Comment by probedb** [comment]
@kyle-ilantzis yep, the red screen has gone :) It appears to be in the react app I run in the WebView. For some reason although the code is running, it's not firing the postMessage. I tried a very simple test and it picks up the code. Thanks for the help 👍

**Comment by MrLoh** [comment]
@probedb did you get it working to receive `postMessage` from the WebView, it worked without problems for me when triggered through a button. Maybe you need an on document ready hook.

**Comment by MrLoh** [comment]
Here some example code for sending and receiving messages from react native and web view back and fourth.

native side: 

```js
import React from 'react'
import PropTypes from 'prop-types'
import MessageWebView from './MessageWebView'
import { View, TouchableOpacity, Text, WebView } from 'react-native'

export default class MessageTest extends React.Component {
    constructor(props) {
        super(props)
        this.postMessage = this.postMessage.bind(this)
    }
    receivedMessage(action) {
        console.log('received message from web view')
        console.log(action)
    }
    postMessage() {
        console.log('sending message from react native')
        this.webView.postMessage('message from react native')
    }
    render() {
        return (
            <View style={{ flex: 1, marginTop: 22 }}>
                <MessageWebView
                    source={require('./MessageTest.html')}
                    ref={x => {
                        this.webView = x
                    }}
                    onMessage={this.receivedMessage}
                />
                <TouchableOpacity onPress={this.postMessage}>
                    <Text>Send message from react native</Text>
                </TouchableOpacity>
            </View>
        )
    }
}
```

webview side: 

```html
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        html, body {
            margin: 0;
            font-family: sans-serif;
        }
    </style>
</head>
<body>
    <h2>Hello Web from React Native</h2>
    <button>Send message from web</button>
    <textarea style="height: 50%; width: 100%;" readonly></textarea>
    <script>
        const log = document.querySelector('textarea')
        function logMessage(message) {
            log.append(Date.now() + " | " + message + "\n");
        }
        document.querySelector("button").onclick = function() {
            const message = 'message from web view'
            logMessage(message)
            window.postMessage(JSON.stringify(message))
        }
        document.addEventListener("message", function(event) {
            const message = JSON.parse(event.data)
            logMessage(message)
        }, false)
    </script>
</body>
</html>
```

**Comment by probedb** [comment]
@MrLoh many thanks :) It seems to be something in my WebView side sending the messages as I tried it with a very basic HTML page with a click to send and the React Native side picked it up.

**Comment by jigfox** [comment]
I tried @MrLoh Code, but I still get the red error screen:

```js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  WebView,
  Dimensions,
} from 'react-native';

const patchPostMessageJsCode = `(${String(function() {
  var originalPostMessage = window.postMessage
  var patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer)
  }
  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage')
  }
  window.postMessage = patchedPostMessage
})})();`

class MessageWebView extends React.Component {
  constructor(props) {
    super(props)
    this.postMessage = this.postMessage.bind(this)
  }
  postMessage(action) {
    this.WebView.postMessage(JSON.stringify(action))
  }
  render() {
    const { html, source, url, onMessage, ...props } = this.props
    return (
      <WebView
        {...props}
        javaScriptEnabled
        injectedJavaScript={patchPostMessageJsCode}
        source={source ? source : html ? { html } : url}
        ref={x => {this.WebView = x}}
        onMessage={e => onMessage(JSON.parse(e.nativeEvent.data))}
      />
    )
  }
}

export default class WebViewTest extends Component {

  onLoadStart() {
    console.log('start')
  }

  onLoadEnd() {
    console.log('end')
  }

  onMessage() {
    console.log('message')
  }

  render() {
    return (
      <View style={styles.container}>
        <MessageWebView
          source={{uri: 'https://www.hornbach.de'}}
          style={{marginTop: 20}}
          javaScriptEnabled
          startInLoadingState
          onLoadStart={this.onLoadStart}
          onLoadEnd={this.onLoadEnd}
          style={styles.web}
          onMessage={this.onMessage}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  web: {
    flex: 1,
    width: Dimensions.get('window').width,
  },
});

AppRegistry.registerComponent('WebViewTest', () => WebViewTest);

```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by MrLoh** [comment]
Please keep this open. It is very real.

**Comment by kyle-ilantzis** [comment]
What @MrLoh said, this issue is very real, please keep it open.

**Comment by jigfox** [comment]
While this proplem is real and it should be open. We worked around this problem using https://github.com/CRAlpha/react-native-wkwebview, but sadly this means we have two different implementations of the code injected for iOS and android. It would be much nicer too have a solution working the same on both platforms with the default WebView

**Comment by linnett** [comment]
Absolutely still a problem over here too. Please keep open @hramos

**Comment by ames89** [comment]
still not working, on rn - 0.48.4 stills shows a red screen error

**Comment by MrLoh** [comment]
Please keep open.

**Comment by andersondecarvalho** [comment]
import React, { Component } from 'react';
import { View, Text, WebView, Dimensions, Alert } from 'react-native';

const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;
  var patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };
  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };
  window.postMessage = patchedPostMessage;
};

const injectScript = '(' + String(patchPostMessageFunction) + ')();';

export default class WebviewCustom extends Component {
  constructor(props) {
    super(props);
    this.state = { webviewLoaded: false };
  }

  _onLoadEnd() {
    this.handleNavigationChange();
  }

  handleNavigationChange() {
    const script = 'window.postMessage(document.documentElement.innerHTML)';
    thisWebView && thisWebView.injectJavaScript(script);
  }

  _onMessage(e) {
    Alert.alert(e.nativeEvent.data);
  }

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'rgb(255, 255, 255)' }}>
        <WebView
          ref={webview => {
            thisWebView = webview;
          }}
          onLoadEnd={this._onLoadEnd.bind(this)}
          injectedJavaScript={injectScript}
          source={{ uri: this.props.url }}
          onMessage={this._onMessage}
        />
      </View>
    );
  }
}

**Comment by andersondecarvalho** [comment]
`import React, { Component } from 'react';
import { View, Text, WebView, Dimensions, Alert } from 'react-native';

const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;
  var patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };
  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };
  window.postMessage = patchedPostMessage;
};

const injectScript = '(' + String(patchPostMessageFunction) + ')();';

export default class WebviewCustom extends Component {
  constructor(props) {
    super(props);
    this.state = { webviewLoaded: false };
  }

  _onLoadEnd() {
    this.handleNavigationChange();
  }

  handleNavigationChange() {
    const script = 'window.postMessage(document.documentElement.innerHTML)';
    thisWebView && thisWebView.injectJavaScript(script);
  }

  _onMessage(e) {
    Alert.alert(e.nativeEvent.data);
  }

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'rgb(255, 255, 255)' }}>
        <WebView
          ref={webview => {
            thisWebView = webview;
          }}
          onLoadEnd={this._onLoadEnd.bind(this)}
          injectedJavaScript={injectScript}
          source={{ uri: this.props.url }}
          onMessage={this._onMessage}
        />
      </View>
    );
  }
}
`

**Comment by andersondecarvalho** [comment]
```
import React, { Component } from 'react';
import { View, Text, WebView, Dimensions, Alert } from 'react-native';

const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;
  var patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };
  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };
  window.postMessage = patchedPostMessage;
};

const injectScript = '(' + String(patchPostMessageFunction) + ')();';

export default class WebviewCustom extends Component {
  constructor(props) {
    super(props);
    this.state = { webviewLoaded: false };
  }

  _onLoadEnd() {
    this.handleNavigationChange();
  }

  handleNavigationChange() {
    const script = 'window.postMessage(document.documentElement.innerHTML)';
    thisWebView && thisWebView.injectJavaScript(script);
  }

  _onMessage(e) {
    Alert.alert(e.nativeEvent.data);
  }

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'rgb(255, 255, 255)' }}>
        <WebView
          ref={webview => {
            thisWebView = webview;
          }}
          onLoadEnd={this._onLoadEnd.bind(this)}
          injectedJavaScript={injectScript}
          source={{ uri: this.props.url }}
          onMessage={this._onMessage}
        />
      </View>
    );
  }
}

```

**Comment by MrLoh** [comment]
Yes we know there are workarounds documented here. But it’s still a bit nevertheless.

**Comment by hramos** [comment]
Re-opening. Is anyone working on a fix or is there a PR waiting for review? I want to make sure this gets fixed before the issue gets closed due to inactivity.

**Comment by zecaptus** [comment]
I saw this PR https://github.com/facebook/react-native/pull/12997/commits/34d5053d682ee2ec203b2f459832131e7d11ab3e .

I'm sure this will fix this bug. 

Is there a working workaround for this ? I've tryed everything here, but nothing seems to works for me, every time I have the red message.

**Comment by zecaptus** [comment]
Hum, strange things ...

I just tried to install newer version of react-native, I can't since i'm using create-react-native-app.
So I've just re-install the 48.4 version and all seem's to work now ... I can't explain why ...

**Comment by samermurad** [comment]
#12997 will not necessarily fix this.
I fixed it locally and submitted a pull request #16502 
I also created a gist for a quick fix for react native 0.44.2 [here](https://gist.github.com/samermurad/d5292fd82cf6ec1f6fa37b87f550f2c7)

**Comment by Angelk90** [comment]
@samermurad, @MrLoh, @andersondecarvalho : Boys I still can not understand why onMessage do not print me anything, can you give me a hand, tell me where I am wrong?
link: https://snack.expo.io/Bk1qZdDeG

**Comment by zecaptus** [comment]
To be honest, I can't understand why you didn't have our RedScreen :/ maybe it's specific to create-react-native-app ?!

**Comment by Angelk90** [comment]
@zecaptus: RedScreen? What do you mean?

**Comment by samermurad** [comment]
@Angelk90 honestly I can't really tell, I mean you are pointing the url to facebook's website, I use the onMessage with [react-native-webview-invoke](https://github.com/pinqy520/react-native-webview-invoke) to create a bridge between react native and native JS (i.e: I have a webview that loads a local html file which then loads a native JS script where I do my own BL), I don't know when or if facebook ever uses the postMessage function in their implementations, what are you trying to achieve?

**Comment by Benorb** [comment]
Sombody has a real solution?
i want to do this: window.postMessage(document.cookie)
and im stuck with this error..
How can i solve it?

**Comment by zecaptus** [comment]
You can probably solving this by ejecting your app from create-react-native-app and removing redscreen dependency. Btw I think this error shouldn't thrown in a production env.

**Comment by rodrijuarez** [comment]
Also having the same problem in iOS, this problem isn't present in Android though. Hope this is fixed soon so we don't have to go through this kind of workarounds (that could cause some other problems)

**Comment by jeveloper** [comment]
@Benorb  Hey, i've had the same issue. I read the source code and when running in dev mode , RN will throw an error but even if you dismiss and your webview will be operational, the app is messed up. Unfortunately you can test this by running in release mode and then you won't see the error. @zecaptus  Sorry but your comment is incorrect. This is based on Macro code on Objective C that will invoke this, nothing to do with the web site itself.

**Comment by rodrijuarez** [comment]
Is this by any chance solved in a newer version of react-native ? Or is this just laying out here for about half year?

**Comment by jeveloper** [comment]
@rodrijuarez  Agreed to bring this up again. I wanted to say something but i am not entirely sure why in dev mode this is specifically throwing an error (maybe a warning would be enough) but maybe there is a reason. It's horrible for working on a solution and debugging.

**Comment by Angelk90** [comment]
You guys can publish your solutions, since days the solution I used is not working anymore, I do not understand the reason.

**Comment by xxsnakerxx** [comment]
I found workaround that works for me (RN 0.52)

Just add at the end of the `injectedScript`
```js 
window.postMessage = window.originalPostMessage || window.postMessage;
```

```js
const injectedScript = () => {
  window.postMessage(document.body.innerHTML);
  window.postMessage = window.originalPostMessage || window.postMessage;
}

<WebView
  source={source}
  injectedJavaScript={`(${String(injectedScript)})()`}
  onMessage={this._onMessage}
/>
```

**Comment by Angelk90** [comment]
@xxsnakerxx: Can I ask you if you could possibly make a working example of your code on Expo, in order to try it?

**Comment by Angelk90** [comment]
I use such a thing instead:
```
render() {
    const jsCode =`
        (function ready() {
          function whenRNPostMessageReady(cb) {
            if (postMessage.length === 1) cb();
            else setTimeout(function() { whenRNPostMessageReady(cb) }, 100);
          }
          whenRNPostMessageReady(function() {
            postMessage(document.getElementById('name').innerHTML);//*Reference
          });
        })();`;
    return (
      <View>
      {(this.state.url != "") && (
      <WebView
        source={{
        uri: this.state.url,
        }}
        onMessage={(evt)=>{
          this.setState({code: evt.nativeEvent.data});
        }}
        injectedJavaScript={jsCode}
        javaScriptEnabled
        style={{ flex: 1 }}
      />)}
      </View>
    );
  }
```

//*Reference
I do not understand why inside:
`           whenRNPostMessageReady (function () {
`

I can put only one line, for example:
`             postMessage (document.getElementById ( 'name'). innerHTML);
`
If I try to put more lines, example:
```
var c = document.getElementById ('name'). innerHTML;
  postMessage (c);
```

It stops working.

@xxsnakerxx : 
Could you check if the same thing happens to you too?

**Comment by tranduykhanh** [comment]
@MrLoh Confirm work on iOS! 👍

**Comment by zecaptus** [comment]
Finally I've found a workaround that works with browsing.

```JS
import React from 'react';
import { StyleSheet, WebView, View } from 'react-native';

const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace(
      'hasOwnProperty',
      'postMessage',
    );
  };

  window.postMessage = patchedPostMessage;
};

const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      laod: false,
    };
  }

  onMessage() {
    console.log('onmessage');
  }

  loadstart = () => this.setState({ load: false });

  loadend = () => this.setState({ load: true });

  render() {
    return (
      <View style={styles.container}>
        <WebView
          source={{
            uri:
              'https://www.google.com',
          }}
          style={{}}
          ref={c => (this.webView = c)}
          onLoadStart={this.loadstart}
          onLoadEnd={this.loadend}
          javaScriptEnabled
          injectedJavascript={patchPostMessageJsCode}
          onMessage={this.state.load ? this.onMessage : null}
          startInLoadingState={true}
          scalesPageToFit={true}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    bottom: 50,
    left: 0,
    right: 0,
  },
});
```

**Comment by knod** [comment]
@MrLoh: I know it's a bit rude to make this request here, but I've tried other avenues (searches, issues, discord, irc) and haven't been able to find a way to move forward. Would anyone be willing to come on to the irc channel (#reactnative) or discord and give me a few hints and tips? Maybe answer some questions? Same name there as on here. I don't think this is an appropriate place for a complex Q&A session, but my current code looks like this: https://pastebin.com/Epy9xSSn. I have a bouncer, so I'll get your message if you leave me one with my username in it. Let me know if you have a bouncer too or, if not, how else I can reach you/what time you'll be able to be on.

**Comment by JulianKingman** [comment]
So I read through this whole thread, and several related ones and I don't see any solution that actually works reliably... This comment seemed promising: https://github.com/facebook/react-native/pull/10941#issuecomment-338651134 but it doesn't seem to matter what I do to define or redefine `window.onMessage`, I get the error `a previous value was defined`. 

I'm just trying to get the window height, and pass it to react native to resize it. Here's my current script (that's failing):
```javascript
const patchPostMessageJsCode = `
(function ready() {
  var body = document.body,
  html = document.documentElement;
  var height = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight);
  (function resetPostMessage () {
    if(window.originalPostMessage != undefined) {
      window.postMessage = window.originalPostMessage || window.postMessage;
    }
  })();
  function postWhenReady(message) {
    if (!window.postMessage) {
      resetPostMessage();
      setTimeout(postWhenReady(message), 200);
    }
    window.postMessage(message);
  }
  postWhenReady(JSON.stringify({height: height}));
  (function checkHeight () {
    height = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight);
    postWhenReady(JSON.stringify({height: height, interval: true}));
    setTimeout(checkHeight, 500);
  }))();
  resetPostMessage();
})();`;
```
If I skip the asynchronous stuff, it's fine. It seems like postMessage is getting set by the page I'm loading at some time after initial load, and react native has a difficult time coping with it, no matter how many times I "reset" `window.postMessage`. Is there a foolproof way to use postMessage?

**Comment by morgsvodafone** [comment]
Can someone please explain to me the purpose of the following code snippet from @kyle-ilantzis ?

`(function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) { 
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() { 
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage'); 
  };

  window.postMessage = patchedPostMessage;
})();`

This is resolving the issue for me but i am unclear on what is actually happening. Why is this replacing the `toString()` method?

Any help very appreciated!

**Comment by Dmitrylolo** [comment]
Injecting a patched postMessage method did not work for me. Error is showing even when i comment it in node_modules/react-native/React/Views/RCTWebView.m

**Comment by Nachox07** [comment]
Same issue with this versions:
"react": "16.3.2",
"react-native": "0.55.4",

**Comment by Lie8466** [comment]
Try
`injectedJavaScript="window.RNPostMessage = window.postMessage;window.postMessage = String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');"`

Then use` window.RNPostMessag`

**Comment by schlaegerz** [comment]
No matter what I do, if I try to implement onMessage it breaks the website. 

I am trying to render a meteor app in the Webview, and it depends on postMessage just working normally. 

This would be solved if we could just override the name of the postMessage, like lettings us specify a namespace window.reactNative.postMessage or just change it to window.RNPostmessage it doesn't even need to be a default, but giving the option to change it would fix all these problems.

**Comment by stonecold123** [comment]
@jneuendorf 
You are right. I have a quill editor loaded in the WebView. The problem only occurs when the content contains a youtube video.

**Comment by Titozzz** [comment]
Hi there, we are migrating all the WebView issues to the new repository https://github.com/react-native-community/react-native-webview. Correct me if I'm wrong but this does not seem to happen with the new WKWebview implementation. If it does, feel free to open an issue directly on the new repository and link that issue to it!
Thanks,

**Comment by stonecold123** [comment]
@Titozzz 
I use `react-native-navigation` and `react-native-link` usually doesn't work on `MainApplication.java` for Android. 
Do I need to add the webview package to the `createAdditionalReactPackages()` method?  
I ran `react-native link react-native-webview` but there are no changes on the file.

**Comment by Titozzz** [comment]
@stonecold123 please open an issue on the new repo

**Comment by Titozzz** [comment]
@CharlesStover To goal of the community repo is to fix theses issues that were never fixed. The slimmening should allow everyone to move faster. We, of course, hope that expo will choose to add all the slimmening packages into their releases so that you don't have to depend on such workarounds

**Comment by AdamZaczek** [comment]
> injectedJavascript should instead be the following
> 
> ```js
> (function() {
>   var originalPostMessage = window.postMessage;
> 
>   var patchedPostMessage = function(message, targetOrigin, transfer) { 
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() { 
>     return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage'); 
>   };
> 
>   window.postMessage = patchedPostMessage;
> })();
> ```
> 
> And then it works! 😄
> 
> And if any one is interested, in my code instead of writing a giant string I did the following
> 
> ```js
> const patchPostMessageFunction = function() {
>   var originalPostMessage = window.postMessage;
> 
>   var patchedPostMessage = function(message, targetOrigin, transfer) { 
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() { 
>     return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
>   };
> 
>   window.postMessage = patchedPostMessage;
> };
> 
> const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';
> 
> ...
> 
> <WebView injectedJavaScript={patchPostMessageJsCode} />
> ```

You man are my hero! This is so simple and eloquent. It works for Expo 31 even when using iframes

**Comment by olegongit** [comment]
For me it helped to use 'useWebKit' prop on a WebView.

**Comment by princeTPG** [comment]
This issue will not occur is you use "useWebKit" prop of webview, that will use WK webview instead of UI webview in case of IOS.
But in case if you don't want to use WK webview, then below is the sample JS code that you can inject in you Webview with "injectedJavaScript" prop.

      `(function () {
          let originalPostMessage = window.postMessage;
          let patchedPostMessage = function(message, targetOrigin, transfer, ...other) { 
            originalPostMessage(message, targetOrigin, transfer, ...other);
          };

          patchedPostMessage.toString = function() { 
            return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
          };

          window.postMessage = patchedPostMessage;
        })()`

The above code did nothing just patched window.postMessage function, the above issue will not appear.

**Comment by Angelk90** [comment]
@AdamZaczek , @princeTPG : 


I can't get it to work properly, you can give an example that can work on https://snack.expo.io?

I did something like that, but it seems that it doesn't work anymore.

Code:

```
render() {
    const jsCodeOpenload = `
        (function ready() {
          function whenRNPostMessageReady(cb) {
            if (postMessage.length === 1) cb();
            else setTimeout(function() { whenRNPostMessageReady(cb) }, 100);
          }
          whenRNPostMessageReady(function() {
            postMessage(document.getElementById('olvideo_html5_api').innerHTML);
          });
        })();`;
    return (
      <View>
        {this.state.urlOpenload != '' && (
          <WebView
            source={{
              uri: this.state.urlOpenload,
            }}
            onMessage={evt => {
              this.setState({ code: evt.nativeEvent.data });
            }}
            injectedJavaScript={jsCodeOpenload}
            javaScriptEnabled
            style={{ flex: 1 }}
          />
        )}
      </View>
    );
  }
```

onMessage seems to receive nothing more, even if it worked before.

**Comment by TfADrama** [comment]
> This issue will not occur is you use "**useWebKit**" prop of webview, that will use WK webview instead of UI webview in case of IOS.
> But in case if you don't want to use WK webview, then below is the sample JS code that you can inject in you Webview with "**injectedJavaScript**" prop.
> 
> ```
>   `(function () {
>       let originalPostMessage = window.postMessage;
>       let patchedPostMessage = function(message, targetOrigin, transfer, ...other) { 
>         originalPostMessage(message, targetOrigin, transfer, ...other);
>       };
> 
>       patchedPostMessage.toString = function() { 
>         return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
>       };
> 
>       window.postMessage = patchedPostMessage;
>     })()`
> ```
> 
> The above code did nothing just patched window.postMessage function, the above issue will not appear.

The patched script makes my onMessage to be always called twice in iOS when i do a click event...
The useWebKit prop was the only way, at least for now...

**Comment by kenobi91** [comment]
If you still have this issue you can use code from above, to prevent this error like this:

`const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };

  window.postMessage = patchedPostMessage;
};`

Then you can append your own JS injection code like this:

`<WebView
       injectedJavaScript={'(' + String(patchPostMessageFunction) + ')();' + injectedJavaScript}/>`

This will prevent error from above but also this will prevent in some cases to use window.postMessage from your injected JS code. To go around this just wrap window.postMessage(msg) in timeout like this:
`
setTimeout(() => {
    window.postMessage(JSON.stringify(postMessage));
}, 100);
`

**Comment by Rafaell416** [comment]
> injectedJavascript should instead be the following
> 
> ```js
> (function() {
>   var originalPostMessage = window.postMessage;
> 
>   var patchedPostMessage = function(message, targetOrigin, transfer) { 
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() { 
>     return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage'); 
>   };
> 
>   window.postMessage = patchedPostMessage;
> })();
> ```
> 
> And then it works! 😄
> 
> And if any one is interested, in my code instead of writing a giant string I did the following
> 
> ```js
> const patchPostMessageFunction = function() {
>   var originalPostMessage = window.postMessage;
> 
>   var patchedPostMessage = function(message, targetOrigin, transfer) { 
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() { 
>     return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
>   };
> 
>   window.postMessage = patchedPostMessage;
> };
> 
> const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';
> 
> ...
> 
> <WebView injectedJavaScript={patchPostMessageJsCode} />
> ```

Awesome man, if you come to Colombia I'll invite u some Empanadas.

**Comment by kckunal2612** [comment]
> injectedJavascript should instead be the following
> 
> ```js
> (function() {
>   var originalPostMessage = window.postMessage;
> 
>   var patchedPostMessage = function(message, targetOrigin, transfer) { 
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() { 
>     return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage'); 
>   };
> 
>   window.postMessage = patchedPostMessage;
> })();
> ```
> 
> And then it works! 😄
> 
> And if any one is interested, in my code instead of writing a giant string I did the following
> 
> ```js
> const patchPostMessageFunction = function() {
>   var originalPostMessage = window.postMessage;
> 
>   var patchedPostMessage = function(message, targetOrigin, transfer) { 
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() { 
>     return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
>   };
> 
>   window.postMessage = patchedPostMessage;
> };
> 
> const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';
> 
> ...
> 
> <WebView injectedJavaScript={patchPostMessageJsCode} />
> ```

Is there an updated version of this answer which will work with the new version of react-native-webview ? I am unable to receive messages in onMessage() on both iOS and Android. :(

**Comment by kckunal2612** [comment]
> Is there an updated version of this answer which will work with the new version of react-native-webview ? I am unable to receive messages in onMessage() on both iOS and Android. :(

Answering my own question here for everyone else's reference -

(See - https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0)

```
// Apply fix for newer react-native-webview not supporting window.postMessage
const webViewFix = function() {
  window.postMessage = function(data) {
    window.ReactNativeWebView.postMessage(data);
  };
};
const windowPostMessageFix = '(' + String(webViewFix) + ')();';

const patchPostMessageFunction = function() {
  const originalPostMessage = window.postMessage;

  const patchedPostMessage = function(message, targetOrigin, transfer) {
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() {
    return String(Object.hasOwnProperty).replace(
      'hasOwnProperty',
      'postMessage',
    );
  };

  window.postMessage = patchedPostMessage;
};

const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';
```

Make sure you call windowPostMessageFix function first and then your second function -
```
<WebView
 injectedJavaScript={[
                windowPostMessageFix,
                patchPostMessageJsCode
              ].join('')}
```

I hope it helps ! Thanks !

**Comment by DevArenaCN** [comment]
> > Is there an updated version of this answer which will work with the new version of react-native-webview ? I am unable to receive messages in onMessage() on both iOS and Android. :(
> 
> Answering my own question here for everyone else's reference -
> 
> (See - https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0)
> 
> ```
> // Apply fix for newer react-native-webview not supporting window.postMessage
> const webViewFix = function() {
>   window.postMessage = function(data) {
>     window.ReactNativeWebView.postMessage(data);
>   };
> };
> const windowPostMessageFix = '(' + String(webViewFix) + ')();';
> 
> const patchPostMessageFunction = function() {
>   const originalPostMessage = window.postMessage;
> 
>   const patchedPostMessage = function(message, targetOrigin, transfer) {
>     originalPostMessage(message, targetOrigin, transfer);
>   };
> 
>   patchedPostMessage.toString = function() {
>     return String(Object.hasOwnProperty).replace(
>       'hasOwnProperty',
>       'postMessage',
>     );
>   };
> 
>   window.postMessage = patchedPostMessage;
> };
> 
> const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';
> ```
> 
> Make sure you call windowPostMessageFix function first and then your second function -
> 
> ```
> <WebView
>  injectedJavaScript={[
>                 windowPostMessageFix,
>                 patchPostMessageJsCode
>               ].join('')}
> ```
> 
> I hope it helps ! Thanks !

This did solve the issue with the red screen, but when I tried to post data back from my frontend code calling `window.postMessage('some stuff'. '*')` I got error `TypeError: undefined is not an object (evaluating 'window.ReactNativeWebView.postMessage')` Any ideas?
