### ISSUE TITLE
Can't properly render ReactRootView if it is inside Scrollable ViewGroup.

### ISSUE THREAD

**Issue by zikil** [facebook/react-native#11546]
### Description
After update android react native lib from `v0.24` to `v0.38` I'm experience bug with rendering `ReactRootView`. I'm trying to use `ReactRootView` as an item for `ListView`(or `RecyclerView`, I tried both). Specifically: `ReactRootView` is being rendered to slowly, method `onLayout` (from javascript code) is called too many times (instead of one) and it takes 2-3 sec. I created github project to show how to reproduce the bug - [Github page](https://github.com/zikil/ReactNativeReportBug)

### Reproduction
I have simple react view that I'm trying to show in the list view inside the android app:
```
export default class Sample_2 extends Component {
  render() {
    return (
      <View style={styles.container} onLayout={this.onLayout.bind(this)} >
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
  onLayout(e) {
    // here I'm sending (to the java code) new sizes for the item
    var dict = e.nativeEvent.layout;
    if (NativeModules.BridgeModule) {
      NativeModules.BridgeModule.onLayoutChanged(dict);
    }
  }
}
```

Then I compile local js and put bundle in the asset folder.  
`react-native bundle --platform android --dev true --entry-file index.android.js --bundle-output android/main.jsbundle`

Then I set local js bundle to the `reactInstanceManager` and then start `startReactApplication` for the view .
```
 ReactInstanceManager reactInstanceManager = ReactInstanceManager.builder()
                    .setApplication(getApplication())
                    .setBundleAssetName("main.jsbundle")
                    //.... you can see details in github project
  mReactRootView.startReactApplication(reactInstanceManager, "Sample_2", null);
```
Result: huge delay in rendering.
Is there any additional API that I'm not aware of that will help to fix that or does anybody have smart idea how to avoid that? 
P.S. I know that this is not very good idea to use `ReactRootView` for `ListView` item, but currently I have to stick with that approach. 
P.P.S. IOS react native libs works properly and method `onLayout` is called only once.

**Update:**
Recently I discovered new bug. Application is crashing while it is trying to update `ReactRootView`with properties(again,  `ReactRootView` is an item of `RecyclerView/ListView`). I guess it can be related to the first issue. I updated github repo, to reproduce the bug - launch second activity with `RecyclerView`.
 Stacktrace: 
```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'marginBottom' in shadow node of type: RCTText
at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:110)
at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:148)
at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)
at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:246)
at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:186)
at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:235)
....
```

**Comment by zikil** [comment]
@mkonicek any updates on this? Thanks in advance.

**Comment by fxkopp** [comment]
@zikil @mkonicek experiencing the same issue

**Comment by anthonytheunissen** [comment]
Any Update on this issue? We are kinda stuck and need a solution urgently. Thanks in advance!

**Comment by fxkopp** [comment]
@anthonytheunissen We fixed our issue. We had the same issue with line height because we used a Float value and lineHeight only accepts Integers. So parsing it solved the issue. So might you wann try this?

**Comment by zikil** [comment]
@fxkopp where exactly do you use float instead of integers?

**Comment by rachitwatts** [comment]
@zikil could you solve this issue? We are also experiencing this.
Also, I want to know how are you calculating the height of ReactRootView and when are you setting it, we have the same use case as you.

**Comment by nazar-kacharaba-perfectial** [comment]
@rachitwatts We have not solved this issue. However, newest react (we currently using `v0.43`) does better job on rendering react views, but still not that good as iOS framework does. We still have massive problems related to that. Answering your question, as you can see in the [source code](https://github.com/zikil/ReactNativeReportBug), we do that via js code, in `onLayout()` method([see](https://facebook.github.io/react-native/docs/view.html#onlayout) we call java code to update listview item height.

**Comment by zikil** [comment]
@rachitwatts We have not solved this issue. However, newest react (we currently using `v0.43`) does better job on rendering react views, but still not that good as iOS framework does. We still have massive problems related to that. Answering your question, as you can see in the [source code](https://github.com/zikil/ReactNativeReportBug), we do that via JS code, in `onLayout()` method ([see](https://facebook.github.io/react-native/docs/view.html#onlayout)) we call java code to update `ListView` item height.

**Comment by hslls** [comment]
@fxkopp @anthonytheunissen @rachitwatts My solution for ReactRootView as ListView item, but there is a delay too. Is there a better solution?
```Java
        final ReactRootView rrv = new ReactRootView(mContext);
        ViewTreeObserver vto = rrv.getViewTreeObserver();
        vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {

            @Override
            public void onGlobalLayout() {
                int childCount = rrv.getChildCount();
                if (childCount > 0) {
                    View childView = rrv.getChildAt(0);
                    final AbsListView.LayoutParams params = (AbsListView.LayoutParams) rrv.getLayoutParams();
                    params.height = childView.getHeight();
                    if (params.height > 0) {
                        ViewTreeObserver obs = rrv.getViewTreeObserver();
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                            obs.removeOnGlobalLayoutListener(this);
                        } else {
                            obs.removeGlobalOnLayoutListener(this);
                        }
                    } else {
                        int adjustDP;
                        Object tag = rrv.getTag();
                        if (tag instanceof Integer) {
                            adjustDP = (Integer) tag;
                        } else {
                            adjustDP = 0;
                        }
                        params.height = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, ++adjustDP, mContext.getResources().getDisplayMetrics());
                        rrv.setTag(adjustDP);
                        rrv.setLayoutParams(params);
                    }
                }
            }

        });
        int initDP = 1;
        rrv.setTag(initDP);
        int height = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, initDP, mContext.getResources().getDisplayMetrics());
        AbsListView.LayoutParams lp = new AbsListView.LayoutParams(AbsListView.LayoutParams.MATCH_PARENT, height);
        rrv.setLayoutParams(lp);
        rrv.startReactApplication(mReactInstanceManager, "HelloWorld", null);
        return rrv;
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/cant-properly-render-reactrootview-if-it-is-inside-scrollable-viewgroup
