### ISSUE TITLE
<View> borderRadius / border[Left|Top|Bottom|Right]Color not works together @ Android

### ISSUE THREAD

**Issue by code-by** [facebook/react-native#12403]
### Description

I'd like to make a View with different colors for each side (with border{Side}width: 1) and add borderRadius.
But when I use borderRadius and border{Side}Color this not works together at Android.

### Reproduction

https://rnplay.org/apps/8dV5AA

**Comment by matthamil** [comment]
I'm experiencing the same issue. I can't seem to have two sides of the same `<View>` set to two different colors, AND set different border radiuses on different corners. When I try to have the top border color set to gray and the left border color set to blue AND have a border top left radius AND a border bottom left radius I get a gray border on all sides of my `<View>` like so:

![image](https://cloud.githubusercontent.com/assets/11802078/23142976/6004e6dc-f784-11e6-926d-f4ffa0c55623.png)

**Comment by Swordsman-Inaction** [comment]
I checked the source code([here](https://github.com/facebook/react-native/blame/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L249)), the border won't be drawn if borders are not fully set(all four borders) when the `radius` is set. But I don't know why...  @janicduplessis do you have any idea?

**Comment by SuhairZain** [comment]
Having the same issue here. Have you found any workarounds?

**Comment by rahuljiresal** [comment]
This looks like a regression. It was fixed here https://github.com/facebook/react-native/issues/5411

**Comment by janicduplessis** [comment]
@rahuljiresal The issue you linked seems to be a different problem, I tried the example in it and it did work so I don't think it's a regression.

Not sure what the issue is but I reproduced it easily in snack, it does work on iOS but not android.
https://snack.expo.io/ry1VDvZ6x

**Comment by rahuljiresal** [comment]
@janicduplessis Yes you're right. However, as soon as you add `borderRadius` to the styling of the triangle, it disappears. Try the following style with and without the borderRadius

```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var SampleApp = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <View style={styles.triangle}/>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  triangle: {
        overflow: 'hidden',
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 100,
        borderTopWidth: 100,
        borderLeftColor: 'transparent',
        borderTopColor: 'red',
        // borderRadius: 10
    }
   },
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
      
```

**Comment by AnyGong** [comment]
+1 me too!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kirillpisarev** [comment]
I don't know is it related or not but `border[Top|Right|Bottom|Left]Width` breaks border on android if `borderRadius` property is also set
https://snack.expo.io/BkQrD4IUZ

**Comment by 349989153** [comment]
This issue can be reproduced on android if you use `borderRadius` and `border[Left|Top|Bottom|Right]Width`
together,  `border[Left|Top|Bottom|Right]Color` has nothing to do with it.

Test with RN 0.47.2

**Comment by akademy** [comment]
I'm encountering this issue now. This is a bug only on Android,  works fine on iOS - I can only add a bottomBorder if borderRadius is 0. I'm using RN 0.46.4. (I can add a border to all sides at once though)

**Comment by MrSpeedR** [comment]
I have got same issue on Android when use borderRadius or border[TopLeft...]Radius with border[Left|Top|Bottom|Right]Width

**Comment by lucascavalheiro** [comment]
Same issue here. I'm using RN 0.47.2

**Comment by duwaynevandort** [comment]
Same issue on RN 0.48.4. Adding a borderRadius with border[Left|Top|Bottom|Right]Width causes the border to not render.

**Comment by duncan-iaria** [comment]
Same issue here, also RN 0.48.4

**Comment by gregblass** [comment]
My current workaround for cards with top borders until this is addressed:

https://snack.expo.io/@gregblass/border-radius-top-border-android-workaround

**Comment by gregblass** [comment]
I had to post here one more time to say that in my opinion, this should really be taken out of the icebox. With material design cards being common on Android (which have a 2px border radius), card links/panels/dividers with borders disappear, and it becomes a huge pain. I've spent 5+ hours today dealing with this with workarounds like passing first/last props to components due to this.

If the issue is a challenging one - so be it - but it surely should not be ice boxed!

**Comment by shergin** [comment]
cc @rsnara

**Comment by rsnara** [comment]
Up until yesterday, React Native actually didn't support border(Top|Left|Right|Bottom)(Color|Width) With rounded borders. So it wasn't a bug, more just a feature that hadn't yet been implemented. 

I just merged a few commits into master to implement this feature yesterday.

**Comment by luco** [comment]
@rsnara Is the master already synced with npm?

**Comment by porluz** [comment]
I'm seeing this issue  with
"react": "16.0.0",    
"react-native": "0.50.3".

Once I add a border[L/T/R/B] Radius to border[L/T/R/B]Width, the border disappears

**Comment by chawkibenalaya** [comment]
borderBottomLeftRadius: number
borderBottomRightRadius: number
borderTopLeftRadius: number
borderTopRightRadius: number
This worked for me

**Comment by kevinzhangftw** [comment]
Hey , i tried that. still doesnt work :(
listItemStyle:{
    borderWidth: 0.5,
    borderBottomWidth: 1,
    borderLeftColor: '#008000',
    borderLeftWidth: 10,
    backgroundColor: 'white',
    borderColor: '#DCDCDC',
    // borderRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },

**Comment by kevinzhangftw** [comment]
ok i got it to work. for future people, u must explictly set each border edge and radius!

```
listItemStyle:{
    borderWidth: 0.5,
    borderBottomWidth: 1,
    // borderLeftColor: '#008000',
    borderLeftWidth: 10,
    backgroundColor: 'white',
    // borderColor: '#DCDCDC',
    // borderRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderTopColor: '#DCDCDC',
    borderBottomColor: '#DCDCDC',
    borderLeftColor: '#008000',
    borderRightColor: '#DCDCDC',
  },
```

**Comment by cristianonescu** [comment]
works only on android......
