### ISSUE TITLE
[FlatList] on new batch (items) render list bounces few px

### ISSUE THREAD

**Issue by grundmanise** [facebook/react-native#12722]
I've just recreated `FlatListExample` where `renderItem` has `Image` with `uri` & `Icon` from `react-native-vector-icons`, when scrolling the list I can see that sometimes it bounces few px. Am I the only one who experience this issue?

**Comment by grundmanise** [comment]
You can see this bouncing well when you scroll very fast to the bottom (I've got 500 items) and after that you scroll up with a smaller velocity

**Comment by mnkang89** [comment]
I have the same problem!!

**Comment by mnkang89** [comment]
Because my contents have fixed heihgt, I had used my own getItemLayout function to skip measurement of content height. like below

const ITEM_HEIGHT = 368
getItemLayout={(data, index) => (
  {length: ITEM_HEIGHT, offset: ITEM_HEIGHT * index, index}
)}

but I felt I gave wrong ITEM_HEIGHT to it. so i deleted my own getItemLayout implementation in FlatList option then i fixed the 'few pixels bouncing' problem. for your understanding I fixed it like below.

*Before(I implemented my own _getItemLayout method to minimize measurement calculation)
  <FlatListE
          style={{ flex: 1 }}
          ref={this._captureRef}
          ....
          getItemLayout={this._getItemLayout} 
          data={this.props.items} />

*After(I just used deleted my own getItemLayout method and used default implementation)
  <FlatListE
          style={{ flex: 1 }}
          ref={this._captureRef}
          ....
          data={this.props.items} />

I hope this helps you~

**Comment by grundmanise** [comment]
@mnkang89 thanks for sharing. I also used `getItemLayout`, without `getItemLayout` not a whole list is scrollable, it appends list items as you scroll.

**Comment by AntAreS24** [comment]
Still happening to me on Android. I'm using RN 0.44.1

I tried even without rendering my items (I'm simply using <Text>{item.body}</Text>) but the bouncing still occurs.

I noticed that when this happens, it's the equivalent of the native pull up/down to refresh. Sometime, I can even see it (semi transparent arc from left to right of the screen). I put some logs in the code and I can see that the scroll value goes below 0, which causes this behaviour. I wonder if it's related to the https://developer.android.com/reference/android/widget/ListView.html#setOverscrollHeader(android.graphics.drawable.Drawable) functionality...

Haven't found a way to fix this yet.

**Comment by netdown** [comment]
Still experiencing on RN57. Also happens with initialScrollIndex, [#e0c7363](https://github.com/facebook/react-native/commit/e0c7363) did not fix. Now I may have tried all option-combinations, doesn't seem to be a solution (except removing getItemLayout) without some bugfix. Notable that only happens with relatively bigger lists (like 20-30 elements). My list has a component which includes Image components, not related to vector.

**Comment by hramos** [comment]
Please open a new issue - comments on closed issues rarely lead to a solution. Thanks!
