### ISSUE TITLE
[Android] TextInput doesn't scroll properly when restricting the height on an expanding TextInput

### ISSUE THREAD

**Issue by jonasb** [facebook/react-native#12799]
### Description

I'm creating a InputText where I want to restrict the height to a maximum. When I do it the TextInput doesn't automatically scroll when I write enough to add another line of text. That means I have to manually scroll down to see what I'm typing.

* It works on iOS as expected
* It works as expected if I'm setting a fixed height (`style={{height: 200}}`)
* It works as expected if I don't restrict the height (`style={{ height: Math.max(35, this.state.height) }}`)

### Reproduction

```
class AutoExpandingTextInput extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            text: 'React Native enables you to build world-class application experiences on native platforms using a consistent developer experience based on JavaScript and React. The focus of React Native is on developer efficiency across all the platforms you care about — learn once, write anywhere. Facebook uses React Native in multiple production apps and will continue investing in React Native.',
            height: 0,
        };
    }
    render() {
        return (
            <TextInput
                {...this.props}
                multiline={true}
                onChange={(event) => {
                    // onContentSizeChange doesn't work on Android, use onChange instead https://github.com/facebook/react-native/issues/11692
                    this.setState({ height: event.nativeEvent.contentSize.height });
                }}
                onContentSizeChange={(event) => {
                    this.setState({ height: event.nativeEvent.contentSize.height });
                }}
                onChangeText={(text) => {
                    this.setState({ text });
                }}
                style={{ height: Math.min(200, Math.max(35, this.state.height)) }}
                value={this.state.text}
            />
        );
    }
}
```

### Solution

?

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System: MacOS

**Comment by stoffern** [comment]
https://github.com/facebook/react-native/issues/11692#issuecomment-274564452

**Comment by Palisand** [comment]
@jonasb @shergin This is also happening on RN 0.46.1. Simply including 
``` javascript
onContentSizeChange={() => {}}
```
is enough to cause what appears to be **disabling automatic scrolling**, even on inputs of fixed height!

**Comment by kkotelczuk** [comment]
I have the same issue in RN 0.46.4

**Comment by Palisand** [comment]
@shergin (in response to 😕 ) Try out this snack on an android device: https://snack.expo.io/BkhOoGtLZ. I used a Galaxy S6.

**Comment by richchurcher** [comment]
Confirmed on RN 0.46.4, with:
```
  handleContentSizeChange = ({ nativeEvent }) => {
    const { height } = nativeEvent.contentSize
    this.setState({
      inputHeight: height > MAX_INPUT_HEIGHT ? MAX_INPUT_HEIGHT : height
    })
  }

  render () {
    return <View>
      <TextInput
        onContentSizeChange={this.handleContentSizeChange}
        style={ height: this.state.inputHeight } />
    </View>
  }
```

**Comment by teyou** [comment]
confirmed ios doesn't have this issue only android

**Comment by guysegal** [comment]
any progress on this issue?

**Comment by stoffern** [comment]
@guysegal use workaround as posted

**Comment by shergin** [comment]
Yes, I am still working on this.

**Comment by guysegal** [comment]
@stoffern which workaround are you referring to? I didn't find a workaround for the case where max height is defined

**Comment by JaxGit** [comment]
This bug wasn't happening when we were using RN 0.38.0, should be some changes afterwards

**Comment by huanghaodong** [comment]
I have the same issue in RN 0.48.3

**Comment by kesiena115** [comment]
I extended [react-native-autogrow-input](https://github.com/ivpusic/react-native-autogrow-input) to create a Component that works for me (I've only tested this on Android). This is a messy hack because I use two TextInput. The user sees only one of them. The hidden TextInput handles onContentSizeChange() while the visible one receives user input, grows & scrolls appropriately. The two TextInput communicate with each other via the component state. The component requires two props: `minHeight` and `maxHeight`. Feel free to customize this for your use case or let me know if you have a better solution.

```
import React, { PureComponent } from 'react';
import { TextInput, View } from 'react-native';

import PropTypes from 'prop-types';

export default class AutoGrowInput extends PureComponent {

  componentWillMount() {
    this.setState({
      height: this.props.minHeight,
      inputValue: '',
    });
  }

  onContentSizeChange = (event) => {
    const { minHeight, maxHeight } = this.props;
    // Adding 30 to provide extra padding.
    let inputHeight = Math.max(minHeight, event.nativeEvent.contentSize.height + 30);
    if (inputHeight > maxHeight) {
      inputHeight = maxHeight;
    }
    if (this.state.height !== inputHeight) {
      this.setState({
        height: inputHeight,
      });
    }
  }

  clear = () => {
    if (this.inputRef) {
      this.inputRef.setNativeProps({ text: '' });
      this.setState({
        height: this.props.minHeight,
        inputValue: '',
      });
    }
  }

  value = () => {
    return this.state.inputValue;
  }

  focus = () => {
    if (this.inputRef && this.inputRef.focus) {
      this.inputRef.focus();
    }
  }

  render() {
    return (
      <View
        style={{
          flex: 1,
          marginTop: 5,
          marginBottom: 10,
          height: this.state.height,
          alignSelf: 'stretch',
          padding: 0,
        }}
      >
        {/*
        This is the TextInput the user sees. It does not have onContentSizeChange(), so it
        scrolls as expected. It receives the user input and stores it as this.state.inputValue
        */}
        <TextInput
          ref={ref => this.inputRef = ref}
          multiline
          {...this.props}
          style={[this.props.style, { height: this.state.height }]}
          onChangeText={val => this.setState({ inputValue: val })}
          value={this.state.inputValue}
        />
        {/*
        This is a hidden TextInput that the user does not see. It uses onContentSizeChange() to
        calculate the height of the input the user sees. It receives the user's input from
        this.state.inputValue.
        */}
        <TextInput
          multiline
          style={{ height: 0, margin: 0, padding: 0 }}
          onContentSizeChange={this.onContentSizeChange}
          value={this.state.inputValue}
        />
      </View>
    );
  }
}

AutoGrowInput.propTypes = {
  style: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.array,
    PropTypes.object,
  ]),
  minHeight: PropTypes.number,
  maxHeight: PropTypes.number,
};

```

**Comment by lukecwilliams** [comment]
I only get the textbox to grow on an `<Enter>` press.  A long line that wraps several times always returns a height of 14; only after pressing `<Enter>` I get a height of 24 (then 42, etc.)

How can we get autogrowing to work with wrapping?  I'm using the exact example from @jonasb at the top of this thread.

**Comment by konradkierus** [comment]
This issue also exists with RN 0.49.0 with 'autoGrow' option and 'maxHeight' property set to imitate the same behavior as with using onContentSizeChange which shouldn't surprise as internally auto-growing features uses onContentSizeChange.

**Comment by joncursi** [comment]
Same issue here. I was able to work around this by setting `onContentSizeChange` to `undefined` on Android, and specifying a fixed height through the `style` prop on Android as well. I only apply these changes on Android via `Platform.OS === 'android' ? A : B`.

Hoping for a fix sometime soon, my TextInput component is looking pretty nasty with all of these if/else workarounds for Android lately.

**Comment by shergin** [comment]
Hey there,
It will not fix this particular issue, but look at this: c550f27a4e82402b966567d7b79a8b1f1d1491a5.
TextInput on Android has dynamic intrinsic content size now, similarly to iOS. It basically makes `autoGrow` deprecated.

However, I still don't know how to fix this issue. 😢

**Comment by joncursi** [comment]
[My workaround](https://github.com/facebook/react-native/issues/12799#issuecomment-334199622) no longer works in RN 0.49.1.  😢

**Comment by enahum** [comment]
having the same issue for RN 0.49.1 :S

**Comment by Palisand** [comment]
RN 0.49.1 - Android

Now automatic scrolling for `TextInput` doesn't work **AT ALL**. I was able to, at some point, observe auto scrolling when setting a fixed height as @jonasb has stated. Now that's gone! Can any one else confirm?

**Comment by joncursi** [comment]
@Palisand I can confirm [100%](https://github.com/facebook/react-native/issues/12799#issuecomment-334537094).

**Comment by Palisand** [comment]
I remember a time (around [this commit](https://github.com/facebook/react-native/commit/481f560f64806ba3324cf722d6bf8c3f36ac74a5) change) where everything on Android was working as expected: auto-expand, cursor tracking, the whole lot. Now it seems multiline inputs were the amount of text is expected to exceed the height is pretty much useless. What happened?! 😭

**Comment by Palisand** [comment]
@shergin I have taken a look at your changes c550f27a4e82402b966567d7b79a8b1f1d1491a5 on the RNTester app. **Is there a way to get the screen to scroll to the line where the cursor is located (rather than having the user manually scroll)?** This was done automatically in an earlier version of react-native, ~0.46 if I remember correctly.

Also, what is the problem you are facing exactly when trying to get auto-scrolling working again?

**Comment by shergin** [comment]
@Palisand Well, I just tried to fix/enable it, but I failed. So, yes, the current state is: layout is working, scrolling is not (and I don't know how to fix that, yet).
But, it should be (easy) fixable. 😂

**Comment by Palisand** [comment]
I was specifically referring to the scrolling of a parent view of a growable TextInput rather than the input itself. It's good to hear that you think the latter should be easily fixable as this is pretty critical functionality. I personally don't even know where to begin making changes to get this working (`ReactTextInputManager.java`, `ReactTextEdit.java`?).

**Comment by konradkierus** [comment]
@shergin @Palisand I've tracked the issue basing on RN 0.49-stable branch and this is a guilty method: https://github.com/facebook/react-native/blob/0.49-stable/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L121

I've created my own implementation of ReactEditText which looks like this:
```java
public class CustomTextInput extends ReactEditText {
    public CustomTextInput(Context context) {
        super(context);
    }

    @Override
    public boolean isLayoutRequested() {
        return false;
    }
}
```
Then I've overrided ReactTextInputManager like this:
```java
public class CustomTextInputManager extends ReactTextInputManager {

    @Override
    public String getName() {
        return "CustomTextInput";
    }

    @Override
    public CustomTextInput createViewInstance(ThemedReactContext context) {
        CustomTextInput editText = new CustomTextInput(context);
        int inputType = editText.getInputType();
        editText.setInputType(inputType & (~InputType.TYPE_TEXT_FLAG_MULTI_LINE));
        editText.setReturnKeyType("done");
        editText.setTextSize(
                TypedValue.COMPLEX_UNIT_PX,
                (int) Math.ceil(PixelUtil.toPixelFromSP(ViewDefaults.FONT_SIZE_SP)));
        return editText;
    }
}
```
and then I've copy-pasted the TextInput class and put my CustomTextInput here https://github.com/facebook/react-native/blob/0.49-stable/Libraries/Components/TextInput/TextInput.js#L42

And the issue is gone!

This is surely a pretty short workaround but it may require proper implementation and testing on master RN branch. I'm not sure why someone would not want the automatic scroll on the TextInput so I don't know what is the purpose of the original implementation and which use cases it handles. I thought that maybe setting initial very long text on TextInput with restricted height would cause the TextInput to be scrolled to the bottom but no, it didn't break this behavior.

**Comment by Palisand** [comment]
@konradkierus @shergin Just tested this by changing `ReactEditText` directly. This solves **both** scrolling issues and saved me from continuing down the dark path of using the cursor's y position. However, it might lead to some unintended behavior with `onContentSizeChange` (see [this commit](https://github.com/facebook/react-native/commit/2537157d994ac83f53a5ebc6ba5d74a9ad41f0c2#diff-457fd2ba359cc6fbb0c471516e279696R106)).

**Comment by shukerullah** [comment]
I am facing this textInput multiline issue for my last two projects.

It really is painful that the such basic needs are being ignored in `React Native` such as navigation, which is not really solved yet after two years. Nested Scroll (Android) is another example.

**Comment by stoffern** [comment]
I dont quite get what your problems are.
`React Native` is supposed to be a **framework/core** rather than "the complete package"
Navigation, swipe functions, etc should be extentions or seperate repos, in FB`s and also my opinion.

The textInput problem can easily be solved.

You should not use `onContentSizeChange` for this, rather use `onChange`
```js
onChange={event => {
  this.setState({
    height: event.nativeEvent.contentSize.height
  });
}}
```

**Comment by enahum** [comment]
@stoffern what would that accomplish?

Set a textInput to have a maxHeight start typinh on it and see how it wont auto scroll as you enter new lines

**Comment by Palisand** [comment]
@shukerullah After @shergin's changes, `TextInput`s for both iOS and Android have an intrinsic size. You do not need to use `onContentSizeChange` or `autoGrow` to control input size anymore if you're on master; try out the RNTester app and rejoice! To restore Android's cursor-following / auto-scrolling, you need to use @konradkierus's changes which, at the very least, involve always having `ReactEditText`'s `isLayoutRequested` method always return `false`. To add cursor-following to iOS it is a little more involved if you want to use my method (see my previous comment), but you also have the option of using @baijunjie's [react-native-input-scroll-view](https://github.com/baijunjie/react-native-input-scroll-view).

**Comment by stoffern** [comment]
@Palisand great comment, thanks for the heads up! 
Did not see that commit, i was on a old version 😉

**Comment by guysegal** [comment]
So basically in the next release (0.50 or maybe 0.51) it will work as expected, right?

**Comment by peterlazar1993** [comment]
@Palisand Is a fix for this already on master?
Basically I'm trying to reproduce the same behvaviour as iOS on Android.
![textinput](https://user-images.githubusercontent.com/4848554/32414950-2ae482de-c257-11e7-89b5-0051e8b03d9e.gif)

**Comment by LEEY19** [comment]
hi @konradkierus , why does it not work when I simply just change the existing isLayoutRequested method in `ReactEditText.java` file to always return false?

**Comment by konradkierus** [comment]
@LEEY19 Because otherwise it would break the following use case: if you set initial long text on TextInput with restricted height then TextInput would be already scrolled to the bottom. If you don't need to provide default value for the TextInput then you're fine with returning false all the time.
You can read more explanations on the issue if you read my previous post https://github.com/facebook/react-native/issues/12799#issuecomment-335082550 from top to the bottom.

**Comment by LEEY19** [comment]
@konradkierus Thanks for your swift reply. I actually tried just changing isLayoutRequested to always return false but the auto scrolling issue wasn't solved. If all I want is to get the auto scrolling on Android work on a TextInput that has a set maxHeight until a point, how do I do that? 

I tried following your steps in implementing both `CustomTextInputManager` and `CustomTextInput` classes. And then in TextInput.js, I did this:
```
if (Platform.OS === 'android') {
  var AndroidTextInput = requireNativeComponent('CustomTextInput', null);
} else if (Platform.OS === 'ios') {
  var RCTTextView = requireNativeComponent('RCTTextView', null);
  var RCTTextField = requireNativeComponent('RCTTextField', null);
}
```

It would not work. What did I do wrong?

**Comment by konradkierus** [comment]
@LEEY19 I'm not sure what you did wrong. Did you build RN from source? I wasn't doing this, just tried t  o make the workaround without building RN from the master branch. Also, please note that I was testing this on RN 0.49, didn't have opportunity yet to check the behavior on RN 0.50 which consist changes to TextInput's height calculations (https://github.com/facebook/react-native/commit/c550f27a4e82402b966567d7b79a8b1f1d1491a5)

**Comment by LEEY19** [comment]
@konradkierus nope I did not build RN from source. I am testing on 0.47.1. Maybe that could be the reason..

To refresh for the changes, you would just run `react-native run-android` right?

**Comment by konradkierus** [comment]
@LEEY19 Make sure to register the CustomTextInputManager in your createViewManagers method. You can read about the procedure here: https://facebook.github.io/react-native/docs/native-modules-android.html#register-the-module
Also, I'm not sure where did you change the below line but if you're unsure if it worked then change the 'CustomTextInput' to something else like 'SomethingElse'. If the app doesn't produce an error then you did something wrong.
```
var AndroidTextInput = requireNativeComponent('CustomTextInput', null);
```

**Comment by EsdrasEtrenne** [comment]
+1

having this issue as well. 
I am using expo version 22.0 

for react native in my package.json i have:

`"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",`

which is react native version 49.3 and the auto scrolling is broken.

**Comment by yasir-netlinks** [comment]
+1

Having the same issue with `maxHeight` set

**Comment by dead23angel** [comment]
+1
using 0.47.1
solution and did not find, but it is very necessary, if you do not use onContentSizeChange that field does not increase

**Comment by LEEY19** [comment]
@konradkierus Sorry for requesting for help again, I have zero knowledge on Java.. When you override the `ReactEditText` and `ReactTextInputManager`, did you just place the new public classes in the respective original files? 

Also when it comes to registering the module, where do I place the java file? The `CustomTextInput` module does not seem to be registered and it cannot be fetched in the MainApplication.java file. Its not mentioned here https://facebook.github.io/react-native/docs/native-modules-android.html#register-the-module as well, on where I should be placing the module-registering file

**Comment by konradkierus** [comment]
@LEEY19 read this https://facebook.github.io/react-native/docs/native-components-android.html Previously I gave you a link to writing a custom module, this link shows how to implement custom component (extending view managers). If you still won't know how to properly do it then please ask for help in StackOveflow to not spam here.

**Comment by EsdrasEtrenne** [comment]
React Native 50.0 is out, is this fixed for anyone?

**Comment by joncursi** [comment]
Still there for me as well on 0.50.3

**Comment by EsdrasEtrenne** [comment]
On >=50.0 it does at least work as long as you do not have a height set. Which I guess is a bit of a win

**Comment by EsdrasEtrenne** [comment]
I found a solution that works for my purposes so figured I'd share

https://snack.expo.io/r1y4tXVxz

```
import React, { Component } from 'react';
import {
  StyleSheet,
  TextInput,
  View,
  ScrollView,
  KeyboardAvoidingView
} from 'react-native';

export default class App extends Component {

  state = {
      text: '',
  };

  render() {
    return (
      <KeyboardAvoidingView
        behavior = "position"
        keyboardVerticalOffset= {80}
        keyboardDismissMode = "on-drag"
      >
        <View
        style ={{height:500, backgroundColor: "blue"}}
        />
        <ScrollView
          ref={(scroll) => {this.scroll = scroll;}}
          onContentSizeChange = {() => {this.scroll.scrollToEnd({animated: true})}}
          style = {{height:80}}
        >
            <TextInput
              blurOnSubmit = {false}
              multiline = {true}
              style={styles.text}
              onChangeText={text => this.setState({ text })}
              onContentSizeChange={this._onContentSizeChange}
              placeholder={"Start Typing..."}
            />
        </ScrollView>
      </KeyboardAvoidingView>
    );
  }
}

const styles = StyleSheet.create({
  text: {
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
});
```

There are some nested ScrollViews since KeyboardAvoidingView is a ScrollView but it works pretty well as a workaround without having to do native code

**Comment by Lily418** [comment]
@EsdrasEtrenne I like this work around it definitely improves the issue I'm having. Although one thing to be aware of here is that if the text input gets very tall and the user starts editing in the middle then when the content size changes the scrolling to bottom will go too far so the part they were editing disappears.

**Comment by dead23angel** [comment]
@EsdrasEtrenne hi!
I'm using https://github.com/FaridSafi/react-native-gifted-chat .
Can you tell me how to fix this mistake in it?

**Comment by EsdrasEtrenne** [comment]
Hi @dead23angel I dont know about that. It could require fixing the actual library code?

Somebody pointed out a flaw in my code though so here is an updated version that works in case a user scrolls up and is editing part of the code:

https://snack.expo.io/r1e2R7Ylz
good for React Native >= 50.0


```

import React, { Component } from 'react';
import {
  StyleSheet,
  TextInput,
  View,
  ScrollView,
  KeyboardAvoidingView
} from 'react-native';

export default class App extends Component {

  state = {
      text: '',
      textYPosition: 0,
      textHeight: 0

  };

  updateScrollPosition(width, height){

    let yPositionDifference = (height - this.state.textHeight)
    let newYPosition = this.state.textYPosition + yPositionDifference

    console.log(width, height, newYPosition)
    this.scroll.scrollTo({x: 0, y: newYPosition, animated: false})

    this.setState({textHeight: height})
  }

  handleScroll(scrollEvent){
    let textYPosition = scrollEvent.nativeEvent.contentOffset.y
    this.setState({textYPosition})
  }
  render() {
    return (
      <KeyboardAvoidingView
        behavior = "position"
        keyboardVerticalOffset= {80}
        keyboardDismissMode = "on-drag"
      >
        <View
        style ={{height:500, backgroundColor: "blue"}}
        />
        <ScrollView
          ref={(scroll) => {this.scroll = scroll;}}
          onContentSizeChange = {(width, height) => this.updateScrollPosition(width, height)}
          style = {{height:80}}
          scrollEventThrottle = {1}
          onScroll = {nativeEvent => this.handleScroll(nativeEvent)}
        >
            <TextInput
              blurOnSubmit = {false}
              multiline = {true}
              style={styles.text}
              onChangeText={text => this.setState({ text })}
              placeholder={"Start Typing..."}
            />
        </ScrollView>
      </KeyboardAvoidingView>
    );
  }
}

const styles = StyleSheet.create({
  text: {
    marginBottom: 16,
    paddingHorizontal: 8,
  },
});

```
This is obviously pretty messy and I actually like the simplicity of @konradkierus version, but since I am using Expo for react native I do not have the luxury of using native code. It needs to be 100% javascript.

The key here is updating the component's state using the ScrollView's `onScroll` method to capture the new current `Y` position of the TextInput any time the scroll position changes.

After that, anytime the `onContentSizeChange` method is called we save the new content height to state. We also use the `scrollTo` method increment the current `Y` position by the difference of the new content height and the previous content height we saved in state.

**Comment by shergin** [comment]
0bef872f3fc8b1cd78c574d03eacc886bef4e239 should fix this.
If anyone can test it, I will appreciate that. 😄

**Comment by riryjs** [comment]
@shergin thank you, how can i implemented it in RN 48.2?
I have a huge code so I think i won't install new RN version since I have tried and too many configuration to re-setup.

**Comment by dead23angel** [comment]
@shergin 

It would be nice to make this commit to version 0.47, because I like the @riryjs code is great to update the packages

**Comment by jamesreggio** [comment]
@shergin, I've confirmed that this fixed the issue (by cherry-picking patch atop v0.50.3). Thanks!

**Comment by ide** [comment]
FYI - we've cherry-picked this into 0.51-stable (RC with this patch still not released but it will go out with the final 0.51.0 release assuming it's not reverted).

**Comment by EsdrasEtrenne** [comment]
seriously @shergin thank you so so much. This is such a save!

**Comment by mannol** [comment]
@ide Any idea when the 0.51 will be released?
@jamesreggio Any idea how to cherrypick this commit into a project initialized with react-native init (react-native-git-upgrade doesn't work with 0.51.0-rc.3 which should have this commit)?

Thanks!

**Comment by jamesreggio** [comment]
Hey @mannol, cherry-picking Android fixes is a fairly involved process because you first need to setup your project to [build Android from source](https://github.com/facebook/react-native/blob/master/docs/android-building-from-source.md). It's been a long time since I set up the Android build in my project, but all I remember is that it took a while to get working.

If you are building Android from source, the fastest way to 'cherry-pick' is to actually just copy/paste the changes to `ReactEditText.java` from [this commit](https://github.com/facebook/react-native/commit/2d88b6374731951e625da75938d353328559f308) into your `node_modules` directory, and then use a tool like [patch-package](https://github.com/ds300/patch-package) to preserve the changes across `yarn`/`npm install`s.

**Comment by ide** [comment]
0.51 is planned to be released sometime today (though unexpected things can happen, so give it a few extra days of buffer room).

**Comment by shergin** [comment]
❤️

**Comment by xcarpentier** [comment]
I see it's fixed in 0.52 instead: https://github.com/facebook/react-native/commit/0bef872

**Comment by thambt** [comment]
Hi,
it fixed in Android. but i see it in IOS. 
i'm in R.N 0.54.0

**Comment by elgrones** [comment]
Still there for me as well on 0.50.4
