### ISSUE TITLE
`react-native link` corrupts `project.pbxproj` file

### ISSUE THREAD

**Issue by dylanpyle** [facebook/react-native#12959]
### Description

Starting from a working project, recently upgraded to React Native 0.42.0. Following the instructions at https://developers.facebook.com/docs/react-native/getting-started

```
$ react-native install react-native-fbsdk
Scanning 646 folders for symlinks in /Users/dylan/dev/cala/ios/node_modules (6ms)
calaRN@1.2.68 /Users/dylan/dev/cala/ios
└── react-native-fbsdk@0.5.0

Scanning 647 folders for symlinks in /Users/dylan/dev/cala/ios/node_modules (5ms)
rnpm-install info Linking react-native-fbsdk ios dependency
rnpm-install info iOS module react-native-fbsdk has been successfully linked
rnpm-install info Module react-native-fbsdk has been successfully installed & linked
```

```
$ react-native link react-native-fbsdk
Scanning 647 folders for symlinks in /Users/dylan/dev/cala/ios/node_modules (6ms)
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/*" or ";" but "\"" found.
```

```
$ open ios/calaRN.xcodeproj
```

![](https://cldup.com/ty0TeyJkO5.png)

```
$ git diff ios/calaRN.xcodeproj/project.pbxproj
```
https://gist.github.com/dylanpyle/144e98578227c72287a119d386fb1bee

### Reproduction

Can provide access to the project in question to the React Native team if needed; [email me](mailto:d@ca.la).

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Operating System: macOS 10.12.3
* Dev tools: XCode 8.2.1

**Comment by dylanpyle** [comment]
Temporary workaround — manually editing the `pbxproj` file by hand as follows seems to fix it. This is, I assume, what react-native link should have been doing.

```diff
@@ -1003,7 +1040,10 @@
                                CURRENT_PROJECT_VERSION = 68;
                                DEAD_CODE_STRIPPING = NO;
                                DEVELOPMENT_TEAM = 5492JZ4B5H;
-                               HEADER_SEARCH_PATHS = "$(inherited)";
+                               HEADER_SEARCH_PATHS = (
+                                       "$(inherited)",
+                                       "$(SRCROOT)/../node_modules/react-native-fbsdk/ios/RCTFBSDK/**",
+                               );
                                INFOPLIST_FILE = calaRN/Info.plist;
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                                LIBRARY_SEARCH_PATHS = (
@@ -1033,7 +1073,10 @@
                                "CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
                                CURRENT_PROJECT_VERSION = 68;
                                DEVELOPMENT_TEAM = 5492JZ4B5H;
-                               HEADER_SEARCH_PATHS = "$(inherited)";
+                               HEADER_SEARCH_PATHS = (
+                                       "$(inherited)",
+                                       "$(SRCROOT)/../node_modules/react-native-fbsdk/ios/RCTFBSDK/**",
+                               );
                                INFOPLIST_FILE = calaRN/Info.plist;
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                                LIBRARY_SEARCH_PATHS = (
```

**Comment by Kureev** [comment]
Thanks for the issue, @dylanpyle!

Most likely, this happens because of incorrect assumption [here](https://github.com/facebook/react-native/blob/545072b02d94e264a66987a5cebc15629a16f188/local-cli/link/ios/mapHeaderSearchPaths.js#L35). We assume that if we have `HEADER_SEARCH_PATHS` defined, then it is an array which is apparently not the case. We need to add a check if `HEADER_SEARCH_PATHS` is not an array and if so, wrap it into one.

Do you want to make a contribution? Otherwise I can fix it tomorrow

**Comment by dylanpyle** [comment]
@Kureev Thanks for the pointer! I'll take a look at getting a PR out tonight.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by dylanpyle** [comment]
@hramos Pull request #12964 fixes this issue

**Comment by hramos** [comment]
Great, thanks @dylanpyle. Re-opening.

**Comment by manuTro** [comment]
I'm still getting the problem. I tried to link the `react-native-video`  library  and I had 
`rnpm-upgrade ERR! Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found. ` and the follows lines have been added to the `project.pbxproj` file:

```
LIBRARY_SEARCH_PATHS = (
					"$(inherited)",
					"\"$(SRCROOT)/$(TARGET_NAME)\"",
				);
				HEADER_SEARCH_PATHS = (
					"$(inherited)",
					"$(SRCROOT)/../node_modules/react-native-video/ios",
				);
			};
```
How I can manually fix it?

**Comment by dylanpyle** [comment]
@manuTro When i ran into this issue, my problem was that the `link` step had created code like:

```
HEADER_SEARCH_PATHS = "$(inherited)""$(SRCROOT)/../node_modules/react-native-fbsdk/ios/RCTFBSDK/**";
```

instead of:

```
HEADER_SEARCH_PATHS = (
  "$(inherited)",
  "$(SRCROOT)/../node_modules/react-native-fbsdk/ios/RCTFBSDK/**",
);
```

— so my solution was to manually edit it to look like the second code until https://github.com/facebook/react-native/pull/12964 is merged. The code you posted looks OK to me; is there a chance there's an issue somewhere else in the `pbxproj` file?

**Comment by manuTro** [comment]
@dylanpyle  the `pbxproj` file was fine before the link.. Is it possible that, since I had the error 
```
rnpm-upgrade ERR! Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
 
```
the problem is on these lines?
```
LIBRARY_SEARCH_PATHS = (
					"$(inherited)",
					"\"$(SRCROOT)/$(TARGET_NAME)\"",
				);
```
Unfortunately I'm not an expert, so I don't know what I should expect.

**Comment by hramos** [comment]
A fix is incoming, we just need to resolve whatever is blocking that PR from being merged internally. Hang tight.

**Comment by dylanpyle** [comment]
Fixed in master! Thanks @hramos!

**Comment by theronic** [comment]
react-native-git-upgrade 0.2.7 corrupted my project.pbxproj file and left it in a state where git does not even know it's conflicted.
