### ISSUE TITLE
init new project error with React-Native 0.43-rc4

### ISSUE THREAD

**Issue by hnzlk2014** [facebook/react-native#13078]
NPM version: 4.4.1
Xcode version: 8.2 (8C38)
React Native version: 0.43-rc1~4
Platform: iOS
Operating System: MacOS os x EI Capitan

react-native 0.42.3 no problem.

react-native init --version="0.43.0-rc.4" FlatListTest4

error message:
2017-03-22 18:24:09.965 [warn][tid:NSOperationQueue 0x618000030700 :: NSOperation 0x61800004f390 (QOS: DEFAULT)][RCTBatchedBridge.m:113] Failed to load source: Error Domain=JSServer Code=500 "Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/zlk/Downloads/ReactNative/FlatListTest4/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map or in these directories:
  /Users/zlk/Downloads/ReactNative/FlatListTest4/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`." UserInfo={stack=(
        {
        file = "";
        lineNumber = 0;
        methodName = "";
    }
), NSLocalizedDescription=Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/zlk/Downloads/ReactNative/FlatListTest4/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map or in these directories:
  /Users/zlk/Downloads/ReactNative/FlatListTest4/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.}
2017-03-22 18:24:09.978 [fatal][tid:main] Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/zlk/Downloads/ReactNative/FlatListTest4/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map or in these directories:
  /Users/zlk/Downloads/ReactNative/FlatListTest4/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.

**Comment by ncuillery** [comment]
I confirm the problem.

It's is due to the React version 16.0.0-alpha.5 published on NPM yesterday.

Fix your React version to 16.0.0-alpha.4 in your `package.json`and re-install the dependencies.

**Comment by hnzlk2014** [comment]
npm ERR! notarget No compatible version found: react-test-renderer@16.0.0-alpha.4
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0, 1.1.0, 15.3.0, 15.3.1-rc.1, 15.3.1-rc.2, 15.3.1, 15.3.2-rc.1, 15.3.2, 15.4.0-rc.1, 15.4.0-rc.2, 15.4.0-rc.3, 15.4.0-rc.4, 15.4.0, 15.4.1, 15.4.2, 16.0.0-alpha, 16.0.0-alpha.0, 16.0.0-alpha.2, 16.0.0-alpha.3, 16.0.0-alpha.5

**Comment by hnzlk2014** [comment]
16.0.0-alpha.3 is ok.

**Comment by gaearon** [comment]
I think the problem is that we didn't pin the React version during one of the previous syncs: https://github.com/facebook/react-native/commit/24a7665df5c35e0db32572c6ff83f51392c43f13#commitcomment-21457443. So now every time we release a new alpha of `react` (potentially with breaking changes because it's an alpha), React Native RC that contains `~` in the peer dependency will let the users happily upgrade to a broken version.

For people in this thread, the solution is to pin your `react` version in `package.json` to `16.0.0-alpha.4`. Your code might not work with `16.0.0-alpha.5` until we do another sync.

**Comment by gaearon** [comment]
(And we need to pin React versions in the future, just like we did before. I'm not sure why we broke the pattern, and whether it was intentional or not.)

**Comment by javache** [comment]
The package build issue should be resolved as far as I'm aware with https://github.com/facebook/react-native/commit/a2cfea1934ab3682b2597a53de0b2b00a319832f

**Comment by gaearon** [comment]
The followup we agreed on is @bvaughn will submit a PR removing `~` from `package.json` and coordinate with @mkonicek to get a similar change into RC branch.

**Comment by gaearon** [comment]
Fix up in https://github.com/facebook/react-native/pull/13121.

**Comment by dcp12345678** [comment]
The solution suggested by ncuillery did not work for me. I still get same "No bundle url present" error.

**Comment by sergiofraile** [comment]
Same in here. Even a new project with react-native 0.43.3 gives me the same issue.
