### ISSUE TITLE
[iOS][cocoapods] 'RCTAnimation/RCTValueAnimatedNode.h' file not found

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#13198]
### Description

`'RCTAnimation/RCTValueAnimatedNode.h' file not found.`
in current master https://github.com/facebook/react-native/tree/c233191485ef733aa7a8d4ea5c758b9e6a06964c

1) related to 28 of march changes. @janicduplessis might help
2) podspec test are passed. @alloy do you have ideas how tests could be improved?
Maybe we need to run `xcbuild` to test?

### Reproduction Steps and Sample Code

https://github.com/skv-headless/AwesomeProject - demo project based on this page https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#cocoapods

### Solution

It works if change `#import <RCTAnimation/RCTValueAnimatedNode.h>` to `#import "RCTValueAnimatedNode.h"`

### Additional Information

* Platform: [iOS]
* Development Operating System: [MacOS]

**Comment by alloy** [comment]
> podspec test are passed. @alloy do you have ideas how tests could be improved?
> Maybe we need to run xcbuild to test?

Nah, we should ideally build all the subspecs, I’ll take a look at how long those take.

**Comment by alloy** [comment]
@skv-headless Your example fails to build from a fresh clone with different issues than the one this ticket is about. Can you make sure it fails with the exact issue you mention from a fresh clone (so no `pod install`, no `npm install`) ?

**Comment by alloy** [comment]
While enabling full podspec testing I did encounter this failure, which is probably the one you’re referring to:

```
In file included from /Users/eloy/Code/React/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.m:10:
/Users/eloy/Code/React/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h:12:9: fatal error: 'RCTAnimation/RCTValueAnimatedNode.h' file not found
#import <RCTAnimation/RCTValueAnimatedNode.h>
```

**Comment by skv-headless** [comment]
Yep. This error. I've updated repo in case it still needed. Are you going to update test script?

**Comment by alloy** [comment]
Yeah I’ll do that, and then we’ll see how much time it takes to complete on CI.

**Comment by alloy** [comment]
Pushed #13217

**Comment by shrutic** [comment]
I still get this error even in 0.44.0 where the code in RCTNativeAnimatedModule.h is updated from It works if change #import <RCTAnimation/RCTValueAnimatedNode.h> to #import "RCTValueAnimatedNode.h"

as mentioned by the original Bug logger. So the solution did not work for me.. Any other recommended solutions?

**Comment by iggyfisk** [comment]
This is fixed as of https://github.com/facebook/react-native/commit/7b7d6bb1583eada246de17d4c33b5fd37ba8ce0c @skv-headless

**Comment by nartawak** [comment]
@iggyfisk Is it possible to have a 0.44 fix with this commit ?

**Comment by egorkhmelev** [comment]
For those who still searching for a quick solution. I was able to launch iOS app with RCTAnimation subspec by including following string to my **package.json**:

```
"scripts": {
  "postinstall": "sed -i '' 's\/#import <RCTAnimation\\/RCTValueAnimatedNode.h>\/#import \"RCTValueAnimatedNode.h\"\/' ./node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h",
  ...rest scripts
}
```

React: 16.0.0-alpha.12
ReactNative: 0.45.0-rc.0

Didn't work for me with above PR which already accepted in **0.45.0-rc.0**

**Comment by Igor1201** [comment]
@egorkhmelev same for me. `ss.header_dir` on Podspec didn't solve this issue.

**Comment by nartawak** [comment]
@iggyfisk This PR ([7b7d6bb](https://github.com/facebook/react-native/commit/7b7d6bb1583eada246de17d4c33b5fd37ba8ce0c)) didn't solve this issue but this one which is closed yes [(13217)](https://github.com/facebook/react-native/pull/13217/files) !!! 

Does someone work again on a this issue ?

**Comment by guysegal** [comment]
this is a blocker for us too.. why is the issue closed?

**Comment by younatics** [comment]
Still get this error in RN 0.45.1

**Comment by djhr** [comment]
having this error too in v0.45.1

**Comment by stefanengel** [comment]
Getting the error in RN 0.45.1 as well

**Comment by younatics** [comment]
Please use this script in `package.json`  `script` section.
```
"postinstall": "sed -i '' 's\/#import <RCTAnimation\\/RCTValueAnimatedNode.h>\/#import \"RCTValueAnimatedNode.h\"\/' ./node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h",
```

It will change `#import <RCTAnimation/RCTValueAnimatedNode.h>` -> `#import "RCTValueAnimatedNode.h`

**Comment by guysegal** [comment]
I use this script and it works but it's not a solution its a patch.. Also some of our teammates are working on Windows macines so this script will not work (I know there's an equivalent for Windows)

The point is that this should be solved the right way without using any hacking..

**Comment by younatics** [comment]
Right. Should be fixed

**Comment by iegik** [comment]
> The import in the header needs to be namespaced, this is not a correct solution.
How to fix?

**Comment by guysegal** [comment]
it seem that this change in RCTNativeAnimatedNodesManager.h does the trick:

before:

<img width="445" alt="screen shot 2017-07-03 at 11 54 59" src="https://user-images.githubusercontent.com/7164560/27785501-7fd44b04-5fe6-11e7-855d-a66b2547e4c9.png">

after:

<img width="492" alt="screen shot 2017-07-03 at 11 55 52" src="https://user-images.githubusercontent.com/7164560/27785525-9588a878-5fe6-11e7-8e76-6bb412314584.png">

Does this make sense? It's working for me on 0.45.1, without running the patch script

**Comment by iegik** [comment]
`cd ios && pod install && cd ..`

**Comment by luugiathuy** [comment]
@littlehome-eugene you can try `npm run postinstall`

**Comment by mobinni** [comment]
I got this issue upgrading to react native 0.47.1, any way to resolve it without hacks?

**Comment by shergin** [comment]
Does anyone tried to investigate real cause of this problem and find proper solution? All approaches mentioned here and in attached PRs do not look legit and almost certainly will not be merged.

**Comment by guysegal** [comment]
isn't my solution that was posted here on July 3rd good enough? (the comment with the image attached)

**Comment by shergin** [comment]
@guysegal That file is not part of `React` module so it cannot be correct solution, right?

**Comment by jaybowong** [comment]
No luck after upgrading to 0.48.3. Have to use the [postinstall script](https://github.com/facebook/react-native/issues/13198#issuecomment-302917321) to solve it.

**Comment by janicduplessis** [comment]
Did anyone try setting `private_header_files`? We do use that in a few place in the pod config file. I'm pretty sure it's just a config issue, we should not have to change the import. Sorry about this taking so long to get resolved but we want to make sure we have the right fix.

**Comment by iegik** [comment]
> @guysegal That file is not a part of React module so it cannot be correct solution, right?
@shergin, which file:
https://github.com/facebook/react-native/blob/master/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h or https://github.com/facebook/react-native/blob/master/Libraries/NativeAnimation/Nodes/RCTValueAnimatedNode.h is **not a part of React** ?

**Comment by iegik** [comment]
@janicduplessis [Documentation](http://facebook.github.io/react-native/releases/next/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies) update needed for `private_header_files`

**Comment by shergin** [comment]
@iegik I assume `RCTValueAnimatedNode` is part of `RCTAnimation`. Am I wrong?

**Comment by qianyanseu** [comment]
Still having this issue using `0.48.3`

**Comment by janicduplessis** [comment]
@iegik Did the `private_header_files` thing I mentionned ended up working? It was just a wild guess haha

**Comment by iegik** [comment]
@janicduplessis This is not a joke - https://github.com/facebook/react-native/issues/15775

**Comment by shergin** [comment]
@iegik What do you mean? Do you have an idea how to fix this issue?

**Comment by johannth** [comment]
I've asked on the [Cocoapods mailing list](https://groups.google.com/forum/#!topic/cocoapods/65WdPX8OH6g) but I think it is correct to change the import to `#import <React/RCTValueAnimatedNode.h>`. 

I think this is because `RCTAnimation` is only a subspec and will be built within the `React.framework` when installed with Cocoapods. If `RCTAnimation` would be a full-fledged pod then it would be possible to use `#import <RCTAnimation/RCTValueAnimatedNode.h>`.

**Comment by yimingtang** [comment]
The header file `RCTValueAnimatedNode.h` is a part of `RCTAnimation` framework, so it should be 

* `#import "RCTValueAnimatedNode.h"` **inside** RCTAnimation
* `#import <RCTAnimation/RCTValueAnimatedNode.h>` **outside** RCTAnimation.

**Comment by johannth** [comment]
@yimingtang Are you sure about that? I think RCTAnimation isn't built as a full-fledged framework because it gets distributed as a subspec to React (which Cocoapods builds as the framework). So I think it should be:

+ `#import "RCTValueAnimatedNode.h"` inside RCTAnimation
+ `#import <React/RCTValueAnimatedNode.h>` outside RCTAnimation because `RCTValueAnimatedNode` is found within `React.framework`.

There is a similar issue with `fishhook` as well, see #16271 and #16039.

**Comment by rodrigoelp** [comment]
Hey guys, no idea what is the status of this with other people... but I am having the compilation error. Fixed it as per suggestion `#import <React/RCTValueAnimatedNode.h>`

**Comment by ZionChang** [comment]
Still get error with `fishhook.h` and `RCTValueAnimatedNode.h`, so I have to change it manually.

**Comment by povloid** [comment]
Have some errors after migration to RN 0.50.3

**Comment by tirrorex** [comment]
Same here, please fix this

**Comment by rodrigoelp** [comment]
In case you guys are not checking the other issue: guykogus provided a "fix" here #16039

Unfortunately, this has been on for sometime now and facebook is not paying attention to this :(

**Comment by fjtrujy** [comment]
I think that we should push this up again.
Otherwise we will have always kind of `hack` on our projects to make them work with Cocoapods.

Thanks!

**Comment by jeremyclee** [comment]
Not sure if this will help anyone, but I can avoid this issue if I **remove** `use_frameworks!` from my `Podfile`
If you need to add `use_frameworks!`, it seems like the [postinstall](https://github.com/facebook/react-native/issues/13198#issuecomment-302917321) script is the only way..

**Comment by p2k** [comment]
There is a common practice that I noticed in quite a few projects that deal with this issue. Here is how it would look like:
```
#if __has_include(<React/RCTValueAnimatedNode.h>)
#import <React/RCTValueAnimatedNode.h>
#else
#import "RCTValueAnimatedNode.h"
#endif
```
You can adjust this to your needs, e.g. if you want to cling to `#import <RCTAnimation/RCTValueAnimatedNode.h>` for whatever reason, then just replace the first and second line appropriately.

**Comment by rodrigoelp** [comment]
Love your suggestion @p2k I think that should be the fix

**Comment by msand** [comment]
Yep, the practice suggested by @p2k seems great. This could be applied to: https://github.com/facebook/react-native/pull/17080
https://github.com/facebook/react-native/pull/16271

https://github.com/facebook/react-native/pull/18050

Removing the need for this postinstall patch:
https://github.com/facebook/react-native/pull/17764#issuecomment-367943213

**Comment by jlyonsmith** [comment]
What build is the React Native team planning to put out a fix for this?  Now that Swift has been around for a couple years and `use_frameworks!` has become commonplace this seems like it really needs a fix.  Maybe a trial branch so that folks can report errors and issues before release?

**Comment by rodrigoelp** [comment]
That is exactly my line. Doing an application completely in react native is practically unfeasible and most new software is been written in swift (and kotlin)

**Comment by p2k** [comment]
Duplicate declaration is inherently prevented by ObjC/clang's `#import` instruction, except if the headers do exist twice, which is prevented with my proposed approach.

**Comment by khadkaPratik** [comment]
@younatics Your trick worked but i have to remove node_modules folder add the script in package.json and npm install . It worked in my case

**Comment by orta** [comment]
Hi everyone, I've centralized a lot of the CocoaPods issues into a single project which will apply all of the post-install fixes for you, which should simplify integrating React Native with CocoaPods

**Comment by Abdul-Hannan** [comment]
its sad that even after an year, React-native iOS through Cocoapods is not seamless, you still have to patch around things

**Comment by jeanregisser** [comment]
What version are you on @Abdul-Hannan?
The project I'm currently working on uses CocoaPods with React Native 0.55.3 without any issue.

**Comment by jeanregisser** [comment]
Ok, and what version of CocoaPods?

**Comment by Abdul-Hannan** [comment]
I am using COCOAPODS: 1.5.0,
avoided issues by using @orta 's https://github.com/orta/cocoapods-fix-react-native

**Comment by chrisballinger** [comment]
I can verify that RN 0.56.0-rc.2 does *not* resolve the issue.

**Comment by rodrigoelp** [comment]
Yup, it has not been fixed. This issue has been on for more than a year.

**Comment by keshavkaul** [comment]
@jeanregisser This is still an issue with RN 0.56.0-rc.4

**Comment by pavjacko** [comment]
try to add this to package.json and run it in your post-install:
```
"scripts": {
  "fix:ios": "sed -i '' 's/#import <RCTAnimation\\/RCTValueAnimatedNode.h>/#import \"RCTValueAnimatedNode.h\"/' ./node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h"
}

Here is the project template which demonstrates this:
https://www.npmjs.com/package/react-native-vanilla

**Comment by ttruongatl** [comment]
I upgraded my react-native to v0.56.0. once I run `pod install` before building iOS. It works. My solution is

1. Update react-native@0.56.0
2. cd ios && pod install
3. react-native run-ios

**Comment by muhammadsr** [comment]
For those who are still experiencing the issue. Try the following:

1. ` rm -rf ~/Library/Developer/Xcode/DerivedData/`
2. Inside the `ios` folder, do `rm -rf "`pwd`/Pods/"`
3. `rm -rf "${HOME}/Library/Caches/CocoaPods"`
4. Open `xcworkspace` 
5. Product > Clean 
6. Product > Clean Folder (Must hold the option key)
7. Build

Good luck!

**Comment by Dimon70007** [comment]
> I am using COCOAPODS: 1.5.0,
> avoided issues by using @orta 's https://github.com/orta/cocoapods-fix-react-native

it's not a solution to remove import code for fixing bugs because it may cause crash
