### ISSUE TITLE
Android WebViews do not update when content contains #

### ISSUE THREAD

**Issue by FuadBalashov** [facebook/react-native#13574]
### Description
If you have a webview that contains html with a `#` in it, the WebView will not be updated if the content after the `#` is changed on rerender. This issue only occurs with android devices (versions tested are noted below).

### Reproduction Steps and Sample Code
Example: https://snack.expo.io/BJj62vVAx
* Create a component which:
** has a state variable which is a string with a `#` in it
** displays that string as the (html) source of a webview
** has a button that changes the value of the state variable by modifying the content after the `#`.
( this can be seen in the example provided )
* click on the button to update the string
* Note that the new value of the string is not shown in the webview

Expected:
* The WebView should rerender to show the new html it is given.

### Solution

Not sure, however, it would be worth verifying this with other characters to see if any others cause this issue.

### Additional Information

* React Native version: 0.42.0 & 0.43.0
* Platform: Android (5, 6 & 7) have not tried older versions.
* Development Operating System: Mac OS Sierra
* Dev tools: 2.2.2 Android SDK: 23

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by xerotolerant** [comment]
I experience this as well. I was setting the content contain a style with a color value like `#ffaacc` and it failed to update. I then simply included a random '#' just to be sure after reading this. It really refused to re load even though it's parent component definitely reloaded

How peculiar. I wonder why this character in particular is causing this problem

I'm on  react 16.2.0 and react-native 0.53.3.

**Comment by kidmysoul** [comment]
I have the same problem with @xerotolerant ,  the webview doesnot re-render when I have code in html like 

`              body {
                color: #4a4a4a;
              }`

Even when I comment out the style like 

`              body {
                /*color: #4a4a4a;*/
              }`
it doesnot work too.


And when I dropped the whole style , the content re-rendered .

it only happened in android.

I use    "react-native": "0.50.0",

@hramos      please re-open this issue because it's a bug I think.

**Comment by fshauge** [comment]
This is indeed still an issue. It's caused by the fact that the HTML sent to [WebView.loadData](https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)) contains invalid characters in relation to the specified encoding.

> The encoding parameter specifies whether the data is base64 or URL
    encoded. If the data is base64 encoded, the value of the encoding
    parameter must be 'base64'. For all other values of the parameter,
    including null, it is assumed that the data uses ASCII encoding for
    octets inside the range of safe URL characters and use the standard %xx
    hex encoding of URLs for octets outside that range. For example, '#',
    '%', '\', '?' should be replaced by %23, %25, %27, %3f respectively.

I see two solutions:

1. URL encode the HTML before calling loadData
2. base64 encode the HTML before calling loadData and pass "base64" as the encoding

**Comment by fshauge** [comment]
A temporary solution in your React Native app is to call encodeURIComponent with the HTML before passing it to the WebView.
