### ISSUE TITLE
Listview getting crashed while scrolling fast or doing fling

### ISSUE THREAD

**Issue by orbitptr** [facebook/react-native#13592]
### Description

I used a sectioned data in the listview with the following structure.
{
  key1: {d1:"somedata"},
  key2: {d1:"somedata"}
}

While scrolling little faster and doing couple of flings up and down am this crash is coming. 

### Reproduction Steps and Sample Code
 threadid=1: thread exiting with uncaught exception (group=0x418c1d58)
 FATAL EXCEPTION: main
 Process: com.little, PID: 11085
 java.lang.NullPointerException
 	at com.facebook.react.views.scroll.ReactScrollView.getMaxScrollY(ReactScrollView.java:308)
 	at com.facebook.react.views.scroll.ReactScrollView.onOverScrolled(ReactScrollView.java:341)
 	at android.view.View.overScrollBy(View.java:17558)
 	at android.widget.ScrollView.computeScroll(ScrollView.java:1259)
 	at android.view.View.getDisplayList(View.java:13358)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.View.draw(View.java:14193)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2959)
 	at android.view.View.draw(View.java:14479)
 	at android.view.View.getDisplayList(View.java:13373)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
 	at android.view.View.getDisplayList(View.java:13311)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.View.draw(View.java:14193)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
 	at android.view.View.getDisplayList(View.java:13368)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
 	at android.view.View.getDisplayList(View.java:13311)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
 	at android.view.View.getDisplayList(View.java:13311)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
 	at android.view.View.getDisplayList(View.java:13311)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
 	at android.view.View.getDisplayList(View.java:13311)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
 	at android.view.View.getDisplayList(View.java:13311)
 	at android.view.View.getDisplayList(View.java:13415)
 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2427)
 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2299)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1929)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1046)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5660)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
 	at android.view.Choreographer.doFrame(Choreographer.java:544)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
 	at android.os.Handler.handleCallback(Handler.java:733)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:136)
 	at android.app.ActivityThread.main(ActivityThread.java:5052)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
 	at dalvik.system.NativeStart.main(Native Method)

### Solution
Its going into  this method and calling getMaxScrollY()

@Override
  protected void onOverScrolled(int scrollX, int scrollY, boolean clampedX, boolean clampedY) {
    if (mScroller != null) {
      // FB SCROLLVIEW CHANGE

      // This is part two of the reimplementation of fling to fix the bounce-back bug. See #fling() for
      // more information.

      if (!mScroller.isFinished() && mScroller.getCurrY() != mScroller.getFinalY()) {
        int scrollRange = getMaxScrollY();
        if (scrollY >= scrollRange) {
          mScroller.abortAnimation();
          scrollY = scrollRange;
        }
      }

      // END FB SCROLLVIEW CHANGE
    }

    super.onOverScrolled(scrollX, scrollY, clampedX, clampedY);
  }

I dont know for what reason it will become null.
  private int getMaxScrollY() {
    int contentHeight = mContentView.getHeight();   =============>>> Here is the crash =====> mContentView is null.
    int viewportHeight = getHeight() - getPaddingBottom() - getPaddingTop();
    return Math.max(0, contentHeight - viewportHeight);
  }

The only place the mContentView is made null is here
===========================================
  @Override
  public void onChildViewRemoved(View parent, View child) {
    mContentView.removeOnLayoutChangeListener(this);
    mContentView = null;
  }

### Additional Information

* React Native version: 0.42.3
* Platform: Android
* Development Operating System: Ubuntu 16.04
* Dev tools: Android Studio

**Comment by ludovic-coder** [comment]
Did you try to update to 0.43 ? Many bug was fixed for ListView and FlatList

**Comment by hramos** [comment]
+1. Can you try out FlatList and let us know how it goes? FlatList is the new replacement for ListView and it's more likely for this to be addressed if FlatList is similarly affected.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/listview-getting-crashed-while-scrolling-fast-or-doing-fling

**Comment by hugoh1995** [comment]
Still crashes for with even with latest version of RN and using flatlist on Android devices only.
