### ISSUE TITLE
[0.45.0] + [0.46.0-rc.2] fails to compile folly: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by sjmueller** [facebook/react-native#14328]
Having a problem compiling react native 0.45 & 0.46-rc.2 during the linking phase:

![image](https://cloud.githubusercontent.com/assets/29085/26806163/56d6b4aa-4a04-11e7-8a67-0d1f2d5c8bc5.png)

![image](https://cloud.githubusercontent.com/assets/29085/26806216/9213dcbe-4a04-11e7-836a-9d8e93a18d2f.png)

I've never seen errors in RN related to folly, so not really sure what has changed from 0.44 to 0.45 that would cause this type of compilation error. My best guess could be from this commit 885856c6a1cc0e848699f71c2175bfd90933b2b9 that's trying to fix the Travis build, but it does a bunch of stuff with conditional includes that I don't understand.

Our RN xcode project is in swift, so maybe the difference is why these errors snuck through without detection? 

cc @ericvicenti @javache

**Comment by sjmueller** [comment]
Any help here? I've tried just about everything:
- Reconfigure `Other Linker Flags` with every combination of `-all_load` `-Objc` `-lc==`)
- Include libthird-party.a in our project's `Linked Frameworks and Libraries`
- Add to `Header Search Paths` `$(SRCROOT)/../node_modules/react-native/third-party` recursively

@ericvicenti @javache @vjeux @lelandrichardson: The thirdparty changes included in 0.45+ have broken swift projects using react native. I realize that fb doesn't use swift, but more and more teams are in this camp and so any advice or potential fixes you can think of would be greatly appreciated.

**Comment by javache** [comment]
The compilation error you mention should be fixed by https://github.com/facebook/react-native/commit/2766103291606c18f1e9520c668c39048acd1271. Can you check if those changes are present in your copy?

**Comment by andon** [comment]
We are having the same issue after upgrade from rn-0.44.2 to rn-45.1.

@javache I checked react-native in node_modules, and the changes from https://github.com/facebook/react-native/commit/2766103291606c18f1e9520c668c39048acd1271 are present, but we still get the errors.

Similar as with @sjmueller, we tried all the steps to clean up the project before getting to this issue.

**Comment by sjmueller** [comment]
@javache I have prepared a barebones swift 3 project with RN `0.46.0-rc.2` which reproduces the errors:

[rn46-swift-3rd-party-errors.zip](https://github.com/facebook/react-native/files/1075522/rn46-swift-3rd-party-errors.zip)
- `npm i` to install dependencies
- open project in xcode, then `⌘ SHIFT <` to uncheck parallelized build + add React as the first target:
  
  ![image](https://user-images.githubusercontent.com/29085/27147960-78e4fdcc-50f3-11e7-867c-7bcdc19713ba.png)
- Run the project in xcode `⌘ R`

You should now be able to reproduce the error:

<img src="https://user-images.githubusercontent.com/29085/27148048-cdffb432-50f3-11e7-9726-70e59f353e96.png" width="200" />

**Comment by daesan** [comment]
@javache I have upgraded from 0.44.3 to 0.45.1 and I am experiencing the same linker error as @sjmueller. My project is Objective-C based and I am using CocoaPod.

Looking at the linker warnings, there seems to be path misconfiguration? "ios" part is being repeated in the path.

<img width="251" alt="error" src="https://user-images.githubusercontent.com/2495/27159510-9747025a-51a8-11e7-85b5-6fa44a2fd536.png">

**Comment by sjmueller** [comment]
Sorry you have the same issue @daesan -- didn't know until now that objc projects are affected too. I originally thought it was just swift.

**Comment by sjmueller** [comment]
FYI our swift project does not use cocoapods at all.

**Comment by mhorowitz** [comment]
There's two problems here:

1. the react project file includes folly/File.cpp, which is what pulls in these symbols, and is unnecessary.  You can delete it; I'll submit a fix to do the same upstream.

2. Normally, an unreferenced .o file in a .a file would not cause a problem, but your top-level project file includes `-all_load` in Other Linker Flags.  This causes all .o files to get pulled in, which causes the failure.  This flag was needed as a workaround for an old version of Xcode, but not any more.  If I remove the flag, your project builds without any linker errors.  So this likely a good workaround for now.

**Comment by sjmueller** [comment]
Thanks for chiming in @mhorowitz. As mentioned above, I tried every combination of Linker Flags. For the record, I have never been able to get a swift project to work with react native using just `-lc++` and `-ObjC` linker flags. Yes the project will build, however the app will immediately crash at runtime.  This is what I just got by removing `-all_load` in favor of `-ObjC` in the swift project I shared:

<img src="https://user-images.githubusercontent.com/29085/27168808-23863094-515c-11e7-9efb-bb16bf681e4d.png" width="375" />

```
<RCTBridge: 0x6100000ba160>, executor: (null))
2017-06-14 23:45:50.390 [warn][tid:main][RCTBridge.m:114] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
```

<img src="https://user-images.githubusercontent.com/29085/27168871-59483470-515c-11e7-88a2-10c99d348921.png" width="375" />

**Comment by sjmueller** [comment]
Actually, the error above is caused by AppTransportSecurity -- i forgot to add the exception:
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
```
After updating info.plist, I get the error:
```
2017-06-15 00:03:02.798 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'ReactPropTypes.string')
2017-06-15 00:03:02.800 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'ReactPropTypes.string')
2017-06-15 00:03:02.814 [error][tid:com.facebook.react.JavaScript] this._lazyCallableModules[name] is not a function. (In 'this._lazyCallableModules[name]()', 'this._lazyCallableModules[name]' is undefined)
2017-06-15 00:03:02.817 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: this._lazyCallableModules[name] is not a function. (In 'this._lazyCallableModules[name]()', 'this._lazyCallableModules[name]' is undefined)
```

These are not errors I recall seeing before. For reference, the error is the same for `-all_load` or `-ObjC`, of course after a clean + rebuild.

**Comment by andon** [comment]
Removing ```-all_load``` from ```Other Linker Flags``` makes the project build again.

**Comment by sjmueller** [comment]
@mhorowitz FYI removing File.cpp fixes the problem 🎉  -- I tried with our full project. There are some other problems now with the packager for `0.46.0-rc.2` that I've detailed in #14530, but not related to this issue.
