### ISSUE TITLE
NativeComponents iOS Documentation - RCT_CUSTOM_VIEW_PROPERTY 

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#14436]
### Description

The RCT_CUSTOM_VIEW_PROPERTY example for RNTMap no longer functions, and isn't properly explained.

```objc
// RNTMapManager.m
RCT_CUSTOM_VIEW_PROPERTY(region, MKCoordinateRegion, RNTMap)
{
  [view setRegion:json ? [RCTConvert MKCoordinateRegion:json] : defaultView.region animated:YES];
}

```

The native RNTMap class does not exist, and prior to this is not mentioned at all throughout the tutorial. It is however created later on when describing event handling, although the creation of it is not explained.

Side note, why does RCT_CUSTOM_VIEW_PROPERTY supply "json" rather than "name"? Seems very counter intuitive that you're implementing a method that is supposed to make use of arguments that aren't defined any where near the definition.

ie:
```objc
#define RCT_CUSTOM_VIEW_PROPERTY(name, type, viewClass) \
RCT_REMAP_VIEW_PROPERTY(name, __custom__, type)         \
- (void)set_##name:(id)**name** forView:(viewClass *)view withDefaultView:(viewClass *)defaultView
```

### Solution

Review documentation, break into multiple components, explain in more detail.

### Additional Information

* React Native version:0.45
* Platform: iOS
* Development Operating System: N/A
* Dev tools: N/A

**Comment by hramos** [comment]
`MapViewIOS` was removed a couple of versions ago. No one has touched this guide in a while, so unless someone volunteers to get it back up to date, we'll probably end up removing it from the docs.

**Comment by ShannonChenCHN** [comment]
@MattFoley I fixed this issue by using `MKMapView` to replace `RNTMap`, and it worked great. Maybe you can have a try.

**Comment by teameh** [comment]
@ShannonChenCHN Yeah that worked for me as well. I'll create a PR for this. Took me way too long to figure this out.

**Comment by teameh** [comment]
Added another pr, clearing up the categories a bit.

**Comment by teameh** [comment]
I'll stop here for now, but maybe I could rewrite the whole page if I understand how everything works a bit more 😏

**Comment by hdchan** [comment]
I'm still getting a "Warning: Native component for "RNTMap" does not exist"
Has anyone successfully implemented this?

**Comment by teameh** [comment]
@hdchan I've reworked the guide but it's not merged yet. You can preview it here, please let me know if it works for you :) https://github.com/teameh/react-native/blob/e10bcf1c0abf87e3eb23e7ebff543f3d72bb7c62/docs/NativeComponentsIOS.md

**Comment by hdchan** [comment]
@teameh it still doesn't work for some reason. I'm not sure if I am missing a step. I'm doing the minimum, up to the 

> Then you just need a little bit of JavaScript to make this a usable React component:
But I am still getting the warning 

> Warning: Native component for "RNTMap" does not exist

**Comment by teameh** [comment]
I've tried it again and it works for me. I've created a [new ReactNative project ](https://github.com/teameh/ReactNativeNativeComponentsExample/commit/43a92e5f254b8510df6a58a75005b51ca1da46bd) and added [one commit](https://github.com/teameh/ReactNativeNativeComponentsExample/commit/307846f1ef3d28b9c6fe90a8f254ad446ec08ee8) containing those first steps. 

Could you check if my project works for you?

**Comment by hdchan** [comment]
Thank you for the sample @teameh I will see what is different in my project that's making it not work.
Do you know if the Android version of Native UI is up to date? I will need to implement that side after this. 

Thanks again!

**Comment by teameh** [comment]
Good luck!

I've got no idea if that guide is up to date.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
