### ISSUE TITLE
iOS Native UI Component NOT rendering

### ISSUE THREAD

**Issue by jackwzp** [facebook/react-native#15097]
Hi all,

I followed the guide in [Native UI Component](https://facebook.github.io/react-native/docs/native-components-ios.html) to create a custom native UI that I want to render in JS. I generated a brand new project with ```react-native init CustomUI``` and then followed the instructions in the doc.

The example in the doc uses ```MKMapView``` and I've wrapped this view as a sub view to ```MyCustomUI``` class as explained in this [issue](https://github.com/facebook/react-native/issues/2948). Then I return ```MyCustomUI``` view in the ```MyCustomUIManager``` class.

Then I try to grab my view in ```index.ios.js``` file with the ```requireNativeComponent("MyCustomUI", MyCustomUIView)``` method.

However, when I run the app. Nothing is being rendered, I just get a blank background. I also tried not wrapping the ```MKMapView``` and return it directly from ```MyCustomUIManager``` and that didn't work either. 

I've a repo setup [here](https://github.com/jackwzp/react-native-ios-native-UI) if you guys want to try and run it

### Environment

1. `react-native -v`:  0.46.4
2. `node -v`: 6.10.2
3. `npm -v`: 3.10.10

- Target Platform: iOS 10+
- Development Operating System: Mac OSX 10.12.4

### Code

```obj-c
// MyCustomUI.h

#import <UIKit/UIKit.h>

@interface MyCustomUI : UIView
@end
```

```obj-c
// MyCustomUI.m

#import "MyCustomUI.h"
#import <MapKit/MapKit.h>

@implementation MyCustomUI

-(instancetype)init {
  self = [super init];
  if (self) {
    [self setUp];
  }  
  return self;
}

-(void) setUp {
  NSLog(@"Map Setup");
  MKMapView * map = [[MKMapView alloc] init];
  [self addSubview:map];
}

@end

```

```obj-c
// MyCustomUIManager.h

#import <Foundation/Foundation.h>
#import <React/RCTViewManager.h>

@interface MyCustomUIManager : RCTViewManager

@end
```

```obj-c
// MyCustomUIManager.m

#import "MyCustomUIManager.h"
#import "MyCustomUI.h"

@implementation MyCustomUIManager
@synthesize bridge = _bridge;

RCT_EXPORT_MODULE()

- (UIView *)view
{
  MyCustomUI * myUi = [[MyCustomUI alloc] init];
  return myUi;
}

@end
```

```javascript
// index.ios.js

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  requireNativeComponent
} from 'react-native';


// Get MyCustomUI 

var MyCustomUI = requireNativeComponent('MyCustomUI', MyCustomUIView);

class MyCustomUIView extends Component {
  render() {
    return <MyCustomUI {...this.props} />;
  }
}

MyCustomUIView.propTypes = {
  
};



export default class CustomUI extends Component {
  render() {
    return (
      <View style={styles.container}>
        <MyCustomUIView style={styles.custom} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  custom: {
    flex: 1,
  }
});

AppRegistry.registerComponent('CustomUI', () => CustomUI);
```

**Comment by reilem** [comment]
I had this issue and I fixed it by overriding the layoutSubviews function in my custom view. Apparently the frame will be determined by react-native after intialisation and so if you don't implement layoutSubvies the subviews inside your custom uiview will not have their frame updated. 

This is already done by default in the MKMapView and so there is no need to use a MyCustomUI wrapper UIView. If you really want to use a wrapper UIView then make sure to implement the layoutSubviews functon in which you update the frame of all subviews you wish to see. I hope this helps!

**Comment by jackwzp** [comment]
@reilem thanks for your response. I appreciate it. I tried returning the ```MKMapView``` directly in the ```MyCustomUIManager``` class as well and that did not work either.

```obj-c
// MyCustomUIManager.m

- (UIView *)view
{
    return [[MKMapView alloc] init];
}
```

I tried overriding the layoutSubviews method in MyCustomUI but I'm not sure what exactly I should be doing inside this method other than calling the super to layout subviews. With this dummy overridden layoutSubview, I still don't see anything being rendered. Any thoughts?

```obj-c
// MyCustomUI.m

- (void) layoutSubviews {
    [super layoutSubviews];
    // What else should I do?
}
```

**Comment by reilem** [comment]
@jackwzp It might be that you are just using incorrect styling. I'm no react-native expert but I was messing around with this yesterday and managed to find a way to test it.

Try replacing the `'MyCustomUI'` in `requireNativeComponent('MyCustomUI', MyCustomUIView)` with something incorrect like `'blahblah'`. Now the linking should be broken and react-native will render your component as a box with a red border. You can now use this box with red border to see what the true location and size of your component is. For example I once saw it was not using the full width of the screen and was just a single pixel along the left side of the screen. When I added `alignSelf: 'stretch'` to the style I could then see the component.

**Comment by jackwzp** [comment]
@reilem thanks for the help. I was able to get it working. I had to set the frame of the subviews in ```layoutSubviews```. Another way I found also works was to initialize the ```MKMapView``` with ```initWithFrame``` method, then I don't need to override the ```layoutSubviews``` class.

### Method 1
```obj-c
// MyCustomUI.m
// No longer need to override layoutSubviews method
- (void) setMap {
  MKMapView * map = [[MKMapView alloc] initWithFrame:CGRectMake(0, 0, 200, 300)];
  [self addSubview:map];
}
```

### Method 2

```obj-c
// MyCustomUI.m
// Create MKMapView with just init method works with this
- (void) layoutSubviews {
  [super layoutSubviews];  
  for(UIView* view in self.subviews) {
    [view setFrame:self.bounds];
  }
}
```

**Comment by bangnguyensea** [comment]
Got same issue too, don't know whey React Native init my view with frame (0, 0, w, 0).

**Comment by jgfidelis** [comment]
@bangnguyensea did you ever figure it out? I am having this problem with a view as well
