### ISSUE TITLE
[Build][iOS] Building project in Xcode takes for ever in Running 1 of 1 custom shell scripts

### ISSUE THREAD

**Issue by hugomosh** [facebook/react-native#15469]
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment

react-native-cli: 2.0.1
react-native: 0.46.4
$ node -v
v6.11.2
$ npm -v
3.10.10
$  yarn --version
0.24.5

iOS
Then, specify:

### Steps to Reproduce

1. I just open xcode in any React Native Project and 
2. hit run (Debug and Release scheme) and the ***Running 1 of 1 custom shell scripts*** takes for ever (20 minutes or so).
The terminal opens and the packager execute but i believe it hangs there 

### Expected Behavior

At the beginning was very fast. But now it is impossible.
I expect to be fast again. 
Don´t now if I change something that make the process slow.

### Actual Behavior

Hangs in that process for ever and also the first time the packager runs takes too long to load to 100%.

![captura de pantalla 2017-08-11 a la s 18 15 12](https://user-images.githubusercontent.com/898426/29235131-d58e4474-7ec1-11e7-9553-6d2b614fb0a2.png)

  Thanks !

**Comment by MacKentoch** [comment]
Same here, looking at the react-native-cli started output I have:

```bash
Loading dependency graph...
Bundling `index.ios.js`  ░░░░░░░░░░░░░░░░  0.0% (0/1)
```
*it remains 0.0% for eternity (computer time and worse human time...).*

I tried to reset cache / clear all (*like simulator content*) but no success with that:
```bash
watchman watch-del-all
rm -rf node_modules && npm install
npm start -- --reset-cache
```

By the way:
```bash
watchman watch-del-all
```

Seems like idled (so I killed it). 

**It could be related to watchman too?**

**Comment by MacKentoch** [comment]
seems like the same issue as  #15476

**Comment by MacKentoch** [comment]
AS I supposed it was due to watchman that was broken for some reason (*homebrew update?*).

## I Solved by **uninstalling COMPLETELY watchman** then **re-install it**:

```bash
brew uninstall watchman
brew install watchman
```

Then I had a bug about`ViewPropTypes.style` being undefined...
It was dur to react-native-maps in file `MapViews.js` I had to change:
```javascript
ViewPropTypes.style
```

to 

```javascript
View.propTypes.style
// don't forget to import View from react-native in the same time
```

**Comment by nishiltamboli** [comment]
Hi @MacKentoch . I am facing a similar issue where the Custom Shell Script during Archive takes forever. It is stuck particularly on 'Transform cache was reset'. Shall I also try reinstalling watchman?

**Comment by RichardLindhout** [comment]
Had the same problem a few months ago. I did run react-native cli as sudo. Perhaps one of the react-native/build tools is installed as sudo.

**Comment by hugomosh** [comment]
I had reallize that this process are made: 
![captura de pantalla 2017-09-06 a la s 19 04 09](https://user-images.githubusercontent.com/898426/30139879-463d313e-9336-11e7-8010-13415878e5f6.png)
If i kill the node process the building continues.

 I am not sure what it does, the packager starts but not progress is there to see. 
I think is some kind of bug, or misconfiguration (not receiving the finish flag) at some point. 

If I kill it too soon the app doesn't run but killing it after ca 5 minutes it runs. If i doesn't kill it it takes more than 20  minutes. Then it builds the app

**Comment by guillaumechereau** [comment]
I would like to reopen this issue, since I still have this problem.

**Comment by RichardLindhout** [comment]
Do you run react-native commands as sudo?

**Comment by hugomosh** [comment]
Not me @RichardLindhout. Neither when I run react-native run-ios nor when I build Xcode.

Should I?

**Comment by guillaumechereau** [comment]
I don't use sudo no.

**Comment by JayricMok** [comment]
I having same issue with "Running 2 of 4 custom shell script" take like 5 min or longer

**Comment by longsangstan** [comment]
Same problem here. At first it was very fast, but later just stuck forever. Even with completely new project.

react-native-cli: 2.0.1
react-native: 0.52.2

**Comment by helloeyesimple** [comment]
why this issue been closed? a lot of people still got this problem

**Comment by philjoseph** [comment]
I do have the same pb as well and wonder if we can speed up re-run of the app via xcode, when there is nothing to build it still run the shell scripts for a very long time

**Comment by helloeyesimple** [comment]
So is there any solution to this? Strangely this issue does not appeared when building Android App.

**Comment by Gp2mv3** [comment]
I have the same issue with my Mac Mini, only used to compile iOS version of the app. The issue is there since the beginning (v0.37) and I'm now using v0.53, the build always takes ages...
Really annoying.

I've a normal HDD, don't know if it can be related ?

**Comment by desarrollospyro** [comment]
@Gp2mv3 here your same situation!...
We have reinstalled watchman also and no effects. 
We hope it comes any solution soon

**Comment by nthegedus** [comment]
Issue solved using `react-native run-ios --device "PHONE_NAME"`

But you have to open the app manually

**Comment by ArtyEmsee** [comment]
Same issue:

`react-native: 0.54.0`

**Comment by mouthzipper** [comment]
same problem after updating xcode
```
xcode: 9.3
react-native: 0.45.1
```

**Comment by shehrozekhan** [comment]
I am running into the same issue. XCode remains stuck at "Running 1 of 1 custom shell scripts" for around 20 mins every time before it runs the application. However, on a friend's computer the same project compiles and runs in a reasonable amount of time with the same iPhone device. What could the issue be with my computer?

**Comment by simonbuchan** [comment]
That step basically checks if it's not a debug simulator build and runs `react-native bundle --entry-file index.js --platform ios --dev $IS_DEBUG --bundle-output $DEST/main.jsbundle --assets-dest $DEST --reset-cache` (modulo filenames) - so check if that takes much shorter. I suspect it doesn't.

**Comment by shrinandhini2801** [comment]
i Am facing same issue as well :(

**Comment by mouthzipper** [comment]
@shrinandhini2801  what version of xcode you are using? if 9.3, downgrading to 9.2 fixed my issue.

**Comment by shrinandhini2801** [comment]
@mouthzipper i am using Xcode 9.2 only. Still facing that issue. I am trying to run that in actual device not in simulator.

**Comment by uurtsaikhb** [comment]
I am having same issue. It takes forever to build on simulator and real device.

**Comment by damikdk** [comment]
@hugomosh `sudo pkill -9 node` helped, finally! Thanks

**Comment by rpires** [comment]
Can confirm that I'm facing this issue.

I did some digging around and my issue seems to be related to this log messages which appear during that build phase. I have no idea whats causing it...

At some point, it seems socket 3952 finally is available, and the build finishes.

```
2018-04-15 20:19:12.260837+0100 RedactedApp[790:309152] [] nw_connection_get_connected_socket 3952 Connection has no connected handler
2018-04-15 20:19:12.260944+0100 RedactedApp[790:309152] TCP Conn 0x1c0367c80 Failed : error 0:61 [61]
2018-04-15 20:19:14.062277+0100 RedactedApp[790:309152] [] nw_connection_get_connected_socket 3953 Connection has no connected handler
2018-04-15 20:19:14.062386+0100 RedactedApp[790:309152] TCP Conn 0x1c0361ec0 Failed : error 0:61 [61]
2018-04-15 20:19:14.286143+0100 RedactedApp[790:309152] [] nw_connection_get_connected_socket 3954 Connection has no connected handler
2018-04-15 20:19:14.286251+0100 RedactedApp[790:309152] TCP Conn 0x1c0361800 Failed : error 0:61 [61]

[... many hundred more like that]

```

Running on:

Mac OS 10.13.4
XCode: 9.3
React Native: 0.52.0

Any pointers?
Thanks.

**Comment by geekwill** [comment]
I have the same problem, but I still don't know how to solve it？

**Comment by arthare** [comment]
This doesn't seem like a "fix", but I fired up `top` in another terminal window, and of the 4 node scripts consuming CPU cycles, one of them was shown as "stuck".  I `kill`'d its PID, and that unblocked whatever custom script 2/4 is and successfully deployed on my iPad.

This was after a fresh reboot of the mac and it was the first build I'd performed, so I don't think it was leftover from a previous build.
