### ISSUE TITLE
FlatList onEndReached Called On Load [iOS] (with detailed findings)

### ISSUE THREAD

**Issue by zachrnolan** [facebook/react-native#16067]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.10.3
  Yarn:  1.0.2
  npm:  3.10.10
  Watchman:  4.7.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

### Steps to Reproduce

1. Create minimal app with a FlatList component that loads 20 items (with a height that is roughly double the height of the screen size)
1. Add onEndReached prop with a handler function that adds more data to the FlatList
1. Add onEndReachedThreshold prop with a value of 0.5
1. Load the app with the iOS simulator or an actual device

```
<FlatList
  data={this.state.data}
  keyExtractor={(item, index) => index}
  renderItem={this._renderItem}
  onEndReached={this.onEndReached}
  onEndReachedThreshold={0.5} />
```

### Expected Behavior

onEndReached should not be called until the user scrolls down on the vertical FlatList.

### Actual Behavior

onEndReached is called as the FlatList is loaded without any interaction from the end user. There seems to be some kind of race condition, as it only happens 50% of the time I load the screen. It is definitely reproducible with a couple refreshes.

### Reproducible Demo

Preferred way to reproduce is to download my minimal repo from https://github.com/zachrnolan/react-native-flatlist-vertical and yarn install && react-native run-ios

I also created a snack here: https://snack.expo.io/HkkO0RGob. Although it seems to be a little buggy with displaying the console logs.

### Detailed Findings

Since starting with React Native about a year and a half ago, I've always dealt with some inconsistencies or bugs with lists and infinite scroll / paging. I've outlined my findings with FlatList to hopefully allow other people to better understand the landscape. This could be too much detail for this particular bug report, but I think it's helpful.

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
iOS | 5 (roughly half the screen height) | 0

**Results:** 
onEndReached is called **twice** on load of the FlatList

**Notes:**
I'm guessing that onEndReached is called after the load of FlatList since the bottom of the FlatList is in view. It seems like the user should have to interact with the FlatList before onEndReached is called. Either way, shouldn't be called twice.

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
iOS | 10 (roughly the same height as the screen) | 0

**Results:** 
onEndReached is called **once** on load of the FlatList

**Notes:**
- onEndReached should not be called on load
- I'm able to load more pages as I scroll down, however, it will call onEndReached multiple times if I scroll really fast. I believe this is due to the momentum issue outlined here: https://github.com/facebook/react-native/issues/14015#issuecomment-310675650

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
iOS | 10 (roughly the same height as the screen) | 0.5 OR 1

**Results:** 
Same as above

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
iOS | 10 (roughly the same height as the screen) | > 1

**Results:** 
onEndReached is called multiple times on load of FlatList (typically around 10 times)

**Notes:**
- I've read around on different issues that it's best to use a number between 0 and 1. Just wanted to document how it behaves when the threshold is greater than 1

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
iOS | 20 (roughly double the height of the screen) | 0

**Results:** 
- Works as expected!
- Still have the momentum issue.

**Notes:**
This would be my preferred settings, however, the app I have in production is for both iOS and Android. These settings have another issue on Android (see below). I could check for Platform, so that may work.

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
iOS | 20 (roughly double the height of the screen) | 0.5

**Results:** 
- Works as expected!
- Still have the momentum issue.
- 50% of the time, onEndReached is called **once** on load of the FlatList (not good)

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
Android | 5 (roughly half the screen height) | 0

**Results:** 
- onEndReached is called **once** on load of the FlatList
- onEndReached is not called again when scrolling

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
Android | 10 (roughly the same height as the screen) | 0

**Results:** 
Android works as expected the first time you load more. However, it will not load a second time after you scroll to the bottom with the new data loaded. onEndReached function is not called.

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
Android | 10 (roughly the same height as the screen) | 0.5 OR 1

**Results:** 
- onEndReached is called once on load of the FlatList (should not be called until scrolling to the bottom of the list)
- Once you scroll down and onEndReached is called twice (should only be called once)

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
Android | 10 (roughly the same height as the screen) | > 1

**Results:** 
onEndReached is called multiple times on load of FlatList (typically around 5 times)

**Notes:**
- I've read around on different issues that it's best to use a number between 0 and 1. Just wanted to document how it behaves when the threshold is greater than 1

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
Android | 20 (roughly double the height of the screen) | 0

**Results:** 
- onEndReached isn’t called on load (good)
- onEndReached isn’t called when I scroll to the bottom of the list (bad)

---

Platform | Number of Items | onEndReachedThreshold
--- | --- | --- 
Android | 20 (roughly double the height of the screen) | 0.5

**Results:** 
- Works as expected!

**Comment by richardgirges** [comment]
Seeing the same behavior on iOS / React Native 0.48.4

**Comment by zachrnolan** [comment]
This is also an issue with horizontal FlatLists.

**Comment by allmaxgit** [comment]
How make not fire onEndReached on load on iOS?
My application entering in infinite loop because of this.

**Comment by hoorsa** [comment]
hi (sorry for my English)
my solution:
1. declare a variable:  **loadFlag: false**,
2. after first data fetch set **loadFlag: true**, (for next fetch)
3. before fetching new data onEndReached check **loadFlag**, if true then set **loadFlag: false** and call onEndReached function else don't call onEndReached function (fetch is loading).
4. after fetch new data from onEndReached function set **loadFlag: true**. (for next onEndReached)

**Comment by skyout** [comment]
I found this same issue - try putting `onEndReached` function call in an anonymous function.

**Comment by mahyarr** [comment]
Having the same issue. Im using a boolean flag to circumvent loading the data twice but it's obviously not a very elegant solution.

**Comment by janziemba** [comment]
Another possible workaround https://github.com/facebook/react-native/issues/14015#issuecomment-310675650

**Comment by Naoto-Ida** [comment]
I have not found a workaround that works...
but so far, if I remove [this line](https://github.com/facebook/react-native/blob/6b95c4fb142a7015b2afca50cc19eec0b8913d8c/Libraries/Lists/VirtualizedList.js#L1088), it stops doing the initial `onEndReached`.

**Comment by reinvanimschoot** [comment]
Has anyone found a better solution? It's very frustrating to work with FlatList like this.

**Comment by rudra0713** [comment]
I am facing another irritating issue. In my app, I created 4 tab screens. In one of the screens, I am using a FlatList. As soon as I load my app,   onEndReached method for the FlatList is getting called at that time (even when I have not navigated to my list screen). More importantly and disturbingly, this method is not getting called even when I scroll to the bottom of my Flatlist.

**Comment by AndreyMalykhin** [comment]
+1

**Comment by AyubaMakoa** [comment]
`constructor(props){
super(props);
this.state = {
flatListReady:false
}
}

_scrolled(){
this.setState({flatListReady:true})
}

loadMore = () => {
if(!this.state.flatListReady){ return null}

//you can now load more data here from your backend

}
<FlatList
onScroll={this._scrolled.bind(this)}
style={{width:'100%',flexGrow:1}}
ListHeaderComponent={this.headerComponent}
data={this.props.data}
renderItem={this.renderItem}
keyExtractor={(item,index) => index }
onEndReached={(x) => {this.loadMore()}}
onEndReachedThreshold={0.5}

           />
`

**Comment by ToniChaz** [comment]
same problem here

**Comment by christophby** [comment]
+1

**Comment by irodeanu** [comment]
+ 1

**Comment by anil1712** [comment]
Guys any update on the same? I am still facing the issue

**Comment by superandrew213** [comment]
I've tried all workarounds and none of them work 100% for me. This is the closest https://github.com/facebook/react-native/issues/14015#issuecomment-310675650 but still has some issue. It doesn't trigger when you scroll to end a second time.

Debouncing `onEndReached` like this using lodash's `debounce` or another debounce function works quite well.

```
constructor(props) {
    super(props);
    this._onEndReached = _.debounce(this._onEndReached, 500);
  }
```

It stops multiple triggers onLoad (when list is shorter than screen height) and onEndReached.

**Comment by Shu-Ji** [comment]
This is reproduced in the latest version 0.53.0

**Comment by timwangdev** [comment]
I just reopened this issue, because this bug still occurs in latest version of react-native.

**Comment by anil1712** [comment]
@timwangdev so did you get any solution for the same?

**Comment by CristiTr** [comment]
For those  of you that use `native-base`, enclosing FlatList between `<Content>` causes this issue.

Replacing  the `<Content>` with `<View>` solved the issue in my case.

**Comment by perlo27** [comment]
I'm wonder if there is any reason to call onEndReached if data is empty (data = [])? 

```
_maybeCallOnEndReached() {
    const {
      data,
      getItemCount,
      onEndReached,
      onEndReachedThreshold,
    } = this.props;
    const {contentLength, visibleLength, offset} = this._scrollMetrics;
    const distanceFromEnd = contentLength - visibleLength - offset;
    if (
      onEndReached &&
      this.state.last === getItemCount(data) - 1 &&
      /* $FlowFixMe(>=0.63.0 site=react_native_fb) This comment suppresses an
       * error found when Flow v0.63 was deployed. To see the error delete this
       * comment and run Flow. */
      distanceFromEnd < onEndReachedThreshold * visibleLength &&
      (this._hasDataChangedSinceEndReached ||
        this._scrollMetrics.contentLength !== this._sentEndForContentLength)
    ) {
      // Only call onEndReached once for a given dataset + content length.
      this._hasDataChangedSinceEndReached = false;
      this._sentEndForContentLength = this._scrollMetrics.contentLength;
      onEndReached({distanceFromEnd});
    }
  }
```
When your Flatlist component is mounting all checks are true if data is empty  :
- onEndReached  is true (if you passed ofc)
- this.state.last === getItemCount(data) -1  is true (last === -1 by default)
- distanceFromEnd is **likely** below zero since visibleLength > contentLength when data is empty
thus distanceFromEnd < onEndReachedThreshold * visibleLength ===true, if  onEndReachedThreshold >= 0
- this._hasDataChangedSinceEndReached === true by default 

If there are no such cases when it is necessary to call onEndReached with empty data, 
then adding the check for **data.length** in if statement above will solve the problem i guess.

**Comment by anil1712** [comment]
Hi Guys

Also, I am getting this while running `tsc` command. (I am using NativeBase) 	
```
error TS2322: Type '{ refreshing: boolean; data: DataGridRow[]; renderItem: ({ item, index }: { item: any; index: any...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<FlatListProperties<any>, ComponentState>...'.
Type '{ refreshing: boolean; data: DataGridRow[]; renderItem: ({ item, index }: { item: any; index: any...' is not assignable to type 'Readonly<FlatListProperties<any>>'.
```

Is anyone has any solution for this. I have updated my typescript with the latest version but still, I am getting this. Event the vscode is also showing the same.

**Comment by patrickleemsantos** [comment]
Hi All, 

My solution here is to check first whether the Flatlist was already scrolled or not by using **onScrollEndDrag** property of Flatlist. 

onEndReached will still be called for the first time, but you can prevent it before data fetching since the list was not scrolled yet (in my example its on _handleLoadMore_ function).

Please see my example code below.

constructor(props) {
    super(props);
    this.state = {isListScrolled: false};
}

handleLoadMore = () => {
      if (isListScrolled) {
           (Load more list....)
      }
}

<FlatList
                onScrollEndDrag={this.setState({isListScrolled: true})}
                keyExtractor={(item, index) => index.toString()}
                onEndReached={this.handleLoadMore}>

My react native version "react-native": "^0.52.2"

**Comment by hh2k** [comment]
@patrickleemsantos 
I think you will need to use something like this or else I get errors.
onScrollEndDrag={() => {this.setState({ isListScrolled: true }); }}

**Comment by feliperaul** [comment]
Also seeing this on "react-native": "0.54.4". Super duper annoying.

**Comment by shafy** [comment]
+1

**Comment by hh2k** [comment]
I am getting the error on 0.55 also

**Comment by adamnator92** [comment]
it's still happen, 
```
Packages: (wanted => installed)
  react: ^16.3.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4
```

**Comment by auchauncey** [comment]
+1

**Comment by jvitorr** [comment]
+1

**Comment by coocon** [comment]
it's still happen in 0.55.4. 
I think  setting Datas leads to FlatView rendering and  trigger the event "onEndReached",    I solved it by doing this:

```javascript

componentDidMount() {
        this.isScrolled = false;       
}
getData = () => {
        // this.setState({data: [.....]});
        setTimeout(() => {
                this.isScrolled = true;
        }, 100);
}
onEndReached = () => {
        if (!this.isScrolled) {
            return null;
        }
}
```

**Comment by ventr1x** [comment]
And that's why react in itself is really a problem for professional applications that don't have 500 devs to workaround stuff like airbnb had to. We won't see any fix from facebook if they don't have the same issue somewhere. They simply don't care.

Same issue in newest versions without any ui library.

**Comment by nyura123** [comment]
> For those of you that use `native-base`, enclosing FlatList between `<Content>` causes this issue.
> 
> Replacing the `<Content>` with `<View>` solved the issue in my case.

There could also be issues when FlatList is inside another ScrollView.

**Comment by stefanoeb** [comment]
React Native 0.57.2 and issue persists when the FlatList is inside a `<ScrollView>`. Removing the ScrollView solves the problem.

**Comment by cdrlee** [comment]
@coocon It works. 
Latest RN 0.57.4

**Comment by EugeneDraitsev** [comment]
Any updates? Issues exist more that 1 year, it easily reproduced on latest RN by placing `FlatList` inside of `ScrollView` and still not fixed

**Comment by joey3060** [comment]
Even I didn't put the FlatList inside ScrollView, the problem still persists.
RN 0.57.0

**Comment by helmerdavila** [comment]
> > For those of you that use `native-base`, enclosing FlatList between `<Content>` causes this issue.
> > Replacing the `<Content>` with `<View>` solved the issue in my case.
> 
> There could also be issues when FlatList is inside another ScrollView.

You saved my life man. 👍 💯

**Comment by kidmysoul** [comment]
My case is , this bug (onEndReached called onLoad) only happened in iphone X simulator .

 When I changed to iphone7, this bug disappeared.

**Comment by Prozhou** [comment]
is there anybody care this problem.

**Comment by kidmysoul** [comment]
@Prozhou 
Yes, I cared. because it doesnot work well on iphoneX

**Comment by levi-beers** [comment]
RN 0.59.2 and this is still a problem.

**Comment by spyshower** [comment]
This is a very mind-blowing thing for them to fix. I am sure we gonna have to wait another 2-3 years for it.

**Comment by RealSilo** [comment]
Pretty annoying.

**Comment by guoliang1206** [comment]
Still has onEndReached bug, can not works well as the document said.

**Comment by stageover** [comment]
> `constructor(props){
> super(props);
> this.state = {
> flatListReady:false
> }
> }
> 
> _scrolled(){
> this.setState({flatListReady:true})
> }
> 
> loadMore = () => {
> if(!this.state.flatListReady){ return null}
> 
> //you can now load more data here from your backend
> 
> }
> <FlatList
> onScroll={this._scrolled.bind(this)}
> style={{width:'100%',flexGrow:1}}
> ListHeaderComponent={this.headerComponent}
> data={this.props.data}
> renderItem={this.renderItem}
> keyExtractor={(item,index) => index }
> onEndReached={(x) => {this.loadMore()}}
> onEndReachedThreshold={0.5}
> 
> ```
>        />
> ```
> 
> `

this works for me

**Comment by dellwatson** [comment]
the bug is still exist anyway, using Expo 34 --> RN 0.59.8

**Comment by ifsnow** [comment]
https://github.com/ifsnow/react-native-infinite-flatlist-patch

I made a patch library to help with this issue. I hope this helps.

**Comment by Samide47** [comment]
the problem still exists in latest version of RN

**Comment by sahrens** [comment]
Sorry for the bug and the radio silence here.

I finally dug into this and I believe the issue is indeed a race between `onLayout` and `onContentSizeChange`, which in general should be fine because there is no expectation of ordering between the two, and only causes issues with certain configurations.

The bug can be triggered if `initialNumToRender` is smaller than needed to fill past the `onEndReachedThreshold` (say the default, 10, is only 580px tall, but it takes 15 to reach the threshold). This will cause an incrementally render of more items to try and fill the viewport. The problem is that if the `onLayout` comes back before the first `onContentSizeChange`, it will first do the state increment to render 20 items and then the stale `onContentSizeChange` callback from 10 items will fire and we'll think that the content size for 20 items is 580px when in fact it's 1160px (which is past the threshold). If those 20 items are also all of our available data, then we'll call `onEndReached` because we think we've rendered everything and are still within the `onEndReachedThreshold`.

The fundamental problem here is the system getting confused when a stale async `onContentSizeChange` comes in after increasing `state.last`. I wish there was a concrete timeframe, but Fabric will give us more flexibility to do things synchronously so hopefully we can avoid class of issues once that roles out.

There are a few workarounds you can try while you wait for a proper fix to be released:

1) Provide the `getItemLayout` prop so the list doesn't have to rely on async layout data (you should do this whenever possible anyway for better perf). e.g. for the original snack example, you can just add `getItemLayout={(d, index) => ({length: 58, offset: 58 * index, index})}` since all the rows are height 58 and the issue will no longer repro. Note this is fragile and must be kept in sync with UI changes, a11y font scaling, etc - a more robust approach could be to render a single representative row offscreen and measure it with `onLayout` then use that value.
2) If `getItemLayout` is not feasible to compute for your UI, increase `initialNumToRender` to cover the `onEndReachedThreshold`.
3) And/or add your own logic to protect against extra calls to `onEndReached` as others have suggested.

**Comment by sahrens** [comment]
This should be fixed in https://github.com/facebook/react-native/commit/8ddf231306e3bd85be718940d04f11d23b570a62

**Comment by yasir-netlinks** [comment]
Hi guys, I am having the same problem too, but I have noticed this happening. On initial load when the array of data is of length `0` (no data), the `onEndReached` doesn't trigger. But on subsequent navigation to this screen and the array is already populated with some data, I see that it triggers `onEndReached` (with no scroll, on load)
The array is kept cuz I didn't want clear the array in reducer upon `FETCH_DATA` action, cuz if there is some data previously fetched already, should be shown instead of the loader.

**Comment by dpossamai** [comment]
> For those of you that use

This save my day! Thanks!

**Comment by Stevemoretz** [comment]
It's not fixed yet and it's a horrible bug, I tried the solutions like flag and stuff but on different items for flatlist I got different results so the whole thing is useless

**Comment by jbromberg** [comment]
Still having this bug.

**Comment by Stevemoretz** [comment]
I literally deleted this feature from my app and added some item add the footer saying load more items...clicking that would load more items.Well it's terrible but at least I know it always works. Unlike the onEndReached which does wathever it wants whenever it wants and doesn't do anything it doesn't want to do.

**Comment by seyaobey** [comment]
Still having bug, it has been literally 3 years!!

**Comment by ELiHimself** [comment]
+ the bug is still there....

**Comment by Stevemoretz** [comment]
Fixed it, that function returns an object it has distanceProp or something like this in it, just put a if statement to check if that is bigger than 0.

It gets fixed :)

**Comment by ELiHimself** [comment]
> Fixed it, that function returns an object it has distanceProp or something like this in it, just put a if statement to check if that is bigger than 0.
> 
> It gets fixed :)

I am not so sure you are right, i am console loging the distanceFromBottom val you are talking about when the callback triggers. First of all it is not consistant, secondly its never 0 always under at least for my case.

**Comment by Stevemoretz** [comment]
add these props to FlatList: 
```js
                      onEndReachedThreshold={0.5}
                      onEndReached: (d) => {
                          if (d.distanceFromEnd > 0) {
                               console.log("onEndReached");
                          }
                      },
```

Let me know if this fixes your issue.

**Comment by ELiHimself** [comment]
> add these props to FlatList:
> 
> ```js
>                       onEndReachedThreshold={0.5}
>                       onEndReached: (d) => {
>                           if (d.distanceFromEnd > 0) {
>                                console.log("onEndReached");
>                           }
>                       },
> ```
> 
> Let me know if this fixes your issue.

This seems to work fine to prevent the initial load issue, however after the first load more the infinite loop issue still exists.

**Comment by Stevemoretz** [comment]
What's the infinite loop issue?

**Comment by 1061750360** [comment]
> ```js
> d.distanceFromEnd > 0
> ```

thank you，it is useful for me.And I think it will help others too!

**Comment by 1061750360** [comment]
> > add these props to FlatList:
> > ```js
> >                       onEndReachedThreshold={0.5}
> >                       onEndReached: (d) => {
> >                           if (d.distanceFromEnd > 0) {
> >                                console.log("onEndReached");
> >                           }
> >                       },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if this fixes your issue.
> 
> This seems to work fine to prevent the initial load issue, however after the first load more the infinite loop issue still exists.


thank you，it is useful for me.And I think it will help others too!

**Comment by Martinnord** [comment]
@Stevemoretz's solution worked great for me. Thank you.

**Comment by fabOnReact** [comment]
https://github.com/ifsnow/react-native-infinite-flatlist-patch/tree/master/patches does not support rn versions > 0.68.
Do you still experience this issue? Should I work on this? Thanks
