### ISSUE TITLE
Support flow experimental.const_params=true

### ISSUE THREAD

**Issue by ckknight** [facebook/react-native#16228]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  6.11.2
  Yarn:  1.1.0
  npm:  3.10.10
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4

### Steps to Reproduce

(Write your steps here:)

1. Create a new react-native app with create-react-native-app
2. `yarn add --dev flow-bin@^0.49.1` (same version specified in `.flowconfig`)
3. Add `experimental.const_params=true` under `[options]` in `.flowconfig`
4. `./node_modules/.bin/flow`

### Expected Behavior

`No errors.`

(Write what you thought would happen.)

### Actual Behavior

```
$ flow
node_modules/fbjs/lib/UnicodeBidi.js.flow:90
 90:   fallback = fallback || UnicodeBidiDirection.NEUTRAL;
       ^^^^^^^^ fallback. const param cannot be reassigned (see experimental.const_params=true in .flowconfig)
 89: function resolveBlockDir(str: string, fallback: ?BidiDirection): BidiDirection {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^ const param fallback

node_modules/fbjs/lib/UnicodeBidi.js.flow:92
 92:     return fallback;
                ^^^^^^^^ null. This type is incompatible with the expected return type of
 89: function resolveBlockDir(str: string, fallback: ?BidiDirection): BidiDirection {
                                                                      ^^^^^^^^^^^^^ string enum

…[removed for brevity]…

... 88 more errors (only 50 out of 138 errors displayed)
To see all errors, re-run Flow with --show-all-errors
```

### Reproducible Demo

https://github.com/ckknight/ReactNative-const_params-repro

**Comment by ckknight** [comment]
This also affects react-native@0.49.0

**Comment by janicduplessis** [comment]
Some of there errors seem to come from RN dependencies (fbjs from the sample you provided). I think it would be nice to fix but will require changing stuff across repos. If someone want to send a PR to fix some errors that are in this repo it would be nice.

**Comment by rajsek** [comment]
Hi @janicduplessis: I am a beginner in opensource contribution and like to work on this.
Could you please guide me to fix this issue?

**Comment by TakaGoto** [comment]
@janicduplessis would like to work on this since it seems like an easy one for first timer. just to clarify, this would be to add `experimental.const_params=true` to react-native's `.flowconfig` and find/fix all the ones it outputs.

**Comment by klvs** [comment]
I have a PR inbound for this. Should be submited today or tomorrow.

**Comment by klvs** [comment]
@TakaGoto I'll tag you in my PR in case you'd like to submit any changes as well. You need to clone this repo, enable experimental.const_params and run flow. Most of the errors are fixed with a minor refactor.

**Comment by TheSavior** [comment]
I really really want to do this. Unfortunately, we have a monorepo at facebook and everything is under a single flow config. If we merge this, it wouldn't change how flow treats these files internally and we'd be likely to break flow for everyone in open source.

Fortunately, I actually wrote a pretty intensive codemod to do it at Facebook so we could convert our entire codebase and turn this flow config on. Unfortunately, there is an issue with the codemod that has kept me from converting our entire codebase. The codemod erroneously converts:

function foo(myVar) {
  var myVar = 2; // valid shadowing of the function argument
}
into

function foo(myVar) {
  let localMyVar = myVar;
  var localMyVar = 2; // Uncaught SyntaxError: Identifier 'localMyVar' has already been declared
}
If you would be interested in detecting this scope issue and getting the codemod to handle it, we'd be able (and happy) to make this change to react native. The codemod would of course also be open source then. :)

**Comment by klvs** [comment]
Very interesting. I'll take a look, thanks!

**Comment by TheSavior** [comment]
Silly bot

**Comment by kelset** [comment]
👋 there - this issue is still technically "not fixed", for the reason Eli explained above.

Basically every instance similar to this in the main codebase
```
function foo(arg) {
  arg += 2;
  console.log(arg);
}
```

would need to be changed to

```
function foo(arg) {
  let localArg = arg;
  localArg += 2;
  console.log(localArg);
}
```

There is a codemod Eli worked on -> https://github.com/cpojer/js-codemod/pull/85 which would help a lot in automating this process, but there is a 1% cases in which it would conflict.

So, all in all, there is a lot of work related to "code hygiene" - we'd love to see some PRs to help with this effort but it's really low prior right now. So I'm going to close it as there are more important tasks to focus on.
