### ISSUE TITLE
`npm starts` hangs on 'Loading dependency graph, done.'

### ISSUE THREAD

**Issue by mikeborozdin** [facebook/react-native#16798]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.3871768

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

(Write your steps here:)

1. `react-native init MyApp`
2. `cd MyApp`
3. `npm start`

### Expected Behavior

1. The browser opens with my app

### Actual Behavior

1. Nothing happens

**Comment by comeonbuddy** [comment]
I have the same issue here :(

**Comment by EladZemingo** [comment]
Me too

**Comment by andela-ojoloko** [comment]
Me too

**Comment by N3TC4T** [comment]
Same here ...

**Comment by Gokul-11** [comment]
I got the same problem, anyone suggested me any solution

**Comment by anerivala** [comment]
Having the same Problem!!!

**Comment by adamchenwei** [comment]
same problem

**Comment by adamchenwei** [comment]
why for 30 days no one care lol, btw I am using `create-react-native-app`

**Comment by ervinne13** [comment]
solved this by not bothering with npm start but using yarn start instead

**Comment by HDaghash** [comment]
same issue

**Comment by adamchenwei** [comment]
actually realize its NOT hanging, its running, you just need to run the simulator also in the root level lololol

**Comment by DiegoFelipe** [comment]
same issue with me

**Comment by gdbhosale** [comment]
@adamchenwei What exactly to do ? Can you elaborate. I am new to React Native.

**Comment by adamchenwei** [comment]
something similar to what is been said in this tutorial https://developer.telerik.com/topics/mobile-development/launch-android-emulators-ios-simulators-command-line/

**Comment by goodok21** [comment]
@adamchenwei so, what is next? now running two windows: the terminal and the iOS emulator. that, the wise man, the councils were over?

**Comment by goodok21** [comment]
in terminal in root of the project:
`react-native upgrade` - it generates 'IOS' and 'Android' folders again
`react-native link`
`react-native run-ios`

**Comment by adamchenwei** [comment]
@goodok21 something similar to `react-native run-ios --simulator="iPhone 4s"`

**Comment by goodok21** [comment]
@adamchenwei something similar to lol what?

**Comment by adamchenwei** [comment]
sorry, what I meant is that you should be able to run this command in your root, so your simulator can be initiated,and your project gets to load into the simulator. React Native does NOT produce a browser version testable app (so far I know), ReactXP does though, but, that's another story.

**Comment by adamchenwei** [comment]
https://facebook.github.io/react-native/docs/running-on-simulator-ios.html

**Comment by alande-amorim** [comment]
@ervinne13 's answer did the trick for me

**Comment by ashikazeez** [comment]
I have same issue:
OS :Ubuntu 16.04 LTS
Memmory:7.3GiB
OS type:64-bit
i also installed java,node with npm,
then-- install:
sudo npm install -g react-native-cli
react-native init Sample
react-native run-android
react-native start
 after these code showing 

"Looking for JS files in
   /mnt/20C8E761C8E73426/React native/Sample 
Metro Bundler ready.
Loading dependency graph, done."
 not working.....

**Comment by thedanielvogelsang** [comment]
Was this issue ever closed? I'm having the same problem.

**Comment by imranparuk** [comment]
Also having this issue

**Comment by goodok21** [comment]
@thedanielvogelsang

react-native init MyApp
cd MyApp
yarn
react-native run-ios

or ‘react-native run-android’

**Comment by jass-trix** [comment]
try to disable remote JS Debugging
it works for me :/
it seems it has already running but the simulator doesn't respond

**Comment by samcorcos** [comment]
I deleted `node_modules`, ran `npm i` again, then `react-native run-ios` and it worked fine.

**Comment by TETRA2000** [comment]
Same thing happened for me. (v0.53.3)
But after I reinstalled watchman, it resolved. 😺

**Comment by timbarden** [comment]
I've been having this problem and I simply don't understand what I need to do. Tried a bunch of things listed above but nothing works. What is the definitive process here?

**Comment by zaro** [comment]
Same thing here. Funny thing is my project was working just fine.
haven'y updated it couple of months, and now it doesn't work at all.

**Comment by JustinReport** [comment]
I got same issue. but not solved. help me please

**Comment by david-fournier-smartnsoft** [comment]
Same issue here

**Comment by angelomichel** [comment]
Same issue here too.

Tried removing/reinstalling watchman, the watchmen watch-del-all, removing node_modules and npm i again, rebooting macos. It started failing when I tried installing a dependency (npm), I removed/reverted that code but I can never run my app any more... 

Everyone has different solutions to the issue, but none worked for me

**Comment by saravanakumargn** [comment]
Make sure in Android emulator Wifi is Turned on

**Comment by gersonmontenegro** [comment]
I've did all the things that you describe before, and nothing happened. For now, is not an option for me stop my project, so I run 
`react-native run-android`
or
`react-native run-ios`
and the project run directly on the device in a good way, but the debugging part is painful, but at least is a real option.

**Comment by Chipped1** [comment]
I have the same issue, and I'm using Windows 10, so I can't run the iOS emulator

**Comment by gersonmontenegro** [comment]
I don't know you can run the app in a iOS emulator from Windows, usually is not possible.

**Comment by diegosiao** [comment]
Make sure localhost is included as an exception in NSAppTransportSecurity in **Info.plist** file of the iOS project.

```
        <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by bbing** [comment]
if you've tried everything but still not worked , reboot your computer

**Comment by mic-kul** [comment]
Had same problem, finally when tried to start it on the real device realised that I need to update my iOS version:
`react-native run-ios --device "iPhone" # with connected device`
resulted in following error:```
]  iPhoneConnect: ## Unable to mount developer disk image, (Error Domain=com.apple.dtdevicekit Code=601 "Could not locate device support files." UserInfo={DeviceType=iPhone9,3, NSLocalizedDescription=Could not locate device support files., NSLocalizedRecoverySuggestion=This iPhone 7 (Model 1660, 1778, 1779, 1780) is running iOS 11.3.1 (15E302), which may not be supported by this version of Xcode.}) {```

Matching versions of XCode and iOS did the job 🎉

**Comment by kevinNejad** [comment]
I recommend use Yarn instead of npm.
in most of the cases, removing your node-modules folder and reinstalling and rebuilding your project may fix the problem. 
Make sure you reset your cache and clear your watchman as well. 
you can even try clean your project in XCode and build it using XCode.

**Comment by RedEarthBlueSky** [comment]
To echo samcorcos delete the node_modules folder and npm i worked for me

**Comment by enjeyw** [comment]
None of the above fixes worked for me, but I noticed on my android device there was actually an error message to the effect of
`Native module [NAME] tried to override [NAME]  for module name [OTHER NAME] `. 
Googling this led me to a different [issue](https://github.com/rebeccahughes/react-native-device-info/issues/243), where the suggested fix was to go to the MainApplication.java file (in android/app/src/main/java/com/appname) and remove any duplicate imports and overides. This fixed the problem :)

**Comment by dvdobrovolskiy** [comment]
same issue

hangs on
Loading dependency graph, done.


even in absolutely new sample (react-360 init test)

**Comment by yahya-pondokit** [comment]
Same issue here

**Comment by Asinox** [comment]
Just reinstall Watchman

**Comment by Joaquimdcp** [comment]
Same issue here

**Comment by samiede** [comment]
Any updates on this?
Strangely, for me it works in the genymotion emulator, after I've pointed it to the right adb folder, I just really really prefer the official emulator.

**Comment by mrabdullahsahin** [comment]
I also had the same problem. After **ejecting** a project on **React Native**, I typed **"npm start"** and it said **"loading dependency graph, done"** and stayed like that. But after typing **"npm run ios"** instead of **"npm start"** my problem was solved. iOS simulator and metro bundler run successfully.

**Comment by Fuseteam** [comment]
that's not solving, that a work around using the ios simulator
the issue remains "npm start" doesn't work

**Comment by MrgSub** [comment]
Basically, from what I see, this happens after ejecting or building your iOS
You won't be able to use `npm start`, you will need to build and run the app on a simulator.
You won't have livereload as an option so rip

Correct me if I'm wrong.

**Comment by geek-ibrar** [comment]
Was facing the same issue, just run 
`watchman watch .`
and then 
`react-native start`

it worked for me :)

**Comment by thefakhreddin** [comment]
@adamchenwei
you're a true lifesaver. txn in adv.

**Comment by williscool** [comment]
Leaving this here for future self if working on a react app with windows subsystem for linux (wsl).

So you can't run `react-native start-android` because the deploying of the android app will fail (java path is wrong and a whole host of other things)

BUT YOU CAN 

Build the app with android studio deploy it to your emulator or phone then

run `react-native start`

The `Loading dependency graph, done`

Message... means THE SERVER IS RUNNING!

Everything is good you just need to make sure adb is running in windows and

```
adb reverse tcp:<PORT> tcp:<PORT>
```

Then you can run your app.

(Also if you get a blank white screen in the app on your phone just kill the app and do the shake to reload thing. You'll know its working when the app finally makes a request to the react-native server on your laptop)

But here is my ask to the react native team.

Can ya pls have a better server is ready message lol?

**Comment by pblUSA** [comment]
Weird. I had the same issue when running on device and on emulator. I got it resolved by double tapping 'r' while on the emulator. Doesn't really seem like a reasonable fix (not sure why the `yarn start` stops after `Loading dependency graph, done.`)but you can try if that works

**Comment by Jopaul07** [comment]
If you're getting this loading error while running 'react-native run-ios' or building through xcode then try 'react-native run-android' after connecting an android device to your pc.
If not happening try deleting node-modules and 'npm install'.

**Comment by LakshitF** [comment]
> 
> 
> actually realize its NOT hanging, its running, you just need to run the simulator also in the root level lololol

Hey can you please explain what do you mean by this...I am not able to fix this issue

**Comment by vdaranyi** [comment]
This solved it for me: https://www.youtube.com/watch?v=Z_JH9_ZMj-M

**Comment by Saad9624** [comment]
nothing works for me

**Comment by Saad9624** [comment]
okay so it is because when you create or start a server it changes its ip first you have to confirm the ip address of your system and then put it into the in app dev setting host address
hopes its work for all
