### ISSUE TITLE
KeyboardAvoidingView has no effect on multiline TextInput

### ISSUE THREAD

**Issue by peacechen** [facebook/react-native#16826]
KeyboardAvoidingView only works with single-line TextInputs.  When the `multiline` prop is set, KeyboardAvoidingView does not shift the TextInput at all.

### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  7.0.0
    npm:  3.10.8
    Watchman:  4.7.0
    Xcode:  9.1

  Packages: (wanted => installed)
    react-native: 0.49.3
    react: 16.0.0-beta.5

  Target Platform: iOS (10.3)

### Steps to Reproduce

1. Use a `<TextInput>` component with `multiline` prop set.
2. Wrap this in a ScrollView
3. Wrap that in a KeyboardAvoidingView.

### Expected Behavior

Multiline TextInput should scroll above the soft keyboard.

### Actual Behavior

Soft keyboard covers multiline TextInput.

### Reproducible Demo

```
import React, { Component } from 'react';
import { Text, TextInput, View, ScrollView, KeyboardAvoidingView, Keyboard} from 'react-native';

...

	render() {
		return (
			<KeyboardAvoidingView style={{flex:1}} behavior="padding" keyboardVerticalOffset={64}>
				<ScrollView keyboardShouldPersistTaps={'handled'}>
					<View style={{padding: 12}}>
						// various content to fill the page
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 1</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 2</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 3</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 4</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 5</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 6</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 7</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 8</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 9</Text>
						<Text style={{fontSize: 20, padding: 40}}>MESSAGE 10</Text>
					</View>
					<TextInput
						style={{padding: 4}}
						multiline={true}
						placeholder={'Type something here...'}
						onChangeText={this.updateMessage}
						value={this.state.message}
					/>
				</ScrollView>
			</KeyboardAvoidingView>
		);
	}

```

**Comment by vivalaakam** [comment]
I have a similar issue

### Environment

node: 8.9.1
react: 16.0.0
react-native: 0.50.3

### Steps to Reproduce

1. Use a `<TextInput>` component with `autoCorrect="false"` prop.
2. Wrap that in a KeyboardAvoidingView with `behavior="position"` prop.
3. Change keyboard type to Emoji keyboard

###Expected Behavior

Multiline TextInput should be above the soft keyboard.

###Actual Behavior

Soft keyboard covers TextInput.

### Reproducible Demo

https://github.com/vivalaakam/react-native-issue

**Comment by vivalaakam** [comment]
`Keyboard.addListener('keyboardWillChangeFrame', this.onKeyboardChange)` doesn't`t fire when I change keyboard to emoji and fires when I change from emoji to other

**Comment by jibberilins** [comment]
KeyboardAvoidingView works fine with multiline TextInput because i am using them myself. Initially they would not work for me. To solve my problem i removed the height on the TextInput and set the behavior to "padding". The "flex: 1" you have on the  KeyboardAvoidingView might be the problem i think or its the scrollview. But KeyboardAvoidingView definitely works fine with multiline.

**Comment by peacechen** [comment]
Referring to my snippet posted above, there's no height on the TextInput and KeyboardAvoidingView's behavior is set to padding.

Its style needs `flex:1` to allow the ScrollView to take up the entire height.

Try the code with and without multiline set.  It fails with multiline set, but the same code works for single line TextInputs.

**Comment by hoscarcito** [comment]
Same problem here!

**Comment by fadlykayo** [comment]
@peacechen I have exactly the same problem like you. Need to add flex: 1 for the ScrollView as the wrapper. And it works if I remove the prop multiline={true}. Any solution for this?

**Comment by sherxia92** [comment]
The same issue。
my code is same as the author. there is a multiline TextInput in ScrollView. outsider with a KeyboardAvoidingView Wrapper.

**Comment by monmonja** [comment]
If anyone still is looking for a fix, you could try
`<View style={{position:relative}}>
     <TextInput ref='multilineText' value={this.state.textValue} 
           onChangeText={(textValue) => this.setState({textValue})}/>
     <TextInput style={{ color:'transparent', position: 'absolute', width: '100%', height: '100%' }}
           placeholderTextColor='transparent'
           onFocus={() => setTimeout(() => this.refs.multilineText.focus(), 1000) } 
           value={this.state.textValue}
           onChangeText={(textValue) => this.setState({textValue})}
      />
</View>
`
Its a dirty hack but it does the job, what it does it when user clicks on the input it would be clicking on the single line and the keyboard will scroll to that line then after 1 seconds (you can adjust this, i just found 1 seconds to be good with our app) it would focus on the multiline. The value and onChangeText makes sure that when the user star typing they would have the same value except the single line has transparent text.

The downside is when a user clicked the multiple line, the cursor wont go to the location they clicked but it would go to the end.

**Comment by peacechen** [comment]
@monmonja  That's a creative work-around.  I wonder if it could also be done by setting the `multiline` to a state variable that is changed during `onFocus`.  That would eliminate the second `TextInput`.

I don't see the multiline prop in the first TextInput, but I assume it's supposed to be in there.

**Comment by kfroemming** [comment]
Has anyone found a good solution for this?

**Comment by chmielot** [comment]
@peacechen I tried to implement your suggestion but it has a strange effect and doesn't work. Something's flickering and the keyboard eventually disappears.
I am also looking for a solution to this. Cannot apply @monmonja 's workaround because I'm using redux-form. This makes it much more complicated for this workaround.
I can confirm that all is working fine when I remove the multiline prop. I wrapped the whole application with KeyboardAvoidingView and my multiline TextInput is at the end of the form like in the author's example.

**Comment by Hsuer** [comment]
same problem here and still have no solution

**Comment by sndkd** [comment]
I too facing the same issue. It works fine if multiline is set to false and not if set to true. My TextInput does not have any height. _Any solutions_??

**Comment by jasonchoibiz** [comment]
A workaround for this is to make a reference to the parent scrollview and call its scrollTo method to the multilined TextInput coordinates whenever onFocus is called. 

`<KeyboardAvoidingView
   style={styles.container}
   behavior="padding"
>
  <ScrollView ref={component => { this.myScrollView = component; }}>
    <TextInput 
       multiline
       onFocus={() => this.myScrollView.scrollTo({ x: 0, y: 750, animated: true })}
    />
  </ScrollView>
</KeyboardAvoidingView>`

**Comment by lucasboleli** [comment]
same problem here only on IOS
textinput multiline has no effect on keyboardavoidingview

it is working fine on android

**Comment by amsul** [comment]
This has been quite frustrating for us as well.. Seems like the only consistent way to do this is by scrolling manually as @jasonchoibiz suggested.

It's an ugly workaround though! ☹️

**Comment by robertobrogi** [comment]
there is news about this problem?

**Comment by luco** [comment]
Still having this.

**Comment by Bobozee** [comment]
same problem here

**Comment by Jmedders** [comment]
Same issue, here's a simple snack for anyone to play with: https://snack.expo.io/r1qpj0k5Q

**Comment by Bobozee** [comment]
> Same issue, here's a simple snack for anyone to play with: https://snack.expo.io/r1qpj0k5Q

I've tried this and it works:

[https://github.com/baijunjie/react-native-input-scroll-view](https://github.com/baijunjie/react-native-input-scroll-view)

**Comment by linoleum00** [comment]
react-native version 0.56.1
same problem....

**Comment by recepkoseoglu** [comment]
it is working;
`
<KeyboardAvoidingView behavior="padding" style={Platform.OS !== 'android' && { flex: 1 }}>
        <ScrollView>
             ...
             <TextInput ... />
             ...
       </ScrollView>
</KeyboardAvoidingView>
`

**Comment by recepkoseoglu** [comment]
it is working;
`javascript
<KeyboardAvoidingView behavior="padding" style={Platform.OS !== 'android' && { flex: 1 }}> 
  <ScrollView>
      ... 
      <TextInput ... />
      ...
  </ScrollView>
</KeyboardAvoidingView>
`

**Comment by recepkoseoglu** [comment]
it is working;
```javascript
<KeyboardAvoidingView behavior="padding" style={Platform.OS !== 'android' && { flex: 1 }}> 
  <ScrollView>
      ... 
      <TextInput ... />
      ...
  </ScrollView>
</KeyboardAvoidingView>
```

**Comment by luco** [comment]
@recepkoseoglu It works on non-multiline Inputs. Try on multiline.

**Comment by recepkoseoglu** [comment]
> @recepkoseoglu It works on non-multiline Inputs. Try on multiline.
Yes you are right. Working for multiline following :smile:

```javascript
Platform.OS === 'android' ? (
  <ScrollView style={{ flex: 1 }}>
    <KeyboardAvoidingView  >
       ... 
      <TextInput ... />
      <TextInput ... />
      <TextInput ... />
      <TextInput ... />
      ...
    </KeyboardAvoidingView>
  </ScrollView>
  ) : (
    <KeyboardAvoidingView behavior="padding"  style={{ flex: 1 }}>
       <ScrollView>
         ... 
         <TextInput ... />
         <TextInput ... />
         <TextInput ... />
         <TextInput ... />
         ...
      </ScrollView>
    </KeyboardAvoidingView>
)

```

**Comment by mk-nickyang** [comment]
It's working if we use `<View>` to wrap the content instead of `<ScrollView>`, not ideal if you have many TextInputs though.
```
<KeyboardAvoidingView
    behavior={Platform.OS === "ios" ? "padding" : null} 
    style={{ flex: 1 }}
>
    <View style={{ flex: 1, justifyContent: "flex-end" }}>
        ...
        <TextInput multiline />
        <View style={{ flex: 1 }} /> // Use this to take up bottom spacing
    </View>
</KeyboardAvoidingView>
```

**Comment by thinklinux** [comment]
That's a real pain in the ass :) I have not found a good way to handle multiline inputs in a VirtualizedList.

**Comment by luco** [comment]
No fix yet?

**Comment by ankhanguit** [comment]
RN 0.57... confirm this bug still there.

**Comment by boraerbasoglu** [comment]
still same issue here. any solution?

**Comment by matteocollina** [comment]
I switched to "[React-Native Keyboard Manager](https://github.com/douglasjunior/react-native-keyboard-manager)" and it works. Just install and your issues are solved

**Comment by kfroemming** [comment]
This is really causing a lot of problems. Any updates on this issue? I have tried using the libraries mentioned above but each of them come with sacrifices in user experience.

**Comment by noll-fyra** [comment]
Same here. With multiline applied, KeyboardAvoidingView doesn't work.

**Comment by raffjones** [comment]
Just hit this exact problem, and can confirm that KeyboardAvoidingView has no effect at all with any behaviour attribute option if the View contains a multiline TextInput

**Comment by franzwarning** [comment]
Super annoying. Any resolve here?

**Comment by compojoom** [comment]
I tried to debug this today without much success. What I found out however is that _onKeyboardChange is triggered no matter if we have a multiline true or false. In both cases LayoutAnimation receives the same config:
https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L107

I added an onAnimationDidEnd callback to LayoutAnimatijon and it has been called both for multiline true and false. In the case of false - the view was properly updated. In the case of multiline true as per the issue here - no layout change occurs. 

So it seems that the KeyboardAvoidingView component behaves correctly both for multiline true or false, but LayoutAnimation fails to properly animate the position with multiline true.

**Comment by tuzmusic** [comment]
> KeyboardAvoidingView works fine with multiline TextInput because i am using them myself. Initially they would not work for me. To solve my problem i removed the height on the TextInput and set the behavior to "padding". The "flex: 1" you have on the KeyboardAvoidingView might be the problem i think or its the scrollview. But KeyboardAvoidingView definitely works fine with multiline.

Kinda hate to be the only person upvoting this one, but simply setting behavior to `position` worked for me!

**Comment by bob76828** [comment]
If you want to KeyboardAvoidingView works fine with multiline TextInput, 
please setting the scrollEnabled prop to false.
It works for me.

**Comment by dy93** [comment]
> If you want to KeyboardAvoidingView works fine with multiline TextInput,
> please setting the scrollEnabled prop to false.
> It works for me.

It works for me, too

**Comment by lalayueh** [comment]
@bob76828 Thanks for saving my time.

**Comment by peacechen** [comment]
Does that work inside a ScrollView?  Refer to the OP for how it's used in such a case.

**Comment by dy93** [comment]
@peacechen You should use ScrollView inside KeyboardAvoidingView
```
<KeyboardAvoidingView>
  <ScrollView>
    <TextInput
      multiline={true}
      scrollEnabled={false} // to make keyboard avoiding works
    >
    </TextInput>
  </ScrollView>
</KeyboardAvoidingView>
```

**Comment by adteague** [comment]
> Referring to my snippet posted above, there's no height on the TextInput, and KeyboardAvoidingView's behavior is set to padding.
> 
> Its style needs `flex:1` to allow the ScrollView to take up the entire height.
> 
> Try the code with and without multiline set. It fails with multiline set, but the same code works for single line TextInputs.

^ This from @peacechen worked for me perfectly. I have `scrollEnabled={true}` & `multiline={true}`

**Comment by artshevtsov** [comment]
> scrollEnabled={false} // to make keyboard avoiding works
Yep, but if this option enabled, scrolling for this textinput turns off, so it's not suitable if you want to  have textinput with fixed number of lines, eg numberOfLines={3}

**Comment by gbalduzzi** [comment]
@adteague the problem persists when you have a scrollview inside the KeyboardAvoidingView instead of a simple view

**Comment by adteague** [comment]
@gbalduzzi You don't add a ScrollView component. You make the TextInput multiple lines with scrolling enabled. See my code example above.

**Comment by peacechen** [comment]
@adteague 
A ScrollView is needed when the form is longer than the screen height.  Multiple TextInputs live within the ScrollView.  Does your approach solve that use case?

**Comment by adteague** [comment]
@peacechen No it would not. Try...

```
<KeyboardAvoidingView
  behavior="height"
  style={{flex: 1, flexDirection: "column"}}
>
  <ScrollView style={{flex: 1}}>
    <TextInput
        multiline={false}  // Default is false so you can remove this line
        scrollEnabled={false} // Default is false so you can remove this line
        style={{flex: 0}}
        // Other relevant props
      />

      <TextInput
        style={{flex: 0}}
        // Other relevant props
      />
  </ScrollView>
<KeyboardAvoidingView />
```

**_(Not on my dev computer so sorry if it doesn't works)_**

**Comment by peacechen** [comment]
That's the same structure as the code snippet in the OP, which results in the multiline TextInput bug.

**Comment by gbalduzzi** [comment]
@adteague My whole screen is wrapped by a KeyboardAvoidingView and, inside that, I have a Scrollview because the content is long and need to be scrolled.

At the end of the screen, I have a multiline textinput. On iOS, when the user tap on the text input it opens the keyboard without moving the input. If i set `multiline={false}`, it works perfectly.

The overall structure is the following:
```
<SafeAreaView style={{flex: 1}}>
          <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : null} style={{flex: 1}}>
               <ScrollView style={{flex: 1}} contentContainerStyle={{flexGrow: 1}}>
                       // Some other stuff
                       <TextInput style={{width: 200, height: 300}} multiline={true} scrollEnabled={false} />
               </ScrollView>
          </KeyboardAvoidingView>

</SafeAreaView>
```

**Comment by artshevtsov** [comment]
@gbalduzzi try doing this way: 

```
<KeyboardAvoidingView
      enabled
      behavior={ Platform.OS === 'ios' ? 'padding' : false }
      style={{ flex: 1}}
    >
      <ScrollView
        keyboardShouldPersistTaps={'always'}
        keyboardDismissMode={ Platform.OS === 'ios' ? 'interactive' : 'on-drag'}
      >
              <TextInput style={{width: 200, height: 300}} multiline={true} scrollEnabled={false} />
      </ScrollView>
</KeyboardAvoidingView>
```

Keyboard will hide on swipe to top in interactive mode on ios, and KeyboardAvoidingView should scroll to multiline textInput. Android also should be ok.

**Comment by nicoferreyra** [comment]
> If you want to KeyboardAvoidingView works fine with multiline TextInput,
> please setting the scrollEnabled prop of TextInput to false.
> It works for me.

This one worked for me! Thanks bob76828

**Comment by raygerrard** [comment]
This is still an issue on 0.61.4

**Comment by thijs-qv** [comment]
No fix yet? This issue is over two (2) years old now...

**Comment by luco** [comment]
@bob76828 Super thanks a lot man!!!

**Comment by dozoisch** [comment]
Not stale

**Comment by kuldeepworkid** [comment]
> > Same issue, here's a simple snack for anyone to play with: https://snack.expo.io/r1qpj0k5Q
> 
> I've tried this and it works:
> 
> https://github.com/baijunjie/react-native-input-scroll-view

This Really worked for me. Thanks

**Comment by errawn** [comment]
still unfixed 😭

**Comment by willymulyana** [comment]
> If anyone still is looking for a fix, you could try
> 
> ```
> <View style={{position:relative}}>
>     <TextInput ref='multilineText' value={this.state.textValue} 
>         onChangeText={(textValue) => this.setState({textValue})}/>
>     <TextInput style={{ color:'transparent', position: 'absolute', width: '100%', height: '100%' }}
>         placeholderTextColor='transparent'
>         onFocus={() => setTimeout(() => this.refs.multilineText.focus(), 1000) } 
>         value={this.state.textValue}
>         onChangeText={(textValue) => this.setState({textValue})}
>     />
> </View>
> ```
> 
> Its a dirty hack but it does the job, what it does it when user clicks on the input it would be clicking on the single line and the keyboard will scroll to that line then after 1 seconds (you can adjust this, i just found 1 seconds to be good with our app) it would focus on the multiline. The value and onChangeText makes sure that when the user star typing they would have the same value except the single line has transparent text.
> 
> The downside is when a user clicked the multiple line, the cursor wont go to the location they clicked but it would go to the end.

Thanks, it works for me. I add `caretHidden={true}` for transparent `TextInput` to hide its cursor.

**Comment by colinfwren** [comment]
> If anyone still is looking for a fix, you could try
> 
> ```
> <View style={{position:relative}}>
>     <TextInput ref='multilineText' value={this.state.textValue} 
>         onChangeText={(textValue) => this.setState({textValue})}/>
>     <TextInput style={{ color:'transparent', position: 'absolute', width: '100%', height: '100%' }}
>         placeholderTextColor='transparent'
>         onFocus={() => setTimeout(() => this.refs.multilineText.focus(), 1000) } 
>         value={this.state.textValue}
>         onChangeText={(textValue) => this.setState({textValue})}
>     />
> </View>
> ```
> 
> Its a dirty hack but it does the job, what it does it when user clicks on the input it would be clicking on the single line and the keyboard will scroll to that line then after 1 seconds (you can adjust this, i just found 1 seconds to be good with our app) it would focus on the multiline. The value and onChangeText makes sure that when the user star typing they would have the same value except the single line has transparent text.
> 
> The downside is when a user clicked the multiple line, the cursor wont go to the location they clicked but it would go to the end.

From an automation perspective (using Appium) this works, you just need to make sure you put the testID/accessibilityLabel on the hidden input so that the actions are carried out against that instead of the visible one.

I had to reduce the timeout to 100ms instead of the full second as this was causing issues with the text entry as it would miss characters.

**Comment by nguyenduy2392** [comment]
textinput will hidden when input too many line on scroll view? it only android. i must allway add height for textinput
any solution for this bug ?
```
<ScrollView>
                    <View style={styles.container}>
                        <TextInput
                            onChangeText={(text) => {
                                this.setState({ moTa: text })
                            }}
                            value={this.state.moTa}
                            multiline={true}
                            scrollEnabled={false}
                            placeholder='Nhập thông tin mô tả'
                            style={styles.input}
                        />
                    </View>
                </ScrollView>

input: {                     
        ...(Platform.OS == 'android' ? { height: themes.screen.height - 400 } : {}),
        fontSize: 18,
        textAlignVertical: 'top', fontFamily: themes.fontFamily
    },
```

**Comment by a-eid** [comment]
this still is an issue with `63.4`

**Comment by Sujan4k0** [comment]
Bumping this - setting `scrollEnabled` to `false` works, but it seems like an indirect fix to an underlying issue.

**Comment by akichim21** [comment]
https://github.com/facebook/react-native/issues/16826#issuecomment-521978128

> Yep, but if this option enabled with eg numberOfLines={3}, we have multiline textinput without scrolling which is not so good for forms with lots of other fields

this still is an issue with RN 0.63.4.
It's fine if delete numberOfLines props.

**Comment by castalonirenz** [comment]
i tried setting scrollEnabled to false but when you keep typing it return an error.


![image](https://user-images.githubusercontent.com/13584669/114499408-9b361500-9c58-11eb-8028-4732c04828c4.png)

**Comment by minhna** [comment]
This works best for me:
```
import { SafeAreaView } from 'react-native-safe-area-context';

<SafeAreaView style={{ flex: 1 }}>
  <ScrollView>
    <TextInput
      multiline
      scrollEnabled={false}
    />
  </ScrollView>
</SafeAreaView>
```

**Comment by aprilmintacpineda** [comment]
This is still an issue, I'm using `React-native 0.64.2`, putting `scrollEnabled={false}` is not really a good idea when you are using a text input with a fixed height, because you want the user to actually be able to scroll through the text input.

**Comment by Darpsoft** [comment]
This worked for me 
```javascript
import React from "react";
import { Platform, TextInput, KeyboardAvoidingView, ScrollView } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const Component = (params) => {
  return (
    <SafeAreaView style={{ flex: 1 }} edges={["right", "bottom", "left"]}>
      <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}>
        <ScrollView>
          <TextInput multiline scrollEnabled={false} />
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

```

**Comment by jetako** [comment]
This solution leverages the scrollEnabled hack but reenables scroll after the keyboard appears. You just need to set the height precisely because partial lines are hidden when `scrollEnabled={false}`

```
import React, { useState, useRef, forwardRef } from 'react'
import { TextInput } from 'react-native'

export const TextArea = forwardRef((props, ref) => {
  const { onFocus, onBlur, ...inputProps } = props
  const [scrollEnabled, setScrollEnabled] = useState(false)
  const scrollEnabledTimerRef = useRef()

  return (
    <TextInput
      ref={ref}
      multiline
      scrollEnabled={scrollEnabled}
      onFocus={e => {
        scrollEnabledTimerRef.current = setTimeout(() => setScrollEnabled(true), 800)
        onFocus?.(e)
      }}
      onBlur={(e) => {
        clearTimeout(scrollEnabledTimerRef.current)
        setScrollEnabled(false)
        onBlur?.(e)
      }}
      {...inputProps}
    />
  )
})
```

**Comment by codal-mpawar** [comment]
https://github.com/facebook/react-native/issues/16826#issuecomment-528578462 work for me Thanks for the help

**Comment by vanenshi** [comment]
We need a hero

**Comment by jimuelpalaca** [comment]
> This worked for me
> 
> ```js
> import React from "react";
> import { Platform, TextInput, KeyboardAvoidingView, ScrollView } from "react-native";
> import { SafeAreaView } from "react-native-safe-area-context";
> 
> const Component = () => {
>   return (
>     <SafeAreaView style={{ flex: 1 }} edges={["right", "bottom", "left"]}>
>       <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}>
>         <ScrollView>
>           <TextInput multiline scrollEnabled={false} />
>         </ScrollView>
>       </KeyboardAvoidingView>
>     </SafeAreaView>
>   );
> };
> ```

This one works for me too.

**Comment by yayobyte** [comment]
> This worked for me
> 
> ```js
> import React from "react";
> import { Platform, TextInput, KeyboardAvoidingView, ScrollView } from "react-native";
> import { SafeAreaView } from "react-native-safe-area-context";
> 
> const Component = () => {
>   return (
>     <SafeAreaView style={{ flex: 1 }} edges={["right", "bottom", "left"]}>
>       <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}>
>         <ScrollView>
>           <TextInput multiline scrollEnabled={false} />
>         </ScrollView>
>       </KeyboardAvoidingView>
>     </SafeAreaView>
>   );
> };
> ```

> This worked for me
> 
> ```js
> import React from "react";
> import { Platform, TextInput, KeyboardAvoidingView, ScrollView } from "react-native";
> import { SafeAreaView } from "react-native-safe-area-context";
> 
> const Component = () => {
>   return (
>     <SafeAreaView style={{ flex: 1 }} edges={["right", "bottom", "left"]}>
>       <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"}>
>         <ScrollView>
>           <TextInput multiline scrollEnabled={false} />
>         </ScrollView>
>       </KeyboardAvoidingView>
>     </SafeAreaView>
>   );
> };
> ```

This worked for me as well guys

**Comment by Kasik-D** [comment]
Hi guys, after 2 days suffers I found a solution
But you will need to connect library [react-native-keyboard-aware-scroll-view ](https://github.com/APSL/react-native-keyboard-aware-scroll-view)

If you use Expo, go to app.json and write `"softwareKeyboardLayoutMode": "pan"` in android
If you use CLI you need find similar solution

Let's start

Main component => **ChatComponent**

`import { Box } from 'native-base';
import React from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import { SafeAreaView } from 'react-native-safe-area-context';

import { useChat } from '../../hooks';
import { chatThemeType } from '../../types/chat';
import { pageEmpty } from '../../types/pager-view';
import { RequestHandler } from '../request-handler/request-handler';
import { ChatBottomInput } from './chat-bottom-input/chat-bottom-input';
import { ChatList } from './chat-list/chat-list';

type Props = {
  theme: chatThemeType;
  EmptypageData: pageEmpty;
};

export const ChatComponent = ({ theme, EmptypageData }: Props) => {
  const { chatLoading } = useChat();

  const scrollRef = React.useRef<KeyboardAwareScrollView>(null);

  return (
    <SafeAreaView edges={['bottom']} style={styles.safeAreaViewStyle}>
      <KeyboardAvoidingView
        style={styles.keyboardAvoidingViewStyle}
        behavior={Platform.OS === 'ios' ? undefined : 'height'}
      >
        <RequestHandler loading={chatLoading}>
          <KeyboardAwareScrollView
            ref={scrollRef}
            contentContainerStyle={styles.keyBoadStyle}
            scrollEnabled={false}
            nestedScrollEnabled={true}
          >
            <Box flexGrow={1}>
              <ChatList theme={theme} EmptypageData={EmptypageData} />

              <ChatBottomInput theme={theme} scrollRef={scrollRef} />
            </Box>
          </KeyboardAwareScrollView>
        </RequestHandler>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  keyBoadStyle: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  keyboardAvoidingViewStyle: {
    flex: 1,
  },
  safeAreaViewStyle: {
    backgroundColor: '#D5EDD8',
    flex: 1,
  },
});
```
--------------------------------------

**Comment by coprocoder** [comment]
Seriously, in 5 years they have not come up with anything other than "scrollEnabled={false}" ??
Even if you block the scroll, then when you wrap the line, it goes down under the keyboard.
Why does the field grow up on android, but on ios it moves down under the keyboard?
How many versions of RN have already been released over these 5 years, but this bug has not been fixed.

**Comment by endruuu** [comment]
> > Referring to my snippet posted above, there's no height on the TextInput, and KeyboardAvoidingView's behavior is set to padding.
> > Its style needs `flex:1` to allow the ScrollView to take up the entire height.
> > Try the code with and without multiline set. It fails with multiline set, but the same code works for single line TextInputs.
> 
> ^ This from @peacechen worked for me perfectly. I have `scrollEnabled={true}` & `multiline={true}`
> 
> _**Code:**_
> 
> ```
> <KeyboardAvoidingView
>   behavior="padding"
>   style={{flex: 1, flexDirection: "column"}}
> >
>   <View style={{flex: 1}}>
>     <TextInput
>         multiline={true}
>         scrollEnabled={true}
>         style={{flex:1}}
>         // Other relevant props
>       />
>   </View>
> <KeyboardAvoidingView />
> ```

Thanks!! It also works for me.

**Comment by Abdullah2500** [comment]
When you give prop scrollEnabled={false} in textInput, it will solve your issue but the problem comes in lenthy texts. It won't allow scrolling inside textInput. So the best approach would be to create a ref as const refScroll = useRef(false) and then pass that ref to textinput scrollEnabled prop. 
<TextInput scrollEnabled={refScroll.current}. And then onFocus={() => refScroll.current = true}  
Its a workaround but works fine with me...

**Comment by josaric** [comment]
Try this:

````

constructor(props) {
    super(props);
    this.state = {
        scrollEnabled: true
    }
}


onFocus() {
    let self = this;
    // disable scroll until the library does its own magic
    this.setState({
        scrollEnabled: false
    });
    // enable scroll again after 1 sec
    setTimeout(function() {
        self.setState({
            scrollEnabled: true
        })
    }, 1000)
}

onBlur() {
        // enable scroll on blur
        this.setState({
            scrollEnabled: true
        })
    }


<TextInput 
scrollEnabled={this.state.scrollEnabled}
onFocus={()=> this.onFocus()}
onBlur={()=> this.onBlur()}
multiline=true
 />

````

**Comment by mathbalduino** [comment]
Still happening...

**Comment by zonblade** [comment]
still happening on ios device, but with workaround above its ok now.

**Comment by mmkhmk** [comment]
Any updates? I'm facing the same issue.

**Comment by kipperlhp** [comment]
It's 2023 now

**Comment by xDreamLand** [comment]
Still happening

**Comment by vcapretz** [comment]
> When you give prop scrollEnabled={false} in textInput, it will solve your issue but the problem comes in lenthy texts. It won't allow scrolling inside textInput.

I solved this by setting only a `minHeight` to my input, so it doesn't scroll, but it grows if the user keeps typing 😋 
worked good enough for my use case 

(still frustrating that this is an issue from 2017 and we are still here tho)

**Comment by Saad-Bashar** [comment]
> 

I have done the same. My text input grows as well. But I noticed that after a certain amount, it behaves the same. The text inside the input gets cut off.

**Comment by Saad-Bashar** [comment]
> > When you give prop scrollEnabled={false} in textInput, it will solve your issue but the problem comes in lenthy texts. It won't allow scrolling inside textInput.
> 
> I solved this by setting only a `minHeight` to my input, so it doesn't scroll, but it grows if the user keeps typing 😋 worked good enough for my use case
> 
> (still frustrating that this is an issue from 2017 and we are still here tho)

Do you have scroll enabled set to false or true? I have the same, I also have minHeight, scrollEnabled={false}, however after writing the text for a certain amount the text gets cut off even the input can not grow anymore.

**Comment by karimelsaidy** [comment]
5 years and now direct solution yet?!

**Comment by demoox** [comment]
Damn it's 2023 and the only "solution" is `scrollEnabled={false}` ? stop a bit...

**Comment by mathbalduino** [comment]
I think FB has bigger concerns right now lol

**Comment by alainib** [comment]
2023 and not a proper way to avoid keyboard over input from reactnative ....

**Comment by jbagaresgaray** [comment]
Bump

**Comment by honcon** [comment]
Hi folks,

After a lot of search I've a workaround for my case, The thing I wanted was not have a scrollable TextInput but a non-scrollable infinite height as size of text as gives and this view contained to a ScrollView working properly with a KeyboardAvoidingView,

Voila:

```javascript
import React, { useState } from 'react';
import { SafeAreaView, ScrollView, TextInput, View, KeyboardAvoidingView, Keyboard, TouchableWithoutFeedback } from 'react-native';

import { Header } from 'react-native/Libraries/NewAppScreen';

export default function App(): JSX.Element {
  const [text, setText] = useState(`
  One
  Two
  Three
  Four
  Five`);

  const [textInputHeight, setTextInputHeight] = useState(40);

  const handleTextChange = (newText: any) => {
    setText(newText);
  };

  return (
    <SafeAreaView style={{ flex: 1 }}>
      <KeyboardAvoidingView behavior='padding' style={{ flex: 1 }}>
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>

          <ScrollView
            style={{
              backgroundColor: '#00ffff32',
              borderWidth: 1,
              borderColor: '#0000ff',
            }}
          >
            <Header />
            <View style={{}}>
              <TextInput
                style={{
                  borderWidth: 1,
                  height: Math.max(40, text.split('\n').length * 20),
                }}
                onChangeText={handleTextChange}
                value={text}

                onContentSizeChange={event => {
                  const { height } = event.nativeEvent.contentSize;
                  setTextInputHeight(Math.max(40, height));

                }}
                multiline={true}
                scrollEnabled={false}
              />
            </View>
          </ScrollView>
        </TouchableWithoutFeedback>
      </KeyboardAvoidingView>

    </SafeAreaView>
  );
}
```

I wrapped this functionality in a CustomInputView component of course

**Comment by istvan-panczel** [comment]
Hi,

I'm new to React-Native and ran into the same problem.
I came up with a dirty hack for myself, probably can help out someone else in the future:

```jsx
const [isScrollEnabledForTextArea, setIsScrollEnabledForTextArea] = useState<boolean>(false);

<TextArea
  keyboardType={'default'}
  isInvalid={invalid}
  value={value}
  onChangeText={onChange}
  onBlur={() => {
    setIsScrollEnabledForTextArea(false);
  }}
  autoCompleteType={'off'}
  autoCapitalize={'none'}
  autoCorrect={false}
  scrollEnabled={isScrollEnabledForTextArea}
  onFocus={() => {
    // dirty hack, the KeyboardAvoidingView cant handle an input if it has multiline text
    setTimeout(() => setIsScrollEnabledForTextArea(true), TWO_SEC_IN_MS);
  }}
></TextArea>
```

I'm using NativeBase with ```<Controller />``` and ```<TextArea />``` but the problem is the very same. This solved it for me.

**Comment by Q118** [comment]
So setting `scrollEnabled` to false made the KeyboardAvoidingView logic work for me.. yay.
BUT... now... my `clearButtonMode` prop doesn't work! Ack! Anyone else got to this point?
Thank you community for your help.

**Comment by Q118** [comment]
For anyone still looking for a solution to this. I created an NPM package, [expo-clear-input](https://www.npmjs.com/package/expo-clear-input) that is a solution to the above by working on any platform (web, ios, android) and in both single and multiline `<TextInput>`s. 

**A little `x` button for all**

**Comment by Jonathan0wh** [comment]
It is 2024 now... Still no direct fix?

**Comment by joshenx** [comment]
fix?

**Comment by TaewookKwak** [comment]
<img width="743" alt="스크린샷 2024-01-25 오후 11 47 23" src="https://github.com/facebook/react-native/assets/93242268/d3e0759b-740a-4dd3-9c48-fb8d1b539029">
<img width="736" alt="스크린샷 2024-01-25 오후 11 48 19" src="https://github.com/facebook/react-native/assets/93242268/08b82e3f-40ab-4c56-91b0-588cafab115f">
`
return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      enabled
      style={styles.avoid}
      keyboardVerticalOffset={0}>
      <View style={styles.inputContainer}>
        <TextInput
          style={styles.input}
          editable
          multiline
          textAlignVertical="top"
          onChangeText={newText => setText(newText)}
          value={text}
          maxLength={maxLength}
          autoFocus={true}
        />
        <View style={styles.counterContainer}>
          <Text style={styles.counter}>{`${text.length}/${maxLength}`}</Text>
        </View>

        <DotButton style={{width: '100%'}}>
          <DotButton.ButtonText>Send</DotButton.ButtonText>
        </DotButton>
      </View>
    </KeyboardAvoidingView>
  );
`

`
 inputContainer: {
    maxHeight: 500,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 10,
    alignSelf: 'stretch',
  },
  counterContainer: {
    alignSelf: 'stretch',
  },
  counter: {
    textAlign: 'right',
    marginTop: 4,
  },
  avoid: {
    flex: 1,
  },
`

for those who have a similar structure as me

**Comment by fabOnReact** [comment]
I believe it is an issue with [RCTScrollViewComponentView.mm](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm) and/or RCTUITextView.

The behaviour is not automatic on iOS, some libs provide it like [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager). 

I tested the workaround from [comment-1148477911](https://github.com/facebook/react-native/issues/16826#issuecomment-1148477911).

My understanding is that the native iOS implementation of ScrollView will keep the current scroll position automatically, for example:

1) ScrollView displays item 1-10
2) ScrollView height is resized from 700 to 300
3) After resizing, the ScrollView will scroll down so that item 10 is still visible at the bottom. The scroll position does not change

step 3) does not work on iOS when using multiline TextInput (UITextView), while it works when using single line TextInput (UITextField). Probably, the fact that UITextView can scroll, breaks this functionality.

Maybe the iOS implementation of UITextView/ScrollView keeps the position constant based on the contentOffset, but as we have 2 scrollviews (ScrollView scrolls and UITextView scrolls), the implementation manages the content offset of the TextInput multiline, instead of the parent scrollview.

KeyboardAvoidingView just wraps a view with `style={{padding: bottom}}` and decreases the height of the native ScrollView by the height of the keyboard

https://github.com/facebook/react-native/blob/12155c464c116b0786e8a6f3115a99804cf9b91d/packages/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L232-L246

as you can see, there is no native impl of KeyboardAvoidingView, simply it changes the ScrollView height 

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<img width="1080" alt="Screenshot 2024-02-02 at 11 56 15 AM" src="https://github.com/facebook/react-native/assets/24992535/ec0c148e-1234-44b5-b8b4-603fca34caad"/>


</p>
</details>


after opening the keyboard, the scrollview height is decreased by the height of the keyboard, but the scrollview fails to scroll to the previous position

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>


<img width="1080" alt="Screenshot 2024-02-02 at 11 58 53 AM" src="https://github.com/facebook/react-native/assets/24992535/07446bdf-1cd8-41b3-bf05-112718d0c1fd" />


</p>
</details>

I also added to the below example, logic to scroll down the scrollview after opening the keyboard. 
- It works when scrolling up
- It does not work when scrolling down
It may be related to the ability of the scroll view to scroll down with a TextInput multiline.

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

```javascript
import * as React from 'react';
import {
  Keyboard,
  StyleSheet,
  KeyboardAvoidingView,
  ScrollView,
  View,
  Text,
  TextInput,
} from 'react-native';

const RNTesterApp = () => {
  const [text, setText] = React.useState(
    'a line 1 \n a line 2 \n a line 3 \n a line 4 \n a line 5 \n a line 6 \n a line 7 \n',
  );
  let scrollViewRef = React.useRef(null);
  const [isScrollEnabled, setIsScrollEnabled] = React.useState(true);

  const onKeyboardWillShow = () => {
    console.log('onKeyboardWillShow');
    setIsScrollEnabled(false);
    if (scrollViewRef) {
      console.log('scrollToEnd');
      scrollViewRef.scrollTo({x: 0, y: 300});
    }
  };

  function onKeyboardDidShow() {
    console.log('onKeyboardDidShow');
    setIsScrollEnabled(true);
  }

  React.useEffect(() => {
    const subKWS = Keyboard.addListener('keyboardWillShow', onKeyboardWillShow);
    const subKDS = Keyboard.addListener('keyboardDidShow', onKeyboardDidShow);

    return () => {
      subKWS.remove();
      subKDS.remove();
    };
  }, []);

  return (
    <KeyboardAvoidingView style={{flex: 1, marginTop: 100}} behavior="padding">
      <ScrollView
        ref={ref => (scrollViewRef = ref)}
        keyboardShouldPersistTaps={'handled'}
        maintainVisibleContentPosition={{minIndexForVisible: 1}}>
        <View style={{padding: 12}}>
          <Text style={styles.text}>MESSAGE 1</Text>
          <Text style={styles.text}>MESSAGE 2</Text>
          <Text style={styles.text}>MESSAGE 3</Text>
          <Text style={styles.text}>MESSAGE 4</Text>
          <Text style={styles.text}>MESSAGE 5</Text>
          <Text style={styles.text}>MESSAGE 6</Text>
          <Text style={styles.text}>MESSAGE 7</Text>
          <Text style={styles.text}>MESSAGE 8</Text>
          <Text style={styles.text}>MESSAGE 9</Text>
          <Text style={styles.text}>MESSAGE 10</Text>
          <Text style={styles.text}>MESSAGE 11</Text>
        </View>
        <TextInput
          multiline={true}
          placeholder={'Type something here...'}
          onChangeText={setText}
          value={text}
          scrollEnabled={true}
          style={styles.input}
        />
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

export default RNTesterApp;

const styles = StyleSheet.create({
  text: {
    fontSize: 20,
    padding: 40,
  },
  input: {
    height: 50,
  },
});

```

</p>
</details>

I may consider working on this issue and publishing a fix if **requested** by the community. 
I believe it requires an extensive implementation in UITextView and RCTScrollViewComponentView to control their content offset.

https://github.com/hackiftekhar/IQKeyboardManager/blob/aa656e1f0d95f0154622f453599318602848be3b/IQKeyboardManager/IQKeyboardManager.m#L838-L853

https://stackoverflow.com/a/20052756/7295772

https://stackoverflow.com/a/69811662/7295772

Similar issues, but on Android are https://github.com/facebook/react-native/issues/25239 and https://github.com/facebook/react-native/issues/30373#issuecomment-1524520237

**Comment by vanenshi** [comment]
@fabOnReact Thanks for the great details on the problem, Fabrizio
this is a 7-year-old problem, if you manage to fix it, all of us can remove the nasty workaround in our code and start using the pure component.

**Comment by fabOnReact** [comment]
Thanks, but I decided to not contribute anymore to facebook/react-native.

**Comment by Paraschoudhary176** [comment]
`<KeyboardAvoidingView
   style={{ flex: 1 }}
   behavior="padding"
>
  <ScrollView ref={component => { this.myScrollView = component; }}>
    <TextInput 
       multiline
       onFocus={() => this.myScrollView.scrollTo({ x: 0, y: 750, animated: true })} // <- your coordinates here
    />
  </ScrollView>
</KeyboardAvoidingView>`

**_This is how this will work. You can also try keyboard aware scroll view , or in android manifiest.xml can change the adjust keyboard. or if nothing works then we have antother alternative a prop called tabBarHideOnKeyboard: true._**

**Comment by pein892** [comment]
@Paraschoudhary176 Thanks for your thoughts, and here is my solution：
```javascript
const App = () => {
  const scrollViewRef = useRef(null)
  const textInputRef = useRef(null)

  const onFocus = () => {
    if (Platform.OS === 'ios' && isMultiline) {
      if (scrollViewRef.current && textInputRef.current) {
        textInputRef.current.measureLayout(
          scrollViewRef.current,
          (x, y, width, height) => {
            setTimeout(() => {
              scrollViewRef.current.scrollTo({y: y, animated: true});
            }, 500);  // 500ms just work fine.
          },
          () => {},
        );
      }
    }
  }

  return (
    <KeyboardAvoidingView>
      <ScrollView ref={scrollViewRef}>
        <TextInput 
          ref={textInputRef} 
          multiline={true} 
          numberOfLines={3} 
          onFocus={onFocus} />
      </ScrollView>
    </KeyboardAvoidingView>
  )
}
```

**Comment by kirillzyusko** [comment]
hello, maintainer and creator of `react-native-keyboard-controller` is here 👋 

I think [KeyboardAwareScrollView](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/components/keyboard-aware-scroll-view) from `react-native-keyboard-controller` should solve this problem - it automatically detects a moment when focused `TextInput` is growing and automatically scrolling to the necessary coordinates.

Theoretically similar behavior can be backported to `KeyboardAvoidingView` component from RNKC because this functionality is powered by another hook (layout changes detection) - but I hardly can imagine a layout where `KeyboardAvoidingView`+`multiline` is more preferable option over `KeyboardAwareScrollView`+`multiline`.

Anyway, if you have such examples and if you think, that something is not working or should work in a different way - feel free to open issues in [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller) repository 👀

**Comment by Energieman** [comment]
in 2024, Here is mu working fix, scrollEnabled={false} did most o the magic. I honestly hope it helps someone here. 

<KeyboardAwareScrollView 
                enableAutomaticScroll={true}
                innerRef = {(ref) => setScrollViewRef(ref)}
                style={{backgroundColor: 'green'}}>
                <TextInput 
                    scrollEnabled={false} //2
                    ref={editFieldRef}
                    editable={noteEditable}
                    placeholder="Enter note..."
                    placeholdercolor={BaseColor.blackColor}
                    onChangeText={text => {setNoteText(text);}} //avoidGoingBack();
                    value={noteText}
                    defaultValue={noteText}
                    multiline = {true}
                    numberOfLines = {10}
                    autoFocus={true}
                    forcedStyle={{fontSize: 20}} //custom TextInput component prop
                    style={{ 
                        minHeight: '100%', //for ios because number of lines dosent work with it
                        color: BaseColor.unchangeableClack, backgroundColor: colorPaleteToUse, 
                    }}
                />
            </KeyboardAwareScrollView>

**Comment by alainib** [comment]
> in 2024, Here is mu working fix, scrollEnabled={false} did most o the magic. I honestly hope it helps someone here.
> 
> <KeyboardAwareScrollView enableAutomaticScroll={true} innerRef = {(ref) => setScrollViewRef(ref)} style={{backgroundColor: 'green'}}> <TextInput scrollEnabled={false} //2 ref={editFieldRef} editable={noteEditable} placeholder="Enter note..." placeholdercolor={BaseColor.blackColor} onChangeText={text => {setNoteText(text);}} //avoidGoingBack(); value={noteText} defaultValue={noteText} multiline = {true} numberOfLines = {10} autoFocus={true} forcedStyle={{fontSize: 20}} //custom TextInput component prop style={{ minHeight: '100%', //for ios because number of lines dosent work with it color: BaseColor.unchangeableClack, backgroundColor: colorPaleteToUse, }} />

disabling scroll on a scrollview .... not a fix at all

**Comment by shuo-hiwintech** [comment]
+1

**Comment by chrisdev3001** [comment]
I dont wanna depends on another library for this bug, here is my solution:

Custom hook:
```typescript
import { useRef } from 'react'
import { doSomethingAtSecondX } from '@core/utils'

interface MoveScrollTo {
  x: number
  y: number
}

export const useMoveScroll = () => {
  const scrollRef = useRef() as any

  const moveScrollTo = ({ x, y }: MoveScrollTo) =>
    scrollRef.current.scrollTo({ x, y, animated: true })

  const moveScrollToDown = (pxToDown: number) => {
    if (scrollRef.current) {
      doSomethingAtSecondX({
        callback: () => moveScrollTo({ x: 0, y: pxToDown }),
        seconds: 0.35
      })
    }
  }

  return {
    scrollRef,
    moveScrollToDown
  }
}

``` 

Component:
```typescript
const { scrollRef, moveScrollToDown } = useMoveScroll()

return (
<ScrollView
      ref={scrollRef}
      showsVerticalScrollIndicator={false}
      ....
  />

    <Input
      multiline
      numberOfLines={5}
      placeholder='write comments here...'
      onFocus={() => moveScrollToDown(450)}
      onChangeText={setComments}
    />

</ScrollView>

)

``` 
Hope this help 🐰

**Comment by aman-technyx** [comment]
@chrisdev3001 can you tell me where i can get this "doSomethingAtSecondX" 
import { doSomethingAtSecondX } from '@core/utils'

**Comment by HemalSPatel** [comment]
+1

**Comment by chrisdev3001** [comment]
> @chrisdev3001 can you tell me where i can get this "doSomethingAtSecondX" import { doSomethingAtSecondX } from '@core/utils'

I have updated the code... it was just a little helper function 👀

**Comment by ftaibi** [comment]
why is so hard to work with keyboards in rn???? :(((((

**Comment by aman-technyx** [comment]
@ftaibi this code works for me !

`import React from 'react';
import {
    Platform,
    Keyboard,
    TouchableWithoutFeedback,
    ViewStyle,
} from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';

interface Props {
    children: React.ReactNode;
    style?: ViewStyle;
}

const KeyboardAvoidingComponent: React.FC<Props> = ({ children, style }) => {
    return (
        <KeyboardAwareScrollView
            showsVerticalScrollIndicator={false}
            style={style}
            extraHeight={Platform.OS === 'ios' ? 150 : 0} // adjust height for iOS
            enableOnAndroid={true}>
            <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
                {children}
            </TouchableWithoutFeedback>
        </KeyboardAwareScrollView>
    );
};

export default KeyboardAvoidingComponent;
`

use as 

<KeyboardAvoidingComponent style={{flex: 1}}>
<View/>.          // no need to use scrollview here.
</KeyboardAvoidingComponent>

**Comment by kjossendal** [comment]
Still broken for me on iOS. If you are using a scrollview and have reanimated, this works great.

```
import React, { forwardRef } from "react";
import { Dimensions, ScrollView, TextInput } from "react-native";
import Animated, {
  KeyboardState,
  runOnJS,
  useAnimatedKeyboard,
  useAnimatedProps,
  useAnimatedReaction,
  useAnimatedRef,
  useAnimatedScrollHandler,
  useSharedValue,
} from "react-native-reanimated";

interface KeyboardAwareScrollViewProps {
  offset?: number;
}

export function withReanimatedKeyboardAwareScrollView<T extends typeof ScrollView>(Component: T) {
  const AnimatedScrollView = Animated.createAnimatedComponent(Component);
  return forwardRef<
    Animated.ScrollView,
    React.ComponentProps<typeof ScrollView> & KeyboardAwareScrollViewProps
  >(function KeyboardAwareReanimatedScrollView(props, ref) {
    const { offset = 0 } = props;
    const scrollY = useSharedValue(0);
    const keyboard = useAnimatedKeyboard();
    const scrollViewRef = useAnimatedRef<ScrollView>();

    const setRefs = (node: Animated.ScrollView) => {
      // Refs are either objects with a 'current' property or functions
      if (typeof ref === "function") {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
      scrollViewRef.current = node;
    };

    const performScroll = () => {
      TextInput.State.currentlyFocusedInput()?.measure(
        (x, y, width, textInputHeight, pageX, textInputPageY) => {
          const textinputBottomY = textInputPageY + textInputHeight;
          const keyboardTopY = Dimensions.get("screen").height - keyboard.height.value;
          // check whether the text input is covered by the keyboard
          if (textinputBottomY < keyboardTopY) {
            return;
          }

          scrollViewRef?.current?.scrollTo({
            y: scrollY.value + textinputBottomY - keyboardTopY + offset,
          });
        },
      );
    };

    useAnimatedReaction(
      () => {
        return keyboard.state.value;
      },
      (keyboardState) => {
        if (keyboardState === KeyboardState.OPEN) {
          runOnJS(performScroll)();
        }
      },
    );

    const containerPaddingStyle = useAnimatedProps(() => {
      return {
        paddingBottom: keyboard.height.value,
      };
    });

    const handler = useAnimatedScrollHandler(
      {
        onScroll: (e) => {
          scrollY.value = e.contentOffset.y;
        },
      },
      [],
    );

    return (
      <>
        <AnimatedScrollView {...props} ref={setRefs} scrollEventThrottle={16} onScroll={handler}>
          {props.children}
          <Animated.View style={containerPaddingStyle} />
        </AnimatedScrollView>
      </>
    );
  });
}

// Usage
export const KeyboardAwareScrollView = withReanimatedKeyboardAwareScrollView(ScrollView);
```

**Comment by mmaass** [comment]
> > in 2024, Here is mu working fix, scrollEnabled={false} did most o the magic. I honestly hope it helps someone here.
> > <KeyboardAwareScrollView enableAutomaticScroll={true} innerRef = {(ref) => setScrollViewRef(ref)} style={{backgroundColor: 'green'}}> <TextInput scrollEnabled={false} //2 ref={editFieldRef} editable={noteEditable} placeholder="Enter note..." placeholdercolor={BaseColor.blackColor} onChangeText={text => {setNoteText(text);}} //avoidGoingBack(); value={noteText} defaultValue={noteText} multiline = {true} numberOfLines = {10} autoFocus={true} forcedStyle={{fontSize: 20}} //custom TextInput component prop style={{ minHeight: '100%', //for ios because number of lines dosent work with it color: BaseColor.unchangeableClack, backgroundColor: colorPaleteToUse, }} />
> 
> disabling scroll on a scrollview .... not a fix at all , if you have like 10 inpunt inside to show ? (

Look again, scrolling is disabled for the **TextInput**

**Comment by just-myself** [comment]
Waiting for the hero to return

**Comment by pradumyamindcrew** [comment]
<ScrollView style={{ paddingHorizontal: 16 }} automaticallyAdjustKeyboardInsets={true}>

Final Solution

**Comment by graceazilin** [comment]
> <ScrollView style={{ paddingHorizontal: 16 }} automaticallyAdjustKeyboardInsets={true}>
> 
> Final Solution

@pradumyamindcrew Been testing your solution and it works like a charm! Created an expo snack:
https://snack.expo.dev/@graceazilin/blissful-green-candies

basically it's `scrollEnabled={false} ` in TextInput and `automaticallyAdjustKeyboardInsets={true}` in ScrollView

`export default function App() {
  return (
<KeyboardAvoidingView style={styles.container}>
  <ScrollView
    automaticallyAdjustKeyboardInsets={true}
    style={styles.scrollView}>
    <TextInput
      style={styles.textInput}
      placeholder="Enter extremely long text"
      placeholderTextColor="grey"
      multiline
      scrollEnabled={false}></TextInput>
  </ScrollView>
</KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: { flex: 1, paddingTop: 200, alignItems: 'center' },
  textInput: {
    width: 250,
    height:'auto',
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 3,
    padding: 12,
  },
});
`

**Comment by wneel** [comment]
Any update planned on this ?

**Comment by Rvalle23** [comment]
The solution proposed by  @pradumyamindcrew work but of course, you need to disable the scroll inside of the multiline box, is there any other troubleshoot to enable the scroll inside. Please, we need a solution for this.

**Comment by pachun** [comment]
So I spent a few hours on this today before I came across this issue. [Here's something I got working](https://github.com/pachun/blog/blob/main/posts/2025-05-30-creating-a-scrollable-keyboard-avoiding-multiline-text-field-in-react-native.md).

Hope that does something for someone else!

**Comment by SSylvain1989** [comment]
> <ScrollView style={{ paddingHorizontal: 16 }} automaticallyAdjustKeyboardInsets={true}>
> 
> Final Solution

This works fine for me thanks

```jsx
    <KeyboardAvoidingView style={styles.scrollView}>
      <ScrollView automaticallyAdjustKeyboardInsets={true}>
// your code 
// your multiline 
          <Box>
            <ControlledInput
              control={control}
              name="message"
              label={`${t('native:contact.request.message.label')} *`}
              ruleName="required"
              multiline
              numberOfLines={5}
              minHeight={150}
              scrollEnabled={false} 👈
            />
          </Box>
      </ScrollView>
    </KeyboardAvoidingView>

````

**Comment by a-eid** [comment]
stop using `KeyboardAvoidingView` from `react-native`, and consider using `react-native-keyboard-controller`.

**Comment by boblitex** [comment]
> stop using `KeyboardAvoidingView` from `react-native`, and consider using `react-native-keyboard-controller`.

highly recommend this, should solve all of your keyboard problems, multiline or nah

**Comment by maik-emanoel** [comment]
> <ScrollView style={{ paddingHorizontal: 16 }} automaticallyAdjustKeyboardInsets={true}>
> 
> Final Solution

The only solution that really fixed my problem and dont broke scroll inside the TextInput. Thanks, man.

**Comment by TrungRN** [comment]
If TextInput is inside ScrollView, add:
scrollEnabled={false} to TextInput to fix the issue
```
<TextInput
    scrollEnabled={false}
/>
```

**Comment by pachun** [comment]
https://github.com/software-mansion/react-native-enriched has worked great for me. Maybe it'll work well for others arriving here.

**Comment by wneel** [comment]
still relevant

**Comment by Vignesh1318** [comment]
any update on this issue still issue there ?

**Comment by wahyutrading** [comment]
Try to use keyboardAvoidingView or KeyboardAwareScrollView from react-native-keyboard-controller instead. I also had this issue before.
