### ISSUE TITLE
Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativeBridgeEventPlugin`

### ISSUE THREAD

**Issue by milad1367** [facebook/react-native#16840]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes
### Steps to Reproduce

I started my project 2 months ago. my project worked correctly until I forced relaunch project(removed project files and git clone project from GitHub and npm install after npm start).
1.npm install or yarn install (Tested with both)
2.npm start or yarn start

### Expected Behavior

I expected start project correctly.
### Actual Behavior

![1](https://user-images.githubusercontent.com/15375991/32837633-1febb4ec-c9c3-11e7-9697-9d2a23f6b89e.png)
![2](https://user-images.githubusercontent.com/15375991/32837638-23309316-c9c3-11e7-8951-fcbe028984bf.png)
![3](https://user-images.githubusercontent.com/15375991/32837648-26dee634-c9c3-11e7-81be-8be3f259afb9.png)

also after run npm ls :
![4](https://user-images.githubusercontent.com/15375991/32837721-66cab2a0-c9c3-11e7-8351-b452f4a7be52.png)

package.json
```
{
  "name": "sirin",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~20.0.0",
    "react-native-scripts": "1.2.1",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "links": "react-native link",
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "rnpm": {
    "assets": [
      "src/assets/fonts"
    ]
  },
  "dependencies": {
    "art": "^0.10.1",
    "d3": "^4.10.2",
    "d3-array": "^1.2.1",
    "d3-path": "^1.0.5",
    "d3-shape": "^1.2.0",
    "expo": "^20.1.3",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.0",
    "react-native-chart": "^1.0.8-beta",
    "react-native-charts-wrapper": "^0.2.10",
    "react-native-circular-progress": "^0.0.8",
    "react-native-customisable-switch": "^0.1.0",
    "react-native-datepicker": "^1.6.0",
    "react-native-device-info": "^0.11.0",
    "react-native-drawer": "^2.5.0",
    "react-native-elements": "^0.16.0",
    "react-native-filesystem": "^0.1.0",
    "react-native-gesture-handler": "^1.0.0-alpha.31",
    "react-native-installed-apps": "0.0.6",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-material-switch": "^0.0.4",
    "react-native-modal": "^3.1.0",
    "react-native-pathjs-charts": "0.0.31",
    "react-native-progress": "^3.4.0",
    "react-native-progress-circle": "^2.0.0",
    "react-native-responsive-image": "^2.1.0",
    "react-native-shadow": "^1.2.1",
    "react-native-side-menu": "^1.0.2",
    "react-native-simple-toast": "^0.0.7",
    "react-native-snap-carousel": "^3.2.2",
    "react-native-svg": "^5.4.1",
    "react-native-svg-image": "^2.0.0",
    "react-native-svg-uri": "^1.2.1",
    "react-native-switch": "^1.1.0",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "redux-thunk": "^2.2.0"
  }
}
```

### Reproducible Demo

I cannot be launched project so I cannot show a demo.
I think is the problems of GestureHandler.js but I cannot solve it.
I tested project with new versions (react,react-native, expo) problems solved.but I cannot update those versions because the UI components will be broken.

**Comment by bakhtiararifin** [comment]
i have similar problem on expo sdkVersion 20.0.0

**Comment by Listor** [comment]
same here

    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.0",
     sdk 20.0.0

**Comment by luklapp** [comment]
It seems to work after downgrading `react-native-gesture-handler`. I used the latest version of `expo/react-native-gesture-handler`.

In package.json:
```"dependencies": {
"react-native-gesture-handler": "git://github.com/expo/react-native-gesture-handler#db4222870a6664dd7f7215bd6c9639a6a7dd7da9",
}```

**Comment by milad1367** [comment]
i added this but not worked.

**Comment by luklapp** [comment]
@milad1367 Try to install all dependencies again and clear the cache:

```
rm -rf ./node_modules
rm -rf $TMPDIR/react-*
npm install
npm start -- --reset-cache // (or click "Restart" if you use Expo XDE)
```

**Comment by bakhtiararifin** [comment]
@luklapp i have tried it, and got another error
![screen shot 2017-11-17 at 11 38 33](https://user-images.githubusercontent.com/16460231/32929662-2f4de430-cb8c-11e7-9438-8a75d55b9255.png)

**Comment by Listor** [comment]
did all the above but it is still not working. since the dependencie is in the expo dep itself removing node_modules will remove the change to the package.json won't it ?

so how is this supposed to work or what am i missing ?

**Comment by luklapp** [comment]
Maybe try to update to Expo v22.0.0 or latest (v23.0.0), looks like the dependency is fixed there!

**Comment by Listor** [comment]
switching to expo 22 works since there is no sdk for version 23 yet. thx luklapp

**Comment by luklapp** [comment]
@Listor: Expo 23 was just released today! :)

https://blog.expo.io/expo-sdk-v23-0-0-is-now-available-be0a8c655414

**Comment by Listor** [comment]
oh weird and nice at the same time :D cause it wouldn't let me work with sdk 23 got an error with it saying that the latest possible was 22. will give it a shot later but since it is working right now i don't want to change anything ;) maybe something overlapped and i was too quick

**Comment by milad1367** [comment]
@luklapp: I did, but not solved. Someone help me.customer waiting for me and I cannot update the project to SDK 23 . I'm crazy.

**Comment by milad1367** [comment]
oh-oh, I solved it.i added react-native-gesture-handler1.0.0-alpha.27.

**Comment by luklapp** [comment]
@Listor: You have to update the Expo Client on your phone, otherwise it won't work with 23.0.0 ;)

**Comment by milad1367** [comment]
i added react-native-gesture-handler1.0.0-alpha.23 and everything solved!

**Comment by simjoh** [comment]
I solved this as
npm uninstall react-native-gesture-handler
npm install -save react-native-gesture-handler@1.0.0-alpha.27

**Comment by sohaibjaved44** [comment]
It didn't work for me with npm install --save react-native-gesture-handler@1.0.0-alpha.27, I have tried 23 to 29 all but could not luck with my react-native starter kit. struggling to find out the compatible one.

**Comment by murrayrj** [comment]
![screen shot 2018-08-25 at 00 30 58](https://user-images.githubusercontent.com/12058038/44612240-92ba1300-a7fe-11e8-963a-aced9829642d.png)
I'm still getting this issue with the newer version of RN. This is a link to my package.json and repo for anyone to test and help: https://github.com/murrayrj/React-Native-CRNA-Expo-Starter/blob/master/package.json

**Comment by Samuelote** [comment]
I'm still getting this error after 3 days of scouring the web for answers. It is the same exact error as murrayrj above. Any new solutions here?

**Comment by milad1367** [comment]
you have to add react-native-gesture-handler1.0.0-alpha.23

**Comment by milad1367** [comment]
you have to add react-native-gesture-handler1.0.0-alpha.23

**Comment by SchulzWill** [comment]
Having problems with this too. 
![error](https://user-images.githubusercontent.com/8031507/48168837-de9e3380-e2e8-11e8-9a9b-d7ef70ef68b4.jpg)
