### ISSUE TITLE
[TextInput] Not clear what Warning Message for TextInput means.

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#1689]
After upgrading React Native to 0.6.0 I'm starting to get this warning.

`Warning: Don't set .props.style of the React component <TextInput />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props.`

I did everything as it describes above. but nothing works so far. Any idea why this warning start to show up. I would like to see some example if that possible,

**Comment by brentvatne** [comment]
Can you show us some code that produces this warning?

**Comment by alinz** [comment]
Well, I'm using my fork version of react-native which can be found [here](https://github.com/alinz/react-native/tree/ali2). 
I have only changes 2 things
 - added `es6.modules` to white list [here](https://github.com/alinz/react-native/blob/ali2/packager/transformer.js#L31)
 - [force](https://github.com/alinz/react-native/blob/ali2/package.json#L3) the version to be 0.5.0 to by pass some npm errors. 

now the regular `TextInput` component keeps sending me that warning. I'm not doing any fancy thing. It used to work but changes to latest code causes this warning.

**Comment by brentvatne** [comment]
We can't really support forks, but if you can reproduce this on a standard build of React Native then please do link to the repo and I'll be happy to take a look! Closing until then

**Comment by jawadrehman** [comment]
@brentvatne I use the version 0.6-rc and I can see the same warning message.

**Comment by admmasters** [comment]
This is occurring on the 0.6.0 release version. Can be reproduced by creating a brand new project and adding at least one TextInput field to the render method.

**Comment by admmasters** [comment]
This is related to line 422 of TextInput.js:
````
props.style = [styles.input, this.props.style]
````
You are mutating props within the render method - which obviously is not good practice.

**Comment by ide** [comment]
@admmasters do you want to submit a PR? Cloning the props should fix it ex:
```js
var props = {
   ...this.props,
  style: [styles.input, this.props.style],
};
```

**Comment by admmasters** [comment]
Sure - I was just looking at it now :)

**Comment by alinz** [comment]
:+1:

**Comment by chirag04** [comment]
saw this warning today.

**Comment by chirag04** [comment]
@ide  Is this merged in master? I just updated to 0.7.1 and i still see this warning

**Comment by ide** [comment]
It has not been merged.

**Comment by browniefed** [comment]
@brentvatne looks like the solution got merged 5 days ago.

**Comment by brentvatne** [comment]
@browniefed - indeed, this is in master now! Thanks for pointing it out :smile:
