### ISSUE TITLE
Border not animating with scale

### ISSUE THREAD

**Issue by wassgha** [facebook/react-native#17224]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.5.0
  Yarn: 1.1.0
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0

  Target Platform: Android (26+)

### Steps to Reproduce

After upgrading to react-native 0.51.0, a component that used to be animated (scales up and down based on scroll) and that has a border (with border-radius too) no longer animates. The component itself still scales (verified by adding a background) but the borders don't. Since there has been a lot of work on borders in 0.51.0 I am assuming this has to do with that.

Steps

1. Create a component using `Animated.View` that has styles including a border. In my case this is
```
    borderRadius: 88 / 2,
    width: 88,
    height: 88,
    borderWidth: 4,
    borderColor: 'rgba(0, 0, 0, 0.8)'
```
and add an animated variable as its `transform: [{scale: ...}]`.
2. Make sure you are using `react-native` 0.51.0
3. Every aspect of the component will scale as the animated value changes, except for borders

### Expected Behavior

Prior to upgrading to `0.51.0` the borders used to scale

### Actual Behavior

![ezgif com-video-to-gif 11](https://user-images.githubusercontent.com/591655/34030793-7034f4be-e13c-11e7-97db-845238af6285.gif)

### Reproducible Demo

[https://snack.expo.io/Sk6o8ZWMG](https://snack.expo.io/Sk6o8ZWMG)

(Works on Appetize but not on actual phone)

**Comment by wassgha** [comment]
Pinging @rsnara and @AaaChiuuu

**Comment by Druux** [comment]
same for me! any updates on this?

**Comment by zachgibson** [comment]
@wassgha I ran the snack and it was a different app example. Where is the snack for the GIF you posted?

**Comment by wassgha** [comment]
@zachgibson the snack is an isolated version of the bug that occurs inside the beta if our app (which you can see in the gif). I can invite you to the beta if you'd like but the effect is the same.

**Comment by arma7x** [comment]
Same for me. Temporary downgrade to rn 0.49 works perfectly

**Comment by uribro** [comment]
this was broken in 0.51.0 downgrade to 0.50.0 works.

**Comment by nadavoran** [comment]
Is this issue fixed on 0.52.0

**Comment by aahz** [comment]
Still broken for 0.53.0

Now using hack with `react-native-svg.Circle` to get around the problem, may be this will help someone

**Comment by hssrrw** [comment]
The bug is still reproduced in 0.53.0. Does anyone have an idea how this could be possibly fixed?

**Comment by hramos** [comment]
Reopening as this was introduced in 0.48 and is still present as of 0.54

**Comment by VinceBT** [comment]
Any progress on this issue ?

**Comment by rsnara** [comment]
Hey @wassgha!

I tried to reproduce this issue on v0.50.0, v0.51.0, and v0.55.0 of React Native, but wasn't able to. I didn't expect v0.50.0 to repro the problem, but v0.51.0 and v0.55.0 should repro. To attempt reproduction, I built React Native directly from the Github repository and plugged your code into RNTester. 

When the above failed, I used expo to run your snack on my S8, but still had no luck. 

I also created a new project using `create-react-native-app`, and changed the react-native version to 0.51 by making the following changes to `package.json`:
```JSON
  "dependencies": {
    "expo": "^24.0.0",
    "react": "16.3.1",
    "react-native": "~0.51.0"
  }
```

Changes made to app.json:

```JSON
{
  "expo": {
    "sdkVersion": "24.0.0"
  }
}
```

With a the brand new project running react native v0.51.0, I couldn't reproduce the problem. 

**Observed Behaviour**: What I see is a pulsating black circle surrounded with a red border, which I expect is the correct behaviour.

There's a high likelihood that I'm making a mistake somewhere, does this problem still reproduce for you?

**Comment by wassgha** [comment]
Seems to have been fixed (for me at least), @VinceBT maybe?

**Comment by VinceBT** [comment]
@wassgha Which version are you using ?

**Comment by rsnara** [comment]
@hramos, is this issue still a problem?

**Comment by nadavoran** [comment]
I didn't upgrade to 0.55 but I could still see the issue on 0.53. 
When I run my app on large Android phones (like the pixel) everything seems to be ok, but when I run it on a smaller device like Samsung s7 the issue reproduces

**Comment by Fsarmento** [comment]
I am still having this exact same issue on 0.56. it only happens when borderRadius is set to a value bigger than 0.

react: 16.4.1 => 16.4.1
react-native: 0.56.0 => 0.56.0

I made a simple example on expo snack [here](https://snack.expo.io/@fsarmento/bug---android-7---borderradius-not-scaling). Scan the QR code with an Android 7.0 phone to reproduce the bug.

**Comment by nicollecastrog** [comment]
@hmramos I'm having this same issue on `0.56`. It's worth noting that other issues around static elements *with* borders *using* `borderRadius` being blurred in Android were in fact fixed [here](https://github.com/facebook/react-native/commit/c5ca26a0e5c0660196300ee34d6007c63879611f), so the upgrade to RN 0.56 fixes that. My static round buttons, for example, look crisp now.

The issue that remains is when you try to *animate* an element that uses `borderRadius` (whether it's got borders or not). In my case I'm try to animate a circle with some background colour from small to large:

![blurry-expanding-circle](https://user-images.githubusercontent.com/5670279/45546794-49b21900-b816-11e8-9f74-11fc0650f9da.gif)

**Device info:**
Google Pixel, API 27, Android 8.1
