### ISSUE TITLE
Android: Border radius renders in a blurred / choppy way in 0.51.0

### ISSUE THREAD

**Issue by dannycochran** [facebook/react-native#17267]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.4
  Yarn:  Not Found
  npm:  3.10.10
  Watchman:  4.9.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.53.0 => 0.53.0

  Target Platform: Android (22)

### Steps to Reproduce

Create a simple view:

```javascript
export default class App extends Component {
  render() {
    return (
      <View style={styles.background}>
        <View style={styles.container}>
          <Text>Welcome to React Native!</Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  background: {
    backgroundColor: 'purple',
    flex: 1
  },
  container: {
    position: 'absolute',
    left: 100,
    top: 100,
    width: 200,
    height: 100,
    backgroundColor: 'orange',
    borderWidth: 2,
    borderColor: 'orange',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center'
  }
});
```

### Expected Behavior

I would expect that the border does not render in a strange and pixelated way. Previously in react-native 0.49.5, the exact same code would render like so:

<img width="615" alt="screen shot 2017-12-18 at 5 16 14 pm" src="https://user-images.githubusercontent.com/1217178/34135720-3be7184e-e417-11e7-9e2f-5b4c351bab9b.png">

### Actual Behavior

In react-native 0.53.0, that same code renders this blurry border:

<img width="707" alt="screen shot 2017-12-18 at 5 15 54 pm" src="https://user-images.githubusercontent.com/1217178/34135728-45aa6930-e417-11e7-98d2-3cd75ee404cb.png">

### Reproducible Demo

The code snippet above compiles and should be sufficient to reproduce this problem.

**Comment by dannycochran** [comment]
Pinging @rsnara who is listed on release notes for 0.51.0 for border work, and @AaaChiuuu who worked on "overflow: hidden" for 0.50.0.

**Comment by SirNeuman** [comment]
I've also noticed this. It's especially noticeable when you have the border color different from the background color of the button and surrounding view.

**Comment by dannycochran** [comment]
This appears to be one of a number of bugs related to borders in Android for 0.51.0:

https://github.com/facebook/react-native/issues/17286
https://github.com/facebook/react-native/issues/17251
https://github.com/facebook/react-native/issues/17224
https://github.com/facebook/react-native/issues/17144

**Comment by jkimbo** [comment]
@rsnara any update on this issue? It's currently blocking our upgrade to v0.51

**Comment by jkimbo** [comment]
Another bug related to this: https://github.com/facebook/react-native/issues/17311

**Comment by gtauniverse** [comment]
same problem

**Comment by dannycochran** [comment]
@rsnara are you able to take a look at this, or help us identify which commit might be responsible?

**Comment by yedidyak** [comment]
This is the android profile GPU rendering on a screen with a couple of circles with borderWidth of 1 in RN 0.51.0. The same screen renders flawlessly on lower versions of RN.

![screenshot_1515418843](https://user-images.githubusercontent.com/8819594/34673384-bedd6716-f48a-11e7-9524-919b8d70d294.png)

**Comment by yedidyak** [comment]
I made a PR that fixes the performance issue. The problem was that the new borders calculations didn't support a borderRadius larger than the maximum possible - 50% of the smallest side.

https://github.com/facebook/react-native/pull/17514

**Comment by atlanteh** [comment]
@yedidyak Is this the reason for all of the above bugs mentioned by @dannycochran ?
Will this PR also fix all of those as well?

**Comment by yedidyak** [comment]
It's possible, I didn't notice any specific issues as shown above, just serious performance issues. My PR is specific to borderRadius > 50% of the view size. I posted it here because it seems that several different border issues in 0.51.0 were merged into here.

**Comment by dannycochran** [comment]
Still in 0.52.0, 5aa1fb3 and ca7fe72 by @rsnara did not fix, not sure they were intended to?

**Comment by Luze26** [comment]
We can also see a line between each side of the border (appeared in 0.51 and still presents in 0.52).
![image](https://user-images.githubusercontent.com/2338637/35388745-47416010-01d5-11e8-9c44-5be20c7d9765.png)

**Comment by sandropoluan** [comment]
Same here . RN 0.52

**Comment by sandropoluan** [comment]
This issue still exist on RN 0.53

**Comment by jamesloper** [comment]
Here's a snack to help clarify the error

``` javascript
       import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.button}>
          <Text style={styles.buttonText}>Pushy Pushy</Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-around',
    backgroundColor: '#fff',
    padding: 10,
  },
  button: {
    borderRadius: 2,
    borderColor: 'red',
    borderWidth: 1,
    padding: 10,
  },
  buttonText: {
    fontSize: 16,
    textAlign: 'center',
  },
});
```

https://snack.expo.io/BytwPGarz

**Comment by atlanteh** [comment]
@hramos 
Guys, how can you release new versions of react-native with such a bug? This issue has been reported almost two months ago and should have been address almost instantly. It there anyone on this?

**Comment by jwesselink** [comment]
This bug prevents me from updating to newer react native versions (0.50.4 is the latest working version). This bug is still present in the latest 0.52 release.

**Comment by hramos** [comment]
@atlanteh the release schedule is fixed, and unless tests are broken, the release will go out. 

I'm not sure what you mean by "address almost instantly" -- this is a GitHub issue, not a pull request. We rely on contributors from the community to help address any issues that affect them.

**Comment by atlanteh** [comment]
@hramos I understand that, but fact is, that border radius doesn't work on latest releases. Someone broke it few releases ago and for some reason nobody cares. This means there's no test coverage on border radius? Almost no one uses it?

**Comment by rsnara** [comment]
Sorry for not getting to this earlier. But it seems like the calculations in [ReactViewBackgroundDrawable.drawRoundedBackgroundWithBorders](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L329-L454) might be a bit off. That's just a hunch though. Regardless, the problem should be in ReactViewBackgroundDrawable, since that's the class we use to do border drawing in Android. 

Unfortunately, I'm a bit swamped with work, so I can't guarantee that I'll get to this fix anytime soon. [This comment](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L626-L712) explains how rounded borders work. It shouldn't be too difficult to understand, so I'd love it if someone else could take a crack at it.

**Comment by Annihil** [comment]
The border radii work perfect on Android, but it's just completely aliased unfortunately (whereas antialiased on iOS)

![](https://i.imgur.com/wGVbKJS.png)

**Comment by sandropoluan** [comment]
@react-native-bot why is this closed? I'm use v0.53.0 and and still having this problem.

**Comment by derN3rd** [comment]
It's closed because of the github stale bot.
But yeah, the problem is still present.

@dannycochran could you please reopen this issue?

**Comment by dannycochran** [comment]
I'm not sure I can re-open the issue, pinging @hramos

**Comment by TheSavior** [comment]
The auto close bot had a bug and closed way more issues than intended. It was turned back off soon after. :-/

**Comment by animaonline** [comment]
Having this problem in 0.54, any updates?

**Comment by hramos** [comment]
No updates, the issue is up for grabs -- no PR has been submitted yet.

**Comment by TheSavior** [comment]
@animaonline This comment by @rsnara is probably the right place to start looking: https://github.com/facebook/react-native/issues/17267#issuecomment-366457506

**Comment by allengleyzer** [comment]
@animaonline The border refactoring started (and broke) with commit 4994d6a389b4e41ba25e802edab5d3fdc9e8a4f1, files affected are `ReactViewBackgroundDrawable` and `ReactViewGroup`. Essentially all the changes to those files since that commit seem to be related to the refactor.

**Comment by abarisic86** [comment]
@hramos change of rendering rounded corners after version 50.4 produced more than this problem (#18000), can we revert those changes until it's implemented correctly? For users that used newly introduced renderer with more options, they can stay on the current version until it's fixed and rest of us can update to next version. I will be happy to make PR if that makes sense to you. What do you think?

**Comment by hramos** [comment]
Reverting a commit after more than a few hours is not something we usually do - at this point we have to consider fixing this forward, especially considering changes introduced in 0.50.4 have been in use at Facebook for over 4 months now.

**Comment by thangkho** [comment]
when I test with RN 0.49 it working perfect.

**Comment by thangkho** [comment]
when I test with old vesion RN 0.49 it working perfect.
` <TouchableOpacity style=
{{ width: 300, 
height: 100, 
borderRadius: 50,
borderWidth: 2, 
borderColor: 'red' }}>
</TouchableOpacity>`

**Comment by alansainz** [comment]
Has anyone found a workaround for this?

**Comment by itchingpixels** [comment]
This is currently blocking us as well.

**Comment by Rah1x** [comment]
I cant believe its not resolved in all this time.. sick an tired of bloody RN programming half the month I just spend fixing and upgrading dependencies!

**Comment by Rah1x** [comment]
So I couldnt install my old RN app die to this issue:
https://github.com/facebook/react-native/issues/6692

So I had to upgrade RN to another version and try again. Now ive this issue of borderradius. So now ive 2 issues - whats the point of upgrade!

**Comment by Rah1x** [comment]
Still not fixed:

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: ^0.55.3 => 0.55.3

**Comment by iamdurui** [comment]
Still not fixed: 
  react-native: ^0.55.3 => 0.55.3
It is my code 
<View style={styles.sButton}>
                <Text style={styles.lText}>立即申请</Text>
              </View>
 sButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 36,
    borderColor: '#fff',
    marginTop: 18,
    width: Dimensions.get('window').width - 180,
    borderWidth:2,
    borderTopRightRadius:10
  },
lText: {
    fontSize: 16,
    color: '#fff',
  },
first , I run this code at android 4.3(Coolpad 5200s) 
![default](https://user-images.githubusercontent.com/16399401/39170645-d97dcd9e-47ce-11e8-982b-e99ed24181d0.png)
second ,I run this code at android 7.0(HUAWEI P9)
![14_53_35__04_24_2018](https://user-images.githubusercontent.com/16399401/39170860-9553ec60-47cf-11e8-9530-f92b2942ea3a.jpg)

**Comment by himabindugadupudi** [comment]
Fixed with commit c5ca26a which is now in Master. Please test with Master build.

**Comment by TheSavior** [comment]
@Rah1x, it will be part of the April release.

**Comment by TheSavior** [comment]
It seems like we are pretty close to 0.56 and this bug has existed for many releases. I’ll leave it up to @grabbou to decide on whether it should be cherry picked.

**Comment by Rah1x** [comment]
I see the new release `0.55.4` at 
https://github.com/facebook/react-native/releases

However since im using `react-native-git-upgrade` I cant seem to upgrade. This is what I get when I run it

> git-upgrade ERR! Error: The specified version of React Native 0.55.4 doesn't exist

**Comment by atlanteh** [comment]
React Native 55.4 doesn't include this fix. It probably only includes a cherry-pick or two of critical bugs that couldn't wait until next release.
As much as I want this bug fixed, it's not considered critical.

**Comment by yakirbu** [comment]
@atlanteh 
How isn't it considered critical? 
An app UI that is mostly designed with border-radius items will have all its views pixelated.

I hope it will be added to the next version.

**Comment by atlanteh** [comment]
Since this bug has been discovered quite few releases ago and not fixed until now, it's no longer critical. If it was discovered just after cutting a release, I think it would qualify as critical and a new hotfix would be released, but after so long, it's not longer urgent enough

**Comment by TheSavior** [comment]
I'm not sure that critical vs non-critical really matters at this point. This issue has been fixed but we haven't had a release since then. This fix will be in the next release.

**Comment by atlanteh** [comment]
Should be any moment, the release was delayed due to tests failing and there's already a PR fixing them.
See here: #19625

**Comment by Rah1x** [comment]
Thats why ive given up on RN altogether.. In all the years of development, ive never seen a system full of silly bugs such as the border blurr and that couldnt get resolved only to tell you the list of enormous bugs they mustbe fixing elsewhere. Just call it BugNative instead of ReactNative!

**Comment by jamesloper** [comment]
I was the lead developer for 7 months during a huge app build. We had quite an incredible product in my eyes. In the end we decided to scrap it because it was taking too many resources on our company. Right before we were winding down and returning to more pressing development matters, we noticed the bug. We tried to handle it internally but on the next release, our lead disigner popped in and cursed because everything looked ffffed up. At that moment we threw in the towel and gave up on react native even though the project was still technically ongoing. If our company had decided to continue working on that project, to this day we would still not be hearing the end of it from our disgruntled designer who rightfully so thought we can't do simple tasks like draw a rounded rectangle or have two 1px borders have equal width. I'm distanced from the effects this bug reaps because I haven't touched react native in so long and the cancellation of the project coinsided with the release that introduced  this bug but can not see how this bug never sounded major alarms. Side note react native was a blast to use otherwise and we considered it to be a very production ready library. Expo was incredible.

**Comment by hramos** [comment]
This fix is now part of the latest release candidate: https://github.com/facebook/react-native/releases/tag/v0.56.0-rc

The schedule is meant to provide a reasonably stable release every month or so, but there's nothing preventing anyone from using React Native from master. In the future, you can take advantage of any fixes-in-master-but-not-yet-in-a-release by using React Native from master or pinning your `react-native` package to the commit that introduced the fix.

I'd also like to take the opportunity to remind everyone that this repo abides to the following Code of Conduct: https://github.com/facebook/react-native/blob/master/CODE_OF_CONDUCT.md. Maintainers will hide comments from first offenders, and they reserve the right to block repeat offenders.
