### ISSUE TITLE
Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')

### ISSUE THREAD

**Issue by a3diti** [facebook/react-native#17348]
When changing scheme to Release in able to run the app on the device, it triggered an error
```
Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')
```
This crashed the application.

I searched for the error code and found it: `project/node_modules/react-native/Libraries/Components/Subscribable.js` on line 33 with RN 0.51.0

**Comment by a3diti** [comment]
I fixed it by evaluating variable `this._subscribableSubscriptions` on line 33 on react native file `project/node_modules/react-native/Libraries/Components/Subscribable.js`

Changing this:
```
this._subscribableSubscriptions.forEach(
```

To this:
```
this._subscribableSubscriptions && this._subscribableSubscriptions.forEach(
```

**Comment by avshenuk** [comment]
@facebook-github-bot reopen please. It's the same issue for me. No addition information. Just started to throw this error today without any changes.

**Comment by avshenuk** [comment]
React Native version 0.50.3 is affected too

**Comment by a3diti** [comment]
My bad for closing it, the issue is fixed for the moment as i mentioned it above, the problem seems to be related to the **Subscribable** component of RN. 
<img width="626" alt="screen shot 2017-12-26 at 00 14 01" src="https://user-images.githubusercontent.com/3646190/34343510-b8e9142c-e9d1-11e7-9aaf-582198334771.png">

**Comment by noambonnie** [comment]
I also have this issue. RN 0.51.0, running a release build on Android 7.

**Comment by leethree** [comment]
I'm seeing the exact same issue. Looks like `Subscribable.componentWillUnmount` is called before `Subscribable.componentWillMount` is called.

**Comment by zhangsn** [comment]
Same issue for me. No code changes. It suddenly fails. RN 0.50.4

**Comment by gveeden** [comment]
@a3diti I Could kiss you!

**Comment by brownieboy** [comment]
Getting this error too, on a new test app, created with react-native-cli@2.0.1, which used react-native 0.51.0 and react 16.0.0.

@a3diti 's code change to the `Subscribable.js` file worked for me too, but that's a workaround, not a fix though.  You would have to put that code change in every time you cloned your repository and ran `npm install`.  We need a proper fix for this.

**Comment by luhui** [comment]
same issue for me.  debug build works fine, but fail in release build. RN 0.51.0

**Comment by troublediehard** [comment]
I have this error when building APK via Expo. RN 0.51.0

**Comment by atesoriero2000** [comment]
Same Issue. Changing line 33 in `project/node_modules/react-native/Libraries/Components/Subscribable.js` to:

> `this._subscribableSubscriptions && this._subscribableSubscriptions.forEach(`

worked for me! Thankyou!

**Comment by steveccable** [comment]
If that workaround is working for people, anybody mind making a PR against RN itself so that this problem is fixed for everyone?

**Comment by sonaye** [comment]
The proposed workaround did it for me, but it introduced another bug (throws in dev mode only):

<img width="400" src="https://user-images.githubusercontent.com/23000873/34363524-de71bc82-ea8d-11e7-8f52-13c605c016bd.png">

Seems related to `react-navigation`.

**Comment by cyphire** [comment]
I am closing the issue I created today for this one.  Here is what I contributed on it.


### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
                                                       
Environment:                                           
  OS: Windows 10                                       
  Node: 8.9.1                                          
  Yarn: 1.3.2                                          
  npm: 5.5.1                                           
  Watchman: Not Found                                  
  Xcode: N/A                                           
  Android Studio: Version  3.0.0.0 AI-171.4408382      
                                                       
Packages: (wanted => installed)                        
  react: 16.0.0 => 16.0.0                              
  react-native: 0.51.0 => 0.51.0                       
                                                       

### Steps to Reproduce

1.  When building the app in normal debug mode, no issue. 
2.  Created a dummy certificate and updated the build.gradle correctly, In the "android" directory, I ran "gradlew assembleRelease".
3.  This created the correct SIGNED app-release.apk in the apk directory.
4.  Installed the app-release.apk in both the emulator on computer as well as an LG V20 device.
5.  Both the emulator and the device crash on startup.
6.  Other person with same issue:
[GitHub issue 353891887](https://github.com/facebook/react-native/issues/16522#issuecomment-353891887)

### Expected Behavior


I expected that the release version would work as the debug version did.

### Actual Behavior

Signed apk crashes when any screen which has any version of ScrollView in it's render.

The problem is this: 
`   this._subscribableSubscriptions.forEach
`
fails because the "this._subscribableSubscriptions" is null (and should not be).

Here is where the error occurs: in Subscribable.js 
(..\node_modules\react-native\Libraries\Components\Subscribable.js)

This is the original code.
```
  componentWillUnmount: function() {
    this._subscribableSubscriptions.forEach(
      (subscription) => subscription.remove()
    );
    this._subscribableSubscriptions = null;
  },

```
Here is where i removed the failing call.  I have confirmed that this._subscribableSubscriptions returns a null and crashes when the forEach() is called.
```
  componentWillUnmount: function() {
  console.log(`Subscribable - error location? ${this._subscribableSubscriptions}`)  
  if (false) {
    this._subscribableSubscriptions.forEach(
      (subscription) => subscription.remove()
    );
  }
    this._subscribableSubscriptions = null;
  },

```
Following removing the offending code, the app no longer crashes on startup.

FROM LOGCAT:

```
12-26 16:02:51.675 20609 20609 D ReactNative: ReactInstanceManager.ctor()
12-26 16:02:51.678 20609 20609 D ReactNative: ReactInstanceManager.createReactContextInBackground()
12-26 16:02:51.678 20609 20609 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
12-26 16:02:51.679 20609 20609 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
12-26 16:02:51.679 20609 20609 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
12-26 16:02:51.679 20609 20609 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
12-26 16:02:51.721 20609 20625 D ReactNative: ReactInstanceManager.createReactContext()
12-26 16:02:51.783 20609 20625 D ReactNative: Initializing React Xplat Bridge.
12-26 16:02:51.784 20609 20625 D ReactNative: Initializing React Xplat Bridge before initializeBridge
12-26 16:02:51.789 20609 20625 D ReactNative: Initializing React Xplat Bridge after initializeBridge
12-26 16:02:51.789 20609 20625 D ReactNative: CatalystInstanceImpl.runJSBundle()
12-26 16:02:51.807 20609 20633 D ReactNative: ReactInstanceManager.setupReactContext()
12-26 16:02:51.807 20609 20633 D ReactNative: CatalystInstanceImpl.initialize()
12-26 16:02:51.812 20609 20633 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
12-26 16:02:51.940 20609 20632 I ReactNativeJS: Running application "test" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
12-26 16:02:51.965 20609 20632 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')
12-26 16:02:51.965 20609 20632 E ReactNativeJS:
12-26 16:02:51.965 20609 20632 E ReactNativeJS: This error is located at:
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in ScrollView
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in RCTView
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in RCTView
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in RCTView
12-26 16:02:51.965 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.969 20609 20632 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')
12-26 16:02:51.969 20609 20632 E ReactNativeJS:
12-26 16:02:51.969 20609 20632 E ReactNativeJS: This error is located at:
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in ScrollView
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in RCTView
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in t
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in RCTView
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in RCTView
12-26 16:02:51.969 20609 20632 E ReactNativeJS:     in t
12-26 16:02:52.418 20609 20609 D ReactNative: ReactInstanceManager.detachViewFromInstance()

```
### Reproducible Demo

Because the app crashes on a production build here is a simple App.js file.

This demo can be reproduced by:
1. creating a new:           react-native init test
2. substituting the App.js code below for the App.js which is the default on creating a project.
3. follow instructions for creating a keystore
4. updating the gradle.build as per the instructions in react-native docs.
5. build in the android directory with "gradlew assembleRelease"
6. run and see that with version 51.0 crashes in the Scribbable.js (as show above) although, of course, it's not Scribbable wher the error is, that is just where it occurs.

NOTE: but probably not important.  When I build my app (either my own app or the test app), I must run gradlew assembleRelease twice, it always fails the first time.  I think it needs to reset the transform cache.

ADDITIONAL NOTE: From what the other person who has seen  this said, when reducing the version of React-native to 49.5 the problem goes away.

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  FlatList,
  StyleSheet,
  Text,
  View
} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

export default class Example extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <FlatList
          data={[{key: 0, title: 'Hello1'}, {key: 1, title: 'Hello2'}, {key: 2, title: 'Hello3'}]}
          renderItem={(itm)=> {
            return (<View key={itm.item.key}><Text>{itm.item.title}</Text></View>)
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

```

**Comment by jnrepo** [comment]
made a PR https://github.com/facebook/react-native/pull/17359 for react-native folks.

I'm actually having the same issue here: https://github.com/jnrepo/react-native-custom-components/blob/master/src/Subscribable.js will make another PR for that module as well.

**Comment by ohflying** [comment]
The issue is caused by the uglify-es@3.3.2，back to 3.2.2

**Comment by googya** [comment]
@ohflying how did you find the reason of being caused by uglify-es ?

**Comment by vovkasm** [comment]
@googya Not sure about concrete uglify-es versions, but it looks ulify-es related. Why?

1. study of code in Subscribable.js
2. For us this crash was very environment dependent:
 - local builds always works, simulator or device
 - jenkins builds deployed to testfligh always fails
 - crashes or they absence was stable and reproducible, so if app crashed it always crashed, if not it always works, so it looks as packaging issue.

We did not try to deeply investigate packing process, because fork/patch RN was more fast and logical fix for us, but I probably can diff bundled js from jenkins builds and local (if it is really needed).

**Comment by leethree** [comment]
This bug should be caused by `uglify-es` 3.3.X. I confirm that it's fixed by downgrading `uglify-es`. Just add this block to `package.json`:

```json
  "resolutions": {
    "uglify-es": "3.2.2"
  }
```

**Comment by mohamed-ismat** [comment]
Is there a workaround for this problem for people using Expo? it's using a fork of react native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz
Did anyone try reverting to an older sdk version? @troublediehard

**Comment by troublediehard** [comment]
@mohamed-ismat no I didn't try another SDK version, didn't find another workaround as well. In my case, it was test project, so I just stop using Expo.

**Comment by sonaye** [comment]
@mohamed-ismat @troublediehard Why stop using Expo? this is JS, not native. You can modify the code as long as it doesn’t introduce any new native deps. The packager bundles all the JS into a single entry file and push it through the air (opens just like any other link if opening from the Expo client, stored locally if standalone until you push a new version).

**Comment by sonaye** [comment]
What I would like to know is why would componentWillUnmount fires before componentWillMount?

**Comment by troublediehard** [comment]
@sonaye I don't get your point. How do you suggest to fix this issue for Expo?

**Comment by sonaye** [comment]
@troublediehard open node_modules/react-native and make your edit there. The point is that this is javascript code not native code.

**Comment by troublediehard** [comment]
@sonaye this isn't work.
I run 
`exp build:android `
and it builds APK on the Expo server. I believe It doesn't use your local node_modules, so changes will not effect the end result.

**Comment by mohamed-ismat** [comment]
For people using Expo, you don't need to edit anything in react-native. I confirm that adding 

` "resolutions": {
    "uglify-es": "3.2.2"
  }`

to `package.json` does indeed fix the problem. 

Tried both publishing on Expo and building a standalone app and it's working like a charm

**Comment by sonaye** [comment]
> I believe It doesn't use your local node_modules, so changes will not effect the end result.

@troublediehard why would you believe that? the build services are for the native side only, any javascript would be bundled on your machine and sent to these services. can you at least try my solution, it is working for me.

**Comment by Daadler6** [comment]
@mohamed-ismat for Expo what APK are you using?

**Comment by mohamed-ismat** [comment]
@Daadler6 when you build the app using `exp build:android` for example it uploads your code to their site and creates an APK which you can download. Do you mean which APK or which SDK? I'm using `sdkVersion: 24.0.0`

**Comment by Daadler6** [comment]
@mohamed-ismat - Thanks! Yes I meant SDK as I am currently on 23.0.0. However the ```"resolutions": { "uglify-es": "3.2.2" }``` ended up fixing it once I did a full reload. Thanks!

**Comment by sonaye** [comment]
`"resolutions": { "uglify-es": "3.2.2" }` fixed the issue that was introduced by the first solution `this._subscribableSubscriptions &&` for me.

**Comment by bochen2014** [comment]
downgrade `gulify-es` worked for me. 
```json
 "resolutions": {
    "uglify-es": "3.2.2"
  }
```

it seems that `gulify-es` has cause quite a few issues (#16745)
It also seems that `react-native` doesn't have smoke test? or integration test (release version)

**Comment by chenweigh** [comment]
How to fix it? anyone have idea? The Same Issue for me.
<img width="443" alt="2017-12-28 11 53 57" src="https://user-images.githubusercontent.com/15101298/34399785-d4da1d84-ebc5-11e7-8f4c-d00068572efb.png">

**Comment by avshenuk** [comment]
Downgrade of react-native to 0.49.5 helped me.

**Comment by pavlomakarov** [comment]
This issue seems to only occur in minified code. Upgrading metro-bundler to the latest version resolved it for me. You can just explicitly add it to your dependencies, I'm using `metro-bundler `0.22.1. Also, adding `uglyfy-es@3.2.2` to resolutions didn't help, because older versions of metro bundler still forced a 3.3.2 dependency

**Comment by avshenuk** [comment]
uglify-es or uglify-js? Because uglify-es didn’t help me...

**Comment by kadoshms** [comment]
I encounter the same issue.

**Comment by jnrepo** [comment]
```
 "resolutions": {
    "uglify-es": "3.2.2"
  }
```
does not work for me as well

**Comment by sachabest** [comment]
+1 for `npm install -save uglify-es@3.2.2`; No need to mess with resolutions. Delete `node_modules/`, run that line, and publish. Works beautifully.

**Comment by novalagung** [comment]
I modified `project/node_modules/react-native/Libraries/Components/Subscribable.js`, and it's working. but I think this is not the right way to solve this issue. I haven't tried to downgrade `uglify-js`

**Comment by googya** [comment]
@jnrepo  if you are using mom and not yarn,you should add uglify-es under dependencies,

**Comment by jnrepo** [comment]
@googya using node and tried adding it dependencies, but still didn't work. used command below

`npm install -save uglify-es@3.2.2`

**Comment by jnrepo** [comment]
got it work, for node people make sure the uglify-es module version is set specifically to 3.2.2.

`"uglify-es": "3.2.2"`

I had `"uglify-es": "^3.2.2"` before and it would fail

**Comment by FreddyPoly** [comment]
@jnrepo 's solution worked for me, thanks a lot !

But it worked once I deleted the `node_modules` folder but also the `package-lock.json` file. So if it's still not working for you, try adding `uglify` as a dependency:

`npm install --save uglify-es@3.2.2`

Change your `package.json`:

From `"uglify-es": "^3.2.2"` to `"uglify-es": "3.2.2"`

And then run:

`rm -rf node_modules/ package-lock.json  && npm i`

**Comment by wkwiatek** [comment]
As @pavlomakarov said in https://github.com/facebook/react-native/issues/17348#issuecomment-354276752, the `metro-bundler` in older version can still force `uglify-es@3.3.2`, so for me installing latest version of metro-bundler did the trick: 
```
npm i metro-bundler
```
or specifically
```
npm i metro-bundler@0.22.1
```

**Comment by gaberudy** [comment]
Had the same issue and only @pavlomakarov solution worked for me (`"metro-bundler": "0.22.1"` to my dependencies).

Deeply troubling that a minification pass causes this type of logic issue, as the implications for the rest of the app are unknown but also possible unstabilizing. JS stacks feel like such a house of cards sometimes...

**Comment by cowai** [comment]
I think I do not get the issue when I clear the npm cache and it installed the latest version of uglify-es 3.3.3 from the last day. Can anyone confirm?

**Comment by Jaftem** [comment]
Hey everyone, posting in case someone goes through the same headache as I did this morning.

Just finding this issue was extremely tough. The exception did not appear for me if I did a reload and had the dev server bundle my code. And if I uninstalled the app and ran `react-native run-android`, I also would not get this thrown exception (even if not connected to the dev server). The exception *only* appeared in production builds or after I created a new bundle and build without connecting to the dev server.

@ohflying 's solution worked for me. `npm install -save uglify-es@3.2.2`

**Comment by esutton** [comment]
@gaberudy I agree with your statement that "JS stacks feel like such a house of cards sometimes...".  "Two steps forward and one step back"...

The metro and uglify solutions did not work for me.  

In order to build new Android release builds I had to roll back from ^0.51.0 to:
````
"react-native": "0.49.5",
````

**Comment by sandropoluan** [comment]
I confirm my problem fixed with
`npm install -save uglify-es@3.2.2`

**Comment by simplepanda** [comment]
Also confirming that an `rm -rf node_modules`, adding a fixed dependency to 3.2.2 of `uglify-es` (not 3.3.x), then a `yarn install` and a recompile fixes this issue for me.

I see this issue was opened and closed - and that the proposed code fix above has some side effects in dev mode (`this._subscribableSubscriptions && this._subscribableSubscriptions.forEach(`). 

Any suggestion as to the production fix going forward? Confirmed to be an `uglify-es` issue, I suppose?

**Comment by simplepanda** [comment]
Also looks like adding a dependency to `"uglify-es": ">=3.3.4"` solves this issue for me too. So 3.2.2 = ok and 3.3.4 = ok, but 3.3.2 = NOT ok.

**Comment by brownieboy** [comment]
I just created a brand new project with react-native-cli 2.0.1 (the latest version as I write this) and once I'd added my dependencies (`native-base` and `react-navigation`) I saw that the installed version of `uglify-es` was already set at `3.3.4` without me having to modify it.

I was able then to install a Release version of my app directly to my iPhone without incurring the crash.

So issue solved, for new projects at least?

**Comment by a3diti** [comment]
For those who have initiated the project and have already uglify-es version 3.3.2 please update to higher version. 

## For new created projects the problem is fixed automatically because current version of uglify is [v3.3.4](https://github.com/mishoo/UglifyJS2).

## The problem
It was caused with the app crashing when installing the app as release on the simulator or device from component of react-native located in: `Libraries/Components/Subscribable.js`.
It seemed the `componentWillUnmount` was called before `componentWillMount` and generating an error for an undefined variable, this kind of problem is believed to be generated from uglify-es v3.3.2 and fixed by uglify-es v3.3.4, some kind of bug during compression of js files, probably on rare occasions (when RN project is build with release mode it is compressed by default using uglify-es).

## Solution
Note: For projects initiated with uglify-es v3.3.2 and probably lower versions
1. Add a `resolutions` part to `package.json` for your project in order to get v3.3.4 or higher of uglify-es:
```
  "resolutions": {
    "uglify-es": ">=3.3.4"
  }
```
2. Type `npm install` or `yarn install` to install the node packages

Example of [package.json](https://gist.github.com/a3diti/f6fb7c1f894196870a4791b122e30dad)
## Done
I'm closing the issue since it is automatically resolved.

**Comment by Liron-K** [comment]
I am seeing this even with uglify-es set to 3.3.4.

**Comment by esutton** [comment]
@a3diti Adding a resolution is a temporary work-around and not a fix.

I expect many people will run into this but may not be lucky enough to determine the root cause let alone discover this closed issue and a work-around.

**Comment by a3diti** [comment]
@esutton Ok, i guess you have a different environment since the `uglify-es` solution didn't work for you.

I recommend some necessary actions to perform when installing `uglify-es`, i do those sometimes when i have unexplainable errors:
- Clean build on Xcode
- Delete all folders inside DerivedData folder by going to Xcode>Preferences>Locations> press the icon on DerivedData folder locations, and delete all folders inside.
- Quit Xcode entirely
- Stop any react native listening cli (Metro Builder)
- Delete app from your testing device/simulator
- With terminal go to your project root, delete `node_modules` folder, remove `package-lock.json` file, re-install packages using yarn, not npm 5.x because v5.x is known to have some bugs.
```
rm -rf node_modules
rm -rf package-lock.json
yarn install
```
- Test your app by running Debug or Release version

When i test the app for release, on Xcode i go to "Edit Scheme">Run>Build Configuration>Release
Also i test it on TestFlight on some devices before releasing it.

**Comment by Liron-K** [comment]
So I updated all of the dependencies in my package.json, removed node_modules *AND* the package-lock.json and did a clean/rebuild in release mode and that worked.

I'm not sure if it was the package-lock or that the dependencies weren't all on the most up-to-date level, but that fixed it.

**Comment by esutton** [comment]
@a3diti Shouldn't this be fixed in react-native and * * NOT * * as a **manually added resolution** in a **developer's project's package.json**?

### Concerns:
1) Requiring the addition of an **uglify-es resolution** to your **Awesome project's package.json** is * NOT * a fix.  It feels like a temporary work-around for the root problem.

2) **Question:** How will a developer know he needs to add an **uglify-es resolution** to the project's package.json ???  Changing **react-native init** to add the **uglify-es resolution** seems silly.

### Work-Around:
I confirmed this works on both Android and iOS release builds.

Add and commit an uglify-es 3.3.4 resolution to your project's package.json:
```
	"dependencies": {
                ...
		"react": "^16.2.0",
		"react-native": "^0.51.0",
                ...
	},
	"resolutions": {
		"uglify-es": "3.3.4"
	}

```
git clone https://acme.com/Awesome source
cd source
yarn
react-native run-android --variant=release
# Use Xcode to verify Scheme is set to release
react-native run-ios
```

**Comment by 362228416** [comment]
+1

**Comment by esutton** [comment]
I expect * many * release build apps have suddenly started crashing due to this minification bug.  I randomly ran across this one: 
[[Minification Bug] Crash on google pixel and IOs #199](https://github.com/FormidableLabs/victory-native/issues/199#issuecomment-355561793)

**Comment by iMagdy** [comment]
This comment https://github.com/facebook/react-native/issues/17348#issuecomment-353892314 fixed it for me.

Thanks @a3diti !

I've submitted a PR (https://github.com/facebook/react-native/pull/17463) with this fix. Hopefully it gets merged soon.

**Comment by arma7x** [comment]
Upgrade to RN0.52 works for me

**Comment by sonaye** [comment]
`uglify-es@3.3.5` breaks code too.

**Comment by quincycs** [comment]
@sonaye thanks!  I'm using expo 24 and your comment worked for me.  I had to do both your steps.
https://github.com/facebook/react-native/issues/17348#issuecomment-354209083

**Comment by ryanhomer** [comment]
[Forcing `@3.2.2`](https://github.com/facebook/react-native/issues/17348#issuecomment-354424195) worked for me. Issue is still present in `uglify-es@3.3.7`. There were [a lot of changes](https://github.com/mishoo/UglifyJS2/commits/master?after=ec7cd1dcf7c7a3b86288061b61ad72ba081f83bb+69) between `3.2.2` and `3.3.0` (over 40 commits) so it may take a while to figure out what caused this.

**Comment by RafaelMagalhaesN** [comment]
Solved with uglify-es 3.3.4 (steps: delete uglify-es from node_modules, put in your package.json "uglify-es": 3.3.4 and finally  install with npm i).

**Comment by sonaye** [comment]
`uglify-es@3.2.2` is the only stable resolution that worked for me so far, any new version breaks the app somewhere, up to `@3.3.7`.

**Comment by asarmohd** [comment]
We can resolve the issue by checking this._subscribableSubscriptions on line 33 on react native file project/node_modules/react-native/Libraries/Components/Subscribable.js - line 33

(-)this._subscribableSubscriptions.forEach
(+)this._subscribableSubscriptions && this._subscribableSubscriptions.forEach(

**Comment by temitope** [comment]
Running into same issue only on release not debug.
RN 0.51

**Comment by hugoh1995** [comment]
Nothing works for me, tried all fixes mentioned above but app still crashes when scrolling inside a scrollview on Android Real Device (Samsung)

**Comment by add-ryan** [comment]
For me the problem was that the function is called inside the wrong object. Replacing onPress={this.someFunction} with onPress={() => {this.someFunction()} did the trick.
