### ISSUE TITLE
[0.54] Warnings for soon to be deprecated lifecycle methods

### ISSUE THREAD

**Issue by pbogdan03** [facebook/react-native#18175]
### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

No warnings would appear in debugger console.

### Actual Behavior

Warnings about React soon to be deprecated lifecycle methods are displayed.
e.g.:
```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: Container, Image, ResourceSavingSceneView, TabViewPagerPan, TouchableOpacity, Transitioner, withCachedChildNavigation(TabView)

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

### Steps to Reproduce

```
react-native run-ios
```
With Chrome debugger open.

**Comment by Krestek** [comment]
Same here, with run-android too.

**Comment by kelset** [comment]
This deprecation won't happen for quite some time still, and it's a React issue per sè. Closing.

**Comment by mjfox09** [comment]
Is this an issue with the React version then? Deprecating it down to 16.0.0 shows the same warning boxes.

**Comment by graig12** [comment]
Same issue Replicated both on  ios and android.

**Comment by JorgeMoralesLopez** [comment]
Same here too on android.

**Comment by clebertom** [comment]
Same issue android and ios.

**Comment by realtebo** [comment]
I understand that you think that will need only a short time poeriod before *all* dependecies will upgrade itselfs... but in the while, what's the right syntax for console.ignoreYelloBox ?

**Comment by mjfox09** [comment]
@kelset These warnings are generating YellowBoxs that we are going to have to ignore for "quite some time"? 

Also, this isn't a React issue at all. React is deprecating the component lifecycles that React-Native components are using. The React-Native components need to be upgrade in order to conform with the new React standard.

Would you consider re-opening this issue for extended discussion on the subject?

**Comment by njwest** [comment]
To my mind, the bigger problem is not that React Native throws this warning, but that it throws **six yellow boxes** (in my case) due to duplicate deprecation warnings for componentWillMount and componentWillReceiveProps. 

This hurts the dev experience and makes debugging more time consuming, as the seconds wasted getting distracted by and dismissing/ignoring duplicate irrelevant errors start to add up.

**Comment by deepanchakravarthi** [comment]
Hi Guys,

I'm a beginner and I started to learn React Native for the past 2 days. I got the same error in Android. We can't ignore it - It's my opinion. We need to discuss on it and find the solution.

**Comment by sydneywu** [comment]
So can i understand that react is deprecating componentWillMount / componentWillReceiveProps, and it is react-native that will need to update TouchableHighlight/ Text /View. Not the developers that are using the elements wrongly?

**Comment by pbogdan03** [comment]
Every component that uses that method will need to be updated, so both react-native and developers need to take action.

**Comment by deepanchakravarthi** [comment]
Also I checked react js website. There is no update/log/documentation about this issue. But I'm very sure that the issue not because of development bugs. According to the warning message, there must be an alternative solution for it. I could not get after a long time search.. :( and I'm wondering about this issue ;)

**Comment by ShiChenlong** [comment]
In my opinion,react is deprecating the component lifecycles that React-Native components are using.The React-Native components need to be upgraded in order to conform with the new React standard.

**Comment by dhani112** [comment]
I am a beginner in react native.The same warning message am getting in every project i am creating 
**componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
Please update the following components: Text, View**

**Comment by turnrye** [comment]
This was a confusion for a few engineers on my team. React has an RFC that
proposed changes to the lifecyle methods:
https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md

It's a big change, and supporting it will take some time. To hide the
yellow box would be to inappropriately ignore a deprecation, but users
should understand that this is not due to their code but instead internal
to React Native.

**Comment by jhnferraris** [comment]
Here's a link of "what's to come":

https://github.com/facebook/react-native/issues/18165#issuecomment-369913385

**Comment by mjfox09** [comment]
Thank you @jhnferraris and @gre for the code to disable these warnings. 

Will this disable warnings  for custom components as well as React-Native provided components?

**Comment by njwest** [comment]
@turnrye While hiding deprecation warnings may be inappropriate, there is no reason why the deprecation warnings for both lifecycles (which are hard-coded in and thrown by React Native, not by the React lib) should be duplicated twice or more. 

The duplication issue is a bug, as the warnings are identical and are thrown from the same path and may obscure other yellow boxes in debugging. It would be appropriate to only throw the deprecation warnings once.

I suppose that is the price of free software.

**Comment by njwest** [comment]
@mjfox09 You should avoid using componentWillMount completely -- put any logic you want to run pre-mount in your component's **constructor()** function.

**Comment by turnrye** [comment]
@njwest absolutely – there should not be duplicate warnings.

**Comment by mjfox09** [comment]
@njwest I think there's some confusion in my question. I understand what the RFC states and what my code needs to be changed to.

What I'm asking about is if setting the "warnAboutDeprecatedLifecycles" flag to false (found on the ReactFeatureFlags package) will impact the warnings that React is generating for my projects components or if it will only remove warnings for React-Native components. I don't have my project in front of me to try this.

Take a look at the issue that jhnferraris linked to get a glimpse of the code I'm talking about.

**Comment by nicodeslandes** [comment]
For those looking for a way to remove those warnings until the React Native components are updated, add the following to your code (eg at the top of `index.js`):
```javascript
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings([
  'Warning: componentWillMount is deprecated',
  'Warning: componentWillReceiveProps is deprecated',
]);
```

I agree that `componentWillMount` should be avoided completely, but until the React Native components are updated those warnings are just getting in the way.

**Comment by gre** [comment]
alternatively you can also do this: https://github.com/facebook/react-native/issues/18165#issuecomment-369907978

**Comment by gaearon** [comment]
I want to stress **these lifecycles are not being deprecated yet**. Again, we’ll post a blog post with more details. The warning came before the blog post by accident.

**Comment by gaearon** [comment]
Also, this definitely sounds like a bug:

>Please update the following components: Text, View

>To my mind, the bigger problem is not that React Native throws this warning, but that it throws six yellow boxes (in my experience at least) due to duplicate deprecation warnings for componentWillMount and componentWillReceiveProps.

We'll fix or revert this asap. Please give us a day to sort this out.

**Comment by jhnferraris** [comment]
@gaearon Thanks!

**Comment by bvaughn** [comment]
Quick follow-up to Dan's comment. @grabbou and I chatted about this earlier, and the deprecation warning feature flag [has been turned off for the 0.54 branch](https://github.com/facebook/react-native/commit/2f8446319a9b72e64d3c75f36c370eec234dafeb#diff-a638a2c4b7670144a219d4a60b7f765e).

**Comment by jqn** [comment]
@bvaughn this error show up on RN 0.54.0 does this mean in not turned off?

**Comment by hey99xx** [comment]
It's refreshing to see the Dan's responsiveness compared to the person who closed the issue without even attempting to understand the concern.

**Comment by enapupe** [comment]
@hey99xx I'm sure Dan would have done the same: close the issue and get in touch with React team ASAP. This was just the right call since this is the React Native repo and this is a React issue. Have some respect for other peoples' decisions you don't fully understand.

**Comment by hey99xx** [comment]
Since Dan is the one who re-opened the issue, that's clearly not the case. I also don't see any indication that From Lorenzo was the one who contacted React team. From his comment it looked like he was content with all developers see the deprecation warning constantly. I expect the same kind of respect from the contributors of the project, he could have at least guided OP to open an issue in React instead of just closing this report.

**Comment by jhnferraris** [comment]
@bvaughn Re: https://github.com/facebook/react-native/issues/18175#issuecomment-371205379,
what version of RN should we be using to use this fix?

**Comment by bvaughn** [comment]
Whichever one was released after @grabbou's commit (2f84463 ~ March 7, 2018 8:11 am PST)

```
$ npm info react-native | grep 0.54
  'dist-tags': { latest: '0.54.0', next: '0.54.0-rc.4' },
     '0.54.0-rc.0',
     '0.54.0-rc.2',
     '0.54.0-rc.3',
     '0.54.0-rc.4',
     '0.54.0' ],
     '0.20.0': '2016-02-16T17:50:54.610Z',
     '0.54.0-rc.2': '2018-02-12T16:48:13.799Z',
     '0.54.0-rc.0': '2018-02-12T20:35:08.410Z',
     '0.54.0-rc.3': '2018-02-13T18:17:51.808Z',
     '0.54.0-rc.4': '2018-02-27T19:54:11.332Z',
     '0.54.0': '2018-03-01T19:02:06.832Z' },
```

Looks like maybe one hasn't been cut yet? I think Mike was going to cherry-pick a few more fixes in before doing another release. My guess is he hasn't finished that yet. (I am not involved with the `react-native` release process.

**Comment by jhnferraris** [comment]
@bvaughn Thanks for the info. I asked because when I tried `$ yarn add react-native` to update the version I still see the warnings. I'll just wait for the release information

**Comment by grabbou** [comment]
I wanted to cherry-pick few other things before, but since it's already Friday and I don't want to leave this quite important issue too long, I am going to release 0.54.1 with this fix only right now.

Please expect 0.54.2 at the beginning of next week - there are few minor tweaks related to linking that I want to ship.

**Comment by wellyshen** [comment]
@grabbou `react-native-git-upgrade` can't find 0.54.1

**Comment by bvaughn** [comment]
Looks like it hasn't been released yet, @wellyshen:
```
$ npm info react-native | grep 54.1
     '0.54.0-rc.4': '2018-02-27T19:54:11.332Z'
```

**Comment by grabbou** [comment]
Just released it. Sorry, Circleci failed on deploy and had to retrigger
manually.

**Comment by wellyshen** [comment]
@grabbou Great! I updated my RN to v0.54.1 everything works fine!

**Comment by gaearon** [comment]
We'll need to remember to follow up before the next branch cut on this.
Docs will likely be ready by then, but it seems wrong this [fires for Text/View](https://github.com/facebook/react-native/issues/18175#issuecomment-370418075) and [the ergonomics seem not ideal too](https://github.com/facebook/react-native/issues/18175#issuecomment-370310849).

**Comment by bvaughn** [comment]
> To my mind, the bigger problem is not that React Native throws this warning, but that it throws six yellow boxes (in my experience at least) due to duplicate deprecation warnings for componentWillMount and componentWillReceiveProps.

I would not expect this to happen. We only warn [once per component type](https://github.com/facebook/react/blob/fcc4f52cdded62e3b8e95d18e3e6adf17b981eed/packages/react-reconciler/src/ReactStrictModeWarnings.js#L198-L201) and we [collapse all component names into a single warning message](https://github.com/facebook/react/blob/fcc4f52cdded62e3b8e95d18e3e6adf17b981eed/packages/react-reconciler/src/ReactStrictModeWarnings.js#L126-L139) (well, one per lifecycle). We _could_ combine the messages further, but I think a separate warning per deprecated lifecycle makes sense.

**Comment by DimitryDushkin** [comment]
Here we go again at 55.1

**Comment by gaearon** [comment]
The links are all ready now, so they should actually redirect to the blog post with instructions. I'm not sure if we wanted to hold the actual warnings until 16.4.0 or not though (like we did on the web). Let me chat to @bvaughn.

**Comment by gaearon** [comment]
There also shouldn't be false positives like `<View>` and `<Image>`.

**Comment by gaearon** [comment]
Let's reopen for discussion until we're sure everything is intentional.

**Comment by gaearon** [comment]
We asked @grabbou to cut another patch that temporarily disables the warning flag. I guess we need to keep doing this in every stable release until 16.4.0 comes out.

**Comment by bvaughn** [comment]
I think the (temporary) solution to this will be another cherry pick like 2f84463.

**Comment by grabbou** [comment]
I am cherry-picking this one more time. There has to be something really weird with our `RNTester` app as I didn't see any warnings during testing. I will further investigate that to prevent this in the future.

**Comment by grabbou** [comment]
@bvaughn why not just set it to `false` on master until we are ready?

**Comment by gaearon** [comment]
Because we need it turned on internally at FB and don’t currently have a way to use different feature flags in OS builds.

**Comment by bvaughn** [comment]
`master` is auto-synced from fbsource, and it needs to be true in fbsource.

**Comment by grabbou** [comment]
FYI 0.55.2 is on its way (CI tests right now) including a fix for this
issue.

**Comment by bvaughn** [comment]
I've created a gist that goes into more detail about the current feature flag situation:
https://gist.github.com/bvaughn/91583b158a207c72d63954452101b5d6

**Comment by ujwal-setlur** [comment]
@bvaughn Thanks for the explanation. It helps.

Where is this feature flag file for react-native so that we can do some postinstall tweaking to turn off flags that were turned on accidentally?

**Comment by ujwal-setlur** [comment]
Also, for this particular issue where lifecycle hooks have changed, is there a rationale published somewhere? Kind of a core thing to do...Thanks.

**Comment by bvaughn** [comment]
The feature flag file is [`ReactFeatureFlags.js`](https://github.com/facebook/react-native/blob/master/Libraries/Renderer/shims/ReactFeatureFlags.js), but there is no API to expose the feature flags. (They can't be turned off that way.)

**Comment by ujwal-setlur** [comment]
Hmm... This file cannot be edited before a build?

**Comment by ujwal-setlur** [comment]
Setting warnAboutDeprecatedLifecycles: **false** in [ReactFeatureFlags.js](https://github.com/facebook/react-native/blob/master/Libraries/Renderer/shims/ReactFeatureFlags.js) does resolve this issue. Any idea when 0.55.2 is coming out?

**Comment by juanlet** [comment]
same problem here....just updated to
    "react": "16.3.1",
    "react-native": "0.55.0"

and seeing the multiple repeated warnings about life cycle. Which is the version that has the fix?

**Comment by gaearon** [comment]
0.55.2 will have the fix. Will be out in a few days.

**Comment by stage88** [comment]
None of the suggestions worked for me in 0.55.1.

I found that you can manually edit this file https://github.com/facebook/react-native/blob/master/Libraries/Renderer/shims/ReactFeatureFlags.js to disable these warnings.

You can find it in your node_modules folder: node_modules/react-native/Libraries/Renderer/shims/ReactFeatureFlags.js, update warnAboutDeprecatedLifecycles to false

It will work until 0.55.2 is out...

**Comment by wellyshen** [comment]
I got this kind of new deprecated warning in 0.55.2.

![simulator screen shot - iphone 8 - 2018-04-10 at 00 35 37](https://user-images.githubusercontent.com/21308003/38510303-2dd65f06-3c57-11e8-8f8f-89dbd36d3159.png)

**Comment by cwhenderson20** [comment]
@gaearon For me, I don't use `isMounted` anywhere in my project code. I believe the warning is coming from packages inside node_modules. A quick search reveals that it's used in `react-native/Libraries/Components/Touchable` and in a few places in react-navigation.

**Comment by gre** [comment]
I had the same problem today & temporarily used YellowBox to disable this message specifically.

**Comment by gaearon** [comment]
We'll need a minimal reproducing project to look at this.

**Comment by wellyshen** [comment]
Yes I didn't use `isMounted()` in my project but I'm using react-navgiation.

**Comment by bvaughn** [comment]
It looks like these warnings [have been addressed in the 2.x branch of `react-navigation`](https://github.com/react-navigation/react-navigation/issues/3657#issuecomment-379607655) FWIW. Although I guess that's still only available as an RC.

**Comment by wellyshen** [comment]
How to disable `isMounted()` warning? Any workaround?

**Comment by wellyshen** [comment]
YellowBox API can help us ignore these warnings.

```javascript
import { YellowBox } from 'react-native';

// ...

YellowBox.ignoreWarnings([
  'Warning: isMounted(...) is deprecated in plain JavaScript React classes.'
]);
```

**Comment by MiLeung** [comment]
or `console.disableYellowBox = true;` to remove all the yellow boxes completely.

**Comment by ujwal-setlur** [comment]
@MiLeung you don't want to do that. That will get rid of all legitimate warnings that may require addressing

**Comment by juandpr** [comment]
I am having the same issue. I just created a new project using `create-react-native-app`

```
"expo": "^26.0.0",
"native-base": "^2.4.2",
"react": "16.3.0-alpha.1",
"react-native": "0.54.0",
"react-navigation": "^1.5.11"
```

**Comment by MiLeung** [comment]
@ujwal-setlur That is incorrect - warnings still appear in the console. I use it because dismissing yellow boxes is annoying.

**Comment by gaearon** [comment]
@ryan2clw It’s not clear either from your comment or from Q&A which warnings you’re seeing specifically. I also asked for a reproducing case in https://github.com/facebook/react-native/issues/18175#issuecomment-379890106 and neither you nor anybody else in this thread has provided it so far. So it is hard to help you.

**Comment by ryan2clw** [comment]
Hi Dad,

Attached is screen shot.  I’m happy using the expo 25.0.0 version, but if you are attempting to fix it for others, here is the screen shot.  Thanks for looking out.  I just ran the commands for hello world from the React site after installing node and this is the warning once you follow the link in expo and the program loads up.

Sincerely,

Ryan

**Comment by ryan2clw** [comment]
Oops meant Dan, that’s embarrassing

**Comment by gaearon** [comment]
I think mailing attachments doesn't work, could you please go to https://github.com/facebook/react-native/issues/18175 and post it there? Thanks!

**Comment by ryan2clw** [comment]
![img_0101](https://user-images.githubusercontent.com/17858514/39053905-3874dc10-447e-11e8-846d-b4b170e71275.jpg)

<img width="1440" alt="helloworldexporeactwarnings" src="https://user-images.githubusercontent.com/17858514/39053832-04477a42-447e-11e8-8280-eaa596f95c48.png">
YellowBoxes in terminal and app

**Comment by ryan2clw** [comment]
Done

**Comment by gaearon** [comment]
@ryan2clw 

Looking at your StackOverflow question, you were using `react-native@0.54.0`. As explained in this thread **there was a bug in `react-native@0.54.0` which caused this**. The bug was fixed in `react-native@0.54.1`. So if you update to that, it should work.

There was a also similar bug in `react-native@0.55.0`, and it was fixed in `react-native@0.55.2`.

**Comment by gaearon** [comment]
I’m going to close this as the issue appears solved in `0.54.1` (for 0.54 branch) and `0.55.2` (for 0.55 branch).

**Comment by ryan2clw** [comment]
I’ll check that out.  I just installed react from the start-up guide, using npm and then later yarn.  I would recommend that when you run “create-react-native-app ProjectName” that it defaults to 0.54.1, as troubleshooting “helloWorld” might discourage your average noob.

**Comment by gaearon** [comment]
I would expect it to default to the latest version, but cc @ide in case it doesn't.

**Comment by bvaughn** [comment]
FWIW, I believe there was a second source of warnings coming from `NativeMethodMixins` for 0.54 that wasn't fixed until commit d9bd9d5 which was released with 0.54.3.

**Comment by jonathanandrewsuk** [comment]
I started a create-react-native-app a couple hours ago and the default was `react-native@0.54.0`, change it to `react-native@0.54.1` and it solves this problem. (`react-native@0.55.2` didn't work for me.)

**Comment by gaearon** [comment]
I'll ping `create-react-native-app` maintainers. I don't know why it uses a buggy version by default.

**Comment by ericketts** [comment]
I'm not sure whether this still the case, or whether this is the proper place to mention it, but I recall that back in January or so `CRNA` was shipping a broken expo build as well.

**Comment by gaearon** [comment]
Got a word back from CRNA folks, they’ll fix it to use the latest patch. Thanks for pointing it out!

**Comment by ryan2clw** [comment]
Its working, just tried it.  That was a fast turnaround.

**Comment by bvaughn** [comment]
```js
console.disableYellowBox = true;
```

I would not advise this because it suppresses all warnings- not just the false positive you're trying to suppress.

@nicodeslandes's [suggestion from a few days ago](https://github.com/facebook/react-native/issues/18175#issuecomment-370575211) shows a safer short term workaround approach:
```js
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings([
  'Warning: componentWillMount is deprecated',
  'Warning: componentWillReceiveProps is deprecated',
]);
```

Although this, too, will suppress _actionable_ warnings (deprecations in your own components) as well as the ones for the built-in components.

**Comment by putrantoinc** [comment]
anybody's seeing this issue as well with react-native version 0.55.3?

**Comment by gaearon** [comment]
Note that `isMounted is deprecated` false positive is being discussed in https://github.com/facebook/react-native/issues/18868.
(It's unrelated to this thread.)

**Comment by ryan2clw** [comment]
I’m on version 0.54.1.  No warnings here.  How often should I be updating React?  Is it bad practice to keep the same version while the software is in development?

**Comment by Comi9** [comment]
`react-native 0.55.4` is still **not** fixed.

**Comment by syrakozz** [comment]
is it fixed on react-native 0.56 ?

**Comment by jslz** [comment]
I am seeing this, but it is an "error" not just a "warning" so my build fails. Lo, I am confused.

```
/Users/x/Dev/a/b/c/src/components/button/d/D.js
  56:16  error  componentWillReceiveProps is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops  react/no-deprecated
```

**Comment by skptricks** [comment]
Check out solution for this issue : https://www.skptricks.com/2018/10/warning-componentwillmount-is-deprecated-in-react-native.html
