### ISSUE TITLE
XHR fails with "Invalid response for blob" always when response status 204( no-content )

### ISSUE THREAD

**Issue by mastersam92** [facebook/react-native#18190]
When I try fetch some backend's api, then response, in case of success, has contentType application/json and http status 204 (no content), my api call fails with error: "Invalid response for blob:"
If response have some content, fetch works perfectly;

Update: 
RN default fetch( whatwg-fetch ) request **fails always when response status 204( no content )**, regardless of content-type, request method( tested on GET / POST ).. and, even if response has some data in body, but have status 204 - fetch fails with error "Invalid response for blob:".

### Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0 => 16.2.0
  react-native: ^0.54.0 => 0.54.0
  whatwg-fetch: ^1.0.0 => 1.1.1

### Expected Behavior

Works normally. Without some errors in fetch only because response has status 204( no content );

### Actual Behavior

Fails with error: "Invalid response for blob:"

### Steps to Reproduce

1. Fetch( with default RN fetch ) some backend's API, that response with contentType application/json and http status 204 (no content), i.e response contains only header.

2. Enjoy fails with.. description about.. blob !?

**Comment by andrew-wagner89** [comment]
I encountered the same issue when I tried to upgrade from 0.53.0 to 0.54.0, so for now I'm just going to stay on 53 until this is resolved

**Comment by leogeng** [comment]
Get the same issue

**Comment by balsloev** [comment]
Same issue here. 
<img width="314" alt="skaermbillede 2018-03-09 kl 10 08 46" src="https://user-images.githubusercontent.com/6825080/37199435-e814321a-2381-11e8-9900-f9203af602d1.png">

**Comment by Azkv** [comment]
+1

**Comment by dbarros** [comment]
I'm also seeing the same error on 0.54. Works fine in 0.53.3.

**Comment by Azkv** [comment]
0.53
```
case 'blob':
        this._cachedResponse = new global.Blob(
          [base64.toByteArray(this._response).buffer],
          {type: this.getResponseHeader('content-type') || ''}
        );
        break;
```

0.54 XMLHttpRequest blob case
```
case 'blob':
        if (typeof this._response === 'object' && this._response) {
          this._cachedResponse = BlobManager.createFromOptions(this._response);
        } else {
          throw new Error(`Invalid response for blob: ${this._response}`);
        }
        break;
```

**Comment by obsidianart** [comment]
Same here, but only on Android. Iphone seems to work, which makes no sense.

**Comment by dhorrock** [comment]
Any updates or work arounds for this?

**Comment by johnckendall** [comment]
+1, Same problem doing a fetch with method HEAD

**Comment by gnumarcelo** [comment]
Got the same error on iOS simulator.

**Comment by satya164** [comment]
Does anyone have a repro case that I can test?

**Comment by johnckendall** [comment]
easy to replicate:

`fetch('https://twitter.com/johnckendall',{method:'HEAD'})`

**Comment by satya164** [comment]
I could repro this with a simple server. It would be great if someone has a repro which I can use to fix the issue.

**Comment by skv-headless** [comment]
reproducible in fresh app https://github.com/skv-headless/TestFetch based on @johnckendall answer

**Comment by David-vz** [comment]
We've got the same issue on our end.
Empty response from a server call (even if status = ok and status code is 200) returns the above error.
Diving in to XMLHttpRequest.js and making the following changes seems to be working for now:
`case 'blob':
          if(typeof this._response==='string'){
              this._cachedResponse = null;
              break;
          } else if (typeof this._response === 'object' && this._response) {
          this._cachedResponse = BlobManager.createFromOptions(this._response);
        } else {
          throw new Error(`Invalid response for blob: ${this._response}`);
        }
        break;`

Obviously not ideal...
It seems to be expecting and forcing an object for the return...
running console.log(typeof this._response) will output 'string' when the content is empty and cause the error to fire.

**Comment by satya164** [comment]
This issue seems iOS only? Please always mention the platform when opening an issue. This is a duplicate of https://github.com/facebook/react-native/issues/18223 and should be fixed in master. We'll cherry pick it to release version soon.

**Comment by brenohq** [comment]
same issue here

**Comment by simplepanda** [comment]
Same issue on 0.54.

0.54 and 0.55 have both been issues for us on; the instability / lack of code review that seem to be occurring in the PR's is a little troubling.

**Comment by hmenzagh** [comment]
@satya164 No I'm getting it on Android only for my part

**Comment by sadhu05** [comment]
Same issue here

**Comment by hmenzagh** [comment]
@sadhu05 see #18440

**Comment by luhui** [comment]
Same issue on android, `0.55.4`. Always happened if the url contains '-', and protocol is https.

e.x. POST 'https://apis-test.somedomain.com'

**Comment by jgreen01** [comment]
This issue is happening in `0.55.4`.

![screenshot_1529533615](https://user-images.githubusercontent.com/25392304/41688000-081fcc72-749f-11e8-823e-bb2883d5f5b4.png)
```      case 'blob':
        if (typeof this._response === 'object' && this._response) {
          this._cachedResponse = BlobManager.createFromOptions(this._response);
        } else {
          throw new Error(`Invalid response for blob: ${this._response}`); // line 257
        }
        break;
```

**Comment by satya164** [comment]
Duplicate of #18440

**Comment by obsidianart** [comment]
18440 is Android, this is IOs. 18440 is not about 204 or empty responde either. I don't think they are duplicates @satya164 even if they might have the same root cause.

**Comment by satya164** [comment]
@obsidianart this was already fixed on iOS. most comments here reference Android.

**Comment by stueynet** [comment]
@satya164 lets keep the focus on this one as its still open and Android is in the title: https://github.com/facebook/react-native/issues/18440

**Comment by bonham000** [comment]
Same issue here with Expo 29 (React Native 0.55.4). The app is running normally in the development and if I preview a build in the Expo app but if I open an `.apk` build on Android it fails on startup with `invalid response for blob` if I am on wifi, and just a blank screen (no feedback) if on cellular data.

**Comment by wzup** [comment]
@satya164 
> _this was already fixed on iOS._ 

You are wrong. This IS NOT fixed on iOS! I'm on iOS, see my env below and I get same error.

![screen shot 2018-09-27 at 9 46 10 am](https://user-images.githubusercontent.com/3880497/46135871-e9c46500-c24e-11e8-82ea-ddc9a369dbd5.png)

Env:

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.0-alpha.2 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2
```
