### ISSUE TITLE
Controlled TextInput broken for Chinese (and other languages) in v0.54 on iOS

### ISSUE THREAD

**Issue by danielsuo** [facebook/react-native#18403]
Controlled ```TextInput``` breaks the Chinese pinyin keyboard's autocomplete feature. A similar issue was raised a year and a half ago (#8265) and fixed by #7496. However, it appears that others are having the same problem (#12599, #18260, #18379), but re-filing the issue with the template filled out and an example to reproduce.

Note that this works correctly in v0.53. This may have something to do with the big ```Text```, ```TextInput``` refactor that dropped with v0.54 (Thanks, btw, @shergin and @hovox!).

I've included both a working (v0.53) and broken (v0.54) example below.

### Environment

Environment:
  OS: macOS High Sierra 10.13
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

Typing on a US keyboard would bring up Chinese characters corresponding to letters typed.

### Actual Behavior

Each new letter typed is considered individually, instead of along with the previous untranslated characters.

Shamelessly stealing an image from @ForU who did a nice job of showing the issue:

![image](https://user-images.githubusercontent.com/1693614/37463182-60980ba0-288f-11e8-82f2-281cd722f342.gif)

### Steps to Reproduce

Unfortunately, expo hasn't updated to the latest version of React Native. I've prepared a small project that demonstrates the issue [here](https://github.com/danielsuo/react-native-pinyin-bug). There is a working version on a branch [here](https://github.com/danielsuo/react-native-pinyin-bug/tree/v0.53); same project, just using RN v0.53 instead of v0.54.

**Comment by hramos** [comment]
Great bug report! Thanks for organizing all of the reports.

**Comment by magicien** [comment]
@danielsuo I created a PR #18456 to fix this issue.
I made sure that it works for Japanese, but I'm not sure about Chinese.
I forked your test app and applied this change.
Can you (or anyone who can speak Chinese) try [this app](https://github.com/magicien/react-native-pinyin-bug) to check if it's fixed?

**Comment by BooYeu** [comment]
if it has prop value or defaultvalue,you can't input Chinese

**Comment by magicien** [comment]
Thank you @BooYeu! It might need to include #18278.
Let me update the PR.

**Comment by magicien** [comment]
I updated [the pull request](https://github.com/facebook/react-native/pull/18456) and [the sample app](https://github.com/magicien/react-native-pinyin-bug).
And I tried one of Chinese keyboards. I hope it's expected behavior.
![screenshot](https://user-images.githubusercontent.com/1047810/37642754-b51faa54-2c61-11e8-8627-e3887cdde47f.gif)

**Comment by BooYeu** [comment]
I changed and tried again , but it doesn't work . Do you have the prop "defaultValue" like defaultValue=this.props.value ? I found it ok that using defaultValue="test"

**Comment by magicien** [comment]
I tried 2 cases, and both of them seemed working.
```
<TextInput
  placeholder="Type here!"
  onChangeText={text => {
    this.setState({ text: text });
  }}
>
  <Text>{this.state.text}</Text>
</TextInput>
```

```
<TextInput
  placeholder="Type here!"
  onChangeText={text => {
    this.setState({ text: text });
  }}
  value={this.state.text}
/>
```

**Comment by BooYeu** [comment]
Oh My fault . I appreciate your help !!! Thanks !!

**Comment by magicien** [comment]
All right. Thank you!

**Comment by danielsuo** [comment]
Works for me! Appreciate the quick fix!

**Comment by magicien** [comment]
Thank you @danielsuo!
I'm going to update the test plan of the pull request.

**Comment by Rob117** [comment]
This wasn't merged into 0.54.4 right?
Is this in 0.55.0?

**Comment by mkjfeng01** [comment]
0.55.0 has this problem

**Comment by TFsky** [comment]
@mkjfeng01   git+https://github.com/CHANOMA/react-native.git#0.54-stable-flow-0.66 ,  Works for me!     This wasn't merged into 0.55.0 ( https://github.com/facebook/react-native/pull/18456/files)

**Comment by mkjfeng01** [comment]
Are you sure this issue has be solved? Case I still could not input Chinese, react-native version from 0.54.0 to 0.55.2 !
 ![](https://ws2.sinaimg.cn/large/006tNc79gy1fq7lskcw3bg30ml0a37wh.gif)

**Comment by mkjfeng01** [comment]
@magicien It looks like problem appear when defaultValue/value and onChangeText been used  at the same time and point to same props.

**Comment by magicien** [comment]
I think it will be fixed by this PR, but this PR has not been merged yet.

**Comment by danielsuo** [comment]
I can confirm that this PR resolves my problem and I’m using it in
production.

**Comment by mkjfeng01** [comment]
I checked my code again this morning and found that the Chinese input method can be entered. The problem has been solved. Thank you very much for your reply. @magicien  @danielsuo

**Comment by musicode** [comment]
how to resolve it?

**Comment by tsangwailam** [comment]
Currently, i use 2 state properties to solve the problem.

```
state= {
text:"",
text2:"",
}
<TextInput
 value={this.state.text}
  onChangeText={text => {
    this.setState({ text2: text });
  }}
 onBlur={e=>setState({text:this.state.text2})}
/>
```

**Comment by mkjfeng01** [comment]
Here 👉 https://github.com/facebook/react-native/issues/18767

**Comment by mpyw** [comment]
@tsangwailam  Better solution is introduced here

[react native0.54.2以降でTextInputでonChangeTextを使うと日本語変換ができなくなる的なお話 ~ 適当な感じでプログラミングとか！](http://watanabeyu.blogspot.jp/2018/04/react-native0542textinputonchangetext.html)

**Comment by johnxie** [comment]
Any updates on this issue?

**Comment by mpyw** [comment]
Currently the following comment provides the best solution

https://github.com/facebook/react-native/pull/18456#issuecomment-392472616

**Comment by ben5276** [comment]
Has this been fixed in 0.56?

**Comment by vovkasm** [comment]
@ben5276  I will test it shortly... but probably not, because I tracked commits to master, and did not see anything that looks like fix for TextInput :-/

**Comment by vovkasm** [comment]
I checked it, at first glance Japanese input seems to work. But I using it rarely, so can't be totally sure.
My test code is here: https://github.com/vovkasm/react-native-textinput-bug/tree/rn-0.56 (it is for another bug, so try to filter input, but until filtering broken, one can test anything :-)

**Comment by dogecrypto** [comment]
Not solved yet? Temporally hack code maybe not good to tackle on...

**Comment by kevinkevw** [comment]
I was facing the same issue.
After different tests. It seems to be fine if TextInput with onChangeText but not setting the value.

`<TextInput onChangeText={ text => this.setState({ inputText: text }) } />`

And _this.state.inputText_ returns exactly the same as what I can see from the screen.
Any potential problems if using TextInput without setting the _value_ props?

**Comment by vovkasm** [comment]
@kevinkevw, but most of times you need to set `value`. Without a value, how you would implement "reset" functionality, or set initial value?
And exactly without a value, you simple do not trigger this bug, as your `TextUnput` now effectively uncontrolled.

**Comment by kevinkevw** [comment]
@vovkasm Ah yes you're right. I got your point. But the bug itself still not yet been fixed.

Leaving it uncontrolled seems working fine in my case, I set the initial value by `defaultValue` props and I don't really have to reset the TextInput, maybe forcing a re-render? : /

**Comment by kk412027247** [comment]
@ tsangwailam 唔该晒！！

**Comment by kk412027247** [comment]
@tsangwailam In order to be compatible with android, I change some code.
The following code work well for me.

```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, TextInput} from 'react-native';


export default class App extends Component {

  state= {
    text:"", // hold the final text
    text2:"", // temporary store the input text
  };

  handleInput = (text) =>  this.setState({ text2: text });
  handleDisplay = (text) =>  this.setState({text:text});

  render() {
    return (
      <View style={styles.container}>
        <TextInput
          value={this.state.text}
          placeholder={'type here'}
          onChangeText={Platform.OS ==='ios' ? this.handleInput : this.handleDisplay}
          onBlur={ Platform.OS ==='ios' ? this.handleDisplay.bind(null,this.state.text2) : null}
        />
        <Text style={styles.text}>{this.state.text}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  input:{
    width:'100%'
  },
  text: {
    textAlign: 'center',
    margin: 20,
    color:'#999'
  },
});

```

**Comment by mmmulani** [comment]
I just landed a fix for this on iOS. Please try it out and let me know if it doesn't work for this problem.

**Comment by Taphood** [comment]
Which official release is going to have this bug fix?

**Comment by krizpoon** [comment]
Based on @tsangwailam 's solution, I came up with the following component. It works as a drop-in replacement (almost, except for the ref prop). It would work with external changes to the text value too.

```
import React, { PureComponent } from 'react';
import { TextInput, Platform } from 'react-native';
import ReactNativeVersion from 'react-native/Libraries/Core/ReactNativeVersion';

export function fixComposeInput(Component) {
    return class MyTextInput extends PureComponent {
        state = { diffKey: 0, value: '', display: '' };

        static getDerivedStateFromProps(props, state) {

            if (!state || !state.props || props.value !== state.props.value) {

                const value = props.value || '';
                const display = state && state.display || '';
                if (value !== display) {
                    const diffKey = ((state && state.diffKey) >>> 0) + 1;
                    return { props, value, display: value, diffKey };
                }
            }

            return { props };
        }

        handleChange = text => {
            // keep track of the display value
            this.setState({ display: text }, () => {
                const { onChangeText } = this.props;
                onChangeText && onChangeText(text);
            });
        };

        render() {
            const { refInput, value: valueProp, onChangeText, ...inputProps } = this.props;
            const { value, diffKey } = this.state;

            return <Component
                { ...inputProps }
                key={ `TextInput${diffKey}` }
                ref={ refInput }
                value={ value }
                onChangeText={ this.handleChange }
            />;
        }
    };
}

const rnVer = ReactNativeVersion.version.minor;

export default (Platform.OS === 'ios' && rnVer >= 54 && rnVer <= 56 ? fixComposeInput(TextInput) : TextInput);
```
