### ISSUE TITLE
[SectionList][inverted] SectionList headers are sticky-at-the-top-footers if the list is inverted

### ISSUE THREAD

**Issue by terrysahaidak** [facebook/react-native#18945]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.6.0
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce

Clone [this repository](https://github.com/terrysahaidak/ReactNative-SeactionList-Bug-Example) and run it via `react-native run-ios`.
Observe the section separators are in wrong (randomly?) places.

## Expected Behavior

The section list headers should be in the top of the section instead of the bottom like section footers do with an inverted list (but they aren't sticky).

#### Expected gif:
![kapture 2018-04-19 at 13 46 22](https://user-images.githubusercontent.com/7809008/38987367-1b25ac26-43d8-11e8-854b-05c4b1b64242.gif)

## Actual Behavior

The section headers are footers instead of headers. They are sticky because of https://github.com/facebook/react-native/pull/17762 but still footers, not headers.

Sample code:
```jsx
export default class App extends React.Component {
  render() {
    return (
      <View style={s.container}>
        <SectionList
          inverted
          sections={mock.sections}
          maxToRenderPerBatch={10}
          initialNumToRender={10}
          style={{ flex: 1 }}
          keyExtractor={(item) => item.messageId}
          renderSectionHeader={sectionProps => (
            <SectionHeader
              {...sectionProps}
            />
          )}
          renderItem={({ item }) => (
            <ListItem
              item={item}
            />
          )}
          ItemSeparatorComponent={ItemSeparator}
        />
        />
      </View>
    );
  }
}
```

#### Problem Gif:
![kapture 2018-04-19 at 13 43 42](https://user-images.githubusercontent.com/7809008/38987253-c12987e2-43d7-11e8-8baa-40d48e5743f6.gif)

**Comment by almorak** [comment]
try:
set sectionlist  stickySectionHeadersEnabled={false}  
use renderSectionFooter instead of renderSectionHeader with inverted case

**Comment by terrysahaidak** [comment]
@almorak thanks for your advice, but it won't fix the bug at all.
Sticky headers are common behavior for chat date headers, I still need them.

Also, see my second issues:
https://github.com/facebook/react-native/issues/18943

**Comment by terrysahaidak** [comment]
Hi @janicduplessis, you have worked on [support of inverted sticky headers](https://github.com/facebook/react-native/pull/17762), but there are some issues, could you please look at them?

**Comment by terrysahaidak** [comment]
@iamolegga I just don't use section list with sticky headers currently. Just simply FlatList with custom functions for creating sections and then render it.

**Comment by brunoro** [comment]
Also struggling with this here, I'm implementing infinite scroll to the top and need sticky headers (or inverted footers, apparently). Any solutions so far?

**Comment by die20** [comment]
I've been able to use this as a workaround: 

```
<SectionList>
renderSectionFooter={<View style={{transform: [{ scaleY: -1 }]}}>...</View>}
renderItem={<View style={{transform: [{ scaleY: -1 }]}}>...</View>}
inverted={true}
</SectionList>
```

**Comment by terrysahaidak** [comment]
Could you please provide an example with that fix applied to my repro?

Here is what I've got:

![image](https://user-images.githubusercontent.com/7809008/61306195-d5108800-a7f4-11e9-948c-30881b17d0fd.png)

**Comment by terrysahaidak** [comment]
This hasn't been fixed yet.

**Comment by stepupithubapp** [comment]
just simple use renderSectionFooter then header and make inverted true simple

**Comment by je7ov** [comment]
I'm having the same issue with inverted sticky headers.

> just simple use renderSectionFooter then header and make inverted true simple

This doesn't address the issue. We're looking to have sticky section headers on inverted lists

**Comment by ydv0121** [comment]
+1

**Comment by djhr** [comment]
**`opened this issue on 19 Apr 2018`**

**Comment by irfaan** [comment]
Not able to find a good solution here. What we really need is the ability to make sticky footers a possibility. Then, when a list is inverted, you can switch stickyFooters on to keep it sticky at the top and start above the content of the section.

**Comment by terrysahaidak** [comment]
I just checked this issue on 0.62 and seems like it's still there.

**Comment by deniscreamer** [comment]
Please provide us a new param **stickySectionFooterEnabled**

**Comment by franciscosolla** [comment]
If someone is still stuck on it, Medium has posted a workaround:
https://medium.com/@smali.kazmi/react-native-sticky-date-like-whatsapp-using-inverted-sectionlist-c141f5933d55

in which I've made some changes to make it desappear when not needed anymore:
just setting it to null when lastItem is the sectionHeader (sectionFooter)

`function updateCurrentDate({ viewableItems, changed }: { viewableItems: Array<ViewToken>; changed: Array<ViewToken> }) {
        if (viewableItems && viewableItems.length) {
            const lastItem = viewableItems.pop()
            if (lastItem && lastItem.item.title && lastItem.item.title === currentDate) setCurrentDate(null) 
            else if (lastItem && lastItem.section) setCurrentDate(lastItem.section.title)
            else setCurrentDate(null)
        }
        else setCurrentDate(null)
    }`

also, changed the style of the date header to be absolute, so it appears over the list.

**Comment by terrysahaidak** [comment]
Still an issue.

**Comment by vibinjoby** [comment]
> If someone is still stuck on it, Medium has posted a workaround:
> https://medium.com/@smali.kazmi/react-native-sticky-date-like-whatsapp-using-inverted-sectionlist-c141f5933d55
> 
> in which I've made some changes to make it desappear when not needed anymore:
> just setting it to null when lastItem is the sectionHeader (sectionFooter)
> 
> ```js
> function updateCurrentDate({ viewableItems, changed }: { viewableItems: Array<ViewToken>; changed: Array<ViewToken> }) {
>         if (viewableItems && viewableItems.length) {
>             const lastItem = viewableItems.pop()
>             if (lastItem && lastItem.item.title && lastItem.item.title === currentDate) setCurrentDate(null) 
>             else if (lastItem && lastItem.section) setCurrentDate(lastItem.section.title)
>             else setCurrentDate(null)
>         }
>         else setCurrentDate(null)
>     }
> ```
> 
> also, changed the style of the date header to be absolute, so it appears over the list.

yo man, this is the solution I was looking for, you're a lifesaver.
Thanks, buddy 👍🏻

**Comment by SrBrahma** [comment]
It is a shame that is hasn't been officially fixed yet.

There should be a new "inverted" prop to make the life of us who make "chat-like" components better. Inverted just sucks.

**Comment by fangpenlin** [comment]
Hey folks 👋

This issue troubled me as I also need the sticky header to work for inverted section list for the app I am building. To solve the problem, I create an `InvertedSectionList` component for fixing this issue outside of RN code base. I open sourced it here

https://github.com/LaunchPlatform/inverted-section-list

For now I only built it to make it works for my app, didn't test it with other corner cases. My `InvertedSectionList` component is basically copying source code from RN repo and made critical changes only to make the sticky header (footer actually) works. So in theory, if I port the changes back to RN, it should fix this. I am trying my best to see if I can find time to create PRs to fix this issue. However, if you want, please feel free to port the changes I made and open PRs to RN's repo. In the mean time hopefully the component I made can solve your problem as well before it's fixed in the upstream.

**Comment by sergeymild** [comment]
Still an issue on stock installs

**Comment by SrBrahma** [comment]
Up

**Comment by adidoes** [comment]
I can't believe this is still an issue after so many years and how common of a design it is in today's apps.

**Comment by jailsonpaca** [comment]
up

**Comment by mtnt** [comment]
still an issue...
"After all this time? - Always" =)

**Comment by iamolegga** [comment]
![image](https://github.com/facebook/react-native/assets/5501657/58f72c6a-dafe-410d-8158-a75f080b4227)

**Comment by Ilyxxxaa** [comment]
Please repair it

**Comment by timothyerwin** [comment]
how is this still an issue? is it bc all resources are on the metaverse?

**Comment by ayushneekhar** [comment]
Is it that hard to implement stickySectionFooterEnabled?

**Comment by SimpleCreations** [comment]
Still an issue

**Comment by VadymVashchuk** [comment]
After 6 years still an issue

**Comment by adsalihac** [comment]
😀

**Comment by eljonathas** [comment]
24/04/2024 and still an issue

**Comment by MrQazi665** [comment]
Hello,

I'm interested in making the 'renderSectionFooter' sticky. Is this possible? 

<img width="584" alt="image" src="https://github.com/facebook/react-native/assets/107867869/9527de7e-a0b7-48c5-a1b0-608c5817989c">

**Comment by HuziMuzi** [comment]
28/08/2024 still an issue

**Comment by fangpenlin** [comment]
Hey guys, after years, I was working on upgrading RN version of my app and realized this issue is still here 😅

So I tried my best to open a PR for addressing this bug:

https://github.com/facebook/react-native/pull/47130

It appears to be working as I tested, but I am not sure if there's any corner cases I missed. I may also need to find a time to test other platforms, such as iOS. I know this bug troubles us for a very long time, so it would be great if you guys can help me test my PR see if it's working as expected.

I have never create a new PR with a major change like this in react-native repo, so I may also need some help. If you know what's missing in my PR, and how to get my PR merged, please let me know. Thank you so much 🙏

**Comment by migueldaipre** [comment]
> Hey guys, after years, I was working on upgrading RN version of my app and realized this issue is still here 😅
> 
> So I tried my best to open a PR for addressing this bug:
> 
> #47130
> 
> It appears to be working as I tested, but I am not sure if there's any corner cases I missed. I may also need to find a time to test other platforms, such as iOS. I know this bug troubles us for a very long time, so it would be great if you guys can help me test my PR see if it's working as expected.
> 
> I have never create a new PR with a major change like this in react-native repo, so I may also need some help. If you know what's missing in my PR, and how to get my PR merged, please let me know. Thank you so much 🙏

Hey @fangpenlin, is [this](https://github.com/facebook/react-native/pull/47130) ready or still in progress?

**Comment by fangpenlin** [comment]
@migueldaipre yep, it's ready for review

**Comment by migueldaipre** [comment]
@fangpenlin thanks 👍

also cc @cortinico @cipolleschi

**Comment by cortinico** [comment]
I've pinged a couple of folks internally to look into this 👍

**Comment by Vinay-Gurjar** [comment]
**_Problem_**: **renderSectionHeader** is appearing after messages instead of before them
This problem occurs because SectionList is inverted (inverted={true}), which reverses the rendering order of both:
So use **renderSectionFooter** instead of actually **renderSectionHeader** which moves the footer upwards

`

```
  <SectionList
                sections={messageSections}
                keyExtractor={(item) => item._id}
                inverted 
                renderSectionFooter={({ section: { title } }) => (
                    <View key={title} style={{ alignItems: "center", marginVertical: 10, padding:5}}>
                        <View style={{backgroundColor: Colors.subThemeColor, padding: 8, borderRadius: 25}}>
                        <CustomText style={{ fontSize: 13,fontWeight: "bold", color: "#555"}}>{title}</CustomText>
                        </View>
                    </View>
                )}
                renderItem={({ item, index }) => renderMessageBubble(item, index)}
                onEndReached={onLoadMore}
                onEndReachedThreshold={0.8}
                ListFooterComponent={loading ? <ActivityIndicator size="small" /> : null}
            />`
```

**Comment by fangpenlin** [comment]
Hey @Vinay-Gurjar thanks for reviewing it. I will find a time looking into this issue and address it.

**Comment by SimpleCreations** [comment]
Still an issue

**Comment by SimpleCreations** [comment]
Not stale

**Comment by SimpleCreations** [comment]
Not stale
