### ISSUE TITLE
Cookies set in a redirect response are not persisted

### ISSUE THREAD

**Issue by michaeleisel** [facebook/react-native#19376]
When I go to a site that returns a 303 along with a Set-Cookie header, it does not use the new cookie from that redirect when it goes to the new URL. This would be somewhat manageable if I could use `redirect: 'manual'` in `fetch`'s request options and inspect the redirect myself, but that is also broken.

- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 10.0.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.2 => 0.55.2

## Steps to Reproduce
Go to a site that redirects with a 303 response and sets a cookie via Set-Cookie.

## Expected Behavior
Cookie that it sets is sent up when the redirect continues with whatever URL the 303 sent you to.

## Actual Behavior
Cookie is not sent up

**Comment by michaeleisel** [comment]
When I try this using an `NSURLSession` in Objective-C, the cookie is set as expected, so react native is behaves differently from native.

**Comment by michaeleisel** [comment]
From my testing, android doesn't have the same problem, so I guess it's an iOS thing

**Comment by km16** [comment]
It just stopped cookies for me from 0.56. Was working fine till 0.55. I am facing the issue in a normal fetch request.

**Comment by michaeleisel** [comment]
@kelset why add a “no repro steps” label? There are repro steps in the ticket

**Comment by km16** [comment]
Even I am facing this on android. It works perfectly till 0.55.4. I just feel https://github.com/facebook/react-native/pull/19770 might fix this, when it get's merged.

**Comment by Jacse** [comment]
Please see #16127

**Comment by gtebbutt** [comment]
@Jacse Would that explain a difference between 0.55 and 0.56? I thought that PR was referencing an issue from much further back than that. 

I'm seeing what appears to be a related issue on iOS: since updating from 0.55 to 0.57, the `react-native-video` package is no longer passing cookies to the CDN. 

Perhaps worth noting that the recent chat on #19958 also suggests an explicit behaviour change after 0.55, since several users there are apparently needing to explicitly add `credentials: 'include'` where it wasn't needed before.

**Comment by GetSource1234** [comment]
I am also seeing this issue in rn 0.57 (ios 12.0).`credentials: 'include'` helps, but this flag does not help if you reopen the app. Cookie will be deleted after app relaunch.

**Comment by BKova** [comment]
> I am also seeing this issue in rn 0.57 (ios 12.0).`credentials: 'include'` helps, but this flag does not help if you reopen the app. Cookie will be deleted after app relaunch(could be only my case).

Can confirm this works on Android in RN 0.57

**Comment by corradio** [comment]
I'm having exactly the same issue. Only happens on iOS, so I dug into the the iOS code.
It turns out this commit caused the issue: https://github.com/facebook/react-native/commit/047961fbf77cb012b53978184102e8ca3d00c7ec#diff-0b161cb06747782c515275d84ec94b14R234
In a nutshell, the HTTPShouldHandleCookies boolean has no effect when custom cookies are set (see https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1415485-httpshouldhandlecookies?preferredLanguage=occ). Setting custom cookies prevents the cookies of a redirect response from being re-used in the subsequent request.

I've fixed it by patching the RCTHTTPRequestHandler.mm by adding the following code block:

```objc
- (void)URLSession:(NSURLSession *)session
              task:(NSURLSessionTask *)task
willPerformHTTPRedirection:(NSHTTPURLResponse *)response
        newRequest:(NSURLRequest *)request
 completionHandler:(void (^)(NSURLRequest *))completionHandler
{
  // Add the cookies to the new request
  // This is necessary because we're not letting iOS handle cookies by itself
  NSMutableURLRequest *nextRequest = [request mutableCopy];
  
  NSArray<NSHTTPCookie *> *cookies = [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookiesForURL:request.URL];
  nextRequest.allHTTPHeaderFields = [NSHTTPCookie requestHeaderFieldsWithCookies:cookies];
  completionHandler(nextRequest);
}
```

Is this a bug in RN that should be fixed? Happy to do a PR with this change if needed.

Ref https://github.com/facebook/react-native/issues/14869 and https://github.com/facebook/react-native/issues/15918 https://github.com/facebook/react-native/pull/16127 cc @jamesreggio

**Comment by Jacse** [comment]
@corradio I would love to see that as a PR. If the goal is to have the two platforms behave similarly then this would clearly need to be fixed, since cookies persist across redirects on Android.

**Comment by corradio** [comment]
PR submitted: https://github.com/facebook/react-native/pull/22178

**Comment by Meshz** [comment]
I am trying to authenticate through NTLM in RN. Here's the normal flow: `Req with NTLM Type1Msg` > `Res 401 with WWW-Authenticate` > `Req with NTLM Type3Msg` > `Res 302 with Set-Cookie` > `Res 200`.

Everything is working on iOS 9.3 but it is broken on iOS 10.0 and above. Could this be related to cookie management? Any hint would be much appreciated!

**Comment by roots-ai** [comment]
@corradio Adding this code, still doesn't resolve the issue for me.
