### ISSUE TITLE
App crashes with abort message "availableHeight is indefinite so heightMeasureMode must be YGMeasureModeUndefined" when user resumes app from background.

### ISSUE THREAD

**Issue by herlarb** [facebook/react-native#19719]
## Environment
OS: Windows 10
Node: 8.9.4
Yarn: 1.5.1
npm: 5.6.0
Watchman: Not Found
XCode: N/A
Android Studio: Version 2.3.0 AI-162.4069837

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.1 => 0.55.1

## Description
The app crashes when the user attempts to resume an app  from the background on android 
Crash log : https://gist.github.com/herlarb/7a8820dbfc56d3dffd35ba235b8e888a

## Steps to Reproduce
1. Launch any given app built using the environment provided
2.  Using the android back button send app to background
3. Relaunch the app from background using  the opened apps tray or by tapping on the app icon
4. Observe

## Expected Behavior
App should not crash when the user attempts to resume app from background

## Actual Behavior
The app crashes unexpectedly when the user resumes the app from the background

**Comment by hramos** [comment]
Looks like your report is for an old version (0.55.1). Your repro steps are not specific enough and require a lot of effort for a contributor. In general, you want to file an issue that is complete and ready to be picked up by someone who is interested in providing a fix (see https://stackoverflow.com/help/mcve).

Closing as debugging individual crashes is out of scope for this issue tracker unless a minimum repro is provided.

**Comment by herlarb** [comment]
@hramos Seems the react native contributors are quick to close  issues. You can't 0.55 is old when 0.56 has just been released (Documentation has not even been updated to 0.56). This issue has been recurring in react native as #9550 and #16727 all for which have been shelved aside like this. It gives an impression that  contributors don't want to look through the code or  don't have a fix for the issue

The Abort message raised during the crash lies in react-native/ReactCommon/yoga/yoga/Yoga.cpp lines
 2556 -2560(react native 0.56 ) appears like a yoga issue

**Comment by hramos** [comment]
The latest stable version is 0.55.4, and is already two months old. We encourage everyone to use the release candidate versions whenever possible, _especially_ when filing bug reports. With over 600 issues currently open, we have to prioritize, so you're right, I don't want to look at an issue that has not been tested in the release that I'm curating at this moment.

**Comment by herlarb** [comment]
@hramos So what if I'm able to reproduce the issue on 0.55.4. Would you be willing to look at it

**Comment by hramos** [comment]
Your issue would not be auto-closed if it's reported against 0.55.4, but like I said above, the train is moving fast and we're focusing on getting the 0.56.0 release candidate ready for release. Issues that can be reproduced on `0.56.0-rc.1` are our highest priority at the moment.

**Comment by DavidNorena** [comment]
Its happening with 0.56.0

**Comment by ivanzotov** [comment]
Reopen the issue, please. It's happening with 0.56

**Comment by CoderHuzaifa** [comment]
Happening in 0.55.4.
availableHeight is indefinite so heightMeasureMode must be YGMeasureModeUndefined

**Comment by herlarb** [comment]
I raised this issue  and @hramos  replied that it was an individual crash case. It appears it isn't an individual crash case obviously. As I'm  not a collaborator I can't reopen this issue. Hopefully @hramos  gets this mention and reopens the ticket.

**Comment by hramos** [comment]
Happy to re-open, but it looks like the original report still mentions 0.55.4. If I re-open it in the current state, it will be closed automatically. It is for this reason that we ask people to edit their issues to mention the most up to date release they've verified this on, or to submit a new issue (if you are not the author of the closed issue).

**Comment by pramodsharma403** [comment]
### Quick fix:- MainActivity.java
`@Override
    public void invokeDefaultOnBackPressed() {
        moveTaskToBack(true);
    }
`

**Comment by kjs104901** [comment]
@pramodsharma403 
Thanks. It occurs in 0.57.1 and fixed by

> ### Quick fix:- Please add below method in your MainActivity.java
> `@Override public void invokeDefaultOnBackPressed() { moveTaskToBack(true); }`

Anyone can fix react native by pull request?

**Comment by SM-Wistful** [comment]
I am still getting this issue:

`react-native 0.57.1`

I added `@Override public void invokeDefaultOnBackPressed() { moveTaskToBack(true); }` my `MainActivity.java` but it still does not work. I am getting this error when trying to start up my app, it shows up immediately and I can't even test...

**Comment by SM-Wistful** [comment]
Quick update: This was an obscure issue with another library I am using (https://github.com/APSL/react-native-keyboard-aware-scroll-view). My report here can be disregarded.

**Comment by kyledmellander** [comment]
@Sam-DevZ 

I'm on 0.57.1 and am still running into this issue. We also use React-Native-Navigation and 'react-native-keyboard-aware-scroll-view'. What was your solution?

**Comment by phantom1299** [comment]
This is still present on 0.57.8
I'm using wix navigaton and this happens when I'm in my auth app wich has a ScrollView rendered and then the user logs in and I start my normal app.

If I don't render a ScrollView it doesn't happen

**Comment by theweavrs** [comment]
Occurring in 0.59.1. I am using `react-native-navigation` as well. If there's any fix please tell.

**Comment by rickhanlonii** [comment]
Hey all, sorry to hear so many are experiencing this

Unfortunately we can't debug an issue from a single crash report and a number of +1s

If anyone can provide a way for us to reproduce this issue so that we can determine if this is a core issue or and issue with a third-party lib then I am happy to re-open and investigate

**Comment by pratham014** [comment]
This issue happens when you are specifying values for margin and padding in %. 

Remove the % values from your stylesheet  and use flex or DP values and this issue should resolve.

**Comment by tsirolnik** [comment]
I had this issue when I've rendered multiple views inside an horizontal ScrollView with the views having width and padding values as percentages, .

Something like this - 

```js
<ScrollView horizontal={true}>
    <View style={{ width: '20%', paddingLeft: '5%', paddingRight: '5%'}}>
        <View>
             .....
        </View>
    </View>
    <View style={{ width: '20%', paddingLeft: '5%', paddingRight: '5%'}}>
        <View>
             .....
        </View>
    </View>
</ScrollView>

````

Changing the styles of the views to absolute values, like @pratham104 suggested, resolved this issue.

RN 0.60.5

**Comment by mangBert** [comment]
any update on this?
