### ISSUE TITLE
[Text] has superfluous lines

### ISSUE THREAD

**Issue by yulodl** [facebook/react-native#2018]
text rendered on iphone 6 plus simulator or real device ,show superfluous lines, seems like text's border
![img_0002-compressor](https://cloud.githubusercontent.com/assets/7265437/8715649/0701631a-2bb8-11e5-8d54-935d2e8b921c.png)

**Comment by yulodl** [comment]
#947

**Comment by ssssssssssss** [comment]
This issue could be reproduced in 0.4.2 and 0.8.0-rc, and there is no clean way to workaround.

**Comment by yulodl** [comment]
@a2 @vjeux This is pretty critical for daily use. Do you also experience the same issue?

**Comment by brentvatne** [comment]
@yulodl @ssssssssssss - can you please provide a sample project on Github with this?

**Comment by yulodl** [comment]
@brentvatne https://gist.github.com/yulodl/77cdce9a57e050b56fdf 
Text with styles.bug will show the artifacts.

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by ssssssssssss** [comment]
Maybe [Text] suffers the similar issue as [Image] do?

 [Image] Resize mode contain produces glitches when dimension is float #1870

**Comment by ssssssssssss** [comment]
This issue has not  been fixed in 0.9.0-RC. Any progress here? Thank you.

**Comment by ssssssssssss** [comment]
It's not fixed in 0.10.0-rc yet.

**Comment by jawadrehman** [comment]
@brentvatne any update ?

**Comment by jawadrehman** [comment]
@brentvane @nicklockwood  @yulodl apparently it has something to do with font sizes. i had to change the font size by one or two places to get rid of the borders.try fontSize 16 with iphone 6 + 

hope this helps :)

**Comment by vjeux** [comment]
Should be fixed by this: https://github.com/facebook/react-native/commit/f5d68f6ecb0499229185120fd1fe747c1142a2b4

Can you confirm?

**Comment by jawadrehman** [comment]
@vjeux i just tried it, didnt work .

**Comment by vjeux** [comment]
@jawadrehman hmm ok :( Need to continue digging then :x

**Comment by jawadrehman** [comment]
@vjeux p.s i have tried this on 0.8 stable, not the later versions.

**Comment by ssssssssssss** [comment]
Disable the “launch screen” for the project will cause this issue.

**Comment by ssssssssssss** [comment]
@vjeux Tried latest 0.11.0-rc, doesn't work.

**Comment by brentvatne** [comment]
@ssssssssssss - can you pos tan example project? I cannot reproduce this on 0.11-rc using the gist provided above by @yulodl

**Comment by ssssssssssss** [comment]
@brentvatne Disable the “launch screen” for the project will cause this issue.

**Comment by list000001** [comment]
@brentvatne  you can init a hello world project,and  remove launch screen file,then reproduced.
![2015-09-08 1 44 37](https://cloud.githubusercontent.com/assets/3348326/9727383/05e9fd18-5631-11e5-8f7c-d22d8a000697.png)
![2015-09-08 1 44 43](https://cloud.githubusercontent.com/assets/3348326/9727384/0c67dd72-5631-11e5-88cb-2b04b55e249b.png)

**Comment by jawadrehman** [comment]
@vjeux @brentvatne i can confirm that @ssssssssssss is correct. removing the launch screen file does cause this ( i had to do this to start the app with a uiimageview - to get rid of the blank screen and make it consistent with the LaunchImage )

**Comment by brentvatne** [comment]
Thanks folks - @nicklockwood - any ideas here?

**Comment by brentvatne** [comment]
I believe this is fixed now, @jawadrehman please ping me if not and I will reopen and try to get some attention to it

**Comment by jawadrehman** [comment]
@brentvatne yeah its working, had to set the launch screen to make it work.

**Comment by jawadrehman** [comment]
(y)

**Comment by machard** [comment]
@brentvatne 
rn 0.31.0, without launch screen, the problem is still present

**Comment by blockspeiser** [comment]
I'm seeing similar artifacts on rn 0.35.0. 

They occur only on iPhone plus, on device, but not on the simulator. 

They occur on every Text component which ends up rendered with a non-integer width or height. If the inspector shows it as having half pixel value height, the Text has a border on top, half pixel width gives it a border right.

@brentvatne this is a critical bug for us - any information on how to fix or work around?

**Comment by kesjien** [comment]
Any updates on this ?

**Comment by zsajjad** [comment]
Any update on this? We are integrated in some other app that is not using launch screen and we have to get it done asap...

**Comment by stiang** [comment]
I believe @blockspeiser is correct that this is about fractional widths/heights, and I was finally able to figure out why that happens. One clue was that it worked perfectly on my iPhone 6s, but not on my colleagues’ iPhone 7 Pluses.

Our app uses a launch image asset catalog source (actually a different one for every scheme), and it turned out that we had added images just for some of the sizes - notably not for Retina HD 5.5". Also, some of the launch images we *had* added were the wrong dimensions.

The solution for us was to add [properly sized](https://developer.apple.com/ios/human-interface-guidelines/graphics/launch-screen/) launch images to the asset catalog, for every type of screen resolution.

As to *why* this happens, I can only speculate that the launch image dimensions are somehow picked up by React Native as it tries to figure out what to translate the unitless dimensions to on a physical device. And if the launch image has dimensions that don’t match the physical screen, you end up with fractional sizes.

If that is the case, and this is even possible to fix, I think a separate issue should be opened. But it would be nice if someone more deeply familiar with RN can confirm first.

(Also, just in case it can help anyone, we had deleted the LaunchScreen.xib file, but I found that setting the Launch Screen File input field to *some* value anyway, say `LaunchScreen` would affect the resolution when the launch image was disabled)

**Comment by AlanFoster** [comment]
Running into this exact issue with `0.43.3` following the same repro steps of deleting the launch screen file.

![image](https://user-images.githubusercontent.com/1271782/27331816-f785886e-55b6-11e7-8fc1-32164b32617b.png)

_Note_: I don't currently have the cycles to confirm this on the latest 0.46 rc builds

**Comment by sfm2222** [comment]
I've the same issue any suggested fix?

**Comment by estemilia** [comment]
https://stackoverflow.com/questions/46191522/how-to-add-iphonex-launch-image?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
