### ISSUE TITLE
fetch API doesn't resolve or reject

### ISSUE THREAD

**Issue by john-hu** [facebook/react-native#20405]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
      Memory: 226.52 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      Yarn: 1.2.1 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.3, 27.0.3, 28.0.1
        API Levels: 14, 15, 16, 17, 18, 19, 20, 22, 23, 25, 26, 8
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

## Description
Using the example of [networking doc](https://facebook.github.io/react-native/docs/network) to fetch movie.json from facebook server doesn't work.

I had traced the code to [dispatchEvent](https://github.com/facebook/react-native/blob/master/Libraries/Network/XMLHttpRequest.js#L579) which doesn't trigger load event. The reason is [event-target-shim@1.1.1](https://github.com/mysticatea/event-target-shim/blob/v1.1.1/dist/event-target-shim.js#L355-L358) cannot find any 'load' event listeners.

## Reproducible Demo
1. check out github repo: https://github.com/john-hu/react-native-fetch-no-resolve-reject 
2. `npm install`
3. `react-native run-android`
4. open debugger ui to see console

## Expected Result 
see the following console.log
```
before fetch
fetch sent
{
  "title": "The Basics - Networking",
  "description": "Your app fetched this from a remote endpoint!",
  "movies": [
    { "id": "1", "title": "Star Wars", "releaseYear": "1977"},
    { "id": "2", "title": "Back to the Future", "releaseYear": "1985"},
    { "id": "3", "title": "The Matrix", "releaseYear": "1999"},
    { "id": "4", "title": "Inception", "releaseYear": "2010"},
    { "id": "5", "title": "Interstellar", "releaseYear": "2014"}
  ]
}
[Array]
```

## Actual Result
```
before fetch
fetch sent
```

**Comment by john-hu** [comment]
BTW, I am trying to upgrade my another react-native project from `0.49.3` to latest version. The code works well at `0.49.3` but not good at `0.56.0`.

**Comment by Shubham-Sinha** [comment]
Happens same on my codebase. I upgraded from 0.55 to 0.56 and fetch calls aren't getting completed. However on enabling ``network inspect`` in debugger, the fetch calls are resolved/rejected normally.

**Comment by john-hu** [comment]
According to the code of event-target-shim, it should work if we use XHR.addEventListener('load', func). But it is not tested on my site.

**Comment by ggtmtmgg** [comment]
In my environment, it works in both of Android and iOS.
I used https://github.com/john-hu/react-native-fetch-no-resolve-reject.

Android logs:
<img width="1274" alt="android_logs" src="https://user-images.githubusercontent.com/4220570/43559220-22fe5b10-9648-11e8-81a6-112367063916.png">

iOS logs:
<img width="466" alt="ios_logs" src="https://user-images.githubusercontent.com/4220570/43559222-257453cc-9648-11e8-8f5f-c8978085e4b2.png">


## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 30.20 MB / 8.00 GB
      Shell: 5.3.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.2.1 - /usr/local/var/nodenv/versions/8.2.1/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/var/nodenv/versions/8.2.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 27.0.3
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 2.3 AI-162.3934792
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by ggtmtmgg** [comment]
@john-hu 
I used yarn for installing node modules, cause I didn't notice that there is already package-lock.json.

```
$ yarn list | grep event-target-shim
├─ event-target-shim@1.1.1
│  ├─ event-target-shim@^1.0.5
$ yarn list | grep -B 30 event-target-shim
├─ envinfo@5.10.0
├─ error-ex@1.3.2
│  └─ is-arrayish@^0.2.1
├─ errorhandler@1.5.0
│  ├─ accepts@~1.3.3
│  └─ escape-html@~1.0.3
├─ es-abstract@1.12.0
│  ├─ es-to-primitive@^1.1.1
│  ├─ function-bind@^1.1.1
│  ├─ has@^1.0.1
│  ├─ is-callable@^1.1.3
│  └─ is-regex@^1.0.4
├─ es-to-primitive@1.1.1
│  ├─ is-callable@^1.1.1
│  ├─ is-date-object@^1.0.1
│  └─ is-symbol@^1.0.1
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ escodegen@1.11.0
│  ├─ esprima@^3.1.3
│  ├─ esprima@3.1.3
│  ├─ estraverse@^4.2.0
│  ├─ esutils@^2.0.2
│  ├─ optionator@^0.8.1
│  ├─ source-map@~0.6.1
│  └─ source-map@0.6.1
├─ esprima@4.0.1
├─ estraverse@4.2.0
├─ esutils@2.0.2
├─ etag@1.8.1
├─ event-target-shim@1.1.1
--
├─ react-native@0.56.0
│  ├─ absolute-path@^0.0.0
│  ├─ ansi-styles@2.2.1
│  ├─ art@^0.10.0
│  ├─ base64-js@^1.1.2
│  ├─ chalk@^1.1.1
│  ├─ chalk@1.1.3
│  │  ├─ ansi-styles@^2.2.1
│  │  ├─ escape-string-regexp@^1.0.2
│  │  ├─ has-ansi@^2.0.0
│  │  ├─ strip-ansi@^3.0.0
│  │  └─ supports-color@^2.0.0
│  ├─ cliui@3.2.0
│  │  ├─ string-width@^1.0.1
│  │  ├─ string-width@1.0.2
│  │  │  ├─ code-point-at@^1.0.0
│  │  │  ├─ is-fullwidth-code-point@^1.0.0
│  │  │  └─ strip-ansi@^3.0.0
│  │  ├─ strip-ansi@^3.0.1
│  │  └─ wrap-ansi@^2.0.0
│  ├─ commander@^2.9.0
│  ├─ compression@^1.7.1
│  ├─ connect@^3.6.5
│  ├─ core-js@1.2.7
│  ├─ create-react-class@^15.6.3
│  ├─ debug@^2.2.0
│  ├─ denodeify@^1.2.1
│  ├─ envinfo@^5.7.0
│  ├─ errorhandler@^1.5.0
│  ├─ escape-string-regexp@^1.0.5
│  ├─ event-target-shim@^1.0.5
```

**Comment by john-hu** [comment]
Strange. The same issue cannot be reproduced today. I had re-installed with `npm install` today. And it works correctly....... I will close this issue since we cannot reproduce it.

**Comment by john-hu** [comment]
Reopen this issue because it comes to me when I use it with the release build.

**Comment by john-hu** [comment]
@paul-todd2  Thanks for the information. Actually, I use Android smart phone to test it. I found it happens randomly. For some unknown cases, I can reproduce it 100%....

**Comment by msafayasar** [comment]
@john-hu could you find any solution?

**Comment by john-hu** [comment]
@msafayasar 
No, I didn't.... The current status of my project is that I can get the fetch resolved at debug build and cannot resovle at release build. Will waiting for next release to check it.

**Comment by msafayasar** [comment]
@john-hu 
In your situation does it resolve maybe after 60 seconds? Or does it never resolve?

I am very obsessed with this problem. I optimized every bit of my server side code because I thought it was because of server but it wasn't. I am very close to publish my app but cannot publish in this condition. I hope someone give proper solution to this

**Comment by john-hu** [comment]
@msafayasar I never noticed that it is resolved after 60s+ or is never resolved. I just noticed that the speed doesn't make sense. The URL I use is a RSS feed which is hosted at cloudflare. The speed should be fast.

My current workaround is to use old version of react native. Old version is so stable. You should also give old version a try if you don't use any new features from 0.56.

**Comment by mikemorris** [comment]
I'm seeing this behavior since upgrading from v0.53 to v0.57, _on both iOS and Android_, where calls to `fetch` will never resolve. The requests are definitely sent and able to reach a local server, but responses seem to just be lost.

I tried pinning `event-target-shim@1.0.5`, but that didn't resolve this issue.

Maybe related to https://github.com/facebook/react-native/issues/21092 or https://github.com/facebook/react-native/issues/21094?

**Comment by john-hu** [comment]
I made a release build of my app. The issue still exists at my app's release build after migrated to 0.57.0.

**Comment by john-hu** [comment]
@msafayasar 
I got a workaround which worked at the debug and release mode. I gave up to `fetch`. I use the `XMLHttpRequest`. According to my previous finding, `event-target-shim` cannot dispatchEvent through `on`load. But it can dispatchEvent through `addEventListener`.

Today, I come back to this issue and try to find a workaround. I use the following code which resolves or rejects correctly:
```
export const fetchText = (url) => {
    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.addEventListener('readystatechange', (e) => {
            if (xhr.readyState !== 4) {
                return;
            }
            if (xhr.status === 200) {
                resolve(xhr.responseText);
            } else {
                reject(e);
            }
        });
        xhr.open('GET', url);
        xhr.send();
    });
};
```

Please give it a try.

**Comment by john-hu** [comment]
@alexisbronchart Thanks for this information. I can confirm that this issue is gone after the `@babel/plugin-proposal-class-properties` removed.

**Comment by ZhengYuTay** [comment]
Still having this problem with or without `@babel/plugin-proposal-class-properties`. Current, rn version 0.57.1. Seems to be a bug with `fetch`.

**Comment by raphaelgodro** [comment]
I have this issue as well with react-native 0.56.0.
Can you guys stop closing issue for no reason? This is a real issue!
Have this problem with or without `@babel/plugin-proposal-class-properties`

**Comment by JPeer264** [comment]
This issue is really weird. I tried to debug it, but it is really hard to find a device where it happens. The strange part: it happens just on production builds and just on some devices. I didn't find a specific pattern yet, but we had issues just on the newest OS versions. 

On previous rn versions we had the problem with iPhone 6 + X (iOS 12). Now we have this problem with Samsung Galaxy S8 (Android 8).

**Fun fact.** As I said it works on the development builds. So, as soon as we run the development builds on such devices it then suddenly works in production as well. This is the only way I found how to "fix" this kinda problem.

I will definitely try now the `XMLHttpRequest` @john-hu suggested. Also @john-hu can you maybe try to check if my "Fun fact" also applies to you?

**Comment by john-hu** [comment]
@JPeer264  Where is the **Fun fact** repo? I would like to try it. Actually, I stopped my small RN app development because of a lot of 3rd parties libs issues. I am considering to give up RN and go back to native app.

**Comment by JPeer264** [comment]
Actually I meant to try it in your own repo. My repo is unfortunately private.

Just as a note: Maybe you should give `expo` a try, which is is an immense timesaver.

**Comment by john-hu** [comment]
@JPeer264 Got you. I had similar **Fun fact**. But after I removed the `@babel/plugin-proposal-class-properties`, it is gone.

**Comment by JPeer264** [comment]
I always thought we are not using the class properties plugin. But we are using the preset `babel-preset-expo` which is using the `metro-react-native-babel-preset` under the hood. So as of [this](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js#L25) we are also using this plugin. I will try to remove this plugin somehow. Thanks for the hint.

**Comment by kelset** [comment]
Is this issue still happening in 0.59? 🤔

**Comment by Tino-F** [comment]
@kelset I'm having this issue using 0.59.1. It works fine in debug mode, but won't working when I build the release APK

**Comment by fcaride** [comment]
I had exact the same problem. The reason was that i had a space hidden in the url. In the debugger worked with that space but without the debugger no

**Comment by kelset** [comment]
Can any of you folks kindly provide a repro with the latest 0.59? (Or wait for 0.60? Should come out later this week)

**Comment by Tino-F** [comment]
I found out that my issue was the SSL. My API wasn't using SSL (which isn't allowed in production mode apparently). After I added SSL, I was able to make requests and get responses. I had to add the cert, private key, and chain file before it started working for me.

**Comment by NicolasSmit** [comment]
@Tino-F 
Can you please provide the details of your solution ?

**Comment by Tino-F** [comment]
@NicolasSmit the URL that I was "fetching" was using HTTP instead of HTTPS

so instead of

`http://example.com`

I used

`https://example.com/`

**Comment by NicolasSmit** [comment]
@Tino-F 
I got this ;) 
But how did you add the cert, private key & chain file ?

**Comment by Tino-F** [comment]
@NicolasSmit it's done on the server that you're fetching to and it depends on what kind of server you're using whether it's a Node, Apache, Nginx, etc. so the instructions will vary for each. I used let's encrypt to generate the cert, private key & chain file. 

You can check out their article on how to get started here: https://letsencrypt.org/getting-started/

**Comment by spsaucier** [comment]
@john-hu The XMLHttpRequest workaround works for me too. Unfortunately, as the babel plugin is part of `module:metro-react-native-babel-preset`, it's not particularly practical to remove it at this point. I'm very surprised more people haven't run into this issue.

**Comment by soumyamishra89** [comment]
My ios app does not resolve all fetch calls. I updated to RN 0.60.4 and the issue has worsened. @babel/plugin-proposal-class-properties is not part of babelrc file. The fetch call gets stuck and i wait for it to timeout after which it starts working again. Is there any workaround for it?

**Comment by spsaucier** [comment]
@soumyamishra89 Is it in your `yarn/package.lock` file anywhere?

**Comment by soumyamishra89** [comment]
@spsaucier yes its in my package.lock file. Does it affect because of it?

**Comment by john-hu** [comment]
It affects your project if you can find it at your package.lock or yarn.lock files.

**Comment by soumyamishra89** [comment]
metro-react-native-babel-preset requires this package. How should i remove it without affecting the packages that requires it?

**Comment by glebtv** [comment]
Just had this exact issue during react-native upgrade from 0.60.5 to 0.61.2
Running on physical device (oneplus 5t) from linux (arch).
For me, a full PC reboot resolved it (no device reboot) with react-native-debugger running.

**Comment by EmpireJones** [comment]
This issue didn't seem to relate to usage of `plugin-proposal-class-properties`, for me. I resolved this issue by clearing the cache via the packager - `react-native start -- --reset-cache` or `npm run start --reset-cache`.

I was previously only clearing the cache via `react-native run-android -- --reset-cache` and deleting node_modules folder, but there seems to be new and innovative places to hide cached files in the `$TMPDIR` folder (`$TMPDIR/react-native-packager-cache-*`, `$TMPDIR/metro-bundler-cache-*`, `$TMPDIR/haste-map-react-native-packager-*`).

**Comment by tqbdev** [comment]
I face the same problem. When the app on production, some users download from App Store and can't fetch any API. This is serious problems.

**Comment by kelset** [comment]
This issue had really low interaction in 2020, so I'm going to close and lock this. If you have the issue still, please open a new issue with a good repro with 0.62 so that it can be investigated.
