### ISSUE TITLE
[RN 0.57] JS Exception: Unexpected token '='.

### ISSUE THREAD

**Issue by freakinruben** [facebook/react-native#21074]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @types/react-native: ^0.56.4 => 0.56.18
      react: ^16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
```

## Description
I've been trying to upgrade from RN `0.55` to `0.57`. So far I got almost everything working except android:

- ts-jest ✅ 
- `react-native bundle` ✅ (`react-native bundle --platform android --dev false --entry-file index.js --bundle-output index.bundle`)
- iOS debug build ✅
- iOS release build ✅
- Android debug build ✅
- Android release build ✅
- Running iOS debug/release build ✅
- Running android debug/release build ❌ 

Error from logcat:
```
E ReactNativeJNI: Got JS Exception: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration. (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:145698)
E unknown:ReactNative: Exception in native call from JS
E unknown:ReactNative: com.facebook.react.devsupport.JSException: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration. (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:145698)
E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:789)
E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:164)
E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
E unknown:ReactNative: Caused by: com.facebook.jni.CppException: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration. (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:145698)
E unknown:ReactNative: 	... 7 more
E unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration. (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:145698)
E unknown:ReactNative:
E unknown:ReactNative: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration. (http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false:145698)
E unknown:ReactNative:
D ReactNative: CatalystInstanceImpl.destroy() start
D ReactNative: CatalystInstanceImpl.destroy() end
```

Similar error happens for release build. I've tried to look up the token on which it is tripping but there is no `=` sign at column `145698`...

Not sure how to create a reproducable demo at this point since runs fine on iOS and bundling for android also works..

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by yurykorzun** [comment]
I have a similar issue with babel parsing, but on only on windows and with react-navigation added.

**Comment by ajcrites** [comment]
This also happens to me with `react-navigation`. Not importing `createStackNavigator` at least does not cause this issue. It manifests differently for me though:

```
TypeError: comments is not iterable
    at PluginPass.Program (/path/node_modules/@babel/plugin-transform-flow-strip-types/lib/index.js:58:31)
```

**Comment by fhadsheikh** [comment]
@ajcrites I was getting the same error but switching to nvm 8.3, I get the error below now

`Cannot read property 'Symbol(Symbol.iterator)' of null`

**Comment by AlicanC** [comment]
@ajcrites see this issue for `TypeError: comments is not iterable`: https://github.com/react-navigation/react-navigation/issues/4983#issuecomment-420892313

**Comment by freakinruben** [comment]
@yurykorzun I'm using `react-native-navigation`, so not sure if this is caused by the navigation library

**Comment by elanpang** [comment]
You update RN from 0.55 to 0.57,  babel has a big upgrade from RN 0.56, our team also found some navigation issues, I think you should an issue ticket to navigation project.

**Comment by freakinruben** [comment]
I just did a shot in the wild, updating the JavascriptCore using [JSC-android-buildscripts](https://github.com/react-community/jsc-android-buildscripts) and now it runs fine on android! 

I'm suspecting that the Typescript compiled by Babel is not compatible with the current JSC, but I've no idea where to start looking.

One thing I also noticed is that the JS output by http://localhost:8081/index.delta?platform=android&dev=true&minify=false contains `\n` characters instead of actual newlines. This makes finding the location of the original error a lot more difficult

**Comment by sairus2k** [comment]
https://github.com/babel/babel/issues/8692
resolved in 7.1.0 version

**Comment by chaim1221** [comment]
I'm getting a similar issue:

```
error: bundling failed: SyntaxError: /Users/r633719/Code/healthpass/react/sundown/src/screens/public/login.tsx: Unexpected token, expected ")" (22:46)

  20 |     emailChanged: (text: string) => {},
  21 |     passwordChanged: (text: string) => {},
> 22 |     loginUser: ({ email, password, navigator }: { email: string, password: string, navigator: Navigator }) => {},
     |                                               ^
  23 |     validation: Function,
  24 |     useBiometrics: { wasAsked: boolean, use: boolean }
  25 | }
```

 with `react-native` 0.56.1 -> 0.57.1 and `typescript` 2.9.2

... for an update with no breaking changes, it seems to be breaking a lot of things. :p

**Comment by chaim1221** [comment]
I'm getting a similar issue:
```
error: bundling failed: SyntaxError: /Users/me/Code/myApp/react/sundown/src/screens/public/login.tsx: Unexpected token, expected ")" (22:46)

  20 |     emailChanged: (text: string) => {},
  21 |     passwordChanged: (text: string) => {},
> 22 |     loginUser: ({ email, password, navigator }: { email: string, password: string, navigator: Navigator }) => {},
     |                                               ^
  23 |     validation: Function,
  24 |     useBiometrics: { wasAsked: boolean, use: boolean }
  25 | }
```
with react-native 0.56.1 -> 0.57.1 and typescript 2.9.2

... for an update with no breaking changes, it seems to be breaking a lot of things. :p

**Comment by chaim1221** [comment]
re: Babel upgrade... srsly?

https://babeljs.io/docs/en/v7-migration
https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading

... it's a short book. Also I tried to do the steps I found there, and it didn't seem to resolve my issue. I ended up stashing my changes.

**Comment by freakinruben** [comment]
@animaonline [Upgrading JavascriptCore](https://github.com/react-community/jsc-android-buildscripts) did the trick for me...

**Comment by chawax** [comment]
Upgrading JavascriptCore works, but it is not supported before SDK 21 (Android < 5.0). And I have the problem too on iOS 9.3.

Is there a way to use Typescript compiler (the one used by react-native-typescript-transformer ?) and not Babel 7 one to compile Typescript ? I already had to solve problems with namespaces and enums because of Babel 7. And now one more problem 👎

**Comment by chawax** [comment]
One gave me the solution ! You have to change your `rn-cli.config.js` file :

```
module.exports = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-typescript-transformer'),
  },
}
```

This way it doesn't use Babel 7 Typescript transformer but the former React Native Typescript transformer that supports namespaces and enums !

**Comment by artyorsh** [comment]
For those who are trying to configure ts with expo-31:
Check our [boilerplate](https://github.com/akveo/akveo-react-native-boilerplate/tree/typescript). This repo contains all initial configurations to make things working with new expo-31, babel 7, typescript and jest.

**Comment by chawax** [comment]
It won't solve other problems with Babel 7 and Typescript, support of namespaces for example. And from what I understood it comes from architectural constraints, so it won't be solved soon. If Babel 7 doesn't support the whole Typescript, it can't be the right choice for React Native with Typescript.

**Comment by LinusU** [comment]
I personally think that the limitations of Babels TypeScript support is extremely small, and not something that you run into, especially since it only affects the code in your project and not the code of your dependencies. I have yet to see a project that actually uses namespaces since we have modules, or maybe I'm missing something?

That being said, there is nothing stopping anyone from using the official TypeScript compiler together with React Native. We didn't change anything to make that harder. In fact, we just upgraded Babel and the new Babel has support for TypeScript.

@chawax if you feel that the Babel support for TypeScript is inadequate, you can use `tsc` with React Native using this package: https://github.com/ds300/react-native-typescript-transformer

I do recommend trying out Babel though since the limitations are very small, and it will be faster since it doesn't have to pass the code first thru `tsc` and then `babel`.

**Comment by chawax** [comment]
@LinusU Actually I use Swagger code generator to generate a API client. And this generated code uses namespaces ;) I tried to patch the Swagger code generator but it's not that easy and time consuming. I used react-native-typescript-transformer as you suggested and it works well (I have posted about this a few posts before) and it works well anyway. Just hope it will still be maintained.

**Comment by jsamr** [comment]
I had the same cryptic message, but was unrelated. If you happen to use **Typescript constructor parameter assignment**, it won't work, see babel/babel/issues/8752

**Comment by danielwinkler** [comment]
@chawax I patched the swagger codegen, it's only a few lines of code
This code removes namespaces and just creates long names for the enums
There should be no name collisions in this case

https://github.com/danielwinkler/swagger-codegen/commit/a519f740475800edda5f7d61ebaef2292d898efe
