### ISSUE TITLE
Image not showing in release build, black color image only showing (Updated)

### ISSUE THREAD

**Issue by merbin2012** [facebook/react-native#21790]
## Environment
  React Native Environment Info:
    System:
      OS: Windows 7
      CPU: x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 1.46 GB / 7.89 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
It is working perfectly if I do not use images in the release build. In release build instead of images, showing only black space.

I am searching for this problem above one month and I found many answers and I tried all, but all are not working.

Tried answers
1) react-native bundle --assets-dest ./android/app/src/main/res/ --entry-file ./App.js --bundle-output ./android/app/src/main/assets/index.android.bundle --platform android -dev false
2) remove all image resizing code

## Reproducible Demo
`import React, { Component } from 'react';
import { Image } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <Image source={require('./a.png')} />
    );
  }
}`

**Comment by radko93** [comment]
We can't help you if you won't reproduce that with latest version

**Comment by merbin2012** [comment]
@radko93 Thanks for your response
Now I have updated to the latest version and tried the same problem still found. The images are shown in "**react-native run-android**" command. But not showing when I run this command "**react-native run-android --variant=release**".

If run the following command before the run-android, it shows "**error duplicate resources**"
"**react-native bundle --assets-dest ./android/app/src/main/res/ --entry-file ./App.js --bundle-output ./android/app/src/main/assets/index.android.bundle --platform android --dev false**"

**react-native info :**
D:\cordova projects\React Native\NewApp>react-native info

  React Native Environment Info:
    System:
      OS: Windows 7
      CPU: x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 1.46 GB / 7.89 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

**Comment by merbin2012** [comment]
The image name is **backimage.png**. I just started learn to React native, so I don't know much more about react native.
I just modify the default **App.js** file with the following code and just copy the "backimage.png" into project folder (D:\cordova projects\React Native\NewApp).

`import React, { Component } from 'react';
import { Image } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <Image source={require('./backimage.png')} style={{ width: 250, height: 160 }} />
    );
  }
}`

**Comment by cbjs** [comment]
same with ImageBackground

**Comment by merbin2012** [comment]
@cbjs I have solved this problem when I put the image into the folder.

**Comment by radko93** [comment]
@merbin2012 which folder?

**Comment by zhangjingzhu19930808** [comment]
@merbin2012 how did you fix it? i have the same problem...

**Comment by cbjs** [comment]
fixed by upgrading gradle to 3.1.4 and buildToolsVersion 27.0.3

**Comment by TheSavior** [comment]
It sounds like this has been resolved with the latest versions of tools. Let us know if you still run into this on the latest release.

**Comment by ssghajar** [comment]
> @cbjs I have solved this problem when I put the image into the folder.

hi,i have this problem too...how did you fix it?which folder?

**Comment by dturner123** [comment]
I have just installed React Native 0.6 and am having the same issue. When running "react-native run-android" the image displays but also shows a network error message. When running "react-native run-android --variant=release", the network error doesn't display, but the image then displays as a black blob.

**Comment by xempie** [comment]
I still have the same issue. It works for some time but for some reason after a few days or a week all images disappear!

**Comment by nuKs** [comment]
Fixed this with shrinkResources set to false in build.gradle.
