### ISSUE TITLE
iOS: border width and color renders incorrectly on iOS for particular values

### ISSUE THREAD

**Issue by rroehrig** [facebook/react-native#21945]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 38.27 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/opt/node@8/bin/node
      Yarn: yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 31.83s. - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
I have a triangle build with View and styles only. It renders incorrectly depending on the width/height values on iOS. The problem occurred after upgrading to react-native 0.57.3 (from 0.55.x).

Actual:
![bildschirmfoto 2018-10-25 um 14 13 08](https://user-images.githubusercontent.com/7395312/47499546-8551f100-d860-11e8-9524-c53937ce723a.png)

Expected:
![bildschirmfoto 2018-10-25 um 14 11 23](https://user-images.githubusercontent.com/7395312/47499614-aa466400-d860-11e8-80d2-2016bbba9cb0.png)

## Reproducible Demo
The following snippet is *not* working (tested with iPhone 6 Plus and iPhone X):
```
<View style={{
                width: 0,
                height: 0,
                backgroundColor: 'transparent',
                borderStyle: 'solid',
                borderTopWidth: 0,
                borderRightWidth: 82.4,
                borderBottomWidth: 82.4,
                borderLeftWidth: 0,
                borderTopColor: 'transparent',
                borderRightColor: 'red',
                borderBottomColor: 'transparent',
                borderLeftColor: 'transparent',
            }}
            />
```

The following snippet is working:
```
<View style={{
                width: 0,
                height: 0,
                backgroundColor: 'transparent',
                borderStyle: 'solid',
                borderTopWidth: 0,
                borderRightWidth: 82.5,
                borderBottomWidth: 82.5,
                borderLeftWidth: 0,
                borderTopColor: 'transparent',
                borderRightColor: 'red',
                borderBottomColor: 'transparent',
                borderLeftColor: 'transparent',
            }}
            />
```

It's just an example, there are much more values showing the problem!

**Comment by mezod** [comment]
Very same issue ocurring here. Also upgrading from 0.55 to 0.57.3. 

![screen shot 2018-11-01 at 20 10 03](https://user-images.githubusercontent.com/1230963/47873794-6a5c1f80-de12-11e8-8703-7fb7ebe5a898.png)

```
         borderTopWidth: 40,
         borderRightWidth: 0,
         borderBottomWidth: 0,
         borderLeftWidth: 60,
         borderTopColor: 'transparent',
         borderRightColor: 'transparent',
         borderBottomColor: 'transparent',
         borderLeftColor: this.props.color,
```

**Comment by ddesvillechabrol** [comment]
Hello,

I had the same issue with react-native 0.57.4 and I deleted this commit https://github.com/facebook/react-native/commit/dba2235d95e46514206bcfaefc7e965193536fe8 to retrieve my triangles.

Dimitri

**Comment by mezod** [comment]
Hey Dimitri! Thanks! By deleting the commit you mean you forked react-native or just changed it in your node_modules while you wait for an upgrade? (i'm not fond of any of both solutions that's why I'm asking :P)

**Comment by ddesvillechabrol** [comment]
Hey ! Yeah I forked react-native repo and I added a commit to undo changes 😄

**Comment by michaelknoch** [comment]
I rewrote my triangles to use transforms today. Maybe the comment "// Asymmetrical edgeInsets cause strange artifacting on iOS 10 and earlier." makes sense

**Comment by angelos3lex** [comment]
Any workaround on this guys?

**Comment by FadiAboMsalam** [comment]
any solution for this guys ?

**Comment by jamesreggio** [comment]
Ah, yikes. @t-benze is right: the regression occurred in a fix I made for another border issue.

Here's the original issue: #11897
Here's my PR with justification: #21208

There was another suggested fix in this PR: #19451

I would suggest that you try incorporating the patch from #19451 and see if it regresses the border-triangle functionality. If it doesn't, open a PR to revert my change (dba2235d) and include the other fix from #19451.

Sorry about this!

**Comment by csath** [comment]
[#19451 ](https://github.com/facebook/react-native/pull/19451) patch didn't work for me. I reverted the ([dba2235](https://github.com/facebook/react-native/commit/dba2235d95e46514206bcfaefc7e965193536fe8)) commit and now it works as previously.

**Comment by FadiAboMsalam** [comment]
is this fixed in react-native 0.58.3 ?
any suggestion how to fix ?

**Comment by rpavlovs** [comment]
This changes breaks semi-circles as well.

Before:
![image](https://user-images.githubusercontent.com/634881/53137817-08e2cc80-3539-11e9-8457-731c72f034f6.png)

After:
![image](https://user-images.githubusercontent.com/634881/53137864-36c81100-3539-11e9-8af2-ff6eea5ffa5a.png)

Manually patching to revert the change fixes the issue. 
#23402 Didn't help since it only disables if for `hasCornerRadii` which we need to set.

What's the best course of actions to fix this?

**Comment by johman10** [comment]
I have found a fix for the triangle issue. Adding a border radius of any value bigger than 0 seems to fix the issue for now without reverting any commit.

Complete styles that work for me:
```js
borderTopWidth: 0,
borderRightWidth: 50,
borderBottomWidth: 50,
borderLeftWidth: 0,
borderTopColor: 'transparent',
borderRightColor: 'red',
borderBottomColor: 'transparent',
borderLeftColor: 'transparent',
width: 0,
height: 0,
backgroundColor: 'transparent',
borderStyle: 'solid',
borderRadius: 0.000001,
```

| without borderRadius | with borderRadius |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5371454/54542525-384ff200-499c-11e9-90d4-5b4b81d040e8.png) | ![image](https://user-images.githubusercontent.com/5371454/54542540-400f9680-499c-11e9-8d07-a09b50bc16ce.png) |

Hope this helps some of you!

**Comment by mezod** [comment]
After having fixed the issue using borderRadius: 0.000001, the error started appearing again randomly (some triangles would appear cut while some others not) setting a bigger borderRadius made the trick, so borderRadius: 1, works better

**Comment by mezod** [comment]
This issue still exists. Using a very small borderRadius like borderRadius: 0.000001 works for 95% of the cases but the triangles still appear cut in some older devices like iPad Mini.

On the other hand, having such a small borderRadius removes a pixel from the opposite hedge as shown here: 

![](https://i.imgur.com/tS6ZcSl.png)

It's barely perceptible and not a big deal, but perceptible enough for people to notice.

Ultimately, using borderRadius feels hacky.
