### ISSUE TITLE
nw_socket_handle_socket_event [C39.1:1] Socket SO_ERROR [61: Connection refused]

### ISSUE THREAD

**Issue by wzup** [facebook/react-native#22140]
React Native always sends this strange logs in Xcode console. This log is just infinite.

What does this log mean?
Is it normal for RN? 
How to remove this behavior from my RN app?

![screen shot 2018-11-05 at 12 06 20 pm](https://user-images.githubusercontent.com/3880497/47993566-712bb080-e0f8-11e8-8f53-8f85b57f9af8.png)

**Comment by wzup** [comment]
This is ridiculous!
Fix your bot. I raised a question that your bot doesn't understand.

**Comment by EricPKerr** [comment]
@wzup i'm running into this issue too. Did you resolve?

**Comment by msand** [comment]
Dupe of https://github.com/facebook/react-native/issues/21030

**Comment by ryd0rz** [comment]
+1

**Comment by vocampos** [comment]
+1

**Comment by ImranNaseem1989** [comment]
+1

**Comment by kisakov** [comment]
+1

**Comment by zazagag** [comment]
+1

**Comment by msand** [comment]
This should be fixed in the latest react-native. Provide a reproduction using the latest version, rather than +1 a closed issue which is a duplicate of a resolved problem.

**Comment by airlaser** [comment]
@msand I'm not seeing this fixed in 0.59.3. I see the code that should fix it, I'm definitely on 0.59.3, but I'm still getting the endless spam.

**Comment by lioPixiumDigital** [comment]
Still here in 0.59.5 too

**Comment by GreenRidingHood** [comment]
i have the same problem, there is another open ticket #24023

**Comment by GreenRidingHood** [comment]
@wzup like my previous comment @patrickkempff solution worked for me, 

at AppDelegate.m  , changing 

`return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];`

to

`return [NSURL URLWithString:@"http://<ip of the packager>:8081/index.bundle?platform=ios"];`

**Comment by mpmprudencio** [comment]
+1

**Comment by DataGreed** [comment]
same problem

**Comment by RWOverdijk** [comment]
@msand This issue has been around for a long time, and issues about this keep getting closed left and right. It's not fixed, still exists, and is really annoying, too.

Anything we can do to help?

**Comment by airlaser** [comment]
My solution was to switch to flutter, it's been more performant and lacks the various little issues like this. And when they do happen, they get fixed.

**Comment by msand** [comment]
@RWOverdijk Are you getting this error once on startup? Or does it keep writing that to the output every so often? The issue used to be that it kept retrying and eating up more memory. Now I only see it once on startup, so in that sense the issue is fixed already. I think facebook has some internal tools which aren't open source, and react-native is trying to connect to that, failing and thus causing this message. Either way it should only happen in development mode, and shouldn't be causing any issues as far as I know at the moment. Or do you have any other symptoms than this being written to output once?

I'm not on the core team, so I don't know anything about the actual difference in development environment internally at facebook vs open-source. And I don't have any power to change the logic related to this. I guess a configuration flag which would disable the system from even trying to connect would be useful, and wouldn't cause developers to go looking for the cause and fix for this warning/error message. What do you think @shergin ?

**Comment by RWOverdijk** [comment]
@msand This issue pops up while running, too. I filter out my logs now, but any other logs become impossible to read. And it keeps becoming more and more, like some old task keeps retrying while new tasks get spawned. I followed the upgrade paths from rndiff, so perhaps something wasn't in there and I missed a step? I'm on 0.59.10 right now, making the step to 0.60 once I fix issues with other libs, but I read that it should be fixed in 0.59.9 as well.

**Comment by packetstracer** [comment]
+1 here. Updated my Xcode and react-native-ble-plx in my project, and cannot start the app it gets stuck in Loaded 100%

**Comment by philipbapr** [comment]
+1 here. I just update my RN to the latest with xcode latest version to and this issue still appear.
