### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by checkraiser** [facebook/react-native#229]
Hi. I've build the AwesomeProject and got 19 Apple Mach-O Linker Error: it has the form of : "_JSContectGetGlobalObject", referenced from..."

Do you know how to fix this? Thank you very much.

**Comment by vjeux** [comment]
Hey, this is the first time we heard of this error. Can you give more information or join IRC to help us figure out what's going on? Thanks!

**Comment by marynate** [comment]
That happened to me when deploying to iOS 6 device, fixed by manually linking JavaScriptCore framework (http://stackoverflow.com/questions/23514579/javascriptcore-framework-availability-on-ios)

Please be noted if you want to target iOS 6, you have to also replace/wrap all iOS 7 api calls in the source.

**Comment by lazywei** [comment]
I faced this error when targeting iOS 7.
![image](https://cloud.githubusercontent.com/assets/2840571/7038399/e4db1cd0-dde3-11e4-8cee-ba263bb2c520.png)

![image](https://cloud.githubusercontent.com/assets/2840571/7038401/e959b870-dde3-11e4-83dc-3359ab26ef5d.png)

**Comment by lazywei** [comment]
after restart Xcode, the error disappear...

**Comment by brentvatne** [comment]
Closing! Let us know if the problem comes back

@jsierles #fridaytriage

**Comment by Hi-Rube** [comment]
my app use react-native 0.3 before some months ago, now i update the react-native to the version 0.6.0 ,I also have this error.  I have known lazywei  restart the Xcode  then error is disappear, but i still have this error, thx

**Comment by asimolmez** [comment]
I deleted a folder of a test project in` Project Navigator` and `Targets`. It solved my problem.
