### ISSUE TITLE
Dimensions.get('window').height returns wrong height on Android with notch

### ISSUE THREAD

**Issue by onitzschke** [facebook/react-native#23693]
## 🐛 Bug Report
Dimensions.get('window').height returns wrong height on Android with notch
Device: Android One Mi A2 Lite

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 1013.34 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 18, 23, 25, 26, 27, 28
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-21 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM EABI v7a, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.58.5 => 0.58.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by hramos** [comment]
Can you provide more information? What value did the API return vs what was expected, for example.

**Comment by onitzschke** [comment]
@hramos 
Xiaomi Mi A2 lite:
    Dimensions.get('window').height) => 681
    Dimensions.get('screen').height) => 760
    StatusBar.currentHeight => 31
Google Pixel 3:
    Dimensions.get('window').height) => 737.4545454545455
    Dimensions.get('screen').height) => 785.4545454545455
    StatusBar.currentHeight => 24

Expect Dimensions.get('window').height) === 705 on Xiaomi Mi A2 lite to get the same Layout as on Google Pixel 3.

**Comment by grabbou** [comment]
I believe this is related to issues with `Dimensions.get('window')` that I outlined here: https://github.com/facebook/react-native/issues/14887#issuecomment-474455052

**Comment by terryttsai** [comment]
Hi I'm seeing the same issue. `Dimensions.get('window').height` returns the wrong dimensions for me as well on my Essential Phone. 

`Dimensions.get('screen').height`: 853.3333333333334
`Dimensions.get('window').height`: 759.6666666666666
`StatusBar.currentHeight`: 48

So I took a screenshot and measured out the pixels. I measured the soft menu bar to be 48 logical pixels. So I expect `Dimensions.get('window').height` to return 853.333 - 48 = 805.333 but instead I get 759.666.

**Comment by ouabing** [comment]
Same issue on Mi 8 Lite.

**Comment by Martijnkerr** [comment]
Issue is on the new Samsung s10 model too.

**Comment by alexandrius** [comment]
My workaround was to calculate root view height with onLayout.

**Comment by andrey-shostik** [comment]
same on redmi note 7

**Comment by danilojpferreira** [comment]
I fix this like this:
Import { Dimensions, StatusBar } from 'react-native';

static height = Platform.OS === 'android' ? Dimensions.get('screen').height - StatusBar.currentHeight : Dimensions.get('window').height;

**Comment by franzwarning** [comment]
True on Samsung Galaxy s10 model.

**Comment by danilojpferreira** [comment]
I trying now fix (temporarily)like this:
Import { Dimensions, StatusBar } from 'react-native';

static height = Platform.OS === 'android' && Platform.Version > 26 ? Dimensions.get('screen').height - StatusBar.currentHeight : Dimensions.get('window').height;

**Comment by danilojpferreira** [comment]
> I fix this like this:
> Import { Dimensions, StatusBar } from 'react-native';
> 
> static height = Platform.OS === 'android' ? Dimensions.get('screen').height - StatusBar.currentHeight : Dimensions.get('window').height;


I trying now fix (temporarily)like this:
Import { Dimensions, StatusBar } from 'react-native';

static height = Platform.OS === 'android' && Platform.Version > 26 ? Dimensions.get('screen').height - StatusBar.currentHeight : Dimensions.get('window').height;

**Comment by Bardimaswift** [comment]
Need add `<meta-data android:name="android.max_aspect" android:value="2.1" />` into `<application>` in `AndroidManifest.xml`. [It helped for me.](https://stackoverflow.com/a/43126712)

**Comment by rahamin1** [comment]
Same problem with react-native 0.59.9, react 16.8.3

### Dimensions.get('window').height  returns:

- 598 on LG V20 (should be 640), StatusBar.currentHeight returns 24.
- 616 on Xiaomi Mi A1 (should be 640), StatusBar.currentHeight returns 24.

### React native info:
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 1.80 GB / 7.87 GB
    Binaries:
      Yarn: 1.16.0 - C:\Users\yossi\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

**Comment by dhruvdangi** [comment]
Based on the phones I've tested, for devices giving wrong height, Dimensions.get('screen').height is not equal to Dimensions.get('window').height.
Here is a temporary fix that I'm using:
```const screenHeight =
      Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height
        ? Dimensions.get('window').height - StatusBar.currentHeight
        : Dimensions.get('window').height

**Comment by andrey-shostik** [comment]
@dhruvdangi exist another case with bottom navigation bar, its can be hid or showed.

**Comment by alexandrius** [comment]
Just create something like this in app layout. There's small startup speed impact but solve the height issue

```jsx
if (this.state.windowHeight === 0) {
    return <View onLayout={({ nativeEvent }) => {
        const windowHeight = nativeEvent.layout.height;
        Defaults.windowHeight = windowHeight;
        this.setState({ windowHeight })
    }} style={{ flex: 1 }} />
}
```

**Comment by jakobinn** [comment]
You can use the following package to fix this issue:
https://github.com/Sunhat/react-native-extra-dimensions-android

**Comment by rahamin1** [comment]
Dear bot;

As far as I am aware, the problem described here is not solved.

**Comment by codeplaygoa** [comment]
> Based on the phones I've tested, for devices giving wrong height, Dimensions.get('screen').height is not equal to Dimensions.get('window').height.
> If StatusBar.currentHeight > 24, we consider that it's a device with a notch
> Here is a temporary fix that I'm using:
> 
> ```
>       Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24
>         ? Dimensions.get('window').height - StatusBar.currentHeight
>         : Dimensions.get('window').height
> ```
unfortunately this didnt work but i modified your code to work for me
[Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24
        ? Dimensions.get('screen').height - StatusBar.currentHeight
        : Dimensions.get('window').height](url)
screen height instead of window

**Comment by jsamr** [comment]
Same issue on OnePlus 7. Even though I appreciate the work done by RN Team, I find the failing of such basic, elementary functionality for so long astonishing. Perhaps the blame is on Android API, I don't know. But it's exasperating.

**Comment by GalB-TenderMarket** [comment]
I solved s10 height issues using this:
```
const height = Platform.OS === 'android' && Platform.Version > 26 ? ExtraDimensions.getRealWindowHeight() - ExtraDimensions.getSoftMenuBarHeight()
 : Dimensions.get('window').height;

```

**Comment by kopax** [comment]
I am having the same issue on an iPhone 6 with chrome and safari.

@GalB-TenderMarket what is `ExtraDimensions`?

**Comment by GalB-TenderMarket** [comment]
> I am having the same issue on an iPhone 6 with chrome and safari.
> 
> @GalB-TenderMarket what is `ExtraDimensions`?

react-native-extra-dimensions-android npm package

**Comment by wmadfaa** [comment]
here is my solution
```tsx
import React, { useState, useContext } from "react";
import { Dimensions, View, LayoutChangeEvent } from "react-native";

export default {
  window: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
};

const DEFAULT_DIMENSIONS_CONTEXT_VALUE = {
  width: Dimensions.get("window").width,
  height: Dimensions.get("window").height,
};

const DIMENSIONS_CONTEXT = React.createContext(DEFAULT_DIMENSIONS_CONTEXT_VALUE);

export const DimensionsProvider: React.FC = ({ children }) => {
  const [layout, setLayout] = useState(DEFAULT_DIMENSIONS_CONTEXT_VALUE);

  const handleLayout = ({ nativeEvent }: LayoutChangeEvent) => {
    const { width, height } = nativeEvent.layout;
    setLayout({ width, height });
  };

  return (
    <View onLayout={handleLayout} style={{ flex: 1 }}>
      <DIMENSIONS_CONTEXT.Provider value={layout}>{children}</DIMENSIONS_CONTEXT.Provider>
    </View>
  );
};

export const useDimensions = () => {
  const dimensions = useContext(DIMENSIONS_CONTEXT);
  return dimensions;
};
```

**Comment by jsamr** [comment]
@wmadfaa That is a workaround the bug but the bug is still here.

**Comment by Bardiamist** [comment]
Faced with it. Very unpleasant bug.

**Comment by stevenyap** [comment]
I am having this bug too.

**Comment by dragos99** [comment]
Me too..so annoying.

**Comment by yangdong-wuye** [comment]
+1

**Comment by trongitnlu** [comment]
It's work for me, you can try it.
`export const deviceHeight = Dimensions.get('window').height;
export const DEVICE_HEIGHT = Platform.select({
  ios: deviceHeight,
  android:
    StatusBar.currentHeight > 24
      ? deviceHeight
      : deviceHeight - StatusBar.currentHeight,
});`

**Comment by cklinx** [comment]
+1

**Comment by maystrenkoYurii** [comment]
+1 according to my observations related CutoutMode

**Comment by hengkx** [comment]
+1

**Comment by Bardiamist** [comment]
<details>

![PHOTO-2020-05-29-11-46-34](https://user-images.githubusercontent.com/22082342/90356258-1703a180-e079-11ea-9aa4-acd6efced5a8.jpg)

<summary>
`Dimensions.get('window').height - StatusBar.currentHeight` works for devices without software bottom navigation bar.
</summary>
</details>

<details>

![Screenshot_2020-08-14-18-31-46-631_com valr app](https://user-images.githubusercontent.com/22082342/90356288-38fd2400-e079-11ea-9aad-6126bf595aed.jpg)

<summary>
But then on devices with software bottom navigation bar that is wrong.
</summary>
</details>

How can I detech that user has software bottom navigation bar?

**Comment by LenKagamine** [comment]
The [workaround](https://github.com/facebook/react-native/issues/23693#issuecomment-662860819) by @trongitnlu works for me, but an alternative is to use [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) and grab the frame width and height from there. This also seems to work with Android navigation buttons @Bardiamist.

```js
import { useSafeAreaFrame } from 'react-native-safe-area-context';

const Component = props => {
  const frame = useSafeAreaFrame();
  // frame.height
};
```

A frame equivalent of  `withSafeAreaInsets` doesn't seem to exist, but with a class component you could make your own higher-order component or a wrapper like this:

```js
class Component extends React.Component { ... }

const Frame = props => {
  const frame = useSafeAreaFrame();
  return <Component {...props} height={frame.height} />;
};
```

or grab directly from `SafeAreaFrameContext`

```js
class Component extends React.Component {
  render() {
    return (
      <SafeAreaFrameContext.Consumer>
        {(frame) => ...}
      </SafeAreaFrameContext.Consumer>
    );
  }
}
```

Make sure to wrap your root component with `SafeAreaProvider` for this to work.

**Comment by pjivers-bom** [comment]
> The [workaround](https://github.com/facebook/react-native/issues/23693#issuecomment-662860819) by @trongitnlu works for me, but an alternative is to use [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) and grab the frame width and height from there.
> 
> ```js
> import { useSafeAreaFrame } from 'react-native-safe-area-context';
> 
> const Component = props => {
>   const frame = useSafeAreaFrame();
>   // frame.height
> };
> ```
> 
> A frame equivalent of `withSafeAreaInsets` doesn't seem to exist, but with a class component you could make your own higher-order component or a wrapper like this:
> 
> ```js
> class Component extends React.Component { ... }
> 
> const Frame = props => {
>   const frame = useSafeAreaFrame();
>   return <Component {...props} height={frame.height} />;
> };
> ```
> 
> or grab directly from `SafeAreaFrameContext`
> 
> ```js
> class Component extends React.Component {
>   render() {
>     return (
>       <SafeAreaFrameContext.Consumer>
>         {(frame) => ...}
>       </SafeAreaFrameContext.Consumer>
>     );
>   }
> }
> ```
> 
> Make sure to wrap your root component with `SafeAreaProvider` for this to work.

That's a really elegant solution. Thank you.

**Comment by safaiyeh** [comment]
> The [workaround](https://github.com/facebook/react-native/issues/23693#issuecomment-662860819) by @trongitnlu works for me, but an alternative is to use [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) and grab the frame width and height from there.
> 
> ```js
> import { useSafeAreaFrame } from 'react-native-safe-area-context';
> 
> const Component = props => {
>   const frame = useSafeAreaFrame();
>   // frame.height
> };
> ```
> 
> A frame equivalent of `withSafeAreaInsets` doesn't seem to exist, but with a class component you could make your own higher-order component or a wrapper like this:
> 
> ```js
> class Component extends React.Component { ... }
> 
> const Frame = props => {
>   const frame = useSafeAreaFrame();
>   return <Component {...props} height={frame.height} />;
> };
> ```
> 
> or grab directly from `SafeAreaFrameContext`
> 
> ```js
> class Component extends React.Component {
>   render() {
>     return (
>       <SafeAreaFrameContext.Consumer>
>         {(frame) => ...}
>       </SafeAreaFrameContext.Consumer>
>     );
>   }
> }
> ```
> 
> Make sure to wrap your root component with `SafeAreaProvider` for this to work.

Appreciate this work around! Closing, feel free to open another issue if this continues to be an issue thanks everyone.

**Comment by Bardiamist** [comment]
@safaiyeh Workaround isn't fix.

Also @LenKagamine workaround not helpful in my case. I want to know dememsions before any view rendered for use demension in StyleSheet.

Instead that workaround possible to use just `View` with `onLayout`. But I want to fix instead workarounds.

**Comment by jsamr** [comment]
@safaiyeh With all respects, another workaround is to not use React Native, or change our careers in development. My point is, **a workaround is no fix**. The bug still exists. Please reopen :-)
ﻡﺮﮑﺸﺘﻣ

**Comment by cristianoccazinsp** [comment]
Looking forward for fixes related to this. I have been testing on a Pixel 5 and got surprised about how terrible the Dimensions and StatusBar components are working.

For starters, the Dimensions API has a different behaviour if the device is in portrait or landscape modes. In portrait, it doesn't seem to account for the status bar height, however, it does include the status bar height in landscape. So the code to get the current screen height has to consider whether or not it is in in portrait or landscape.

Following, the StatusBar API does not update the `currentHeight` value on orientation changes, so it stays to w/e orientation the app was opened with. Therefore, we cannot use `StatusBar.currentHeight` on devices that have different status bars depending on the orientation. Ultimately, we cannot use neither Dimensions nor StatusBar to get the exact window height.

As a very ugly work around written above, I am using this, but note that the 28 value is just a magic value from my test device that will most likely not work in every device.

```
// screen height = windowHeight - getMinusHeight(orientation.isPortrait)

const getMinusHeight = (isPortrait) => {

    // need this to consider notch-based devices
    // update this once RN fixes their height calcs
    if(StatusBar.currentHeight > 24){
      return isPortrait ? 6 : 28;
    }
    return StatusBar.currentHeight;
  }
```

**Comment by jsamr** [comment]
I invite you to express your feelings regarding Dimensions module here: https://github.com/react-native-community/discussions-and-proposals/issues/291

**Comment by zarvedan** [comment]
Did you try to use Dimensions.get("screen").height instead of Dimensions.get("window").height ?

It fixes my issue on Google Pixel 4a.

**Comment by DanielBoening** [comment]
@safaiyeh this workaround is clearly not applicable to all projects without big rework. With more and more android devices getting screen notches it is not understandable why this does not have high priority and is left to stay. 
Furthermore I got the assumption that the wrong screen sizes also affect measureView() calculations for those devices.

**Comment by dancherb** [comment]
It seems like `Dimensions.get('window').height` _doesn't_ include `StatusBar.currentHeight` when `StatusBar.currentHeight` is >24, giving inconsistent results. `Dimensions.get('screen').height` (_screen_ instead of _width_) is also unpredictable. For me, this always had an excess of 48, maybe equivalent to the Android bottom navigation buttons.

You can see how these dimensions given are incorrect with the following example at the root of the app:

```
<View style={{
  flex: 1,
  backgroundColor: 'red'
}}>
    <View style={{
      width: Dimensions.get('window').width - 2,
      height: Dimensions.get('window').height - 2,
      backgroundColor: 'blue',
      borderWidth: 1,
      borderColor: 'yellow'
    }}/>
</View>
```

If all the dimensions given were correct, the blue section would perfectly cover the screen, with a 1px yellow border. This is rarely the case - and there is lots of red space visible, or no yellow.

**Comment by cristianoccazinsp** [comment]
The dimensions module probably has to be externalized since its been almost a year and this is still broken.

**Comment by dancherb** [comment]
I saw useWindowDimensions() from 'react-native' recommended as the way forward and just migrated to this, but this has the same issue...

**Comment by fabriziobertoglio1987** [comment]
I don't think it is worth it investing time to build a separate Dimensions module. They will re-write all this modules with the new architecture https://youtu.be/FqMTXagEvHo

it will take some effort to build the module with all the bug fixes and test both iOS/Android and keep it in sync with react-native.

**Comment by valeriik** [comment]
> > Based on the phones I've tested, for devices giving wrong height, Dimensions.get('screen').height is not equal to Dimensions.get('window').height.
> > If StatusBar.currentHeight > 24, we consider that it's a device with a notch
> > Here is a temporary fix that I'm using:
> > ```
> >       Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24
> >         ? Dimensions.get('window').height - StatusBar.currentHeight
> >         : Dimensions.get('window').height
> > ```
> 
> unfortunately this didnt work but i modified your code to work for me
> `Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24 ? Dimensions.get('screen').height - StatusBar.currentHeight : Dimensions.get('window').height`
> minus from screen height instead of window

This didn't work for me for few Android devices. 

e.g. **Xiaomi Redmi 4A**:
Dimensions.get('screen').height - 640
Dimensions.get('window').height - 640
Status bar height - 25
but REAL Dimensions.get('window').height should be 640-25 = 615 instead of 640!

I have not tested the code below on **absolutely all** Android devices, so I cannot give a 100% guarantee that this code works on 100% of devices in the world, but it works on all devices that I tested:

```
import { getStatusBarHeight } from 'react-native-status-bar-height'
import { initialWindowMetrics } from 'react-native-safe-area-context'

export const STATUS_BAR_HEIGHT = getStatusBarHeight()

export const WINDOW_HEIGHT_NO_STATUS_BAR = Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && STATUS_BAR_HEIGHT > 24 
? Dimensions.get('screen').height - STATUS_BAR_HEIGHT 
: STATUS_BAR_HEIGHT > 24 
  ? Dimensions.get('window').height - STATUS_BAR_HEIGHT 
  : Dimensions.get('window').height + initialWindowMetrics.insets.bottom === Dimensions.get('screen').height 
    ? Dimensions.get('window').height - STATUS_BAR_HEIGHT 
    : Dimensions.get('window').height
```

**Comment by Aryk** [comment]
> > > Based on the phones I've tested, for devices giving wrong height, Dimensions.get('screen').height is not equal to Dimensions.get('window').height.
> > > If StatusBar.currentHeight > 24, we consider that it's a device with a notch
> > > Here is a temporary fix that I'm using:
> > > ```
> > >       Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24
> > >         ? Dimensions.get('window').height - StatusBar.currentHeight
> > >         : Dimensions.get('window').height
> > > ```
> > 
> > 
> > unfortunately this didnt work but i modified your code to work for me
> > `Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24 ? Dimensions.get('screen').height - StatusBar.currentHeight : Dimensions.get('window').height`
> > minus from screen height instead of window
> 
> This didn't work for me for few Android devices.
> 
> e.g. **Xiaomi Redmi 4A**: Dimensions.get('screen').height - 640 Dimensions.get('window').height - 640 Status bar height - 25 but REAL Dimensions.get('window').height should be 640-25 = 615 instead of 640!
> 
> I have not tested the code below on **absolutely all** Android devices, so I cannot give a 100% guarantee that this code works on 100% of devices in the world, but it works on all devices that I tested:
> 
> ```
> import { getStatusBarHeight } from 'react-native-status-bar-height'
> import { initialWindowMetrics } from 'react-native-safe-area-context'
> 
> export const STATUS_BAR_HEIGHT = getStatusBarHeight()
> 
> export const WINDOW_HEIGHT_NO_STATUS_BAR = Platform.OS !== 'ios' && Dimensions.get('screen').height !== Dimensions.get('window').height && STATUS_BAR_HEIGHT > 24 
> ? Dimensions.get('screen').height - STATUS_BAR_HEIGHT 
> : STATUS_BAR_HEIGHT > 24 
>   ? Dimensions.get('window').height - STATUS_BAR_HEIGHT 
>   : Dimensions.get('window').height + initialWindowMetrics.insets.bottom === Dimensions.get('screen').height 
>     ? Dimensions.get('window').height - STATUS_BAR_HEIGHT 
>     : Dimensions.get('window').height
> ```

I tried this, but unfortunately doesn't quite work always.

Only thing that seems tried and true is:

```
import { useSafeAreaFrame } from 'react-native-safe-area-context';
```

**Comment by valeriik** [comment]
> I tried this, but unfortunately doesn't quite work always.
Could you tell please what are these real devices models?

**Comment by Aryk** [comment]
Xiaomi Redmi Note 9S on MUIU Global 12.0.6

**Comment by DaveLomber** [comment]
If someone is interested in getting Android nav bar height - there is a new library which works like a charm

https://github.com/ConnectyCube/react-native-android-navbar-height

```
import { Dimensions } from "react-native";
import { getNavigationBarHeight } from "react-native-android-navbar-height";

// ...

const scale = Dimensions.get('screen').scale;
const navigationBarHeight = await getNavigationBarHeight();
const result = navigationBarHeight / scale;
```

**Comment by paradite** [comment]
For anyone looking for a way to dynamically get the height available for rendering, this is working for me across iOS and Android:
```js
const insets = useSafeAreaInsets();
const frame = useSafeAreaFrame();
const availableHeight = frame.height - insets.top - insets.bottom;
```

My specific use case was to exclude ad banner height from usable height:
```js
const adBannerHeight = 50;
const insets = useSafeAreaInsets();
const frame = useSafeAreaFrame();
const usableHeight = frame.height - adBannerHeight - insets.top - insets.bottom;
```

**Comment by valeriik** [comment]
> For anyone looking for a way to dynamically get the height available for rendering, this is working for me across iOS and Android:
> 
> ```js
> const insets = useSafeAreaInsets();
> const frame = useSafeAreaFrame();
> const availableHeight = frame.height - insets.top - insets.bottom;
> ```
> 
> My specific use case was to exclude ad banner height from usable height:
> 
> ```js
> const adBannerHeight = 50;
> const insets = useSafeAreaInsets();
> const frame = useSafeAreaFrame();
> const usableHeight = frame.height - adBannerHeight - insets.top - insets.bottom;
> ```

[paradite](https://github.com/paradite), according to my research you are only 50% right because for Android it works differently.

My investigation base on your approach:

```
import { getStatusBarHeight } from 'react-native-status-bar-height'
import { initialWindowMetrics } from 'react-native-safe-area-context'

const STATUS_BAR_HEIGHT = getStatusBarHeight()
const usableHeight1 = initialWindowMetrics.frame.height - initialWindowMetrics.insets.top - initialWindowMetrics.insets.bottom
const usableHeight2 = initialWindowMetrics.frame.height
...
```

**Android 10, Huawei P30Lite**

```
...
Dimensions.get('screen').height 770.6666666666666
Dimensions.get('window').height 743.6666666666666

initialWindowMetrics.frame {y: 27, width: 360, height: 743.6666870117188, x: 0}
initialWindowMetrics.insets {bottom: 0, left: 0, right: 0, top: 27}

STATUS_BAR_HEIGHT 27
usableHeight1 716.6666870117188 //WRONG
usableHeight2 743.6666870117188 //CORRECT
```

**Android 7.1.2, Xiaomi Redmi 4A**

```
...
Dimensions.get('screen').height 640
Dimensions.get('window').height 640

initialWindowMetrics.frame {y: 25, width: 360, x: 0, height: 615}
initialWindowMetrics.insets {left: 0, bottom: 0, top: 25, right: 0}

STATUS_BAR_HEIGHT 25
usableHeight1 590 //WRONG
usableHeight2 615 //CORRECT
```

**iPhone 11 simulator**

```
...
Dimensions.get('screen').height 896
Dimensions.get('window').height 896

initialWindowMetrics.frame {y: 0, x: 0, height: 896, width: 414}
initialWindowMetrics.insets {left: 0, top: 48, right: 0, bottom: 34}

STATUS_BAR_HEIGHT 44
usableHeight1 814 //CORRECT
usableHeight2 896 //WRONG
```

**iPhone 5s simulator**

```
...
Dimensions.get('screen').height 568
Dimensions.get('window').height 568

initialWindowMetrics.frame {y: 0, x: 0, height: 568, width: 320}
initialWindowMetrics.insets {left: 0, top: 20, right: 0, bottom: 0}

STATUS_BAR_HEIGHT 20
usableHeight1 548 //CORRECT
usableHeight2 568 //WRONG
```

So, as I can see **the really worked/correct approach is** 🥳:

```
import { Platform } from 'react-native'
import { initialWindowMetrics } from 'react-native-safe-area-context'

const availableHeight = Platform.OS === 'ios' ? initialWindowMetrics.frame.height - initialWindowMetrics.insets.top - initialWindowMetrics.insets.bottom : initialWindowMetrics.frame.height
```

**Comment by paradite** [comment]
@valeriik i tried your solution, it worked on iPhone 8 simulator, but not Samsung S21 (real device).
Evidently my solution is also not correct, so I will try on other devices to test further.

**Comment by paradite** [comment]
@valeriik actually, I noticed that you used `initialWindowMetrics.insets` and `initialWindowMetrics.frame` instead of hooks `useSafeAreaInsets()` and `useSafeAreaFrame()`.

I tested them and they have different values for Android:
Android:
```js
initialWindowMetrics Object {
  "frame": Object {
    "height": 752,
    "width": 360,
    "x": 0,
    "y": 0,
  },
  "insets": Object {
    "bottom": 48,
    "left": 0,
    "right": 0,
    "top": 26.66666603088379,
  },
}
frame Object {
  "height": 752,
  "width": 360,
  "x": 0,
  "y": 0,
}
insets Object {
  "bottom": 0, // different here
  "left": 0,
  "right": 0,
  "top": 26.66666603088379,
}
```

ios:
```js
initialWindowMetrics Object {
  "frame": Object {
    "height": 667,
    "width": 375,
    "x": 0,
    "y": 0,
  },
  "insets": Object {
    "bottom": 0,
    "left": 0,
    "right": 0,
    "top": 20,
  },
}
frame Object {
  "height": 667,
  "width": 375,
  "x": 0,
  "y": 0,
}
insets Object {
  "bottom": 0,
  "left": 0,
  "right": 0,
  "top": 20,
}
```

**Comment by njho** [comment]
Subscribed. @valeriik and others thanks for the research

**Comment by devarif** [comment]
I'm using this approach and worked

`const STATUSBAR_HEIGHT = StatusBar.currentHeight;
const height = STATUSBAR_HEIGHT > 24 ? Dimensions.get('window').height + STATUSBAR_HEIGHT : Dimensions.get('window').height;`

**Comment by kotsh23** [comment]
const [itemHeight, setItemHeight] = useState(
    Platform.OS === "android" && Platform.Version < 30
      ? Dimensions.get("window").height - StatusBar.currentHeight
      : Dimensions.get("window").height
  );

**Comment by cristianoccazinsp** [comment]
Why is this closed? `StatusBar.currentHeight` still gives wrong values on various Android devices (specifically, those with Notch).  It's basically impossible to use `Dimensions` and `StatusBar.currentHeight` to determine height of usable screen space.

Further, the react-native rendering engine also has the same calculation issues. On some devices, trying to get something auto adjust its height up to 100% will end up rendered outside the screen on some devices.

**Comment by yahacom** [comment]
Encountered same issue.
Tested on two phones - both Android API 31. 
And `Dimensions.get('window').height` returns different values. In one case it include value of `StatusBar.currentHeight` (and this value cover full screen height), in another - doesn't (and I have empty space on bottom). And here no any flags to determine relations of this behaviour.

**Comment by lucasmartinsd** [comment]
only solution that worked for me:

```
import { Platform } from 'react-native'
import { initialWindowMetrics } from 'react-native-safe-area-context'

const USABLE_HEIGHT =
            Platform.OS === 'ios'
                ? initialWindowMetrics.frame.height -
                  initialWindowMetrics.insets.bottom
                : initialWindowMetrics.frame.height;
```

worked on: all iphones, samsung galaxy s20fe, samsung galaxy a9, redmi note 7 and motorola moto g5.

**Comment by InceptSolutions** [comment]
An easy fix that worked for us on both Samsung S7 and Samsung A31 is the following:

```js
const height = Dimensions.get("window").height;
const isSame = height == Dimensions.get("screen").height;
const correctHeight = isSame ? height - StatusBar.currentHeight : height;
```

**Comment by lfjnascimento** [comment]
depending on the problem this might help, take the dimensions of the screen and not the window.

```
import { Dimensions } from 'react-native';
const { height: screenHeight, width: screenWidth } = Dimensions.get('screen');
```

**Comment by iway1-hstk** [comment]
Should we reopen a new issue or something? This is a pretty massive problem and definitely is definiteyl the responsibility of the React Native core team. at the moment devs can't even get the height of their screen, it's very frustrating :(.

**Comment by fede4954** [comment]
This issue should definetely NOT be closed, it needs to be reopened or something, this is very much still an issue, I'm getting wrong heights on Galaxy A53 and a Mi A3 for example

Like others said you can use the onLayout prop on an element that spans the entire screen to get the actual height (I use the SafeAreaProvider's from react-native-safe-area-context onLayout) but I don't think this is ideal

**Comment by giorgiobeggiora** [comment]
why the hell was this closed? the issue is not fixed

**Comment by sirmong** [comment]
Still experiencing issues when trying to calculate available space

**Comment by AhmedAbuelenin** [comment]
After some testing on different android versions and different devices this what I got. 
from android version 10 and upwards window height is not including status bar height (fyi status bar height is including notch if exist as far as I tested)
below version 10 window height is including status bar height
we can summarize the above as like:
```
const WINDOW_HEIGHT =
  Platform.OS === 'android' && Platform.Version  >= 29   ? 
  Dimensions.get('window').height + StatusBar.currentHeight
    : Dimensions.get('window').height; 
```
note: WINDOW_HEIGHT on emulator includes status bar height I tested this for a few versions 30, 31, 33 which is different from the real devices as mentioned above.

Hope this help someone.

**Comment by eagleblack** [comment]
I a still facing this issue

**Comment by Colossus** [comment]
This is still not working. Window and screen heights return almost random values and are close to useless

**Comment by Colossus** [comment]
@iway1-hstk immediate Nobel prize for this solution

**Comment by WilcoBreedt** [comment]
> Dimensions.get('screen').height !== Dimensions.get('window').height && StatusBar.currentHeight > 24
>         ? Dimensions.get('window').height - StatusBar.currentHeight
>         : Dimensions.get('window').height

This almost worked. Modified it slightly and seems to be working on Google Pixel 2 XL, Samsung Galaxy S20 FE, Xiaomi Pad 5, Google Nexus 4

```
export const sBarHeight = StatusBar.currentHeight || 0;
export const screenHeight =
  Platform.OS === 'android' &&
  Dimensions.get('screen').height !== Dimensions.get('window').height &&
  sBarHeight <= 24
    ? Dimensions.get('window').height - sBarHeight
    : Dimensions.get('window').height;
```

**Comment by WilcoBreedt** [comment]
Resolved the issue with the following code, which seems to be working well

Custom hook with a context
```jsx
import React, { useContext, useState } from 'react';
import { Dimensions, SafeAreaView, StyleSheet, View } from 'react-native';

const ScreenDimensionsContext = React.createContext(null);

export const useDimensions = () => {
  const dimensions = useContext(ScreenDimensionsContext);
  return dimensions;
};

export const ScreenDimensionsProvider = ({ children, onDimensions }) => {
  const [dimensions, setDimensions] = useState(Dimensions.get('window'));
  const onLayout = (layout) => {
    if (onDimensions) {
      onDimensions(layout);
    }
    setDimensions(layout);
  };
  return (
    <ScreenDimensionsContext.Provider value={dimensions}>
      <SafeAreaView style={styles.flex}>
        <View
          style={styles.flex}
          onLayout={(e) => onLayout(e.nativeEvent.layout)}>
          {children}
        </View>
      </SafeAreaView>
    </ScreenDimensionsContext.Provider>
  );
};

const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
});
```
Use the context anywhere in your app and wrap your App.js in the Context
App.js
```jsx
const App = () => {
const [height, setHeight] = useState();
return (
	<ScreenDimensionsProvider onDimensions={layout => setHeight(layout.height)}>
		<View style={{height}}>
			<RestOfApp />
    	</View>
	</ScreenDimensionsProvider>
)
```
Anywhere else in your app
```jsx
const RandomComponent = () => {
const { height } = useDimensions();
return <View style={{height}} />
}
```

**Comment by Chasty** [comment]
@iway1-hstk Amazing!!

**Comment by deniska69** [comment]
> Сейчас лучшее решение — просто измерить экран самостоятельно и перейти к контексту:
> 
> ```js
> const Context = React.createContext();
> 
> export default function MyApp() {
>     const [appHeight, setAppHeight] = useState(Dimensions.get('window').height);
>     return (
>         <Context.Provider value={appHeight}>
>             <View style={{flex: 1}} onLayout={(e)=>setAppHeight(e.nativeEvent.layout.height)}>
>                 <RestOfApp/>
>             </View>
>         </Context.Provider>
>     )
> }
> 
> export function useActualHeight() {
>     return useContext(Context);
> }
> ```

great solution! How else can I get this value NOT through a hook...

**Comment by Vimiso** [comment]
I don't use `SafeAreaView` because again it's sketchy between platforms. However, using safe area insets information helps. It seems ios includes those values in its window height, while on android you have to explicitly factor them in. I hate that this works:

```jax
import { Dimensions, Platform} from 'react-native'
import { useSafeAreaInsets } from 'react-native-safe-area-context'

const safeAreaInsets = useSafeAreaInsets()
const safeAreaPadding = Platform.OS === 'android' ? safeAreaInsets.top+safeAreaInsets.bottom : 0

const screenHeight = Dimensions.get('window').height + safeAreaPadding
```

...it's nearly 2025 and a simple function to get the actual screen height still does not exist?

**Comment by luanxingtong-helium10** [comment]
use this works for me

```ts
import { useSafeAreaFrame } from "react-native-safe-area-context";

const { height } = useSafeAreaFrame();
```
