### ISSUE TITLE
[RCTBatchedBridge] Exception when running app

### ISSUE THREAD

**Issue by justinmakaila** [facebook/react-native#2396]
Even on a fresh install, I keep receiving this exception when trying to run my RN app:
```
2015-08-21 11:30:02.977 MyApp[46251:1723441] -[RCTBatchedBridge perfStats]: unrecognized selector sent to instance 0x7fabf9bb8a00
2015-08-21 11:30:02.983 MyApp[46251:1723441] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTBatchedBridge perfStats]: unrecognized selector sent to instance 0x7fabf9bb8a00'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106018c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000105cb1bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x00000001060200ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000105f7613c ___forwarding___ + 988
	4   CoreFoundation                      0x0000000105f75cd8 _CF_forwarding_prep_0 + 120
	5   MyApp                       0x0000000104815516 -[RCTBatchedBridge _mainThreadUpdate:] + 422
	6   QuartzCore                          0x0000000106e7710f _ZN2CA7Display15DisplayLinkItem8dispatchEv + 37
	7   QuartzCore                          0x0000000106e76fd7 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 315
	8   CoreFoundation                      0x0000000105f80174 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	9   CoreFoundation                      0x0000000105f7fd35 __CFRunLoopDoTimer + 1045
	10  CoreFoundation                      0x0000000105f41d3d __CFRunLoopRun + 1901
	11  CoreFoundation                      0x0000000105f41366 CFRunLoopRunSpecific + 470
	12  GraphicsServices                    0x0000000108e91a3e GSEventRunModal + 161
	13  UIKit                               0x0000000106fd08c0 UIApplicationMain + 1282
	14  MyApp                       0x00000001047b68af main + 111
	15  libdyld.dylib                       0x0000000109673145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

RN version `0.8.0`

**Comment by ide** [comment]
I think you have profiling mode enabled -- if you turn that off or upgrade RN the issue should go away for you.

**Comment by justinmakaila** [comment]
Is that an Xcode setting...? I'm not sure what you mean

**Comment by ide** [comment]
It's in your app. Easiest way to reset it is to uninstall the app and re-run it.

**Comment by brentvatne** [comment]
Either that or reset simulator settings: ![](http://url.brentvatne.ca/15HnI)

**Comment by justinmakaila** [comment]
Did both to no avail @ide @brentvatne

**Comment by justinmakaila** [comment]
If it helps, the issue is happening on L:721 in `RCTBatchedBridge.m` in the `_mainThreadUpdate:` call. I'm guessing it's supposed to update some sort of UI component

**Comment by ide** [comment]
I would try updating to 0.9.0 or 0.10.0-rc since we don't support old versions.

**Comment by justinmakaila** [comment]
I'm on 0.9.0 now, same thing. Tried 0.10.0 but ran into issues with the `react-native-fbsdk*`

**Comment by justinmakaila** [comment]
I moved the `RCTBridge (RCTPerfStats)` category into the `RCTBridge` file and got past the first issue. Now I'm getting an exception saying that `[RCTRootContentView reactTag]` is an unrecognized selector.

Obviously, not a proper fix for this issue.

**Comment by ide** [comment]
It sounds like there's something wrong with your compiler since `reactTag` is defined in a category as well. Not sure what the problem is though.

**Comment by justinmakaila** [comment]
Hmm, well, one of my coworkers is having the same issue. It's strange, because I would assume that it's due to something that changed in the `project.pbxproj`. However, rolling back to our last working release gives me the same exception.

**Comment by ide** [comment]
Maybe try clearing DerivedData if you haven't already?

**Comment by justinmakaila** [comment]
Cleared `DerivedData` and cleaned. Same issue.

**Comment by danielbuechele** [comment]
I had the same problem. What fixed it for me was adding `-ObjC` to `OTHER_LDFLAGS` in the Build Settings of my project.

**Comment by justinmakaila** [comment]
Tried that but didn't work. I ended up creating a new xcodeproj and transferring all my files and settings over. It was a huge pain, but what are you going to do. Feel free to close this, I'll reopen if I discover any new details.



—Justin Makaila

**Comment by ktoh** [comment]
I've just run into the same issue on 0.11.0.
Tried all the steps above to no avail.
Trace as follows:


```
2015-09-18 16:59:08.305 myapp[833:12138] -[RCTBatchedBridge perfStats]: unrecognized selector sent to instance 0x7fba7bcb94b0
2015-09-18 16:59:08.310 myapp[833:12138] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTBatchedBridge perfStats]: unrecognized selector sent to instance 0x7fba7bcb94b0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109691c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010932abb7 objc_exception_throw + 45
	2   CoreFoundation                      0x00000001096990ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00000001095ef13c ___forwarding___ + 988
	4   CoreFoundation                      0x00000001095eecd8 _CF_forwarding_prep_0 + 120
	5   myapp                            0x0000000108d4b99d -[RCTBatchedBridge _mainThreadUpdate:] + 429
	6   QuartzCore                          0x000000010a58610f _ZN2CA7Display15DisplayLinkItem8dispatchEv + 37
	7   QuartzCore                          0x000000010a585fd7 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 315
	8   CoreFoundation                      0x00000001095f9174 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	9   CoreFoundation                      0x00000001095f8d35 __CFRunLoopDoTimer + 1045
	10  CoreFoundation                      0x00000001095bad3d __CFRunLoopRun + 1901
	11  CoreFoundation                      0x00000001095ba366 CFRunLoopRunSpecific + 470
	12  GraphicsServices                    0x000000010e00ca3e GSEventRunModal + 161
	13  UIKit                               0x000000010a6df8c0 UIApplicationMain + 1282
	14  myapp                            0x0000000108d0f3df main + 111
	15  libdyld.dylib                       0x000000010c88a145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by joenoon** [comment]
I just ran into this as well.  The fix for me was to add __-ObjC__ to Other Linker Flags in the __Project__ (not Target).  The __Target__'s Other Linker Flags should be __$(inherited)__ .

In my case, I had removed the pod "ParseFacebookUtilsV4".  This pod must have been doing this for me and somehow hiding this from being a problem before.

**Comment by ktoh** [comment]
@joenoon unfortunately that's not an option for our project as the -ObjC flag breaks other (Facebook) libraries. 

I'm going to try to dig into the trace to see what I can find....will report back!

**Comment by Jin-Li-ICT** [comment]
@ktoh you can try -force_load linker flag
http://stackoverflow.com/questions/32775481/rctbatchedbridge-perfstats-unrecognized-selector-sent-to-instance

**Comment by ktoh** [comment]
@JansenLi thanks!  I resolve my issue by abandoning the problematic library (facebook SDK).  I did look into the React Bridge traffic using the bridge inspector but was unable to find any more detail.  It looks like the StackOverflow guy you referenced got further than I did :-)

**Comment by tomtang539** [comment]
Had a similar issue, I fixed it by updating plist with the following:

```
<key>LSApplicationQueriesSchemes</key>
<array>
        <string>fbapi</string>
        <string>fb-messenger-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
</array>
```

here's the facebook page that describes the changes:

https://developers.facebook.com/docs/ios/ios9

**Comment by luoyibu** [comment]
@JansenLi how to set the -force_load linker flag?  I didn't find the libReact.a in the project.

**Comment by doronnimrod** [comment]
@danielbuechele 
 -ObjC to OTHER_LDFLAGS
did the trick for me

**Comment by d-a-n** [comment]
@tomtang539 Thanks, this fixes the error.

**Comment by AhmedMAtia** [comment]
Hi 
I have the same issue 
I tried the previews solutions but still have the error 

`2016-01-04 12:22:37.405 myapp [16916:350051] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFString substringFromIndex:]: Index 175 out of bounds; string length 174'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ea9ce65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010dca0deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ea9cd9d +[NSException raise:format:] + 205
	3   Foundation                          0x000000010d84811d -[NSString substringFromIndex:] + 126
	4   myapp                            0x000000010d5e15f5 RCTBundlePathForURL + 293
	5   myapp                            0x000000010d5e167d RCTIsXCAssetURL + 45
	6   myapp                            0x000000010d6336d0 -[RCTXCAssetImageLoader canLoadImageURL:] + 48
	7   myapp                            0x000000010d62ac77 -[RCTImageLoader imageURLLoaderForURL:] + 615
	8   myapp                            0x000000010d62c070 __87-[RCTImageLoader loadImageWithTag:size:scale:resizeMode:progressBlock:completionBlock:]_block_invoke_2125 + 368
	9   libdispatch.dylib                   0x000000011201fe5d _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000011204049b _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001120268ec _dispatch_queue_drain + 2215
	12  libdispatch.dylib                   0x0000000112025e0d _dispatch_queue_invoke + 601
	13  libdispatch.dylib                   0x0000000112028a56 _dispatch_root_queue_drain + 1420
	14  libdispatch.dylib                   0x00000001120284c5 _dispatch_worker_thread3 + 111
	15  libsystem_pthread.dylib             0x000000011237868f _pthread_wqthread + 1129
	16  libsystem_pthread.dylib             0x0000000112376365 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by tinygipxy** [comment]
Hi, 

I got this error in this line of code: 


NSString *RCTGetURLQueryParam(NSURL *URL, NSString *param)
{
  RCTAssertParam(param);
  if (!URL) {
    return nil;
  }
  NSURLComponents *components = [NSURLComponents componentsWithURL:URL
                                           resolvingAgainstBaseURL:YES];
  **for (NSURLQueryItem *item in components.queryItems.reverseObjectEnumerator) {**
    if ([item.name isEqualToString:param]) {
      return item.value;
    }
  }
  return nil;
}


2016-01-10 00:06:23.698 empty18[3667:60b] -[__NSConcreteURLComponents queryItems]: unrecognized selector sent to instance 0x14da35c0
2016-01-10 00:06:23.703 empty18[3667:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSConcreteURLComponents queryItems]: unrecognized selector sent to instance 0x14da35c0'
*** First throw call stack:
(0x30d92f83 0x3b543ccf 0x30d96917 0x30d95203 0x30ce4768 0x95d6f 0x5f69d 0x5c631 0x5bb87 0x3ba2b833 0x3ba2b81f 0x3ba2b777 0x30d5d8a1 0x30d5c175 0x30cc6ebf 0x30cc6ca3 0x35bcc663 0x3361314d 0x4900d 0x3ba50ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

Regards,

**Comment by kavehazari** [comment]
What @tomtang539 suggested fixed the problem for me as well. Thank you.

**Comment by RobinClowers** [comment]
I fixed this error just by `rm -rf node_modules && npm install`.

**Comment by stscript** [comment]
when I stop the global proxy ,it work

**Comment by yey** [comment]
@stscript `stop the global proxy` works! good job!

**Comment by kevinhylant** [comment]
@luoyibu did you ever figure this out? I have the same issue where my version of RN does not have a static ReactLib.a library

**Comment by wkarim86** [comment]
I had the same issue in mac. I just unchecked Web Proxy(HTTP) and Secure Web Proxy (HTTPS) under Systems Preferences > Network > Advance > Proxies
That's it and React Native start working

**Comment by neiker** [comment]
I tried all suggestions from this thread and still happen. On RN 42

**Comment by dayudodo** [comment]
I fixed this error by:
`npm uninstall yarn
rm -rf node_modules && npm install`

**Comment by superandrew213** [comment]
I got this error when I started using yarn. My fix:
```
rm -rf node_modules
yarn cache clean
npm cache clean
npm i
```
