### ISSUE TITLE
Android AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

### ISSUE THREAD

**Issue by HunterHR** [facebook/react-native#25296]
🚨 The issue tracker is not for questions. 🚨

As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek. Please take a look at the following resources.

### https://stackoverflow.com/questions/tagged/react-native

If you have a coding question related to React Native, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React Native, as well as ask for help with specific questions.

### https://www.reactiflux.com/

Reactiflux is an active community of React and React Native developers. If you are looking for immediate assistance or have a general question about React Native, the #react-native channel is a good place to start.

If you want to participate in casual discussions about the use of React Native, consider participating in one of the following forums:
- Discord Community: https://discord.gg/0ZcbPKXt5bZjGY5n
- Spectrum Chat: https://spectrum.chat/react-native
- Facebook Group: https://www.facebook.com/groups/react.native.community

If you'd like to discuss topics related to the future of React Native, or would like to propose a new feature or change before sending a pull request, please check out the discussions and proposals repo:
- https://github.com/react-native-community/discussions-and-proposals

> For a full list of community resources, check out React Native's Community page at https://facebook.github.io/react-native/help.

**Comment by nailikhaled** [comment]
android\app\build\intermediates\manifests\full\release\AndroidManifest.xml:63: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.

**Comment by Dhaval240420** [comment]
hey ant one find any solution, i am getting same issue

**Comment by BartlomiejKucyniak** [comment]
warning: string 'ucrop_error_input_data_is_absent' has no default translation.
warning: string 'ucrop_mutate_exception_hint' has no default translation.
/Users/xxx/xxx/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:45: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

**Comment by dhamnesh** [comment]
Facing the same issue. How to resolve??

**Comment by PixClix** [comment]
Same here. Error is thrown local and in bitrise.

**Comment by t1amat9409** [comment]
These bots are quick to close issues for no valid reason😅😅... I'm also facing this issue... Can't seem to find a fix online

**Comment by PixClix** [comment]
Maybe related to this: https://developers.google.com/android/guides/releases#june_17_2019

**Comment by t1amat9409** [comment]
Could be so...

**Comment by dancherb** [comment]
Also experiencing this issue - have reverted to previous commits and getting the same error, which suggests it's an external issue (like the Google news link given)

**Comment by prameetc** [comment]
@viniciusoliveira01 Thanks mate! Your solution worked perfectly!

**Comment by VicEsquivel** [comment]
Any update in the issue?

**Comment by Pradeep-DCPL** [comment]
Hi guys any update about this issue. i am facing the same

**Comment by udaisubramaniam** [comment]
Add this to the end of your app/build.gradle dependencies, it forces the gcm library version- so then the third party libraries you're using in your project that are dependent on it, don't break

configurations.all {
       resolutionStrategy {
           force 'com.google.android.gms:play-services-gcm:16.1.0'
           force 'com.google.android.gms:play-services-base:16.1.0'
           force 'com.google.firebase:firebase-core:16.0.9'
           force 'com.google.firebase:firebase-messaging:18.0.0'
   }}

**Comment by MateuszPrasal** [comment]
@udaisubramaniam solved my problem ! Thanks !

**Comment by heldercunha** [comment]
Problem solved.

In my case i only add this line in my build.gradle file

ext {
    buildToolsVersion = '28.0.3'
    minSdkVersion = 23
    compileSdkVersion = 27
    targetSdkVersion = 27
    supportLibVersion = '27.1.1'

    // this line solve my problem
    googlePlayServicesVersion = '16.+'
}

**Comment by t1amat9409** [comment]
``` npm i jetifier && npx jetify ``` kinda helped me

**Comment by graka295** [comment]
@heldercunha t
thanks mate!

**Comment by graka295** [comment]
@heldercunha thanks dude, you are hero

**Comment by cfmitrah** [comment]
@heldercunha Thanks it worked perfectly.

**Comment by dimlksin2** [comment]
None of the solutions work for me, are there any other options to fix the problem?

**Comment by wanxsb** [comment]
@heldercunha Thanks, it worked perfectly

**Comment by HarshitMadhav** [comment]
@udaisubramaniam your solution worked but now I am unable to get the push notifications using firebase.

**Comment by Pradeep-DCPL** [comment]
It worked for me by adding below lines 

Android/App/build.gradle

**Changed below line** 
compile 'com.google.android.gms:play-services-base:+'
compile 'com.google.android.gms:play-services-maps:+'

**To** 
compile 'com.google.android.gms:play-services-base:16.1.0'
compile 'com.google.android.gms:play-services-maps:16.0.0'

AND in Android/build.gradle
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 18
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
    googlePlayServicesVersion = "16.+"
    firebaseVersion = "17.3.4"
}

**Comment by jsmitrah** [comment]
My team faced this issue in three different projects. Each one need a different fix and all are working fine now.
I mentioned all 3 fixes below

Solution 1:

implementation(project(":react-native-push-notification"), {
exclude group: "com.google.android.gms"
exclude group: "com.google.firebase"
})

After that the notifications stopped working here so I have to add this in my app/android/build.gradle:
ext {
googlePlayServicesVersion = "16.0.0"
firebaseVersion = "17.3.4"
}

*********************************
Solution 2:

In another case i only added this line in my build.gradle file

ext {
buildToolsVersion = '28.0.3'
minSdkVersion = 23
compileSdkVersion = 27
targetSdkVersion = 27
supportLibVersion = '27.1.1'

// this line solve my problem
googlePlayServicesVersion = '16.+'
}

***********************************
Solution 3:

Finally in app/build.gradle
you can use this

dependencies {
    compile "com.google.android.gms:play-services-gcm:16.1.0"
    compile "com.google.firebase:firebase-messaging:17.6.0"
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase", module: "firebase-messaging"
    }
    ...
}

**Comment by jsmitrah** [comment]
My team faced this issue in three different projects. Each one need a different fix and all are working fine now.
I mentioned all 3 fixes below

Solution 1:

implementation(project(":react-native-push-notification"), {
exclude group: "com.google.android.gms"
exclude group: "com.google.firebase"
})

After that the notifications stopped working here so I have to add this in my app/android/build.gradle:
ext {
googlePlayServicesVersion = "16.0.0"
firebaseVersion = "17.3.4"
}

*********************************
Solution 2:

In another case i only added this line in my build.gradle file

ext {
buildToolsVersion = '28.0.3'
minSdkVersion = 23
compileSdkVersion = 27
targetSdkVersion = 27
supportLibVersion = '27.1.1'

// this line solve my problem
googlePlayServicesVersion = '16.+'
}

***********************************
Solution 3:

Finally in app/build.gradle
you can use this

dependencies {
    compile "com.google.android.gms:play-services-gcm:16.1.0"
    compile "com.google.firebase:firebase-messaging:17.6.0"
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase", module: "firebase-messaging"
    }
    ...
}

**Comment by udaisubramaniam** [comment]
I had mentioned the fix for me was this- https://github.com/facebook/react-native/issues/25296#issuecomment-503440779

However incase you use firebase notifications and find they aren't working, add this as well in the dependencies

implementation project(':react-native-firebase')
implementation(project(':react-native-push-notification')) {
    exclude group: 'com.google.android.gms'
}

**Comment by mstratiev** [comment]
> It worked for me by adding below lines
> 
> Android/App/build.gradle
> 
> **Changed below line**
> compile 'com.google.android.gms:play-services-base:+'
> compile 'com.google.android.gms:play-services-maps:+'
> 
> **To**
> compile 'com.google.android.gms:play-services-base:16.1.0'
> compile 'com.google.android.gms:play-services-maps:16.0.0'
> 
> AND in Android/build.gradle
> ext {
> buildToolsVersion = "26.0.3"
> minSdkVersion = 18
> compileSdkVersion = 26
> targetSdkVersion = 26
> supportLibVersion = "26.1.0"
> googlePlayServicesVersion = "16.+"
> firebaseVersion = "17.3.4"
> }

god bless you, @Pradeep-DCPL , GOD BLESS YOU
was about to lose my cool if that damn debugging and configs and stuff

**Comment by leuducquy** [comment]
god bless you, @Pradeep-DCPL 
You save my life
Fro me i did change from compile 'com.google.android.gms:play-services-base:+' to  implementation 'com.google.android.gms:play-services-base:16.1.0' and it work

**Comment by Subway19** [comment]
@Pradeep-DCPL  Thanks so much. It works.

**Comment by patrickgalbraith** [comment]
For me the issue was with `react-native-device-info` but it will happen with anything that uses v17+ of `play-services-gcm`.

The fix was to add this to our `android/build.gradle` to force the version.

```
def versionOverrides = [
    "com.google.android.gms:play-services-gcm": "16.+"
]

subprojects {
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def overrideVersion = versionOverrides[details.requested.group + ":" + details.requested.name]

            if (overrideVersion != null && details.requested.version != overrideVersion) {
                logger.info "Overriding dependency ${details.requested.group}:${details.requested.name} version ${details.requested.version} --> $overrideVersion"
                details.useVersion overrideVersion
            }
        }
    }
}
```
You will get "Overriding dependency..." messages which will tell you which packages are being replaced.

Credit to Howard Lewis Ship for the gradle override code.

**Comment by ppv94** [comment]
i am getting same error 
AAPT: No resource identifier found for attribute 'appCompon
entFactory' in package 'android'

i changed googlePlayServicesVersion = '+' to googlePlayServicesVersion = '16.+'

what should i do
this is my build.gradle
ext {
        googlePlayServicesVersion = '16.+'
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.0"
    }

and my dependencies :

dependencies {
    compile project(':react-native-image-crop-picker')
    //compile project(':react-native-facebook-account-kit')
    compile project(':react-native-youtube')
    compile project(':react-native-vector-icons')
    compile project(':react-native-compress-image')
    compile project(':lottie-react-native')
    compile project(':react-native-gesture-handler')
    compile project(':react-native-image-picker')
    compile project(':react-native-fbads')
    compile project(':react-native-admob')
    compile project(':react-native-share')
    compile project(':react-native-android-permissions')
    compile project(':react-native-view-shot')
    compile project(':react-native-image-resizer')
    compile project(':react-native-fs')
    compile 'com.facebook.fresco:fresco:1.8.1'
    compile 'com.facebook.fresco:animated-gif:1.8.1'
    // For WebP support, including animated WebP
    compile 'com.facebook.fresco:animated-webp:1.3.0'
    compile 'com.facebook.fresco:webpsupport:1.3.0'
    // For WebP support, without animations
    compile 'com.facebook.fresco:webpsupport:1.3.0'
    compile project(':react-native-fetch-blob')
    compile project(':react-native-svg')
    compile project(':react-native-fbsdk')
    //compile project(':react-native-vector-icons')
    compile project(':react-native-linear-gradient')
    compile fileTree(dir: "libs", include: ["*.jar"])
     implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
     implementation ("com.android.support:support-v4:${rootProject.ext.supportLibVersion}")
     implementation ("com.android.support:design:${rootProject.ext.supportLibVersion}")
    compile 'com.google.android.gms:play-services-ads:16.0.0'
    compile "com.facebook.react:react-native:+"  // From node_modules
        //compile ("com.facebook.react:react-native:^0.56.0") { //force = true }
    compile 'com.google.android.gms:play-services-auth:+' // should be at least 9.0.0
    implementation (project(':react-native-facebook-account-kit')) {
        exclude group: "com.android.support"
    }
    }

**Comment by vvusts** [comment]
For me issue was solved by upgrading `react-native-device-info` to latest version (2.1.1) and changed compileSDK from 27 to 28 (also need to install SDK28 from SDK Manager).

**Comment by baotoan1905** [comment]
> For me issue was solved by upgrading `react-native-device-info` to latest version (2.1.1) and changed compileSDK from 27 to 28 (also need to install SDK28 from SDK Manager).

OMG, OMG. You are my life saviour. I changed the compileSDK from 27 to 28 then it's working like a charm. Thanks man. BTW, can you share how you know that we need to increase the compileSDK ?

**Comment by vvusts** [comment]
[Read this](https://github.com/facebook/react-native/issues/25294).

**Comment by ppv94** [comment]
upgrading react-native-device-info to latest version (2.1.1) and changed compileSDK from 27 to 28
i am getting below error
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
what should i do

**Comment by Keerato** [comment]
After upgrading react-native-device-info to the latest version (2.1.1) and changed compile SDK from 27 to 28, I am getting below error

Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/app/INotificationSideChannel$Stub$Proxy.class

What should I do next?

**Comment by nailikhaled** [comment]
Add this section to dependencies.gradle file

configurations.all {
        resolutionStrategy { 
            force 'com.google.guava:guava:14.0.1'
            force 'com.google.guava:guava-gwt:14.0.1'
        }
    }

**Comment by nailikhaled** [comment]
Add this section to dependencies.gradle file

 configurations.all {
     resolutionStrategy {
        force 'com.google.android.gms:play-services-gcm:16.1.0'
        force 'com.google.android.gms:play-services-base:16.1.0'
        force 'com.google.firebase:firebase-core:16.0.9'
        force 'com.google.firebase:firebase-messaging:18.0.0'
}}

**Comment by ppv94** [comment]
> Add this section to dependencies.gradle file
> 
> configurations.all {
> resolutionStrategy {
> force 'com.google.android.gms:play-services-gcm:16.1.0'
> force 'com.google.android.gms:play-services-base:16.1.0'
> force 'com.google.firebase:firebase-core:16.0.9'
> force 'com.google.firebase:firebase-messaging:18.0.0'
> }}

but am not using any firebase in my project 
here is my build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "27.0.2"
            }
        }
    }
}

subprojects {
      if (project.name.contains('react-native-vector-icons')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }
        }
    }
}

buildscript {

ext {
        googlePlayServicesVersion="15.0.1"
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "27.1.0"
    }

    repositories {
        jcenter()
        google()
    }
    dependencies {
         classpath 'com.android.tools.build:gradle:3.1.4'
         classpath 'com.google.gms:google-services:3.2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects {
	if (project.name.contains('react-native-vector-icons')) {
		buildscript {
			repositories {
				maven {
					url "https://dl.bintray.com/android/android-tools/"
				}
				jcenter()
			}
		}
	}
}

subprojects {
	if (project.name.contains('react-native-image-picker')) {
		buildscript {
			repositories {
				maven {
					url "https://dl.bintray.com/android/android-tools/"
				}
				jcenter()
			}
		}
	}
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        configurations.all {
    resolutionStrategy {
        force 'com.facebook.android:facebook-android-sdk:4.28.0'
        }
    }
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
}

**Comment by SaiKiran322** [comment]
> It worked for me by adding below lines
> 
> Android/App/build.gradle
> 
> **Changed below line**
> compile 'com.google.android.gms:play-services-base:+'
> compile 'com.google.android.gms:play-services-maps:+'
> 
> **To**
> compile 'com.google.android.gms:play-services-base:16.1.0'
> compile 'com.google.android.gms:play-services-maps:16.0.0'
> 
> AND in Android/build.gradle
> ext {
> buildToolsVersion = "26.0.3"
> minSdkVersion = 18
> compileSdkVersion = 26
> targetSdkVersion = 26
> supportLibVersion = "26.1.0"
> googlePlayServicesVersion = "16.+"
> firebaseVersion = "17.3.4"
> }

@Pradeep-DCPL  LifeSaviour <3

**Comment by Leinadio** [comment]
After a little tour on the internet. I did this.

**Step 1:** 
Add in the _android/build.gradle_.
`googlePlayServicesVersion = "16.0.0"`
`firebaseVersion = "17.3.4"`
```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0"
        firebaseVersion = "17.3.4"
    }
   ...
```
**Step 2:** 
`cd android && ./gradlew assemble`

**Step 3:** 
Open android studio and open an android emulator. Mine is on Pixel XL API 27

**Step 4:** 
`react-native run-android`

**Comment by dengue8830** [comment]
fixed with this

```
configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-gcm:16.1.0'
  }
}
```

that fixes two issues:
- firebase
`appComponentFactory androidx problem`

- react-native-device-info
`Android dependency 'com.google.android.gms:play-services-stats' has >different version for the compile (16.0.1) and runtime (17.0.0)`

Explanation: gms has upgraded to androidx so all the libs that use it as dependency had defined it as `:gms+` so when google released a breaking change they all updated to it and broke everything

Solutions:
1) upgrade your project and dependencies in order to use androidx. Not all you dependencies are using it so i don't know if this is a good idea.
2) force the project to use a previous version of the gms lib. This could be a problem? may be, will see 😆  it's building fine for now

I will wait until all the libs upgrade to androidx and then migrate the project to rn60

**Comment by Tuapplicacion** [comment]
I'm having the same problem, I've tried everything and I haven't been luck.

**android/build.gradle**

`ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
    // supportLibVersion = "27.1.0"
    googlePlayServicesVersion="12.0.1"
}`

**app/build.gradle**
`dependencies {
    compile project(':react-native-view-overflow')
    compile project(':react-native-video')
    compile project(':react-native-vector-icons')
    compile project(':react-native-splash-screen')
    compile project(':react-native-sentry')
    compile project(':react-native-push-notification')
    compile project(':react-native-onesignal')
    compile project(':react-native-localization')
    compile project(':react-native-keep-awake')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-google-places')
    compile project(':react-native-gesture-handler')
    compile project(':react-native-geolocation-service')
    compile project(':react-native-firebase')
    compile project(':react-native-fcm')
    compile project(':react-native-fbsdk')
    compile project(':react-native-device-info')
    compile project(':react-native-code-push')
    compile project(':react-native-camera')
    compile project(':react-native-android-location-services-dialog-box')
    compile project(':react-native-admob')
    implementation project(':react-native-code-push')
    implementation project(':react-native-view-overflow')
    implementation project(':react-native-admob')
    implementation project(':react-native-sentry')
    implementation project(':react-native-keep-awake')
    implementation project(':react-native-firebase')
    implementation 'com.facebook.android:facebook-android-sdk:4.37.0'
    implementation 'com.facebook.android:facebook-marketing:4.37.0' 
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-geolocation-service')
    implementation project(':react-native-push-notification')
    implementation project(':react-native-google-places')

    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation "com.google.firebase:firebase-core:16.0.6"
    // implementation 'com.google.firebase:firebase-core'
    // implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.android.support:multidex:1.0.3'
    implementation project(':react-native-onesignal')
    implementation project(':react-native-camera')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-video')
    implementation (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        implementation 'com.android.support:exifinterface:+'
        implementation ('com.google.android.gms:play-services-vision:12.0.1') {
            force = true
        }
    }
    implementation project(':react-native-android-location-services-dialog-box')
    implementation project(':react-native-device-info'), {
        exclude group: "com.google.android.gms"
    }
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-localization')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.android.gms:play-services-ads:17.1.1'

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.google.gms.google-services'`

I already have test all fixes in the previous posts and nothing seems to work for me.

**Comment by dengue8830** [comment]
you have to upgrade to android 28, i will update my last answer, check it my `ext` android build config

**Comment by cesarPHP** [comment]
Hi, i'm using cordova apache for mobile apps, but i got the same error when i compile. I'm using too firebase and google maps plugin's. I did all the posible solutions that you show here with the build.gradle
And, i have not luck, please help!!!

**Comment by t1amat9409** [comment]
@cesarPHP did you migrate to androidx?

**Comment by cesarPHP** [comment]
mmm, no, how i do that?

**Comment by Keerato** [comment]
I've tried all of the solutions here, but it still doesn't work.
I want to identify the reason for this issue. So, please corrects me if I'm wrong.
This issue is due to some libs we are using already upgrade to AndroidX.
So, some of its dependencies have a conflict with each other.
The ways to solve this are: 
1. wait until all libs upgrade to AndroidX
2. downgrade all libs not to use AndroidX

**Comment by bundamasakan** [comment]
> 
> 
> After upgrading react-native-device-info to the latest version (2.1.1) and changed compile SDK from 27 to 28, I am getting below error
> 
> Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> 
> > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/app/INotificationSideChannel$Stub$Proxy.class
> 
> What should I do next?

same problem

**Comment by t1amat9409** [comment]
> thanks to @udaisubramaniam. Fixed with this
> 
> at the end of your `android/app/build.gradle` (before `apply plugin` line if you have that line)
> 
> ```
> configurations.all {
>   resolutionStrategy {
>     force 'com.google.android.gms:play-services-gcm:16.1.0'
>   }
> }
> ```
> 
> that fixes two issues:
> 
> * firebase
>   `appComponentFactory androidx problem`
> * react-native-device-info
>   `Android dependency 'com.google.android.gms:play-services-stats' has >different version for the compile (16.0.1) and runtime (17.0.0)`
> 
> Explanation: gms has upgraded to androidx so all the libs that use it as dependency had defined it as `:gms+` so when google released a breaking change they all updated to it and broke everything
> 
> Solutions:
> 
> 1. upgrade your project and dependencies in order to use androidx. Not all you dependencies are using it so i don't know if this is a good idea.
> 2. force the project to use a previous version of the gms lib. This could be a problem? may be, will see laughing  it's building fine for now
> 
> I will wait until all the libs upgrade to androidx and then migrate the project to rn60
> 
> UPDATE: Seeing the `useful resources` below, you have to upgrade your android project to sdk 28 (i have had already done that because it's a good practice). If you use android studio it will propose you to automagically upgrade to the config below
> 
> this is my `ext` config in `android/build.gradle`
> 
> ```
> ext {
>     buildToolsVersion = "28.0.3"
>     minSdkVersion = 16
>     compileSdkVersion = 28
>     targetSdkVersion = 28
>     supportLibVersion = "28.0.0"
> }
> ```
> 
> also i'm using
> `classpath 'com.android.tools.build:gradle:3.3.2'`
> `gradle version 4.10.1`
> 
> Useful resources
> 
> #25307
> [#25296 (comment)](https://github.com/facebook/react-native/issues/25296#issuecomment-503440779)
> #25301
> https://stackoverflow.com/questions/56648263/android-dependency-com-google-android-gmsplay-services-stats-has-different-ve

@bundamasakan did you try the above? if not... then you need to install jetifier

```
npm i jetifier && npx jetify
```

This will help migrate your project to android x and resolve all conflicts... you might have to jetify your project every time you npm install

**Comment by bundamasakan** [comment]
> @bundamasakan did you try the above? if not... then you need to install jetifier
> 
> ```
> npm i jetifier && npx jetify
> ```
> 
> This will help migrate your project to android x and resolve all conflicts... you might have to jetify your project every time you npm install

still with the same problem.
is there another way
@t1amat9409

**Comment by t1amat9409** [comment]
If you did jetify. Remove all references to ```android.*``` in your app/build.gradle ... 
Make sure you have a copy just in case, but it worked for me.

The duplicates are cause by ```android.*``` libraries

**Comment by andrewhartwig** [comment]
@dengue8830 I owe you a beer sir, your solution of adding 
```
configurations.all {
  resolutionStrategy {
    force 'com.google.android.gms:play-services-gcm:16.1.0'
  }
}
```

resolved my situation without having to tinker with anything else.

I wish I understood what any of this does better. I get really stressed out when these random google issues occur!

**Comment by dengue8830** [comment]
@andrewhartwig that forces the project to use that specific version of that lib for all the implicit dependencies used within the libs you have installed, if you check the versions of that lib you will see the latest versions are 16.1 and 17 and if you check inside of each one, version 17 has androidx dependencies.

So i can't understand how others still have issues even with this solution, may be they are specifying another gcm version within some specific dependency, or are using some lib that has androidx as dependency. You guys should execute the command that draws a tree and there you will see wich lib is using androidx so you can include it in the `force` line config. That command is in the links that i mentioned above

**Comment by andrewhartwig** [comment]
Thank you @dengue8830 great explanation!

**Comment by Alferdize** [comment]
please help I am stuck in push notification issue.I have tried all the above solution. my `react-native info` is 
`React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 48.23 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 26.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-asset: 1.1.3
      react-native-cli: 2.0.1
      react-native-contacts-wrapper: 0.2.4
      react-native-contacts: 4.0.2
      react-native-push-notification: 3.1.3`
my android build gradle is:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.0"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        googlePlayServicesVersion = "16.0.0"
        firebaseVersion = "17.0.0"
    }
    repositories {
        google()
        jcenter()
        maven { 
            url "https://jitpack.io"
         }
          maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:4.2.0'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }


}
subprojects {
    afterEvaluate {
        project -> if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '26.0.2'
            }
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { url "https://jitpack.io" }
         maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
`

and my app build gradle is:
`apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.gosociety"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }


    configurations.all {
        resolutionStrategy {
            force 'com.android.support:support-v4:27.1.0'

        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}


dependencies {
    implementation "com.google.android.gms:play-services-gcm:16.1.0"
    implementation (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase", module: "firebase-messaging"
    }

    implementation project(':react-native-image-picker')


    implementation project(':react-native-contacts')
    implementation project(':react-native-svg')
    implementation project(':react-native-contacts-chooser')
    implementation project(':react-native-i18n')
    implementation project(':react-native-locale-detector')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-share')
    implementation project(':react-native-image-to-pdf')


    implementation project(':react-native-charts-wrapper')

    implementation project(':react-native-vector-icons')
    implementation project(':react-native-fs')

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules


}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

// apply plugin: 'com.google.gms.google-services'`

the app crashes whenever the push-notification is called in my login.js file:
`
import React, {Component} from 'react';
import {
  Platform,
  StyleSheet,
  ImageBackground,
  TouchableOpacity,
  AsyncStorage,
  Dimensions,
  NetInfo,
  ActivityIndicator,
  View,
  BackHandler,
  Alert
} from 'react-native';
import {
  Container,
  Text,
  Body,
  Button,
  Input,
  Item,
  CheckBox,
  Right,
  Left,
  Title,
  Thumbnail
} from 'native-base';
import Icon from 'react-native-vector-icons/FontAwesome';
import PushNotification from 'react-native-push-notification'
// var PushNotification = require('react-native-push-notification');
import Global from '../global/Global';
import Constant from '../global/Constants';
import VerifyUser from '../mutation/login/verifyUser';
import updateUserToken from '../mutation/updateUserToken';
import {  withApollo, compose,graphql,Query } from 'react-apollo'
import GetWings from '../query/tracker/GetWings.js'
import { strings } from '../locales/I18n';
import I18n from 'react-native-i18n';
import AwesomeAlert from 'react-native-awesome-alerts';


import gql from 'graphql-tag';
import Constants from '../global/Constants';


// true means invalid, so our conditions got reversed
class Login extends Component {
  constructor(props){
    super(props);
    this.state={
  //  username: '8459832342',
  //   password: 'khan',
    //  username: '8483077289',
    //  password: 'anubhavsharma',
     username: '',
      password: '',
    //  username: '',
    //  password: '',
      icon:1,
      True:'',
      connection_Status : "",
      Error1:'0',
      Error:'',
      isUserLoggedIn:false,
      placeholder_userName:'',
      placeholder_password:'',
      app_lang:'',
      showAlert:true,
      alertText:'',
  }
  
}

componentWillMount(){  
  this.exitApp();
  this.getAppLanguage();

   
   
    if (Platform.OS == "android") {
      BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);                           
}

}

componentWillUnmount() {
  if (Platform.OS == "android") {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);                           
}

}


 /*
Alert to exit application
*/
exitApp = () => {
  
BackHandler.addEventListener('hardwareBackPress', function() {
Alert.alert(
  strings('alert.exit_app_title'),
  strings('alert.exit_app_msg'), [{
      text: 'Cancel',
      onPress: () => console.log('Cancel Pressed'),
      style: 'cancel'
  }, {
      text: 'OK',
      onPress: () => BackHandler.exitApp()
  }, ], {
      cancelable: false
  }
)
return true;
})

}


//Exit app wih back button press
handleBackButton = () => {

  if (this.props.isFocused) {
    Alert.alert(
      'Exit App',
      'Exiting the application?',
      [
        {
          text: 'Cancel',
          onPress: () => console.log('Cancel Pressed'),
          style: 'cancel'
        },
        {
          text: 'OK',
          onPress: () => BackHandler.exitApp()
        }
      ],
      {
        cancelable: false
      }
    );
    return true;
  }
};




// registerToken = (mob,slugSocName)=>{
//   console.log("crash")
//   let self = this;

//   PushNotification.configure({
//     onError: function(e) {
//       console.log('onErro ::',e)
//     },
//     onRegister: function ({token, os}) {
//       console.log('TOKEN:', token);
      
//       AsyncStorage.setItem('token', JSON.stringify(token));
//       self.updateTokenInDB(mob ,token, slugSocName)
//     },
//     onNotification: function (notification) {
//       console.log('NOTIFICATION:', notification);
//     },
//     senderID: "1087021464546",
//     permissions: {
//       alert: true,
//       badge: true,
//       sound: true
//     },
//     popInitialNotification: true,
//     requestPermissions: true,
//   });
//   console.log("op")

  
// }

registerToken = (mob,slugSocName)=>{

  console.log("In reg ::",mob,  slugSocName)
  let self = this;

  try {

  PushNotification.configure({
    
    onError: function(e) {
      console.log('onError ::',e)
    },
    onRegister: function ({token}) {
      console.log('TOKEN:', token);
      
      AsyncStorage.setItem('token', JSON.stringify(token));
      self.updateTokenInDB(mob ,token, slugSocName)
    },
    
    onNotification: function (notification) {
      console.log('NOTIFICATION:', notification);
    },
    senderID: "1087021464546",
    permissions: {
      alert: true,
      badge: true,
      sound: true
    },
    popInitialNotification: true,
    requestPermissions: true,
  });

     
} catch (error) {
    console.log('In reg catch :',error)
}
}

updateTokenInDB = (mob, token,slugSocName)=>{

  // const user = JSON.parse(this.state.admin)

  console.log('in updateTokenDB ::',mob,token)

  this.props.UpdateUserToken({
      variables: {
        slugSocName: slugSocName,
        mob: mob,
        token
      }
    })
    .then(({ data }) => {

      console.log('In Update token success :',data)

    })
    .catch((err) => {
      console.log(`Update Token : in err: ${JSON.stringify(err)}`);
    });

}



//get app language
getAppLanguage = () => {
  AsyncStorage.getItem(Constants.APP_LANGUAGE).then(value =>{
    I18n.locale = value;
    this.setState({
      app_lang:value
    })
  })
}




  





componentDidMount() {
  NetInfo.isConnected.addEventListener(
      'connectionChange',
      this._handleConnectivityChange

  );
  NetInfo.isConnected.fetch().done((isConnected) => {

    if(isConnected == true)
    {
      this.setState({connection_Status : "Online"})
    }
    else
    {
      this.setState({connection_Status : "Offline"})
    }

  });
}

connection() {
    // prevent memory leaks!
    NotificationsIOS.removeEventListener('remoteNotificationsRegistered', this.onPushRegistered.bind(this));
  NotificationsIOS.removeEventListener('remoteNotificationsRegistrationFailed', this.onPushRegistrationFailed.bind(this));
  NetInfo.isConnected.removeEventListener(
    'connectionChange',
    this._handleConnectivityChange);
}
_handleConnectivityChange = (isConnected) => {

  if(isConnected == true)
    {
      this.setState({connection_Status : "Online"})
    }
    else
    {
      this.setState({connection_Status : "Offline"})
    }
};
press =()=>{
  const { icon} = this.state
  if(icon==0){
    this.setState({icon:1});
  }
else{
  this.setState({icon:0});

}
}

  signUp = () => {
    const { username, password} = this.state
  this.setState({Error1:'0'});
  const reg = /^[0]?[789]\d{9}$/;
if(reg.test(username) === false){
     this.setState({Error:'please fill the valid phone no.'});
     this.setState({Error1:'1'});
    }
    else if(password==""){
      this.setState({Error:'please fill the passsword'});
      this.setState({Error1:'2'});  
    }
   
    else {
      this.props.navigation.navigate("PersonalInfoForm" )
  }
 }
 _storeData = async (data) => {
  try {
    await AsyncStorage.setItem('ownerDetails', JSON.stringify(data));
    console.log("IN store data funtion")
  } catch (error) {
    console.log("Data is not Available")
  }
}
_storeWings = async (data) => {
  try {
    await AsyncStorage.setItem('Wings', JSON.stringify(data));
    console.log("Wings Stored")
  } catch (error) {
    console.log("Data is not Available")
  }
}
getWings = (slugSocName) => {
  this.props.client
  .query({
    query: GetWings,
    variables: {
      mId: `${slugSocName}::wing`
    },
    fetchPolicy: "network-only"
  })
      .then(({ data }) => {
        this.setState({ loading: false });
        
        console.log('Wings ::',data.getSocietyMetaById)

        if (data.getSocietyMetaById != null) {
          this._storeWings(data.getSocietyMetaById)
  
        } 
      })
      .catch(err => {
        this.setState({ loading: false });


      });
}


// Verify User
verifyCredintials = () => {
  console.log("in login pres >>>")
  const { username, password, connection_Status} = this.state;
  if((username == ''  || username.length == 0) && (password == '' || password.length == 0)){
    alert(strings('errors.please_enter_username_password'))
  }else if(username == '' || username.length == 0){
    alert(strings('errors.please_enter_mobile'))
  }else if(password == '' || password.length == 0){
    alert(strings('errors.please_enter_password'))
  }else if(username.length > 0 && password.length > 0){
    this.checkInternetConnection();
  }else{
    alert("Please fill all details");
  }
}

/*
    Check Internet connection
  */
 checkInternetConnection = () => {
  NetInfo.isConnected.fetch ().then (result => {
    if (result) {
      this.login();
    } else {
      alert ('No internet connection');
      this.setState ({
        isInternetAvailable: false,
      });
    }
  });
};


//Verify user
  login = () => {
 const { username, password, connection_Status} = this.state
 this.connection
 console.log('uname :',username,password)
 if(connection_Status == "Online")
 {
  this.setState({True: 1})
    this.props.VerifyUser({
        variables: {
          "mob": username,
          "pass": password
        }
      })
      .then(({ data }) => {
      //  console.log("login data = " + JSON.stringify(data))
      console.log("login Succ = ")

      if(data.verifyUser == null){
        alert("Please check username or password");
        setTimeout(()=>{this.setState({True: ''})}, 2000);
      }else{
      AsyncStorage.setItem(Constant.IS_USER_LOGGED_IN , true.toString());
        // this.onReg()
       // this.registerToken(data.verifyUser.mob,data.verifyUser.slugSocName)
       this.registerToken(data.verifyUser.mob,data.verifyUser.slugSocName)
        console.log("crash2")
       this._storeData(data.verifyUser)
       this.getWings(data.verifyUser.slugSocName);
       setTimeout(()=>{this.setState({True: ''})}, 2000);
       if(data.verifyUser.role=="flatOwner"){        
        setTimeout(()=>{this.props.navigation.navigate('Navigate')}, 1500);
       }
       else{
        setTimeout(()=>{this.props.navigation.navigate('PersonalInfoForm')}, 1500);
       }
      
      }
        
      })
      .catch((err) => {
        setTimeout(()=>{this.setState({True: ''})}, 100);
        alert(`${JSON.stringify(err)}`);
        //alert("Please check username or password")
      });
    }
    else{
      alert("You Are Offline");
    }
  }


  showAlert = () => {
    this.setState({
      showAlert: true
    });
  };
 
  hideAlert = () => {
    this.setState({
      showAlert: false
    });
  };

  
  render () {
    const {showAlert , alertText} = this.state;
   
    let pic = {
      uri: 'http://www.tokkoro.com/picsup/2407175-abstract-blue-light-pink-and-orange-color-gradient-background.jpg',
    };
    return (
      
      <Container style = {Global.container}>
     
          <Body style={styles.LoBody}>
       
           
            <Thumbnail source={require('../image/logo.png')} style={styles.Iconstyle} large/>
              <Body style = {styles.loginContainer}>
      
            <Item  style={Global.Itemtstyle} rounded >
            <Input style = {[Global.InputStyle,Global.appFont]}
             placeholder = {strings('login.enter_mobile_no')}
            keyboardtype='numeric'
            value = {this.state.username}
            onChangeText={username=>this.setState({username})} 
            />
            <Icon active name='user-circle' color='black'  size={25}/>


            </Item>

            {this.state.Error1 === '1'? <Text style={Global.ErrorStyle}>{this.state.Error}</Text>: <Text></Text> }
            <Item  style={Global.Itemtstyle} rounded>
            <Input style = {[Global.InputStyle,Global.appFont]}
            placeholder = {strings('login.enter_password')}
            value = {this.state.password}
            secureTextEntry = {this.state.icon === 0 ? false : true }
            onChangeText={password=>this.setState({password})} 
            />
            <Icon active size={25} color='black' name={this.state.icon === 0 ? 'eye' : 'eye-slash' } 
             onPress={this.press}/>
          
      
            </Item>
            {this.state.Error1 === '2'? <Text style={Global.ErrorStyle}>
            {this.state.Error}</Text>: <Text></Text> }
          { this.state.True === '' ? 
          
          <Button  full onPress = {this.verifyCredintials.bind(this)}   style={[Global.loginbutton,Global.appFont,{borderRadius:25}]}>
          <Text style={[Global.AppHeaderTextStyle , Global.appFont]}>
          {strings('login.login')}
          </Text>
         
            </Button>
            
         : <View style={[styles.container1, styles.horizontal]}>
        <ActivityIndicator size="large" color="#5c007a" />
      </View>}
         

         <Button  transparent style = {[Global.ResetLink,Global.appFont]} 
         onPress = {() => this.props.navigation.navigate("ChangepasswordScreen")}>
         <Text style={[Global.Bluecolor,Global.appFont]}>
         {strings('login.forgot_password')}
          </Text>
         </Button>
    
            </Body>
            </Body>


      </Container>
    );
  }
}
const styles = StyleSheet.create ({
  container: {
    width: '100%',
    height: '100%',
    flex: 1,
  },
  RemFont:{
    fontSize: 20
  },
  RemMar:{
    margin:15
  },
  Iconstyle:{
    width:200, 
    height:100, 
    marginTop:30,
    marginBottom: 20,
  },
  HeaderLo:{
    width:420, 
    height:60,
    alignItems: 'center', 
    backgroundColor:  '#5c007a'
  },
  LoBody:{ 
    alignItems: 'center',
    paddingHorizontal:20 ,
    marginTop:30
  },
  LoItem:{
    alignItems: 'center', 
  borderBottomWidth:0
},
loginContainer:{
  marginTop:20
},
});


// export default Login;

const LoginPage = compose(
  withApollo, 
  graphql(VerifyUser,{name: "VerifyUser"}),
  graphql(updateUserToken,{name: "UpdateUserToken"}),
  

)(Login)

export default LoginPage;
`
please help Thank you.

**Comment by baotoan1905** [comment]
@Alferdize 
I fixed by updated to the latest react-native-push-notification 3.1.3. 
Then From app/build.gradle I added the following
`implementation(project(":react-native-push-notification"), {
      exclude group: "com.google.android.gms"
      exclude group: "com.google.firebase"
    })
    implementation "com.google.android.gms:play-services-gcm:${rootProject.ext.googlePlayServicesVersion}"
    implementation "com.google.firebase:firebase-messaging:${rootProject.ext.firebaseVersion}"`

in build.gradle I added 
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        googlePlayServicesVersion = "16.0.0"
        firebaseVersion = "17.5.0"
    }
Hope it helps.

**Comment by Keerato** [comment]
Now I found the solution!
You have to update react-native to 0.59
In your package.json
"dependencies": {
"react": "^16.5.1",
"react-native": "^0.59.0",
"react-native-device-info": "^2.1.2",
...
}
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5.0.2",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1"
  },
  "resolutions": {
    "@babel/runtime": "7.0.0-beta.46"
  },
In .babelrc
{
  "presets": ["module:metro-react-native-babel-preset"]
}

And also use 
compileSdkVersion = 28
classpath 'com.android.tools.build:gradle:3.3.2'
gradle version 4.10.1
Then 
npm i jetifier && npx jetify
npx react-native run-android
And then my app get back to life again. Hope that will help

**Comment by natsu90** [comment]
this is frustrating, i'm working on cordova app & tried everything above, none of those works for me.

**Comment by FunkyLambda** [comment]
Wow, what a rubbish platform for developing apps. And yet people use RN.

**Comment by t1amat9409** [comment]
@FunkyLambda are you a Flutter Dev??

**Comment by willgriffiths** [comment]
For an explanation of the two fixes this article is great: 
https://itnext.io/react-native-how-to-handle-an-app-with-both-pre-androidx-and-androidx-dependencies-rn60-bf4df7ea0dd2

**Comment by FunkyLambda** [comment]
> Maybe related to this: https://developers.google.com/android/guides/releases#june_17_2019

@PixClix Niiiice! Worked for me. Changed my `compileSdkVersion` from 27 to 28 and that fixed it.

**Comment by mg4u** [comment]
> It worked for me by adding below lines
> 
> Android/App/build.gradle
> 
> **Changed below line**
> compile 'com.google.android.gms:play-services-base:+'
> compile 'com.google.android.gms:play-services-maps:+'
> 
> **To**
> compile 'com.google.android.gms:play-services-base:16.1.0'
> compile 'com.google.android.gms:play-services-maps:16.0.0'
> 
> AND in Android/build.gradle
> ext {
> buildToolsVersion = "26.0.3"
> minSdkVersion = 18
> compileSdkVersion = 26
> targetSdkVersion = 26
> supportLibVersion = "26.1.0"
> googlePlayServicesVersion = "16.+"
> firebaseVersion = "17.3.4"
> }

Thanks, your suggestion works for me.

As a side note, consider being sure that `com.android.support:appcompat-VERSON` is 27 like  this line 
`    compile "com.android.support:appcompat-v7:27.0.1"`

**Comment by WeslleyNasRocha** [comment]
> @FunkyLambda are you a Flutter Dev??

Looks like xamarin

**Comment by rithikunsen** [comment]
Hello
