### ISSUE TITLE
App Crash on Android OS 5.1.1 Real Oppo R7s (32BIT) RN(0.60.0)

### ISSUE THREAD

**Issue by xrebrovz** [facebook/react-native#25490]
after init react native new version 0.60.0 application crash after open

07-04 16:42:16.737 30259-30317/? E/art: dlopen("/data/data/com.news060/lib-main/libc++_shared.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.news060/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
07-04 16:42:16.737 30259-30317/? E/SoLoader: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.news060/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
07-04 16:42:16.737 30259-30317/? E/SoLoader: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.news060/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
07-04 16:42:16.737 30259-30317/? E/SoLoader: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.news060/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
07-04 16:42:16.737 30259-30317/? E/SoLoader: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.news060/lib-main/libc++_shared.so" is 64-bit instead of 32-bit

FATAL EXCEPTION: create_react_context
    Process: com.news060, PID: 30259
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.news060/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:818)

## Environment:
React Native Version 0.60.0
OS: Mac OS Mojave 10.14.4
Android Studio: Version 3.4.1
Android Device Oppo r7s 5.1.1 (os 32bit) 

## Steps To Reproduce
1.Init React Native 0.60.0
2.react-native run-android on real device oppo r7s 5.1.1 (os 32bit) app crash

**Comment by reachzhai** [comment]
same problem,so many users tell us they can't use our app

java.lang.UnsatisfiedLinkError: 
  at com.facebook.soloader.SoLoader.b (SoLoader.java:738)
  at com.facebook.soloader.SoLoader.a (SoLoader.java:591)
  at com.facebook.soloader.SoLoader.a (SoLoader.java:529)
  at com.facebook.soloader.SoLoader.a (SoLoader.java:484)
  at com.facebook.react.bridge.ReactBridge.staticInit (ReactBridge.java:31)
  at com.facebook.react.bridge.NativeMap.<clinit> (NativeMap.java:19)
  at com.facebook.react.jscexecutor.JSCExecutorFactory.create (JSCExecutorFactory.java:25)
  at com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:944)
  at java.lang.Thread.run (Thread.java:818)

**Comment by ckitterl** [comment]
The problem is  cause by oppo's install appication.

**Comment by BennyTian** [comment]
the same problem  .

`
couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.huabenapp/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
`


crash on Android  5.0/5.1/5.1.1  device.

**Comment by ckitterl** [comment]
@BennyTian If my answer can't resolve the problem ？

**Comment by BennyTian** [comment]
> @BennyTian If my answer can't resolve the problem ？

I am going to try  thanks .

**Comment by zsajjad** [comment]
Facing same issue. Count of 64bit & 32bit libs is same @ckitterl

**Comment by codyi96** [comment]
Same issue in VIVO X7...
It seems a bug caused by the installer of Funtouch OS. I update to Funtouch OS PD1602_A_3.12.2 then it works. 😎

**Comment by ckitterl** [comment]
@zsajjad VIVO or OPPO. I test on OPPO R9 with colorOS v3.0.0 and android 5.1; If the count of 64bit & 32bit libs are same, everything is OK. But Failed with VIVO X7 as codyi96 said

**Comment by zsajjad** [comment]
I made changes to packagingOptions and things are working fine on all devices both 64-bit & 32 bit devices

```groovy
    defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }
    }
    ...
    packagingOptions {
        doNotStrip '*/mips/*.so'
        doNotStrip '*/mips64/*.so'
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'

        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'

        exclude "lib/arm64-v8a/libgnustl_shared.so"
        exclude '/lib/mips64/**'
        exclude '/lib/arm64-v8a/**'
        exclude '/lib/x86_64/**'
    }
```

**Comment by codyi96** [comment]
> I made changes to packagingOptions and things are working fine on all devices both 64-bit & 32 bit devices
> 
> ```groovy
>     defaultConfig {
>         ndk {
>             abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
>         }
>     }
>     ...
>     packagingOptions {
>         doNotStrip '*/mips/*.so'
>         doNotStrip '*/mips64/*.so'
>         pickFirst '**/armeabi-v7a/libc++_shared.so'
>         pickFirst '**/x86/libc++_shared.so'
>         pickFirst '**/arm64-v8a/libc++_shared.so'
>         pickFirst '**/x86_64/libc++_shared.so'
> 
>         pickFirst '**/x86/libjsc.so'
>         pickFirst '**/armeabi-v7a/libjsc.so'
> 
>         exclude "lib/arm64-v8a/libgnustl_shared.so"
>         exclude '/lib/mips64/**'
>         exclude '/lib/arm64-v8a/**'
>         exclude '/lib/x86_64/**'
>     }
> ```
Thank you for your reply! But I have different opinions.
It's impossiable to generate an apk file included .so files for arm64-v8a i think. Because you has excluded `/lib/arm64-v8a/**`.
In other words, the following configuration is invalid:
```groovy
     defaultConfig {
         ndk {
             abiFilters 'arm64-v8a'
         }
     }
```
In this case, you only used .so files for armeabi-v7a instead of arm64-v8a, so it works.😂
@zsajjad

**Comment by waseefakhtar** [comment]
> I made changes to packagingOptions and things are working fine on all devices both 64-bit & 32 bit devices
> 
> ```groovy
>     defaultConfig {
>         ndk {
>             abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
>         }
>     }
>     ...
>     packagingOptions {
>         doNotStrip '*/mips/*.so'
>         doNotStrip '*/mips64/*.so'
>         pickFirst '**/armeabi-v7a/libc++_shared.so'
>         pickFirst '**/x86/libc++_shared.so'
>         pickFirst '**/arm64-v8a/libc++_shared.so'
>         pickFirst '**/x86_64/libc++_shared.so'
> 
>         pickFirst '**/x86/libjsc.so'
>         pickFirst '**/armeabi-v7a/libjsc.so'
> 
>         exclude "lib/arm64-v8a/libgnustl_shared.so"
>         exclude '/lib/mips64/**'
>         exclude '/lib/arm64-v8a/**'
>         exclude '/lib/x86_64/**'
>     }
> ```

@zsajjad  I tried your suggestion by making changes to packagingOptions which now throws an exception saying `/libimagepipeline.so" is 32-bit instead of 64-bit` instead of the other way around (I mean, I can reproduce it even on an emulator and not just on an Oppo device):

```
2019-08-20 15:40:03.430 14786-15049/com.degoo.android.dev W/System.err: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.degoo.android.dev/lib-main/libimagepipeline.so" is 32-bit instead of 64-bit com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738) 
com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591) 
com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529) 
com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484) 
com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40) 
com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:31
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13) 
com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init (MemoryPooledByteBufferOutputStream.java:51) com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:73) 
com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24) 
com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:85) 
com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:97) 
com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(LocalResourceFetchProducer.java:37) 
com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:50) com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:46) 
com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43) 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51) java.lang.Thread.run(Thread.java:919)
```

**Comment by codyi96** [comment]
Fixed by this [pr](https://github.com/facebook/SoLoader/pull/45).

**Comment by waseefakhtar** [comment]
@oprisnik could you merge https://github.com/facebook/react-native/issues/25490#issuecomment-522968429 and release a new version for Fresco?

**Comment by oprisnik** [comment]
Awesome, thanks @codyi96, I'll take a look.

**Comment by oprisnik** [comment]
SoLoader 0.8.0 [has been released](https://github.com/facebook/SoLoader/releases/tag/v0.8.0). You can now update the version for RN and this should be fixed, fingers crossed.

Side note: With v0.8.0, we've also released a new `NativeLoader` interface that can be used instead of `SoLoader.loadLibrary(...)`. This allows you to employ any native library loading mechanism you'd like. Just implement your own `NativeLoaderDelegate` and initialize `NativeLoader` with that instance.

**Comment by btxd** [comment]
Hi,guys.I have given up using fresco. Facebook developer solves the problem too slowly; use Glide to solve my problem

**Comment by ckitterl** [comment]
> react-native v0.60.5
> still issue please help me

Upgrade Soloader 0.80 will resolve your problem.

**Comment by auchaphon** [comment]
> > react-native v0.60.5
> > still issue please help me
> 
> @auchaphon Upgrade Soloader 0.80 will resolve your problem.

I try this , still not work
<img width="662" alt="Screen Shot 2562-09-24 at 20 30 53" src="https://user-images.githubusercontent.com/29698585/65515946-4dd54400-df0a-11e9-8f17-6b01fd4f1e08.png">

**Comment by codyi96** [comment]
> > > react-native v0.60.5
> > > still issue please help me
> > 
> > 
> > @auchaphon Upgrade Soloader 0.80 will resolve your problem.
> 
> I try this , still not work
> <img alt="Screen Shot 2562-09-24 at 20 30 53" width="662" src="https://user-images.githubusercontent.com/29698585/65515946-4dd54400-df0a-11e9-8f17-6b01fd4f1e08.png">

@auchaphon 
You can try to do it like this:
```groovy
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
```

**Comment by ursNj** [comment]
in which file we have to force the soloader newer version ????

**Comment by codyi96** [comment]
> in which file we have to force the soloader newer version ????

build.gradle under your module folder.

For example:
![image](https://user-images.githubusercontent.com/23372652/65830704-74b5c080-e2e4-11e9-889d-86fc4e86ef94.png)

You can check the version by run `gradle dependencies` in terminal:
![image](https://user-images.githubusercontent.com/23372652/65830718-b2b2e480-e2e4-11e9-9a93-c9f1251d6ae2.png)

File: [build.gradle.txt](https://github.com/facebook/react-native/files/3666613/build.gradle.txt)

**Comment by mars-lan** [comment]
Can confirm that forcing soloader to 0.8.0 does *not* fix the issue. Still seeing the following crash on react-native 0.60.5 + react-native-v8 (i.e. not using hermes)

```
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libhermes.so
com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:789)
com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:639)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:577)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:525)
com.facebook.hermes.reactexecutor.HermesExecutor.<clinit> (HermesExecutor.java:20)
com.facebook.hermes.reactexecutor.HermesExecutorFactory.create (HermesExecutorFactory.java:27)
com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:949)
java.lang.Thread.run (Thread.java:761)
```

**Comment by nolife08021** [comment]
> > > > react-native v0.60.5
> > > > still issue please help me
> > > 
> > > 
> > > @auchaphon Upgrade Soloader 0.80 will resolve your problem.
> > 
> > 
> > I try this , still not work
> > <img alt="Screen Shot 2562-09-24 at 20 30 53" width="662" src="https://user-images.githubusercontent.com/29698585/65515946-4dd54400-df0a-11e9-8f17-6b01fd4f1e08.png">
> 
> @auchaphon
> You can try to do it like this:
> 
> ```groovy
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```

@codyi96  Hi, I had forced to 0.8.0 version, but still faced the same issue. Any advice?

**Comment by codyi96** [comment]
> > > > > react-native v0.60.5
> > > > > still issue please help me
> > > > 
> > > > 
> > > > @auchaphon Upgrade Soloader 0.80 will resolve your problem.
> > > 
> > > 
> > > I try this , still not work
> > > <img alt="Screen Shot 2562-09-24 at 20 30 53" width="662" src="https://user-images.githubusercontent.com/29698585/65515946-4dd54400-df0a-11e9-8f17-6b01fd4f1e08.png">
> > 
> > 
> > @auchaphon
> > You can try to do it like this:
> > ```groovy
> > configurations.all {
> >      resolutionStrategy {
> >        force "com.facebook.soloader:soloader:0.8.0"
> >      }
> > }
> > ```
> 
> @codyi96 Hi, I had forced to 0.8.0 version, but still faced the same issue. Any advice?

@nolife08021 Could u show me the logcat? Maybe this issue and yours are different, i guess.🤔

**Comment by nolife08021** [comment]
@codyi96 
 
Thanks for help. I fixed it with this solution [https://github.com/facebook/react-native/issues/25415#issuecomment-541404167](url)

**Comment by mharlowfod** [comment]
@nolife08021 That link comes up dead for me, can you confirm if it's still the solution or if it has moved? Any copy-paste would be great, too.

**Comment by codyi96** [comment]
@mharlowfod 
https://github.com/facebook/react-native/issues/25415#issuecomment-541404167

**Comment by trinanda** [comment]
> > > > react-native v0.60.5
> > > > still issue please help me
> > > 
> > > 
> > > @auchaphon Upgrade Soloader 0.80 will resolve your problem.
> > 
> > 
> > I try this , still not work
> > <img alt="Screen Shot 2562-09-24 at 20 30 53" width="662" src="https://user-images.githubusercontent.com/29698585/65515946-4dd54400-df0a-11e9-8f17-6b01fd4f1e08.png">
> 
> @auchaphon
> You can try to do it like this:
> 
> ```groovy
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```

Woa... I have try to figure out this few days..
this saved mine, thanks a lots Man :)

**Comment by kyubjn** [comment]
> I made changes to packagingOptions and things are working fine on all devices both 64-bit & 32 bit devices
> 
> ```groovy
>     defaultConfig {
>         ndk {
>             abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
>         }
>     }
>     ...
>     packagingOptions {
>         doNotStrip '*/mips/*.so'
>         doNotStrip '*/mips64/*.so'
>         pickFirst '**/armeabi-v7a/libc++_shared.so'
>         pickFirst '**/x86/libc++_shared.so'
>         pickFirst '**/arm64-v8a/libc++_shared.so'
>         pickFirst '**/x86_64/libc++_shared.so'
> 
>         pickFirst '**/x86/libjsc.so'
>         pickFirst '**/armeabi-v7a/libjsc.so'
> 
>         exclude "lib/arm64-v8a/libgnustl_shared.so"
>         exclude '/lib/mips64/**'
>         exclude '/lib/arm64-v8a/**'
>         exclude '/lib/x86_64/**'
>     }
> ```

It work for me. Thank bro
