### ISSUE TITLE
fontWeight behavior changed on Android between <0.60.0 and >= 0.60.0 - now high font weights can default to low ones

### ISSUE THREAD

**Issue by iamacup** [facebook/react-native#25696]
Prior to 0.60.0 font weights that were not supported but were high would default to the nearest 'bold' font. Now they just default to a non-bold font.

React Native version:

## Steps To Reproduce

1a. `react-native init AwesomeProject` (at time of writing defaults to version 0.60.3)
2a. Use this code in `App.js`

```

import React, {Fragment} from 'react';
import { Text, SafeAreaView } from 'react-native';

const App = () => {
  return (
      <SafeAreaView>
        <Text style={{fontWeight: '900'}}>FONT WEIGHT 900</Text>
        <Text style={{fontWeight: '800'}}>FONT WEIGHT 800</Text>
        <Text style={{fontWeight: '700'}}>FONT WEIGHT 700</Text>
        <Text style={{fontWeight: '600'}}>FONT WEIGHT 600</Text>
        <Text style={{fontWeight: '500'}}>FONT WEIGHT 500</Text>
        <Text style={{fontWeight: '400'}}>FONT WEIGHT 400</Text>
        <Text style={{fontWeight: '300'}}>FONT WEIGHT 300</Text>
        <Text style={{fontWeight: '200'}}>FONT WEIGHT 200</Text>
        <Text style={{fontWeight: '100'}}>FONT WEIGHT 100</Text>
      </SafeAreaView>
  );
};

export default App;
```
3a. Run the app in an emulator or on device
4a. Output: https://imgur.com/VEpgKzC

<details>
  <summary>react-native info</summary>
  <code><pre>
  info Fetching system and libraries information...
  System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 1.28 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.60.3 => 0.60.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
    </pre></code>
</details>

**THEN**

1b. `react-native init AwesomeProject2 --version 0.59.9`
2b. Use code from above in App.js
3b. Run the app in an emulator or on device
4b. Output: https://imgur.com/ZW9hZGU

<details>
  <summary>react-native info</summary>
  <code><pre>
  info 
    React Native Environment Info:
      System:
        OS: macOS 10.14.5
        CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
        Memory: 1.34 GB / 16.00 GB
        Shell: 3.2.57 - /bin/bash
      Binaries:
        Node: 12.2.0 - /usr/local/bin/node
        Yarn: 1.15.2 - /usr/local/bin/yarn
        npm: 6.10.0 - /usr/local/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
      SDKs:
        iOS SDK:
          Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
        Android SDK:
          API Levels: 23, 28
          Build Tools: 28.0.3
          System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      IDEs:
        Android Studio: 3.4 AI-183.6156.11.34.5692245
        Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
      npmPackages:
        react: 16.8.3 => 16.8.3 
        react-native: 0.59.9 => 0.59.9 
      npmGlobalPackages:
        create-react-native-app: 1.0.0
        react-native-cli: 2.0.1
  </pre></code>
</details>

Describe what you expected to happen:

When an unsupported font weight is higher than a supported, non standard font weight, the default should be picked as the fatter one not the skinny one.

Snack, code example, or link to a repository:

**Comment by RobinCsl** [comment]
It looks like this originates from this commit https://github.com/facebook/react-native/commit/3915c0fa6178fbb8aa9b8bd54881cfdbde8fde70#diff-d4141c42bc6789637b6fdc7754ec1dd9

In particular, the commit message says: 
> This change might break texts where fontWeight use improperly, because this PR removes conversion of values above 500 to BOLD and below 500 to normal.

**Comment by iamacup** [comment]
I don't really know if this is an issue or not then - this is the code i am using to 'fix' the fonts in my code base, this does not apply if you are using custom fonts.

**iOS:**
<img width="391" alt="ios" src="https://user-images.githubusercontent.com/12894620/62011576-03d21b00-b172-11e9-92fb-bd02ee54cab9.png">

**Android:**
<img width="374" alt="android" src="https://user-images.githubusercontent.com/12894620/62011579-06347500-b172-11e9-8cdd-f64ee91f9263.png">

```
const oldRender = Text.render;

const settings = [{
    fontFamily: 'sans-serif-thin',
    fontWeight: 'normal',
  }, {
    fontFamily: 'sans-serif-light',
    fontWeight: 'normal',
  }, {
    fontFamily: 'sans-serif',
    fontWeight: 'normal',
  }, {
    fontFamily: 'sans-serif-medium',
    fontWeight: 'normal',
  }, {
    fontFamily: 'sans-serif',
    fontWeight: 'bold',
  }, {
    fontFamily: 'sans-serif-medium',
    fontWeight: 'bold',
  }
];

const defaultIndex = 2;

Text.render = (...args) => {
  const origin = oldRender.call(this, ...args);

  if (Platform.OS === 'android') {
    let useIndex = defaultIndex;

    if (typeof origin.props.style !== 'undefined' && typeof origin.props.style.fontWeight !== 'undefined') {
      const { fontWeight } = origin.props.style;

      if (fontWeight === '100' || fontWeight === '200' || fontWeight === '300') {
        useIndex = 0;
      } else if (fontWeight === '400') {
        useIndex = 1;
      } else if (fontWeight === '500' || fontWeight === 'normal') {
        useIndex = 2;
      } else if (fontWeight === '600') {
        useIndex = 3;
      } else if (fontWeight === '700' || fontWeight === 'bold') {
        useIndex = 4;
      } else if (fontWeight === '800' || fontWeight === '900') {
        useIndex = 5;
      }
    }

    return React.cloneElement(origin, {
      style: [settings[defaultIndex], origin.props.style, settings[useIndex]],
    });
  }

  return origin;
};
```

**Comment by gaodeng** [comment]
why this issue is closed?

**Comment by steventilator** [comment]
Shouldn't this issue be open? It's definitely not desired behaviour if a fontWeight of '900' defaults to Roboto Regular on Android. This essentially means I have to either use the hack mentioned by @iamacup or use a custom font that includes all the font weights I need.

**Comment by jorgemarrero** [comment]
> I don't really know if this is an issue or not then - this is the code i am using to 'fix' the fonts in my code base, this does not apply if you are using custom fonts and it is not using the roboto default which does not seem to support very many font weights out of the box.
> 
> **iOS:**
> <img alt="ios" width="391" src="https://user-images.githubusercontent.com/12894620/62011576-03d21b00-b172-11e9-92fb-bd02ee54cab9.png">
> 
> **Android:**
> <img alt="android" width="374" src="https://user-images.githubusercontent.com/12894620/62011579-06347500-b172-11e9-8cdd-f64ee91f9263.png">
> 
> ```
> const oldRender = Text.render;
> 
> const settings = [{
>     fontFamily: 'sans-serif-thin',
>     fontWeight: 'normal',
>   }, {
>     fontFamily: 'sans-serif-light',
>     fontWeight: 'normal',
>   }, {
>     fontFamily: 'sans-serif',
>     fontWeight: 'normal',
>   }, {
>     fontFamily: 'sans-serif-medium',
>     fontWeight: 'normal',
>   }, {
>     fontFamily: 'sans-serif',
>     fontWeight: 'bold',
>   }, {
>     fontFamily: 'sans-serif-medium',
>     fontWeight: 'bold',
>   }
> ];
> 
> const defaultIndex = 2;
> 
> Text.render = (...args) => {
>   const origin = oldRender.call(this, ...args);
> 
>   if (Platform.OS === 'android') {
>     let useIndex = defaultIndex;
> 
>     if (typeof origin.props.style !== 'undefined' && typeof origin.props.style.fontWeight !== 'undefined') {
>       const { fontWeight } = origin.props.style;
> 
>       if (fontWeight === '100' || fontWeight === '200' || fontWeight === '300') {
>         useIndex = 0;
>       } else if (fontWeight === '400') {
>         useIndex = 1;
>       } else if (fontWeight === '500' || fontWeight === 'normal') {
>         useIndex = 2;
>       } else if (fontWeight === '600') {
>         useIndex = 3;
>       } else if (fontWeight === '700' || fontWeight === 'bold') {
>         useIndex = 4;
>       } else if (fontWeight === '800' || fontWeight === '900') {
>         useIndex = 5;
>       }
>     }
> 
>     return React.cloneElement(origin, {
>       style: [settings[defaultIndex], origin.props.style, settings[useIndex]],
>     });
>   }
> 
>   return origin;
> };
> ```

@iamacup 
Could you explain a bit more about your solution?

**Comment by gaodeng** [comment]
+1

> Shouldn't this issue be open? It's definitely not desired behaviour if a fontWeight of '900' defaults to Roboto Regular on Android. This essentially means I have to either use the hack mentioned by @iamacup or use a custom font that includes all the font weights I need.

**Comment by jacobcabantomski-ct** [comment]
@iamacup Could you re-open this issue?

**Comment by iamacup** [comment]
Done :)

**Comment by jacobcabantomski-ct** [comment]
@jorgemasta His solution is simulating the previous font weight rendering on android. I ended up using his solution to do something similar in our code base for our custom text component.

```javascript
// @flow
import * as React from 'react';
import { StyleSheet, Text as RNText, Platform } from 'react-native';

type Props = {|
    ...
    style: {} | number | $ReadOnlyArray<?{} | ?number | null>,
    title: ?boolean,
    medium: ?boolean,
    italic?: ?boolean,
|};

const styles = StyleSheet.create({
	...
    medium: { fontWeight: '500' },
	androidMedium: {
		fontFamily: 'Roboto-Medium',
		fontWeight: '500',
	},
	roboto100: {
		fontFamily: 'Roboto-Thin',
	},
	roboto100Italic: {
		fontFamily: 'Roboto-ThinItalic',
	},
	roboto300: {
		fontFamily: 'Roboto-Light',
	},
	roboto300Italic: {
		fontFamily: 'Roboto-LightItalic',
	},
	roboto400: {
		fontFamily: 'Roboto-Regular',
	},
	roboto400Italic: {
		fontFamily: 'Roboto-Italic',
	},
	roboto500: {
		fontFamily: 'Roboto-Medium',
	},
	roboto500Italic: {
		fontFamily: 'Roboto-MediumItalic',
	},
	roboto700: {
		fontFamily: 'Roboto-Bold',
	},
	roboto700Italic: {
		fontFamily: 'Roboto-BoldItalic',
	},
	roboto900: {
		fontFamily: 'Roboto-Black',
	},
	roboto900Italic: {
		fontFamily: 'Roboto-BlackItalic',
	},
});

...

const androidGetFontWeightStyles = ({
	title,
	medium,
	italic,
	style,
}: Props): {} => {
	if (title || medium) {
		return styles.androidMedium;
	}

	// $FlowFixMe
	if (style && style.fontWeight !== undefined) {
		// $FlowFixMe
		const isItalic = italic || style.fontStyle === 'italic';
		const fontFamilyStyle =
			styles[`roboto${style.fontWeight}${isItalic ? 'Italic' : ''}`];
		if (fontFamilyStyle) {
			return fontFamilyStyle;
		}
	}

	return {};
};

const getFontWeightStyles = (props: Props): {} => {
	if (Platform.OS === 'android') {
		return androidGetFontWeightStyles(props);
	}

	if (props.title || props.medium) {
		return styles.medium;
	}

	return {};
};

export default function Text(props: Props) {
    ...

	const textStyles = [
		...
		getFontWeightStyles(props),
	];
    
    ...
    
	return (
		<RNText style={textStyles}>
			...
		</RNText>
	);
}

...

```

**Comment by dulmandakh** [comment]
I introduced the change to add support for other font weights natively and fix parity with iOS. Custom font weight support wasn't available when RN emerged, but added later in SDK 25 or 26.

**Comment by aelesia** [comment]
I wrote a package to handle mapping of custom fonts (eg. Roboto-Light, Roboto-Black) to fontWeights heavily modified from [jacobcabantomski-ct's code](https://github.com/facebook/react-native/issues/25696#issuecomment-553091605).

[https://www.npmjs.com/package/react-native-font-weight](react-native-font-weight alpha)

**Comment by gaodeng** [comment]
?

**Comment by leolusoli** [comment]
has it been fixed in RN 0.62.0?

**Comment by StagasaurusRex** [comment]
Still an issue in 0.62.0

**Comment by excitedcat** [comment]
Same issue

**Comment by fabriziobertoglio1987** [comment]
I quote https://github.com/facebook/react-native/pull/25341

>I found that on Android we only support 2 fontWeight options, either normal or bold, even developer can set any numeric value. But iOS supports all possible numeric values. This PR tries to add support for all possible numeric values on Android, **even if it's supported only on Android P(28) and above**.

I should write a Pull Request to re-enable to old behaviour on Android API < 28 in [ReactBaseTextShadowNode](https://github.com/dulmandakh/react-native/blob/fb6cf2552a0ab19d4e96d7d3a586de36c792c1a4/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java#L487-L497)

```java
  @ReactProp(name = ViewProps.FONT_WEIGHT)
  public void setFontWeight(@Nullable String fontWeightString) {
    int fontWeightNumeric =
        fontWeightString != null ? parseNumericFontWeight(fontWeightString) : -1;
    int fontWeight = UNSET;
    if (fontWeightNumeric >= 500 || "bold".equals(fontWeightString)) {
      fontWeight = Typeface.BOLD;
    } else if ("normal".equals(fontWeightString)
        || (fontWeightNumeric != -1 && fontWeightNumeric < 500)) {
      fontWeight = Typeface.NORMAL;
    }
```

**Comment by fabriziobertoglio1987** [comment]
@iamacup

I don't understand your sentence below. Do you believe that I can present a pull request with such a change in behaviour? 

>**Describe what you expected to happen**:
>When an unsupported font weight is higher than a supported, non standard font weight, the default should be picked as the fatter one not the skinny one.

I think you should close this issue in favour of https://github.com/facebook/react-native/issues/28854. Your requirement is not clear.

I quote issue https://github.com/facebook/react-native/issues/28854

>Expected Results
>font weight values should change font effect in android sdk 28 and above.
Expected result should look like this

<img src="https://user-images.githubusercontent.com/24992535/84390507-fc83f680-abf7-11ea-838d-c9c359d1dcbf.png" width="250" />

I quote https://github.com/facebook/react-native/issues/26193#issuecomment-525028689

>It's known issue due to Android limitations. Only way to use custom font weights is to create a custom font.
>Android added support changing font weights programmatically, but won't work on older versions.

My pull request should fix this behaviour for Android Pie API 28.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/b4c13929e2eeb2a697978b0d55f10139272326e3/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTypefaceUtils.java#L110

Publishing Pull Request Tonight

**Comment by kangfenmao** [comment]
Not fixed

**Comment by mrmarktyy** [comment]
Still not fixed

**Comment by nimabrownlee** [comment]
React native is great but its things like this that just makes it feel unfinished. 2 years has passed and it still isn't fixed. The problem is that it worked with older RN versions and now it's broken.

**Comment by dulmandakh** [comment]
Why would developer depend or specify non-existing font weight. I would rather offer consistent UX by specifying font weights explicitly

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29117 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by MauriceArikoglu** [comment]
bump. still having issues with 64.0...

**Comment by t3hfx** [comment]
I've managed a way to fix it, so go to /android/app/main/assets/fonts/ and rename all the fonts from: 'font-regular.ttf' to 'font-400.ttf' and rename all the fonts according to the table with font weights
Then just create a component where you can pass a font weight and just handle it there as a style to text
If Platform.OS === 'ios' ? {fontWeight: fontWeightFromProps} : {fontWeight: `font-${fontWeightFromProps}`} and don't use normal or bold as font weight, just numbers.

**Comment by MauriceArikoglu** [comment]
> I've managed a way to fix it, so go to /android/app/main/assets/fonts/ and rename all the fonts from: 'font-regular.ttf' to 'font-400.ttf' and rename all the fonts according to the table with font weights
> Then just create a component where you can pass a font weight and just handle it there as a style to text
> `` Platform.OS === 'ios' ? {fontWeight: fontWeightFromProps} : {fontFamily: `font-${fontWeightFromProps}`} `` and don't use normal or bold as font weight, just numbers.

Not really a fix, more a workaround. 
Also doesn't work if you only have one [variable font](https://docs.microsoft.com/de-de/typography/develop/font-variations).

This needs a real fix from the framework vendor's side. Especially considering this worked before.

**Comment by SurajMDurgad** [comment]
Any idea when this will be merged?

**Comment by liamjones** [comment]
@SurajMDurgad it already was in RN 0.66 (see the tags on the linked commit)

**Comment by SurajMDurgad** [comment]
But I just tested it on 0.66.3, it still doesn't work, it only works for `fontWeight: '700'`. @liamjones

**Comment by gabk17** [comment]
2 years later, still not fixed
