### ISSUE TITLE
[60.3] fetch issue

### ISSUE THREAD

**Issue by MasoudAlali** [facebook/react-native#25701]
React Native version:
0.60.3

## Steps To Reproduce
1. upgrade react native to 0.60.3 and clean node modules and install it again
2. send a request with fetch

there will be error like this:
unexpected token o in json at position 1

and I investigated for issue and it happens because in whatwg-fetch library 
in line 492 `support.blob` will be true and the response from xhr will be Blob
so in fetch `response.json()` will fail because response is Blob not stringified json

there are some hotfixes, but I don't know exact solution for this

**Comment by kbrandwijk** [comment]
This seems rather major, with basic `fetch` functionality just being completely broken after spending a lot of time on the 0.60 upgrade. Looking forward to an ETA on this.
In the meantime, I'd also take a hotfix, I haven't been able to find one yet.

**Comment by MasoudAlali** [comment]
> This seems rather major, with basic `fetch` functionality just being completely broken after spending a lot of time on the 0.60 upgrade. Looking forward to an ETA on this.
> In the meantime, I'd also take a hotfix, I haven't been able to find one yet.

you can somehow disable blob support in your project, because in `whatwg-fetch` it's checking support.blob :)
it's not good one but you can temporary do `global.Blob = ""` in your init

**Comment by kennym** [comment]
Experiencing the same problem in 0.60.4

@lklepner

**Comment by bockc** [comment]
just updated to RN 0.60.4, I can confirm that I receive a blob when I used to receive a stringified json before. Fetch is unusable in its current state, thus making RN 0.60.4 unusable aswell. I will wait for a fix

**Comment by asurare** [comment]
Same issue for me on RN 0.60.4 as well. Did not find any viable solution yet.

**Comment by kbrandwijk** [comment]
I tried the `global.Blob` workaround, and it seemed to work fine in debug mode, but somehow does not work in release mode...

**Comment by RageBill** [comment]
I encountered the same problem in my project.

For some reason, I managed to fix this (and I still cannot explain what happened) by changing some dependencies and clean build the app again.

Here's the dependencies I changed:
`@react-native-community/async-storage 1.6.1 --> 1.5.1`
`react-native-device-info 2.3.0 --> 2.2.2`
`react-native-linear-gradient 2.5.6 --> 2.5.5`
`@babel/plugin-proposal-decorators 7.4.4 --> 7.2.0`
`react-test-renderer 16.8.6 --> removed`

I don't exactly know what one fixed my problem, but it works for me now. Hope this helps whoever is struggling with this problem.

My `react-native` version is `0.60.4` and `react` version is `16.8.6`.

**Comment by rshaikhcornerstone** [comment]
I am getting just this warning 
{"line":"24531", "coloumn":"31", "sourceURL":"http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"}

**Comment by kennym** [comment]
We are able to reproduce this issue within the context of `@react-native-community/async-storage`. We have posted a reproducible test scenario here: https://github.com/react-native-community/async-storage/issues/174

We are not entirely sure if this is something that has to be fixed on the react-native or on the async-storage side, but this defect definitely only happens in 0.60.4, which is why I'm linking this thread.

**Comment by kennym** [comment]
For us, it is an issue with 'Network Inspect' in the debugger: https://github.com/jhen0409/react-native-debugger/issues/365

Disabling that fixes this issue.

**Comment by kbrandwijk** [comment]
@kennym That's a workaround _at best_, and it definitely doesn't _fix_ this issue.

**Comment by briangonzalez** [comment]
@kbrandwijk Have you been able to find a fix?

**Comment by macnibblet** [comment]
Anyone had any success here?

**Comment by bockc** [comment]
> I encountered the same problem in my project.
> 
> For some reason, I managed to fix this (and I still cannot explain what happened) by downgrading some dependencies and clean build the app again.
> 
> Here's the dependencies I changed:
> `@react-native-community/async-storage 1.6.1 --> 1.5.1`
> `react-native-device-info 2.3.0 --> 2.2.2`
> `react-native-linear-gradient 2.5.6 --> 2.5.5`
> `@babel/plugin-proposal-decorators 7.4.4 --> 7.2.0`
> `react-test-renderer 16.8.6 --> removed`
> 
> I don't exactly know which one fixed my problem, but it works for me now. Hope this helps whoever is struggling with this problem.
> 
> My `react-native` version is `0.60.4` and `react` version is `16.8.6`.

RageBill states this works. I haven't tried it yet, as I don't consider downgrading packages being a fix at all. If you have no other choice and absolutely have to use RN 0.60, you may give it a shot.

**Comment by kbrandwijk** [comment]
No, just no. This is a breaking issue, and should be treated as such. This has been going on for almost a month now, I guess everyone just knows you have no way out once you're heavily invested in using RN...

**Comment by kozillla** [comment]
Was having the same issue, in my case, I fixed it by adding ```android:usesCleartextTraffic="true"``` to ```AndroidManifest.xml``` , more info https://github.com/facebook/react-native/issues/24627

hope it helps !

**Comment by WoodyWoodsta** [comment]
XHR returning a Blob is not the issue. It's the fact that the check for whether or not the response is a `Blob` [here](https://github.com/github/fetch/blob/37d10362687492868548c4d70c5c12e4a671771e/fetch.js#L217) is trivially failing. It appears that `xhr` is using its own `Blob` prototype compared to the globally defined `Blob`. I wouldn't have a clue on how to resolve.

**Comment by RikSchefferOberon** [comment]
I found a workaround by disable Blob support in fetch:
edit node_modules/whatwg-fetch/fetch.js
and node_modules/react-native/node_modules/whatwg-fetch/fetch.js
and node_modules/react-native/node_modules/whatwg-fetch/dist/fetch.umd.js

at the top of the files edit the support variable:
replace:
var support = {
  searchParams: 'URLSearchParams' in self,
  iterable: 'Symbol' in self && 'iterator' in Symbol,
  blob:
    'FileReader' in self &&
    'Blob' in self &&
    (function() {
      try {
        new Blob()
        return true
      } catch (e) {
        return false
      }
    })(),
  formData: 'FormData' in self,
  arrayBuffer: 'ArrayBuffer' in self
}

with:
var support = {
  searchParams: 'URLSearchParams' in self,
  iterable: 'Symbol' in self && 'iterator' in Symbol,
  blob: false,
  formData: 'FormData' in self,
  arrayBuffer: 'ArrayBuffer' in self
}

**Comment by bockc** [comment]
This is absolutely not a workaround, most especially if you need to work with blobs at some point in your application.
I understand that facebook's team must have a ton of work to do, but this is a very major issue and has been there for almost two months now, we need this to be fixed in order to upgrade to RN 0.60.
Hope they release 0.60.5 with a fix for this very soon :|

**Comment by WoodyWoodsta** [comment]
I totally agree. If you are going to patch `whatwg-fetch`, at least make the change to [this line](https://github.com/github/fetch/blob/37d10362687492868548c4d70c5c12e4a671771e/fetch.js#L217) to fix the usage of Blobs. To simply override Blob support is not constructive in the slightest.

**Comment by RikSchefferOberon** [comment]
sadly 0.60.5 did not fix this for me

**Comment by dwoniu** [comment]
"react": "16.8.3",
 "react-native": "0.59.9",

app 
// global.XMLHttpRequest = global.originalXMLHttpRequest
//   ? global.originalXMLHttpRequest
//   : global.XMLHttpRequest
// global.FormData = global.originalFormData
//   ? global.originalFormData
//   : global.FormData

fetch
  // if (window.__FETCH_SUPPORT__) {
  //   // it's RNDebugger only to have
  //   window.__FETCH_SUPPORT__.blob = false
  // } else {
  //   /*
  //    * Set __FETCH_SUPPORT__ to false is just work for `fetch`.
  //    * If you're using another way you can just use the native Blob and remove the `else` statement
  //    */
  //   global.Blob = global.originalBlob ? global.originalBlob : global.Blob;
  //   global.FileReader = global.originalFileReader
  //     ? global.originalFileReader
  //     : global.FileReader
  // }

then 

Enable Network Inspect 

it seemed to work fine for me

**Comment by asurare** [comment]
@dwoniu It seems to me that this is an issue related to react-native@0.60.X+ versions only..

**Comment by kiran-mantana** [comment]
I upgraded my App to 0.60.0, I get blob as response, any update on the isssue?

We are planning app for production, There are some workarounds can we do the work arounds and move to production?

**Comment by kbrandwijk** [comment]
No, thanks to unattended issues like this, 0.60.x is NOT suitable for production. It is beyond me why these things are abandoned like this.

**Comment by roots-ai** [comment]
Hi!
Promise object can be handled with...

```
.then((response) => response.json())
.then((responseJson) => {
   //HANDLE RESPONSE HERE
}
```

**Comment by hunzalashakeel1996** [comment]
does anyone found a solution about this issue please guide ?

**Comment by skurgansky-sugarcrm** [comment]
try newer version of react-native-devtools
0.9.14 for example

**Comment by hunzalashakeel1996** [comment]
@skurgansky-sugarcrm  you mean to say react-devtools this npm ?

**Comment by hunzalashakeel1996** [comment]
@skurgansky-sugarcrm i am using this solution global.Blob = null and it works on both debug and release build. if this solution is fine or have some setbacks ?

**Comment by skurgansky-sugarcrm** [comment]
i mean remote dev tool app.
btw when you upgraded RN did you removed all manually linked native modules?
maybe there is  a problem. I had same issues.

**Comment by hunzalashakeel1996** [comment]
@skurgansky-sugarcrm  yeah i did actually i create app from scratch. that same code works fine on react native 0.59 but give this blob type response in 0.60.X. I use this global.blob = null trick and it works. but now i am confuse it is wrong for future or it's fine

**Comment by skurgansky-sugarcrm** [comment]
its wrong. fetch works fine.

**Comment by skurgansky-sugarcrm** [comment]
When i had this issue i searched for a solution and found old same issues for RN 0.22.x version. So this is most probably configuration problem.

**Comment by hunzalashakeel1996** [comment]
`//get driver child from db
export const login = number => {
  return dispatch => {
    return new Promise(async (resolve, reject) => {
      dispatch(uiStartLoading());
      fetch(`${url}/api/login`, {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ number: number })
      })
        .then(res => {
          dispatch(uiStopLoading());
          resolve(res)
        })
        .catch(err => {
          dispatch(uiStopLoading());
          Alert.alert("Error", `Something went wrong \n ${err}`)
        })
    });
  };
};`

this is the code which i using in fetch. In my 0.59 version this return me object with status and bodyInit which has my data in object form but now there is some blob text in bodyInit

**Comment by hunzalashakeel1996** [comment]
@skurgansky-sugarcrm 

//get driver child from db
export const login = number => {
  return dispatch => { 
    return new Promise(async (resolve, reject) => {
      dispatch(uiStartLoading());
      fetch(`${url}/api/login`, {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ number: number })
      })
        .then(res => {
          dispatch(uiStopLoading());
          resolve(res)
        })
        .catch(err => {
          dispatch(uiStopLoading());
          Alert.alert("Error", `Something went wrong \n ${err}`)
        })
    });
  };
};

this is the code which i using in fetch. In my 0.59 version this return me object with status and bodyInit which has my data in object form but now there is some blob text in bodyInit

**Comment by skurgansky-sugarcrm** [comment]
yes i know. did you migrate from 0.59 to 0.60.x ? you might have wrong migration

**Comment by skurgansky-sugarcrm** [comment]
difference between 0.60.x and 0.5x.x is that 0.60.x have autolinking feature for native modules (Fetch for example)
there are differences in ios/Podfile and in xcode xcodeproj linking Libraries section.

**Comment by skurgansky-sugarcrm** [comment]
>  i create new app from scratch with react native 0.60.5 just copying my javascript code to it,

i did the same. launched simple http server on express and checked. It worked in my case. So i started to look for configuration issues. I updated [react-native-devtools](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.9.14) and removed manual links for native-modules. Since then I haven't seen this issue.

**Comment by kbrandwijk** [comment]
@skurgansky-sugarcrm Don't spread fake news on a confirmed issue. This is not about using devtools, and it's also not about migration, and it definitely has nothing to do with autolinking.
As @hunzalashakeel1996 and others have mentioned. This happens on creating a new app from scratch as well, which pretty much rules out all other options anyway.

**Comment by hunzalashakeel1996** [comment]
Exactly. And if someone find solution about that please mention me on your comment.

**Comment by skurgansky-sugarcrm** [comment]
it's your own problems not RN. see this link [Asked 3 years, 4 months ago](https://stackoverflow.com/questions/36820390/react-native-fetch-returns-blob-instead-of-json-after-upgrading-to-0-24-1)

you think such a big issue could exist since 0.24.1 ? really ?
@kbrandwijk I see you like accusing some1 without any proof

**Comment by skurgansky-sugarcrm** [comment]
related links
https://github.com/jhen0409/react-native-debugger/issues/365 + referenced inside

**Comment by RageBill** [comment]
I don't see why the same issue could not appear again after a lot of version changes.
I would say the issue is not "exists since 0.24.1", but rather "reappears after many versions".
Same error message does not necessarily entails the same bug in the same position of the codebase as well.

**Comment by WoodyWoodsta** [comment]
The ticket has been labelled as a bug, and therefore has been found to be one. What's the point in making claims about similar symptoms? We're better software developers than that! It's clearly an issue, based on the number of reactions on the ticket, and it's the first time that I have come across the symptoms. Defending it by pulling out an issue from 3 years ago does nothing but create confusion and perhaps embarrassment on your part too 😄

**Comment by Mexxerio** [comment]
Same issue on 0.60.5

setting `global.Blob = null` is not an option for me because other aspects of my app depend on it.

So I replaced all uses of `fetch` with a third party library for now. But this is most definitely a react-native bug and should be fixed as soon as possible.

**Comment by sunnylqm** [comment]
ping @janicduplessis

**Comment by YanYuanFE** [comment]
node_modules/whatwg-fetch/dist/fetch.umd.js

```
if ('responseType' in xhr && support.blob) {
        // xhr.responseType = 'blob';
}
```

**Comment by k-varma** [comment]
Is this issue solved in 0.61.0

**Comment by SiddhantJ19** [comment]
Why is this issue closed? I can't find an answer to this issue.
Please help

**Comment by bockc** [comment]
@SiddhantJ19 this issue is not closed, only the one in which it has been referenced is closed. :)

We currently have trouble upgrading our project to RN0.61, but hopefully this will fix this issue. We will keep you posted when we know more.

**Comment by saboosrishti** [comment]
I am facing something really strange with react native debugger, I can see the result of fetch calls only when the network inspect mode is enabled, if I disable the network inspect mode I don't get any response and get an error "Unhandled promise rejection Network request fail". 
I am using RN - 0.60.3 and react native debugger latest version...
Any leads on this issue will be really appreciated.
Thanks!!!

**Comment by bockc** [comment]
@SiddhantJ19 @k-varma I just finished updating our project to RN0.61 and I confirm that the issue is still here. Maybe this could be a dependency that causes this issue ?

**Comment by SergueyPutilin** [comment]
I have the same problem on rn 0.61.2 when I send a cookie with my fetch call. The call only works when I have RN debugger open and have global.blob set to null.

**Comment by SergueyPutilin** [comment]
I fixed this by using this code in componentDidMount in my app.js before I do any calls.
https://github.com/jhen0409/react-native-debugger/issues/382#issuecomment-544226529

It does seem that this is a dependancy issue (I think). When I commented the line of code that @YanYuanFE mentioned a few comments prior. All of my calls work as intended. 
But this workaround is not a good one since you have to do this every time you delete node_modules.

**Comment by PatelAshish1** [comment]
Using JSON.stringify(data);:

Full Source Code At [Here](https://icetutor.com/question/parsing-json-giving-unexpected-token-o-error/)

**Comment by roots-ai** [comment]
@SergueyPutilin Thanks! This resolves the issue for me.

**Comment by bockc** [comment]
@SergueyPutilin I had the same issue after upgrading to RN0.61. I literally have no clue whatsoever of what happened, but I installed axios as a dependency, tested and still got the same issue. I removed it from my package.json, uninstalled it and everything went perfectly fine after that.

Any reinstallation of node_modules after that went perfectly fine and the problem disappeared. I really don't know, but, it works....

**Comment by Relax594** [comment]
> 
> 
> I am facing something really strange with react native debugger, I can see the result of fetch calls only when the network inspect mode is enabled, if I disable the network inspect mode I don't get any response and get an error "Unhandled promise rejection Network request fail".
> I am using RN - 0.60.3 and react native debugger latest version...
> Any leads on this issue will be really appreciated.
> Thanks!!!

exactly this. Whenever i run the debugger, everything is working fine. When i try to run it my app just freezes while running the fetch.

**Comment by rossjohnsonMP** [comment]
Does anyone have any other workarounds? 

https://github.com/jhen0409/react-native-debugger/issues/382#issuecomment-544226529 - works on simulator and in debug mode but **not on testflight**

**Comment by quanzaiyu** [comment]
the same problem

**Comment by quanzaiyu** [comment]
It seems to be the problem of reaction-native-debugger.

If open debugger mode with reaction-native-debugger, and `GLOBAL.XMLHttpRequest...` in `index.js`  leads to this problem.

Just remove this line:

```js
GLOBAL.XMLHttpRequest = GLOBAL.originalXMLHttpRequest || GLOBAL.XMLHttpRequest
```

see [Network Inspect not working with RN 0.60.0 #365](https://github.com/jhen0409/react-native-debugger/issues/365)

**Comment by qalqi** [comment]
```  
  else if (body && body.constructor && body.constructor.name == 'Blob') {
        this._bodyText = body = body.text()
}
```
Add this condition to https://github.com/github/fetch/blob/7232090c04e1ddefb806910bbd0a756bc8aac2f0/fetch.js#L229

**Comment by Shobson-three29** [comment]
https://github.com/jhen0409/react-native-debugger/issues/365#issuecomment-524345356

I had the exact issue, and i found a solution in the comment that i've linked. my react-native-debugger was on a pretty old version, and upgrading it to the newest version solved the issue. 

without the debugger running at all, i was getting network errors. with the debugger running, i was getting the parsing error. now i can make fetch calls with the debugger running and it works as intended. no other workarounds are needed.

**Comment by jm555jm** [comment]
I solved my problem by adding param 'encoding'
in fetch.js, readBlobAsText does not specify the encoding, 
and response.text() will goto undefined, so response.json() will throw error.
(response.json is equal to JSON.parse(result of response.text()))
```
function readBlobAsText(blob, encoding) {
  var reader = new FileReader();
  var promise = fileReaderReady(reader);
  reader.readAsText(blob, encoding);
  return promise
}
```

**Comment by quentingirard** [comment]
Any update ?

**Comment by garrettjoecox** [comment]
For what it's worth downgrading `@react-native-community/async-storage` from 1.6.1 to 1.5.1 fixed this in our case, absolutely clueless as to why. 🤦

**Comment by jasperkuperus** [comment]
ping @hramos

**Comment by jasperkuperus** [comment]
> ping @hramos I can confirm this is still an issue on `0.62.2`

Sorry about that ping. So, apparently, if you're using RN Debugger that's older than 0.11 and RN that's 0.61+, then you'll need to upgrade your RN Debugger. See here about compatibility:

https://github.com/jhen0409/react-native-debugger#notice-react-native-compatibility

Then there is no need to add any of the mentioned hacks to your codebase.

**Comment by asurare** [comment]
Can this issue be closed @MasoudAlali

**Comment by didrikg** [comment]
I still have this issue with RN 0.63.4 and React Native Debugger 0.11.5

![image](https://user-images.githubusercontent.com/10706579/109517767-e67dd500-7aa9-11eb-91eb-2c464113bb20.png)

**Comment by pavel-stryber** [comment]
This helped but typescript is really unhappy with this.

[](https://github.com/jhen0409/react-native-debugger/issues/382#issuecomment-646874107)

**Comment by perry-mitchell** [comment]
[This](https://github.com/jhen0409/react-native-debugger/issues/382#issuecomment-646874107) helped us on RN 0.66.1. Can't believe this is still an issue :confused:
