### ISSUE TITLE
Android auto-linking broken in 0.60.4 - null is not an object evaluating RNFSManager

### ISSUE THREAD

**Issue by adamkoch** [facebook/react-native#25805]
When creating a fresh RN project using 0.60.4 then running it on Android I see the following error. Usually this would mean an issue with linking but my understanding was that the new auto-linking should take care of this.

Running on iOS works fine (after pod install).

`null is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')`
![Screenshot_1563962589](https://user-images.githubusercontent.com/869261/61785174-77141e00-ae4e-11e9-8d51-8f6475778fea.png)

React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 22.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Start an Android emulator or connect an Android device via USB
2. react-native init AwesomeProject
3. cd AwesomeProject && react-native run-android

Repros 100% for me.

Describe what you expected to happen:
Template app should start correctly.

**Comment by EgidioCaprino** [comment]
We have the same problem with all the libraries that should now be linked automatically.

**Comment by dulmandakh** [comment]
Please make sure you linked the module correctly. And please file an issue https://github.com/itinance/react-native-fs to request auto linking support if it doesn't exists.

**Comment by adamkoch** [comment]
@dulmandakh The issue report is for auto-linking, so it shouldn't require any manual linking.

As per my comment in the original report:
"Usually this would mean an issue with linking but my understanding was that the new auto-linking should take care of this."

Also - "Running on iOS works fine (after pod install)." so auto-linking is working fine with react-native-fs on iOS and shouldn't require any additional steps on Android.

**Comment by adamkoch** [comment]
Ah. It appears my metro bundler had cached these required libs from my other projects. Clearing my cache and re-running fixed things up. Not sure why a fresh project would not start it's build separate/fresh from other projects though.

**Comment by dulmandakh** [comment]
@adamkoch FYI, auto-linking is CLI  feature, not RN core. Is it correct that the issue is resolved

**Comment by adamkoch** [comment]
Got it. Yes it is resolved. I guess the issue is with the CLI not clearing cache or sharing cache between projects on the local machine. If others run into this, you should clear your RN caches to fix.

**Comment by fostahgix** [comment]
@adamkoch How did you clear your RN cache? I am running into this same issue with 0.60.5 and tried `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache` which didn't resolve the issue.

**Comment by adamkoch** [comment]
@fostahgix I basically ran the same commands to clear everything I could. What I did have to do was run the commands in other RN projects I had on my machine (I guess they were sharing caching dirs). My main project (which used RNFSManager), was somehow contaminating any other projects I had on my machine, so even when creating a fresh new project in a separate dir, it was still throwing this error despite a new project not using RNFSManager.
