### ISSUE TITLE
React-native run-android in loop  (Starting JS server ... )

### ISSUE THREAD

**Issue by EvertonCosmo** [facebook/react-native#26097]
After starting a new project and trying to test it, it starts js serving. In this case I used the test app, but I have an app in the same situation

React Native version:
System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz
    Memory: 230.84 MB / 3.56 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 11.15.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.10.3 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 22, 25, 27, 28, 29
      Build Tools: 28.0.3, 29.0.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1.type react-native init 
2.type react-native run-android (with devices or emulator connected)

![Screenshot from 2019-08-18 09-26-50](https://user-images.githubusercontent.com/12981463/63224451-d1c53f00-c19a-11e9-90ed-13e4f66d733f.png)

**Comment by craicoverflow** [comment]
I'm also facing this issue.

**Comment by creativemind1** [comment]
same here

**Comment by nicolaslima321** [comment]
i'm with same problem, i tried to reinstall nodejs and react-native but no success

**Comment by nicolaslima321** [comment]
![image](https://user-images.githubusercontent.com/23743072/63273612-ae6ec280-c274-11e9-91fe-ebe2f728441c.png)

Using Fedora 30

**Comment by aismaniotto** [comment]
Same problem on Manjaro. :(

**Comment by ogiansouza** [comment]
It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

**Comment by aismaniotto** [comment]
Thank you very much. That's works as a workaround. Waiting for final solution. And again, thank you!!

**Comment by EvertonCosmo** [comment]
@ogiansouza Thanks a lot

**Comment by efranelas** [comment]
> It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

Works perfectly, thanks!

**Comment by vkasraj** [comment]
I am also facing this issue.

### React Native
```
react-native-cli: 2.0.1
react-native: 0.61.2
```

### Kernel
```
Linux hello-pc 5.2.21-1-MANJARO #1 SMP PREEMPT Sat Oct 12 11:09:56 UTC 2019 x86_64 GNU/Linux
```

### OS
```
Description:    Manjaro Linux
Release:        18.1.1
Codename:       Juhraya
```

> It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

Though this solved my issue. But many of the devs did not want to run two commands to run the project.

**Comment by siddhi-sandy** [comment]
Any fix yet?

**Comment by franjorub** [comment]
same issue in openSuSe tumbleweed

**Comment by Ianito** [comment]
Same here.

Manjaro 18.1.4
Kernel: x86_64 Linux 5.4.2-1-MANJARO

**Comment by cassioalmeidas** [comment]
Temporary fix:

`REACT_TERMINAL=<your terminal> react-native run-android`

in my case with archlinux + xfce4:

`REACT_TERMINAL=xfce4-terminal react-native run-android`

or puts in your .bashrc:

`export REACT_TERMINAL=xfce4-terminal`

note: it will use two instances of terminal

**Comment by karansapolia** [comment]
> It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

Wish this is officially resolved soon.

**Comment by albertschulz** [comment]
The issue is caused, because spawning the process to run the Metro Bundler does not return:
https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.ts#L348

This seems to be an issue in the `execa` library, which was introduced by this merge:
https://github.com/react-native-community/cli/pull/601/files

It can be fixed by replacing the call with the previous one:
`spawn('sh', [launchPackagerScript], procConfig);`

**Possible workarounds**, by setting the terminal
* explicitly, using `$ react-native run-android --terminal path/to/terminal`
* implicitly, by setting one of the environment variables `TERM_PROGRAM` or `REACT_TERMINAL`

**Comment by numToStr** [comment]
I hope this issue get resolved quickly for all the linux guys.✌🏻

**Comment by mrsoftware** [comment]
same.

**Comment by mondyfy** [comment]
Stuck in the same issue in manjaro 19.0 Kyria.

**Comment by Rapiz1** [comment]
same.

**Comment by h2ash** [comment]
manjaro 19 kde
same

**Comment by arafatzahan** [comment]
How's this still not fixed? Sad

**Comment by Esemesek** [comment]
Fix for that is already merged in the `cli` - https://github.com/react-native-community/cli/issues/1066. I think we're safe to close this issue.

**Comment by ShivamJoker** [comment]
How this issue is still present in the latest version of RN -_- please fix it

**Comment by Esemesek** [comment]
@ShivamJoker First of all, please stop spamming various repos without giving any additional or helpful information.
Second of all, this issue is about terminal not launching on `Linux` machines, while your issue is connected to `OSX` (https://github.com/react-native-community/cli/issues/1066#issuecomment-610369254). This issue should be fixed in the latest version of `@react-native-community/cli`. Your problem seems to be connected to your local env setup.
@cpojer Can we close this issue as it was already fixed and released in the CLI (https://github.com/react-native-community/cli/pull/1099)

**Comment by BrenoMazieiro** [comment]
**Linux:**
Go to the terminal and type:
`react-native start`

and then in **OTHER** terminal, inside your project folder:
`yarn android`
or
`npm run android`

**Comment by yassinebridi** [comment]
@Esemesek this issues is still occuring, using the lates cli version 2.0.1

**Comment by safaiyeh** [comment]
> @ShivamJoker First of all, please stop spamming various repos without giving any additional or helpful information.
> Second of all, this issue is about terminal not launching on `Linux` machines, while your issue is connected to `OSX` ([react-native-community/cli#1066 (comment)](https://github.com/react-native-community/cli/issues/1066#issuecomment-610369254)). This issue should be fixed in the latest version of `@react-native-community/cli`. Your problem seems to be connected to your local env setup.
> @cpojer Can we close this issue as it was already fixed and released in the CLI ([react-native-community/cli#1099](https://github.com/react-native-community/cli/pull/1099))

Closing, for future CLI issues please file issues at https://github.com/react-native-community/cli

**Comment by jose2007kj** [comment]
> **Linux:**
> Go to the terminal and type:
> `react-native start`
> 
> and then in **OTHER** terminal, inside your project folder:
> `yarn android`
> or
> `npm run android`

thanks this got the issue fixed for me in arch-linux

**Comment by whatdtech** [comment]
Reinstalling android studio with a new emulator or changing the app name in **app.json , build.gradle and android manifest.xml** solved the issue.
