### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callabel module (calling runApplication)

### ISSUE THREAD

**Issue by Hugo-Meiring** [facebook/react-native#26687]
<img width="545" alt="Screenshot 2019-10-02 at 13 35 27" src="https://user-images.githubusercontent.com/5610758/66041369-fe020880-e519-11e9-8616-58da88177c0f.png">

Currently on React Native 0.61.0-rc.3, updating to 0.61.1 causes this issue.

React Native version:

```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 871.19 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Update the package.json values to use latest 0.61.1 (and other latest values pulled for a `react-native init`)
2. Run the project (`yarn && cd ios && pod install && cd .. && yarn start` + `yarn ios`)

Describe what you expected to happen:
The app should be running like on 0.61.0-rc.3. What major changes where made between the release candidate and 0.61.0 (also your website still show 0.60.0 as the latest version). Here is the source code changes between the two:
https://react-native-community.github.io/upgrade-helper/?from=0.61.0-rc.3&to=0.61.1

Snack, code example, screenshot, or link to a repository:

Can't be provided, production and private react-native init application.

**Comment by radko93** [comment]
Unfortunately, this error does not give any feedback on what exactly is wrong.  You need to dig deeper.

**Comment by Hugo-Meiring** [comment]
Here are logs from Xcode:

```019-10-02 14:19:16.269987+0200 libertychat[59943:2042867] TCP Conn 0x60000320ccc0 Failed : error 0:61 [61]
2019-10-02 14:19:16.303 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
2019-10-02 14:19:16.305 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
2019-10-02 14:19:16.311 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[{"app_state":"active"}]'
2019-10-02 14:19:16.313 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 18 and callID 9 for module <unknown>. Args: '[{"app_state":"active"}]'
2019-10-02 14:19:16.314 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 40 and callID 20 for module <unknown>. Args: '[{"app_state":"active"}]'
2019-10-02 14:19:16.317 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[{"app_state":"active"}]'
2019-10-02 14:19:16.318 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 73 and callID 36 for module <unknown>. Args: '[0]'
2019-10-02 14:19:16.319 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 99 and callID 49 for module <unknown>. Args: '[1]'
2019-10-02 14:19:16.320 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 18 and callID 9 for module <unknown>. Args: '[{"app_state":"active"}]'
2019-10-02 14:19:16.322 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 123 and callID 61 for module <unknown>. Args: '[2]'
2019-10-02 14:19:16.323 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 139 and callID 69 for module <unknown>. Args: '[3]'
2019-10-02 14:19:16.323 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 155 and callID 77 for module <unknown>. Args: '[4]'
2019-10-02 14:19:16.324 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 40 and callID 20 for module <unknown>. Args: '[{"app_state":"active"}]'
2019-10-02 14:19:16.327 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 73 and callID 36 for module <unknown>. Args: '[0]'
2019-10-02 14:19:16.329 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 99 and callID 49 for module <unknown>. Args: '[1]'
2019-10-02 14:19:16.330278+0200 libertychat[59943:2042874] [] nw_proxy_resolver_create_parsed_array [C8 proxy pac] Evaluation error: NSURLErrorDomain: -1003
2019-10-02 14:19:16.330 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 171 and callID 85 for module <unknown>. Args: '[5]'
2019-10-02 14:19:16.331 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 187 and callID 93 for module <unknown>. Args: '[6]'
2019-10-02 14:19:16.367066+0200 libertychat[59943:2042874] [] nw_proxy_resolver_create_parsed_array [C10 proxy pac] Evaluation error: NSURLErrorDomain: -1003
2019-10-02 14:19:16.368 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 203 and callID 101 for module <unknown>. Args: '[7]'
2019-10-02 14:19:16.369 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 219 and callID 109 for module <unknown>. Args: '[8]'
2019-10-02 14:19:16.369 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 239 and callID 119 for module <unknown>. Args: '[9]'
2019-10-02 14:19:16.369809+0200 libertychat[59943:2042874] [] nw_proxy_resolver_create_parsed_array [C11 proxy pac] Evaluation error: NSURLErrorDomain: -1003
2019-10-02 14:19:16.376 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 123 and callID 61 for module <unknown>. Args: '[2]'
2019-10-02 14:19:16.381 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 139 and callID 69 for module <unknown>. Args: '[3]'
2019-10-02 14:19:16.385 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 155 and callID 77 for module <unknown>. Args: '[4]'
2019-10-02 14:19:16.390 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 171 and callID 85 for module <unknown>. Args: '[5]'
2019-10-02 14:19:16.393 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 187 and callID 93 for module <unknown>. Args: '[6]'
2019-10-02 14:19:16.393457+0200 libertychat[59943:2042874] [] nw_proxy_resolver_create_parsed_array [C12 proxy pac] Evaluation error: NSURLErrorDomain: -1003
2019-10-02 14:19:16.395 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 255 and callID 127 for module <unknown>. Args: '[10]'
2019-10-02 14:19:16.396 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 203 and callID 101 for module <unknown>. Args: '[7]'
2019-10-02 14:19:16.397 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 271 and callID 135 for module <unknown>. Args: '[11]'
2019-10-02 14:19:16.398 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 287 and callID 143 for module <unknown>. Args: '[12]'
2019-10-02 14:19:16.399 [error][tid:com.facebook.react.JavaScript] Invariant Violation: No callback found with cbID 303 and callID 151 for module <unknown>. Args: '[13]'
2019-10-02 14:19:16.399 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 219 and callID 109 for module <unknown>. Args: '[8]'
2019-10-02 14:19:16.403 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 239 and callID 119 for module <unknown>. Args: '[9]'
2019-10-02 14:19:16.446 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: No callback found with cbID 255 and callID 127 for module <unknown>. Args: '[10]'```

**Comment by Hugo-Meiring** [comment]
Here is are whats if your re-run the app:

<img width="553" alt="Screenshot 2019-10-02 at 14 26 26" src="https://user-images.githubusercontent.com/5610758/66043899-ac10b100-e520-11e9-87b1-ad59b9469bda.png">

**Comment by radko93** [comment]
Did you try to enable the Debug option?

**Comment by Hugo-Meiring** [comment]
Running in Debug mode shows the following. Here is the full log when running it.
<img width="1384" alt="Screenshot 2019-10-02 at 14 30 27" src="https://user-images.githubusercontent.com/5610758/66044207-54267a00-e521-11e9-93be-18527638fe4a.png">

**Comment by Hugo-Meiring** [comment]
<img width="1384" alt="Screenshot 2019-10-02 at 14 30 27" src="https://user-images.githubusercontent.com/5610758/66044480-ee86bd80-e521-11e9-8f07-79232e522cc8.png">

**Comment by m4rcoperuano** [comment]
Getting this same issue but only on Android. Very weird :(

**Comment by Hugo-Meiring** [comment]
> Did you try to enable the Debug option?

Yes, I also tried toggling Fast Refresh off.

**Comment by m4rcoperuano** [comment]
Fixed the issue on my end by double checking that i modified all the files correctly during my RN upgrade, then running `watchman watch-del-all`, and `react-native start --reset-cache`. Then on android, build -> clean. then it worked! sigh

**Comment by Hugo-Meiring** [comment]
Unfortunately, it doesn't work our project (iOS) @m4rcoperuano. Glad it worked for you

**Comment by radko93** [comment]
It's hard to suggest anything without any more details, I would say that you can try commenting out some parts of your code and try until you find something.

**Comment by asielykey** [comment]
> Fixed the issue on my end by double checking that i modified all the files correctly during my RN upgrade, then running `watchman watch-del-all`, and `react-native start --reset-cache`. Then on android, build -> clean. then it worked! sigh

yeah me too, 
react-native start --reset-cache 
worked on my case

**Comment by Hugo-Meiring** [comment]
> It's hard to suggest anything without any more details, I would say that you can try commenting out some parts of your code and try until you find something.

Ok will do. This will take a bit of time. We essentially have 2 apps that are linked so changes have to be done for 4 environments (2x iOS and 2x Android). Will report back if I find a solution to this.

**Comment by eXist-FraGGer** [comment]
@Hugo-Meiring Probably you use modules that were removed from `react-native`.

**Comment by Hugo-Meiring** [comment]
So, unfortunately, I just can't get this working. If I get iOS working, Android breaks. If android is working, iOS breaks. This is just one of the issues that I ping pong between depending on the platform.

I can't spend more time on this as this is cutting into the release schedule. Will go with a temporary fix of splitting iOS and Android between different react versions and making adjustments to the CI/CD pipeline. A very nasty solution but it might be for the better. We can possibly move all our shared code to a separate repo while we analyze our options.

**Comment by gaguirre** [comment]
@Hugo-Meiring I'm facing a similar issue on a monorepo (using lerna and yarn workspaces).
Is this your case too?

I found that everything works ok when I start the app without using anything from an external package. Even the fast refresh works correctly if I comment the LOC related to external packages, start the app and finally un-comment those lines.

**Comment by ralston3** [comment]
Also ran into this (setup below). Took a bit of @m4rcoperuano 's solution and just stopped my simulator and bundler, then removed everything in watchman via `watchman watch-del-all`. Restarted the simulator via `react-native run-ios` and everything works fine.

Setup
```text
react-native-cli: 2.0.1
react-native: 0.61.2
mac OSmojave 10.14.6
```

**Comment by djohnsonkc** [comment]
This resolved it for me:

$ cd ios && rm -rf Pods && pod cache clean --all && pod install && cd ..

I forgot that I had done a "yarn add ..." on a few NPM modules and forgot to reinstall the pods.

**Comment by ralph-dev** [comment]
I have fixed this error, can confirm it's because one of your libraries isn't linked correctly. Fastest way to fix this is starting from index.js to app.js commenting out imports. Once you've commented out enough libraries the app should work then you will know which library was not linked correctly. Some libraries that say they have auto-linking actually don't..... It's very tedious but this works and my app is now fully functioning!

**Comment by doctor-mosbat** [comment]
You probably used open and closed tags to introduce a component.

Wrong method:
<MyComponent></MyComponent>

Correct method:
<MyComponent/>

**Comment by schumannd** [comment]
Why does it have to be so difficult to find out WHICH Native Module cannot be null.

**Comment by kalmahik** [comment]
Hi! I have the same issue, both on android and iOS. I just remove node_modules and install again, it helps me) no other cleans or rebuilds has no effect(

**Comment by AdrianMrn** [comment]
This is just a vague error to tell you there's something wrong with one of your imports. It can have different causes and has different solutions for each cause. In my case, this was happening because of a circular dependency.

**Comment by Wout-Vanneste-student** [comment]
Hi! I'm having the same issue. BUT I know what is the cause, it's the package `react-navigation-stack` or `react-navigation-tabs`. They both use the package `react-native-reanimated` which is creating the following error for me.
![image](https://user-images.githubusercontent.com/44393610/70377152-5803bd80-1911-11ea-8623-cd52f2609e81.png)

I have tried everything that all of you already posted before me. And none of them have worked successfully, unfortunately...

If anyone has any idea how to fix this issue. You would really help me out big time.

**Comment by sankar2389** [comment]
> Also ran into this (setup below). Took a bit of @m4rcoperuano 's solution and just stopped my simulator and bundler, then removed everything in watchman via `watchman watch-del-all`. Restarted the simulator via `react-native run-ios` and everything works fine.
> 
> Setup
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.61.2
> mac OSmojave 10.14.6
> ```

https://github.com/react-native-community/cli#compatibility denotes that react-native 0.61.X needs react-native-cli: 3.0.0

**Comment by nandorojo** [comment]
This solved it for me, using a managed Expo project:

```
expo start --ios -c
```

**Comment by msand** [comment]
Another possible reason for this is that there are multiple versions of react-native in node_modules

**Comment by msand** [comment]
Try searching for `registerCallableModule('AppRegistry'` in node_modules, if you find more than one, that's a likely reason

**Comment by tnortman** [comment]
> @Hugo-Meiring Probably you use modules that were removed from `react-native`.
> For example `ViewPagerAndroid `

This was the issue for us - we jumped from RN 0.58 to RN 0.61.5 where some RN stock components were removed. ViewPagerAndroid and ListView were the culprits for us.

**Comment by niclin** [comment]
I face same problem just now and try any suggestion but noting change 😢 

when I remove my computer everywhere `node_modules` I resolve this issue for me!!!

so I guess maybe are multiple versions of react-native in node_modules ?

1. `sudo find . -name "node_modules" -type d -prune -exec rm -rf '{}' +`
2. reinstall yarn
3. run `yarn` in my porject
4. xcode -> clean build folder
5. iOS APP is working!!!!

**Comment by tahaphuong** [comment]
i had the same problem, when i used react-navigation package, but i had not downloaded all the required "side-packages" (particularly is react-native-reanimated). The problem may come from one of your import. Check the usage of all packages carefully, you would definitely find a way. Good luck!!

**Comment by lemao-code** [comment]
> Também deparei com isso (configuração abaixo). Peguei um pouco da solução do @ m4rcoperuano e parei meu simulador e empacotador, depois removi tudo no watchman via `watchman watch-del-all`. Reiniciei o simulador via `react-native run-ios`e tudo funciona bem.
> 
> Configuração
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.61.2
> mac OSmojave 10.14.6
> ```
it worked for me

**Comment by henriquecorraro** [comment]
cd ios
remove pods
pod install

**Comment by KEMBL** [comment]
who have this problem in Android mono repo (I have not tried this with ios):  as @msand mentioned the problem could be in many **registerCallableModule('AppRegistry'** in your result bundle. Multiple occurrences could be because of using react-native components from other monorepo packages. 
 
So we need to remove them:
1) react-native run-android
2) Download bundle (from http://127.0.0.1:8081/index.bundle?platform=android&dev=true&minify=false), open it and inspect for the discussing substring
3) Now we need to block node_modules loading from the found places except the first one
4) Add into metro.config.js  into resolver / blacklistRE  patterns like this

blacklistRE: /(.*\\component1\\node_modules\\.*|.*\\component2\\node_modules\\.*|.*\\component3\\node_modules\\.*)$/,

5) start again
react-native run-android
6) check bundle again, it should contain only one **registerCallableModule('AppRegistry'**
7) check how code works on a device.

in gap 4) you probably need to make more particular regexes if your components use "nohoist" components.

as a bonus - smaller bundle size. :)

**Comment by dbrunonascimento** [comment]
> who have this problem in Android mono repo (I have not tried this with ios): as @msand mentioned the problem could be in many **registerCallableModule('AppRegistry'** in your result bundle. Multiple occurrences could be because of using react-native components from other monorepo packages.
> 
> So we need to remove them from the bundle:
> 
> 1. react-native run-android
> 2. Download bundle (from http://127.0.0.1:8081/index.bundle?platform=android&dev=true&minify=false), open it and inspect for the discussing substring
> 3. Now we need to block node_modules loading from the found places except the first one
> 4. Add into metro.config.js  into resolver / blacklistRE  patterns like this
>    `blacklistRE: /(.*\\component1\\node_modules\\.*|.*\\component2\\node_modules\\.*|.*\\component3\\node_modules\\.*)$/`
> 5. start again
>    react-native run-android
> 6. check bundle again, it should contain only one **registerCallableModule('AppRegistry'**
> 7. check how code works on a device.
> 
> in gap 4) you probably need to make more particular regexes if your components use "nohoist" components.
> 
> as a bonus - smaller bundle size. :)

module.exports = {
  ...
  resolver: {
    blacklistRE: /(.*\/component\/node_modules\/.*)$/,
  },
 ... 
};

**Comment by MaxMotovilov** [comment]
It appears that delaying the first call to `AppRegistry.registerComponent()` until an asynchronous event occurs is sufficient to cause this problem. I have originally run into it due to a call to `fetch()` but it reproduces with something as simple as the default application created by `react-native init` if you change
```AppRegistry.registerComponent(appName, () => App);```
to
```setTimeout( () => AppRegistry.registerComponent(appName, () => App), 0 );```
Notably, changing `setTimeout()` to `setImmediate()` in the above example made the issue go away for me.

**Comment by prakashsaran** [comment]
just try yarn/npm install in your root folder of project :thinking:

**Comment by wa-Nadoo** [comment]
I got the same issue when I added a 3rd party library with components. The root of the problem was that the library includes react, react-native, react-navigation as direct dependencies ("dependencies" field in package.json). After moving these dependencies to "peerDependencies" field of library package.json the error gone.

**Comment by alitele** [comment]
Simple close the metro shell and re-run app.

**Comment by lukecaan** [comment]
Getting the same issue, in a monorepo where my redux logic lives in a shared module alongside a react-dom and react-native project ... commenting out my imports doesn't seem to change anything but the error does disappear if I comment out the redux <Provider> I'm trying to render ... anyone got any clues?? As a newbie to react-native and monorepos this whole process has been a NIGHTMARE 😭

**Comment by tomoima525** [comment]
@lukecaan look into metro's blackList. With that you can make your app not seeing   redundant libraries under `redux`'s `node_modules` Ref: https://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories

**Comment by osamagamal7** [comment]
I've spent a decent time figuring out what's causing this error, but still the same. 
I closed the metro bundler and ran:  npm start and it worked, this is weird.

**Comment by pony13500815917** [comment]
> It appears that delaying the first call to `AppRegistry.registerComponent()` until an asynchronous event occurs is sufficient to cause this problem. I have originally run into it due to a call to `fetch()` but it reproduces with something as simple as the default application created by `react-native init` if you change
> `AppRegistry.registerComponent(appName, () => App);`
> to
> `setTimeout( () => AppRegistry.registerComponent(appName, () => App), 0 );`
> Notably, changing `setTimeout()` to `setImmediate()` in the above example made the issue go away for me.

I am also a bug caused by asynchrony！

**Comment by limaantonio** [comment]
Try insert: `import * as React from 'react';` , and after reload your application in your device.

**Comment by rpsutton** [comment]
I had the same issue for IOS, which appeared to pop up out of nowhere. Unfortunately, like @ralph-dev, I found the only thing that worked was going through every import statement to discover the faulty import.

**Comment by runryan** [comment]
It worked for me this way. Just terminated the metro  and reran `yarn iOS`.

**Comment by JakubRimal** [comment]
Also try Android Studio: File > Sync Project with Gradle Files, it worked for me. :tada:

**Comment by merci18** [comment]
Just run npm install then
re-run npm install -g react-native-cli , it worked for me

**Comment by ashokrajbathu** [comment]
> Why does it have to be so difficult to find out WHICH Native Module cannot be null?

Exactly....After a long frustrating period, I decided to understand what does it mean actually. As far as I understand it is trying to tell that some npm package is identified in your node modules and it's not just enough to install the package but you have to add some code in ios in order to make that package works. 

In my case I have installed npm package of react-native-push-notifications and done all the required changes in android but not in IOS.  my ios app which used to work fine suddenly started giving me this clueless error.  Finally, I have solved it. thanks to everyone.

**Comment by adamjuhasz** [comment]
On iOS we followed @MaxMotovilov's suggestion about problems with delaying calling ` AppRegistry.registerComponent(appName, () => App)`. When we no longer waited for other components to load, all was good

**Prev**
```javascript
async () => {
  await analytics.setup();
  AppRegistry.registerComponent(appName, () => App);
};
```

**Working**
```javascript
() => {
  analytics.setup().catch(/* */);
  AppRegistry.registerComponent(appName, () => App);
};

**Comment by xchmelmilos** [comment]
I hope this is correct :)

__Why it crashes?__
React Naive has Message Queue which tries to dynamically dispatch a message  `AppRegistry::runApplication`. In Your case AppRegistry is not bound to "AppRegistry" key in dispatch table inside Message Queue, so it crashes.

__How to fix this?__
In order to bind AppRegistry to "AppRegistry" inside RN Message Queue You have to call any method of AppRegistry (like `AppRegistry.registerComponent', basically any other method will do too). Called method will register AppRegistry inside RN Message Queue.

__Why You have to call arbitrary method on AppRegistry?__
 Because RN lazy loads AppRegistry when any of it's fields is accessed.
```
 get AppRegistry(): AppRegistry {
    return require('./Libraries/ReactNative/AppRegistry');
  },
```

**Comment by UltimatePea** [comment]
For us, the error happens because one of our components in the top-level router is not written correctly, so there are multiple errors in the log. This error happens to the last one thus we ignored the prior error. We found this out by reading the entire log from bottom to top.

**Comment by joaofelipemr** [comment]
Try:
1. unlink the packages you've done manually
2. cd ios && rm -rf Pods && pod cache clean --all && pod install && cd .. (@djohnsonkc)
3. close the metro shell and re-run app. (@alitele)

**Comment by hcminhit** [comment]
> i had the same problem, when i used react-navigation package, but i had not downloaded all the required "side-packages" (particularly is react-native-reanimated). The problem may come from one of your import. Check the guide of all packages carefully, you would definitely find a way. Good luck!!

hello let's be friends! Could you please give me your facebook profile!

**Comment by AdrianMrn** [comment]
@hcminhit not cool man

**Comment by BravenxX** [comment]
Upgrating from  react-native:"0.62.2" to "0.63.1" give me this error. 

For me it's imposible to upgrade react-native without getting an error. It's amazing..

**Comment by dhatGuy** [comment]
I had to close metro and run `expo start` again. And it worked.

**Comment by ISLEMNEDDAR** [comment]
you sure have probleme in an import that was not installed correct or that you have to reinstall your node modules

**Comment by YDaskaloff** [comment]
I've had this issue multiple times and in every one of them I used a different solution. I alway come here, like a retard, see that it's a vague error and end up just digging around my code and ultimately finding something dumb that I've done that broke my app. This last time, I had literally no idea what could be wrong. So I just ran pod install and npm install. Restarted the server, rebuilt the projects and it worked... MAGIC!

**Comment by SvitlanaTimofeyeva** [comment]
I've had this problem when one of the dependencies was specified incorrectly and it led to two instances of react-native being installed in node_modules

**Comment by zabojad** [comment]
I'm updating a quite large project form 0.61 to 0.63 and I'm running into this issue.

I've extracted from our code all the imports we do from `react-native`:

```
require("react-native").View;
require("react-native").StyleSheet;
require("react-native").PixelRatio;
require("react-native").Dimensions;
require("react-native").Text;
require("react-native").Image;
require("react-native").TouchableOpacity;
require("react-native").KeyboardAvoidingView;
require("react-native").ScrollView;
require("react-native").TouchableWithoutFeedback;
require("react-native").Modal;
require("react-native").Switch;
require("react-native").FlatList;
require("react-native").ToastAndroid;
require("react-native").Alert;
require("react-native").NativeEventEmitter;
require("react-native").AppState;
require("react-native").ActivityIndicator;
require("react-native").ProgressBarAndroid;
require("react-native").RefreshControl;
require("react-native").Linking;
require("react-native").TouchableHighlight;
require("react-native").Share;
require("react-native").Animated.View;
require("react-native").Animated;
require("react-native").Animated.Value;
require("react-native").BackHandler;
require("react-native").Keyboard;
require("react-native").Vibration;
require("react-native").ImageBackground;
require("react-native").SafeAreaView;
require("react-native").Slider;
require("react-native").TextInput;
```

Do you see any of them that would cause this error?

If it's not there, then it is perhaps on the other react-native modules *sigh*...

**Comment by xchmelmilos** [comment]
> I'm updating a quite large project from 0.61 to 0.63 and I'm running into this issue.
> 
> I've extracted from our code all the imports we do from `react-native`:
> 
> ```
> require("react-native").View;
> require("react-native").StyleSheet;
> require("react-native").PixelRatio;
> require("react-native").Dimensions;
> require("react-native").Text;
> require("react-native").Image;
> require("react-native").TouchableOpacity;
> require("react-native").KeyboardAvoidingView;
> require("react-native").ScrollView;
> require("react-native").TouchableWithoutFeedback;
> require("react-native").Modal;
> require("react-native").Switch;
> require("react-native").FlatList;
> require("react-native").ToastAndroid;
> require("react-native").Alert;
> require("react-native").NativeEventEmitter;
> require("react-native").AppState;
> require("react-native").ActivityIndicator;
> require("react-native").ProgressBarAndroid;
> require("react-native").RefreshControl;
> require("react-native").Linking;
> require("react-native").TouchableHighlight;
> require("react-native").Share;
> require("react-native").Animated.View;
> require("react-native").Animated;
> require("react-native").Animated.Value;
> require("react-native").BackHandler;
> require("react-native").Keyboard;
> require("react-native").Vibration;
> require("react-native").ImageBackground;
> require("react-native").SafeAreaView;
> require("react-native").Slider;
> require("react-native").TextInput;
> ```
> 
> Do you see any of them that would cause this error?
> 
> If it's not there, then it is perhaps on the other react-native modules _sigh_...

It is probably race condition. 

Add some code which imports AppRegistry and calls `any` of AppRegistry methods (Why? Because when some method of AppRegistry is called, AppRegistry is loaded and initialized).

Then please tell us if Your problem was fixed.

**Comment by marcofuentes05** [comment]
Havig the same issue here :sob: 
Saludos desde Guatemala :guatemala: 
![Captura de pantalla de 2020-07-28 18-02-08](https://user-images.githubusercontent.com/40815025/88741360-b0840700-d0fc-11ea-8c5f-385aaf7e15ad.png)

**Comment by zabojad** [comment]
@marcofuentes05 you are not having the same issue... In your case, just restart the metro bundler and you'll be OK...

**Comment by zabojad** [comment]
> It is probably race condition.
> 
> Add some code which imports AppRegistry and calls `any` of AppRegistry methods (Why? Because when some method of AppRegistry is called, AppRegistry is loaded and initialized).
> 
> Then please tell us if Your problem was fixed.

@xchmelmilos you were right. I've added this:
```javascript
import {AppRegistry} from 'react-native';
console.log('getAppKeys()=',AppRegistry.getAppKeys());
```
At the very beginning of my `index.js` file and the error is gone...

I'm a bit puzzled here:
-> I did not need to do that with RN 0.61.
-> I do not use `AppRegistry` directly as I am using [react-native-navigation](https://wix.github.io/react-native-navigation/docs/installing#displaying-the-app-root)...

So I guess I should now try to identify which call where causing this race condition right? 

With react native navigation alone, I do not get this error. So there is something in our code that causes it...

If you have any hint/suggestion on how to proceed faster and more reliably, please do not hesitate to tell me...

Once again thanks for your help @xchmelmilos!

**Comment by xchmelmilos** [comment]
> > It is probably race condition.
> > Add some code which imports AppRegistry and calls `any` of AppRegistry methods (Why? Because when some method of AppRegistry is called, AppRegistry is loaded and initialized).
> > Then please tell us if Your problem was fixed.
> 
> @xchmelmilos you were right. I've added this:
> 
> ```js
> import {AppRegistry} from 'react-native';
> console.log('getAppKeys()=',AppRegistry.getAppKeys());
> ```
> 
> At the very beginning of my `index.js` file and the error is gone...
> 
> I'm a bit puzzled here:
> -> I did not need to do that with RN 0.61.
> -> I do not use `AppRegistry` directly as I am using [react-native-navigation](https://wix.github.io/react-native-navigation/docs/installing#displaying-the-app-root)...
> 
> So I guess I should now try to identify which call where causing this race condition right?
> 
> With react native navigation alone, I do not get this error. So there is something in our code that get executed before RNN and after startup, that causes it...
> 
> If you have any hint/suggestion on how to proceed faster and more reliably to find it, please do not hesitate to tell me...
> 
> Once again thanks for your help @xchmelmilos!
> 
> Edit: for anyone using RNN, there is [this issue there](https://github.com/wix/react-native-navigation/issues/6168) which is related.

It is caused by RN itself, You just have to be faster to initialize this than RN internal message queue - I wrote about it here https://github.com/facebook/react-native/issues/26687#issuecomment-643281500 .

**Comment by zabojad** [comment]
@xchmelmilos actually, I thought the error was gone but it is not. I'm still see it in my logcat logs... Even with the addition to the index.js file I've made.

I'm a bit clueless on this one...

**Comment by zabojad** [comment]
It is a bit of black magic in my opinion because here what I exactly observe:

-> Without the index.js hotfix (pre-loading AppRegistry as you'b-ve suggested), I see the error both in logcat and in the RN logbox (dev mode):
```
2020-07-30 17:00:38.083 31128-31620/my.app I/ReactNativeJS: AppNavigation.hx:75: AppNavigation.init()
2020-07-30 17:00:38.156 31128-31620/my.app I/ReactNativeJS: AppNavigation.hx:233: setNavigationStack
2020-07-30 17:00:38.190 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-30 17:00:38.191 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2020-07-30 17:00:38.193 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-30 17:00:38.193 31128-31620/my.app I/ReactNativeJS: Running "Home" with {"initialProps":{"componentId":"Component5"},"rootTag":111}
2020-07-30 17:00:38.193 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2020-07-30 17:00:38.217 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-30 17:00:38.218 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2020-07-30 17:00:38.983 31128-31620/my.app I/ReactNativeJS: Running "SideMenu" with {"initialProps":{"componentId":"drawer-id"},"rootTag":121}
```

-> With the fix, I see it only in logcat (not in logbox anymore):

```
2020-07-30 17:04:13.591 31128-31832/my.app I/ReactNativeJS: AppNavigation.hx:75: AppNavigation.init()
2020-07-30 17:04:13.625 31128-31832/my.app I/ReactNativeJS: AppNavigation.hx:233: setNavigationStack
2020-07-30 17:04:13.643 782-31866/? E/ResolverController: No valid NAT64 prefix (244, <unspecified>/0)
2020-07-30 17:04:13.664 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-30 17:04:13.665 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2020-07-30 17:04:13.666 31128-31832/my.app I/ReactNativeJS: Running "Home" with {"initialProps":{"componentId":"Component5"},"rootTag":151}
2020-07-30 17:04:13.667 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-30 17:04:13.668 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2020-07-30 17:04:13.689 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-30 17:04:13.690 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2020-07-30 17:04:14.164 31128-31832/my.app I/ReactNativeJS: Running "SideMenu" with {"initialProps":{"componentId":"drawer-id"},"rootTag":161}
```

**Comment by xchmelmilos** [comment]
> It is a bit of black magic in my opinion because here what I exactly observe:
> 
> -> Without the index.js hotfix (pre-loading AppRegistry as you'b-ve suggested), I see the error both in logcat and in the RN logbox (dev mode):
> 
> ```
> 2020-07-30 17:00:38.083 31128-31620/my.app I/ReactNativeJS: AppNavigation.hx:75: AppNavigation.init()
> 2020-07-30 17:00:38.156 31128-31620/my.app I/ReactNativeJS: AppNavigation.hx:233: setNavigationStack
> 2020-07-30 17:00:38.190 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 2020-07-30 17:00:38.191 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
> 2020-07-30 17:00:38.193 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 2020-07-30 17:00:38.193 31128-31620/my.app I/ReactNativeJS: Running "Home" with {"initialProps":{"componentId":"Component5"},"rootTag":111}
> 2020-07-30 17:00:38.193 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
> 2020-07-30 17:00:38.217 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 2020-07-30 17:00:38.218 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
> 2020-07-30 17:00:38.983 31128-31620/my.app I/ReactNativeJS: Running "SideMenu" with {"initialProps":{"componentId":"drawer-id"},"rootTag":121}
> ```
> 
> -> With the fix, I see it only in logcat (not in logbox anymore):
> 
> ```
> 2020-07-30 17:04:13.591 31128-31832/my.app I/ReactNativeJS: AppNavigation.hx:75: AppNavigation.init()
> 2020-07-30 17:04:13.625 31128-31832/my.app I/ReactNativeJS: AppNavigation.hx:233: setNavigationStack
> 2020-07-30 17:04:13.643 782-31866/? E/ResolverController: No valid NAT64 prefix (244, <unspecified>/0)
> 2020-07-30 17:04:13.664 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 2020-07-30 17:04:13.665 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
> 2020-07-30 17:04:13.666 31128-31832/my.app I/ReactNativeJS: Running "Home" with {"initialProps":{"componentId":"Component5"},"rootTag":151}
> 2020-07-30 17:04:13.667 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 2020-07-30 17:04:13.668 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
> 2020-07-30 17:04:13.689 31128-31128/my.app E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 2020-07-30 17:04:13.690 31128-31128/my.app E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
> 2020-07-30 17:04:14.164 31128-31832/my.app I/ReactNativeJS: Running "SideMenu" with {"initialProps":{"componentId":"drawer-id"},"rootTag":161}
> ```
> 
> I do not see any significant difference in the logcat output :(...

I do not see any errors in your listing, I see only information that `AppRegistry.runApplication` was called - which is ok. Have You pasted correct listings?

**Comment by zabojad** [comment]
@xchmelmilos excuse me you are right again, the following error log appears without preloading AppRegistry:
```
2020-07-31 08:48:10.091 1874-2153/my.app E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
```

I was mistaken because `ReactRootView: runApplication: call AppRegistry.runApplication` is a `E` error log and I was interpreting it as an error while it is probably not one.

So all is good, you hotfix works indeed. But shouldn't it be fixed right within RN?

**Comment by xapai** [comment]
Got similar to @zabojad problem. After implementing a fix suggested, got this:

```
ExceptionsManager.js:179 Invariant Violation: "NavBarTextButton" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```
Not ideal, but leads me to a direction which component may actually cause a problem.

**Comment by xchmelmilos** [comment]
> @xchmelmilos excuse me you are right again, the following error log appears without preloading AppRegistry:
> 
> ```
> 2020-07-31 08:48:10.091 1874-2153/my.app E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
> ```
> 
> I was mistaken because `ReactRootView: runApplication: call AppRegistry.runApplication` is a `E` error log and I was interpreting it as an error while it is probably not one.
> 
> So all is good, you hotfix works indeed. But shouldn't it be fixed right within RN?

Yes, this magical lazy loading of AppRegistry is nonsense, it should be explicit call like `initializeAppRegistry()` or initializing AppRegistry immediately when import is called.

**Comment by gegana** [comment]
For my case I had to upgrade `react-native-progress`. 
https://github.com/oblador/react-native-progress/issues/201#issuecomment-623714289

**Comment by napalm00** [comment]
Even after using the AppRegistry lazy-loading workaround it doesn't work for me. 
It seems to crash when using react-navigation's createStackNavigator and other such methods.
Just upgraded from RN 0.61.5 to 0.63.2, had no issues before.

**Comment by DeadKuriel** [comment]
> Fixed the issue on my end by double checking that i modified all the files correctly during my RN upgrade, then running `watchman watch-del-all`, and `react-native start --reset-cache`. Then on android, build -> clean. then it worked! sigh

That worked for me.
Thanks

**Comment by champion007** [comment]
I am also facing issue with React Navigation with reference to stack other methods. Mine is new project it was working yesterday suddenly stopper tried all the above mentioned steps but nothing worked for me.

RN info -
```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 86.23 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.61.5
```

**Comment by jjd314** [comment]
In our case, there was a bug in a function that was being called at the global level in a module, i.e., at module load time.  We had something like this in foo.js:
```
export default (a, { param }) => {
...
```
and then in bar.js we had something like this:
```
import foo from './foo.js'
foo('something')
```
i.e., called foo() at the top level of the module but without the final argument.  I doubt it was specific to this particular bug, but the crash at module load time was probably enough to derail the AppRegistry.

**Comment by juniorhc** [comment]
0

Ok guys, here we are my solution for this issue:

- npm install native-base@latest -g
- npm install react-native@latest -g
- change package.json for these dependencies
- delete node_modules and npm install

Open it Xcode and Build/Run from scratch

I hope it helped

**Comment by mstankov** [comment]
Probably the single most vague, annoying error in the react-native environment... And we know there's a lot of them :) Usually I'm getting it after adding a package via **yarn add**. Not sure if it's connected to yarn itself and whether npm fixes it. Fix is to simply remove **node_modules** and reinstall them.

**Comment by weblancaster** [comment]
I spent a few hours having the same issue `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)` and it happened "from nowhere".

Because everything was working fine in the previous day and everything was still working fine in the production bundle I thought the usual YOLO commands delete, clean and re-install everything would fix it but I was wrong.

Turns out it was one of the imports (as some suggested above). I couldn't believe it because this package/import has been in the project for weeks 🤕

**Comment by amphyxs** [comment]
Like @weblancaster, I've recieved this error from nowhere. Some days ago I had a good-working app and after I recently launched it, this error appeared. I didn't install any modules or chabged anything. To fix it I've tried to delete and reinstall node modules, clean npm cache, re-link libraries, reinstall react-native and another libraries, but nothing helped. Even if I comment everything in main `index.js` where AppRegistry is called, this error still happens. Is there any way to found out what's wrong? May be there are a problem with some module, but hot to find out which module is wrong?

**Comment by weblancaster** [comment]
@amphyxs take a look at your imports or any small bug that could have been introduced in the past days. Turns out the error message is pretty vague and could be different things.

**Comment by jamesdmurphy51** [comment]
Downgraded back from 0.63.2 to 0.61.5.....fixed the problem.
Hopefully RN team will address this with next release and then Ill upgrade again

**Comment by flicknewb** [comment]
I found that I had a small piece of styling that was missing a letter, and that caused this error to pop up. I had "alignConten" instead of "alignContent", and just adding that 't' fixed the error. I sincerely hope everyone was having different, and more relevant issues underlying their errors...

**Comment by danielvportlandia** [comment]
Encountered this issue after upgrading to 0.63.2, commenting out the imports did eventually help as I was able to see some additional error logs. I had 3 libraries giving me issues.

"react-native-paper": "^4.1.0", // forced to update from 2.15.2
"react-navigation-material-bottom-tabs": "^2.3.0", // forced to update from 1.0.0
"react-native-material-textfield": applied this patch https://stackoverflow.com/a/62794092/12843101

**Comment by davimello28** [comment]
Check if you don't have this situation:

**/folder/index.js**
```js
export * from './A.jsx'
export * from './B.jsx'
```
**/folder/a**
```js
export function A(){
//...
}
```
**/folder/b**
```js
export function A(){ //instead of B()
//...
}
```

**Comment by ritzacco** [comment]
Apparently I started getting this error after an unsuccessful npm installation of **css-to-react-native**

**Comment by ReisMari** [comment]
I really don't know how to explain, but for me, when this happens, I just close everything (Visual Studio, Android Studio, Emulators) and reopen them. After that, my app starts to work again. It´s very weird but I got this Module AppRegistry error many times and every time I restarted all the programs, my app "came back to life". It doesn't hurt to try!

**Comment by nicolascarratala** [comment]
I stopped react-native, then opened xcode hit the product tab and hit the clean build folder button. Then I picked up the project and this solved everything.

**Comment by shivamjjha** [comment]
Close everything: Server, VS Code, Emulator, Rebuild the by `--reset-cache` command, and run your app. If still persists, try restarting the system and doing the steps once more.

[https://stackoverflow.com/a/51304124/11667949](https://stackoverflow.com/a/51304124/11667949) 

[https://stackoverflow.com/a/46826116/11667949](https://stackoverflow.com/a/46826116/11667949)

**Comment by homen** [comment]
I reverted to react-native **0.62.0** from **0.63.2**. At least **0.62.0** shows some information that which component has the problem. Then I able to fix the issue related to the component. Hopes in the future update we will get more information about the issue in the log.

**Comment by nicolascarratala** [comment]
For ios i've only intalled pod, the command i recommend is:
`cd ios; pod install; cd ..  `
I consider that this is produced when i installed react-navigation on my node_modules, and then i forgot to install the pod files related to this new dependency.

**Comment by nokite** [comment]
In case this helps... I resolved this on Android by manually registering some ReactPackage's, despite the instructions of RN-Firebase against that ( https://rnfirebase.io/migrating-to-v6 )
I added:
```
    .addPackage(new ReactNativeFirebaseAppPackage())
    .addPackage(new ReactNativeFirebaseCrashlyticsPackage())
```
It may be relevant that I also register other packages manually - like MainReactPackage, but also MyAppReactPackage, RNRecyclerviewListPackage etc. No idea if the extra ones are compliant with auto-linking or whatever else.

My dependencies are:
```
      "@react-native-firebase/app": "^8.4.5",
      "@react-native-firebase/crashlytics": "^8.4.9",
      "react": "16.9.0",
      "react-native": "0.61.5",

(gradle) 
      val firebase = "17.5.0"
      crashlytics = "17.2.2"
      crashlyticsPlugin = "2.3.0"
```
P.S. It's probably a stupid way to solve the problem, and I probably have lots of inconsistencies in my setup. At some point it's just trial and error now...

**Comment by jerrycaffe** [comment]
for me expo r -c cleared cache then restart the application worked perfectly for me

**Comment by Hugo-Meiring** [comment]
So I have been roped back into this project because the issue was resurfaced again. The initial issue was eventually resolved by:

1. Creating a new react native project from scratch with the exact same name but the latest version (and git init it + commit). This is useful to see what changes between the latest init project that attempts to copy parts of the broken one.
2. Slowly add all the libraries to the package.json and keep testing which broke and which didn't, using the latest of each where possible. And get it to just show the default hello world screen without issue with all the libraries.
3. Add all the source code and update all breaking changes + refactor where needed. I did it first for the inner react native project, and then once it worked did it for our main project. This eventually allowed both iOS and Android to run 0.61.X
4. Copy over this working project over the broken project (remember don't copy over / delete the .git folder of either project). Commit and you are good to go.

I love @ralph-dev 's fastest way suggestion and agree. We will take that route first. That should work, then we can update to react native 0.63.x. Else we will need to do the above like previously. Will report back. All the other suggestions have been tried by the dev that took over from me.

Final note, to those that find this. Especially with some very complex issues, ones where the compilers fail because of a compiler bug, no output or stack trace is given or the crash is not even in any code remotely related or identifiable to you, where Google has no results (not even in Chinese, google translate is amazing and has helped immensely) and there is no smart strategy the way I found to solve the issue as last resort is a binary search. Keeping dividing your code into half (not literally) and disable the one "half". Keep doing this until you hit the issue. It grows exponentially and you will soon get to the issue within 8 - 20 levels deep.

**Comment by ramonpaolo** [comment]
I solved this problem by removing a dependency and an instance that I had made, but I forgot to remove these 2 lines of code

**Comment by hoyame** [comment]
this error occurs when you add dependency without linking it with ``react-native link``, to fix this you need to remove the dependency, reinstall it and link it with ``react-native link``

(there are only certain dependencies that must be linked)

**Comment by matthewbal** [comment]
I ran into this issue when updating to RN 0.63.3, we figured out it was because we were importing a library which had a dependency on an older version of react, hence two react native versions were being loaded into the yarn lockfile.

Could be something for you guys to check out - take a look at the lockfile and ensure there's only one version of react native in there.

**Comment by muhammadashfaq** [comment]
I am facing this issue many times.   why Facebook is not taking it seriously.
<img width="1440" alt="Screenshot 2020-11-06 at 11 03 39 AM" src="https://user-images.githubusercontent.com/48868012/98334383-8a87d000-2024-11eb-8416-2a3ace8425c1.png">

can anyone tell how to fix this?

**Comment by ninety19** [comment]
I had the same problem when updating to RN 0.63.3.
And it work for me by adding the code
"resolutions": {
  "@react-native-community/viewpager": "4.1.0",
  "react-native-webview": "10.10.0",
}

**Comment by lw37** [comment]
> I had the same problem when updating to RN 0.63.3.
> And it work for me by adding the code
> "resolutions": {
>   "@react-native-community/viewpager": "4.1.0",
>   "react-native-webview": "10.10.0",
> }

Where can I use this code?

**Comment by ninety19** [comment]
> > I had the same problem when updating to RN 0.63.3.
> > And it work for me by adding the code
> > "resolutions": {
> > "@react-native-community/viewpager": "4.1.0",
> > "react-native-webview": "10.10.0",
> > }
> 
> Where can I use this code?

package.json

**Comment by obrenoco** [comment]
As commented before, it's quite a generic error.

Remove the `node_modules` folder and then run `yarn install` or `npm install` 

it seemed to solve the issue here.

**Comment by GanongLS** [comment]
> Another possible reason for this is that there are multiple versions of react-native in node_modules

thank for insight

**Comment by shogotsuneto** [comment]
I've experienced this a few times after upgrading to RN 63.3.
Deleting cache, builds or dependencies doesn't work for me. But re-cloning the whole project always works.
I believe there accumulates unrecognized garbage in somewhere under the project folder.

**Comment by dheeraj221b** [comment]
Finally I was able to resolved this issue. I was experiencing this issue after updating react native version from 0.61.2 to 0.63.3.
and I was using a custom component for text input which was extending TextInput. And it worked after replacing TextInput with React.Component.

**Example:**
**Before Fix:**
import React from 'react';
import {TextInput} from 'react-native';
class CustomTextInput extends TextInput{
render(){
**...code**
}
}

After Fix:(Working code):
import React from 'react';
import {TextInput} from 'react-native';
class CustomTextInput extends **React.Component**{
render(){
/**code**/
}
}

**Comment by elgambet** [comment]
> I have fixed this error, can confirm it's because one of your libraries isn't linked correctly. Fastest way to fix this is starting from index.js to app.js commenting out imports. Once you've commented out enough libraries the app should work then you will know which library was not linked correctly. Some libraries that say they have auto-linking actually don't..... It's very tedious but this works and my app is now fully functioning!

This is a lifesaver! Thank you!

**Comment by ilyasbat** [comment]
React Native! You are a problem bitch. I hate you!!!

**Comment by penchef** [comment]
We've been able to create a [(minimal??) reproducible repo](https://github.com/penchef/android-debug-nuisance/blob/main/index.js#L17) which demonstrate the our problem and a soloution:

In our case the `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)` was caused by the `Navigation.registerComponent` call *inside* the `persistStore` callback.

Moving the `Navigation.registerComponent` outside solved the issue (for us).

```javascript
import {persistStore, persistReducer} from 'redux-persist';
import {Navigation} from 'react-native-navigation';
import {combineReducers, createStore, compose} from 'redux';

import AsyncStorage from '@react-native-community/async-storage';

import React from 'react';
import {SafeAreaView, StatusBar, Button, Alert} from 'react-native';

// DOES WORK HERE!
Navigation.registerComponent('foo.bar', () => App);

const store = configureStore();

persistStore(store, null, () => {
  // DOES NOT WORK HERE!
  // Navigation.registerComponent('foo.bar', () => App);

  Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'foo.bar',
            },
          },
        ],
      },
    },
  });
});

...
```

Why does this happen? No idea... 

Good luck everyone out there!

**Comment by sudendrakl** [comment]
why is this still not addressed for over an year?

**Comment by marwan2** [comment]
This issue occurred for me when upgraded from React native "0.61.0" to "0.63.4"

**Comment by workpebojot** [comment]
I forgot how I manually fixed mine, all I remember is you just reset the cache in your app, as long as you just reset it then a new error will appear, sometimes, in others, they says nothing comes out, but he only important thing is that when you are sure that your app is okay, you may need to reset the cache of your app so that you can see a new error message, but if it does not really change, you will need to re-build it to refresh the native components in your mobile app, then see if it is gone, if not, you can restart your computer. What I still remember and I was able to fix mine was because at night the app still had an error, then I turned off the computer when I went to sleep, then the next day the error disappeared, I am also not sure why

**Comment by workpebojot** [comment]
I forgot how I manually fixed mine, all I remember is you just reset the cache in your app, as long as you just reset it then a new error will appear, but in others, they says nothing comes out, but the only important thing is that when you are sure that your app is okay, you may need to reset the cache of your app so that you can see a new error message, but if it does not really change, you will need to re-build it to refresh the native components in your mobile app, then see if it is gone, if not, you can restart your computer. 

What I still remember and I was able to fix mine was because at night the app still had an error, then I turned off the computer when I went to sleep, then the next day the error disappeared, I am also not sure why

**Comment by gorvinsky** [comment]
I'm having this issue too and my app is just a simple webview app. React Native version is 0.63.4

**Comment by 256hz** [comment]
Resetting the Watchman cache fixed this for me: `watchman watch-del-all`

**Comment by goodhyun** [comment]
I had to ...
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

**Comment by mhkhung** [comment]
I found it usually due to a bad node_module that couldn't be loaded. I was adding a dev only module to set my app icon and this started happening. It is easy enough to renove the module since it only needs to run once (took me hours to find out that is causing it)

**Comment by gorvinsky** [comment]
> I'm having this issue too and my app is just a simple webview app. React Native version is 0.63.4

Ok, I fixed my own issue. I had bad integration with Firebase and once I fixed that, the error is gone as well.

**Comment by cmsax** [comment]
For God's sake, please fix this bug...

I've encountered this issue when trying to use the third party package `reanimated-bottom-sheet` or `react-native-bottom-sheet`. I've tried every possible solutions above, the Error is still there...

**Comment by MilosChmel** [comment]
I am pretty sure problems is that apps are sending messages in wrong order or too late (?) into message queue between cpp and javascript. I looked into this problem like a half a Year ago ...

This does not have higher priority because a) You can ignore this error b) it is not user facing c) it is not app breaking, Facebook has now like 987 errors which are  :D

Also I am pretty sure ignoring hundreds of comments on this issue is not DX which Facebook claims they have :D

**Comment by jmccarrell-lmi** [comment]
They should at least provide a more descriptive error message.

They'll provide error boundaries for OTHER devs to use, but god forbid they add decent error reporting on their own software.

**Comment by rvgroup** [comment]
In my case, the problems were in circular dependencies. Refactor and everything works fine!

**Comment by hsavit1** [comment]
I was able to solve this by uninstalling node and reinstalling via NVM

**Comment by hufans** [comment]
> React Native! You are a problem bitch. I hate you!!!
react-native 你这个b问题很大啊

**Comment by Orawko** [comment]
In my case, error was connected with Require cycle. I suggest checking your require cycle warings if you have any and remove them.

**Comment by asanz8** [comment]
In my case using FontAwesome, I was importing **faPaperClip** instead **faPaperclip**, problem gone 🤣

**Comment by robertosousa1** [comment]
If you are creating a native React library and have a sample application with the library installed, the error may be caused by the scope of the React Native library to be with a node_modules folder.

Deleting the node_modules folder worked for me.

**Comment by IM-CrazyDeveloper** [comment]
Hi All,
Facing this issue in RN upgrade 0.64.1 . I am using below configuration
Xcode 12.4
node 10.0

Tried : 'npm start --reset-cache'
also
installed : "@react-native-community/art"


Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 ERROR  Invariant Violation: ART has been removed from React Native. It can now be installed and imported from '@react-native-community/art' instead of 'react-native'. See https://github.com/react-native-art/art
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by MedRaid** [comment]
thanks for the proposed solutions, i will put my answer because it worked for me and maybe it can help someone else, thanks to @ralph-dev, for me it was the @react-navigation/web, actually it was blocking everything, so i deleted all imports:  import { Link } from '@react-navigation/web' in every file, and it worked like a magic, hope this helps someone

**Comment by nischaldutt** [comment]
Okay, finally I was able to fix this. I'll post what worked for me.

I was using `yup` npm module and when I checked the import statement, 
I was using 
`import yup from "yup";`

whereas I should be using
`import * as yup from "yup";`

Silly me! :)
Credit to @ralph-dev

**Comment by Tridence** [comment]
yeah me too,
react-native start --reset-cache
worked on my case (ANDROID)

**Comment by KrisLau** [comment]
Another thing that can cause this is if you're smart like me and accidentally leave the `storyName` of one of your Storybook stories empty 🤦😂
```
storiesOf('Component', module).add('', () => (
  <Component />
));
```

**Comment by GustavoContreiras-Feegow** [comment]
Tried everything, here are some scripts useful to clean and build:
```
"scripts": {
    "start": "npx react-native start --reset-cache",
    "android": "npx react-native run-android",
    "ios": "yarn start & npx react-native run-ios",
    "test": "jest",
    "lint": "eslint .",
    "install-all": "yarn install && yarn pod",
    "pod": "cd ios && pod install && cd ..",
    "clean": "yarn clean-ios && yarn clean-android && yarn clean-node && watchman watch-del-all && rm -rf /tmp/metro-*",
    "clean-android": "rm -rf android/.gradle android/.idea android/build android/app/build",
    "clean-ios": "cd ios && pod deintegrate && cd .. && pod cache clean --all && rm -rf ios/build ios/Podfile.lock",
    "clean-node": "rm -rf node_modules yarn.lock",
    "clean-npm": "npm cache clean --force"
  }
 ```

**Comment by hanifmhd** [comment]
any update on this issue? it still happens on Android.
my RN version is 0.64.0

**Comment by theking200794** [comment]
facing same issue on "react-native": "0.64.2"

**Comment by kodejuice** [comment]
Just go this issue, it gave the error on my physical device but worked on my emulator, so i uninstalled from my device and renistalled then it went away.

**Comment by jeremyrajan** [comment]
Same error for me as well, it starts acting wonky once I install the https://reactnavigation.org/docs/getting-started/ lib. I tried all the above methods, but no luck.

![image](https://user-images.githubusercontent.com/2890683/131209862-fad60788-0e1c-4cac-8102-75d0df096f89.png)

**Comment by devanshsadhotra25** [comment]
<img width="611" alt="Screenshot 2021-09-13 at 8 26 06 PM" src="https://user-images.githubusercontent.com/52030229/133106938-50b713a7-9873-4e94-b9b3-ffdadee86d4b.png">

An Error like for me as well, after I upgraded to RN 0.65.1 and this is the real pain, I upgraded from RN 0.60.3.

**Comment by pedrobneto** [comment]
Just spent a couple hours trying to figure this out, tried everything, and turns out it was because I was calling Stylesheet without importing it in one file...

**Comment by amirhosseinkabiri** [comment]
I hade the Same Issue but the problem was because I had the colors in a separated folder and in one of components I refers to a non-existing color... . But it didn't say where exactly the problem is! Hope it helps you...

**Comment by naolworku** [comment]
If you tried all options given and to working, the issue is with the Drawer navigator

**Comment by nhattuongvippro123** [comment]
I solved this issue just by adding

**import { AppRegistry } from "react-native";
import App from "./App";
import { name as appName } from "./app.json";  
AppRegistry.registerComponent(appName, () => App);**


to my **index.js**
it works for this issue. 14/11/2021

**Comment by harshan89** [comment]
I think there is no solution for this, for me it worked after reinstalling and clearing caches several times,

My steps was,

removed node_module
removed Pods folder in ios

1. go to root folder
2. yarn install
3. cd ios && pod install
4. cd ..
5. react-native start --reset-cache

repeated several time suddenly it worked. :confused:

**Comment by hirajgajera** [comment]
BUNDLE  ./index.js

 ERROR  Error: Cannot create styled-component for component: undefined.

 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

Already tried:
1.  gradlew clean.
2. deleted node_modules and reinstalled it.
3. styled component works perfectly in similar app in similar environment
4. index.js file corrected and is as below:

/**
 * @format
 */

 import { AppRegistry } from "react-native";
 import App from "./App";
 import { name as appName } from "./app.json";
 AppRegistry.registerComponent(appName, () => App);


No solution found on stackoverflow!

**Comment by 25308985** [comment]
For me, the issue was my application package name. Actually, I was reusing the source code of the existing app to make a replica of the same app. So I kept the "build_config_package" the same as an old app but changes the package name.

**Comment by jamalumusic** [comment]
1- update your react-native-reanimated library to "react-native-reanimated": "2.0.0"

2- You should update the babel.config.json file and add react-native-reanimated/plugin to plugins
3- run this command `react-native start --reset-cache`
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    "react-native-reanimated/plugin",
  ],
};
```

This will fix your issue

**Comment by mwalkerr** [comment]
Well this was pretty dumb in my case. We're using React Native Brownfield and I made an update to add a new package: 

```       
 val packages = PackageList(this)
        .packages
        .toMutableList()
        .add(MyRNPackage())
            
```
Well `add` returns a boolean, not a reference to the list, so the list of packages being sent to react native brownfield was actually just a boolean...

**Comment by ZubairovSalim** [comment]
Facing same problem on ios, after deleting `com.facebook.react.BuildConfig` from MainApplication.java for solving this bug on android https://github.com/facebook/react-native/issues/29396. Helped for me: Go to Xcode -> Product -> Clean Build Folder. Rebuild and run.

**Comment by AndriyZahura** [comment]
For me the fix was to comment the most recent style files I've worked, and uncomment them one by one.

**Comment by Shah-zaib44** [comment]
> Just spent a couple hours trying to figure this out, tried everything, and turns out it was because I was calling Stylesheet without importing it in one file...

your comment really helped me

**Comment by isaacparsons-dw** [comment]
I have been having this issue on and off. What I have found most reliable is to delete and reinstall pods. This error message has also shown up on my end when running a different application in xcode than what metro is running. Happens when I forget to kill metro when switching projects.

**Comment by sabrimev** [comment]
One single error but there might be multiple causes. Seeing a lot of diverse discussions in the community means this issue could be hard to find. Try to proceed with the following.

 1. There might be a missing import.
 2. There might be a missing configuration with the library you recently installed.
 3. You may not receive errors in Android but in IOS. Then one of the lib configurations in IOS is missing.
 4. Your cache needs to be reset if RN is upgraded.

If you still cannot find the issue with the above, remove some imports or screens from your App.js. Going with this you can find what exactly caused this error. This is how I found my issue after a day of research.

**Comment by leonardoMoliveira** [comment]
> I have fixed this error, can confirm it's because one of your libraries isn't linked correctly. Fastest way to fix this is starting from index.js to app.js commenting out imports. Once you've commented out enough libraries the app should work then you will know which library was not linked correctly. Some libraries that say they have auto-linking actually don't..... It's very tedious but this works and my app is now fully functioning!

Best solution 🥳 , I was investigating by eliminating imports from my index.js, until I found the problem. Thanks!

**Comment by kohana11** [comment]
> I have fixed this error, can confirm it's because one of your libraries isn't linked correctly. Fastest way to fix this is starting from index.js to app.js commenting out imports. Once you've commented out enough libraries the app should work then you will know which library was not linked correctly. Some libraries that say they have auto-linking actually don't..... It's very tedious but this works and my app is now fully functioning!

In time to find out what's wrong or your task is blocked, this maybe the best solution to try.

**Comment by timothybowers** [comment]
For me this helped me find the problem, to which file was causing the error. (Root cause)

I made sure my metro.config.js file contained this line:
`inlineRequires: true,
`

**Comment by margox** [comment]
For anyone else who facing the same issue and cannot resolve it with every solution you found on the internet, maybe you shoud check if there is a `node_module` folder inside your `src` or `components` folder.
It wasted me half a day and I finally found the reason: I executed `npm i` inside in a deeper path of my project , Holy shit..

**Comment by eitan123a** [comment]
> I have fixed this error, can confirm it's because one of your libraries isn't linked correctly. Fastest way to fix this is starting from index.js to app.js commenting out imports. Once you've commented out enough libraries the app should work then you will know which library was not linked correctly. Some libraries that say they have auto-linking actually don't..... It's very tedious but this works and my app is now fully functioning!

Bro, I don't know you but you saved me after 3 days of pulling my hair out!!
You're my savior!!

**Comment by justintoth** [comment]
In case it helps others... None of the answers above worked for me. I cleaned my iOS pods, npm packages, etc... and also verified that all of my 3rd party package and internal component imports were correct, and was still receiving the error. After two hours, I finally tried quitting the app, uninstalling it, quitting metro, restarting it, then reinstalling the app and it worked! I believe the crucial step was restarting metro...

**Comment by salorsino** [comment]
Seeing this now on a RN app with multiple devs - had one teammate with this issue b/c he was running `npm install --legacy-peer-deps` due to still using deprecated `@react-native-community/async-storage`. Had him update to `@react-native-async-storage/async-storage` and his issues were fixed, but then it started for me...

Still struggling with this issue as of now on my own machine after trying all the above solutions
