### ISSUE TITLE
React Native Android: An absolute positioned, TouchableOpacity outside of the bounds of its parent is not clickable

### ISSUE THREAD

**Issue by travisho-ensu** [facebook/react-native#27232]
If I place a TouchableOpacity outside the bounds of its parent (using absolute positioning) only the portions of the TouchableOpacity which are inside the bounds of the parent are clickable. I think this is a bug because this can only be reproduced in Android, not iOS.
React Native version: 35.0.0

## Steps To Reproduce

Here's a minimal code sample:
`
<View style={{height: 60, width: '100%', zIndex: 1}}>
    <TouchableOpacity onPress={() => console.log('pressed')} style={{position: 'absolute', zIndex: 2, backgroundColor: 'yellow', width: 100, height: 50, top: 70}} />
</View>
`

**Comment by excitedleigh** [comment]
I'm having the same problem, but I've come across #26374 which I think should fix it if/when it's merged?

**Comment by tarasvakulka** [comment]
Hi, may be somebody know when this PR  [#26374](https://github.com/facebook/react-native/pull/26374) will be merged ?

**Comment by harshitaahuja** [comment]
This is still reproducible on version 0.61.5. any fixes?

**Comment by loustak** [comment]
We really need this issue to be fixed.

**Comment by vonkanehoffen** [comment]
I'm still seeing this bug in 0.61.5 on Android. A fix would be amazing.

**Comment by LeonDong199509** [comment]
I got this bud too.  This PR #26374 doesn't work for me. Anyone can help?

**Comment by aanation** [comment]
Any news? 
So many people need this fix :(
It is very difficult for me to develop a custom autocomplete, a dropdown and many other components where absolute positioning is required :(

**Comment by sriram-kailasam** [comment]
A temporary workaround is to import `TouchableOpacity` from `react-native-gesture-handler`. That's how I got it working after a wasted day of messing with `position: 'absolute'`.

**Comment by prateekchachra** [comment]
@sriram-kailasam Not working


I tried using the same.

**Comment by igorrfc** [comment]
Render the absolute positioned touchable component as the last child worked for me. Also, I've enveloped the entire component into a fragment. Example:
```js
const Screen = () => (
  <>
    <ScreenContent />
    <TouchableOpacity style={{position: 'absolute'}} />
  </>

)
```

**Comment by Egizas** [comment]
please merge, this issue is driving me nuts

**Comment by neXorianus** [comment]
I also had the bug when using a wrapper element positioned absolute:
```jsx
<View style={{position: absolute, height: 0, justifyContent: 'space-between'}}>
  <StickyTouchable />
  <StickyTouchable />
</View>
```
This results in Toucheables not beeing clickable. expanding the wrapping View to the height of the Touchables, makes them clickable again, but kills interaction with elements behind the wrapper.

The only way I could fix this is giving the absolute positioning to the children, similar to @igorrfc :
```jsx
<>
  <StickyTouchable style={{position: absolute, left: 0}} />
  <StickyTouchable style={{position: absolute, right: 0}}/>
</>
```

**Comment by Shuo-Mr** [comment]
Has this problem been solved? I also have this problem. When my view is absolutely positioned, it is not in the scope of the parent view, and all internal interaction events will not take effect.

**Comment by jong-hui** [comment]
0.63's `Pressable` have same problem

**Comment by alexvilchis** [comment]
Having the same issue with Pressables

**Comment by youssame** [comment]
> Render the absolute positioned touchable component as the last child worked for me. Also, I've enveloped the entire component into a fragment. Example:
> 
> ```js
> const Screen = () => (
>   <>
>     <ScreenContent />
>     <TouchableOpacity style={{position: 'absolute'}} />
>   </>
> 
> )
> ```

👍

**Comment by abhirna36** [comment]
What's the latest update from the issue ?

**Comment by Svarto** [comment]
same problem

**Comment by JB-CHAUVIN** [comment]
Same problem...

**Comment by mikkelwf** [comment]
Same issue here with Pressable

**Comment by ABespolov** [comment]
You can use standart [Modal](https://reactnative.dev/docs/modal) to block user ui while some loading or more powerfull community [version](https://github.com/react-native-modal/react-native-modal)

**Comment by MrToxy** [comment]
Same issue with View.
RN version "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz".

**Comment by summerkiflain** [comment]
Its a shame that one of the most important design feature doesn't work properly with touchables in overflown area, the issue and the related PR is lingering on for over an year, I hope someone gives it another look and solve the biggest hassle for design implementation, if its working fine in iOS it should replicate the behavior in android too.

**Comment by FrancisLeigh** [comment]
Experiencing this issue also and wrapping the pressable element or complete Fragments not working...

**Comment by JeremiahUL** [comment]
This is a shame honestly. I love RN but I am surprised how long this issue has gone. We celebrated one year anniversary of this issue. 😅

**Comment by kamwoz** [comment]
Why is it waiting for so long here? It's basic funcionality!

**Comment by lukebrandonfarrell** [comment]
A simple fix for this is to position your absolute positioned components at the root of your page

**Comment by summerkiflain** [comment]
> A simple fix for this is to position your absolute positioned components at the root of your page

I don't understand what do you mean by the "root of your page", can you create a small expo snack if possible?

**Comment by cokepizza** [comment]
> A temporary workaround is to import `TouchableOpacity` from `react-native-gesture-handler`. That's how I got it working after a wasted day of messing with `position: 'absolute'`.

same issue react-native 0.63.4 in android
if i use touchableOpacity from 'react-native-gesture-handler', This seems to be bubbling between the touch layers.

https://github.com/software-mansion/react-native-gesture-handler/issues/784

fundamental problem solving seems to be needed on the RN side.

**Comment by waqaspassu** [comment]
I have the same issue.

**Comment by Svarto** [comment]
I found a workable hack, use the BaseButton from react-native-gesture-handler almost exclusively. It manages presses on the correct visible layer and it prevents taps to bubble through and activate several at once (if the ones underneath are also BaseButton)

**Comment by waqaspassu** [comment]
**Custom Dropdown inside header is not clickable**
Pressable or Text inside the dropdown is not clickable
### Dropdown Component
if (toggle) {
		return (
			<View style={styles.modal}>
				<FlatList
					style={{ zIndex: 1 }}
					data={lists}
					renderItem={(data: any) => (
						<Pressable
							style={{ backgroundColor: "red", marginVertical: 2, zIndex: 10 }}
							**onPress={() => console.log("hello clicked me")}**
						>
							<Text>{data.item.name}</Text>
						</Pressable>
					)}
					keyExtractor={(item) => "" + item.value}
				/>
			</View>
		);
	}
### Screen Component where dropdown is rendered
<Stack.Screen
					name="Home"
					component={HomeRoutes}
					options={({ route }) => ({
						headerRight: () => (
							<>
									<Icon
										onPress={() => setToggle(!toggle)}
										name="ellipsis-vertical"
										size={28}
										color="#7E7E7E"
									/>
							<CustomDropdown
									toggle={toggle}
									lists={[
										{ name: "Invite Friend", value: "invitefriend" },
										{ name: "Help", value: "help" },
										{ name: "About", value: "Deleted" },
										{ name: "Terms & Conditions", value: "termandcondition" },
										{ name: "Privacy Policy	", value: "privacy" },
									]}
									listPressd={ListPressed}
								/>
								
								
							</>
						),
						headerTitle: getHeaderTItle(route),
					})}
				/>
				<Stack.Screen
					name="createProfile"
					component={EditProfile}
					options={({ navigation }) => ({
						headerLeft: () => (
							<Icon
								onPress={() => navigation.goBack(null)}
								style={{ marginLeft: 10 }}
								name="arrow-back"
								size={28}
								color="#7E7E7E"
							/>
						),
					})}
				/>

	const [toggle, setToggle] = useState(false);
	const [toggleData, setToggleData] = useState("");
	const ListPressed = (data: IlistPressed) => {
		console.log("dell", data);
		setToggle(false);
		setToggleData(data.item.value);
	};

### Styles

const styles = StyleSheet.create({
	modal: {
		zIndex: 1,
		position: "absolute",
		right: 0,
		top: 25,
		backgroundColor: "#ffff",
		width: 100,
		borderRadius: 5,
		paddingVertical: 10,
		paddingLeft: 10,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.84,

		elevation: 5,
	},
});

**Comment by flora8984461** [comment]
Same issue here, checking updates if any...

**Comment by DesertStrom16** [comment]
> I found a workable hack, use the BaseButton from react-native-gesture-handler almost exclusively. It manages presses on the correct visible layer and it prevents taps to bubble through and activate several at once (if the ones underneath are also BaseButton)

Can confirm this fixes the issue somewhat. Still hacky behavior on Android but much better than TouchableOpacity. Thanks for the heads up, you just saved me hours I'm sure.

**Comment by solidfox** [comment]
@DesertStrom16 could you elaborate on the hacky behavior? Would be awesome to know what to expect.

**Comment by DesertStrom16** [comment]
@solidfox Disregard that comment, hacky behavior was my own doing. As far as I can tell BaseButton is solid through and through.

**Comment by solidfox** [comment]
@DesertStrom16 Awesome! That's great to know!

**Comment by lumberman** [comment]
BaseButton hack isn't working for me. The problem still exists in React Native 0.64.

**Comment by RZsam** [comment]
have the same in 0.64

**Comment by PrimulaX** [comment]
Best workaround so far, for me, it was react-native-gesture-handler.
Just import `TouchableOpacity` from gesture handler and replace RN Touchables, if Touchables disappear use containerStyle prop instead style prop.

**Comment by kutsan** [comment]
@PrimulaX It works, thanks!

**Comment by Desintegrator** [comment]
@PrimulaX thanks! also works with `TouchableWithoutFeedback`

**Comment by Aurangempire** [comment]
> Render the absolute positioned touchable component as the last child worked for me. Also, I've enveloped the entire component into a fragment. Example:
> 
> ```js
> const Screen = () => (
>   <>
>     <ScreenContent />
>     <TouchableOpacity style={{position: 'absolute'}} />
>   </>
> 
> )
> ```

Saved my Day 👯‍♂️

**Comment by JamesJs** [comment]
Any update? Touch is passing throught absolute View...

**Comment by michaelkleinhenz** [comment]
This issue prevents the use of the custom header feature on react-navigation with headers set to `position: absolute`. As you can't add the element last because the layouting is done internally, it just does not work. The only way to do this is turning off the react-navigation custom header feature and create a header locally in every screen implementation.

**Comment by mayurbaldha** [comment]
👀

**Comment by seyaobey-dev** [comment]
Same bug, 2 years; these are reasons some people just switch to flutter...

**Comment by molimat** [comment]
How can we organize the 2 years party of this issue, guys?

**Comment by hlspablo** [comment]
Meanwhile the version 0.65 is being launched to add more and more bugs.. it's so sad that a beautiful tech like React Native is taking this direction, the fundamentals don't work as expected and no one give a shit.

**Comment by alimertcakar** [comment]
> How can we organize the 2 years anniversary party of this issue, guys? Who brings beer?

Will there be cake?

**Comment by safaiyeh** [comment]
Theres a massive effort going on the have eyes on all these fixes: https://github.com/facebook/react-native/projects/17#card-65759870 to track the statuses

**Comment by wajeshubham** [comment]
I was implementing custom dynamic toaster using context to use it globally and wasn't able to access touchable opacity due to absolute positioning but i realized i was rendering my Toaster component before my mail Stack Navigator which was bringing my toaster below navigation layer so i rendered it after stack navigator and it worked

**BEFORE:**
```
 <ToasterContext.Provider value={{toasts:this.state.toastState, showToaster: this.showToaster,closeToaster: this.closeToaster }}>
          <Provider store={store.store}>
            <PersistGate loading={null} persistor={store.persistor}>
             {toastState.length > 0 
                && toastState.length <= 3 
                && toastState.map((t, i) => {
                    return(
                      <DynamicToast i={i} key={i} t={t} position={"bottom"} duration={4000} closeToaster={this.closeToaster} />
                    )
                  }
                )} 
              <NetworkConnectionModal/>
              <AppContainer /> // I was rendering before my AppContainer
            </PersistGate>
          </Provider>
      </ToasterContext.Provider>
```

**AFTER: (Resolved my problem)**
```
 <ToasterContext.Provider value={{toasts:this.state.toastState, showToaster: this.showToaster,closeToaster: this.closeToaster }}>
          <Provider store={store.store}>
            <PersistGate loading={null} persistor={store.persistor}>
              <NetworkConnectionModal/>
              <AppContainer />
              {toastState.length > 0 
                && toastState.length <= 3 
                && toastState.map((t, i) => {
                    return(
                      <DynamicToast i={i} key={i} t={t} position={"bottom"} duration={4000} closeToaster={this.closeToaster} />
                    )
                  }
                )} 
            </PersistGate>
          </Provider>
      </ToasterContext.Provider>
```

**Comment by kodozorro** [comment]
I found this solution, and to be honest; it wasn't obvious at all for me. 

Wrap your main container and button into React.fragment, and everything will be pressed and tapped. I hope so =)

Example:

```ts
<>
   <TouchableOpacity style={styles.hideKeyboard} onPressIn={() => {}} hitSlop={theme.smallElementsHitSlop}>
        <Icon />
   </TouchableOpacity>
   <View style={styles.mainContainer}>
     
   </View>
</>


mainContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: theme.aligned(FOOTER_HEIGHT),
    paddingHorizontal: 16,
    backgroundColor: 'white',
  },
hideKeyboard: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: theme.aligned(30),
    bottom: 38,
    right: 2,
    width: 32,
    height: 32,
    backgroundColor: 'white',
  },

```

**Comment by ZioVio** [comment]
How can this issue be even closed if it is not fixed yet?
RN 0.66.0

**Comment by hlspablo** [comment]
@ZioVio sounds that this problem was solved in 0.66 version, look: https://github.com/facebook/react-native/commit/e35a963bfb93bbbdd92f4dd74d14e2ad6df5e14a

**Comment by VentroArt** [comment]
@hlspablo , but it's not :) 
As soon as child element is out the parent borders, thanks to position absolute, it became unclickable on android.
Faced with this issue today

**Comment by Wei102193** [comment]
Importing from  react-native-gesture-handler works for me.
I am trying to create a custom absolute cart button that is out of the bounds of a bottom navigation tab. React-native-gesture-handler makes it work. But if you have another element that uses TouchableOpacity from React Native. When these two buttons overlap, if you click it, both will be triggered. You have import TouchableOpacity from react-native-gesture-handler for both.

**Comment by liquidvisual** [comment]
I just stumbled upon this hellraising issue today, I wasn't sure what it was at first. I can confirm `react-native-gesture-handler` works for touchables, but in my case **I'm using a FlatList** (which won't scroll). Has anyone had any success in getting an out of bounds FlatList to work in this circumstance?

**Comment by danteallievi** [comment]
Im still having this issue on a view with position absolute and any touchable I use doesn't work

**Comment by maelthi** [comment]
Confirm that this issue is still going on with Pressable. Please fix it, with React native 16.13.1

**Comment by PrimulaX** [comment]
@maelthi That's not RN version.

**Comment by malinthann** [comment]
You have to make zIndex higher 
Example: zIndex: 2 to zIndex 9999
