### ISSUE TITLE
Using `toUpperCase` or `textTransform: 'uppercase'` breaks on an Android controlled TextInput

### ISSUE THREAD

**Issue by nick-michael** [facebook/react-native#27449]
React Native version: 0.61.4 and lower

Trying to force capitalization of characters inside a TextInput is broken on Android.

- `autoCapitalize="characters"` doesn't seem to do anything
- Using `toUpperCase` in the onChangeText hook causes duplication of letters
- Using `textTransform: 'uppercase'` in styles block causes the same duplication of letters
- Using `textTransform: 'uppercase'` in a non-controlled TextInput does nothing

## Steps To Reproduce

1. Create a controlled TextInput and either use onTextChanged to modify the text to uppercase or use text transform in the styles block
2. Type multiple lowercase characters into the text box

Describe what you expected to happen:
Characters should be capitalized

What actually happens:
Characters are capitalized and duplicated

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@nmi09/rn-android-capitalize-input-bug

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9058133/70392933-c2356480-19dc-11ea-803e-7c577f6807b1.gif)

**Comment by inferusvv** [comment]
Yeah. The same issue! On iOS all works fine

**Comment by mgiorgi-github** [comment]
Same issue for me....

**Comment by laraferroni** [comment]
Had same issue. Adding 
```secureTextEntry={Platform.OS === 'ios' ? false : true}```
seemed to fix it for me.

**Comment by YeshanJay** [comment]
Any luck finding a workaround for this??

**Comment by simon-davies-avtura** [comment]
`keyboardType="visible-password"` 

Seems to be the only workaround for me with Android at the moment (I've been looking for ages!). Will need some cross platform testing locally though.

**Comment by emilioheinz** [comment]
Really weird, it worked but I think that should be fixed asap.

> `keyboardType={Platform.OS === 'ios' ? 'default' : 'visible-password'}`
> 
> Seems to be the only workaround for me with Android at the moment (I've been looking for ages!). Will need some cross platform testing locally though.

**Comment by arthurolga** [comment]
i have the same problem. The solution by simon-davies-avtura solved it partially, but I really wanted to use `keyboardType='email-address'`. If there is any other workaround or a solution. I just want to display the font in lowerCase on the UI.

**Comment by fabriziobertoglio1987** [comment]
seems similar issue to https://github.com/facebook/react-native/issues/11068#issuecomment-574013816 

It is difficult to fix this issue related to Rich Text, more info in Pull Request https://github.com/facebook/react-native/pull/27757

**Comment by jamesdarabi** [comment]
This issue is still present in React Native version: `0.63.2`

**Comment by lorenamelor** [comment]
I have the same problem.

**Comment by Agungkes** [comment]
@lorenamelor You can simply use ** autoCapitalize = "characters" ** to TextInput to capitalize

See here [https://stackoverflow.com/questions/46349092/uppercase-keyboard-when-focusing-a-textinput](Uppercase Keyboard when focusing a TextInput)

**Comment by arthurolga** [comment]
`autoCapitalize={'characters'}`
Seems to solve the problem.
https://www.reddit.com/r/reactnative/comments/jhdref/any_solution_to_the_touppercase_problem

**Comment by fabriziobertoglio1987** [comment]
Hello ReactNative Developers! :smiley: 

I just prepared Pull Request https://github.com/facebook/react-native/pull/29070 that seems to solve this issue

**<details><summary>PREVIEWS OF THE BUGFIX</summary>**
<p>

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/83887390-a7079f80-a748-11ea-847e-bd9ee3065982.gif" width="200" height="" /> | <img src="https://user-images.githubusercontent.com/24992535/83886853-eda8ca00-a747-11ea-96eb-dc179fbd9f92.gif"  width="200" height="" /> |

</p>
</details>

You can contact me by email at fabrizio.developer@gmail.com

Please head over to the Pull Request https://github.com/facebook/react-native/pull/29070 and thumbs up if you like it.
If you want to get this fix you can follow the instructions for [building ReactAndroid](https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native) or checkout my [video introduction on forking react-native](https://youtu.be/9RQ2GiApkzU?t=420) (patch-package does not work).

If you don't like the pr please feel free to leave a code review or comment, I'll be happy to add improvements and changes.

Thanks a lot :pray: :peace_symbol: :beach_umbrella:

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29070 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by infinitbility** [comment]
Text transform Example in React Native

Table of content

1. textTransform Props
2. textTransform uppercase
3. textTransform lowercase
4. textTransform capitalize

https://infinitbility.com/react-native/text-transform-in-react-native

**Comment by jarrisoncano** [comment]
i have the same issue when i want to save the value on the onChangeText function.
i'm using expo and react-hook-form for handle the form.

![imagen](https://user-images.githubusercontent.com/62910118/145894693-81d6abe6-8946-4b6e-9e28-d50b4633c87d.png)
![imagen](https://user-images.githubusercontent.com/62910118/145894814-a2c3bd51-6119-46f3-a98d-408b5257ccc2.png)

**Comment by jarrisoncano** [comment]
I find a possible solution to my problem, the TextInput has a property autoCapitalize with the values 'words, sentences, characters', but the user can disable the uppercase in his keyboard so is necessary convert the value to uppercase when i want to save the data

**Comment by montoyadamien** [comment]
Any news on a fix ?

**Comment by jtvargas** [comment]
The duplications of letters are still happening, `RN:0.68.0 on Android` when you try to use the delete function.

**Comment by lay-mand** [comment]
The only thing that I can suggest for people stuck with this issue as me is that to apply TextInput's **value** formatting (`.toUpperCase` or whatever) on **onBlur**, so we forcibly format value after user finished typing. And don't forget about this property: https://reactnative.dev/docs/0.69/textinput#autocapitalize

**Comment by toviszsolt** [comment]
The issue still persists. I encountered the issue when using `toLowerCase`.

For me, the doubling only occurs when typing with the keyboard in capital letters. Each time a letter is pressed, the converted string is appended to the previous string for an unknown reason, instead of being overwritten.

It seems to be some kind of string comparison in the background, maybe something is using a `memo` like stuff and maybe that's causing the problem.

**Comment by jukkahuuskonen** [comment]
Some notes and an ugly fix for this:

1. It seems that unlike in regular JS this seems to change the value of the input only after launching the onChange/onChangeText-events, that may cause some update order mistakes causing this problem
2. Since I figured the problem had something to do with timing I decided to try **setTimeout** on onChangeText-prop to delay the change of **receiver** until the next render.
```
const [receiver, setReceiver] = useState();
...
<TextInput
  onChangeText={value => {
    setTimeout(() => {
      setReceiver(value.toLowerCase());
    });
  }}
  value={receiver}
  placeholder='john.doe@xyz.com...'
  textContentType='emailAddress'
  autoCorrect={false}
  keyboardType='email-address'
/>
```
This already helped the situation. Only the first letter was doubled. trying to type **Boxer** would change to 'bboxer'
3. after briefly looking at the **TextInput.js**-code I decided to try and give the **receiver** an empty string as a defaultValue:
```
const [receiver, setReceiver] = useState('');
...
<TextInput
  onChangeText={value => {
    setTimeout(() => {
      setReceiver(value.toLowerCase());
    });
  }}
  value={receiver}
  placeholder='john.doe@xyz.com...'
  textContentType='emailAddress'
  autoCorrect={false}
  keyboardType='email-address'
/>
```

And this fixed the doubling of letters. Text is blinking a bit but at least for me it worked otherwise just fine.

**Comment by toviszsolt** [comment]
@jukkahuuskonen Now try writing in all caps. I think you will be surprised.
The error only occurs for uppercase letters when using the `toLowerCase()` function.

**Comment by jukkahuuskonen** [comment]
> @jukkahuuskonen Now try writing in all caps. I think you will be surprised. The error only occurs for uppercase letters when using the `toLowerCase()` function.

Not sure if I understood correctly, but it works just fine with me **BOXER** becomes **boxer** no problems except for the text blinking a bit (hence the 'ugly' in the fix).
Also works with swipe-typing.

Of course I've only tested it with my Sony Xperia 5ii.

**Comment by toviszsolt** [comment]
@jukkahuuskonen  You understood well. This seems like a good temporary hack. Good job.
I tried it, it works for me, but **it causes another bug**. Here comes the vicious circle.

- If you delete longer (i.e. hold backspace), then very strange things happen because of `setTimeout()`.

**Comment by jukkahuuskonen** [comment]
> * If you delete longer (i.e. hold backspace), then very strange things happen because of `setTimeout()`.

yup, that can be problem. Didn't notice it myself. Also, if you type too fast a similiar problem occurs. It is really something the **react-native**-team should fix. The problem has been around for several years already...

**Comment by Productivix** [comment]
yes I got that bug also on RN 0.70.6 the first letter is doubled with .toLowerCase()

**Comment by Productivix** [comment]
Hi @cortinico , I think it is inside React-Native, part Android that there is this bug : can you please have a look ?

**Comment by shindenitish** [comment]
Adding autoCapitalize={"none"} and keyboard type as visible-password works. Another thing to note is don't add autoCorrect={false} with this fix.

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by Productivix** [comment]
You have the same behaviour with the code that delegates the 'toLowercase' function elsewhere : 
```
const [filter, setFilter] = useState('');

useEffect(() => {
    console.log('filter:', filter);
    if (filter != filter.toLowerCase()) {
      const replic = filter.toLowerCase();
      console.log('replic:', replic);
      setFilter(replic);
    }
  }, [filter]);

<TextInput
              onChangeText={text => setFilter(text)}
              value={filter}
              placeholder="post filter"
              style={CommonPrxStyles.inputWoWidth}
              maxLength={15}
              autoCapitalize="none" //bug of double 1st letter-still in 0.73.2 - facebook/react-native/issues/27449
            />
```
you get in console with typing "fgHj" : 
LOG  filter: f
 LOG  filter: fg
 LOG  filter: fgH
 LOG  replic: fgh
 LOG  filter: fgh
 LOG  filter: fghfgHj
 LOG  replic: fghfghj
 LOG  filter: fghfghj

it as if there is a state inside the Textinput that is emerging back with an old memory not updated.

**Comment by fabOnReact** [comment]
This PR is included in the [react-native-improved](https://github.com/fabriziobertoglio1987/react-native-improved) library:

# react-native-improved

- **Supports ONLY react-native 0.73**.
- Supports only old architechture (new architechture is WIP)

## Set-up

In package.json

```diff
 "scripts": {
+  "postinstall": "yarn run react-native-patch"
 }
```

Then

## npm

```sh
npm install react-native-improved --save-dev
```

## yarn v1

```sh
yarn add react-native-improved --dev
```

**Comment by Productivix** [comment]
Thank you but : 
in "react-native": "0.73.4",
with the useeffect written in this beginning, it is correct, without still not.
And only yarn add react-native-improved --dev is accepted , "postinstall": "yarn run react-native-patch" generate an error.
