### ISSUE TITLE
WebView and error

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#2904]
The webview is always showing the red screen with the error description even when I've implemented `renderError`. In may case (and in many others) an invalid url doesn't mean an application error, just a business error. 
How can I disable it?

**Comment by sorenbs** [comment]
I implemented renderError like this and it is working for me

webviewRenderError: (errorDomain, errorCode, errorDesc) => (
    <View style={styles.errorContainer}>
      <Text style={styles.errorTextTitle}>
        No Internet Connection
      </Text>
    </View>
  )

What rn version are you on?

Have you had a look at the source for WebView? I find it fairly quick to get a grasp of what it is doing. Maybe you can pinpoint the problem that way.

**Comment by 7ynk3r** [comment]
I'm using react-native-cli@0.1.4.

I'm getting this error message even after implementing `renderError`
![image](https://cloud.githubusercontent.com/assets/6763798/10010826/a58001c8-60a5-11e5-9195-bc6d205bb524.png)

The problem is in this line

    onLoadingError: function(event: Event) {
        event.persist(); // persist this event because we need to store it
        console.error('Encountered an error loading page', event.nativeEvent); // <===
        [...]
    }

That line gets called always. IMO that should be a `console.warning` instead given that it's absolutely normal to have invalid urls in an application. It shouldn't be at the same level as an undeclared variable or an assertion.

**Comment by sorenbs** [comment]
Seems like this commit from 26 days ago fixes that exact thing? https://github.com/facebook/react-native/commit/fa6bc1c3cd37f7e1a3c3fca46fe8dd093452544e

**Comment by 7ynk3r** [comment]
You're right, it's in master but not yet in a release.

In the last stable version 0.11, it's still an error:
https://github.com/facebook/react-native/blob/0.11-stable/Libraries/Components/WebView/WebView.ios.js#L213

Anyway, it's good to know that it's been already fixed.

Thanks!
