### ISSUE TITLE
watchman : unknown option --no-pretty error while npm start

### ISSUE THREAD

**Issue by sreejith-m-sreedharan** [facebook/react-native#2941]
Hi 
I am getting 'unknown option --no-pretty' error while trying to start development server of react-native android project.

I executed 

    npm start

Then i got this: 

    React packager ready.
    
    ERROR: Unknown option --no-pretty
    
    Watchman:  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty
    
    ERROR  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty
    
    Error: watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty
    
        at ChildProcess.<anonymous> (/home/sreejith/projects/sample/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:194:18)
        at emitTwo (events.js:87:13)
        at ChildProcess.emit (events.js:172:7)
        at maybeClose (internal/child_process.js:817:16)
        at Socket.<anonymous> (internal/child_process.js:319:11)
        at emitOne (events.js:77:13)
        at Socket.emit (events.js:169:7)
        at Pipe._onclose (net.js:469:12)

Please help

**Comment by andruschka** [comment]
+1

**Comment by MQQiang** [comment]
brew update  or  use brew install brew --head    may help

**Comment by mkonicek** [comment]
Thanks for reporting! What does `watchman --version` print for you? I'm on 3.8.0.

**Comment by aroth** [comment]
+1

**Comment by andruschka** [comment]
watchman --version outputs:
ERROR: Unknown option --version

**Comment by antigirl** [comment]
are you guys using facebooks' watchman?
not the one thats on NPM

**Comment by andruschka** [comment]
ok i fixed it this way:
npm r -g watchman 
brew update && brew upgrade
brew install watchman

**Comment by sreejith-m-sreedharan** [comment]
I was using npm's watchman. It was conflicting with the watchman installed with brew. Removed all other watchman installations in npm and installed with brew. Now it is working properly.

**Comment by danoctavian** [comment]
the solution to this is not clear.

what version of watchman are we supposed to use? the latest version of watchman is 3.8.0 as of now  and this error happens. do i need to downgrade?

i did not install watchman with npm, but with brew.

Thank you.

**Comment by Ahrengot** [comment]
Still seeing this issue. None of the above fixed it for me. Running watchman 3.8.0

**Comment by alfrednerstu** [comment]
Also having this issue with 3.8.0

**Comment by 3210jr** [comment]
I have just solved an issue similar to this one by running

$ sudo chown -R $(whoami):admin /usr/local

I must have messed with the permissions at one point or the other.
Hope it helps!

**Comment by mihriminaz** [comment]
brew uninstall watchman
brew link pcre
brew install --HEAD watchman

and be sure that you changed the localhost with your localhost url (ifconfig command to check -> http://127.0.0.1:8081/index.ios.bundle?platform=ios&dev=true in my case)

**Comment by philopian** [comment]
awesome thanks!!

**Comment by Alexintosh** [comment]
Same problem with watchman 4.5.0

**Comment by nouh** [comment]
same problem with watchman 4.5.0

**Comment by karna41317** [comment]
same problem with watchman 4.5.0

**Comment by Gagege** [comment]
My current solution is to just completely uninstall watchman. I can still develop without it.

**Comment by theobouwman** [comment]
same with watchman 4.5.0

**Comment by pycal** [comment]
updating xquartz to latest fixed this
https://www.xquartz.org/

**Comment by amonmoce** [comment]
If $watchman --version does not work, you are not using the appropriate watchman. Uninstall NPM watchman by $sudo npm r -g watchman and re-install it with brew $brew install --HEAD watchman. If you had install with brew before, first uninstall with $brew uninstall watchman. So better:

sudo npm r -g watchman
brew uninstall watchman
brew install --HEAD watchman

**Comment by umarF** [comment]
Any resolutions towards breaking in  watchman 4.5.0 ?!

**Comment by scerelli** [comment]
same error  

```
 ERROR  watchman--no-pretty get-sockname returned with exit code 1 2016-05-31T12:59:39,512: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-31T12:59:39,513: [cli] unable to talk to your watchman on /usr/local/Cellar/watchman/HEAD/var/run/watchman/voodo-state/sock! (Undefined error: 0)

Error: watchman--no-pretty get-sockname returned with exit code 1 2016-05-31T12:59:39,512: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-31T12:59:39,513: [cli] unable to talk to your watchman on /usr/local/Cellar/watchman/HEAD/var/run/watchman/voodo-state/sock! (Undefined error: 0)```

**Comment by asarazan** [comment]
+1 here please reopen.

**Comment by jiyinyiyong** [comment]
Same here. Why is this old bug happening again?

**Comment by firegnu** [comment]
watchman 4.5--------close Deco will be ok

**Comment by austinkelleher** [comment]
+1 getting this with watchman 4.5.0

**Comment by mustafakucuk** [comment]
My problem is solved

```
brew uninstall watchman
brew link pcre
brew install --HEAD watchman

```
Thanks @mihriminaz;

**Comment by npomfret** [comment]
Non of these solutions are working for me.  Using watchman v4.6.0

**Comment by dovy** [comment]
```
brew uninstall watchman
brew link pcre
brew install --HEAD watchman
```

Worked for me as well. Seemed like pcre needed an update.

**Comment by karna41317** [comment]
if u are using DECO, close it and run the app again -- worked for me

**Comment by s2zaman** [comment]
I uninstalled and then installed the `watchman`

Got solution from hint provided by **amonmoce** ; helped me completely :)
https://github.com/facebook/react-native/issues/2941#issuecomment-222323506

I followed **andruschka** and **mihriminaz**, but use the command with `sudo`, it will surely solve it.

**Comment by encodi** [comment]
I used the solution of uninstalling it and reinstalling it with --HEAD using brew and it worked fine. Thanks!

**Comment by rishabh7257** [comment]
I was also on the same boat, but with below three line execution it resolved my error. Also make sure to close the deco.
`brew uninstall watchman
npm r -g watchman
brew install --HEAD watchman`

**Comment by salapao2136** [comment]
+1 for linux

**Comment by jzhen** [comment]
+1 for closing Deco.

**Comment by TGrooves-208** [comment]
I had the same errors and it had to do with me downloading Deco. I deleted it and everything seems to be working fine now using. watchman 4.5.0

**Comment by JulianKingman** [comment]
This happened to me after migrating to a new laptop. Long story short, all my files had the wrong owner UID, running this on my home folder fixed this particular issue: `sudo chown -R 501 ~`, where 501 is your UID.

**Comment by doudounannan** [comment]
In fact, the error notices " ERROR  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2017-07-06T15:33:28,862: [0x7fffb4e823c0] the permissions on /usr/local/var/run/watchman/zhengmeiyu-state allow others to write to it. Verify that you own the contents and then fix its permissions by running `chmod 0700 /usr/local/var/run/watchman/zhengmeiyu-state`",I try above solutions, but still did not solve the issue.Then I run $ chmod 0700 /usr/local/var/run/watchman/zhengmeiyu-state, it solves.

**Comment by BryanCrotaz** [comment]
Same bug with watchman 4.9.0 on Windows. Works ok for a while then starts doing this (in `ember serve` from a cmd prompt with admin rights) and only way to fix is reboot

**Comment by Benzer1406** [comment]
Same error on macOS High Sierra with watchman 4.9.0. Tried all proposed solutions!

**Comment by mylonasg88** [comment]
watchman -v => 4.9.0
I tried (which did not make any difference):
```sh
npm r -g watchman
brew update && brew upgrade
brew install watchman
```

And then:
```sh
$ sudo chown -R $(whoami):admin /usr/local
```
That solved it for me!

**Comment by brianyeh01** [comment]
I use the solution with @mylonasg88 and @liamm12 .
It's worked for me.
My watchman version is 4.9.0.
