### ISSUE TITLE
FlatList remove last item and scroll/height position

### ISSUE THREAD

**Issue by lokomass** [facebook/react-native#30258]
## Description
With a simple FlatList, on a iOS device, when I remove the last item, FlatList height is not updated, and a blank area appears at the bottom. If a just scroll a little, then the update comes.

## Environnement
react-native: 0.62.2

## Expected Results
When item is removed, height and scroll are updated.

## Snack, code example, screenshot, or link to a repository:
Here is a snack : https://snack.expo.io/@lokomass/flatlist

## Screen

![video-1603819511](https://user-images.githubusercontent.com/7886368/97342335-64289e80-1886-11eb-8d99-57a5dd7f766c.gif)

**Comment by tusharojha** [comment]
Hi @lokomass 
After going through your issue & I found the problem inside your `deleteAddress` method.

You were comparing an object with int inside the filter. Consider the below mentioned code:

```javascript
  const deleteAddress = (id) => {
    setData(data.filter(item => item.item !== id))
  }
```

I hope it will help. If yes, then you can close the issue.

**Comment by lokomass** [comment]
Hi @tusharojha 
Thanks for your reply.
I dont understand what is my mistake.
Your code is the same as mine. Item.item and id are integer no ?
What do you think I have to write ?
Thanks again for your help

**Comment by tusharojha** [comment]
@lokomass

The check the following code blocks to get the difference between them:
- This is the code you have written for your project
```javascript 
const deleteAddress = (id) => {
    setData(data.filter(item => item !== id))
  }
```
- This is the required change in code (notice the `item.item !== id` line)
```javascript
const deleteAddress = (id) => {
    setData(data.filter(item => item.item !== id))
  }
```

**Comment by lokomass** [comment]
I've just tested your code, but It doesn't work, If a tap to "delete" button, there is no deleted block.
In my button, Have you seen the code, I use "item.item" and not "item" alone.

`onPress={() => deleteAddress(item.item)}`

**Comment by tusharojha** [comment]
Ohh I am sorry I didn't see that.

The issue is something else not with the filter call.

**Comment by lokomass** [comment]
No problem ! It's very annoying the space at the bottom, I really don't undertsand what is the matter.

**Comment by chrisglein** [comment]
Thanks for the Snack! I can see the behavior you're talking about on iOS, and not on Android or Web. The colors were distracting, but yeah... on iOS only it doesn't reset scrolling to the bottom of the list.

This actually sounds familiar, but I'm having trouble finding an existing issue on the repo. I believe I've seen similar iOS scroll issues before and I don't think this has been fixed between 0.62 and now.

**Comment by lokomass** [comment]
Thanks for solution
I’ve updated RN but this doesnt fix my bug
How i can do this please ?
