### ISSUE TITLE
Building from source plugin 'com.facebook.react.codegen' not found

### ISSUE THREAD

**Issue by wvfan** [facebook/react-native#30271]
## Description
I followed the instruction of building from source, but when I tried to run 'react-native run-android', it shows that the plugin 'com.facebook.react.codegen' was not found.

## React Native version:
master

## Steps To Reproduce
1. Install the sdk (I have installed 28, 29 and 30) and ndk on Win10, ARM
2. Install react-native master using npm
3. Modify files mentioned in Building from source instruction
4. Add ~/.gradle/init.gradle, and set the buildDir to "D:/tmp"
5. Run 'react-native run-android' under project folder

Here is the detail:

Jetifier found 1089 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Launching emulator...
error Failed to launch emulator. Reason: Could not start emulator within 30 seconds..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Company\D-Engraver\projects\hashtag2\program\node_modules\react-native\ReactAndroid\build.gradle' line: 10

* What went wrong:
Plugin [id: 'com.facebook.react.codegen'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

**Comment by djorkaeffalexandre** [comment]
Hey @wvfan, any luck?
I'm running into the same problem...

**Comment by ajpaulingalls** [comment]
there must be an additional dependency required to bring down the new gradle plugin, but I can't find any docs anywhere on how to reference it in build.gradle.

**Comment by wvfan** [comment]
Finally I give up using master. I just use the last release version 0.63 which does not use codegen, and it works. One more thing that I encountered but not shown on document is the hermes/DebuggerAPI.h import issue. The solution is to copy all files under node_modules/hermes-engine/android/include/hermes to node_modules/react-native/ReactCommon/hermes. I just want to change a little bit Java code to solve the overflow touch issue but it takes me 3 days :( Hope you can save some time.

**Comment by djorkaeffalexandre** [comment]
@wvfan thank you! You saved my day, I'll need to use a own build of react-native since they never look into my pull request..
I've spent two days into this issue without lucky, I hope this will be fixed before launch 0.64 version....
https://github.com/facebook/react-native/pull/28659

**Comment by djorkaeffalexandre** [comment]
@wvfan are you facing some problem related to libs that are using `.tsx` when you use your own builded react-native? :/
![Screen Shot 2020-11-05 at 12 03 14 PM](https://user-images.githubusercontent.com/29778115/98257818-e4be5d80-1f5e-11eb-9619-6d6be243f0ca.png)
I've already updated metro and babel/core.. :(

**Comment by wvfan** [comment]
I think it should have a type name like 'export type StackNavigator = {'. Typescript is supported by react-native well and I didn't do any config to use it.

**Comment by djorkaeffalexandre** [comment]
Fixed by updating the self builded to `v0.63.2` tag.
Thanks :)

**Comment by rectified95** [comment]
I'm seeing this as well, marking for escalation.

**Comment by lyahdav** [comment]
I don't have a fix, but this happens because the codegen stuff assumes the system can run .sh scripts, which Windows can't.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/tree/master/packages/react-native-codegen

```
yarn add --dev react-native-codegen
```

**Comment by rectified95** [comment]
@fabriziobertoglio1987  FYI:  this command doesn't work on Windows OOTB (the `yarn run` command in package.json calls `rm -rf lib ` which is not a command supported on Windows (this issue is about a failing source build on Windows). Even after I removed the `lib` directory manually and ran  the node script by hand, the codegen task still failed.

@wvfan I have a PR out fixing this:
https://github.com/facebook/react-native/pull/30535

**Comment by fabriziobertoglio1987** [comment]
this issue is not solved for me, when I do `yarn add --dev react-native-codegen` the sourceode from my react-native master change commit .. and does not use the latest master

this is very bad behaviour as I have been working all day, but `ReactAndroid` sourcecode was not the latest commit from my react-native fork. 

this error should not come out when buildind from source. You can not have `react-native-codegen` in your package.json

**Comment by sergeymorkovkin** [comment]
Looks like `react-native-codegen` package installed from npmjs doesn't contain any Java sources. Instead, we need to get it from `react-native/packages/react-native-codegen`.

**Comment by rnike** [comment]
@sergeymorkovkin How do you get `react-native-codegen` from `react-native/packages/react-native-codegen`? I simply do `cp -R ../packages/react-native-codegen ./node_modules/` in `react-native/template` but didn't work.

**Comment by sergeymorkovkin** [comment]
@rnike Just use `git clone` on top of standard `npm i`. E.g. 
`git clone --depth 1 -b 0.64-stable git@github.com:facebook/react-native.git ./node_modules/react-native`. The thing is packages directory won't be included in NPM distribution, as stated [here](https://github.com/facebook/react-native/blob/master/package.json#L16).

**Comment by iceAnson** [comment]
> @rnike Just use `git clone` on top of standard `npm i`. E.g.
> `git clone --depth 1 -b 0.64-stable git@github.com:facebook/react-native.git ./node_modules/react-native`. The thing is packages directory won't be included in NPM distribution, as stated [here](https://github.com/facebook/react-native/blob/master/package.json#L16).

can you provide the plugin classpath?

**Comment by patelnets** [comment]
> Looks like `react-native-codegen` package installed from npmjs doesn't contain any Java sources. Instead, we need to get it from `react-native/packages/react-native-codegen`.

how do we get this to work then?

**Comment by iceAnson** [comment]
finally i have a fix with this problem:

1、build plugin reac-native-codegen from 'react-native/packages/react-native-codgen' and uploadArchives to my own private maven.
2、the first problem you got maybe is the CodegenPluginExtension.jsRootDir is null, you can set this params as 'xxxx/react-native/Libraries' ,it will fix this;
3、if you find some module not found , cd react-native ,npm install xxx。it will be ok

**Comment by 0x0a0d** [comment]
> finally i have a fix with this problem:
> 
> 1、build plugin reac-native-codegen from 'react-native/packages/react-native-codgen' and uploadArchives to my own private maven.
> 2、the first problem you got maybe is the CodegenPluginExtension.jsRootDir is null, you can set this params as 'xxxx/react-native/Libraries' ,it will fix this;
> 3、if you find some module not found , cd react-native ,npm install xxx。it will be ok

can you please write it step by step :(

**Comment by robertying** [comment]
I think right now, it is better to build directly in React Native repo, rather than build in your app's repo as a dependency. Build react native, and then push the whole repo with artifacts to GitHub. Use GitHub repo's URL to install your custom react native.

Here is what I have done to build patched RN (mostly just following the [wiki](https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native)):

```sh
git clone https://github.com/facebook/react-native
cd react-native
git checkout v0.64.1 # or any other release

# now make changes to the code

# build android artifacts
docker run --rm --name rn-build -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android /bin/sh -c "./gradlew installArchives --no-daemon"
```

---

Note: if the gradle daemon unexpectedly disappears, try minimize the max ram usage in the root  `gradle.properties`:

```gradle
org.gradle.jvmargs=-Xmx1024m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

and check `./gradlew` is invoked with `--no-daemon`; this may help a bit.

---

After the build succeeds, include build artifacts `android` in the git:

```sh
git add android --force
git commit -m 'Release for some patches'
git checkout -b release-fix-something
git remote set-url origin https://github.com/myusername/react-native
git push origin release-fix-something:master
```

In your app's repo, install react-native by your fork:

```sh
yarn add https://github.com/myusername/react-native.git
```

**Comment by Trex28** [comment]
You can check my solution here: https://github.com/facebook/react-native/issues/31176#issuecomment-851505561
