### ISSUE TITLE
ReactNative app craches on Android 11 device with targetSdkVersion 30

### ISSUE THREAD

**Issue by volodymyrtaliar** [facebook/react-native#30366]
## Description
ReactNative app crashes on Android 11 device with targetSdkVersion 30.

## React Native version:
`react-native info` output:
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 209.25 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.2, 30.0.0, 30.0.1
      System Images: android-26 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## [Updated] Steps To Reproduce

0. Connect Android 11 device or create Android 11 emulator
1. **$ react-native init MyApp --version 0.63.2**
2. Update targetSdkVersion and compileSdkVersion to be 30 in build.gradle
3. Open new terminal window and do: **$ cd MyApp && react-native start --port 8082**
4. In previous terminal window do: **$ cd MyApp && react-native run-android --port 8082**

## Actual Results
Exception in native call
    java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:234)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:258)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1293)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:923)

## Expected Results
App should build and run successfully on Android 11 device/emulator with targetSdkVersion 30

**Comment by vomchik** [comment]
Make sure that you run ‘react-native start’

**Comment by volodymyrtaliar** [comment]
> Make sure that you run ‘react-native start’

I did run ‘react-native start’, the issue is still there.

**Comment by dulmandakh** [comment]
Some dependencies, like OkHTTP3, crashing when targetSdkVersion is 29 or above, please don't change this. 0.63.4 and 0.64 bumped all dependencies to latest ones.

**Comment by gourav-singhal** [comment]
Getting this issue on RN version 0.62.2 as well

**Comment by nlaitanatix** [comment]
I have similar error for `react-native@0.61.5`. I set only `targetSdkVersion` on `29` and solved my problem.
Notice that I don't change `compileSdkVersion`, that's stills in `30`

**Comment by manohar-octifi** [comment]
Why is it closed changing targetSdkVersion back to 29 is not a permanent fix, It is mandatory to update targetSdkVersion to 30 before November for existing apps and before August for new apps

**Comment by pokatomnik** [comment]
Any updates on that? As far as I know Google [will require](https://developer.android.com/distribute/best-practices/develop/target-sdk) `targetSDKVersion = 30` starting from November 2021.

**Comment by manohar-octifi** [comment]
The crash fixed for me on updating sentry/react-native library, please check your dependencies support targetsdkversion 30

**Comment by girish54321** [comment]
🔥🔥🔥
Finally 🦾 fixed by help form 💻 [stack-overflow](https://stackoverflow.com/questions/67982247/react-native-app-crashes-on-android-11-on-launch-without-giving-error)

**Comment by ttkien** [comment]
> The crash fixed for me on updating sentry/react-native library, please check your dependencies support targetsdkversion 30

It works for me 💯 💯 💯 💯 💯

**Comment by carefreeav09** [comment]
@girish54321  where did you add the lines? 

implementation("com.squareup.okhttp3:okhttp:4.9.1")
implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1") ?

**Comment by girish54321** [comment]
@carefreeav09 
At `/projectName/android/app/build.gradle`
Under `dependencies` 

```
dependencies {
      //------------

    implementation("com.squareup.okhttp3:okhttp:4.9.1")
    implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")

  //--------
}
```

**Comment by ashishprasad2163** [comment]
@carefreeav09 
```
implementation("com.squareup.okhttp3:okhttp:4.9.1")
implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1") 
```
Did it work for you? 
I added this but still crashing.

**Comment by ErickMaeda** [comment]
> The crash fixed for me on updating sentry/react-native library, please check your dependencies support targetsdkversion 30

It work's for me!

My sentry package is now: `"@sentry/react-native": "^2.0.0"`

And followed to migration guide from their docs. https://docs.sentry.io/platforms/react-native/migration/#from-1x-to-2x

**Comment by ashishprasad2163** [comment]
@ErickMaeda What version of react-native?

**Comment by ErickMaeda** [comment]
> @ErickMaeda What version of react-native?

@ashishprasad2163 
`"react-native": "0.59.10"`

**Comment by ashishprasad2163** [comment]
@ErickMaeda  Ok Thanks😊. I upgraded sentry to 2.0.0. Tried @carefreeav09's solution. Upgraded clever tap also. Still, the app is crashing on android 11 devices without any error and working fine on android 9 and below devices. 

I'm new to mobile development. Please suggest some way to debug it. I'm on "react-native": "^0.60.5"

**Comment by manohar-octifi** [comment]
@ashishprasad2163 Try running the release build with ``logcat`` you can find the package that's causing the issue

1. Create an APK and  install it on a device
2. connect the device with USB
3. Run ``adb logcat`` to see logs (better if you do it from Android Studio)
4. Now open app on your device and notice crash logs

**Comment by ashishprasad2163** [comment]
@manohar-octifi Thanks for sharing the steps. 

I did as you said and got this. Is this useful?
I was searching this on StackOverflow and GitHub, maybe something is wrong with the webview package. Not sure.

```
--------- beginning of crash
2021-11-19 02:29:35.780 20128-20221/? A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x728afff000 in tid 20221 (mqt_js), pid 20128 (angle.traveller)
2021-11-19 02:29:35.802 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.817 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.821 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.826 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.843 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.853 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.874 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.891 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.901 726-726/? E/qdmetadata: paramType 2048 not supported
2021-11-19 02:29:35.921 20235-20235/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG: pid: 20128, tid: 20221, name: mqt_js  >>> com.traveltriangle.traveller <<<
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG: uid: 10205
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x728afff000
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x0  000000728ba1c6d0  x1  000000728afff000  x2  0000000000000000  x3  000000728b124c90
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x4  000000728b42c960  x5  000000728b124d00  x6  fff9000000000000  x7  fff9000000000000
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x8  0000007297382ca4  x9  ffff000000000000  x10 000000728b400000  x11 000000728b42c8a8
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x12 fff9000000000000  x13 fff9000000000000  x14 0000000000000000  x15 000000000001ffff
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x16 00000072974b9718  x17 000000760facf400  x18 0000000000000038  x19 000000728ba1c6d0
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x20 b40000745ea84af0  x21 b40000745ea84850  x22 0000000000000000  x23 000000728afff000
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x24 000000728ba1f000  x25 b40000728affe550  x26 0000000000000000  x27 b40000745ea84d50
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     x28 0000000000000000  x29 000000728ba1c630
2021-11-19 02:29:35.922 20235-20235/? A/DEBUG:     lr  0000007297343f78  sp  000000728ba1c5b0  pc  0000007297382ca4  pst 00000000a0000000


```

**Comment by rahamin1** [comment]
None of the above suggestions worked for me. As in your case, my app, using targetSdkVersion 30, is running properly on android 7 and 8 but is crashing on android 11.

Does anybody have another idea?
