### ISSUE TITLE
Android Scrollview ContentInset/ContentOffset do not behave properly.

### ISSUE THREAD

**Issue by Dellybro** [facebook/react-native#30533]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

Content Offset and Content Inset do not work for Android devices on React Native ScrollViews

## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 91.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/Dellybro/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a horizontal scrollview and attempt to use content inset and content offset. Nothing will happen

## Expected Results
Describe what you expected to happen.

I would expect the same results as iOS with contentInset is moves the start and contentOffset is moves the initial starting value

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

https://stackoverflow.com/questions/65014040/react-native-android-scrollview-content-inset-content-offset-not-applied

Please review this stackoverflow question which has all of the information about my current situation.

**Comment by TuTejsy** [comment]
The same for me

**Comment by lukebrandonfarrell** [comment]
This is an issue in "react-native": "0.62.2"

**Comment by Dellybro** [comment]
So apparently, for android you must use padding.

**Comment by fabriziobertoglio1987** [comment]
this must have been solved with https://github.com/facebook/react-native/commit/ed29ba13f97f240c91fdf6c0ef3fb601046697b9 available since 0.63.4 see changelog at https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by likern** [comment]
Can confirm that for `0.63.3` `contentOffset` for Android didn't work, and works for `0.63.4` version.

**Comment by omaryoussef** [comment]
@fabriziobertoglio1987 It seems to only fix `contentOffset` but not `contentInset`. Can confirm `contentInset` is not working at all on Android.

**Comment by Gregoirevda** [comment]
`contentOffset` is working well in 0.63.3! A difference compared to ios is that `contentOffset` `x` or `y` doesn't accept going from null/undefined to a number. `0` has to be the default

**Comment by Hexo97** [comment]
`contentInset` is still not working on Android. alternatively, you can pass style to `contentContainerStyle`.
e.g. : `contentContainerStyle={{ paddingBottom: 150 }}`

**Comment by bolan9999** [comment]
Why not accept this [PR](https://github.com/facebook/react-native/commit/ed29ba13f97f240c91fdf6c0ef3fb601046697b9) ?

**Comment by bolan9999** [comment]
@Gregoirevda It does not work on the latest version, but 0.63.4 works.

**Comment by YanislavSpaceIQ** [comment]
Still have this issue on v.0.68.1. Setting contentOffset doesn't work, but initialScrollIndex works.

**Comment by AlenToma** [comment]
I am having this issue with `react-native 0.68.2`

**Comment by AlenToma** [comment]
This is a work a round if someone is intressted.

```ts
    useEffect(()=> {
        if (scrollviewRef.current)
        scrollviewRef.current.scrollTo({...contenOffset, animated:false})
    },[contenOffset])
```

**Comment by kaueDM** [comment]
Fixed on https://github.com/facebook/react-native/commit/be260b9f479a3b55ee43d2959d2c49fd3c1eb4ac

**Comment by SimpleCreations** [comment]
Unfortunately this is still an issue

**Comment by santirodriguezaffonso** [comment]
Can confirm still not working on Android OS. Current workaround to have the same behavior on iOS & Android: 
`contentContainerStyle={{ paddingBottom }}`

**Comment by SimpleCreations** [comment]
This is still an issue

**Comment by SimpleCreations** [comment]
Still an issue

**Comment by SimpleCreations** [comment]
Not stale

**Comment by SimpleCreations** [comment]
Not stale
