### ISSUE TITLE
I have an error when make debug build.  (error node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js: #<WeakSet> could not be cloned.) anyone have this error

### ISSUE THREAD

**Issue by Rananjaya** [facebook/react-native#31413]
error node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js: #<WeakSet> could not be cloned. Run CLI with --verbose flag for more details.
Error: #<WeakSet> could not be cloned.
    at Object.serialize (v8.js:202:7)
    at _default (/home/rananjaya/Desktop/child_app/ch/node_modules/@babel/core/lib/transformation/util/clone-deep.js:16:30)
    at normalizeFile (/home/rananjaya/Desktop/child_app/ch/node_modules/@babel/core/lib/transformation/normalize-file.js:52:36)
    at normalizeFile.next (<anonymous>)
    at run (/home/rananjaya/Desktop/child_app/ch/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at /home/rananjaya/Desktop/child_app/ch/node_modules/@babel/core/lib/transform-ast.js:20:41
    at Generator.next (<anonymous>)
    at evaluateSync (/home/rananjaya/Desktop/child_app/ch/node_modules/gensync/index.js:251:28)

**Comment by klaaz0r** [comment]
I have a similar issue with all kinds of modules

**Comment by siderakis** [comment]
https://github.com/oblador/react-native-vector-icons/issues/1334

**Comment by japhet247** [comment]
I think the problem might be with @babel/core and @babel/runtime versions. I downgraded to the below versions and it worked for me;

"@babel/core": "^7.12.9",
"@babel/runtime": "^7.12.5",

**Comment by dennislky** [comment]
Sadly, I am still with the same issue, and doesn't find a way out.

For me, it seems the problem is when babel (react native by default is using metro-react-native-babel-preset) trying to transform file, it requires to deep clone the value, and it is using v8.deserialize(v8.serialize(value)) to do that; however, in some versions of v8, the file have been recognized as WeakSet, and therefore threw the DataCloneError.

I have tried several ways, including changing the clone method as per the following code suggested by @amiller-gh
`
const { MessageChannel, receiveMessageOnPort } = require('worker_threads');
const { port1, port2 } = new MessageChannel();
function structuredClone (o) {
  port1.postMessage(o);
  return receiveMessageOnPort(port2).message;
}
`
And was suspecting v8 version difference between different node versions (v12.22.1, v14.16.1, v16.0.0), and the difference between JavaScriptCore and v8, but it seems all are not the case.

Would anyone have other workarounds that may be useful? Thanks in advance!

**Comment by jmikulka** [comment]
As @japhet247 suggested, downgrading `@babel/core` and `@babel/runtime` versions fixes the problem.

See https://github.com/oblador/react-native-vector-icons/issues/1334#issuecomment-832287494.

**Comment by dennislky** [comment]
Hi @jmikulka, thanks for the reply, I had tried with @japhet247's answer too, and I had even tried downgrading React Native version back to 0.63.4 with the corresponding dependencies, and still the same case, successfully compiled, but got the `#<WeakSet> could not be cloned.` error during bundling stage.

**Comment by jmikulka** [comment]
> Hi @jmikulka, thanks for the reply, I had tried with @japhet247's answer too, and I had even tried downgrading React Native version back to 0.63.4 with the corresponding dependencies, and still the same case, successfully compiled, but got the `#<WeakSet> could not be cloned.` error during bundling stage.

I don't think you need to downgrade React Native itself, just the `@babel/core` and `@babel/runtime`.

**Comment by siderakis** [comment]
I've tried all the mentioned versions of @babel/core and @babel/runtime with no luck. In-between builds I ran react-native-clean-project to do a full clean. I also removed as many devDependencies as I could and only have a few in addition to [those](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.64.2/RnDiffApp/package.json) in the sample app. 

@dennislky Did you get it working?

**Comment by NullPainter2** [comment]
@siderakis @dennislky Metro depends on newer version of babel. Older version can be forced inside package.json this way:
```
  "resolutions": {
    "@babel/core": "7.12.17",
    "@babel/runtime": "7.12.18"
  },
```

Forcing this version worked for me.

**BUT Cleaning up yarn.lock made app work on newer version. ** I found it out by accident ... Babel is made of like million packages for some reason. So I cleaned up yarn.lock to avoid duplication of all those babel packages, so multiple minor version of all of babel packages are resolved to just the newest version which was inside file. Then. When I just out of curiosity removed "resolve" from package.json and deleted resolution to old version, newer babel version was working just fine.

Currently newer version which works for me is this:

@babel/core 7.15.15
@babel/runtime 7.12.18

**Comment by NullPainter2** [comment]
Just tried deleting yarn.lock and reinstalling and fixing some unrelated stuff (packages I did not wanted to update) and there was no need to revert to older babel at all.

**Comment by kolarus** [comment]
Still have the same issue even removing yarn.lock, downgrading babel does not seem to resolve this. Happens after upgrade 0.64.2-0.65.1

**Comment by steffen25** [comment]
Did someone find a solution to this problem? I also tried to downgrade babel etc. but still no luck. 
Im experiencing the same error as OP.

`node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js: #<WeakSet> could not be cloned.` 

I see OP opened an issue in the repository of this Keyboard library but unfortunately no activity.
https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/481

@Rananjaya Are you still running into this issue if not Im curious to know what you did to solve it.

**Comment by dlajarretie** [comment]
I'm having the same issue as described in https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/481, even when downgrading babel dependencies.

@steffen25 Did you find a solution ?
