### ISSUE TITLE
failed install hermes-engine

### ISSUE THREAD

**Issue by agungs17** [facebook/react-native#31505]
pods install failed install hermes engine on RN 0.64.1

Installing hermes-engine (0.7.2)

[!] Error installing hermes-engine
[!] /usr/bin/curl -f -L -o /var/folders/1_/yx65j5bj7xxg4wg1wqlr5smm0000gn/T/d20210510-11664-hephga/file.tgz https://github.com/facebook/hermes/releases/download/v0.7.2/hermes-runtime-darwin-v0.7.2.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

**Comment by rchaubey** [comment]
facing the same issue after enabling hermes in ios

**Comment by HammzaHM** [comment]
same issue here

**Comment by unknownFrequency** [comment]
Same here

**Comment by andresfelipe3112** [comment]
ninguna novedad para solucionarlo?

**Comment by daryazata** [comment]
the installation get stuck on `Installing hermes-engine (0.7.2)`

**Comment by ashishprasad2163** [comment]
Same here on iOS. RN 0.65.0

**Comment by summerkiflain** [comment]
Stuck for me too on `Installing hermes-engine (0.8.1)`
RN version: 0.65.1

**Comment by AmirDiafi** [comment]
You need to clean and re-install your pods:
1 - `sudo gem install cocoapods-clean`
2 - `pod deintegrate`
3 - `pod clean` ( this is no longer available )
4 - `pod install`
Enjoy!

**Comment by cortinico** [comment]
> update: I had to wait for some mins , but def. more than usual package install, but at the end it got installed

Please note that the installation of `hermes-engine` takes some time as the Pod needs to download ~1.2Gb of binaries.

**Comment by brunomacf** [comment]
Why am i getting this when trying to install hermes-engine?

```
Installing hermes-engine (0.69.0)

[!] Error installing hermes-engine
[!] /usr/bin/tar xf /var/folders/3k/jl2zckj12qbgrjp5jpmhr84m0000gp/T/d20220623-79686-2rfd1n/file.tgz -C /var/folders/3k/jl2zckj12qbgrjp5jpmhr84m0000gp/T/d20220623-79686-2rfd1n

./destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/Versions/0/hermes: Write failed
./destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-simulator/hermes.framework/hermes: Write failed
./destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-simulator/hermes.framework/Info.plist: Write to restore size failed
./destroot/include/jsi/: Can't create 'destroot/include/jsi'
./destroot/include/hermes/TraceInterpreter.h: Write failed
./destroot/include/hermes/Public/RuntimeConfig.h: Can't create 'destroot/include/hermes/Public/RuntimeConfig.h'
./destroot/include/hermes/Public/GCTripwireContext.h: Write failed
./destroot/include/jsi/instrumentation.h: Write failed
./destroot/bin/hermesc: Write failed
./destroot/bin/hbcdump: Write failed
./destroot/bin/hdb: Write failed
./destroot/bin/hermes: Write failed
./destroot/bin/hvm: Can't create 'destroot/bin/hvm'
tar: Error exit delayed from previous errors.
```

any ideas? i tryied to do a pod clean then pod install but same result.

**Comment by cortinico** [comment]
Closing as this was resolved essentially. Please open a new issue if the issue comes back.

**Comment by ofavor** [comment]
In "node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec", there's an environment variable "HERMES_ENGINE_TARBALL_PATH"
`
if ENV.has_key?('HERMES_ENGINE_TARBALL_PATH')
  Pod::UI.puts '[Hermes] Using pre-built Hermes binaries from local path.' if Object.const_defined?("Pod::UI")
  source[:http] = "file://#{ENV['HERMES_ENGINE_TARBALL_PATH']}"
`
So I downloaded the tar with chrome used the command below:
`
HERMES_ENGINE_TARBALL_PATH="/Users/henry/Downloads/hermes-runtime-darwin-v0.70.0.tar.gz" pod install --verbose
`
It works!

**Comment by conor909** [comment]
@ofavor that is a bit hacky, do you know why this is happening?

**Comment by hit-cod** [comment]
but what if i want to update all dependencies in ios folder. so i go with pod install, then get an hermes error (screen) -> use @ofavor solution to update it, but in the case all other dependencies, which were supposed to be installed after hermes update (with pod install command), wont be, cuz we interrupted the flow, no? i hope u get what i mean. so how to update the rest of them after using @ofavor command
<img width="604" alt="image" src="https://user-images.githubusercontent.com/65369518/189968343-2ae52b18-b733-4dc7-9625-cc6898673fc4.png">

**Comment by conor909** [comment]
Why has this issue gained traction today after 3 months, maybe an intermittent problem with the download location?

**Comment by AndreyNazarov** [comment]
indeed. got the same question, any ideas?

**Comment by hit-cod** [comment]
it seems that i didnt have enough space on mac. u can go to about this mac -> storage -> and there u will see how "available space" is going down. when it got to 0, i got an error. so i deleted everything that i could and it downloaded

**Comment by tomchify** [comment]
> Why has this issue gained traction today after 3 months, maybe an intermittent problem with the download location?

RN v0.70.0 comes bundled with hermes-engine default, so RN community may start seeing this more: https://reactnative.dev/blog/2022/09/05/version-070

**Comment by pythonName** [comment]
> pods install failed install hermes engine on RN 0.64.1
> 
> Installing hermes-engine (0.7.2)
> 
> [!] Error installing hermes-engine [!] /usr/bin/curl -f -L -o /var/folders/1_/yx65j5bj7xxg4wg1wqlr5smm0000gn/T/d20210510-11664-hephga/file.tgz https://github.com/facebook/hermes/releases/download/v0.7.2/hermes-runtime-darwin-v0.7.2.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'



> Why am i getting this when trying to install hermes-engine?
> 
> ```
> Installing hermes-engine (0.69.0)
> 
> [!] Error installing hermes-engine
> [!] /usr/bin/tar xf /var/folders/3k/jl2zckj12qbgrjp5jpmhr84m0000gp/T/d20220623-79686-2rfd1n/file.tgz -C /var/folders/3k/jl2zckj12qbgrjp5jpmhr84m0000gp/T/d20220623-79686-2rfd1n
> 
> ./destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/Versions/0/hermes: Write failed
> ./destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-simulator/hermes.framework/hermes: Write failed
> ./destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-simulator/hermes.framework/Info.plist: Write to restore size failed
> ./destroot/include/jsi/: Can't create 'destroot/include/jsi'
> ./destroot/include/hermes/TraceInterpreter.h: Write failed
> ./destroot/include/hermes/Public/RuntimeConfig.h: Can't create 'destroot/include/hermes/Public/RuntimeConfig.h'
> ./destroot/include/hermes/Public/GCTripwireContext.h: Write failed
> ./destroot/include/jsi/instrumentation.h: Write failed
> ./destroot/bin/hermesc: Write failed
> ./destroot/bin/hbcdump: Write failed
> ./destroot/bin/hdb: Write failed
> ./destroot/bin/hermes: Write failed
> ./destroot/bin/hvm: Can't create 'destroot/bin/hvm'
> tar: Error exit delayed from previous errors.
> ```
> 
> any ideas? i tryied to do a pod clean then pod install but same result.

but i have this issue:

[!] Error installing hermes-engine
[!] /usr/bin/curl -f -L -o /var/folders/py/ywshkpqj4pvb285158rlrbb40000gn/T/d20221011-92879-f2mx73/file.tgz https://github.com/facebook/react-native/releases/download/v0.70.2/hermes-runtime-darwin-v0.70.2.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 43  496M   43  215M    0     0  1899k      0  0:04:27  0:01:56  0:02:31 1913k
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

**Comment by proto1994** [comment]
> @conor909
> 
> > @ofavor that is a bit hacky, do you know why this is happening?
> 
> Just like @cortinico said, hermes-engine is a little bigger, curl cannot download it due to a network error(timeout, peer reset...). I had to download it by chrome or other utilities.

Thank God, I solved it with this method, but need to be reminded that the file path cannot have spaces

**Comment by proto1994** [comment]
> 
Thank God, I solved it with this method, but need to be reminded that the file path cannot have spaces

**Comment by proto1994** [comment]
> [ofavor](https://github.com/ofavor) commented [on 13 Sep](https://github.com/facebook/react-native/issues/31505#issuecomment-1245424395)
In "node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec", there's an environment variable "HERMES_ENGINE_TARBALL_PATH"
if ENV.has_key?('HERMES_ENGINE_TARBALL_PATH') Pod::UI.puts '[Hermes] Using pre-built Hermes binaries from local path.' if Object.const_defined?("Pod::UI") source[:http] = "file://#{ENV['HERMES_ENGINE_TARBALL_PATH']}"
So I downloaded the tar with chrome used the command below:
HERMES_ENGINE_TARBALL_PATH="/Users/henry/Downloads/hermes-runtime-darwin-v0.70.0.tar.gz" pod install --verbose
It works!

--------------------
Thank God, I solved it with this method, but need to be reminded that the file path cannot have spaces

**Comment by Gdevil** [comment]
tried many times, still not work

**Comment by pacyL2K19** [comment]
> tried many times, still not work

I went to this issue a couple of times this week, here are my insights 
From what I experienced, there are a couple of probable reasons why you are facing this, as @ofavor @proto1994 said:
- Either your network is slow and getting a timeout error, then stops the installation ==> https://github.com/facebook/react-native/issues/31505#issuecomment-1245424395 this solution worked for me one time
- Either you don't have enough space on your disk, then you will get a ` Write failed` just because the space is not enough (even though your network is perfect :) ). If this is your case, you need to clean up your disk that will work, the solution worked for me
RN is now supporting the Hermes engine on ios to increase its performance, since the RN 0.64.0 but the package itself is too weight, to avoid this issue, u need to make sure u have enough space on your disk + a good internet network
https://reactnative.dev/docs/hermes#ios

**Comment by AdiKhaparkar123** [comment]
Hello All i am using RN Version  "0.70.6"
 While Installing Pod the terminal is getting stuck on  Installing hermes-engine (0.70.6) , it nearly downloaded/ consume 4gb data but didn't proceed to the next step. 
![Screenshot 2022-12-18 at 7 35 22 PM](https://user-images.githubusercontent.com/115796804/208302792-0f7bc530-b737-4a56-9a17-e2182ca40284.png)

**Comment by aoulaa** [comment]
what happend at the end ?

**Comment by jsonchou** [comment]
Http download
   $ /usr/bin/curl -f -L -o /var/folders/q3/kjnn366n7ndcg1m4130jgctc0000gn/T/d20221223-97777-r61yhm/file.tgz
   https://github.com/facebook/react-native/releases/download/v0.70.6/hermes-runtime-darwin-v0.70.6.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3
   cocoapods-downloader/1.5.1'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     2  496M    2 11.8M    0     0  15006      0  9:37:46  0:13:50  9:23:56 10407

SO SLOW...

**Comment by jsonchou** [comment]
"source": {
    "http": "file:///Users/xxx/packages/hermes-runtime-darwin-v0.70.6.tar.gz"  // replace this line
  },

/ios/Pods/Local Podspecs/hermes-engine.podspec.json

**Comment by AdiKhaparkar123** [comment]
> 

Nothing just go to IOS>podfile>{hermes_enabled => false}>Pod install >rebuild the App and it works.

The issue has been resolved

**Comment by ArthourVaSa** [comment]
It worked for me!!! THANKS!!!!

**Comment by jashanpj** [comment]
As people mentioned here, it's only about size of the Hermes engine, according to your network speed waiting for some time will do the thing. I almost waited around 10 minutes with my GSM network.

**Comment by prox2** [comment]
> Installing hermes-engine (0.71.1)
 > Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/jm/qyc0mdpj0mz8hzt4pd3pzqxh0000gn/T/d20230120-1973-rt3ctg/file.tgz
   https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.71.1/react-native-artifacts-0.71.1-hermes-ios-debug.tar.gz
   --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.4.0'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0  458M    0 3154k    0     0  21457      0  6:13:37  0:02:30  6:11:07 12578


---------------
It is so funny that mine taking around 6 hours to finish, this issue happened with "react-native": "0.71.1" fresh install.
even though my connection speed  almost 200 Mbps. so strange :(

**Comment by dondxniel** [comment]
Hello, I came across this issue too and I noticed @ofavor 's solution to download the hermes compressed file; I just need a download link. I've been googling for a few minutes and still can't seem to find it laying around anywhere.

**Comment by qnrjs42** [comment]
I changed the network and it's solved.

A wifi -> B wifi

**Comment by ssilverr** [comment]
Building on CI this also happens occasionally.

**Comment by ShivamJoker** [comment]
This is what I was looking for. 
Thanks a lot.

I manually downloaded the Hermes as well from the github release URL and provided the path in ENV and it worked.

> In "node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec", there's an environment variable "HERMES_ENGINE_TARBALL_PATH" `if ENV.has_key?('HERMES_ENGINE_TARBALL_PATH') Pod::UI.puts '[Hermes] Using pre-built Hermes binaries from local path.' if Object.const_defined?("Pod::UI") source[:http] = "file://#{ENV['HERMES_ENGINE_TARBALL_PATH']}"` So I downloaded the tar with chrome used the command below: `HERMES_ENGINE_TARBALL_PATH="/Users/henry/Downloads/hermes-runtime-darwin-v0.70.0.tar.gz" pod install --verbose` It works!

**Comment by thanhdevapp** [comment]
cd ios && pod install --verbose . Check network speed, try change dns ...., change network

**Comment by leeeGreat** [comment]
> 
when use commond:

/usr/bin/curl -f -L -o /var/folders/1_/yx65j5bj7xxg4wg1wqlr5smm0000gn/T/d20210510-11664-hephga/file.tgz https://github.com/facebook/hermes/releases/download/v0.7.2/hermes-runtime-darwin-v0.7.2.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

Error creating directory /var/folders/1_/yx65j5bj7xxg4wg1wqlr5smm0000gn.
curl: (23) Failed writing received data to disk/application
get error above, any one can help me?

**Comment by maxckelly** [comment]
I'm also getting this error after updating from 0.70.6 -> 0.71.6

**Comment by chachaxw** [comment]
> In "node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec", there's an environment variable "HERMES_ENGINE_TARBALL_PATH"
> `if ENV.has_key?('HERMES_ENGINE_TARBALL_PATH') Pod::UI.puts '[Hermes] Using pre-built Hermes binaries from local path.' if Object.const_defined?("Pod::UI") source[:http] = "file://#{ENV['HERMES_ENGINE_TARBALL_PATH']}"`
> So I downloaded the tar with chrome used the command below:
> `HERMES_ENGINE_TARBALL_PATH="/Users/henry/Downloads/hermes-runtime-darwin-v0.70.0.tar.gz" pod install --verbose`
> It works!

This is a good way, very nice!

**Comment by josiaharkson** [comment]
This worked like magic for me
[ enable Hermes for iOS by editing your ios/Podfile file ](https://reactnative.dev/docs/hermes#ios)

**Comment by faheem-cmd** [comment]
this works me `arch -arm64 npx react-native init ProjectName`

**Comment by miteshdevg** [comment]
Please check whether your PC has enough space or not !

**Comment by arunsa-hrbl** [comment]
Hi @react-native-bot 

What kind of libraries you guys are developing.  this is 2024 still we have issues with Hermes. even a sample app pod install does't work and fires with below error 

Please guide this. It was working perfectly fine 2 days back and suddenly started throwing this kind of nonsense issues, 


**➜  SampleRNLatestVersion** git:(main) ✗ cd ios
➜  ios git:(main) ✗ pod install --repo-update
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the latest commit from main.
Const Defined!
[!] Failed to load 'hermes-engine' podspec: 
[!] Invalid `hermes-engine.podspec` file: [!] Unable to locate the executable `cmake`.

 #  from /Users/arunsa/Documents/HNMyClub/RNUpGrade73/SampleRNLatestVersion/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec:116
 #  -------------------------------------------
 #        puts "Const Defined!"
 >        CMAKE_BINARY = Pod::Executable::which!('cmake')
 #        # NOTE: Script phases are sorted alphabetically inside Xcode project
 #  -------------------------------------------

[!] Do not use "pod install" from inside Rosetta2 (x86_64 emulation on arm64).
[!]  - Emulated x86_64 is slower than native arm64
[!]  - May result in mixed architectures in rubygems (eg: ffi_c.bundle files may be x86_64 with an arm64 interpreter)
[!] Run "env /usr/bin/arch -arm64 /bin/bash --login" then try again.
**➜  ios git:(main)**


My System data - 

`➜  SampleRNLatestVersion git:(main) ✗ npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 13.6.6
  CPU: (10) x64 Apple M1 Max
  Memory: 1.62 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.0
    path: ~/.nvm/versions/node/v20.12.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/node_modules/.bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.0/bin/npm
  Watchman:
    version: 2024.04.01.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/arunsa/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/arunsa/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

➜  SampleRNLatestVersion git:(main) ✗ `

**Comment by dondxniel** [comment]
@arunsa-hrbl you can always submit a PR with the fix for the issues you find on open-source software. They're open-source for this reason.
