### ISSUE TITLE
React Native not building on Xcode 12.5

### ISSUE THREAD

**Issue by yepes** [facebook/react-native#31592]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Created a RN blank project on a new mac mini m1 apple silicon. SO: Big Sur 11.3.1 
```
npx react-native init AwesomeProject
```

After that, yarn ios works fine. The app is launched correctly on the ios simulator.

if I open Xcode and try to build, I get this error:

Showing All Messages
/Users/myusername/Proyectos/AwesomeProject/ios/AwesomeProject.xcodeproj The linked library 'libPods-AwesomeProject.a' is missing one or more architectures required by this target: arm64.

## React Native version:
```
"dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.1"
  },
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a blank RN default project on an apple m1 computer
2. Check that yarn ios works just fine
3. Try to open ios/AwesomeProject.xcworkspace and hit play
4. The above error should appear

## Expected Results
The app should work when yarn ios and when running in xcode

## Snack, code example, screenshot, or link to a repository:
Just the default code created by ```npx react-native init AwesomeProject```

**Comment by yepes** [comment]
Just having a look at this issue, adding arm64 to excluded architectures seems to work. I'm not exactly sure if this is the correct way to solve this, or what implication will this have in the future:

![image](https://user-images.githubusercontent.com/1114453/119649305-c51b5380-be22-11eb-9e78-ad71962aa879.png)

Can anyone with an m1 computer please confirm this?

**Comment by dulmandakh** [comment]
@yepes could you please test https://github.com/facebook/react-native/pull/31622

**Comment by yepes** [comment]
@dulmandakh how am i supposed to test that PR? do I have to init a new RN project and apply your changes to my node modules and try?

**Comment by yepes** [comment]
@dulmandakh tried but doesn't work:

```
Showing All Messages
/Users/xxxxxxxxx/Proyectos/rn64/ios/rn64.xcodeproj The linked library 'libPods-rn64.a' is missing one or more architectures required by this target: arm64.
```

Looking your PR it seems that what you are doing is just checking if /opt/homebrew/bin exists and adding it to the path. I don't know if this is related with the issue I am facing.

Anyway, I didn't install node using homebrew (when I bought the mm was impossible) and have installed manually:

```
which node
/usr/local/bin/node
```

**Comment by chriskrogh** [comment]
Running into this issue as well on an M1 Mac, however I'm also using nvm to manage my node version. This was on a fresh project created using `npx react-native init MyApp --template react-native-template-typescript`.

package.json
```
"dependencies": {
  "react": "17.0.1",
  "react-native": "0.64.1"
},
```
`xcodebuild -version`
```
Xcode 12.5.1
Build version 12E507
```

`which node`
```
/Users/chriskrogh/.nvm/versions/node/v16.3.0/bin/node
```

**Comment by tido64** [comment]
> package.json
> 
> ```
> "dependencies": {
>   "react": "17.0.1",
>   "react-native": "0.64.1"
> },
> ```

Can you try bumping `react-native` to 0.64.2? The issue should be fixed already. I don't know who owns `react-native-template-typescript`, but you should tell them to bump `react-native` to latest.

**Comment by yepes** [comment]
I'm using the same mac mini. I just recreated a new project:

```
npx react-native init AwesomeProject
```


package.json:
```
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

yarn ios works fine.

Xcode doesn't

I openned ios/AwesomeProject.xcworkspace
Hit play selecting iphone12 14.5. I get this error almost instantly:

```
/Users/myusername/Proyectos/AwesomeProject/ios/AwesomeProject.xcodeproj The linked library 'libPods-AwesomeProject.a' is missing one or more architectures required by this target: arm64.```

Following the steps I suggested in https://github.com/facebook/react-native/issues/31592#issuecomment-848676557 works.

So, the issue is still there.

**Comment by kelset** [comment]
I'm not a big fan of duplication, so I'm going to close this.

For M1 specific issues, please comment here -> https://github.com/facebook/react-native/issues/31438
And for the Xcode 12.5 situation, refer to this troubleshooting guide -> https://github.com/facebook/react-native/issues/31480

**Comment by yepes** [comment]
With all respect, you linked to a closed issue and to an issue that has nothing to do with this. 

IMO, the default template should work fine after a clean install

**Comment by kelset** [comment]
> you linked to a closed issue

Neither of those are closed?

> has nothing to do with this.

Which one?

**Comment by yepes** [comment]
Sorry, i was on mobile and thought #31438 was closed. I will take a look at it

**Comment by chriskrogh** [comment]
> Can you try bumping `react-native` to 0.64.2?

Bumping to latest still doesn't work. I also followed the steps outlined https://github.com/facebook/react-native/issues/31480#issue-876308920 and then [here](https://github.com/aiba/react-native-m1/blob/main/README.md), and `yarn ios` still doesn't work.
