### ISSUE TITLE
TextInput caret is not visible with the property keyboardType="email-address"

### ISSUE THREAD

**Issue by gastonrd7** [facebook/react-native#32782]
### Description

the cursor is not visible, the field expects an email format.
this happens in:
Android 8.1.0 Redmi 5 Plus Model: MEG7
Android 10 Redmi Note 9S Model: M2003J6A1G
Android 10 OnePlus 7 Pro Model: GM1910

### Version

0.64.2

### Output of `react-native info`

Android 8.1.0 Redmi 5 Plus Modelo: MEG7  
Android 10 Redmi Note 9S Modelo: M2003J6A1G
Android 10 OnePlus 7 Pro Modelo: GM1910

### Steps to reproduce
SCAN QR and open expo

I found a "work around" adding by default the property caretHidden = {false}.

Remove or set the "caretHidden" property to true.

Then de issue can be show.

### Snack, code example, screenshot, or link to a repository
https://snack.expo.dev/@gastonrd7/textinput-keyboardtype-email-address

**Comment by RahulSChauhan50** [comment]
I ran your code in snack and it showed an error in placeholder prop. Looks like you are not passing Emails in string format. Use single or double-quotes
![Screenshot (86)](https://user-images.githubusercontent.com/60318300/146686042-d82fbb43-8d26-473b-b7c5-78a017f498a3.png)
. The error was gone when I passed Email as a string and the cursor was visible.

**Comment by gastonrd7** [comment]
Sorry for the source code.
I changed it and I share a link with simpler code.
I found a "work around" adding by default the property caretHidden = {false}.
Although this property is false, for the specified OS and the specified mobile device, passing it the caret is displayed.
This is a work around since we shouldn't pass it to it if it is false by default.

**Comment by AlexTaran** [comment]
Having the same issue. For me the problem reproduced on Lenovo tb 8505f and Xiaomi Redmi 9A (Android 10).
But setting caretHidden = {false} doesn't even help.

**Comment by ayman-kouzayha** [comment]
I am having this issue on my Xiaomi Pocophone F1 (Android 10), I tried to set caretHidden to false, the caret will go away as soon as I set keyboardType="email-address", I also tried to set textContentType={'emailAddress'} instead of keyboardType which did not make the keyboard switch to email mode

**Comment by 04l3x4ndr3** [comment]
set caretHidden={false}

**Comment by korayerdem89** [comment]
same issue...

**Comment by sevak995** [comment]
Solved it by adding:

keyboardType="email-address"
caretHidden={false}
textContentType="emailAddress"
autoComplete={"email"}

AND 

flex: 1
on text input style.
cd android && ./gradlew clean

**Comment by isaacbatst** [comment]
For Redmi 9T `caretHidden={false}` solved.

**Comment by maystrenkoYurii** [comment]
I found in TextInput this comment. It seems that this is how the crash was fixed. https://github.com/facebook/react-native/blob/2b93491779073d7a97e4826300d5c301c835d6d9/packages/react-native/Libraries/Components/TextInput/TextInput.js#L619

**Comment by liamjones** [comment]
> I found in TextInput this comment. It seems that this is how the crash was fixed.
> 
> https://github.com/facebook/react-native/blob/2b93491779073d7a97e4826300d5c301c835d6d9/packages/react-native/Libraries/Components/TextInput/TextInput.js#L619

Interesting, here's the relevant bit of native code for anyone interested: https://github.com/facebook/react-native/blob/2b93491779073d7a97e4826300d5c301c835d6d9/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L591C0-L605C0

**Comment by ersel** [comment]
for xiaomi mi 8 lite `caretHidden={false}` seems to work

**Comment by camilossantos2809** [comment]
On Android, using `react-native@0.73.2` and `caretHidden={false}` doesn't work for me.
However, strangely, if I change it to true, save, and then switch it back to false, it works.

```
<TextInput
      label="E-mail"
      placeholder="Digite o seu e-mail"
      style={{
        minHeight: 40,
        margin: theme.margin * 2,
        minWidth: "80%",
        fontFamily: theme.fontFamily.regular,
        color: theme.colors.black,
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius * 2,
      }}
      textAlign="center"
      editable={true}
      placeholderTextColor={"rgba(0, 0, 4, 0.4)"}
      underlineColorAndroid={"transparent"}
      textContentType="emailAddress"
      keyboardType="email-address"
      autoCapitalize="none"
      autoCorrect={false}
      caretHidden={false}
    />
```

**Comment by luffy-taro** [comment]
Still an issue on old Xiaomi device running android 10. `CaretHidden={false}` didn't work.
