### ISSUE TITLE
Android builds do not install on device

### ISSUE THREAD

**Issue by djMax** [facebook/react-native#33063]
### Description

There is a lot of "surface area" for the problem here, but I'm getting the following issue after upgrading from 0.66.4 to 0.67.2 with the apk built by *appcenter*:

```
2022-02-07 18:05:08.382 1175-1763/? E/NativeLibraryHelper: Library 'libmapbufferjni.so' is not page-aligned - will not be able to open it directly from apk.
2022-02-07 18:05:08.383 1175-1763/? W/NativeHelper: Failure copying native libraries [errorCode=-2]
2022-02-07 18:05:08.383 1175-1763/? E/PackageInstallerSession: Commit of session 1899979103 failed: Failed to extract native libraries, res=-2
```

I am able to build and run on device locally, but this also used to work just fine in appcenter. Let the queries begin!

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 116.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Users/memetral/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

So many things are non-standard - monorepo, typescript, appcenter... I have a diff of "works-vs-doesn't-work" that I am slowly bisecting and will update this issue with results.

**Comment by djMax** [comment]
For other problems, I had set kotlin_version to 1.6.10. Investigating whether dropping it back down helps.

**Comment by djMax** [comment]
I can confirm that adding:

```
android:extractNativeLibs="true"
```

To AndroidManifest.xml fixes it, but I think this is a bad practice in general, right?

**Comment by cortinico** [comment]
> I am able to build and run on device locally, but this also used to work just fine in appcenter.

What do you mean with "in appcenter"? I assume you referred to the Play Store.

> To AndroidManifest.xml fixes it, but I think this is a bad practice in general, right?

Yes that should be discouraged. Your native libraries won't be mmapped and will result in a higher disk usage of your app.

I believe the problem is that your final APK is not zipaligned correcty. See: https://stackoverflow.com/a/41263135 
Which version of the Android SDK are you using? Have you tried updating it?

**Comment by djMax** [comment]
By appcenter I mean Microsoft AppCenter, the CI/remote update tool. I'm using 31. I suspected zipalign too, and I ran zipalign verification (with 4) on the apk and it came back clean. I can see that it is running zipalign in the build flow, but it's hard to tell if it is in the "right place" - and of course the key question is why updating RN (which also brought gradle to 7.2, which is more suspicious) causing this to happen...

```
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
```

**Comment by cortinico** [comment]
> and of course the key question is why updating RN (which also brought gradle to 7.2, which is more suspicious) causing this to happen...

Could you try to bump Gradle to 7.3.3 and AGP to 7.0.4 without updating RN to see if the issue is there?

**Comment by djMax** [comment]
Looks like it may not be so simple: 

```
* What went wrong:
A problem occurred evaluating project ':react-native-touch-through-view'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by cortinico** [comment]
> Yes, though where do I update AGP? I don't see a specific AGP version in my build files. I'm hoping you mean this:

That's correct. AGP is the Android Gradle Plugin, which is the `gradle` artifact in the `com.android.tools.build` group you correctly pointed.

> which was 4.2.2, so quite the upgrade.

Google changed version numbering and moved from 4.2 to 7.0 so you're just going to the upcoming stable: https://developer.android.com/studio/releases/gradle-plugin

> Looks like it may not be so simple:

The `react-native-touch-through-view` library you're using is using a really old version of AGP which is incompatible. Specifically: https://github.com/simonhoss/react-native-touch-through-view/blob/master/android/build.gradle#L14

So you should open an issue on their board and ask to update the plugin.

**Comment by cortinico** [comment]
> just wanted to make sure I wasn't going down a dark alley.

Nope you're on the right track. The problem is that relying on those 3rd party libs that are not getting updated that frequently is going to cause pain in the long run

**Comment by djMax** [comment]
That's basically npm in a nutshell. But it's also what makes the ecosystem work, so I guess we win some we lose some. :)

**Comment by djMax** [comment]
Next up, ShakeBugs with this line:

```
        classpath += files(project.getConfigurations().getByName('compile').asList())
```

**Comment by djMax** [comment]
Removed that line, and now it fails on duplicate class check `:app:checkDebugDuplicateClasses` with hundreds of conflicts like:

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AbstractMessageLite$InternalOneOfEnum found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AbstractParser found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AbstractProtobufList found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AllocatedBuffer found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AllocatedBuffer$1 found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.AllocatedBuffer$2 found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
     Duplicate class com.google.protobuf.Android found in modules jetified-protobuf-java-3.17.3 (com.google.protobuf:protobuf-java:3.17.3) and jetified-protobuf-javalite-3.17.3 (com.google.protobuf:protobuf-javalite:3.17.3)
```

**Comment by cortinico** [comment]
> Removed that line, and now it fails on duplicate class check `:app:checkDebugDuplicateClasses` with hundreds of conflicts like:

Just to clarify, you still haven't bumped RN right? The issue you're seeing there is that you have duplicated classes as you're importing both `protobuf-java` and `protobuf-java-lite` which can't be used together.

**Comment by djMax** [comment]
I had already bumped RN to 0.67 if that's what you mean. Right now we have a "working build" with the extractNativeLibs=true bit on RN 0.67.2

**Comment by djMax** [comment]
I have this in my configurations section: 

```
        compile.exclude group: "com.google.protobuf", module: "protobuf-javalite"
```

Shouldn't that have stopped the conflict?

**Comment by cortinico** [comment]
> Right now we have a "working build" with the extractNativeLibs=true bit on RN 0.67.2

Great. Therefore I'm closing this as the original issue is essentially resolved. Feel free to reopen if this is not the case

> Shouldn't that have stopped the conflict?

I don't know your exact configuration. What I'm saying is that you have two modules, one using `protobuf-java` and another `protobuf-java-lite` which are creating the conflict you mentioned before (which I believe is now resolved as you have a working build?).

**Comment by djMax** [comment]
🤷 The original issue isn't really resolved unless we think that telling people to enable android:extractNativeLibs to true is ok. And although it's not related to the original issue (in theory), the conflicts do not occur in the existing AGP/RN combination - they only happen when I switch to 7.3.3/7.0.4

But I get that it's an imperfect report, so I guess I'll just wait until the next person has the same issue in a simpler use case.

**Comment by cortinico** [comment]
> 🤷 The original issue isn't really resolved unless we think that telling people to enable android:extractNativeLibs to true is ok.

I'm sorry @djMax but I'm having a hard time following the conversation here because we encountered several distinct issues. It's also unclear to me if this issue is solved (as you mentioned you have a working build) or not (as it seems is the case). If it's not you're free to re-open this.

> the conflicts do not occur in the existing AGP/RN combination - they only happen when I switch to 7.3.3/7.0.4

AGP/RN combination 7.3.3/7.0.4 is also confusing to me. I'm not entirely sure what you mean with 7.0.4 as that's not a RN version.

To help us debug, the best approach is to provide a reproducer, on the sample template, aligning the versions to the one you're using locally. In that way, we can take a look at what's going on exactly. 

Otherwise you'll have to wait on the community support (as you said, maybe someone with your exact issue found a solution and can share it). I hope you will understand 🙏

**Comment by emanuelboros** [comment]
I think he misstyped AGP/RN, I think he wanted to tell Gradle and AGP. with 7.3.3/7.0.4 With grade and AGP.  Other than that I have this issue as well.
