### ISSUE TITLE
use-subscription could not resolve dependency for react 18

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [facebook/react-native#33540]
### Description

The latest react-native (v0.68.0) depends on use-subscription: ^1.0.0, but v1.6.0 of use-subscription was just [released two days ago](https://github.com/facebook/react/commit/34aa5cfe0d9b6ec4667e02bf46ab34d83dfb2d6d#diff-6a2a798876b88141c13a66abf3244457664600710b7ac61f3795021a32218468) and it peer depends on react: ^18.0.0 whereas react-native 0.68.0 peer depends on react v17.0.2 which is also what is installed in the vanilla React Native project (npx react-native init). This results in this warning when running `npm install`:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: use-subscription@1.6.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"17.0.2" from the root project
npm WARN   3 more (react-native, react-test-renderer, react-shallow-renderer)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^18.0.0" from use-subscription@1.6.0
npm WARN node_modules/use-subscription
npm WARN   use-subscription@"^1.0.0" from react-native@0.68.0
npm WARN   node_modules/react-native
```

(the warning is also present when using yarn)

### Version

0.68.0

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.97 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/be9276/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init VanillaRN
cd VanillaRN
rm -rf node_modules
npm i

**Comment by hoIIer** [comment]
I don't even use `react-native` in my project, yet here I am with my build failing due to this!

**Comment by hoIIer** [comment]
```
[Container] 2022/04/01 19:05:30 Running command npm ci
--
43 | npm WARN ERESOLVE overriding peer dependency
44 | npm WARN While resolving: use-subscription@1.6.0
45 | npm WARN Found: react@17.0.2
46 | npm WARN node_modules/react
47 | npm WARN   peer react@"17.0.2" from react-native@0.68.0
48 | npm WARN   node_modules/react-native
49 | npm WARN     peer react-native@"*" from @react-native-community/cli@7.0.3
50 | npm WARN     node_modules/@react-native-community/cli
51 | npm WARN     1 more (react-native-get-random-values)
52 | npm WARN   1 more (react-shallow-renderer)
53 | npm WARN
54 | npm WARN Could not resolve dependency:
55 | npm WARN peer react@"^18.0.0" from use-subscription@1.6.0
56 | npm WARN node_modules/use-subscription
57 | npm WARN   use-subscription@"^1.0.0" from react-native@0.68.0
58 | npm WARN   node_modules/react-native
59 | npm WARN
60 | npm WARN Conflicting peer dependency: react@18.0.0
61 | npm WARN node_modules/react
62 | npm WARN   peer react@"^18.0.0" from use-subscription@1.6.0
63 | npm WARN   node_modules/use-subscription
64 | npm WARN     use-subscription@"^1.0.0" from react-native@0.68.0
65 | npm WARN     node_modules/react-native
66 | npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
67 | npm ERR!
68 | npm ERR! Missing: fsevents@1.2.13 from lock file
69 | npm ERR!
```
Any update @jenskuhrjorgensen?

**Comment by jenskuhrjorgensen** [comment]
@hoIIer no updates

**Comment by sergioUjo** [comment]
> I don't even use `react-native` in my project, yet here I am with my build failing due to this!
> 
> Any suggestions or eta?
> 
> <img alt="image" width="377" src="https://user-images.githubusercontent.com/230757/161165109-9826f259-f01e-4214-a360-f334cf79b78e.png">
> 
> yikes!

I manage to solve with: 
`  "overrides": {
    "react-native" : "0.67.3"
  },`
in package.json

**Comment by sergioUjo** [comment]
Got the same issue, fixed with npm legacy peer depencies flag on install or update. That way react 17.0.2 doesnt get installed because of react native.

I think i fix would be to bump the peer dependency on react to 18 or bigger the 17

**Comment by Helicosaurus-Rex** [comment]
@sergioUjo The dependency problem originates from use-subscription >=1.6.0 which should not be required by RN, you should keep React 17 as is. There is already a PR (#33541) on the way.

You may try to mitigate the issue manually on your project by explicitly adding in your package.json the import of use-subscription <1.6.0 in the meantime.

**Comment by AsteriskZuo** [comment]
I have the same problem.

```
asterisk@msyncdeMBP xx % npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: use-subscription@1.6.0
npm WARN Found: react@16.13.1
npm WARN node_modules/react
npm WARN   dev react@"16.13.1" from the root project
npm WARN   1 more (react-native)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^18.0.0" from use-subscription@1.6.0
npm WARN node_modules/use-subscription
npm WARN   use-subscription@"^1.0.0" from react-native@0.63.4
npm WARN   node_modules/react-native
npm WARN 
npm WARN Conflicting peer dependency: react@18.0.0
npm WARN node_modules/react
npm WARN   peer react@"^18.0.0" from use-subscription@1.6.0
npm WARN   node_modules/use-subscription
npm WARN     use-subscription@"^1.0.0" from react-native@0.63.4
npm WARN     node_modules/react-native
...
```

```
asterisk@msyncdeMBP xx % npm react-native info
Unknown command: "react-native"

To see a list of supported npm commands, run:
  npm help
asterisk@msyncdeMBP xx % npm react-native info
Unknown command: "react-native"

To see a list of supported npm commands, run:
  npm help
asterisk@msyncdeMBP xx % npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 489.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/opt/cocoapods/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 30.0.2, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by AsteriskZuo** [comment]
Solutions to the above problems:
rm -rf ./node_modules/@types/react-native/node_modules/

**Comment by cbaconnier** [comment]
I believe this issue is still ongoing for expo 
Expo uses the version 0.64.3 which also has the same dependencies: https://github.com/facebook/react-native/blob/0.64-stable/package.json#L115

I fixed it by forcing the version in my package.json
```
"dependencies": {
    ...
    "use-subscription": ">=1.0.0 <1.6.0"
}
```
