### ISSUE TITLE
'value' is unavailable: introduced in iOS 12.0

### ISSUE THREAD

**Issue by orzhtml** [facebook/react-native#34106]
### Description

'value' is unavailable: introduced in iOS 12.0

### Version

0.69.0

### Output of `npx react-native info`

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 27.26 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 26.0.2, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-25 | Google APIs ARM EABI v7a, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_152 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init example --template react-native-template-typescript

yarn start

open xcode run

### Snack, code example, screenshot, or link to a repository

![image](https://user-images.githubusercontent.com/5866002/176604993-dd97b6f5-ee60-467b-86b4-6fa5cd8249aa.png)

**Comment by friederbluemle** [comment]
Same issue here. I'm also using Xcode 12.4 - Could that be the reason?

**Comment by AmirDiafi** [comment]
+1

**Comment by orzhtml** [comment]
My system：
macOS Catalina （10.15.7）
MacBook Pro (13-inch, Mid 2012)

Xcode Version：12.4 (12D4e)

The latest system cannot be upgraded，Could that be the reason?

**Comment by datqb** [comment]
same issue, please give me solution when u have. tks

**Comment by 3runoDesign** [comment]
+1

**Comment by llVeraVerall** [comment]
I have the same problem. I think the error is that the app runs iOS 14.4

**Comment by ammarahm-ed** [comment]
Here's how I fixed it:

1. Open `node_modules/react-native/scripts/react_native_pods.rb`
2. Go to line no 401 >>> `'ios' => '11.0',`
3.  Change `11.0` to `12.0`
4. Use `patch-package` to make a patch.
5. Run yarn
6. Run pod install
7. Go to `ios/build/generated/ios/React-Codegen.podspec.json` and confirm `"platforms": { "ios": "12.0" }`

That's all.

**Comment by craspadotcom** [comment]
this worked, can you please explain your line of thinking/workflow that made you come to this solution?

**Comment by craspadotcom** [comment]
> 4\. Use `patch-package` to make a patch.

npx patch-package react-native

**Comment by ammarahm-ed** [comment]
@craspadotcom You have to add the postinstall script in package.json so it patches the files when you install/update packages. 

```json
"scripts": {
    "postinstall": "patch-package",
 
  },
```

The error occurs because React Native 0.69 targets ios 12.4 in Podfile but the Codegen generated podspec still targets ios 11.0 while using ios 12+ apis. I think there should be a patch release that fixes this issue.

**Comment by Daniel-Houston** [comment]
This fix worked for me

**Comment by OmarUsman777** [comment]
In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj 

Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.

Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.

**Comment by Azaz0723** [comment]
> In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj
> 
> Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.
> 
> Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.

this was helpful my issue was resolved using this

**Comment by chrisjoohn** [comment]
> you

Thanks for this. After so many tries on how to resolve this issue, this is the one that worked. 🍻

**Comment by sesm** [comment]
Update for version 0.70.3: 
If you want to follow advice from @ammarahm-ed , the property is in a different file now:
```patch
diff --git a/node_modules/react-native/scripts/cocoapods/codegen_utils.rb b/node_modules/react-native/scripts/cocoapods/codegen_utils.rb
index 6fcbb15..7e457b9 100644
--- a/node_modules/react-native/scripts/cocoapods/codegen_utils.rb
+++ b/node_modules/react-native/scripts/cocoapods/codegen_utils.rb
@@ -84,7 +84,7 @@ class CodegenUtils
           'source' => { :git => '' },
           'header_mappings_dir' => './',
           'platforms' => {
-            'ios' => '11.0',
+            'ios' => '12.0',
           },
           'source_files' => "**/*.{h,mm,cpp}",
           'pod_target_xcconfig' => { "HEADER_SEARCH_PATHS" =>
```

**Comment by jhoanborges** [comment]
+1

**Comment by kayewrobleski** [comment]
I had the same issue. Advice from @sesm worked for me

**Comment by IlirBajrami** [comment]
> In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj
> 
> Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.
> 
> Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.

You saved my job man! I know this is because our old macs are not updating to the latest ios. Now i hope i earn enough to buy the new mac :)

**Comment by OmarUsman777** [comment]
> > In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj
> > Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.
> > Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.
> 
> You saved my job man! I know this is because our old macs are not updating to the latest ios. Now i hope i earn enough to buy the new mac :)

I'm glad this solution worked for you, Best of luck for your future endeavours :)

**Comment by hailie-rei** [comment]
@ammarahm-ed 's and @sesm 's solution helped me as well. Thank you!

**Comment by kouhot** [comment]
@OmarUsman777 

I think If you set like this in Podfile, you don't have to change them manually everytime.

```
  ...
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
```

**Comment by samzhao2008** [comment]
> In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj
> 
> Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.
> 
> Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.

Thank you so much. You saved my day.

**Comment by Jf-js** [comment]
Thank you very much. The below fix worked for me too, I am still in the old XCode Version 12.4.

Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.

**Comment by ricardoMogg** [comment]
This is happening to me on XCode 14.2 as well since 2 days ago

**Comment by dvelopin** [comment]
This solution worked for me with Xcode 14.3RC

https://stackoverflow.com/a/74487309

**Comment by ricardoMogg** [comment]
To anyone that keeps having these issues and is using XcodeCloud, make sure to go to the workflow settings and choose the correct environment. In my case it was using the latest environment (14.3RC at the moment) and that was breaking everything. I selected spewcifically 14.2 and multiple things got fixed.

**Comment by ElectricCoffee** [comment]
> Can confirm this happens in Xcode 14.3. I downloaded RC2 today and this issue started. I was able to solve it by the following:
> 
>     1. In your Xcode project navigator, select `Pods`.
> 
>     2. Under Targets, select`React-Codegen` and set the window to `Build Settings`.
> 
>     3. Under Deployment, set `iOS Deployment Target` to `12.4`.
> 
>     4. Clean project and rebuild.

This _almost_ worked for me.
I also had to update the build targets for `react-native-quick-crypto` and `react-native-quick-base64`

**Comment by zanzarone** [comment]
Thanks

> > Can confirm this happens in Xcode 14.3. I downloaded RC2 today and this issue started. I was able to solve it by the following:
> > ```
> > 1. In your Xcode project navigator, select `Pods`.
> > 
> > 2. Under Targets, select`React-Codegen` and set the window to `Build Settings`.
> > 
> > 3. Under Deployment, set `iOS Deployment Target` to `12.4`.
> > 
> > 4. Clean project and rebuild.
> > ```
> 
> This _almost_ worked for me. I also had to update the build targets for `react-native-quick-crypto` and `react-native-quick-base64`. So if anyone relies on these dependencies as well, those need to be bumped.

Thanks man, you saved my day!

**Comment by ervibern** [comment]
Do you know how this can be solved in Expo Managed Workflow? I added `expo-build-properties` plugin to increase the iOS Deployment Target to 13.0 but it didn't solve the issue. Still getting the `'value' is unavailable: introduced in iOS 12.0` issue.
`[
      'expo-build-properties',
      {
        ios: {
          deploymentTarget: '13.0',
        },
      },
    ],`

**Comment by iway1** [comment]
Why was this issue closed? @orzhtml can you please reopen since it isn't fixed

**Comment by Esparzarr** [comment]
> This solution worked for me with Xcode 14.3RC
> 
> https://stackoverflow.com/a/74487309

This work for me

**Comment by ElectricCoffee** [comment]
> Do you know how this can be solved in Expo Managed Workflow? I added `expo-build-properties` plugin to increase the iOS Deployment Target to 13.0 but it didn't solve the issue. Still getting the `'value' is unavailable: introduced in iOS 12.0` issue. `[ 'expo-build-properties', { ios: { deploymentTarget: '13.0', }, }, ],`

That's cool if you use Expo. Our project doesn't however, so other workarounds are needed.

**Comment by behenate** [comment]
> > Can confirm this happens in Xcode 14.3. I downloaded RC2 today and this issue started. I was able to solve it by the following:
> > ```
> > 1. In your Xcode project navigator, select `Pods`.
> > 
> > 2. Under Targets, select`React-Codegen` and set the window to `Build Settings`.
> > 
> > 3. Under Deployment, set `iOS Deployment Target` to `12.4`.
> > 
> > 4. Clean project and rebuild.
> > ```
> 
> This _almost_ worked for me. I also had to update the build targets for `react-native-quick-crypto` and `react-native-quick-base64`. So if anyone relies on these dependencies as well, those need to be bumped.

Thank you this worked perfectly!

**Comment by behenate** [comment]
> Can confirm this happens in Xcode 14.3. I downloaded RC2 today and this issue started. I was able to solve it by the following:
> 
> 1. In your Xcode project navigator, select `Pods`.
> 2. Under Targets, select`React-Codegen` and set the window to `Build Settings`.
> 3. Under Deployment, set `iOS Deployment Target` to `12.4`.
> 4. Clean project and rebuild.

Thank you this worked perfectly!

**Comment by shoopapa** [comment]
> Here's an expo config plugin that worked for me for managed Expo workflow (it updates the deployment target for all pods to 13.0)
> 
> ```js
> /* eslint-disable @typescript-eslint/no-var-requires */
> const { withDangerousMod, withPlugins } = require("@expo/config-plugins");
> const {
>   mergeContents,
> } = require("@expo/config-plugins/build/utils/generateCode");
> const fs = require("fs");
> const path = require("path");
> 
> async function readFileAsync(path) {
>   return fs.promises.readFile(path, "utf8");
> }
> 
> async function saveFileAsync(path, content) {
>   return fs.promises.writeFile(path, content, "utf8");
> }
> 
> const withFixedDeploymentTarget = (c) => {
>   return withDangerousMod(c, [
>     "ios",
>     async (config) => {
>       const file = path.join(config.modRequest.platformProjectRoot, "Podfile");
>       const contents = await readFileAsync(file);
>       await saveFileAsync(file, fixDeploymentTarget(contents));
>       return config;
>     },
>   ]);
> };
> 
> function fixDeploymentTarget(src) {
>   return mergeContents({
>     tag: `rn-fix-deployment-target`,
>     src,
>     newSrc: `
>    installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>                config.build_settings['SWIFT_VERSION'] = '5.0'
>                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
>     end
>   end
> `,
>     anchor: /post_install/,
>     offset: 1,
>     comment: "#",
>   }).contents;
> }
> 
> module.exports = (config) => withPlugins(config, [withFixedDeploymentTarget]);
> ```
> 
> Put this in "<project_root>/config-plugins/deployment-targets.js"
> 
> Then add to your `app.json`:
> 
> ```json
> {
>   "plugins": ["./config-plugins/deployment-targets"]
> }
> ```
> 
> Then `rm -rf ios` => `expo run:ios`
Working for me! I like the fix

Do you have a edit that will only update the react-native codegen package, updating all of them seems a error prone?

**Comment by iway1** [comment]
@shoopapa I haven't tried to do it just with the one package but maybe can add an if statement in there to check for the package name? I'm not really well versed in pod file syntax. probably better to do it that for just react native codegen but doing it this way seems to be fine so far

**Comment by hussainarthuna** [comment]
> Can confirm this happens in Xcode 14.3. I downloaded RC2 today and this issue started. I was able to solve it by the following:
> 
> 1. In your Xcode project navigator, select `Pods`.
> 2. Under Targets, select`React-Codegen` and set the window to `Build Settings`.
> 3. Under Deployment, set `iOS Deployment Target` to `12.4`.
> 4. Clean project and rebuild.

Thank you, it works perfectly for me.

**Comment by lfoliveir4** [comment]
> Here's how I fixed it:
> 
> 1. Open `node_modules/react-native/scripts/react_native_pods.rb`
> 2. Go to line no 401 >>> `'ios' => '11.0',`
> 3. Change `11.0` to `12.0`
> 4. Use `patch-package` to make a patch.
> 5. Run yarn
> 6. Run pod install
> 7. Go to `ios/build/generated/ios/React-Codegen.podspec.json` and confirm `"platforms": { "ios": "12.0" }`
> 
> That's all.
> 
> ```diff
> diff --git a/node_modules/react-native/scripts/react_native_pods.rb b/node_modules/react-native/scripts/react_native_pods.rb
> index 7f6ebab..cea0fef 100644
> --- a/node_modules/react-native/scripts/react_native_pods.rb
> +++ b/node_modules/react-native/scripts/react_native_pods.rb
> @@ -398,7 +398,7 @@ def get_react_codegen_spec(options={})
>      'source' => { :git => '' },
>      'header_mappings_dir' => './',
>      'platforms' => {
> -      'ios' => '11.0',
> +      'ios' => '12.0',
>      },
>      'source_files' => "**/*.{h,mm,cpp}",
>      'pod_target_xcconfig' => { "HEADER_SEARCH_PATHS" =>
> ```

The same issue happened to me in new Xcode 14.3. That's save me! Thanks! ❤️

**Comment by orzhtml** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/5866002/229302356-4c53c657-50d9-4810-8566-35b20c17514e.png">
![image](https://user-images.githubusercontent.com/5866002/229302367-fb09c4cf-11f9-4f01-b85f-d08ea12e3df3.png)

**Comment by orzhtml** [comment]
![image](https://user-images.githubusercontent.com/5866002/229302384-fe503be7-0460-42ee-b26f-cf65d4af1d30.png)

**Comment by shoopapa** [comment]
@iway1 This works for me, updating all the pods isn't necessary
```javascript 
const { withDangerousMod, withPlugins } = require("@expo/config-plugins");
const { ExpoConfig } = require("@expo/config-types");
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");
const { readFileSync, writeFileSync } = require("fs");
const { resolve } = require("path");

const withFixedDeploymentTarget = (c) => {
  return withDangerousMod(c, [
    "ios",
    async (config) => {
      const file = resolve(config.modRequest.platformProjectRoot, "Podfile");
      const contents = readFileSync(file, { encoding: "utf-8" });
      writeFileSync(file, fixDeploymentTarget(contents));
      return config;
    },
  ]);
};

function fixDeploymentTarget(src) {
  return mergeContents({
    tag: `rn-fix-deployment-target`,
    src,
    newSrc: `
  installer.pods_project.targets.each do |target|
    if target.to_s === 'React-Codegen'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
`,
    anchor: /post_install/,
    offset: 1,
    comment: "#",
  }).contents;
}

module.exports = (config) => withPlugins(config, [withFixedDeploymentTarget]);
```
Here is edit for only patching `React-Codegen`
At least temporarily, I recommend this solution if using expo, manually editing the podfile isn't optimal in the expo workflow

**Comment by iway1** [comment]
@shoopapa nice - I also strongly recommend not manually editing any native files at all with expo managed workflow, it's a really big advantage to be able to not care about the ios/android folders and to be able to regenerate them easily.

**Comment by ROG3R-DEV** [comment]
> 

I have this problem after updating xcode from version 14.2 to 14.3. The above solution does the trick, but it's very annoying to have to do this every time you run pod-install. Has anyone found a permanent solution to this problem?

**Comment by rodolforamos** [comment]
> This solution worked for me with Xcode 14.3RC
> 
> https://stackoverflow.com/a/74487309

This worked like magic.

**Comment by skurgansky-sugarcrm** [comment]
test your fix on build with hermes and fabric enabled

**Comment by orzhtml** [comment]
> This solution worked for me with Xcode 14.3RC
> 
> https://stackoverflow.com/a/74487309

![image](https://user-images.githubusercontent.com/5866002/229401009-5e3cdd41-dd73-4031-be61-2c3955c095b8.png)
This worked like magic.

**Comment by iamromec** [comment]
> This is happening with Xcode Cloud when you have Xcode set to 14.3RC, if you change it to 14.2 you are good to go.
> 
> I wonder if this is due to changes in Swift 5.8.

How to change this? Steps?

**Comment by kelset** [comment]
Hey folks, just an headsup: we already landed the change that fixes this correctly in [36759](https://github.com/facebook/react-native/pull/36759) and we are about to release the supported versions of React Native with their right fixes: 

- 0.69: #[36767](https://github.com/facebook/react-native/pull/36767)  
- 0.70: #[36768](https://github.com/facebook/react-native/pull/36768)  
- 0.71: #[36769](https://github.com/facebook/react-native/pull/36769)

Expect them to land later this week.

**Comment by Zagorevsky** [comment]
Hi! This solution helped me a lot!

**Comment by kelset** [comment]
👋 everyone!

We have just now finished rolling out new patch releases for the versions in the [release support window](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) to address this problem, check them out:
* https://github.com/facebook/react-native/releases/tag/v0.71.6
* https://github.com/facebook/react-native/releases/tag/v0.70.8
* https://github.com/facebook/react-native/releases/tag/v0.69.9

They should address this problem fully.

**Comment by WyrdRaven** [comment]
I upgraded from v0.70.5 -> v0.70.8 and I'm still getting the error :(

For instance, in (ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2598:110):

```
d[@"DEFAULT_BACKGROUND_COLOR"] = DEFAULT_BACKGROUND_COLOR.has_value() ? @((double)DEFAULT_BACKGROUND_COLOR.value()) : nil;
       |                                                                                                              ^ 'value' is unavailable: introduced in iOS 12.0
```

**Comment by BrotskyS** [comment]
Just don't install new versions of Xcode in the early days)) What are you hoping for?

**Comment by asindhu** [comment]
> I upgraded from v0.70.5 -> v0.70.8 and I'm still getting the error :(
> 
> For instance, in (ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h:2598:110):
> 
> ```
> d[@"DEFAULT_BACKGROUND_COLOR"] = DEFAULT_BACKGROUND_COLOR.has_value() ? @((double)DEFAULT_BACKGROUND_COLOR.value()) : nil;
>        |                                                                                                              ^ 'value' is unavailable: introduced in iOS 12.0
> ```

I had the same issue, applied the same fix (upgrade from v0.70.6 to v0.70.8) and still have the issue again as well. I'm not all that familiar with the Expo build environment yet but I tried to reset/clean everything as much as possible. I fully removed the ios build directory, then ran `npx expo prebuild --clean` followed by `npx expo run:ios` and get the exact same error still. Tried running `pod install` in the ios directory too, that works without error. I confirmed that react-native package is now at 0.70.8 version. Any ideas? Thanks.

**Comment by jakobvase** [comment]
> 👋 everyone!
> 
> We have just finished rolling out new patch releases for the versions in the [release support window](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) to address this problem, check them out:
> 
>     * https://github.com/facebook/react-native/releases/tag/v0.71.6
> 
>     * https://github.com/facebook/react-native/releases/tag/v0.70.8
> 
>     * https://github.com/facebook/react-native/releases/tag/v0.69.9
> 
> 
> They should address this problem fully.

This worked for me, after `npm install`, `bundle install` and `pod install`. Thanks kelset!

**Comment by MelMayssonOwen** [comment]
> 

Just had this issue and applying the change to all the pods didn't cut it for me. So instead that's what worked for me.

```
# Fix for use_frameworks! :linkage => :static
      react_native_post_install(installer)
      installer.pods_project.targets.each do |target|
        if target.name == 'RCT-Folly'
          target.build_configurations.each do |config|
            config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
          end
        end
      # Change the deployment target to 12.4 for React-Codegen
        if target.name == 'React-Codegen'
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
          end
        end
      end
      # __apply_Xcode_12_5_M1_post_install_workaround(installer)
      installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
```

**Comment by cn-johndpope** [comment]
downgrading to xcode 14.2 also working.

**Comment by canpoyrazoglu** [comment]
Yup. Upgrading from 0.71.4 to 0.71.6 fixes this issue.

**Comment by ahmad-ali14** [comment]
> Here's how I fixed it:
> 
> 1. Open `node_modules/react-native/scripts/react_native_pods.rb`
> 2. Go to line no 401 >>> `'ios' => '11.0',`
> 3. Change `11.0` to `12.0`
> 4. Use `patch-package` to make a patch.
> 5. Run yarn
> 6. Run pod install
> 7. Go to `ios/build/generated/ios/React-Codegen.podspec.json` and confirm `"platforms": { "ios": "12.0" }`
> 
> That's all.
> 
> ```diff
> diff --git a/node_modules/react-native/scripts/react_native_pods.rb b/node_modules/react-native/scripts/react_native_pods.rb
> index 7f6ebab..cea0fef 100644
> --- a/node_modules/react-native/scripts/react_native_pods.rb
> +++ b/node_modules/react-native/scripts/react_native_pods.rb
> @@ -398,7 +398,7 @@ def get_react_codegen_spec(options={})
>      'source' => { :git => '' },
>      'header_mappings_dir' => './',
>      'platforms' => {
> -      'ios' => '11.0',
> +      'ios' => '12.0',
>      },
>      'source_files' => "**/*.{h,mm,cpp}",
>      'pod_target_xcconfig' => { "HEADER_SEARCH_PATHS" =>
> ```

Thank you very much; this was super helpful.

**Comment by ElectricCoffee** [comment]
> > 👋 everyone!
> > We have just finished rolling out new patch releases for the versions in the [release support window](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) to address this problem, check them out:
> > ```
> > * https://github.com/facebook/react-native/releases/tag/v0.71.6
> > 
> > * https://github.com/facebook/react-native/releases/tag/v0.70.8
> > 
> > * https://github.com/facebook/react-native/releases/tag/v0.69.9
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > They should address this problem fully.
> 
> This worked for me, after `npm install`, `bundle install` and `pod install`. Thanks kelset!

Unfortunately this only fixed things for me for the React Native stuff.
I guess I'll have to make an issue on [Quick Crypto](https://github.com/margelo/react-native-quick-crypto) to get them to fix the same issue.

**Comment by devpenzil** [comment]
https://stackoverflow.com/a/75915794/12105742

This solution works for me

**Comment by hungdev** [comment]
> https://stackoverflow.com/a/75915794/12105742
> 
> This solution works for me

thank you, it worked for me

**Comment by diegoamorim-cs** [comment]
> https://stackoverflow.com/a/75915794/12105742
> 
> This solution works for me

Thank's, it worked

**Comment by anshif10** [comment]
if anybody with with react native 0.70 still facing this issue please  upgrade to latest react native version 
1.npx react-native upgrade
2. cd ios 
3. pod install 
4. Reopen xcode and build

**Comment by eliot-ye** [comment]
https://mrdevgeek.com/xcode-14-3-simulator-16-4-build-failure-how-to-fix-value-is-unavailable-introduced-in-ios-12-0-error-with-react-native-0-71-5/

work for me

**Comment by tahagates97** [comment]
@eliot-ye is great works like a charm believe

**Comment by sureco-doug** [comment]
> @OmarUsman777
> 
> I think If you set like this in Podfile, you don't have to change them manually everytime.
> 
> ```
>   ...
>   post_install do |installer|
>     react_native_post_install(
>       installer,
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
>     # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
>       end
>     end
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> ```

@kouhot 's solution worked for me. Had to add this to Podfile and then Clean and run pod install again, and everything worked without error. Thanks kouhot!

**Comment by hlspablo** [comment]
Guys, don't do anything fancy, just update to the latest minor version, delete pods, Podfile.lock, reinstall the pods with pod install --repo-update, and everything should work.

**Comment by Emekaony** [comment]
> In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj
> 
> Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.
> 
> Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.

is there a better way to do this? an automated way via cmd line? I have over 100 instances where this happens and doing it by hand is insane.

**Comment by hlspablo** [comment]
> > In iOS Folder go to Pods/Pods.xcodeproj/xcuserdata/project.pbxproj
> > Change all the 'IPHONEOS_DEPLOYMENT_TARGET = 11.0' to 'IPHONEOS_DEPLOYMENT_TARGET = 12.4'. save and run.
> > Note: every time you pod install it will change so again you have to do it. If there is better approach please do mention.
> 
> is there a better way to do this? an automated way via cmd line? I have over 100 instances where this happens and doing it by hand is insane.

Update to a version that already fixed it. Manually changing things can be a pain in the ass in long time

**Comment by karatekid430** [comment]
`
      if target.name == "React-Codegen"
        # https://github.com/facebook/react-native/issues/34106
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.4"
      end
`

I found that the scalpel is better than the hammer.

**Comment by Aakash359** [comment]
> Here's how I fixed it:
> 
> 1. Open `node_modules/react-native/scripts/react_native_pods.rb`
> 2. Go to line no 401 >>> `'ios' => '11.0',`
> 3. Change `11.0` to `12.0`
> 4. Use `patch-package` to make a patch.
> 5. Run yarn
> 6. Run pod install
> 7. Go to `ios/build/generated/ios/React-Codegen.podspec.json` and confirm `"platforms": { "ios": "12.0" }`
> 
> That's all.
> 
> ```diff
> diff --git a/node_modules/react-native/scripts/react_native_pods.rb b/node_modules/react-native/scripts/react_native_pods.rb
> index 7f6ebab..cea0fef 100644
> --- a/node_modules/react-native/scripts/react_native_pods.rb
> +++ b/node_modules/react-native/scripts/react_native_pods.rb
> @@ -398,7 +398,7 @@ def get_react_codegen_spec(options={})
>      'source' => { :git => '' },
>      'header_mappings_dir' => './',
>      'platforms' => {
> -      'ios' => '11.0',
> +      'ios' => '12.0',
>      },
>      'source_files' => "**/*.{h,mm,cpp}",
>      'pod_target_xcconfig' => { "HEADER_SEARCH_PATHS" =>
> ```



When i i have try this soultion then i am getting this error lol now do i fixed this issues i think your solution does't work for me it is creating another problem, i guess everyone getting the same issues after trying your solutions like this <img width="1440" alt="Screenshot 2023-06-07 at 2 30 16 PM" src="https://github.com/facebook/react-native/assets/54428958/aebb2cd4-511d-4cc9-b1d3-e3fed63d40eb"> i am totally fed -up with your solution pls someone suggest me another solution accepting this one

**Comment by csoylu** [comment]
isn't this solved already, i am facing the same issue?

**Comment by efecantekin** [comment]
> 👋 everyone!
> 
> We have just finished rolling out new patch releases for the versions in the [release support window](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) to address this problem, check them out:
> 
> * https://github.com/facebook/react-native/releases/tag/v0.71.6
> * https://github.com/facebook/react-native/releases/tag/v0.70.8
> * https://github.com/facebook/react-native/releases/tag/v0.69.9
> 
> They should address this problem fully.

I tried to build RN 71.10 on XCode 14.3.1 and got this error again.
I checked Codegen_utils.rb and it uses min_ios_version_supported definition which returns 12.4 already in react_native_pods.rb.

**Comment by samih-dev** [comment]
@efecantekin try cleaning the build using CMD/CRTL+SHIFT+K on xcode and try add the pods again `npx pod-install` - this worked for me

**Comment by bryce0516** [comment]
```
diff --git a/node_modules/react-native/scripts/cocoapods/codegen_utils.rb b/node_modules/react-native/scripts/cocoapods/codegen_utils.rb
index 3694e68..caa9794 100644
--- a/node_modules/react-native/scripts/cocoapods/codegen_utils.rb
+++ b/node_modules/react-native/scripts/cocoapods/codegen_utils.rb
@@ -85,7 +85,7 @@ class CodegenUtils
           'source' => { :git => '' },
           'header_mappings_dir' => './',
           'platforms' => {
-            'ios' => '11.0',
+            'ios' => '12.4',
           },
           'source_files' => "**/*.{h,mm,cpp}",
           'pod_target_xcconfig' => { "HEADER_SEARCH_PATHS" =>
```

in  "react-native": "0.71.2"

npx patch-package react-native 

this works!
try this

**Comment by zabojad** [comment]
It still happens with XCode 14.3.1 and RN 0.71.8 on several modules like : react-native-simple-toast, react-native-svg, react-native-permissions...

The problem started to pop in my project after updating XCode from 14.1 to 14.3.1.

**Comment by jamesrogers93** [comment]
I fixed this by upgrading react-native from 0.71.4 to  0.71.11

**Comment by zachrispoli** [comment]
This issue was fixed for me by bumping `react-native` from `0.70.6` to `0.70.10`, in order to get this fix: https://github.com/facebook/react-native/commit/c5e549e694607cd576be8fcb5ed909fec2ed6dce

So if you're still on react-native 0.70.x, you can still get support for Xcode 14.3 using minor version 10.

**Comment by MohameddAmineYaich** [comment]
I just remove pods folder under ios

**Comment by expressdev093** [comment]
> @OmarUsman777
> 
> I think If you set like this in Podfile, you don't have to change them manually everytime.
> 
> ```
>   ...
>   post_install do |installer|
>     react_native_post_install(
>       installer,
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
>     # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
>       end
>     end
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> ```

thanks this work for me

**Comment by zabojad** [comment]
Still having the issue after performing these steps:
1 - upgrade react-native from 0.71.8 to 0.71.12
2 - Deleted Pods and Podfile.lock
3 - run `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install` in /ios folder
4  - clean build in XCode and build...

**Comment by qaudfuture** [comment]
> > @OmarUsman777
> > I think If you set like this in Podfile, you don't have to change them manually everytime.
> > ```
> >   ...
> >   post_install do |installer|
> >     react_native_post_install(
> >       installer,
> >       # Set `mac_catalyst_enabled` to `true` in order to apply patches
> >       # necessary for Mac Catalyst builds
> >       :mac_catalyst_enabled => false
> >     )
> >     # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
> >     installer.pods_project.targets.each do |target|
> >       target.build_configurations.each do |config|
> >         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
> >       end
> >     end
> >     __apply_Xcode_12_5_M1_post_install_workaround(installer)
> >   end
> > ```
> 
> @kouhot 's solution worked for me. Had to add this to Podfile and then Clean and run pod install again, and everything worked without error. Thanks kouhot!

Thank you, This worked for me

**Comment by Dsalvat596** [comment]
> The second solution is:
> 
> 1. In the Xcode Project select "Pods"
> 2. Select target that throws errors
> 3. Select Build Settings
> 4. Bump iOS Target to required version
> 
> **But you should do this every time when project is updates**
> 
> <img alt="Screenshot 2023-06-15 at 12 29 01" width="1050" src="https://user-images.githubusercontent.com/1431423/246046195-6c7afa41-5828-4500-b5eb-12df15f5be3d.png">

You've saved my life.  Hours upon hours of trying to fix it, and this did the trick.

**Comment by brunoamorim616** [comment]
> @OmarUsman777
> 
> I think If you set like this in Podfile, you don't have to change them manually everytime.
> 
> ```
>   ...
>   post_install do |installer|
>     react_native_post_install(
>       installer,
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
>     # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
>       end
>     end
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> ```

This worked on my project:
"react": "18.1.0",
"react-native": "0.70.6",
XCode Version 14.3
MacBookAir M1 - MacOS Ventura 13.0

**Comment by tonyjohnvan** [comment]
just upgrade react native version to 0.72.3 and pod install fix it for me

**Comment by holicstudio** [comment]
> > The second solution is:
> > 
> > 1. In the Xcode Project select "Pods"
> > 2. Select target that throws errors
> > 3. Select Build Settings
> > 4. Bump iOS Target to required version
> > 
> > **But you should do this every time when project is updates**
> > <img alt="Screenshot 2023-06-15 at 12 29 01" width="1050" src="https://user-images.githubusercontent.com/1431423/246046195-6c7afa41-5828-4500-b5eb-12df15f5be3d.png">
> 
> You've saved my life. Hours upon hours of trying to fix it, and this did the trick.

Today, what is the required version? ios12? or 16?

**Comment by liamjones** [comment]
> Today, what is the required version? ios12? or 16?

@holicstudio depends on your RN version. For the current version, 0.72.4, it's 12.4: https://github.com/facebook/react-native/blob/v0.72.4/packages/react-native/scripts/react_native_pods.rb#L41

You shouldn't need to manually change the version in the Pods project settings with recent RN versions though, the template `Podfile` references the above-linked code dynamically (see https://github.com/facebook/react-native/blob/v0.72.4/packages/react-native/scripts/react_native_pods.rb#L41). So, as RN updates, it'll change the version the Pods project is looking for (as long as you remember to `pod install` after upgrading).

Also, you may have other dependencies that pull up this min required version (for example I believe Expo currently needs 13+ if you're using that in your RN project)

**Comment by nqam1904** [comment]
> min_ios_version_supported

How to configure only once since the project is updated :-?

**Comment by amruth-k99** [comment]
I have an Apple Macbook Pro M3 with Xcode 15.3.
If anyone out there is unable to solve it, try this version:
The `IPHONEOS_DEPLOYMENT_TARGET` should be `13.0`. It should be more than `12.4`.s

```

target.build_configurations.each do |config|
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  if target.name == 'react-native-config'
    config.build_settings['ENVFILE'] = ENVFILES[config.name]
  end
  config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
end

```
