### ISSUE TITLE
React native app upgrade showing icons misplaced in android (production app)

### ISSUE THREAD

**Issue by KiranRadish** [facebook/react-native#36406]
### Description

Platform - Android
I have uploaded new version of my app to the play store, and tried to update the app which is already on the device, then some of the icons are misplaced and it showed the other sections of the app in ANDROID. This is really strange for us. When I deleted the app and reinstall the application it works fine all icons are correctly showing. But when updating the app from play store the icons are misplaced in the app.

In iOS there are no such issues.
In the earlier versions, everything was fine in android and it showed weird results on some of the icons while updating the new version.

### React Native Version

"react-native": "0.66.4"

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 54.73 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /var/folders/n4/7nw_ckyn6gn3xq4zvwyn3d300000gn/T/yarn--1678294944816-0.9964311536435131/node
    Yarn: 1.22.19 - /var/folders/n4/7nw_ckyn6gn3xq4zvwyn3d300000gn/T/yarn--1678294944816-0.9964311536435131/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/kiranchavan/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-29 | Google Play ARM 64 v8a, android-30 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 19.27s.

### Steps to reproduce

update new version of app by keeping old version on android

### Snack, code example, screenshot, or link to a repository

<img width="165" alt="Screenshot 2023-03-08 at 10 36 58 PM" src="https://user-images.githubusercontent.com/93185181/223781162-fbfabb17-8ab1-4b0a-adee-8f1c6de51585.png">

**Comment by KiranRadish** [comment]
This is a production issue suddenly i faced

**Comment by KiranRadish** [comment]
Resolved

**Comment by Iftekhar-Younode** [comment]
@KiranRadish  can you please explain your way of resolving?

**Comment by KiranRadish** [comment]
@Iftekhar-Younode 
Please check if you are using fresco then please downgrade this to 2.5.0 

in app/build.gradle

`implementation 'com.facebook.fresco:fresco:2.5.0'`
`implementation 'com.facebook.fresco:animated-gif:2.5.0`

**Comment by nishadadilshan** [comment]
I downgraded the versions
implementation 'com.facebook.fresco:fresco:2.5.0'
implementation 'com.facebook.fresco:animated-gif:2.5.0

"react-native": "0.71.1"
"react": "18.2.0"

But I'm still facing this issue on production.

**Comment by SudeFidanWT** [comment]
> I downgraded the versions implementation 'com.facebook.fresco:fresco:2.5.0' implementation 'com.facebook.fresco:animated-gif:2.5.0
> 
> My React and React Native versions "react-native": "0.71.1" "react": "18.2.0"
> 
> But I'm still facing this issue on production.

I have had the same problem, then I started the clean build then it was fixed...

**Comment by PramodSoftobiz** [comment]
i am facing the same issue @SudeFidanWT , are you able to fix this by downgrading ? or just clean build has done the job?
