### ISSUE TITLE
onPress is not called after using useNativeDriver transform button

### ISSUE THREAD

**Issue by ThinkerLu** [facebook/react-native#36504]
### Description

 After using useNativeDriver transform button, finger movement occurs when the button is pressed, the button's onPress will not be called, but the visual feedback of the button is normal.
The bug only occurs on Android devices, and when the new architecture is enabled, useNativeDriver=true is set.

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 148.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run my code, Press the button after scrolling the FlatList, move your finger slightly and lift it up.

### Snack, code example, screenshot, or link to a repository
import React, {useRef, useState} from 'react';
import {View, Text, Button, Animated} from 'react-native';

const componentList: number[] = Array.from(new Array(100).keys());

const App = () => {
  const currScroll = useRef(new Animated.Value(0)).current;
  const [count, setCount] = useState(0);

  return (
    <View style={{flex: 1}}>
      <Animated.View
        style={{
          position: 'absolute',
          zIndex: 2,
          width: '100%',
          transform: [{translateY: currScroll}],
        }}>
        <Button
          title={`Press count : ${count}`}
          onPress={() => {
            console.log('pressed');
            setCount(count + 1);
          }}></Button>
      </Animated.View>
      <Animated.FlatList
        style={{width: '100%', height: '100%', position: 'absolute', zIndex: 1}}
        data={componentList}
        renderItem={({index}) => (
          <Text
            style={{
              backgroundColor: 'white',
              height: 28,
            }}>
            {index}
          </Text>
        )}
        keyExtractor={item => item.toString()}
        onScroll={Animated.event(
          [
            {
              nativeEvent: {
                contentOffset: {
                  y: currScroll,
                },
              },
            },
          ],
          {useNativeDriver: true},
        )}></Animated.FlatList>
    </View>
  );
};

export default App;

**Comment by iMonk777** [comment]
Hi @ThinkerLu , we still have this issue. Did you find any solution for this?

**Comment by jugshaurya** [comment]
+1, after applying transform:  translateX/Y/Z(*), on Animated.View, internal content of this View become non-responsive, works after multiple clicking. 

It comes after using New Arch.Even used latest [0.72.0-RC.3](https://github.com/facebook/react-native/releases/tag/v0.72.0-rc.3)

**Comment by the-skins-app** [comment]
@jugshaurya I can confirm I'm having the same issue, using 71.10, android.

**Comment by jugshaurya** [comment]
> @jugshaurya I can confirm I'm having the same issue, using 71.10, android. It basically makes the new architecture unusable on Android, unless you plan to have no animation. It's occurring with all touchables and pressables.
> 
> related: https://github.com/facebook/react-native/issues/36710

I found a temp/possible solution for it, after researching for more than 2 weeks. 

Use `onPressIn` instead of `onPress` !

**Comment by vrgimael** [comment]
> > @jugshaurya I can confirm I'm having the same issue, using 71.10, android. It basically makes the new architecture unusable on Android, unless you plan to have no animation. It's occurring with all touchables and pressables.
> > related: #36710
> 
> I found a temp/possible solution for it, after researching for more than 2 weeks.
> 
> Use `onPressIn` instead of `onPress` !
> 
> Let me know if it also works for you. Also to increase tappable area to make button more responsive, you can use `hitslop` prop.

This is not a solution as it triggers accidentally on any scrollable item

**Comment by jugshaurya** [comment]
> > > @jugshaurya I can confirm I'm having the same issue, using 71.10, android. It basically makes the new architecture unusable on Android, unless you plan to have no animation. It's occurring with all touchables and pressables.
> > > related: #36710
> > 
> > I found a temp/possible solution for it, after researching for more than 2 weeks.
> > 
> > Use `onPressIn` instead of `onPress` !
> > 
> > Let me know if it also works for you. Also to increase tappable area to make button more responsive, you can use `hitslop` prop.
> 
> This is not a solution as it triggers accidentally on any scrollable item

Can you share an example gif or something to get the better context, because i used this solution for codebase, it is working fine.

**Comment by cipolleschi** [comment]
Hi everyone, we have this investigation marked as high priority, so we hopefully would be able to make progress on this as fast as we can.

To help us out, we would greatly appreciate a reproducer starting from [this repo](https://github.com/react-native-community/reproducer-react-native). I understand that the issue does not reproduce consistently, but if you can set up something and tell us how and how much we need to interact with the repro to get the issue happening, this will help us a lot.

Thank you all for the cooperation! 🙏

**Comment by sonicbaume** [comment]
@cipolleschi Here's the example from @ThinkerLu as a reproducer repo, and a video of the result.

Reproducer: https://github.com/sonicbaume/fabric-onpress-bug-reproducer

Video:

https://github.com/facebook/react-native/assets/102724304/97806c87-4788-488a-8f2b-593ea286d300

**Comment by sonicbaume** [comment]
@cipolleschi Is this still considered high priority? Is there anything else you need?

**Comment by cortinico** [comment]
> @cipolleschi Is this still considered high priority? Is there anything else you need?

Yes it is. If someone is willing to attempt to fix it and send a PR, it would be greatly appreaciated. Otherwise we'll eventually fix it in the (hopefully soon) future

**Comment by cipolleschi** [comment]
Thanks for your patience, competing priorities took most of my time. :( 

As @cortinico said, we want to fix this issue, together with some other that are affecting the New Architecture. Bear with us, we will get there.

**Comment by cipolleschi** [comment]
Hi @sonicbaume @ThinkerLu @iMonk777 @jugshaurya @vrgimael, sorry that this took us so long.

I was trying the reproducer and it feels like it is fixed on 0.74.1 with regular touches.

There is still something weird related to when you tap-drag-release within the button. It looks that `onPress` is not invoked in that case. It works if you click-drat to the top-release: it looks like that when we 'release' the touch, we are not considering the translated position.

https://github.com/facebook/react-native/assets/11162307/d8239609-57b8-45b9-b6c6-af363d52f4ca

**Comment by cipolleschi** [comment]
This will be fixes in 0.76.

**Comment by 61xin** [comment]
> This will be fixes in 0.76.

Hi @cipolleschi,  what is the commit id that fixed this bug?

**Comment by 61xin** [comment]
> @61xin there are multiple commits required to fix this issue. It will be quite hard to backport the fix to previous versions, plus the New Architecture is considered stable and ready for production in 0.76. So I strongly suggest to update to 0.76 if you want to migrate to the New Architecture, also because that version will contains many more fixes for the New Arch.

ok，thank you!

**Comment by fdecampredon** [comment]
@61xin  After upgrading to 0.76.1 I can say that the issue is still present

**Comment by cipolleschi** [comment]
@fdecampredon can you share a reproducer? We have a screen in RNTester to test this case and I'm sure it was fixed. Maybe we missed some edge case.

**Comment by fdecampredon** [comment]
@cipolleschi I'm really sorry after more investigation I think it is more related to this one : https://github.com/facebook/react-native/issues/44768.
We'll try to make a minimal reproduction example but it's a bit hard since the problem is deeply nested in a very complex screen.

**Comment by ZhangBinglei2015** [comment]
I am using  react native 0.72 and this solve my problem，you can try it!

```
import type {ViewProps} from 'react-native'
import {PanResponder, View} from 'react-native'

export type TouchComponentProps = {
  onPress: () => void
}

export default (props: ViewProps & TouchComponentProps) => {
  const panresponder = PanResponder.create({
    onStartShouldSetPanResponder: () => true,
    onShouldBlockNativeResponder: () => false,
    onPanResponderRelease: () => {
      props.onPress()
    },
  })

  return (
    <View {...props} {...panresponder.panHandlers}>
      {props.children}
    </View>
  )
}
```

**Comment by kirillzyusko** [comment]
After digging in the code even more I realized that for a `ScrollView` you additionally call `userDrivenScrollEnded` method, which sends `onUserDrivenAnimationEnded` event, and this event gets broadcasted to all `Animated.View`s:

```ts
NativeAnimatedHelper.nativeEventEmitter.addListener(
  'onUserDrivenAnimationEnded',
  data => {
    node.update();
  },
);
```

While I understand, that this approach works for `ScrollView`... Is this approach scalable? For example I may want to send `onUserDrivenAnimationEnded` when keyboard finishes its animation to synchronize shadow-tree, but keyboard animation is not even user-driven animation 🙈 

And theoretically for each 3rd party package that drives animations (i. e. changes `translate` via native driver) we have to add this "synchronization" code?

**Comment by cipolleschi** [comment]
@kirillzyusko sorry for the delay... You performed a very deep investigation, so you have discovered almost everything yourself! :D 

The problem here is how to keep the react tree in sync with the shadow tree and that in sync with the native tree.

The approach of `onUserDrivenAnimationEnded` works with `ScrollView` and every component based on `ScrollView` gets it for free.
This works for animation driven by the user, because we don't know when the animation actually ends. 
For timed animations, such as the opening/closing of the keyboard, we know exactly when the Animation end. We also usually have a callback for it. In those cases, there is another events that the component should emit, that forces the alignment of the trees:  i think that is `onAnimatedValueUpdate`, but I might have to double check.

It should be the same event emitted by scroll view when you call `scrollTo`.

When we have natively driven animations, sending an event from native to JS is the only way to tell React that the trees need to be realigned.

It scales, as an approach, but we would have to be clearer with our Documentation, and given that the code changes so fast, we haven't been as good as we should with that.

We are also exploring other alternatives to the Animated backend, so I hope that the situation could improve soon!
