### ISSUE TITLE
Error when updating to v0.71.4 from v0.68.1

### ISSUE THREAD

**Issue by Abhishek2250** [facebook/react-native#36676]
### New Version

0.71.4

### Old Version

0.68.1

### Build Target(s)

iPhone 14 Pro, iOS version 16.2

### Output of `react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 220.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/abhi/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Issue:
**Unable to resolve any module**

`  error: Error: Unable to resolve module react-native-gesture-handler from /Users/abhi/PROJECT/PROJECT-mob/PROJECT/index.js: react-native-gesture-handler could not be found within the project or in these directories:
  node_modules
  1 | /** @format */
> 2 | import "react-native-gesture-handler"; // fix for https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-443815828
    |                                                                               ^
  3 | import "core-js/es/weak-set"; // only for android; polyfill
  4 | import { AppRegistry, Platform, LogBox } from "react-native";
  5 | import App from "./App";`

**When I comment this out then I get another error:**

`error: Error: Unable to resolve module ./app.json from /Users/abhi/PROJECT/PROJECT-mob/PROJECT/index.js: 
None of these files exist:
  * app.json(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs)
  * app.json/index(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs)
   5 | import App from "./App";
   6 | import ShareApp from "./ShareApp";
>  7 | import { name as appName } from "./app.json";
     |                                  ^
   8 | import "./PROJECT_globals";
   9 |
  10 | if (__DEV__) {`

**After commenting above issue, got another:**

error: Error: Unable to resolve module invariant from /Users/abhi/PROJECT/PROJECT-mob/PROJECT/node_modules/react-native/index.js: invariant could not be found within the project or in these directories:
  node_modules/react-native/node_modules
  node_modules
  100 | export type HostComponent<T> = _HostComponentInternal<T>;
  101 |
> 102 | const invariant = require('invariant');
      |                            ^
  103 | const warnOnce = require('./Libraries/Utilities/warnOnce');

This goes on...
I cleaned the project, cleared cache(metro/pod), and removed node modules, package-lock, pods, podfile.lock, build folder and still getting this error.

Anything I'm doing wrong?

Thanks

**Comment by snamstorm** [comment]
I am having the same issue while upgrading.

I've tried the solution suggester here but still not working
https://stackoverflow.com/questions/75306866/getting-these-errors-while-installing-packages-on-react-native/75306961#75306961

For iOS, I am able to build the application and when the app launches, I see the error. 
For Android, the error is thrown while building the app. 

I've checked all the files that have been changed and I can't see any missteps in my config. 

Any insights will be greatly appreciated

**Comment by efstathiosntonas** [comment]
did you tried running metro with the `--reset-cache` flag?

**Comment by ale917k** [comment]
I recently did a similar upgrade as well (from `0.67.5`) and had the same issue; Think I got it resolved with a hard clean install - Give the below a try (run from your project root folder):
```
cd ios && rm -rf ~/Library/Caches/CocoaPods && rm -rf Pods && rm -rf ~/Library/Developer/Xcode/DerivedData/* && pod deintegrate && pod setup && cd .. && rm -rf node_modules yarn.lock Podfile.lock && yarn && npx pod-install ios && yarn start --reset-cache
```

**Comment by blakef** [comment]
@Abhishek2250 can you confirm if you've had any success clearing your caches?

**Comment by snamstorm** [comment]
I upgraded my Xcode and now having this issue https://github.com/facebook/react-native/issues/36635 - Waiting for 71.6 to drop so that I can try again

But before the upgrade of Xcode, I will still getting the same error despite clearing all the caches etc. Strangely, I was getting this error only when building using the cmd line. When I was building using Xcode directly, I was getting a different error `react-native-permissions lib is null`

**Comment by Abhishek2250** [comment]
@blakef I'm still getting the same error even after clearing the caches

**Comment by ukcasso** [comment]
don't use `resolver: { sourceExts: ['', '', ''] }` in `metro.config.js`
if you use `resolver`, try
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
-      resolver: {
-      sourceExts: ['jsx', 'js', 'ts', 'tsx', 'cjs'],
-    },
    }),
  },
};

**Comment by Abhishek2250** [comment]
@ukcasso This fixed the issue. Thank you so much

However, I'm getting another error but don't see much of a stack trace:

1st error:
`libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: Cannot read property 'prototype' of undefined, js engine: hermes', reason: 'Unhandled JS Exception: TypeError: Cannot read property 'prototype' of undefined, js engine: hermes, stack:`

2nd error: 
`error: Error: While trying to resolve module `idb` from file `/Users/PROJECT_NAME/lib/PROJECT_NAME-mob/PROJECT_NAME/node_modules/@firebase/app/dist/esm/index.esm2017.js`, the package `/Users/PROJECT_NAME/lib/PROJECT_NAME-mob/PROJECT_NAME/node_modules/idb/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/PROJECT_NAME/lib/PROJECT_NAME-mob/PROJECT_NAME/node_modules/idb/build/index.cjs`. Indeed, none of these files exist:`

**Comment by Abhishek2250** [comment]
> recently, has updated react-native template `metro.config.js` [c5a47ab#diff-619f431646870af3d1f29fafda5bead2f4a41ca1869f1a3f18dc01acab4bf5b0](https://github.com/facebook/react-native/commit/c5a47abaf894235f71eea03e57d2f5287d80f3d4#diff-619f431646870af3d1f29fafda5bead2f4a41ca1869f1a3f18dc01acab4bf5b0)
> 
> don't use `resolver: { sourceExts: ['', '', ''] }` in `metro.config.js` if you use `resolver`, try
> 
> ```
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> module.exports = {
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: true,
>       },
> -      resolver: {
> -      sourceExts: ['jsx', 'js', 'ts', 'tsx', 'cjs'],
> -    },
>     }),
>   },
> };
> ```

this fixed the issue, closing this.
Thanks

**Comment by Sagargajul41** [comment]
Hi everyone,
I am getting below error after my react native version moved from 0.64 to 0.70 in my current project.
New Version
0.70.13
Old Version
0.64.2
Can anyone help me  with this issue?

error: Error: Unable to resolve module ./app.json from D:\VR-Setup\UI-Projects\newproject\index.js:

None of these files exist:
  * app.json(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js)
  * app.json\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js)
   5 | import {AppRegistry} from 'react-native';
   6 | import App from './App';
>  7 | import {name as appName} from './app.json';
     |                                ^
   8 | import 'react-native-gesture-handler';
   9 | AppRegistry.registerComponent(appName, () => App);
  10 |
    at ModuleResolver.resolveDependency (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:152:15)
    at DependencyGraph.resolveDependency (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\node-haste\DependencyGraph.js:264:43)
    at Object.resolve (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\lib\transformHelpers.js:170:21)       
    at resolveDependencies (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:466:33)
    at processModule (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:232:31)    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async traverseDependenciesForSingleFile (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:221:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:204:3)

**Comment by maksudkhan7706** [comment]
> > recently, has updated react-native template `metro.config.js` [c5a47ab#diff-619f431646870af3d1f29fafda5bead2f4a41ca1869f1a3f18dc01acab4bf5b0](https://github.com/facebook/react-native/commit/c5a47abaf894235f71eea03e57d2f5287d80f3d4#diff-619f431646870af3d1f29fafda5bead2f4a41ca1869f1a3f18dc01acab4bf5b0)
> > don't use `resolver: { sourceExts: ['', '', ''] }` in `metro.config.js` if you use `resolver`, try
> > ```
> > /**
> >  * Metro configuration for React Native
> >  * https://github.com/facebook/react-native
> >  *
> >  * @format
> >  */
> > 
> > module.exports = {
> >   transformer: {
> >     getTransformOptions: async () => ({
> >       transform: {
> >         experimentalImportSupport: false,
> >         inlineRequires: true,
> >       },
> > -      resolver: {
> > -      sourceExts: ['jsx', 'js', 'ts', 'tsx', 'cjs'],
> > -    },
> >     }),
> >   },
> > };
> > ```
> 
> this fixed the issue, closing this. Thanks

Thanks a lot
