### ISSUE TITLE
Android 13 (SDK 33) Permission Issue

### ISSUE THREAD

**Issue by venukaaventude** [facebook/react-native#36714]
### Description

Hi,
I am unable to request permission for storage. It always returns {"android.permission.READ_EXTERNAL_STORAGE": "never_ask_again", "android.permission.WRITE_EXTERNAL_STORAGE": "never_ask_again"} whenever I try to ask for permission. I tried everything but still the the permission is not allowed on Android 13, sdk 33.

Your help will be really appreciated.

Thank you.

### React Native Version

0.60.6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 85.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /var/folders/xb/vpg5x6bn70j8zj9kq_xl9jv80000gn/T/yarn--1680154755528-0.49562717776096243/node
    Yarn: 1.22.19 - /var/folders/xb/vpg5x6bn70j8zj9kq_xl9jv80000gn/T/yarn--1680154755528-0.49562717776096243/yarn
    npm: 9.1.2 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 21, 23, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native: 0.70.4

### Steps to reproduce

- declare permission issue in manifest file

    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="29" />

- request for storage permission

     const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('Storage Permission Granted.');
      } else {
        Alert.alert('Error', 'Storage Permission Not Granted');
      }

- result

{"android.permission.READ_EXTERNAL_STORAGE": "never_ask_again", "android.permission.WRITE_EXTERNAL_STORAGE": "never_ask_again"}

### Snack, code example, screenshot, or link to a repository

<img width="886" alt="Screenshot 2023-03-30 at 11 13 42" src="https://user-images.githubusercontent.com/116064318/228740783-0d7ee6d1-1f4c-43e9-bc07-931711350fb0.png">
<img width="886" alt="Screenshot 2023-03-30 at 11 14 12" src="https://user-images.githubusercontent.com/116064318/228740790-133a8805-ffbb-4ec5-af20-7ea5aa6d7a30.png">

**Comment by efstathiosntonas** [comment]
@venukaaventude asking for these permissions on Android 13 it's no longer needed. 

More info: 
https://stackoverflow.com/a/73630987/2195000

**Comment by venukaaventude** [comment]
@efstathiosntonas 
thanks for your support.
i figure out the problem we can handle the from **AndroidManifest.xml** , no need to go to the code level. this is how i fixed that issue

```
   <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="29" />
```

**Comment by neethusathya97** [comment]
Hi 

I am using  @ionic-native/media-capture pluigin for my react ionic project with capacitor 5. The media capture for video, audio and camera is working fine in Android 12 and below  devices and also iOS devices .But for android 13 devices the camera capture is not working.Tried out new permission for media in android manifest as suggested in android documentation still not working.We came to know that the ionic.native was replaced with @awesome-cordova-plugins. We tried this also, but didn't worked.

Permission code  added in android.manifest file is given below:-
   <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />

if any solutions.Please suggest
