### ISSUE TITLE
RN0720RC0

### ISSUE THREAD

**Issue by Zagorevsky** [facebook/react-native#36787]
### Description

npx react-native run-ios  
info Found Xcode workspace "RN0720RC0.xcworkspace"
info Found booted iPhoneOleg, iPhone 13
info Building (using "xcodebuild -workspace RN0720RC0.xcworkspace -configuration Debug -scheme RN0720RC0 -destination id=5847661e0e788b4d8dbf49850d7bc63ee497a175")

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RN0720RC0.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RN0720RC0.xcworkspace -configuration Debug -scheme RN0720RC0 -destination id=5847661e0e788b4d8dbf49850d7bc63ee497a175

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 2b02914fc48f153a55474516731d47ac
Build description path: /Users/zagor/Library/Developer/Xcode/DerivedData/RN0720RC0-dpkefiocaqjunqfpjnrtiwtdpmgs/Build/Intermediates.noindex/XCBuildData/2b02914fc48f153a55474516731d47ac.xcbuilddata

note: Building targets in dependency order
/Users/zagor/Documents/dev/RN0720RC0/ios/RN0720RC0.xcodeproj: error: Signing for "RN0720RC0" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RN0720RC0' from project 'RN0720RC0')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RN0720RC0' from project 'RN0720RC0')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RN0720RC0' from project 'RN0720RC0')

2023-04-04 09:37:19.119 xcodebuild[37991:15908681] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
** BUILD FAILED **

info Run CLI with --verbose flag for more details.

### React Native Version

0.72.0-rc.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.2.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
  Memory: 36.23 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.03.20.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0-rc.0
    wanted: 0.72.0-rc.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

npx react-native run-ios  
info Found Xcode workspace "RN0720RC0.xcworkspace"
info Found booted iPhoneOleg, iPhone 13
info Building (using "xcodebuild -workspace RN0720RC0.xcworkspace -configuration Debug -scheme RN0720RC0 -destination id=5847661e0e788b4d8dbf49850d7bc63ee497a175")

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RN0720RC0.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RN0720RC0.xcworkspace -configuration Debug -scheme RN0720RC0 -destination id=5847661e0e788b4d8dbf49850d7bc63ee497a175

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 2b02914fc48f153a55474516731d47ac
Build description path: /Users/zagor/Library/Developer/Xcode/DerivedData/RN0720RC0-dpkefiocaqjunqfpjnrtiwtdpmgs/Build/Intermediates.noindex/XCBuildData/2b02914fc48f153a55474516731d47ac.xcbuilddata

note: Building targets in dependency order
/Users/zagor/Documents/dev/RN0720RC0/ios/RN0720RC0.xcodeproj: error: Signing for "RN0720RC0" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RN0720RC0' from project 'RN0720RC0')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RN0720RC0' from project 'RN0720RC0')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RN0720RC0' from project 'RN0720RC0')

2023-04-04 09:37:19.119 xcodebuild[37991:15908681] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
** BUILD FAILED **

info Run CLI with --verbose flag for more details.

### Snack, code example, screenshot, or link to a repository

How To Test
Generate a new project with the standard command:

npx react-native@latest init RN0720RC0 --version 0.72.0-rc.0

**Comment by blakef** [comment]
I couldn't reproduce this locally with the steps you've provided:
> npx react-native@latest init RN0720RC0 --version 0.72.0-rc.0
> cd RN0720RC0 && npx react-native run-ios

**Comment by kelset** [comment]
@Zagorevsky we have just released RC1, and just like @blakef I wasn't able to repro your problem.

**Comment by ottosamatori** [comment]
same problem

**Comment by sidneip** [comment]
[RUN_FASTLANE] 2023-04-12 18:37:09.968 xcodebuild[98957:773832] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[RUN_FASTLANE] Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[RUN_FASTLANE] 2023-04-12 18:37:13.020 xcodebuild[98969:774012] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[RUN_FASTLANE] 2023-04-12 18:37:17.494 xcodebuild[98969:774081] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
[RUN_FASTLANE] 2023-04-12 18:37:17.494 xcodebuild[98957:773863] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition

**Comment by NicholusMuwonge** [comment]
I still face this issue, any one resolved it? I saw [this](https://stackoverflow.com/a/75979879) answer working for some people but in my case don't even have the `Pod-Runner-frameworks` folder.

**Comment by parasraipeacenepal** [comment]
> I still face this issue, any one resolved it? I saw [this](https://stackoverflow.com/a/75979879) answer working for some people but in my case don't even have the `Pod-Runner-frameworks` folder.

Pod-Runner-frameworks is the file of flutter as flutter refer ios project as Runner

you may find your file as Pod-{Project_name}-frameworks

**Comment by sergey-king** [comment]
same issue Expo 48 + Turborepo setup

```
[RUN_FASTLANE] 2023-04-13 18:57:16.142 xcodebuild[9396:62038] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[RUN_FASTLANE] Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[RUN_FASTLANE] 2023-04-13 18:57:19.190 xcodebuild[9400:62106] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[RUN_FASTLANE] 2023-04-13 18:57:22.042 xcodebuild[9396:62073] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
```
