### ISSUE TITLE
ReactRootView not wrapping to it's content (Android only)

### ISSUE THREAD

**Issue by ilber** [facebook/react-native#38024]
### Description

We have some code in our app that creates a new ReactRootView and add's the view to an existing Android Native View.
Once we upgraded to version 0.71.x we noticed that the size of the ReactRootView is not resizing to it's content as it was doing in the versions before. Now the view is always shown to Fit the parent container. Is that intentional?
Is there a way to go back to the previous behaviour?

### React Native Version

0.71.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 131.39 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2022.10.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ilber/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 21, 22, 27, 28, 31, 33, 33, 34
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 32.0.0, 33.0.1, 33.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /Users/ilber/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.11 => 0.71.11
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

 val view = ReactRootView(currentActivity).apply {
        startReactApplication(
            reactInstanceManager,
          "ModuleName",
            "InitialProps"
        )
        layoutParams = ViewGroup.LayoutParams(WRAP_CONTENT, WRAP_CONTENT)
    }
    
    
// add the view to the native stack.

### Snack, code example, screenshot, or link to a repository

No

**Comment by ilber** [comment]
React Native Version

0.71.0

**Comment by ilber** [comment]
I switched using 0.71.11 but the same issue is shown.
My JS Componente is like this:
```
<View style={styles.arBubbleContainer}>
          <View style={styles.arBubbleImageContainer}>
            <Image source={require('./StockCountIcon.png')} style={styles.arBubbleImage} />
          </View>
          <View style={styles.arBubbleContent}>
            {showBarcodeData ? <Text style={styles.arBubbleHeader}>{this.props.barcodeData}</Text> : stockInfo}
          </View>
        </View>
   ```
   
   and this the style:
   `arBubbleContainer: {
    width: 200,
    height: 50,
    backgroundColor: '#FFFE',
    borderRadius: 25,
    flexDirection: 'row',
  },
  arBubbleContent: {
    width: 150,
    height: 50,
    justifyContent: 'center',
    paddingLeft: 10,
  },
    arBubbleHeader: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  arBubbleInfo: {
    fontSize: 12,
  },
  arBubbleImageContainer: {
    width: 50,
    height: 50,
    backgroundColor: '#52C2B6',
    borderRadius: 25,
  },
  arBubbleImage: {
    width: 50,
    height: 50,
  },`

**Comment by ilber** [comment]
I have captured also the screenshot of the view inspector to check the difference between the 2 versions of RN:

This is the version with 0.70.6:

https://drive.google.com/file/d/1lmMyN7kEKUi8rynhxqLFDJEY2Mw8LYXw/view?usp=sharing

This is the version with 0.71.11:

https://drive.google.com/file/d/1eL9zrsmEJ2xqpB5udeANdmAL_OeBz6Qb/view?usp=sharing

**Comment by cortinico** [comment]
@NickGerleman is this potentially related to:
- https://github.com/facebook/react-native/pull/35897

?

**Comment by NickGerleman** [comment]
> @NickGerleman is this potentially related to:
> 
> * [Only Use WindowInsets for Keyboard Events on Android 11+ #35897](https://github.com/facebook/react-native/pull/35897)
> 
> ?

Very unlikely. That code is just adding some queries to an existing event handler, for firing an existing event, and doesn’t do any sort of mutation.

**Comment by ilber** [comment]
Does anyhow have a clue what did break in 0.71.x? This is a big breaking change for us because we rely a lot on showing the RN JS views inside the android native view.

**Comment by shivenmian** [comment]
#38473 is also related to this. This issue is breaking brownfield UX on Android from 0.71 onwards - please triage accordingly @cortinico

**Comment by NickGerleman** [comment]
I think this and the bottom sheet issue are unlikely to be related to a Yoga change. FYI @luluwu2032 in case this seems related to any changes during that time period (7/22-11/22) before Meta may have made, but I think a lot of Paper changes have been originating from OSS these days.

@shivenmian we might be able to find potentially relevant commits by looking at commits to Android RootView code between the versions (commits between 7/22-11/22). I expect this sort of change would happen around this layer: https://github.com/facebook/react-native/blob/04ad34d6ad64c702d6619aa5a358ddd376f8be8e/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L4

**Comment by NickGerleman** [comment]
One other strategy if you have an easy local repro is to do a bisect of commits within that single release period.

**Comment by cortinico** [comment]
@NickGerleman potentially relevant:
https://github.com/facebook/react-native/issues/38473#issuecomment-1638595994

**Comment by rasaha91** [comment]
@NickGerleman could you provide some more instructions on what you mean? In our test app we can specify a version of react-native in package.json, but I don't think react-native produces a release for every commit? I might be misunderstanding what you are suggesting.

**Comment by NickGerleman** [comment]
Either:
1. Using the nightlies published by RN
2. Building from source.

**Comment by rasaha91** [comment]
As an update, I locally built 0.71-stable, reverting the commit for the devtools overlay and things start working. So I think it's fair to conclude that commit caused the regression. I'm not sure what the proper fix is, but I would like to propose reverting that commit in main and cherry-picking it to 0.71-stable and 0.72-stable for now. @NickGerleman  @cortinico  Does this seem like a reasonable approach?

**Comment by NickGerleman** [comment]
This line looks suspicious: https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c#diff-2a40597b015e446bd9cb647f972aad51d3cdbf396e43b1f52fe35029f8152e32R151

New React Devtools overlay takes up space based on screen dimensions, which is incorrect when the root view is smaller than the screen.

Does this repro outside of DEV bundles?

IIRC @hoxyq might have been looking at DevTools overlay more recently.

**Comment by NickGerleman** [comment]
Directly reverting the diff would introduce a fairly noticeable devx regression, and I think this change interacts with future changes.

Forward fix is the right move imo, especially if there is a scoped enough fix to be backported. See https://github.com/reactwg/react-native-releases/discussions/78 for pick requests.

**Comment by NickGerleman** [comment]
Re #1: This should be fairly easy to workaround. If you are getting a window-space coordinate from ‘measureInWindow’, you can do the same measurement on the overlay, and subtract the offsets, to get a local offset instead.

Re #2: Does the same thing work in browser with the same structure and everything display: flex? Would love to log it if so. But otherwise, if a real height is needed, we could always fall back to onLayout or measurement of user provided content in the worse case.

**Comment by rasaha91** [comment]
Correct that this is DEV only, but having this much of a discrepancy between the debug and release bundle is not ideal from a developer experience standpoint. Please see https://github.com/facebook/react-native/issues/38473 if you need a minimal repro.

**Comment by rasaha91** [comment]
Further clarification. This issue would have repro'd on release builds if you were on 0.71.11, but for a different reason. That was due to a view flattening regression which was fixed (see my comments in https://github.com/facebook/react-native/issues/38473). The result of that regression was similar to the devtools overlay issue, i.e. reactrootview not sized properly. @ilber your issue will likely be resolved if you bump to 0.71.12 and test a release build. It will be broken in dev mode though until the devtools overlay issue is fixed.

**Comment by ilber** [comment]
Will test and let you know. Thanks for the heads up.

**Comment by ilber** [comment]
I can confirm that with 0.71.12 in release mode everything works as expected. Thank you

**Comment by rasaha91** [comment]
@ilber  thanks for confirming. Can you also confirm whether the issue is still occurring in dev mode for you?

**Comment by ilber** [comment]
I just tested in Debug and I can confirm that the issue is still occurring.

**Comment by shivenmian** [comment]
> Correct that this is DEV only, but having this much of a discrepancy between the debug and release bundle is not ideal from a developer experience standpoint. Please see #38473 if you need a minimal repro.

@hoxyq @NickGerleman as pointed out by @rasaha91 here, this issue is leading to a large discrepancy between how the debug and release bundles look. This essentially means the dev bundles can't really be used, and one has to look at the ship bundles when debugging, which is pretty bad developer experience. You ideally expect the dev and ship bundles to have the same UI.

As a example of what impact this causes - one of our experiences was affected by this whitespace issue, and it took 1.5 weeks of trying to debug this with the dev bundle before we realized the dev bundle was broken due to this issue, and the issue was fixed on ship, and so we essentially wasted our time. 

Would appreciate if you can look into patching c52df02 - it is reproing on RN72 as well.

**Comment by hoxyq** [comment]
> > Correct that this is DEV only, but having this much of a discrepancy between the debug and release bundle is not ideal from a developer experience standpoint. Please see #38473 if you need a minimal repro.
> 
> @hoxyq @NickGerleman as pointed out by @rasaha91 here, this issue is leading to a large discrepancy between how the debug and release bundles look. This essentially means the dev bundles can't really be used, and one has to look at the ship bundles when debugging, which is pretty bad developer experience. You ideally expect the dev and ship bundles to have the same UI.
> 
> As a example of what impact this caused - one of our experiences was affected by this whitespace issue, even after we bumped to 0.71.12 (which had the [view flattening fix](https://github.com/reactwg/react-native-releases/discussions/70)). It took 1.5 weeks of trying to debug this with the dev bundle before we realized the dev bundle was broken and the issue was fixed on ship with 0.71.12, which meant we essentially wasted our time.
> 
> Would appreciate if you can look into fixing this issue in [c52df02](https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c) - it is reproing on RN72 as well. Thanks!

I would prioritise fixing this, and I will try to look at it this week.

One strange thing: this is not the only overlay that assigns its height to `Dimensions.get('window').height`. There is also [`InspectorOverlay`](https://github.com/facebook/react-native/blob/e64756ae5bb5c0607a4d97a134620fafcb132b3b/packages/react-native/Libraries/Inspector/InspectorOverlay.js#L60), which was like this for *years*. Can someone try to reproduce this issue with Inspector opened? It can be done via dev menu.

cc @tyao1

**Comment by rasaha91** [comment]
@hoxyq I just checked on 0.70 and when you turn on inspector, the react instance resizes and causes the issue. You can try it in my repro app. 

Before launching inspector:

<img width="224" alt="image" src="https://github.com/facebook/react-native/assets/55814622/2471f2c2-d45d-4c36-b027-f4dc4b0c730f">


After launching inspector:

<img width="224" alt="image" src="https://github.com/facebook/react-native/assets/55814622/0c09507a-1dfa-48a4-b245-9b3b7e6f6c19">


So it seems element inspector has the same bug, but because the component isn't in the component tree initially, things work out. Once you turn on inspector, the component tree changes, and then the native tree changes and we observe the same issue with devtools overlay. So technically both of these scenarios should be fixed and I imagine it's the same fix.

**Comment by rasaha91** [comment]
Couple of other thoughts.
1. Does this issue occur on iOS? I don't have a mac so I wasn't able to test and my repro app doesn't have an iOS build.
2. Does RN have any UI automation for non-fullscreen UI? It would be ideal to add a test scenario to prevent this use case from breaking.

**Comment by hoxyq** [comment]
Update: https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c is not the one that introduces this regression.

We render this View only if React DevTools' hook is injected, basically when React DevTools is opened and connected.
Also, rendering this full-height view is [gated under a flag](https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c#diff-2a40597b015e446bd9cb647f972aad51d3cdbf396e43b1f52fe35029f8152e32R145), which is true only if inspection with React DevTools was enabled.

**Comment by rasaha91** [comment]
Is it possible there was a regression, and that hook does not return null when we aren't inspecting? Even if that is the case, it was working prior to that commit. I don't know whether the root cause of the issue was introduced with https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c but I am reasonably sure that the issue starts occurring with that commit.

**Comment by hoxyq** [comment]
> Is it possible there was a regression, and that hook does not return null when we aren't inspecting? Even if that is the case, it was working prior to that commit. I don't know whether the root cause of the issue was introduced with [c52df02](https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c) but I am reasonably sure that the issue starts occurring with that commit.

Yeah, you are right, this condition is not false even if React DevTools are closed, but this component still returns null.

Oh, I think I got it, this is probably because `collapsable` [here](https://github.com/facebook/react-native/commit/c52df02f84f123a524259eac554f4d2407f1904c#diff-8775ef7007a14c01d4af4586428293fde5b58ee4c46c67203a24a26e6398e2e4R102) is false now with these changes.

Can you try validating it with removing this prop or setting it to `true`? Does this fix the issue for android?

**Comment by rasaha91** [comment]
@hoxyq I modified appcontainer.js in my node_modules to set collapsible to true and the issue still occurs. I verified using devtools that collapsible is set to true.

**Comment by rasaha91** [comment]
@hoxyq in 0.71-stable, setting collapsible to true fixes the issue. 

HOWEVER, in 0.72-stable you have to set collapsible to true AND delete the traceUpdateOverlay component. traceUpdateOverlay was introduced with https://github.com/facebook/react-native/commit/a2f155fdf3ee346af5de580e24deffd70909b070 .

**Comment by rasaha91** [comment]
I think the proper solution should ensure the UI doesn't resize even after enabling devtools or inspector. As such, collapsible shouldn't be a function of those.

**Comment by shivenmian** [comment]
@hoxyq apologies for the delay in testing, was sidetracked with a few critical tasks. I have tested this patch and it does fix the issue on RN72, and throws up the TraceUpdateOverlay error for RN71 as you mentioned. Please go ahead and merge this PR, and do patch this to RN71 as well :) Thanks so much again for this work, much appreciated! cc @kelset @fortmarek @cortinico

**Comment by rasaha91** [comment]
As an FYI, we have integrated the fix, and it works... sort of. If you have something like flipper running in the background, then devtools overlay will be mounted and it won't be obvious why the UI is behaving differently. @hoxyq it sounds like this issue will go away with the work you are doing in Q3?

**Comment by hoxyq** [comment]
> As an FYI, we have integrated the fix, and it works... sort of. If you have something like flipper running in the background, then devtools overlay will be mounted and it won't be obvious why the UI is behaving differently. @hoxyq it sounds like this issue will go away with the work you are doing in Q3?

Yes, I am planning to work on fixing it and hopefully this will be shipped in 0.74.
