### ISSUE TITLE
ScrollView does not work inside position: absolute on Android.

### ISSUE THREAD

**Issue by mirekuhlir** [facebook/react-native#38730]
### Description

ScrollView does not work inside position: absolute on Android. Scrolling works on iOS.

### React Native Version

0.71.11

### Output of `npx react-native info`

System:
    OS: macOS 12.6.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 131.35 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

ScrollView does not work inside position: absolute on Android. Scrolling works on iOS.

`   <View style={{ height: 300, paddingTop: 100 }}>
        <View
          style={{
            position: 'relative',
            height: 40,
            borderColor: 'red',
            borderWidth: 1,
          }}>
          <View
            style={{
              height: 60,
              position: 'absolute',
              width: '100%',
              borderColor: 'green',
              borderWidth: 1,
              zIndex: 1000,
              elevation: 1000,
            }}>
            <ScrollView>
              <Text>1</Text>
              <Text>2</Text>
              <Text>3</Text>
              <Text>4</Text>
              <Text>5</Text>
              <Text>6</Text>
            </ScrollView>
          </View>
        </View>
      </View>`

### Snack, screenshot, or link to a repository

https://snack.expo.dev/3enX3_UHW

**Comment by mirekuhlir** [comment]
Is this a bug or do I need to adjust something else?

**Comment by ponikar** [comment]
Can you make sure that you are importing `ScrollView` from react native and not from react-native-gesture-handler?

**Comment by ovgamesdev** [comment]
I think in absolute scrollView you can scroll only in the part that is in overflow: "hidden" this will work

```jsx
<View style={{ position: 'absolute', top: 0, right: 0, overflow: "hidden", width: 100, maxHeight: 50 }}>
    <ScrollView>{list}</ScrollView>
</View>
```

but it takes away the advantage of absolute.

I fixed this for my project via Modal here is an example 
https://snack.expo.dev/@eristoddle/react-native-select-dropdown

**Comment by SorenHK** [comment]
If anyone else is having this issue (like me), then using react-native-gesture-handler instead actually seems to fix the issue.

In your imports remove ScrollView and instead import:

`import { ScrollView } from 'react-native-gesture-handler';`

**Comment by Dhiraj-j** [comment]
I'm still not able to fix please someone help.

**Comment by caioedut** [comment]
+1

**Comment by TierryBr** [comment]
The problem remains whether importing from react-native-gesture-handler or react native.  Does anyone have any solution?

**Comment by Nsquik** [comment]
@SorenHK this actually solves the problem, thank you ❤️

**Comment by Meegan** [comment]
Can also report this problem, same issue with react-native-gesture-handler and react-native.

**Comment by fabOnReact** [comment]
I'm organizing my next tasks. Are you still interested in adopting a fix for this issue? Or have you already implemented a workaround? If you are interested, I will work on a solution. Thanks

**Comment by fabOnReact** [comment]
> If anyone else is having this issue (like me), then using react-native-gesture-handler instead actually seems to fix the issue.
> 
> In your imports remove ScrollView and instead import:
> 
> `import { ScrollView } from 'react-native-gesture-handler';`

it will not work on gesture handler on iOS

**Comment by HarwinBorger** [comment]
The solution provided by @SorenHK ( `import { ScrollView } from 'react-native-gesture-handler';` ) is working as a work-around, but it doesn't solve the original problem. A fix is still required to solve this problem.

**Comment by hlspablo** [comment]
having the same issue on the react 0.73.4 too

**Comment by prometixX** [comment]
I have the same issue on Expo 50.0 and React Native 0.73.4 too.

**Comment by yehonadav** [comment]
"react-native": "0.73.6",
    "expo": "~50.0.14",

i have an absolute component that takes the entire screen, inside it there's a working scrollview, in one of the scrollview's children, there's another component thats absolute and needs a scrollview, but scrollview does not work

**Comment by OscarMpy** [comment]
Same issue.

**Comment by KeunwooPark** [comment]
In my case, if the parent `View` of a `ScrollView` has `zIndex` property, scroll did not work on Android.

**Comment by KeunwooPark** [comment]
In my case, if a parent view of the `ScrollView` had `zIndex` property, scroll did not work at all on Android, regardless of the zIndex value.

**Comment by Devdre1909** [comment]
https://reactnative.dev/docs/scrollview#nestedscrollenabled-android

Using nestedScrollEnabled fix it for me
Thanks @OscarMpy

**Comment by Vimiso** [comment]
```import { ScrollView } from 'react-native-gesture-handler';```

Fixed the issue for me too. Is this really cheating? It just seems like they built a better scrolling view from the ground up that is more cross platform compatible?

My z-indexes are fine. I just want an absolute `View` that contains a `ScrollView` and for scrolling to be detected - is that too much ask?! Native gesture handler fixes this issue.

**Comment by lukaszrzasa** [comment]
For anyone that have still trouble with `react-native-gesture-handler`  that do not fix anything:

Please read installation page, where you have 3 main things:
- `<GestureHandlerRootView>` is required to have in a root of the app
- `<GestureHandlerRootView>` is required to have in every modal you want to use this ScrollView
- additional configuration that needs to be made for ios and other platforms ;)

Form me that fixes even the following combo (to test purposes):
`ScrollView -> Modal -> ScrollView -> absolute View -> ScrollView` (this last ScrollView didin't work before)

**Comment by iswiboni** [comment]
> <GestureHandlerRootView style={{ flex: 1 }}>

thanks you save me!

**Comment by iswiboni** [comment]
> [@lukaszrzasa](https://github.com/lukaszrzasa) thanks your solution worked i was missing the part where i have to wrap my app with `GestureHandlerRootView`
> 
> here this is what i did
> 
> <GestureHandlerRootView style={{ flex: 1 }}>
>     <NavigationContainer ref={navigationRef}>
>          <Stack.Navigator>
>            ....your navigation
>           </Stack.Navigator>
>       </NavigationContainer>
>   </GestureHandlerRootView>
> 
> then use scrollview from
> 
> import { ScrollView } from 'react-native-gesture-handler';
> 
> 
> <ScrollView>
>   My content
> </ScrollView>

Thanks you save me!

**Comment by onyedikachi23** [comment]
> If anyone else is having this issue (like me), then using react-native-gesture-handler instead actually seems to fix the issue.
> 
> In your imports remove ScrollView and instead import:
> 
> `import { ScrollView } from 'react-native-gesture-handler';`

Thanks. This worked for me.

Don't forget to wrap your app with `GestureHandlerRootView`: 

```tsx
import { GestureHandlerRootView } from 'react-native-gesture-handler';

export default function App() {
  return (
    <GestureHandlerRootView>
      <ActualApp />
    </GestureHandlerRootView>
  );
}

```
