### ISSUE TITLE
RCT-Folly error after upgradeing xcode Version 15.0 (15A240d)

### ISSUE THREAD

**Issue by techamit95ch** [facebook/react-native#39568]
### Description

The following build commands failed:
        CompileC <LOCATION>-duhrncqankvmlvaqzannliomyfdw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/json.o <LOCATION>/ios/Pods/RCT-Folly/folly/json.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (8) arm64 Apple M1 Pro
  Memory: 105.25 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.3
    path: ~/node_modules/.bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/opt/ruby/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "23"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 29.0.0
      - 29.0.1
      - 29.0.2
      - 29.0.3
      - 30.0.0
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
    System Images:
      - android-29 | Intel x86 Atom_64
      - android-29 | Google APIs ARM 64 v8a
      - android-29 | Google APIs Intel x86 Atom
      - android-30 | Intel x86 Atom_64
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google APIs Intel x86 Atom
      - android-31 | Intel x86 Atom_64
      - android-32 | Google APIs ARM 64 v8a
      - android-32 | Google APIs Intel x86 Atom_64
      - android-32 | Google Play ARM 64 v8a
      - android-32 | Google Play Intel x86 Atom_64
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

yarn react-native run-iOS

### Snack, screenshot, or link to a repository

it's confidential

**Comment by RalissonMattias** [comment]
Same here, I need to update my native library because the ios 17 broke her and i get this the same error

**Comment by HowardTangHw** [comment]
https://github.com/facebook/react-native/issues/37748
 
 It's worked for me

**Comment by matthieu-alc** [comment]
If you don't need xcode Version 15.0 you can downgrade to previous version :

- Go to https://developer.apple.com/download/all/ and download previous Xcode version (14.3.1 at the moment).
- Unzip it
- Open Xcode > Settings > Locations, and select the downloaded version in `Command Line Tools` field (if you don't see the downloaded version try close an reopen Xcode)
- Optionally check the output of `npx react-native info` => You should see  `Xcode: 14.3.1` in the `IDEs` section
- Exit the settings and now try again to launch `yarn react-native run-iOS`, it should be working as before Xcode upgrade

**Comment by erickbennett** [comment]
Getting a similar RTC-Folly error. Xcode 15 with RN 0.72.5. Xcode says the error is in Folly/Time line 52, see screen. 
Error was occurring on RN 0.71.7 as well. We upgraded RN in an attempt to troubleshoot the issue. 

<img width="683" alt="rtc-folly-xcode15-error" src="https://github.com/facebook/react-native/assets/9040219/984f2671-0c75-4d5f-b418-10b8e2169a6d">

**Comment by ryanlanciaux** [comment]
Unlikely that this is an actual fix, but if I comment out line 52, it gets past this issue. (And later fails on the linker seemingly unrelated to this but I could be wrong)

**Comment by erickbennett** [comment]
Good call. That helped resolve the issue for me. I needed that 12_5 fix and the 14_3. 

Here's what I added to my pod file:

#before your project and target

def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = min_ios_version_supported
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
      end
    end
  end
end

# here's what the post installer looks like
 post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath],
    :mac_catalyst_enabled => false)
    
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    __apply_Xcode_14_3_RC_post_install_workaround(installer)
  end

**Comment by FarahWe** [comment]
I Just run the project at xcode, crashed and after that xcode suggested me to fix a line at file _hash.hpp_.

This is what a changed!

`
#else
        template <typename T>
    struct hash_base : std::__unary_function<T, std::size_t> {};
#endif
`

This is the code what crashed before

`
#else
        template <typename T>
    struct hash_base : std::unary_function<T, std::size_t> {};
#endif
`

**Comment by LeviWilliams** [comment]
I was able to get rid of the folly build errors by rearranging my build phases, specifically moving our copepods phases up in the order

**Comment by jormelCoin** [comment]
> If you don't need xcode Version 15.0 you can downgrade to previous version :
> 
> * Go to https://developer.apple.com/download/all/ and download previous Xcode version (14.3.1 at the moment).
> * Unzip it
> * Open Xcode > Settings > Locations, and select the downloaded version in `Command Line Tools` field (if you don't see the downloaded version try close an reopen Xcode)
> * Optionally check the output of `npx react-native info` => You should see  `Xcode: 14.3.1` in the `IDEs` section
> * Exit the settings and now try again to launch `yarn react-native run-iOS`
> 
> This worked for me

this worked for me. Thanks

**Comment by ahinkle** [comment]
> If you don't need xcode Version 15.0 you can downgrade to previous version :
> 
> Go to https://developer.apple.com/download/all/ and download previous Xcode version (14.3.1 at the moment).
> Unzip it
> Open Xcode > Settings > Locations, and select the downloaded version in Command Line Tools field (if you don't see the downloaded version try close an reopen Xcode)
> Optionally check the output of npx react-native info => You should see Xcode: 14.3.1 in the IDEs section
> Exit the settings and now try again to launch yarn react-native run-iOS
> This worked for me
> 
> this worked for me. Thanks

Where do you unzip the old Xcode v14.3.1? I've tried the Applications folder, downloads, etc. Tried restarting (both full pc restart and Xcode restart) and it doesn't appear within the dropdown of the "Command Line Tools" field.

![Screenshot 2023-10-10 at 9 08 08 AM](https://github.com/facebook/react-native/assets/17038330/76100426-393e-4004-9971-de6ea50b6a05)

Thanks!

**Comment by erickbennett** [comment]
Unzip Xcode in applications. But you also need to download the command line tools for 14.3.1, which you can get from the Apple Developer site where you get Xcode 14.3.1. Once you download the 14.3.1 cl tools and install them, they will appear as an option in the drop down.

**Comment by ahinkle** [comment]
Ah, gotcha. Thanks! I think my issue is that I'm on MacOS Sonoma. Also can't install cl tools v14. Anyone find a workaround?

![Screenshot 2023-10-10 at 9 28 47 AM](https://github.com/facebook/react-native/assets/17038330/1916f9b5-1938-4173-8fb8-7ad787abde47)

**Comment by cipolleschi** [comment]
Hi there! 
Please:
1. make sure that you are calling the `react_native_post_install` hook in your Podfile's `post_install_hook`. [Like this](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/template/ios/Podfile#L53-L61)
2. Please invoke the `__apply_Xcode_12_5_M1_post_install_workaround` as shown above.
3. update to React Native 0.72.6.

We released a new version of React Native this week that should address all these problems:
- unary_function: addressed by [these lines](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/scripts/cocoapods/utils.rb#L135-L136)
- clockid_t: addressed by [these lines](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/scripts/react_native_pods.rb#L366-L387)

**Comment by MP-OT** [comment]
@techamit95ch Based on https://github.com/facebook/react-native/issues/37748 I've created this def in my podfile:

```def __xcode_15_workaround(installer)
  xcode_version_output = `xcodebuild -version`
  xcode_version_match = xcode_version_output.match(/Xcode (\d+(\.\d+)?)/)

  if xcode_version_match
    xcode_version = Gem::Version.new(xcode_version_match[1])
    if xcode_version >= Gem::Version.new('15.0')
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        end
      end
    end
  end
end
```

You can use it in the post_install script like this:

**Comment by talhauzair-28** [comment]
I have faced the same issue after upgrading XCode and Expo to Following 
Expo: `^50.0.7`
React-Native: `0.73.4`
Xcode: `15.2`

Problem: I was using `jsc` engine instead of `Hermes`. 
Solution: Converting the JS Engine to `Hermes` in podfile resolved this problem.

**Comment by FBRAA** [comment]
> Hi there! Please:
> 
> 1. make sure that you are calling the `react_native_post_install` hook in your Podfile's `post_install_hook`. [Like this](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/template/ios/Podfile#L53-L61)
> 2. Please invoke the `__apply_Xcode_12_5_M1_post_install_workaround` as shown above.
> 3. update to React Native 0.72.6.
> 
> We released a new version of React Native this week that should address all these problems:
> 
> * unary_function: addressed by [these lines](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/scripts/cocoapods/utils.rb#L135-L136)
> * clockid_t: addressed by [these lines](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/scripts/react_native_pods.rb#L366-L387)

still getting the same issue with all beforementioned invocations on latest x-code with RN 0.72.6

**Comment by sleekLancelot** [comment]
What did it for me was to build with xcode, and after that i got an error concerning react codegen, i updated the development target for that on xcode, and subsequent builds from the terminal were successful.

**Comment by tanjilMDS** [comment]
After 2 days of research and trying different approaches I ended up with a solution:
**What I did:**
- deleted build,Pods,podfile.lock and reinstalled pods
- deleted node modules and reinstalled
- deleted projects and started with new one
- uninstalled Xcode several times and reinstalled(Xcode 15.3)
- updated RN to latest version
- updated libraries

but nothing worked

**The solution that worked for me:**
- After downgrading Xcode from 15.3 to 15.2 first it was not building from vscode but when I tried from xcode it successfully built and now I can build it from vscode as well

**Comment by chaitanya71998** [comment]
I was working to setup Xcode cloud, since ios is stating to use xcode 15 or later to build ios apps.
my react native version : "0.71.7".
i tried xcode 15.4 and 15.2 but for both of them build failed.
which version of later xcode 15 would be helpful for this version of react native, or should definitely update react-native version?

@tanjilMDS any insights please

**Comment by tanjilMDS** [comment]
@chaitanya71998 I think you can try downgrading XCode to 15.1 as well. But 15.2 should do the work. Try in a new project as well to check if it builds successfully or not from xcode

**Comment by AteebNoOne** [comment]
Xcode 14 doesn't allow to submit the app to app store, similarly Xcode 15 is throwing RCT error, I think it's regarding this libraries

**Comment by cipolleschi** [comment]
Xcode 15.3 is bugged. They reimplemented the linker and it does not support weak symbols. The error presents itself when building an app using Dynamic Frameworks.

Apple must fix the issue, there is very little we can do here.
Please downgrade to Xcode 15.2. That should do the trick.

**Comment by AteebNoOne** [comment]
I am using Xcode 15.2 still facing RCTPolly issue

**Comment by qsales2022** [comment]
> Xcode 15.3 is bugged. They reimplemented the linker and it does not support weak symbols. The error presents itself when building an app using Dynamic Frameworks.
> 
> Apple must fix the issue, there is very little we can do here. Please downgrade to Xcode 15.2. That should do the trick.



> Xcode 15.3 is bugged. They reimplemented the linker and it does not support weak symbols. The error presents itself when building an app using Dynamic Frameworks.
> 
> Apple must fix the issue, there is very little we can do here. Please downgrade to Xcode 15.2. That should do the trick.

I am also having same issue i using x code 15.2 and react native 0.71.8

**Comment by cipolleschi** [comment]
Can you create a reproducer using [this template](https://github.com/react-native-community/reproducer-react-native)

**Comment by dhruv-bindra** [comment]
Anyone find a solution? Same problem here

**Comment by chaitanya71998** [comment]
check this solution, after following steps in this [issue](https://github.com/facebook/react-native/issues/37748) solved this error.
specifically following these two steps
[step1:](https://github.com/facebook/react-native/issues/37748#issuecomment-1580334650)
[step2](https://github.com/facebook/react-native/issues/37748#issuecomment-1580589448)

**Comment by AnshulRaghav** [comment]
For me, this issue occurred when I updated Xcode from version 14 to 15. After days of debugging, I discovered that the problem was due to Expo. First, I removed all packages and references related to Expo from the iOS folder. After doing this, the project was built successfully.

Then, I progressively added the updated Expo and its related packages back into the project.

- Expo SDK 48
- Xcode 15.1
- M1
- macOS Sonoma 14.4.1

**Comment by Aniket239** [comment]
Multiple commands produce '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/React-Core_privacy.bundle'

Target 'React-Core-60309c9c-React-Core_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/React-Core_privacy.bundle' Target 'React-Core-React-Core_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/React-Core_privacy.bundle'

Multiple commands produce '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCT-Folly_privacy.bundle'

Target 'RCT-Folly-RCT-Folly_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCT-Folly_privacy.bundle' Target 'RCT-Folly.default-Fabric-RCT-Folly_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCT-Folly_privacy.bundle'

I am using react native 0.77.0 and xcode 16.2. The build succeeded but while archiving I am getting this.

**Comment by cipolleschi** [comment]
@Aniket239 The problem is that you have multiple target that are doing the same thing:
- `React-Core-60309c9c-React-Core_privacy` and `React-Core-React-Core_privacy`
-  `RCT-Folly-RCT-Folly_privacy` and `RCT-Folly.default-Fabric-RCT-Folly_privacy`

I suggest to do a `bundle exec pod deintegrate` and reintall pods.

Are you developing also for other Apple platforms other than iOS?

**Comment by Aniket239** [comment]
Even after bundle exec pod deintegrate and reintall pods i am getting the same error. I am developing the app for both Apple and Android.

**Comment by cipolleschi** [comment]
But Apple is only iOS or also macOS and other Apple platforms?
I don't know why the project is loading multiple copies of the the same pods.. There should be something in your specific configuration.

Can you try to remove ios/Pods, ios/Podfile.lock and the xcworkspace file and then rerun pod install?

**Comment by Aniket239** [comment]
@cipolleschi I am developing for ios only. I have tried deleting those duplicate files as well but after building for around 98% the build fails while stating that the files that i have deleted is missing. What do I do in this situation? I am in a loop.

**Comment by Aniket239** [comment]
> But Apple is only iOS or also macOS and other Apple platforms? I don't know why the project is loading multiple copies of the the same pods.. There should be something in your specific configuration.
> 
> Can you try to remove ios/Pods, ios/Podfile.lock and the xcworkspace file and then rerun pod install?

I have tried deleting these files but still getting the same error

**Comment by cipolleschi** [comment]
- which version of Xcode are you using?
- which version of React Native?
- can you paste your Podfile?
- can you ry by creating a new app from the template: `npx @react-native-community/cli init NewApp`

**Comment by Aniket239** [comment]
> * which version of Xcode are you using?
> * which version of React Native?
> * can you paste your Podfile?
> * can you ry by creating a new app from the template: `npx @react-native-community/cli init NewApp --version latest`

I am using these versions:-

System:
  OS: macOS 15.3.1
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 11.0.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
      - 35.0.1
    System Images:
      - android-30 | Google Play ARM 64 v8a
      - android-35 | Intel x86_64 Atom
      - android-35 | Google APIs Intel x86_64 Atom
      - android-35 | Google Play ARM 64 v8a
      - android-35 | Pre-Release 16 KB Page Size Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23726.103.2422.12816248
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.4.1
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.77.0
    wanted: 0.77.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by cipolleschi** [comment]
please change the podfile like this:

```diff
# Resolve react_native_pods.rb with node to allow for hoisting
# use_modular_headers!
- rn_maps_path = '../node_modules/react-native-maps'
- pod 'react-native-google-maps', :path => rn_maps_path
- pod 'FirebaseCore', :modular_headers => true
- pod 'Firebase', :modular_headers => true
- pod 'FirebaseCoreInternal', :modular_headers => true
- pod 'GoogleUtilities', :modular_headers => true
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

- setup_permissions([
-  # 'AppTrackingTransparency',
-  # 'Bluetooth',
-  # 'Calendars',
-  # 'CalendarsWriteOnly',
-  'Camera',
-  # 'Contacts',
-  # 'FaceID',
-  'LocationAccuracy',
-  'LocationAlways',
-  'LocationWhenInUse',
-  # 'MediaLibrary',
-  # 'Microphone',
-  # 'Motion',
-  'Notifications',
-  'PhotoLibrary',
-  # 'PhotoLibraryAddOnly',
-  # 'Reminders',
-  # 'Siri',
-  # 'SpeechRecognition',
-  # 'StoreKit',
-])
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Pinkpaws' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

+ rn_maps_path = '../node_modules/react-native-maps'
+ pod 'react-native-google-maps', :path => rn_maps_path
+ pod 'FirebaseCore', :modular_headers => true
+ pod 'Firebase', :modular_headers => true
+ pod 'FirebaseCoreInternal', :modular_headers => true
+ pod 'GoogleUtilities', :modular_headers => true

+ setup_permissions([
+  # 'AppTrackingTransparency',
+  # 'Bluetooth',
+  # 'Calendars',
+  # 'CalendarsWriteOnly',
+  'Camera',
+  # 'Contacts',
+  # 'FaceID',
+  'LocationAccuracy',
+  'LocationAlways',
+  'LocationWhenInUse',
+  # 'MediaLibrary',
+  # 'Microphone',
+  # 'Motion',
+  'Notifications',
+  'PhotoLibrary',
+  # 'PhotoLibraryAddOnly',
+  # 'Reminders',
+  # 'Siri',
+  # 'SpeechRecognition',
+  # 'StoreKit',
+])

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

```

The `use_react_native!` sets some flags that are used by other pods and if you install the pods before calling the `use_react_native!` function, those pods won't be able to see them.

---

Does a new app created from the template build and run fine?

**Comment by leecuong666** [comment]
> Multiple commands produce '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/React-Core_privacy.bundle'
> 
> Target 'React-Core-60309c9c-React-Core_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/React-Core_privacy.bundle' Target 'React-Core-React-Core_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/React-Core_privacy.bundle'
> 
> Multiple commands produce '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCT-Folly_privacy.bundle'
> 
> Target 'RCT-Folly-RCT-Folly_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCT-Folly_privacy.bundle' Target 'RCT-Folly.default-Fabric-RCT-Folly_privacy' (project 'Pods') has create directory command with output '/Users/pradipta/Library/Developer/Xcode/DerivedData/Pinkpaws-fqxvzkonyxofupcsmbloesfvzllq/Build/Intermediates.noindex/ArchiveIntermediates/Pinkpaws/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCT-Folly_privacy.bundle'
> 
> I am using react native 0.77.0 and xcode 16.2. The build succeeded but while archiving I am getting this.

i'm getting same issue. do you have a solution to this problem?

**Comment by cipolleschi** [comment]
@leecuong666  your setup is somehow broken, as it seems that you have multiple versions of React Native installed in your app. it seems that you have a target called `React-Core` and a target called `'React-Core-60309c9c`.

You need to explain better your setup.
Are you using Expo or a RN app using the CLI?
Are you using also React Native MacOS?
Can you share your podfile?
