### ISSUE TITLE
Pod install error verification checksum was incorrect at boost (1.83.0)

### ISSUE THREAD

**Issue by truongngodang** [facebook/react-native#42109]
### Description

[!] Error installing boost
Verification checksum was incorrect, expected 6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

### Steps to reproduce

1. cd ios & pod install

### React Native Version

0.73.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 73.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
[!] Error installing boost
Verification checksum was incorrect, expected 6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
```

### Reproducer

none

**Comment by dantonio1401** [comment]
Having the same issue

**Comment by deeeed** [comment]
+1

**Comment by InquestApp-Admin** [comment]
same issue. started tonight

**Comment by deeeed** [comment]
The issue seems to be on jfrog.io, the download links are dead https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

It seems to be the only mirror according to:
https://www.boost.org/users/history/version_1_76_0.html

**Comment by Artem-Kalugin** [comment]
> The issue seems to be on jfrog.io, the download links are dead https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
> 
> It seems to be the only mirror according to: https://www.boost.org/users/history/version_1_76_0.html

And even there links dont work, rederecting to dead site

**Comment by kdn0325** [comment]
We found a temporary solution until the issue is resolved

move to 

`node_modules/react-native/third-party-podspecs`

```
spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
:sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
```
change to

```
spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2',
:sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
```

**Comment by kimyoungjae96** [comment]
I solved it with [this](https://github.com/boostorg/boost/issues/843#issuecomment-1872943124).

**Comment by netanelz-amdocs** [comment]
@react-native-bot  / @cortinico  do you plan to fix it so we would not need to patch it? Any ETA?

> I solved it with [this](https://github.com/boostorg/boost/issues/843#issuecomment-1872943124).

**Comment by Jonathanide1** [comment]
Same issue.

**Comment by Yeasirarafat53** [comment]
same issue

**Comment by ronCohen2** [comment]
same issue

**Comment by kdn0325** [comment]
> We found a temporary solution until the issue is resolved
> 
> move to
> 
> `node_modules/react-native/third-party-podspecs/boost.podspec`
> 
> ```
> spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
> :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
> ```
> 
> change to
> 
> ```
> spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2',
> :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
> ```

I temporarily fixed the bug, but when will this be resolved? 

> We found a temporary solution until the issue is resolved
> 
> move to
> 
> `node_modules/react-native/third-party-podspecs/boost.podspec`
> 
> ```
> spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
> :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
> ```
> 
> change to
> 
> ```
> spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2',
> :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
> ```

I temporarily fixed the bug, but when will this be resolved?

**Comment by barghi** [comment]
same here

**Comment by tyler-canton** [comment]
Same

**Comment by PerrettJ4** [comment]
same

**Comment by harry-anderson** [comment]
same

**Comment by masonle2x2** [comment]
same

**Comment by abdymm** [comment]
same

**Comment by ashherr** [comment]
same

**Comment by Daha62** [comment]
https://github.com/boostorg/boost/issues/843 - helped me, just change url from boostorg to sourceforge (checksum is the same)

**Comment by mittalkamal29** [comment]
Same issue

**Comment by SupriyaGo** [comment]
Not working

**Comment by Archish27** [comment]
Damn this is breaking, seems like `https://boostorg.jfrog.io/artifactory` not working. Please fix.

**Comment by ehtisham-ali-emumba** [comment]
https://github.com/facebook/react-native/issues/42109#issuecomment-1872922926

i followed but too slow.

**Comment by edenmoyal1** [comment]
still not working for me

**Comment by cipolleschi** [comment]
This is fixed now. Boost changed something that invalidated the checksum, but it is resolved now.
Our CI is green: https://app.circleci.com/pipelines/github/facebook/react-native/39145/workflows/faa1c7e2-37d6-440b-8b93-abe665bd2087

**Comment by abdullahwt** [comment]
I have solved this issue by following these steps

[](https://stackoverflow.com/questions/77738691/error-installing-boost-verification-checksum-was-incorrect-expected/77745446#77745446)

**Comment by ohlyf** [comment]
> We found a temporary solution until the issue is resolved
> 
> move to
> 
> `node_modules/react-native/third-party-podspecs/boost.podspec`
> 
> ```
> spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
> :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
> ```
> 
> change to
> 
> ```
> spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2',
> :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
> ```

resolved  thanks

**Comment by fuomag9** [comment]
> This is fixed now. Boost changed something that invalidated the checksum, but it is resolved now. Our CI is green: https://app.circleci.com/pipelines/github/facebook/react-native/39145/workflows/faa1c7e2-37d6-440b-8b93-abe665bd2087

not fixed

```
[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
```

**Comment by nickzy9** [comment]
[!] Error installing boost
Verification checksum was incorrect, expected 6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
aniket@Anikets-MacBook-Pro ios %

**Comment by InquestApp-Admin** [comment]
this issue has returned as of last night

[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

**Comment by choi2021** [comment]
Still happening at RN 0.71.13.

There's temporary solution from https://github.com/facebook/react-native/issues/42110#issuecomment-1872943368


`node_modules/react-native/third-party-podspecs/boost.podspec`
```
spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
:sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
change to
```
```
spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2',
:sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }
```

I have found PR which was made from RN developer and RN Team in Boost Repo. https://github.com/boostorg/boost/issues/843
https://github.com/boostorg/boost/issues/845

Until they solve this prob, we might need to use this temporary solution...

**Comment by InquestApp-Admin** [comment]
> This is fixed now. Boost changed something that invalidated the checksum, but it is resolved now. Our CI is green: https://app.circleci.com/pipelines/github/facebook/react-native/39145/workflows/faa1c7e2-37d6-440b-8b93-abe665bd2087

this is broken again.

**Comment by OGD42** [comment]
Stuff like this reminds me why I move to Expo

**Comment by vladimirevstratov** [comment]
stuck with this during integrating appcenter in existing project

**Comment by imransilvake** [comment]
broken again

**Comment by shav95** [comment]
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.76.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  spec.source = { :http => 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }

  # Pinning to the same version as React.podspec.
  spec.platforms = { :ios => '11.0' }
  spec.requires_arc = false

  spec.module_name = 'boost'
  spec.header_dir = 'boost'
  spec.preserve_path = 'boost'
end

This helped me -->  'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2',

**Comment by abdelhamid-f-nasser** [comment]
Is this fix temporary or is it safe to release with it included ?

**Comment by shav95** [comment]
@abdelhamid-f-nasser I think this is a temporary solution. We should not do that after every yarn/npm install, it downloads from an archive I think it is safe

**Comment by vladimirevstratov** [comment]
> # Copyright (c) Meta Platforms, Inc. and affiliates.
> # This source code is licensed under the MIT license found in the
> # LICENSE file in the root directory of this source tree.
> Pod::Spec.new do |spec| spec.name = 'boost' spec.version = '1.76.0' spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" } spec.homepage = 'http://www.boost.org' spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.' spec.authors = 'Rene Rivera' spec.source = { :http => 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2', :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }
> 
> # Pinning to the same version as React.podspec.
> spec.platforms = { :ios => '11.0' } spec.requires_arc = false
> 
> spec.module_name = 'boost' spec.header_dir = 'boost' spec.preserve_path = 'boost' end
> 
> This helped me --> 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2',

archives.boost.io as url for boost help me also

**Comment by hamdij0maa** [comment]
+1 🤣

**Comment by codebycarlos** [comment]
It looks like it's happening again to quite a few people. Could we please re-open this?

**Comment by codebycarlos** [comment]
For anyone struggling, this is what worked for me in the meantime. You can grab a copy elsewhere (e.g. [SourceForge](https://sourceforge.net/projects/boost/files/boost/)) and replace it with the one in your `/node_modules`. 

This may come with security implications and you'll have to do it each time you run an `npm install`.

**Comment by rangga-synergy** [comment]
i have this issue now. @_@

**Comment by kidpollo** [comment]
same

**Comment by rfahernandez** [comment]
Same here...

**Comment by garrett-vorce-mohara** [comment]
Experiencing this issue on React Native & App Center CI/CD

**Comment by c-zhenhao** [comment]
same

**Comment by ngocpd-1250** [comment]
same here....

**Comment by thtRajasthaniGuy** [comment]
same here..... using react-native version 0.70.6

**Comment by doanhtrinh95** [comment]
same here....., Please help...!

**Comment by r-guerin0** [comment]
Also having the issue (running `react-native@0.72.4`)

**Comment by prateekuttreja2020** [comment]
- Facing the same issue

Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

**Comment by LouisJS** [comment]
Same issue as @prateekuttreja2020 . Running on React Native 0.70. Boost 1.76.0

**Comment by dimitris4** [comment]
same issue, react native v. 0.72.6

**Comment by prashantkamboj** [comment]
Same issue with me but why this issue is closed ?

**Comment by lluis-sancho** [comment]
Same error here. (0.71.6)

**Comment by cipolleschi** [comment]
Hi everyone. We are extremely sorry for the disruption. As I mention already, we don't own the service where Boost is hosted, so this is not a part of our infra where we can intervene directly.

We are working on a solution to avoid this problem in the future, so bear with us for now.
From your reports, I can see that the version affected are:
* 0.70
* 0.71
* 0.72
* 0.73

Please bear in mind that 0.70 is not supported anymore. We might consider to make a new release for the sake of this change, but that's still up for discussion.

Please, stop adding comment like "+1" or "I'm affected too", because this just adds noise to the issue and doesn't make us work faster.

@prashantkamboj the issue is closed because the exact same incident happened around New Year's Eve and then the infra recovered the 1st of January, so we closed the issue.
Now, a week after, it is presenting again.

## Workaround

To unblock yourself, you can apply the changes highlighted by this PR: https://github.com/facebook/react-native/pull/42118/files

For 0.72 and 0.73, these changes should be straight forward, as they are already in the monorepo setup, so the files path matches with the one of the PR.

For 0.70 and 0.71, we are not in the monorepo. To get the right path, remove the `package/react-native` from the two files paths.
So, the paths are:
* For the `build.gradle.kts`: `<your_project>/node_modules/react-native/ReactAndroid/build.gradle.kts`
* For the `boost.podspec`: `<your_project>/node_modules/react-native/third-party-podspecs/boost.podspec`

**Comment by Johan-dutoit** [comment]
Here is a PR with the fix https://github.com/facebook/react-native/pull/42118, the RN team are on it already.

**Comment by binarybaba** [comment]
for those on RN@0.72 with boost@1.76
```
spec.source = { :http => 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.gz',
                  :sha256 => '7bd7ddceec1a1dfdcbdb3e609b60d01739c38390a5f956385a12f3122049f0ca' }
```

**Comment by sindhusingh** [comment]
> for those with boost@1.76
> 
> ```
> spec.source = { :http => 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.gz',
>                   :sha256 => '7bd7ddceec1a1dfdcbdb3e609b60d01739c38390a5f956385a12f3122049f0ca' }
> ```
> 
> Quick way to find out: download the file and run `sha256sum <filename>`

Excellent! The temporary solution, as mentioned by others earlier, is effective. However, the issue is that we need to apply this solution every time we install fresh packages. Even creating a patch for these changes doesn't work seamlessly. I'm still in search of a permanent fix.

**Comment by D-Cabs** [comment]
Hi! 
React V. 0.70.5 question. Im a bit unsure what to do as remove "package/react-native" from the path. 

.../node_modules/react-native/ReactAndroid/build.gradle  has 

`task downloadBoost(dependsOn: createNativeDepsDirectories, type: Download) {
    src("https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz")
    onlyIfNewer(true)
    overwrite(false)
    dest(new File(downloadsDir, "boost_${BOOST_VERSION}.tar.gz"))
}`

And  .../node_modules/react-native/third-party-podspecs

`Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.76.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }`
                  
                  
                  
 I am unsure what to change like @cipolleschi mentioned. 
 
 Could somebody point me on what to change as issue is critical for me at the moment.

**Comment by matteodanelli** [comment]
> Hi! React V. 0.70.5 question. Im a bit unsure what to do as remove "package/react-native" from the path.
> 
> .../node_modules/react-native/ReactAndroid/build.gradle has
> 
> `task downloadBoost(dependsOn: createNativeDepsDirectories, type: Download) { src("https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz") onlyIfNewer(true) overwrite(false) dest(new File(downloadsDir, "boost_${BOOST_VERSION}.tar.gz")) }`
> 
> And .../node_modules/react-native/third-party-podspecs
> 
> `Pod::Spec.new do |spec| spec.name = 'boost' spec.version = '1.76.0' spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" } spec.homepage = 'http://www.boost.org' spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.' spec.authors = 'Rene Rivera' spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2', :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }`
> 
> I am unsure what to change like @cipolleschi mentioned.
> 
> Could somebody point me on what to change as issue is critical for me at the moment.

You could check [this](https://github.com/facebook/react-native/pull/42178/files). Maybe it helps

**Comment by abdymm** [comment]
> ld somebody point me on what to change as issue is critical for me at the moment.

you need to do the patch package by changing the source url

**Comment by cipolleschi** [comment]
We have an official workaround and a pinned issue: https://github.com/facebook/react-native/issues/42180.
I'm locking this conversation.
