### ISSUE TITLE
Memory leak in 0.15.

### ISSUE THREAD

**Issue by npapanastasiou** [facebook/react-native#4538]
Running a minimal app created with `react-native init` results in a small a memory leak (just under 1MB/minute) with the app simply idling. The leak grows more substantial with additional components added.

EDIT: I should note that this leak occurred when bundled with --dev=false.

**Comment by mkonicek** [comment]
Hey @npapanastasiou, is this on iOS or Android? How did you measure the memory usage? Can you provide some data / charts?

**Comment by npapanastasiou** [comment]
@mkonicek It was on iOS, measured using Leaks in XCode. I'll try to dig up some charts when I have a minute.

**Comment by ide** [comment]
This should be fixed in master.

**Comment by sdiaz** [comment]
Im running in a similar issue for iOS, but in dev=true. With react-native 0.16.0
Boilerplate ios.index.js

![memory_dev](https://cloud.githubusercontent.com/assets/582158/11614023/5911a500-9c35-11e5-8f60-c098f67b3f2e.png)
![memory_prod](https://cloud.githubusercontent.com/assets/582158/11614024/591c0d74-9c35-11e5-8366-3734df3730ea.png)

**Comment by imton** [comment]
stills in .16

**Comment by rclai** [comment]
I can confirm that this is still happening on 0.16.0 on iOS in the simulator.

**Comment by imton** [comment]
I reach GBs easily.  :(

**Comment by boldkhuu** [comment]
Same problem here.

**Comment by mkonicek** [comment]
Thanks for reporting it. Asked the iOS guys on the RN team.

**Comment by mkonicek** [comment]
Tadeu Zagallo tells me the fix for this will ship in 0.17: https://github.com/facebook/react-native/issues/3953. Closint this so we don't forget to close it (don't have an easy way to automatically close all issues related to a release at once).

**Comment by mkonicek** [comment]
Here's the commit: https://github.com/facebook/react-native/commit/ea96a7edb8a17fbcc57db99217783302bb790056

**Comment by ajwhite** [comment]
I've noticed some similar memory behavior, although not as drastic, over in https://github.com/facebook/react-native/issues/4761. Not sure if it's directly related or not.

Basically, running `react-native init`, and then throwing a `setInterval` when the component mounts that does something to the state every second or so, especially if that interval involves `fetch`, will have a gradual rise in the memory footprint. This has been seen in `0.15` and `0.17.0-rc` with `dev=false`

**Comment by DickyT** [comment]
still in 0.17rc

**Comment by DickyT** [comment]
@ajwhite same as u, I use lots of fetch in my app

**Comment by ajwhite** [comment]
@DickyT when I run it in release mode I no longer have an issue. I _think_ it's only a problem in debug mode.
