### ISSUE TITLE
iOS RN:0.14.2 Border Radius - Blur

### ISSUE THREAD

**Issue by export-mike** [facebook/react-native#4604]
Hi, I've found the borders to blur on iOS when setting border radius on less than four corners... 

https://rnplay.org/apps/mGNsBQ 
![image](https://cloud.githubusercontent.com/assets/2983327/11426191/1c842666-9452-11e5-806b-8e5d18581216.png)

RN version:0.14.2

I originally had commented on this issue: https://github.com/facebook/react-native/issues/3040#issuecomment-159937977 but realised the issue is related to Android.

**Comment by rjoonas** [comment]
More examples at https://github.com/facebook/react-native/issues/2089

**Comment by weicool** [comment]
I'm also seeing this:

![pill_border_radius](https://cloud.githubusercontent.com/assets/169728/12104632/36c3fafa-b302-11e5-99b8-3a57960aa8bb.png)

**Comment by brentvatne** [comment]
Fixed in https://github.com/facebook/react-native/commit/b115277d00f54fa7af5d61062c9e3cf362b7c5da

**Comment by worldlyjohn** [comment]
what version of RN did this make it into?  i'm still affected by this issue running:
- "react": "15.3.1",
- "react-native": "0.33.0",

**Comment by lerman** [comment]
I'm also seeing this issue still

**Comment by rneiss** [comment]
Still seeing on 0.35.0:
![untitled](https://cloud.githubusercontent.com/assets/1596539/19779868/88194826-9c48-11e6-98bf-6e940ae3a24e.png)

**Comment by selvabics** [comment]
add this style, overflow: 'hidden'
