### ISSUE TITLE
Screen jumps when secureTextEntry is set and the keyboard suggests passwords before focusing on the input with secureTextEntry prop

### ISSUE THREAD

**Issue by avega99** [facebook/react-native#47106]
### Description

The screen jumps when one of the inputs has the secureTextEntry prop because the keyboard suggests passwords even when typing in a different input that doesn’t have secureTextEntry prop. This happens when focusing on an input placed before the one with secureTextEntry, and as you type, the password suggestion appears and disappears, causing the screen to jump.

https://github.com/user-attachments/assets/14403cee-3d9c-4951-855e-7591f18c4fb8

### Steps to reproduce

As you can see in the code, username input doesn't have sceureTextEntry prop set and still suggests passwords above the keyboard, this suggestion appears and disappears as you type causing the app to jump, this only happens when focusing the input just before the one that has the secureTextProp set to true.

`export default function HomeScreen() {
  const passRef = useRef<TextInput>(null)
  const usernameRef = useRef<TextInput>(null)

  return (
    <SafeAreaView style={styles.container}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.container}
      >
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <View style={styles.inner}>
            <Text style={styles.header}>Header</Text>
            <TextInput
              placeholder='Email'
              keyboardType='email-address'
              returnKeyType='next'
              blurOnSubmit={false}
              onSubmitEditing={() => usernameRef.current?.focus()}
              style={styles.textInput}
            />
            <TextInput
              ref={usernameRef}
              placeholder='Username'
              returnKeyType='next'
              blurOnSubmit={false}
              onSubmitEditing={() => passRef.current?.focus()}
              style={styles.textInput}
            />
            <TextInput
              ref={passRef}
              placeholder='Password'
              secureTextEntry
              style={styles.textInput}
            />
            <View style={styles.btnContainer}>
              <Button title='Submit' onPress={() => null} />
            </View>
          </View>
        </TouchableWithoutFeedback>
      </KeyboardAvoidingView>
    </SafeAreaView>
  )
}`

### React Native Version

0.74.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 819.86 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.10.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
alejandrovega@Mac-mini-de-Alejandro inputtest % npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 521.91 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.10.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /opt/homebrew/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No stacktrace error or logs
```

### Reproducer

https://github.com/avega99/SecureTextEntryJump

### Screenshots and Videos

https://github.com/user-attachments/assets/9eb7f18f-7247-4140-9905-a9d1940b48d5

![secureTextEntryCode](https://github.com/user-attachments/assets/f5487e2a-ccf4-41ca-90fc-5b4b4273f688)

**Comment by sept-jm** [comment]
This is still an issue in 0.76.3.

Here is an updated repro: [Snack](https://snack.expo.dev/@justinmundt/moody-orange-juice-box)

https://github.com/user-attachments/assets/96a40988-9c2f-46a9-b24c-a03e1ba503f7

The problem can be caused by multiple things, including `textContentType={'username'}` on the former `TextInput`, `secureTextEntry={true}` on the letter `TextInput`, and presumably any other condition that pops the Passwords button in iOS.

**Comment by CamiloVict** [comment]
I fixed the issue with this attribute:  keyboardType={'email-address'}

**Comment by sept-jm** [comment]
> I fixed the issue with this attribute: keyboardType={'email-address'}

@CamiloVict Presuming you are adding this attribute to the first `TextInput`, I tried this in the above snack ([here](https://snack.expo.dev/@justinmundt/moody-orange-juice-box)) to no avail. It also did not work on the second `TextInput`. Can you provide a reproduction?

**Comment by eltacogrande** [comment]
This has never been fixed, has it?

**Comment by LarsDanau** [comment]
I am still experiencing this issue. Any update, anything planned?

**Comment by larafmina2-beep** [comment]
I am also still encountering this issue. Is there an update on a potential
fix or anything currently planned to address this?
