### ISSUE TITLE
[Bug]: maxFontSizeMultiplier is not being respected

### ISSUE THREAD

**Issue by mysport12** [facebook/react-native#47499]
### Description

The maxFontSizeMultiplier prop is not being respected for Text and TextInput components. When accessibility settings are changed to increase the display text, the font size increases beyond the multiplier set.

### Steps to reproduce

- Init a new project from the CLI template
- Add a few Text/TextInput components to the screen
- Prevent some from scaling and allow others to scale with the maxFontSizeMultiplier prop passed
- Change OS accessibility settings from display text size and observe bug

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.0.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 107.84 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 4.5.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/craig/.rvm/gems/ruby-3.3.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 35.0.0
    System Images:
      - android-28 | Google Play Intel x86 Atom
      - android-29 | Google APIs Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google APIs Intel x86_64 Atom
      - android-30 | Google Play Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom_64
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /Users/craig/.rvm/rubies/ruby-3.3.5/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
No logs
```

### Reproducer

https://github.com/mysport12/maxFontSizeMultiplierBug

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/3b4cbb7f-5b7d-4e31-b6a2-7fa705394b8e)
![image](https://github.com/user-attachments/assets/f7c5472a-72d9-43a6-9cf9-d0cbc91e1a49)

**Comment by migueldaipre** [comment]
You need to pass allowFontScaling=true if I'm not mistaken

**Comment by cortinico** [comment]
> The maxFontSizeMultiplier prop is not being respected for Text and TextInput components. When accessibility settings are changed to increase the display text, the font size increases beyond the multiplier set.

Is this working well if you turn off the New Architecture? Asking to understand if this is a Fabric regression or not

**Comment by mysport12** [comment]
@cortinico It is working properly on the legacy architecture in 0.75.4.

**Comment by cortinico** [comment]
> @cortinico It is working properly on the legacy architecture in 0.75.4.

And how about legacy arch on 0.76?

**Comment by mysport12** [comment]
Yes, I can confirm it is working on 0.76.1 with the legacy arch.

**Comment by hungnd-casso** [comment]
> I've added support ([RickardZrinski@140d9eb](https://github.com/RickardZrinski/react-native/commit/140d9eb985cb161f3550d277e16a6b00d96235f2)) and hoping to open a pull request tomorrow. Just need to do some more manual testing / compare with the old architecture and do some screenshots for the PR.
> 
> Edit: still working on it :)

![image](https://github.com/user-attachments/assets/db631253-a979-4661-9c19-3b8e074da97a)

**Comment by RickardZrinski** [comment]
Everything is working on Android and iOS, except that there is some weirdness happening on the new architecture with reapplying changes made in Settings when switching back to the app (e.g. you've changed font size in accessibility settings but you need to restart the app for it to apply).

I don't think this issue is specific to my PR but rather a general issue in the new architecture. Though I'll need to verify that to be sure.

**Comment by mysport12** [comment]
I see the PR addressing this issue is approved and ready to merge... Is this waiting on the Android line height or iOS settings reapplication work before it can land? Appreciate all the help getting this fixed!

**Comment by RickardZrinski** [comment]
I would assume the React Native team are just busy and/or it needs to go through some internal testing at Meta. 
@cipolleschi Anything 

The settings issue isn't a blocker. I can't find the specific GitHub issue now but it's been confirmed as an issue with the new architecture. It's been documented by [others](https://github.com/facebook/react-native/issues/45661) as well.

**Comment by mysport12** [comment]
No worries! Completely understand how busy everyone is with the holiday season, new arch rollout, etc. Just hoping to keep this on the radar for a 0.76.X/0.77.X pick.

**Comment by amol-ghotankar** [comment]
Waiting anxiously to get this fixed 🕐

**Comment by jakecurreri** [comment]
+1 This a big hit to accessibility for our app. It is nixing all of our `maxFontSizeMultiplier` adjustments.

**Comment by RickardZrinski** [comment]
> Yeah, sorry if it's taking a little bit longer but a couple of colleagues suggested a couple of changes internally and I haven't had the time to forward the suggestion to the PR (being off for a week did not help... 😅 ).

No problem! Time off is time off.

I've updated the PR based on the feedback. Hope all is good now.

**Comment by customputing** [comment]
So looks like the fix was moved to this PR https://github.com/facebook/react-native/pull/47614
Also anxiously waiting for this fix.

**Comment by cipolleschi** [comment]
I'm trying to landing the changes... 🤞

**Comment by kapilw360** [comment]
> > [@cortinico](https://github.com/cortinico) It is working properly on the legacy architecture in 0.75.4.
> 
> And how about legacy arch on 0.76?

its not working on 0.76.3. im facing same issue .

**Comment by cipolleschi** [comment]
This is solved and we are shipping the fix in various patch releases.

**Comment by kapilw360** [comment]
> This is solved and we are shipping the fix in various patch releases.

so i need to upgrade the version right ?

**Comment by cipolleschi** [comment]
yes. I believe we shipped the fix on 0.75, 0.76 and 0.78-rc. 
0.77 will arrive next week with the fix.

**Comment by customputing** [comment]
> 0.78-rc.

I updated to 0.76.7 today and still see the maxFontSizeMultiplier have not effect. Is it available yet with package managers or does it require a patch outside of using npm?

**Comment by RyanTG** [comment]
The 0.76.7 release notes say the fix is included, so I wouldn’t expect that you’d need an extra patch.

But yeah, this doesn’t seem to be fixed in 0.76.7.

**Comment by cipolleschi** [comment]
> Also I noticed an e2e test failed for iOS, looks like maestro failed maybe. Just curious if this should cause concern for early adoption?

E2E tests in 0.76 were highly experimental and not reliable. We were actively working on them at the time.

**Comment by longb1997** [comment]
still not working on 0.76.9

**Comment by MarkLee425** [comment]
still not working on 1.0.1
