### ISSUE TITLE
`KeyboardAvoidingView` animation issues since 0.76+

### ISSUE THREAD

**Issue by alexmngn** [facebook/react-native#47625]
### Description

I've updated my project from 0.75.2 to 0.76.1 this morning, and I noticed that the `KeyboardAvoidingView`, which was previously animating properly, is no longer animating. It now jumps and doesn't follow the keyboard animation.

The animation behaviour has changed and doesn't look native smooth anymore. 

### Steps to reproduce

Any new project with KeyboardAvoidingView

### React Native Version

0.76.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 157.52 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.11.0
    path: ~/.nvm/versions/node/v22.11.0/bin/node
  Yarn:
    version: 1.22.17
    path: ~/.npm-global/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v22.11.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/Alexis/.rbenv/shims/pod
```

### Stacktrace or Logs

```text
No crash
```

### Reproducer

https://github.com/alexmngn/reproducer-react-native-keyboard-avoiding

### On my project

**Before update, 0.75.2**

https://github.com/user-attachments/assets/5089cd4d-fb2f-4bde-9a9b-a7790b989c23

**After update, 0.76.1**

https://github.com/user-attachments/assets/60bc6d95-c444-4492-887b-cdb7d4e562d1

### On the reproducer repo

**Before update, 0.75.2**

https://github.com/user-attachments/assets/83df6cab-b4c4-4698-a458-291ab37f982c

**After update, 0.76.1**

https://github.com/user-attachments/assets/8fa6d39c-88af-4527-b41c-d7ae2bc8e7a2

**Comment by migueldaipre** [comment]
Hey @alexmngn, thanks for opening this issue.

Does it happen with the new architecture too?

**Comment by mhoran** [comment]
I've encountered a few issues with `KeyboardAvoidingView` since upgrading to 0.76. The first was due to a [regression](https://github.com/facebook/react-native/issues/47251) that was fixed in 0.76.1. The second is a [bug](https://github.com/software-mansion/react-native-reanimated/issues/6684) in react-native-reanimated **and New Architecture** that seems to break `onLayout`, ultimately causing `KeyboardAvoidingView` to fail to calculate the correct height. The third is an [issue](https://github.com/facebook/react-native/issues/47617) with `LayoutAnimation.configureNext()`, which may be the root cause of this particular bug.

**Comment by simonsayz13** [comment]
I've updated to RN0.76.3 and still encountering this issue

**Comment by mhoran** [comment]
The Reanimated issue has been reported here: https://github.com/software-mansion/react-native-reanimated/issues/6751. However, there may be an issue with KeyboardAvoidingView without Reaniated given the reproducer above does not have Reanimated installed.

**Comment by rileysay** [comment]
Any update on this?

**Comment by Kudo** [comment]
> The third is an https://github.com/facebook/react-native/issues/47617 with LayoutAnimation.configureNext(), which may be the root cause of this particular bug. (I've since discovered the LayoutAnimation.configureNext() issue seems to be related to react-native-reanimated.)

i can confirm the issue is not specifically reanimated. trying the repro without reanimated, the animation is still broken. #47617 is still valid to this one. the LayoutAnimation is not working on new architecture. turning back to old architecture should do the trick.

**Comment by nusret35** [comment]
Any update? I have the same issue.

**Comment by rileysay** [comment]
@nusret35 can use https://github.com/kirillzyusko/react-native-keyboard-controller

**Comment by pedr0luiz** [comment]
@rileysay Does https://github.com/kirillzyusko/react-native-keyboard-controller work for you? For me, it's completely broken after upgrading to 0.76

**Comment by rileysay** [comment]
@pedr0luiz Yes, working fine.

**Comment by ethandpowers** [comment]
I'm having the same issue.  The view snaps to the new position without any animation.  It's quite jarring and a bad experience.  I'm trying out `react-native-keyboard-controller`, but I don't need 'custom' functionality.  I just want the `KeyboardAvoidingView` to behave as it always has.

**Comment by manu-gurudath** [comment]
https://github.com/user-attachments/assets/6e37ce1f-6607-47da-82d2-d43d2caaa230

Experiencing this issue as well with react-native-keyboard-controller!

**Comment by zocario** [comment]
Hi we are having the same issue with react-native 0.79.3 and Expo 53.0.11. Is there any progression on the resolution of this regression?

**Comment by leojalfred** [comment]
I just came across the same issue in my own app with react-native 0.79.4 and expo 53.0.12. I had to disable the New Architecture to fix it. I'd really like to use the New Architecture, but I can't if it's going to lead to issues like this.

**Comment by Yashveer-Soni** [comment]
I having same issue

**Comment by JoeLau7788** [comment]
Using `KeyboardProvider` and `KeyboardAvoidingView` from [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller) solves the animating issue on my site (Expo 53.0.20, RN 0.79.4)

**Comment by oscar-v0** [comment]
Looks like [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller) is running into performance/laggy animation issues on the new architecture. There's an open issue here https://github.com/software-mansion/react-native-reanimated/issues/6854

**Comment by victoriomolina** [comment]
Same issue last rn version + last expo version

**Comment by EmirBostanci** [comment]
We're having the same issue on 0.80+ versions

tried implementing the same functionality with custom stuff, but there are lots of quirks unfortunately

**Comment by tomtargosz** [comment]
We're seeing the same thing on 0.81.5 with the new architecture enabled. Was working fine with the old architecture.

https://github.com/user-attachments/assets/7b5733d6-376d-4c71-8bdb-deec52e70ac6
