### ISSUE TITLE
[0.76] Modals different behaviour on iOS in v0.76

### ISSUE THREAD

**Issue by angelica-snowit** [facebook/react-native#47694]
## Description
Before RN v0.76, on iOS, to see a Modal in top of another Modal you had to put the modal inside the first modal.
Now this behavior has changed and it's possible to see the Modal on top of the first Modal even if it's not inside the Modal. It's difficult to explain, but I prepared a clear example.
Enabling or diasbling new architecture doesn't change.
It seems like a bugfix and not a bug, because the new behavior it's pretty better, but I think it should be reported as a breaking change. The effect is that after upgrading to RN 0.76, I started to see double modals appearing since they are repeated inside modal to works on RN < 0.76.
I don't know if this is the same on Android because on Android I don't use modals this way.

## Steps to reproduce
Open the example with v0.76 and test the Modals: open Modal 2 and then open Modal 1 with the buttons, you will correctly see Modal 1.
See the difference changing to v0.75: Modal 2 will not open when using the button from inside Modal 1. The only way it's to duplicate the <Modal ...> inside the Modal 2 body.

## React Native Version

0.76.1

## Affected Platforms

Runtime - iOS

## Output of npx react-native info

```
System:
  OS: macOS 15.0.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 172.33 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.18.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/angelicarosa/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/angelicarosa/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

## Stacktrace or Logs

It's not a crash.

## Reproducer

[angelica-snowit/rn76-modal-example](https://github.com/angelica-snowit/rn76-modal-example)

## Screenshots and Videos

No response

**Comment by WilliamWelsh** [comment]
I have the same issue. Before 0.76, it worked fine. For example

```ts
    setShowEmailModal(false);
    setShowPhoneModal(true);
```

Would work, the email modal would go away and the phone modal would show up. Now, the phone modal can only show up if I do this

```ts
    //setShowEmailModal(false);
    setShowPhoneModal(true);
```

Showing it on top of another, which isn't ideal

**Comment by KaramDevelopment** [comment]
I have a band-aid solution. It seems that, currently, only one modal can be shown at a time. When you quickly switch from modal1 to modal2, the render breaks. This appears to happen because the animation for modal1 hasn’t completed before modal2 is triggered.

To resolve this, you need to add a timeout. The duration (in milliseconds) depends on the animationType of the modal. For example, with animationType set to "none," 10ms works, but if you use the "slide" animation, 500ms is needed.

This solution isn't optimal because I’m not sure if the animation speed is consistent across different devices or how the timing might be affected. Unfortunately, there doesn’t seem to be a reliable way to wait for the animation to complete. Hoping a permanent solution is implemented soon!

  setModal1(false);
  setTimeout(() => setModal2(true), 10);

**Comment by angelica-snowit** [comment]
> I have a band-aid solution. It seems that, currently, only one modal can be shown at a time. When you quickly switch from modal1 to modal2, the render breaks. This appears to happen because the animation for modal1 hasn’t completed before modal2 is triggered.
> 
> To resolve this, you need to add a timeout. The duration (in milliseconds) depends on the animationType of the modal. For example, with animationType set to "none," 10ms works, but if you use the "slide" animation, 500ms is needed.
> 
> This solution isn't optimal because I’m not sure if the animation speed is consistent across different devices or how the timing might be affected. Unfortunately, there doesn’t seem to be a reliable way to wait for the animation to complete. Hoping a permanent solution is implemented soon!
> 
> setModal1(false); setTimeout(() => setModal2(true), 10);

This is not a problem that required a workaround. The behaviour has simply changed, i haven't experienced layout problems or render breaks. The main thing is that the change is a breaking one (not only for me, but for many react native libraries like stripe), and it's not addressed in the changelog even as a minor.

**Comment by umutturkeri** [comment]
i have similar issues,before RN 0.76 in one page i used  2 modals, edit and add modals.now when i tried to open any modal, first previous modal opening and closing after that if i press buton again modal is opening.its not about being different modal.Example i opened add modal after that i closed.When i want to open add modal its opening and closing for 1 second.

**Comment by WilliamWelsh** [comment]
Imo this is a pretty big undocumented change/issue

**Comment by WilliamWelsh** [comment]
Could https://github.com/facebook/react-native/issues/48030 be related?

**Comment by angelica-snowit** [comment]
> Could #48030 be related?

Honestly, I'm finding really strange that bug opened three days ago are fixed and instead this post didn't even received an answer. I've only wasted time creating a repo to reproduce something that apparently didn't interest anyone.

**Comment by cortinico** [comment]
> @cortinico, question for you since I see your activity on recent posts: why are you guys answering to fresh opened bugs and not to posts of weeks ago with 16 comments? Should I reopen this every day in the hope to get someone to have a look on it?

Because our team is really small and we don't have the capacity to answer to everyone. We offer support as "best effort" meaning that there could be period where we're slower to respond due to team capacity.

Currently our team is hyperfocused on fixing New Architecture only bugs, which this one is not the case so that's why it got lower priority.

> Honestly, I'm finding really strange that bug opened three days ago are fixed and instead this post didn't even received an answer. I've only wasted time creating a repo to reproduce something that apparently didn't interest anyone.

That specific issue was addressed by a member of the community, which sent a PR, which also fixed the issue. We're more than welcome to receive PRs that close issues like this one, as that's practically the fastest way to get those bugs sorted out.

**Comment by angelica-snowit** [comment]
> > @cortinico, question for you since I see your activity on recent posts: why are you guys answering to fresh opened bugs and not to posts of weeks ago with 16 comments? Should I reopen this every day in the hope to get someone to have a look on it?
> 
> Because our team is really small and we don't have the capacity to answer to everyone. We offer support as "best effort" meaning that there could be period where we're slower to respond due to team capacity.
> 
> Currently our team is hyperfocused on fixing New Architecture only bugs, which this one is not the case so that's why it got lower priority.
> 
> > Honestly, I'm finding really strange that bug opened three days ago are fixed and instead this post didn't even received an answer. I've only wasted time creating a repo to reproduce something that apparently didn't interest anyone.
> 
> That specific issue was addressed by a member of the community, which sent a PR, which also fixed the issue. We're more than welcome to receive PRs that close issues like this one, as that's practically the fastest way to get those bugs sorted out.

Every react native app that use, to say one, Stripe library, can't update to RN 0.76 because of this.
The fact that bugs on the New Architecture, that is optional, are more important than the ones on both old and new architecture, still seems absurd to me.

**Comment by cortinico** [comment]
> Every react native app that use, to say one, Stripe library, can't update to RN 0.76 because of this.
> The fact that bugs on the New Architecture, that is optional, are more important than the ones on both old and new architecture, still seems absurd to me.

Please note that we also use the GitHub reaction feature (the '👍') to asses how many community users got affected by a bug, and this one had none.

Unfortunately with so many open bugs daily, is extremely complicated to distinguish between noise and real bugs

**Comment by angelica-snowit** [comment]
So, 4 answers saying "the same", with 4 thumbs up, worths nothing if no one add a thumb up to the first post.
Got it!

**Comment by cortinico** [comment]
> So, 4 answers saying "the same", with 4 thumbs up, worths nothing if no one add a thumb up to the first post.

Sadly answer "the same" does nothing other than creating unnecessary noise. We have 500+ issues and we don't look at every single comments. Top level reactions instead can be used to filter with the GitHub issue filter feature.

**Comment by angelica-snowit** [comment]
Yeah, got it. Again.

**Comment by angelica-snowit** [comment]
https://github.com/facebook/react-native/issues/48065
No logs, no repo, no way to reproduce, no thumbs up: answered in less than an hour.
Honestly, just answer "oh, we missed this" would have sounded better.

**Comment by angelica-snowit** [comment]
As you wish.
Good work.

**Comment by MafeeTech** [comment]
This issue might caused by this PR:

https://github.com/facebook/react-native/commit/dea5a6ca60cebf92554debe2dcdcbc40ad3fbe5a#diff-99db04a88673cd58c6b483a6b9a8ae2e39f85a31307bb6b23547ede14ed067b5R136
![Xnip2024-12-04_23-09-42](https://github.com/user-attachments/assets/387f73b5-902a-412f-bbc8-0b693e507523)

I’m not familiar with iOS development, but I guess that when trying to present the second modal, the `_topMostViewControllerFrom` method retrieves the first modal that is in the process of being dismissed.

Below is the relevant error screenshot:
<img width="934" alt="image" src="https://github.com/user-attachments/assets/623d0190-624b-4b2b-9357-65572c6f4efb">


I have tested without this change, everything is fine.

**Comment by cortinico** [comment]
> This issue might caused by this PR:

Unlikely because the linked PR was included in 0.75 also and @angelica-snowit mentioned that this is a regression 0.75 -> 0.76

**Comment by cortinico** [comment]
0.76.4 should contain the fix which solves the root cause of this issue

**Comment by WilliamWelsh** [comment]
> I have the same issue. Before 0.76, it worked fine. For example
> 
> ```ts
>     setShowEmailModal(false);
>     setShowPhoneModal(true);
> ```
> 
> Would work, the email modal would go away and the phone modal would show up. Now, the phone modal can only show up if I do this
> 
> ```ts
>     //setShowEmailModal(false);
>     setShowPhoneModal(true);
> ```
> 
> Showing it on top of another, which isn't ideal

Upgraded from 0.76.2 to 0.76.4 and I still have this issue

**Comment by zhongwuzw** [comment]
Hi, If anyone can provide a repo, I can have a look :)

**Comment by WilliamWelsh** [comment]
> Hi, If anyone can provide a repo, I can have a look :)

There’s a repo under repo

**Comment by zhongwuzw** [comment]
> > Hi, If anyone can provide a repo, I can have a look :)
> 
> 
> 
> There’s a repo under repo 

seems repo already deleted by the issue reporter.

**Comment by cortinico** [comment]
> I updated to v0.76.5 and the issue has been resolved.

Closing as per this comment as I believe the fix we shipped in .5 should fix this one.

@angelica-snowit deleted the reproducer so is making hard for us to verify further. If this issue with modals persists, please open a new GitHub issue.

**Comment by WilliamWelsh** [comment]
> I updated to v0.76.5 and the issue has been resolved.

Not for me

How about you @angelica-snowit (op) or @KaramDevelopment or @umutturkeri

**Comment by vsheyanov** [comment]
@cortinico I've reproduced this error. 
0.76.5 fixed it for the **new architecture**, but kept broken if you `opt out`.
You can use reproduction repo from another issue I've created: https://github.com/facebook/react-native/issues/48245
Just do `RCT_NEW_ARCH_ENABLED=0 bundle exec pod install` and you won't see the second `Modal` at all.

**Comment by fukuli053** [comment]
This issue is still present in 0.76.5 in **new architecture**

**Comment by vsheyanov** [comment]
@fukuli053 can you open my reproduction repo and confirm that you don't see a second modal with **new architecture**?
https://github.com/vsheyanov/react-76-4-modal-bug/tree/main

**Comment by cortinico** [comment]
Commenting on closed issues won't help. Please open a new issue and provide:
1. Clear reproducer
2. A video of the problem
3. Clarify if it's happening on either old/new arch or both

**Comment by vsheyanov** [comment]
I'll do that based on my message that has everything: 
https://github.com/facebook/react-native/issues/47694#issuecomment-2551245052

**Comment by vsheyanov** [comment]
> I did it also : [#48611 (comment)](https://github.com/facebook/react-native/issues/48611#issue-2780835931)
@yonitou thanks! Then I'm not going to create duplicates.
