### ISSUE TITLE
xcode 16.2 Could not build module 'DarwinFoundation' 

### ISSUE THREAD

**Issue by pareshbbi** [facebook/react-native#48462]
### Description

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.2.sdk/usr/include/sys/_types/_mach_port_t.h:49:10 Could not build module 'DarwinFoundation'

### Steps to reproduce

![Screenshot 2025-01-03 at 2 49 30 PM](https://github.com/user-attachments/assets/b0d7a8d0-001f-464a-b9fb-41ffdfa25872)

### React Native Version

0.76.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1
  CPU: (8) arm64 Apple M2
  Memory: 423.88 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.5
    path: ~/.nvm/versions/node/v18.20.5/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v18.20.5/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/bigbrainy/.rvm/gems/ruby-3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "29"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google Play Experimental 16k Page Size ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
      - android-VanillaIceCream | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/bigbrainy/.rvm/rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Stacktrace or Logs

```text
/*
 * Copyright (c) 2003-2012 Apple Inc. All rights reserved.
 *
 * @APPLE_OSREFERENCE_LICENSE_HEADER_START@
 *
 * This file contains Original Code and/or Modifications of Original Code
 * as defined in and that are subject to the Apple Public Source License
 * Version 2.0 (the 'License'). You may not use this file except in
 * compliance with the License. The rights granted to you under the License
 * may not be used to create, or enable the creation or redistribution of,
 * unlawful or unlicensed copies of an Apple operating system, or to
 * circumvent, violate, or enable the circumvention or violation of, any
 * terms of an Apple operating system software license agreement.
 *
 * Please obtain a copy of the License at
 * http://www.opensource.apple.com/apsl/ and read it before using this file.
 *
 * The Original Code and all software distributed under the License are
 * distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 * Please see the License for the specific language governing rights and
 * limitations under the License.
 *
 * @APPLE_OSREFERENCE_LICENSE_HEADER_END@
 */

/*
 *	mach_port_t - a named port right
 *
 *	In user-space, "rights" are represented by the name of the
 *	right in the Mach port namespace.  Even so, this type is
 *	presented as a unique one to more clearly denote the presence
 *	of a right coming along with the name.
 *
 *	Often, various rights for a port held in a single name space
 *	will coalesce and are, therefore, be identified by a single name
 *	[this is the case for send and receive rights].  But not
 *	always [send-once rights currently get a unique name for
 *	each right].
 *
 *	This definition of mach_port_t is only for user-space.
 *
 */

#ifndef _MACH_PORT_T
#define _MACH_PORT_T
#include <sys/_types.h> /* __darwin_mach_port_t */
typedef __darwin_mach_port_t mach_port_t;
#endif /* _MACH_PORT_T */
```

### Reproducer

https://github.com/pareshbbi/Reproducer

### Screenshots and Videos

![Screenshot 2025-01-03 at 2 49 30 PM](https://github.com/user-attachments/assets/bb7382c6-fb3f-4199-bce4-707473f6c056)

**Comment by cipolleschi** [comment]
@pareshbbi Hi, thanks for submitting the issue. I would appreciate some more information, because you just added the basic reproducer, with no additional dependencies and the default App.tsx file.

We test that scenario internally before shipping a new version of React Native, so we know it works.

Can you share:
- which dependencies are you using when the issue occurs
- your Podfile
- your AppDelegate

--

Have you tried to:
1. remove node_modules
2. remove the Podfile.lock, the Pods folder and the xcworkspace file
3. re run `yarn install`
4. re run `bundle exec pod install`
???

**Comment by lovelytingy** [comment]
@pareshbbi bro, I was actually able to run your reproducer temp project, which you can see in the screenshot. As you can see the my mac running on latest mac version 15.2 and node is also latest but I think the issue with your mac is not with the environment actually it may the simulators issue. Try maybe deleting reinstalling again.

My system info: (Output of npx react-native info)

> System:
  OS: macOS 15.2
  CPU: (10) arm64 Apple M4
  Memory: 154.91 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/lovelytingy/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 34.0.0
      - 35.0.0
      - 36.0.0
    System Images:
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.3.6
    path: /Users/lovelytingy/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true


![Screenshot 2025-01-03 at 18 46 12](https://github.com/user-attachments/assets/dde9f3d7-6b1e-464a-bb84-568e151ded37)

**Comment by Settasit7** [comment]
Same here
![Image](https://github.com/user-attachments/assets/2eea6b1d-428b-48b6-b626-59173d5fb902)

**Comment by cipolleschi** [comment]
Please:
- remove node_modules
- remove the ios/YourApp.xcworkspace file
- remove the ios/Podfile.lock file
- remove the ios/Pods folder
- re-run `yarn install`
- move to `ios` folder
- run `bundle install`
- run `bundle exec pod install`
- open the `YourApp.xcworkspace` file (**not the `YourApp.xcodeproj` file**)

**Comment by AlejandroIrizarry** [comment]
> Same here ![Image](https://github.com/user-attachments/assets/2eea6b1d-428b-48b6-b626-59173d5fb902)

same. So frustrating.

**Comment by AlejandroIrizarry** [comment]
> Please:
> 
> * remove node_modules
> * remove the ios/YourApp.xcworkspace file
> * remove the ios/Podfile.lock file
> * remove the ios/Pods folder
> * re-run `yarn install`
> * move to `ios` folder
> * run `bundle install`
> * run `bundle exec pod install`
> * open the `YourApp.xcworkspace` file (**not the `YourApp.xcodeproj` file**)

@cipolleschi I followed these steps, and cleaned build folder at the end, but it did not work for me. Still receive the same errors 😔

**Comment by cipolleschi** [comment]
@AlejandroIrizarry  Can you try to create a new app from the template with:
```
npx @react-native-community/cli init NewApp --version latest
```
And try again? If that works, there is some issue on the specific project.

If that does not, there is some issue in your local configuration. 

I just run that yesterday and I had no problems in creating a new project and having it running.

**Comment by AlejandroIrizarry** [comment]
@cipolleschi it worked. Seems like the issue is in that specific project 😔

**Comment by abubakarsd** [comment]
I also have the same headache 🤕 for days now. UIKit issues
SDHARUNA-2:ios macbookpro$ npx react-native info
warn Package native-base contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 15.2
  CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Memory: 68.65 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.25
    path: /usr/local/Cellar/openjdk@11/11.0.25/libexec/openjdk.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by XI2944-sauravkumar** [comment]
@AlejandroIrizarry  are you using RN-firebase  use_frameworks  OR  modular_headers?  i am also getting same error when upgrading to RN .76.6

**Comment by cipolleschi** [comment]
@AlejandroIrizarry to use firebase, you should install cocoapods using statically linked frameworks. You can do that by calling `USE_FRAMEWORK=static bundle exec pod install` or by adding `ENV['USE_FRAMEWORKS']='static'` at the beginning of your `Podfile`.. but if you were using React Native with 0.76, that should already be the case.

If you are using NativeBase, we received multiple reports of Native Base not supporting the New Architecture properly (cc. @abubakarsd ).

NativeBase is also deprecated and unmaintained, so I strongly advise you to move away from it as it will work lesse and less with time.

<img width="1274" alt="Image" src="https://github.com/user-attachments/assets/f0414204-c79a-4f06-894b-0867a90a2279" />

Side note, we already released 0.76.7, 0.77.1 and 0.78.0.

**Comment by cw-nikhilnaik** [comment]
This issue was faced by me, and it was because of react-native-firebase. Because of `use_modular_headers` . I removed it and it worked. If you are using firebase and want a fix for it then do this change https://github.com/invertase/react-native-firebase/issues/7477

Also if you see that new project is running perfectly and your current project fails then try to make the package.json and podfile of new project same as that of your current project, so that you will get to see if it is because of any dependency or not.

**Comment by pareshbbi** [comment]
@cw-nikhilnaik still facing same issue  because of react-native-firebase

**Comment by cw-nikhilnaik** [comment]
> @cw-nikhilnaik still facing same issue  because of react-native-firebase
> 

You removed firebase and tried?

**Comment by cipolleschi** [comment]
@pareshbbi please follow the guide on firebase: https://rnfirebase.io/#3-react-native-cli---ios-setup.

Remember to install your pods with `USE_FRAMEWORKS=static bundle exec pod install`

**Comment by FarouqKrayem** [comment]
I'm facing same issue 
-> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.2.sdk/usr/include/___wctype.h:58:10 **Could not build module 'DarwinFoundation'**


![Image](https://github.com/user-attachments/assets/e0ef89de-b594-473d-852c-0dfe8766137b)

i tried to:

remove node_modules
remove the Podfile.lock, the Pods folder and the xcworkspace file
re run 'npm install'

re run 'cd ios' & 'pod install'
My system info: (Output of npx react-native info)
```

System:
  OS: macOS 15.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 132.70 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.6.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.08.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

------
NOTE; i tried to create new react native project -> also didn't worked and wasn't able to run it on ios
--- below is Podfile
```

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Application' do
  use_modular_headers!  # ✅ Improve compatibility with third-party libraries

  # ✅ Google Maps Pods (Make sure these versions work for your project)
  # pod 'GoogleMaps' 
  # pod 'Google-Maps-iOS-Utils'
  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Add react-native-svg pod
  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'ApplicationTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

----------------

here is package,json

```
{
  "name": "Application",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@formatjs/intl-pluralrules": "^5.2.14",
    "@gorhom/bottom-sheet": "^4.6.4",
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-clipboard/clipboard": "^1.16.2",
    "@react-native-community/datetimepicker": "^8.2.0",
    "@react-native-picker/picker": "^2.7.7",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/stack": "^6.4.1",
    "date-fns": "^3.6.0",
    "date-fns-tz": "^3.1.3",
    "i18next": "^23.14.0",
    "react": "18.3.1",
    "react-i18next": "^15.0.1",
    "react-native": "0.75.2",
    "react-native-calendars": "^1.1306.0",
    "react-native-contacts": "^7.0.8",
    "react-native-gesture-handler": "^2.19.0",
    "react-native-image-picker": "^7.1.2",
    "react-native-localize": "^3.2.1",
    "react-native-maps": "^1.20.1",
    "react-native-material-menu": "^2.0.0",
    "react-native-permissions": "^4.1.5",
    "react-native-picker-select": "^9.3.1",
    "react-native-reanimated": "^3.15.1",
    "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.34.0",
    "react-native-svg": "^15.11.1",
    "react-native-svg-transformer": "^1.5.0",
    "react-native-toast-message": "^2.2.1",
    "react-native-vector-icons": "^10.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.75.2",
    "@react-native/eslint-config": "0.75.2",
    "@react-native/metro-config": "0.75.2",
    "@react-native/typescript-config": "0.75.2",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

```

**Comment by cipolleschi** [comment]
please, make sure to open the xcworkspace file, not the xcodeproj file.

```
npx @react-native-communuty/cli init NewApp --version latest --skip-install
cd NewApp 
yarn install
cd ios
bundle install
bundle exec pod install
open NewApp.xcworkspace
cd ..
yarn start
```

This snippet will create a new app, install all the dependencies, open it in Xcode and launch Metro.

From Xcode, <kbd>⌘</kbd>+<kbd>R</kbd> to build and run.

If this does not work, it means that your system is not properly configured, please follow the guide [on the website](https://reactnative.dev/docs/set-up-your-environment?platform=ios).

If that works, it means that your project has some configuration issue.

Let's try to remove all the 3p dependencies in your project and add them back one after the other to see which one is causing the issue. As a general rule, you should **never** touch the Podfile file.
All the dependencies should be installed using `yarn add <dependency_name>` and autolinking will take care of configuring the Podfile for you.
If you use Firebase, make sure to install the pods with `USE_FRAMEWORKS=static bundle exec pod install`.

**Comment by shilpa12233** [comment]
I am trying to add firebase version 11.10.0 , through SPM , i am getting these errors, please help.

**Comment by shilpa12233** [comment]
[



]

**Comment by FarouqKrayem** [comment]
I mange my issue -> was able to proceed and work with xCode 16 with react-native 0.75.2
fix was on podfile

-> 
```
# ✅ Use static frameworks (required for some Swift pods, and safer for iOS 17/18 SDK)
use_frameworks! :linkage => :static
```
&& 
```

  # ❌ Remove use_modular_headers! — it causes Xcode 16.2 build failures
  # use_modular_headers!
```

this is my podFile [Ignore comments]

```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# ✅ Use static frameworks (required for some Swift pods, and safer for iOS 17/18 SDK)
use_frameworks! :linkage => :static

target 'Application' do
  # ❌ Remove use_modular_headers! — it causes Xcode 16.2 build failures
  # use_modular_headers!

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # :hermes_enabled => true,  # Optional: already true by default in your config
    # :flipper_configuration => FlipperConfiguration.disabled,  # Optional: if Flipper was used
  )

  # ✅ Uncomment any custom pods you're using
  # pod 'GoogleMaps' 
  # pod 'Google-Maps-iOS-Utils'
  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'
  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'ApplicationTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

NOTE: before proceeding on update -> u have to delete old pod

```
cd ios
rm -rf Pods Podfile.lock ~/Library/Developer/Xcode/DerivedData
pod install --repo-update
```

**Comment by shilpa12233** [comment]
<img width="353" alt="Image" src="https://github.com/user-attachments/assets/d424b332-af38-49e4-b13e-03e2405969cb" />

**Comment by cipolleschi** [comment]
@shilpa12233 Firebase can't be add through SPM in a react native app.
Please follow the [Firebse guide](https://rnfirebase.io/#installation-for-react-native-cli-non-expo-projects) on how to integrate it with React Native.

**Comment by ezParth** [comment]
@pareshbbi So , did you find the solution?

**Comment by hashirabbasi777** [comment]
I am first time running my app on IOS , this app is working fine on android version here is the error details:

<img width="226" alt="Image" src="https://github.com/user-attachments/assets/8708f310-5083-4092-9a2a-068917e9550c" />


and her is my react native info command result:

<img width="296" alt="Image" src="https://github.com/user-attachments/assets/61e6fbb6-657d-4255-86bf-2111fcd8c830" />

My current React native version is : **0.77.0**

If anyone have good resources for learning IOS react native or Xcode , kindly share
Thnanks

**Comment by ezParth** [comment]
@hashirabbasi777 dude, the main issue was firebase and cleaning the pods, that's it. I fixed for my friend too, he was facing the same issue. If you are not using firebase the cleaning the node modules and then if that also doesn't work then you should switch to Xcode '16.2'.

Since you asked for leaning part of react native, I think you should prefer documentation and blogs :)

**Comment by hashirabbasi777** [comment]
> [@hashirabbasi777](https://github.com/hashirabbasi777) dude, the main issue was firebase and cleaning the pods, that's it. I fixed for my friend too, he was facing the same issue. If you are not using firebase the cleaning the node modules and then if that also doesn't work then you should switch to Xcode '16.2'.
> 
> Since you asked for leaning part of react native, I think you should prefer documentation and blogs :)

Thank you soo much @ezParth for your response. I am using firebase might be firebase create some issues, I am using latest xcode I'll test it with 16.2.
Thanks.

**Comment by cipolleschi** [comment]
@hashirabbasi777 Firebase for iOS has some specific [install instruction](https://rnfirebase.io/#3-react-native-cli---ios-setup) you need to follow. If it is working on Android, you can't just run the same app on iOS if you don't follow these steps.

**Comment by hashirabbasi777** [comment]
> [@hashirabbasi777](https://github.com/hashirabbasi777) Firebase for iOS has some specific [install instruction](https://rnfirebase.io/#3-react-native-cli---ios-setup) you need to follow. If it is working on Android, you can't just run the same app on iOS if you don't follow these steps.

Thanks for sharing install instruction, this issue is mainly related to firbase implementation

**Comment by ds-shubhamsharma** [comment]
> [@pareshbbi](https://github.com/pareshbbi) Hi, thanks for submitting the issue. I would appreciate some more information, because you just added the basic reproducer, with no additional dependencies and the default App.tsx file.
> 
> We test that scenario internally before shipping a new version of React Native, so we know it works.
> 
> Can you share:
> 
> * which dependencies are you using when the issue occurs
> * your Podfile
> * your AppDelegate
> 
> --
> 
> Have you tried to:
> 
> 1. remove node_modules
> 2. remove the Podfile.lock, the Pods folder and the xcworkspace file
> 3. re run `yarn install`
> 4. re run `bundle exec pod install`
>    ???

@cipolleschi I am facing same issue Could not build module 'UIKit' how to resolve please help me 
Thanks

![Image](https://github.com/user-attachments/assets/7ffcad70-20ff-4d65-a8dd-86bce627296f)

**Comment by hashirabbasi777** [comment]
In my scenario this error mostly occur due to not properly set the firebase implementation on ios project, check out the blogs related to setup firebase for ios its helpful , 
Here is m final podfile which is working now : 
```ruby
require Pod::Executable.execute_command('node', ['-p',
 'require.resolve(
 "react-native/scripts/react_native_pods.rb",
 {paths: [process.argv[1]]},
 )', __dir__]).strip

platform :ios, '17.0'

# Use frameworks with static linkage for Firebase compatibility
use_frameworks! :linkage => :static

prepare_react_native_project!

target 'ErpApp' do
  puts "Running use_native_modules! from: #{`which node`.strip}"
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false,
    :hermes_enabled => false # 👈 disable Hermes to fix sandbox issues
  )
  
  # DO NOT manually specify Firebase versions here
  # React Native Firebase (@react-native-firebase/app) already includes the correct dependencies
  # Adding them manually here causes version conflicts
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix for Xcode and M1 Mac
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Standard settings
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        
        # Fix Swift/ObjC interface generation
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        
        # Set deployment target
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
        
        # Ensure proper architectures are used (crucial for M1 Macs)
        if target.platform_name == :ios
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
        
        # Fix for Firebase Swift modules
        if target.name.start_with?('Firebase') || target.name.include?('firebase')
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end
end
```

**Comment by cipolleschi** [comment]
@ds-shubhamsharma it's hard to help without knowing your setup.
If you are using firebase, follow [the installation instructions](https://rnfirebase.io/#3-react-native-cli---ios-setup).

If not, you need to understand which dependency is causing the build to fail.
Start a new app and add one dependency at the time until the app stops building.

**Comment by amitkumarcoding** [comment]
This link work for me

https://github.com/invertase/react-native-firebase/issues/8219#issuecomment-2833639097

**Comment by shilpa12233** [comment]
i added 
use_frameworks! :linkage => :static

$RNFirebaseAsStaticFramework = true # add

but getting but now getting ReactCommon.modulemap not found error

@cipolleschi

**Comment by Mustufa05** [comment]
@hashirabbasi777  Have you solved this issue? And if you have, please tell me how you solved it.. 

> I am first time running my app on IOS , this app is working fine on android version here is the error details:
> 
> <img alt="Image" width="226" src="https://private-user-images.githubusercontent.com/121451399/440881660-8708f310-5083-4092-9a2a-068917e9550c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgxODM5NzEsIm5iZiI6MTc1ODE4MzY3MSwicGF0aCI6Ii8xMjE0NTEzOTkvNDQwODgxNjYwLTg3MDhmMzEwLTUwODMtNDA5Mi05YTJhLTA2ODkxN2U5NTUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxOFQwODIxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGIyY2UzNmViYjJkYmE0NjRjZmM5ZmI1YzM5OTBmY2JkMDQyN2EyNDQyNDdhYWU1NTkxZmViMzhlOTU3MDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cb93R7UQGFJbZdv4vFfS9kPnU8vXZQYLhAuzH-prgBQ">
> and her is my react native info command result:
> 
> <img alt="Image" width="296" src="https://private-user-images.githubusercontent.com/121451399/440882750-61e6fbb6-657d-4255-86bf-2111fcd8c830.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgxODM5NzEsIm5iZiI6MTc1ODE4MzY3MSwicGF0aCI6Ii8xMjE0NTEzOTkvNDQwODgyNzUwLTYxZTZmYmI2LTY1N2QtNDI1NS04NmJmLTIxMTFmY2Q4YzgzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxOFQwODIxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTIzNTZiNmIzY2VmMTZiNDZhMGYzNDRhNWQ4YTc4MjcyOTc5ZjI2MWE1NDgwNzJiYjZjZjk4ZmRiOGU1MTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PI0tjsVMXk0XDL2rthx0eSZHsTweKqxHp_6YZVKvf14">
> My current React native version is : **0.77.2**
> 
> If anyone have good resources for learning IOS react native or Xcode , kindly share Thanks

**Comment by flyskywhy** [comment]
This works for me:
```
rm -rf Pods Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
rm -rf ~/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex
rm -rf ~/Library/Developer/Xcode/DerivedData/SymbolCache.noindex
cd ios
pod install
```

**Comment by kumarsoni7999** [comment]
Hey all 
i have got the same issue in my **RN 0.79** project

I tried lot and lastly found that the issue is not much of the code base 
I was using 

* Xcode 16.1
* Node 20
* RN 0.79

To fix this issue upgrade your **Xcode 26.1**
You can download from "https://xcodereleases.com"

<img width="1298" height="173" alt="Image" src="https://github.com/user-attachments/assets/be1ebb59-7369-4809-8b3c-0ee543a3ba34" />

This fixed my issue

**Note:** After installing the Xcode move to the finder Applications folder
If any error comes in xcode click on red label and click on apply fix button and run again 

Try clean
rm -rf Pods Podfile.lock ~/Library/Developer/Xcode/DerivedData
pod cache clean --all
pod install --repo-update

**AppDelegate.swift**
`import UIKit
import Firebase
import UserNotifications
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider

@main
class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ReactNativeDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {

    // -----------------------------
    // Firebase Init
    // -----------------------------
    FirebaseApp.configure()

    UNUserNotificationCenter.current().delegate = self
    application.registerForRemoteNotifications()

    // -----------------------------
    // React Native New Architecture
    // -----------------------------
    let delegate = ReactNativeDelegate()
    let factory = RCTReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

    window = UIWindow(frame: UIScreen.main.bounds)

    factory.startReactNative(
      withModuleName: "YourAppName",
      in: window,
      launchOptions: launchOptions
    )

    return true
  }

  // -----------------------------
  // APNS Token → FCM Token
  // -----------------------------
  func application(_ application: UIApplication,
    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
  ) {
    Messaging.messaging().apnsToken = deviceToken
  }

  // -----------------------------
  // Foreground notifications
  // -----------------------------
  func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    willPresent notification: UNNotification,
    withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void
  ) {
    if #available(iOS 14.0, *) {
      completionHandler([.banner, .sound, .badge])
    } else {
      // Fallback on earlier versions
    }
  }
}

class ReactNativeDelegate: RCTDefaultReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}
`

Podfile
`require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] },
    )',
    __dir__
  ]
).strip

platform :ios, '15.1'

prepare_react_native_project!

target 'YourAppName' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # --- Firebase: Modular header fix ---
  firebase_pods = [
    'Firebase/Core',
    'Firebase/Messaging',
    'FirebaseCoreInternal',
    'FirebaseCore',
    'FirebaseInstallations',
    'GoogleUtilities',
    'FirebaseAnalyticsInterop'
  ]

  firebase_pods.each do |podname|
    pod podname, :modular_headers => true
  end
  # -------------------------------------

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|

      if target.name == 'FirebaseMessaging'
        target.build_configurations.each do |cfg|
          cfg.build_settings['CLANG_MODULES_AUTOLINK'] = 'NO'
        end
      end

      target.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end
`

**Comment by SourabhMalame** [comment]
Same Issue  

<img width="339" height="266" alt="Image" src="https://github.com/user-attachments/assets/c916fd09-3321-4f3c-9df5-aa1e8f858d79" /> 

rn 0.83 using mac mini i3 version using lib ml kit notification
