### ISSUE TITLE
uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)

### ISSUE THREAD

**Issue by guhcostan** [facebook/react-native#48746]
### Description

When running bundle install, the following error occurs

### Steps to reproduce

1. Do a "bundle install"

### React Native Version

0.75.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 122.52 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.3
    path: ~/.nvm/versions/node/v18.20.3/bin/node
  Yarn:
    version: 1.22.18
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.20.3/bin/npm
  Watchman:
    version: 2024.09.16.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 16.0/16A5230g
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: ^18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger_thread_safe_level.rb:12:in `<module:LoggerThreadSafeLevel>': uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)
    Logger::Severity.constants.each do |severity|
          ^^^^^^^^^^
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger_thread_safe_level.rb:9:in `<module:ActiveSupport>'
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger_thread_safe_level.rb:8:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger_silence.rb:5:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger.rb:3:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support.rb:29:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.2/lib/cocoapods.rb:7:in `<top (required)>'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /Users/vagrant/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.2/bin/pod:36:in `<top (required)>'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/pod:25:in `load'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/pod:25:in `<main>'
```

### Reproducer

https://github.com/guhcostan/build-ios-error-react-native

**Comment by Zlatov** [comment]
```sh
$ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
$ rails _6.1.7.4_ new test_app
/home/someuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.4/lib/active_support/logger_thread_safe_level.rb:16:in `<module:LoggerThreadSafeLevel>': uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)

    Logger::Severity.constants.each do |severity|
    ^^^^^^
```

**Comment by Guoxweii** [comment]
I have the same error

**Comment by Guoxweii** [comment]
[]([concurrent-ruby](https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror))

**Comment by daviddamilola** [comment]
I have the same error

**Comment by cipolleschi** [comment]
The problem is that Ruby released a broken gem for concurrent-ruby on Thursday.
We already fixed it on main but we haven't had the time to release new react native patches for all our versions.

To unblock you, you can modify your Gemfiles like shown in this commit:

https://github.com/facebook/react-native/commit/198adb47af3676c85b35adb308c110c1d87120c8

**Comment by shuaibzahda** [comment]
added this to the Gemfile and it fixed it.

`gem 'concurrent-ruby', '1.3.4'
`
Taken from the stackoverflow thread mentioned by  @Guoxweii

**Comment by cipolleschi** [comment]
@shuaibzahda it is the commit I linked above...

**Comment by jht6** [comment]
> The problem is that Ruby released a broken gem for concurrent-ruby on Thursday. We already fixed it on main but we haven't had the time to release new react native patches for all our versions.
> 
> To unblock you, you can modify your Gemfiles like shown in this commit:
> 
> [198adb4](https://github.com/facebook/react-native/commit/198adb47af3676c85b35adb308c110c1d87120c8)

You are my GOLD!

**Comment by omarabualhija** [comment]
Is anyone still facing this issue? You can resolve it by removing the CocoaPods installed via gem and then reinstalling it using Homebrew.

```

 sudo gem uninstall cocoapods
 brew install cocoapods 
```

**Comment by AtlasApollo** [comment]
> Is anyone still facing this issue? You can resolve it by removing the CocoaPods installed via gem and then reinstalling it using Homebrew.
> 
> ```
> 
>  sudo gem uninstall cocoapods
>  brew install cocoapods 
> ```

Thank you so much! This fixed it for me!

**Comment by NicoJL** [comment]
Edit the .ruby-version file withe the ruby version that you want (the rvm installed on the project)
