### ISSUE TITLE
No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle.

### ISSUE THREAD

**Issue by TonyFTannous-Byd** [facebook/react-native#49173]
### Description

i upgrade my react native app from 0.76.6 to 0.77.0. The build has successfully but i have the following error

No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle.

unsanitizedScriptURLString = (null)

### Steps to reproduce

i applied all the step mention 
https://react-native-community.github.io/upgrade-helper/?from=0.76.6&to=0.77.0&package=com.idp.com&name=IDPMobile

- npm install
- cd ios 
- pod deintegrate pod install --repo-update
- cd ios && xcodebuild clean
- npx react-native run-ios

### React Native Version

0.77.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 111.05 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.1
    path: ~/.nvm/versions/node/v20.18.1/bin/node
  Yarn: Not Found
  npm:
    version: 10.9.2
    path: ~/Documents/AccuV-Team/IDP.Mobile/node_modules/.bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.2
      - 33.0.3
      - 34.0.0
      - 35.0.0
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.77.0
    wanted: ^0.77.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle.

unsanitizedScriptURLString = (null)
```

### Reproducer

https://github.com/TonyFTannous-Byd/repo

open the terminal and run the following:

1- **npm run start:clean**
2- **npm run android:local** (it work no problem)
3- **npm run ios:local** (ios platform did not work, and i have the error in the Screenshots bellow)
...

### Screenshots and Videos

![Image](https://github.com/user-attachments/assets/42694096-da8f-41c8-a17e-eb59dce10097)

**Comment by princektripathi** [comment]
@TonyFTannous-Byd, can you please share a repro to validate the issue?

**Comment by TonyFTannous-Byd** [comment]
@princektripathi 
[https://github.com/TonyFTannous-Byd/repo](url)

**Comment by OTitaev** [comment]
Facing same problem

**Comment by TonyFTannous-Byd** [comment]
@react-native-bot @princektripathi any help please

**Comment by jeroenburgers** [comment]
It's the same issue for me after updating to the Swift and project.pbxproj file (documented in the update guide diff). I have no idea why.

**Comment by YlmRdm** [comment]
I have also same problem.

**Comment by OTitaev** [comment]
Guys, the problem is in DEBUG flag in AppDelegate.swift

`  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
`

You should add 
`				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
`

Inside project.pbxproj in debug XCBuildConfiguration block

Should look like this

`
		83CBBA201A601CBA00E9B192 /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
				CLANG_CXX_LANGUAGE_STANDARD = "c++20";
				CLANG_CXX_LIBRARY = "libc++";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_COMMA = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INFINITE_RECURSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
				CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
				CLANG_WARN_STRICT_PROTOTYPES = YES;
				CLANG_WARN_SUSPICIOUS_MOVE = YES;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				COPY_PHASE_STRIP = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				ENABLE_TESTABILITY = YES;
				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "";
				GCC_C_LANGUAGE_STANDARD = gnu99;
				GCC_DYNAMIC_NO_PIC = NO;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_OPTIMIZATION_LEVEL = 0;
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				GCC_SYMBOLS_PRIVATE_EXTERN = NO;
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				IPHONEOS_DEPLOYMENT_TARGET = 15.1;
				LD_RUNPATH_SEARCH_PATHS = (
					/usr/lib/swift,
					"$(inherited)",
				);
				LIBRARY_SEARCH_PATHS = (
					"\"$(SDKROOT)/usr/lib/swift\"",
					"\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
					"\"$(inherited)\"",
				);
				MTL_ENABLE_DEBUG_INFO = YES;
				ONLY_ACTIVE_ARCH = YES;
				OTHER_CPLUSPLUSFLAGS = (
					"$(OTHER_CFLAGS)",
					"-DFOLLY_NO_CONFIG",
					"-DFOLLY_MOBILE=1",
					"-DFOLLY_USE_LIBCPP=1",
					"-DFOLLY_CFG_NO_COROUTINES=1",
					"-DFOLLY_HAVE_CLOCK_GETTIME=1",
				);
				OTHER_LDFLAGS = (
					"$(inherited)",
					" ",
				);
				REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";
				SDKROOT = iphoneos;
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
				USE_HERMES = true;
			};
			name = Debug;
		};

`

**Comment by jeroenburgers** [comment]
You are a hero @OTitaev!

**Comment by TonyFTannous-Byd** [comment]
@OTitaev 
our Cocoapods scripts should inject that flag for you: https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L422

the react_native_post_install function called in your post_install hook as shown here: https://github.com/react-native-community/template/blob/main/template/ios/Podfile#L28-L33

why SWIFT_ACTIVE_COMPILATION_CONDITIONS not injected????

**Comment by wuduwawawei** [comment]
https://github.com/facebook/react-native/issues/49245#issuecomment-2687027327
Try this and I hope it can help you.

**Comment by ouyangzhigang** [comment]
Facing same problem

**Comment by rym903** [comment]
I'm also facing same issue

**Comment by rym903** [comment]
> Guys, the problem is in DEBUG flag in AppDelegate.swift
> 
> ```
> override func bundleURL() -> URL? {
> #if DEBUG
>     RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
> #else
>     Bundle.main.url(forResource: "main", withExtension: "jsbundle")
> #endif
>   }
> ```
> 
> You should add `SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";`
> 
> Inside project.pbxproj in debug XCBuildConfiguration block
> 
> Should look like this
> 
> ```
> 83CBBA201A601CBA00E9B192 /* Debug */ = {
> 			isa = XCBuildConfiguration;
> 			buildSettings = {
> 				ALWAYS_SEARCH_USER_PATHS = NO;
> 				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
> 				CLANG_CXX_LANGUAGE_STANDARD = "c++20";
> 				CLANG_CXX_LIBRARY = "libc++";
> 				CLANG_ENABLE_MODULES = YES;
> 				CLANG_ENABLE_OBJC_ARC = YES;
> 				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
> 				CLANG_WARN_BOOL_CONVERSION = YES;
> 				CLANG_WARN_COMMA = YES;
> 				CLANG_WARN_CONSTANT_CONVERSION = YES;
> 				CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
> 				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
> 				CLANG_WARN_EMPTY_BODY = YES;
> 				CLANG_WARN_ENUM_CONVERSION = YES;
> 				CLANG_WARN_INFINITE_RECURSION = YES;
> 				CLANG_WARN_INT_CONVERSION = YES;
> 				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
> 				CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
> 				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
> 				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
> 				CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
> 				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
> 				CLANG_WARN_STRICT_PROTOTYPES = YES;
> 				CLANG_WARN_SUSPICIOUS_MOVE = YES;
> 				CLANG_WARN_UNREACHABLE_CODE = YES;
> 				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
> 				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
> 				COPY_PHASE_STRIP = NO;
> 				ENABLE_STRICT_OBJC_MSGSEND = YES;
> 				ENABLE_TESTABILITY = YES;
> 				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "";
> 				GCC_C_LANGUAGE_STANDARD = gnu99;
> 				GCC_DYNAMIC_NO_PIC = NO;
> 				GCC_NO_COMMON_BLOCKS = YES;
> 				GCC_OPTIMIZATION_LEVEL = 0;
> 				GCC_PREPROCESSOR_DEFINITIONS = (
> 					"DEBUG=1",
> 					"$(inherited)",
> 				);
> 				GCC_SYMBOLS_PRIVATE_EXTERN = NO;
> 				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
> 				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
> 				GCC_WARN_UNDECLARED_SELECTOR = YES;
> 				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
> 				GCC_WARN_UNUSED_FUNCTION = YES;
> 				GCC_WARN_UNUSED_VARIABLE = YES;
> 				IPHONEOS_DEPLOYMENT_TARGET = 15.1;
> 				LD_RUNPATH_SEARCH_PATHS = (
> 					/usr/lib/swift,
> 					"$(inherited)",
> 				);
> 				LIBRARY_SEARCH_PATHS = (
> 					"\"$(SDKROOT)/usr/lib/swift\"",
> 					"\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
> 					"\"$(inherited)\"",
> 				);
> 				MTL_ENABLE_DEBUG_INFO = YES;
> 				ONLY_ACTIVE_ARCH = YES;
> 				OTHER_CPLUSPLUSFLAGS = (
> 					"$(OTHER_CFLAGS)",
> 					"-DFOLLY_NO_CONFIG",
> 					"-DFOLLY_MOBILE=1",
> 					"-DFOLLY_USE_LIBCPP=1",
> 					"-DFOLLY_CFG_NO_COROUTINES=1",
> 					"-DFOLLY_HAVE_CLOCK_GETTIME=1",
> 				);
> 				OTHER_LDFLAGS = (
> 					"$(inherited)",
> 					" ",
> 				);
> 				REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";
> 				SDKROOT = iphoneos;
> 				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
> 				USE_HERMES = true;
> 			};
> 			name = Debug;
> 		};
> ```

I tried this but 
`SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG"; ` is already inside my project.pbxproj..

**Comment by matinzd** [comment]
SWIFT_ACTIVE_COMPILATION_CONDITIONS is not being set for the main project. It's being set for pods project. You'll also need to add it for the main project:

```pbxproj
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited)";
```

**Comment by jsSteud** [comment]
For me the problem was solved, when I had both (computer and iPhone) in the same WIFI. Only connected with a cable didn't worked, with in the same WIFI worked.

**Comment by gfgafn** [comment]
**Check your network proxy settings, you will get this error when the following three conditions are met at the same time**
- You are using the iOS simulator
- You have enabled the network proxy in the Mac OS System Settings
- The network proxy server is not on the same device as the Metro Dev Server

This causes the request from your react native APP to http://localhost:8081 not be forwarded to the Metro Dev Server by the proxy server.

**The simplest solution**
Turn off the network proxy in Mac OS System Settings, completely exit your react native APP and reopen it

**Comment by daraxdray** [comment]
> I had the same problem, and I already had the SWIFT_ACTIVE_COMPILATION_CONDITIONS flag set. Here's what helped me:
> 
> Remove Pods
> 
> Remove node_modules
> 
> Do a fresh install
> 
> After installing the app, go to Settings and enable Local Network access

Fresh install of all the node modules and pod? 
ANd where in the settings are we going to enable Local Network access?

**Comment by Imran0511** [comment]
Do one thing
If you are building the app via XCode leave that and build it using terminal
like for example do yarn ios --device(if you are using yarn) , you can select your iphone there
It will make a new build and hopefully it'll run

Also you can check if your metro was running earlier. Close that and build again.

**Comment by Chwajid007** [comment]
Delete the node modules and pods then reinstall it.

Works for me.

**Comment by genesisbell** [comment]
My problem was that I had scheme names other than DEBUG. What I needed to do was to Add **-DDEBUG** to all my Debug-Like Schemes. Steps:

1. Open **Xcode** → **Project Navigator** → **Select your app target**
 
2. Go to **Build Settings**
-    Filter by: **Other Swift Flags**
-    Or navigate to:
          **Swift Compiler** – **Custom Flags** > **Other Swift Flags**

3. Add **-DDEBUG** to all relevant configurations
  For example:

| **Configuration** | **Flags**       |
|-------------------|-----------------|
| devDebug          | -DDEBUG ✅       |
| prodDebug         | -DDEBUG ✅       |
| stagDebug         | -DDEBUG ✅       |
| devRelease        | (leave empty) ❌ |
| prodRelease       | (leave empty) ❌ |
| stagRelease       | (leave empty) ❌ |

> You only need -DDEBUG for the debug builds — never add it to Release.

✅ After Adding:

1. **Product** > **Clean Build Folder**
2. Restart Metro:
  `npx react-native start --reset-cache`

**Comment by linglongmi** [comment]
> 伙计们，问题出在 AppDelegate.swift 中的 DEBUG 标志上
> 
> ```
> override func bundleURL() -> URL? {
> #if DEBUG
>     RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
> #else
>     Bundle.main.url(forResource: "main", withExtension: "jsbundle")
> #endif
>   }
> ```
> 
> 你应该添加 `SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";`
> 
> 在调试 XCBuildConfiguration 块中的 project.pbxproj 内部
> 
> 应该看起来像这样
> 
> ```
> 83CBBA201A601CBA00E9B192 /* Debug */ = {
> 			isa = XCBuildConfiguration;
> 			buildSettings = {
> 				ALWAYS_SEARCH_USER_PATHS = NO;
> 				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
> 				CLANG_CXX_LANGUAGE_STANDARD = "c++20";
> 				CLANG_CXX_LIBRARY = "libc++";
> 				CLANG_ENABLE_MODULES = YES;
> 				CLANG_ENABLE_OBJC_ARC = YES;
> 				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
> 				CLANG_WARN_BOOL_CONVERSION = YES;
> 				CLANG_WARN_COMMA = YES;
> 				CLANG_WARN_CONSTANT_CONVERSION = YES;
> 				CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
> 				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
> 				CLANG_WARN_EMPTY_BODY = YES;
> 				CLANG_WARN_ENUM_CONVERSION = YES;
> 				CLANG_WARN_INFINITE_RECURSION = YES;
> 				CLANG_WARN_INT_CONVERSION = YES;
> 				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
> 				CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
> 				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
> 				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
> 				CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
> 				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
> 				CLANG_WARN_STRICT_PROTOTYPES = YES;
> 				CLANG_WARN_SUSPICIOUS_MOVE = YES;
> 				CLANG_WARN_UNREACHABLE_CODE = YES;
> 				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
> 				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
> 				COPY_PHASE_STRIP = NO;
> 				ENABLE_STRICT_OBJC_MSGSEND = YES;
> 				ENABLE_TESTABILITY = YES;
> 				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "";
> 				GCC_C_LANGUAGE_STANDARD = gnu99;
> 				GCC_DYNAMIC_NO_PIC = NO;
> 				GCC_NO_COMMON_BLOCKS = YES;
> 				GCC_OPTIMIZATION_LEVEL = 0;
> 				GCC_PREPROCESSOR_DEFINITIONS = (
> 					"DEBUG=1",
> 					"$(inherited)",
> 				);
> 				GCC_SYMBOLS_PRIVATE_EXTERN = NO;
> 				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
> 				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
> 				GCC_WARN_UNDECLARED_SELECTOR = YES;
> 				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
> 				GCC_WARN_UNUSED_FUNCTION = YES;
> 				GCC_WARN_UNUSED_VARIABLE = YES;
> 				IPHONEOS_DEPLOYMENT_TARGET = 15.1;
> 				LD_RUNPATH_SEARCH_PATHS = (
> 					/usr/lib/swift,
> 					"$(inherited)",
> 				);
> 				LIBRARY_SEARCH_PATHS = (
> 					"\"$(SDKROOT)/usr/lib/swift\"",
> 					"\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
> 					"\"$(inherited)\"",
> 				);
> 				MTL_ENABLE_DEBUG_INFO = YES;
> 				ONLY_ACTIVE_ARCH = YES;
> 				OTHER_CPLUSPLUSFLAGS = (
> 					"$(OTHER_CFLAGS)",
> 					"-DFOLLY_NO_CONFIG",
> 					"-DFOLLY_MOBILE=1",
> 					"-DFOLLY_USE_LIBCPP=1",
> 					"-DFOLLY_CFG_NO_COROUTINES=1",
> 					"-DFOLLY_HAVE_CLOCK_GETTIME=1",
> 				);
> 				OTHER_LDFLAGS = (
> 					"$(inherited)",
> 					" ",
> 				);
> 				REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";
> 				SDKROOT = iphoneos;
> 				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
> 				USE_HERMES = true;
> 			};
> 			name = Debug;
> 		};
> ```



> 伙计们，问题出在 AppDelegate.swift 中的 DEBUG 标志上
> 
> ```
> override func bundleURL() -> URL? {
> #if DEBUG
>     RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
> #else
>     Bundle.main.url(forResource: "main", withExtension: "jsbundle")
> #endif
>   }
> ```
> 
> 你应该添加 `SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";`
> 
> 在调试 XCBuildConfiguration 块中的 project.pbxproj 内部
> 
> 应该看起来像这样
> 
> ```
> 83CBBA201A601CBA00E9B192 /* Debug */ = {
> 			isa = XCBuildConfiguration;
> 			buildSettings = {
> 				ALWAYS_SEARCH_USER_PATHS = NO;
> 				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
> 				CLANG_CXX_LANGUAGE_STANDARD = "c++20";
> 				CLANG_CXX_LIBRARY = "libc++";
> 				CLANG_ENABLE_MODULES = YES;
> 				CLANG_ENABLE_OBJC_ARC = YES;
> 				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
> 				CLANG_WARN_BOOL_CONVERSION = YES;
> 				CLANG_WARN_COMMA = YES;
> 				CLANG_WARN_CONSTANT_CONVERSION = YES;
> 				CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
> 				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
> 				CLANG_WARN_EMPTY_BODY = YES;
> 				CLANG_WARN_ENUM_CONVERSION = YES;
> 				CLANG_WARN_INFINITE_RECURSION = YES;
> 				CLANG_WARN_INT_CONVERSION = YES;
> 				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
> 				CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
> 				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
> 				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
> 				CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
> 				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
> 				CLANG_WARN_STRICT_PROTOTYPES = YES;
> 				CLANG_WARN_SUSPICIOUS_MOVE = YES;
> 				CLANG_WARN_UNREACHABLE_CODE = YES;
> 				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
> 				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
> 				COPY_PHASE_STRIP = NO;
> 				ENABLE_STRICT_OBJC_MSGSEND = YES;
> 				ENABLE_TESTABILITY = YES;
> 				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "";
> 				GCC_C_LANGUAGE_STANDARD = gnu99;
> 				GCC_DYNAMIC_NO_PIC = NO;
> 				GCC_NO_COMMON_BLOCKS = YES;
> 				GCC_OPTIMIZATION_LEVEL = 0;
> 				GCC_PREPROCESSOR_DEFINITIONS = (
> 					"DEBUG=1",
> 					"$(inherited)",
> 				);
> 				GCC_SYMBOLS_PRIVATE_EXTERN = NO;
> 				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
> 				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
> 				GCC_WARN_UNDECLARED_SELECTOR = YES;
> 				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
> 				GCC_WARN_UNUSED_FUNCTION = YES;
> 				GCC_WARN_UNUSED_VARIABLE = YES;
> 				IPHONEOS_DEPLOYMENT_TARGET = 15.1;
> 				LD_RUNPATH_SEARCH_PATHS = (
> 					/usr/lib/swift,
> 					"$(inherited)",
> 				);
> 				LIBRARY_SEARCH_PATHS = (
> 					"\"$(SDKROOT)/usr/lib/swift\"",
> 					"\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
> 					"\"$(inherited)\"",
> 				);
> 				MTL_ENABLE_DEBUG_INFO = YES;
> 				ONLY_ACTIVE_ARCH = YES;
> 				OTHER_CPLUSPLUSFLAGS = (
> 					"$(OTHER_CFLAGS)",
> 					"-DFOLLY_NO_CONFIG",
> 					"-DFOLLY_MOBILE=1",
> 					"-DFOLLY_USE_LIBCPP=1",
> 					"-DFOLLY_CFG_NO_COROUTINES=1",
> 					"-DFOLLY_HAVE_CLOCK_GETTIME=1",
> 				);
> 				OTHER_LDFLAGS = (
> 					"$(inherited)",
> 					" ",
> 				);
> 				REACT_NATIVE_PATH = "${PODS_ROOT}/../../node_modules/react-native";
> 				SDKROOT = iphoneos;
> 				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
> 				USE_HERMES = true;
> 			};
> 			name = Debug;
> 		};
> ```

@TonyFTannous-Byd 是这样添加吗？
> ```
> override func bundleURL() -> URL? {
> #if DEBUG
>     SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG";
>     RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
> #else
>     Bundle.main.url(forResource: "main", withExtension: "jsbundle")
> #endif
>   }
> ```

**Comment by sandy-garrido** [comment]
For me the issue was simply that the testing device and the developer mac were on restricted networks (the need to be able to talk to each other via the network). I set up a hotspot for both devices (Dev Mac & test iPhone) and now it works.

**Comment by Super1Windcloud** [comment]
It's so easy ,  
First method , xcode config  `  Allow access to the local network ` 
Second  method ,   iphone open settings to  set  app  permission for  allow access to local network

**Comment by ShadyElsharnoby** [comment]
https://github.com/getsentry/sentry-react-native/issues/5168

**Comment by ShadyElsharnoby** [comment]
Steps to Reproduce
upgrade react native to latest 0.81.4
and add new scripts like Sentry DOC

`set -e
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_XCODE="../node_modules/@sentry/react-native/scripts/sentry-xcode.sh"
BUNDLE_REACT_NATIVE="/bin/sh $SENTRY_XCODE $REACT_NATIVE_XCODE"

Expected Result
when run on real device this should work normal like simulator but i faced this error

No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle. unsanitizedScriptURLString = (null)

in case i revert the script every thing work good without sentry

Actual Result
No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle. unsanitizedScriptURLString = (null)

**Comment by antinucleus** [comment]
If a local server (e.g., Express or Fastify) is started on the same port as Expo (8081), this error will occur. In my case, the issue was resolved by stopping the local server or configuring it to use a different port.

**Comment by Donybro** [comment]
I did prev steps 	SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG"; then deleted ios,android,expo, node-modules folders then do  npm install, npx expo prebuild --clean and npx expo run:ios --device but still see issue, then I changed my backend base url in .env file from http://localhost:8080 to http://172.16.13.4:8080 (you can get your own with ipconfig getifaddr en0) and it is worked for me

**Comment by UlasRenasOrdu** [comment]
npm install --> npx expo run:ios 

worked for me.

**Comment by justsomeofl** [comment]
Add this to AppDelegate.swift before startReactNative

```
    #if DEBUG
      RCTBundleURLProvider.sharedSettings().jsLocation = "192.168.1.20:8081" // IP of your computer
    #endif

```

**Comment by ericTrayt** [comment]
Why is this closed, still seems to be an issue for many people and none of the above answers have worked for me.

**Comment by joartola** [comment]
Hitting this on **RN 0.83.4 + New Architecture + Expo 55 + Objective-C AppDelegate**. Both simulator and physical device affected.

## Diagnosis

Added logging inside `bundleURL` to trace the resolution chain:

```objc
- (NSURL *)bundleURL {
#if DEBUG
  BOOL isRunning = [RCTBundleURLProvider isPackagerRunning:@"localhost"];
  NSString *hostPort = [[RCTBundleURLProvider sharedSettings] packagerServerHostPort];
  NSURL *url = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
  NSLog(@"isPackagerRunning=%@ hostPort='%@' url=%@",
        isRunning ? @"YES" : @"NO", hostPort ?: @"nil", url ?: @"nil");
  return url;
#else
  ...
#endif
}
```

Result:

```
isPackagerRunning=YES hostPort='nil' url=nil
```

**Metro is reachable at `localhost:8081` (200 OK), `isPackagerRunning(localhost)` returns YES, but `packagerServerHostPort` returns nil.** This means `guessPackagerHost` inside `packagerServerHostPort` returns nil despite its individual pieces working correctly.

After calling `setJsLocation:@"localhost"` explicitly, `packagerServerHostPort` returns `"localhost"` and `bundleURL` returns a valid URL.

## Workaround

Two things were needed together:

**1. Add `SWIFT_ACTIVE_COMPILATION_CONDITIONS = "$(inherited) DEBUG"`** to the app target's Debug build config (as @TonyFTannous-Byd suggested — it was set project-level but missing on the target itself)

**2. Pre-set `jsLocation` before `startReactNative`** in AppDelegate:

```objc
#if DEBUG
{
  NSString *ipPath = [[NSBundle mainBundle] pathForResource:@"ip" ofType:@"txt"];
  NSString *ip = [[NSString stringWithContentsOfFile:ipPath encoding:NSUTF8StringEncoding error:nil]
                  stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
  // Use ip.txt LAN IP for device builds, localhost for simulator/cloud-built dev clients
  BOOL isLanIp = [ip hasPrefix:@"192.168."] || [ip hasPrefix:@"10."];
  NSString *host = (ip.length > 0 && isLanIp) ? ip : @"localhost";
  [[RCTBundleURLProvider sharedSettings] setJsLocation:host];
}
#endif
```

For us, the SWIFT flag alone wasn't sufficient — possibly because we have an Objective-C AppDelegate (not Swift). The `setJsLocation` bypass ensures `packagerServerHostPort` takes the `jsLocation` path and never hits the broken `guessPackagerHost` branch.

Also required for physical devices: `runOnlyForDeploymentPostprocessing = 0` on the "Bundle React Native code and images" build phase so `ip.txt` is generated in Debug builds (was set to 1, meaning it only ran during Archive).

## Environment
- RN 0.83.4
- Expo SDK 55
- New Architecture enabled (`RCT_NEW_ARCH_ENABLED=1`)
- Objective-C AppDelegate (inherited from older RN versions)
- Xcode 16+

**Comment by wubaibin** [comment]
First, run "yarn start", and then run "yarn ios".
