### ISSUE TITLE
[Android][fetch] app crashes when response contains special character \u2028

### ISSUE THREAD

**Issue by han4wluc** [facebook/react-native#4961]
`fetch('http://someurl')`;
if the response contains the character \u2028 , the app crashes with the following error
`SyntaxError: Unexpected EOF (line 1 in the generated bundle)`

It looks like a tricky character. 
Try copy paste the below statement in your browser console, it should give you an error.
var invalidString = "s ." ;
The special character is between the "s" and the ".";

Running on react-native-0.16.0
This error does not appear during chrome debug mode.

**Comment by christopherdro** [comment]
@han4wluc What's your Content-Type set to?

**Comment by brentvatne** [comment]
cc @mkonicek

**Comment by atom992** [comment]
+1

**Comment by mkonicek** [comment]
> react-native-0.16.0

Can you try 0.18.1? We don't have bandwidth to maintain older than the latest version unfortunately.

**Comment by maraujop** [comment]
I'm seeing this error happening today using version 0.19. Some weird characters make fetch fail crashing the app, we are having serious trouble with this bug. I'm trying to spot which characters are those, but haven't yet had luck.

**Comment by mkonicek** [comment]
Looks like u2028 is a line separator, indeed it also throws an error in the Chrome console. http://www.fileformat.info/info/unicode/char/2028/index.htm

@maraujop Sorry for the delay. Do you see anything in the output of 'adb logcat' you run on your machine showing a stack trace of where the parsing fails?

**Comment by maraujop** [comment]
Hi @mkonicek ,

Sorry, for the delay too, I've been waiting for the app to crash with the same error, so I could report `adb logcat` Today it has finally shown up again, here is the stacktrace:

```
03-09 09:51:40.741 15820 16313 E ReactNative: Got JS Exception: SyntaxError: Unexpected EOF
03-09 09:51:40.741 15820 16313 E unknown:React: Exception in native call from JS
03-09 09:51:40.741 15820 16313 E unknown:React: com.facebook.react.bridge.JSExecutionException: SyntaxError: Unexpected EOF (<unknown file>:1)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.741 15820 16313 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.750 15820 16313 W ReactNativeJS: Loading tab tomorrow failed
03-09 09:51:40.761 15820 16313 W ReactNativeJS: { [SyntaxError: JSON Parse error: Unexpected EOF]
03-09 09:51:40.761 15820 16313 W ReactNativeJS:   line: 65466,
03-09 09:51:40.761 15820 16313 W ReactNativeJS:   column: 10,
03-09 09:51:40.761 15820 16313 W ReactNativeJS:   sourceURL: 'http://10.4.0.50:8081/index.android.bundle?platform=android&dev=true&hot=false' }
03-09 09:51:40.905 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.905 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.905 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.905 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.914 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.914 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.914 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.914 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.920 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.920 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.920 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.920 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.928 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.928 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.928 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.928 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.934 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.934 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.934 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.934 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.941 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.941 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.941 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.941 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.947 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.947 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.947 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.947 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:40.950 15820 16313 W unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-09 09:51:40.951 15820 16313 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.951 15820 16313 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {c2fc43d} sending message to a Handler on a dead thread
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Handler.post(Handler.java:326)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at android.os.Looper.loop(Looper.java:148)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
03-09 09:51:40.951 15820 16313 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)
03-09 09:51:41.095  1289  1289 I Keyboard.Facilitator: onFinishInput()
```

I hope this helps, because this the only bug that's biting us in RN that really worries us.

Thanks, cheers
Miguel

**Comment by BlakeWilliams** [comment]
I'm running into the same thing. It only seems to happen when I'm not debugging via Chrome though.

**Comment by MITDelian** [comment]
I've been seeing the same thing but only on Android 4.2 and below

**Comment by maraujop** [comment]
I can confirm this is happening in a Moto G 3 with Android 6 and in a Nexus 5x Android 6, and a Nexus 5 Android 5.1

**Comment by MITDelian** [comment]
I think it's a runtime error occurring with JSON.parse?

**Comment by KostasZERO72** [comment]
We got the same issue with a list of posts; as far as we can see it has to do with a JSON length limit on Android. The JSON we use is valid, and if I limit the amount of posts we fetch it works as expected.

> JSON parse error: Unrecognized token '< '

It looks like the JSON might be cut off at some point, if it's too long. 

Tested on:
HTC One X - Android 4.4.4.

**Comment by kevinejohn** [comment]
+1. Ran into this issue for Android only.

**Comment by sampurcell93** [comment]
Has anyone made progress on this issue? It's a real real problem. My only solution has been to request data in very small chunks (doesn't seem to be a unicode issue for me) and return with a promise.all();

**Comment by sampurcell93** [comment]
Just a quick workaround, in case nobody has thought of this - my team and I will be building a proxy route on our server that sanitizes inputs from sources that return this/these unicode characters, until we can figure out the problem in RN itself. We haven't tested it yet, but I don't see why it shouldn't work.

**Comment by c-h-** [comment]
Running into this issue on Samsung Galaxy S5 Android 5.0

**Comment by MITDelian** [comment]
We ended up finding that Android had a limit as to how large queries could be and so by chunking our data and queries we were able to get around this issue

**Comment by baurine** [comment]
@han4wluc recently we meet the exact same problem, I use react-native 0.24.1, crash in Android 5.1, but it is ok in iOS。

An api returns a json array, contains 100 items, crashed, at first, I thought it caused by too large body, so I reduce the items to 50, still crashed, then I continue to reduce to 25, still crashed. finally, I use bisection method, position the exact item that cause the crash. its content has no obvious strange when it displays in web browser, but when we goto the database console, print the content, it looks like this:

<img width="123" alt="qq20160531-2" src="https://cloud.githubusercontent.com/assets/1284531/15662989/72e0e2c4-2728-11e6-890c-3fbe3722de06.png">

and when I try to parse it in chrome developer tools console, it also failed.

<img width="184" alt="qq20160531-1" src="https://cloud.githubusercontent.com/assets/1284531/15663023/e84851a0-2728-11e6-805c-eba58222dac1.png">

and following is the crash log by android logcat output, use `adb logcat "*:S ReactNative:V ReactNativeJS:V"` command to see.

<img width="389" alt="qq20160531-3" src="https://cloud.githubusercontent.com/assets/1284531/15663088/7374cc04-2729-11e6-8f37-61128b538441.png">

so I don't think this is the bug of React-Native, and it should not be a bug, it is because your json content is not correct. it is just my opinion. 

finally, how we resolve this problem, we fix it in server, we replace the `\u2080` to `''` when result returns. like this:

```ruby
content = content.gsub(/\u2080/, '')  # ruby sample
```

at last, the only confuse me is that why it doesn't crash in iOS?

**Comment by mangogogos** [comment]
This was occurring to me as well. I haven't been able to determine if it occurs in JSON.parse or in AsyncStorage.getItem (I'm leaning towards either both or the latter) but my fix was to do a find and replace on my json text before storing it in AsyncStorage. I can confirm that it's not fetch that's actually crashing as it wasn't until the content was loaded from the cache that I was crashing (so the first time it would successfully fetch the content from the server then subsequently would crash when the cached data was retrieved). So my fix looked something like this:

````
if ( Platform.OS === 'android' && typeof text === 'string' )
{
  text = text.replace( /\\u2028|\\u2029/g, '' );
}
````

This is in my response handler in my API where text is the raw returned JSON from some request and this is done before JSON.parse as well as before AsyncStorage.setItem

Note that \u2029 will also cause this crash (not just the mentioned \u2028) and that JSON that is correctly encoded will write these characters as the literal string '\u2028'/'\u2029' which is why there's two backslashes in the strings

I'm also not sure why this only crashes on Android when not debugging in chrome

**Comment by nihgwu** [comment]
same issue. Android 4.4.2

**Comment by adeelraza** [comment]
+1 This issue is the biggest cause of crashes for our production app on Android.

**Comment by calebmer** [comment]
We also think we are getting this error with the following stacktrace, this is a tough error to debug:

```
java.lang.RuntimeException: SyntaxError: Unexpected EOF (<unknown file>:1)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:158)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
    at java.lang.Thread.run(Thread.java:818)
```

Similarly, we believe that it is a JSON parsing issue, we’re running some searches in our database now to see if the characters mentioned show up.

@MITDelian, @baurine, @mangogogos: You’ve had more luck so far than us debugging this issue, and you all seem to have come to different solutions. Is there more information you could provide? Stack traces or other post mortem discoveries? @baurine you mentioned your issue was with `\u2080`, did you also have problems with `\u2028`?

@mkonicek: Could this be a bug in the Android JSON parsing library? Is this intended behavior? Is there anywhere we could compare the Android and iOS JSON parsing libraries to confirm this theory?

**Comment by c-h-** [comment]
@calebmer we faced this issue and our solution was basically to try and make it never happen. Since we control every server that speaks to our app, we modified the servers to encode every unicode symbol in responses.

Then in the app we decode the unicode symbols like so:
```
function decodeUnicode(parent, index) {
  const r = /\\u([\d\w]{4})/gi;
  if (typeof parent[index] === 'string') {
    parent[index] = parent[index].replace(r, (match, grp) => {
      return String.fromCharCode(parseInt(grp, 16));
    });
    if (typeof unescape === 'function') {
      parent[index] = unescape(parent[index]);
    }
  }
}
```

On the server this snippet represents what we do to encode unicode and get rid of newlines (which also breaks JSON):
```
row[i] = row[i].replace(/\r?\n/g, '\n').replace(/[\u0080-\uFFFF]/g, function(match) {
   return `\\u${('0000' + match.charCodeAt(0).toString(16)).slice(-4)}`;
});
```

**Comment by mangogogos** [comment]
@calebmer for me, my solution was to find and replace for these characters in the raw json text before doing anything with them (AsyncStorage.setItem/JSON.parse mostly)

````
// API.js
// ....
// ---------------------------------------------------------- getBodyCacheWriter
function getBodyCacheWriter( key, writeToCache = false )
{
  // get a response handler for some request that may write to cache via AsyncStorage
  return function( response )
  {
    return response.text()
                    .then( text =>
                    {
                      if ( Platform.OS === 'android' )
                      {
                        // see https://github.com/facebook/react-native/issues/4961
                        text = text.replace( /\\u2028|\\u2029/g, '' );
                      }
                      if ( writeToCache )
                      {
                        Cache.writeRawValue( key, text );
                      }
                      return text;
                    } )
                    .then( JSON.parse )
                    .catch( () =>
                    {
                      debug( response.url, 'returned invalid json' );
                      return {};
                    } );
  };
}
// ...
````

**Comment by MITDelian** [comment]
So for us this turned out to be a Async Storage issue. On Android the max dB size is 5 MB and max query size is 1 MB.

We ended up forking react native and compiling from source to up the max size to 50 MB and we shard all of our storage saves into 1 MB pieces and then remerge on the relaunch of the app.

We did not face the same character issue as others have.

**Comment by nihgwu** [comment]
@MITDelian I've noticed a warning about the storage size too, but I didn't do further research about that. Is there a cheap way to enlarge the default storage size for android?

**Comment by astreet** [comment]
I'm hitting this too in my personal project :( Looking into it now.

**Comment by astreet** [comment]
This is an error you get when you JSON.parse an empty string -- I haven't located which one it is yet but will look in more tomorrow. (it's possible that this could also trigger when we try to JSON.parse a string with bad characters: it basically just uses the standard JS parser that it uses to parse JS otherwise)

**Comment by MITDelian** [comment]
@nihgwu haha yeah, it's pretty easy but you do need to fork react native and then compile from source. there are instructions in their docs on how to do that for android, it's not too hard.

You don't actually need to change much code lol: https://github.com/nightingale/react-native/commit/f78138cdc3b9a5f3be0ea24f163f5ee2709d5205

**Comment by astreet** [comment]
Yep, this is definitely the problem. See this SO answer: http://stackoverflow.com/a/9168133

Luckily, in the new bridge we are shipping in the next release or two, we don't have this problem anymore. In the meantime, you can replace `ResponseUtil.onDataReceived` (used by the NetworkingModule) with this code if you're hitting this:

```
public static void onDataReceived(
    RCTDeviceEventEmitter eventEmitter,
    int requestId,
    String data) {
    String strippedData = data.replace("\u2028", "").replace("\u2029", "");

    WritableArray args = Arguments.createArray();
    args.pushInt(requestId);
    args.pushString(strippedData);

    eventEmitter.emit("didReceiveNetworkData", args);
  }
```

You can do this by compiling RN Android from source (sorry).

@foghina also has an idea about being able to manually enable the new bridge on RN master.

**Comment by foghina** [comment]
See `ReactNativeHost#createReactInstanceManager()` -- override that and just call `setUseOldBridge(false)` on the builder.

**Comment by foghina** [comment]
And then return your custom host from `MyApplication#getReactNativeHost()`.

**Comment by foghina** [comment]
cc @bestander does the new bridge actually work in OSS like this?

**Comment by bestander** [comment]
It does not work in OSS yet, some build scripts need to be updated to be compiled properly but we are just a few steps away

**Comment by javache** [comment]
I believe @astreet had a solution for this.

**Comment by satya164** [comment]
@javache Thanks.

I'm trying @astreet 's suggestion of modifying `NetworkModule`. I think I might not have to build from source as modules can be overriden. Wish me luck.

**Comment by satya164** [comment]
Unfortunately I can no longer repro the issue locally. I'm gonna push an update with NetworkingModule change and see if I get any further crash reports.

**Comment by OBriensTree** [comment]
Can you guys get this figured out?

**Comment by astreet** [comment]
Is this actually getting worse in the new release? Are we planning on doing a re-roll?

**Comment by satya164** [comment]
@astreet May be it's not the release. I certainly got a lo of crash reports after I upgraded. But it might as well be some user generated content.

Since the new bridge is gonna fix it and there's a workaround available right bow

**Comment by astreet** [comment]
Yeah, if the next release is going to have the fix then there's nothing to do really. But if we're not sure we're going to be releasing the new bridge (or are going to roll another release to fix this), then we should temporarily patch the networking module

**Comment by satya164** [comment]
@astreet Can send a PR if you want.

**Comment by astreet** [comment]
@bestander, do you know where the new bridge comes in with respect to our release schedule?

**Comment by bestander** [comment]
Once @mhorowitz and @cjhopman fix the build scripts for OSS we can enable the new bridge by default.
Branch 0.30 has been cut last week, better not to cherry-pick such a change into stable.
But 0.31 is going to be cut next Monday.

**Comment by astreet** [comment]
Ok, I'm not convinced we can rely on that. The networking fix will also cause perf issues. I'll send out a diff that fixes it properly in the old bridge.

**Comment by astreet** [comment]
This is fixed by https://github.com/facebook/react-native/commit/6d3c7b8a4c1d1a0552a21cfabe03a8d1f344d1ed which should make it into the next release whether or not the new bridge is turned on by then.

**Comment by satya164** [comment]
Thanks a lot @astreet 

Cherry picking this to 0.29.1 and 0.30

**Comment by OBriensTree** [comment]
Hi facebook/react-nativ,

I'd like to add you to my professional network on LinkedIn.

- O'Brien"s Tree Ser.

Confirm that you know O&#39;Brien&quot;s Tree Ser.: https://www.linkedin.com/e/v2?e=0-iqlgebqc-2m&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=XxRZuKix&invitationId=6159119812560777216








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iqlgebqc-2m&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHIjNqJwZxldwAAAVXmW-COh3gVJNMn0rgXFKlPy0HGA6Of4dGruFPbRqZVQLhR98VfRf4GBFyVR6UOTl2-PGU-yV2-tsw0TlsSZwo3aPfVRf0h3uE1uxr41vHzaxsL8OOHQ5XQysEemIqbrt-fGR9MV28b9xOjvXgNuOsoqwV6UeETnU6vZJxSBaBlevMVkp7x&eid=0-iqlgebqc-2m


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iqlgebqc-2m&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by satya164** [comment]
Fixed in https://github.com/facebook/react-native/commit/6d3c7b8a4c1d1a0552a21cfabe03a8d1f344d1ed

**Comment by OBriensTree** [comment]
O'Brien's Tree Serv. And Stump-Grinding would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-b25vav-iqv3qozw-qd&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=XxRZuKix&invitationId=6159119812560777216

View O&#39;Brien&#39;s Tree Serv. And Stump-Grinding&#39;s profile: https://www.linkedin.com/e/v2?e=-b25vav-iqv3qozw-qd&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=XxRZuKix&invitationId=6159119812560777216





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-b25vav-iqv3qozw-qd&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-b25vav-iqv3qozw-qd&loid=AQHEPwlyg0YXQAAAAVYJwd1MQUqSMOvSemVA83XJKJrNaVEZRQ1GeMvp7nK3fisFz8S7eEjrLk4FZEZTGUxYqcsHp2gMdzRlSajH38TB5RAwsnp39a_crcUtgF65NdLPUfSyVmFxuNMraehhkdNS9-Xx0STG943d9_hYoAMcTyDPPCtVjjRVcqPYXQyzRcLUeKxf

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-b25vav-iqv3qozw-qd&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by OBriensTree** [comment]
O'Brien's Tree Serv. And Stump-Grinding would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-b25vav-ir53vllf-zq&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=XxRZuKix&invitationId=6159119812560777216

View O&#39;Brien&#39;s Tree Serv. And Stump-Grinding&#39;s profile: https://www.linkedin.com/e/v2?e=-b25vav-ir53vllf-zq&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=XxRZuKix&invitationId=6159119812560777216





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-b25vav-ir53vllf-zq&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-b25vav-ir53vllf-zq&loid=AQGqCNC68F_cGgAAAVYuhBkA5byvgdRtMIpMOzO6ChpkGSCLiNXvLmKk4MaM4iXpY37fH1qhkFPYI7If2E-dLuA4y15uP528kQEXglPy26MHJLmHGa5Une_Jt-AlDmQYt5eHkD3AhqZGYJtwUSTce99eqKVcPWdwBEdhFLgAQFJ6LCTXFoQzrQ240WWefuDlySEd

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-b25vav-ir53vllf-zq&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by LeBlaaanc** [comment]
Despite adding this patch I still get this error when newlines are contained in the response.
