### ISSUE TITLE
[android][TextInput] Placeholder is not respecting custom font family and weight

### ISSUE THREAD

**Issue by lorenc-tomasz** [facebook/react-native#50137]
### Description

On some Android devices user can change default font to e.g. `Cool jazz`. 

<img src="https://github.com/user-attachments/assets/99ed7771-49fa-44db-b14d-3b26e1b75a49" width="200">

In the app we don't want to allow user to change font family, so we apply `fontFamily` and `fontWeight`. 

Example: 

```javascript

           <TextInput style={{
                height: 60,
                borderColor: 'gray',
                borderWidth: 1,
                marginBottom: 20,
                fontFamily: 'Roboto',
                fontWeight: '400',
                fontSize: 20,
            }} placeholder={"Search..."} />
```

We are expecting the placeholder will be using the same `fontFamily`as set in styles. However it's not a case. Placeholder will use device's default font instead. 

To workaround this I manage to find this solution:

```javascript

import React, { forwardRef, useRef, useCallback } from 'react';
import {Platform, StyleSheet, TextInput, TextInputProps} from 'react-native';

const CustomTextInput = forwardRef<TextInput, TextInputProps>((props, ref) => {
  const inputRef = useRef<TextInput | null>(null);

  const setRef = useCallback(
    (node: TextInput | null) => {
      if (node) {
        inputRef.current = node;

        if (typeof ref === 'function') {
          ref(node);
        } else if (ref) {
          const mutableRef = ref as React.MutableRefObject<TextInput | null>;
          mutableRef.current = node;
        }

        // Workaround for Android to apply style before setting placeholder
        // to apply font family correctly
        if (Platform.OS === 'android') {
          node.setNativeProps({
            style: StyleSheet.flatten([{
                fontFamily: 'Roboto',
                fontWeight: '400',
            }, props.style ?? {}]),
          });
        }
      }
    },
    [ref],
  );

  return <TextInput ref={setRef} {...props} />;
});

export default CustomTextInput;
```

so the `fontFamily` is applied correctly.

```javascript

        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
            paddingHorizontal: safePadding,
            paddingTop: safePadding,
            paddingBottom: safePadding,
          }}>
            <TextInput style={{
                height: 60,
                borderColor: 'gray',
                borderWidth: 1,
                marginBottom: 20,
                fontFamily: 'Roboto',
                fontWeight: '400',
                fontSize: 20,
            }} placeholder={"Search..."} />
        </View>
          <View
              style={{
                  backgroundColor: isDarkMode ? Colors.black : Colors.white,
                  paddingHorizontal: safePadding,
                  paddingTop: safePadding,
                  paddingBottom: safePadding,
              }}>
              <CustomTextInput style={{
                  height: 60,
                  borderColor: 'gray',
                  borderWidth: 1,
                  marginBottom: 20,
                  fontFamily: 'Roboto',
                  fontWeight: '400',
                  fontSize: 20,
              }} placeholder={"Custom search..."} />
          </View>

```

<img src="https://github.com/user-attachments/assets/3b2add21-b145-40ef-9b2f-21f696f7aff2" width="300">

As you can see the first text input has wrong `fontFamily` and the second one uses the correct one. 

However expected behaviour is that the custom font will be applied based on style. 

All React-Native versions are affected. 

### Steps to reproduce

Set custom font into `TextInput` and set placeholder. 
Change Font Style on device. 
You will see that placeholder is not respecting the custom font.

### React Native Version

0.78.1

### Affected Platforms

Runtime - Android

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.3.2
  CPU: (12) arm64 Apple M2 Pro
  Memory: 218.94 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.13.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.9.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2025.02.17.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/tomaszlorenc/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "28"
      - "31"
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 34.0.0
      - 35.0.0
      - 35.0.1
    System Images:
      - android-26 | Google APIs ARM 64 v8a
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.22562.218.2431.13114758
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/tomaszlorenc/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.78.1
    wanted: 0.78.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No logs.
```

### Reproducer

https://github.com/lorenc-tomasz/react-native-text-input-placeholder-font-issue-reproducer

**Comment by lorenc-tomasz** [comment]
Hi @cortinico,
could you look into this, please? I tried to find native solution but nothing worked for me. That's way at the moment I'm using the mentioned workaround.

**Comment by cortinico** [comment]
> Change Font Style on device.

I don't have a device that allows this so I can't reproduce at the moment

**Comment by lorenc-tomasz** [comment]
Just to let you know that any new Samsung Android phone allows that. It's interesting that some users use e.g. `Comic Sans` on device and it's funny how apps look with that font, and even Google Maps doesn't manage it well :D

**Comment by narekmalk** [comment]
Hi, can I take this issue?

**Comment by cortinico** [comment]
> Hi, can I take this issue?

Please do

**Comment by narekmalk** [comment]
@cortinico, @lorenc-tomasz, I tried several physical devices and android emulators, but wasn't able to find the feature of changing system font
I think would be better to assign this issue to someone else
Apologies

**Comment by mensonones** [comment]
Hey, @cortinico and @lorenc-tomasz 

I found out that the cause may be related to **autoCapitalize**

```javascript
<TextInput
  style={{
    height: 60,
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 20,
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 20,
  }}
  autoCapitalize="none"
  placeholder={"Search..."}
/>;
```
If you pass **autoCapitalize="none"** the problem does not occur

![Image](https://github.com/user-attachments/assets/32a4ba1b-ad7a-4056-8a0d-a2c2de455056)

You must run Android again to get the changes related to this case. hot reload does not always work with this change

**Comment by lorenc-tomasz** [comment]
Hi @mensonones,
I have checked your workaround. And it seems to work with 0.78.1. However when I tried the same solution on our production app that still uses 0.76.x, it doesn't fixed the issue. Only the workaround with ref is working fine.

**Comment by lorenc-tomasz** [comment]
Hi @cortinico,
Could you unassign @narekmalk, as he doesn't have a device to look into the issue, please?

**Comment by lorenc-tomasz** [comment]
Hi @cortinico, @narekmalk and @mensonones,

I have pushed changed into `patch` branch. No idea about quality of the solution but this works for me:

```diff

diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
index a037077..2573aec 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
@@ -1298,11 +1298,37 @@ public class ReactEditText extends AppCompatEditText {
 
   @Override
   public void onDraw(Canvas canvas) {
+    // Clip the canvas to the padding box if overflow is not visible.
     if (mOverflow != Overflow.VISIBLE) {
       BackgroundStyleApplicator.clipToPaddingBox(this, canvas);
     }
 
+    // Call the superclass's onDraw method to draw the EditText's default content.
     super.onDraw(canvas);
+
+    // Check if we need to manually draw the hint with a custom font.
+    if (mFontFamily != null && getText().length() == 0 && !isFocused() && getHint() != null) {
+      // Get the Paint object used for drawing.
+      Paint paint = getPaint();
+
+      // Apply the custom font family, style, and weight to the Paint object.
+      Typeface typeface = ReactTypefaceUtils.applyStyles(
+              paint.getTypeface(), mFontStyle, mFontWeight, mFontFamily, getContext().getAssets());
+      paint.setTypeface(typeface);
+
+      // Store the original hint and text colors.
+      int originalHintColor = getCurrentHintTextColor();
+      int originalTextColor = getCurrentTextColor();
+
+      // Set the text color to the hint color to prevent EditText's default hint drawing.
+      setTextColor(originalHintColor);
+
+      // Manually draw the hint text with the custom font.
+      canvas.drawText(getHint().toString(), getCompoundPaddingLeft(), getBaseline(), paint);
+
+      // Restore the original text color immediately after drawing the hint.
+      setTextColor(originalTextColor);
+    }
   }
 
   /**

```


What do you think?

**Comment by cortinico** [comment]
> I have pushed changed into `patch` branch. No idea about quality of the solution but this works for me:

@lorenc-tomasz can you send this as a Pull Request and we'll look into it?

**Comment by lorenc-tomasz** [comment]
@cortinico 

I made create different approach to fix also applying custom font family when typing:

```diff
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditHintTypefaceSpan.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditHintTypefaceSpan.java
new file mode 100644
index 0000000..1a4fb45
--- /dev/null
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditHintTypefaceSpan.java
@@ -0,0 +1,23 @@
+package com.facebook.react.views.textinput;
+
+import android.graphics.Typeface;
+import android.text.TextPaint;
+import android.text.style.MetricAffectingSpan;
+
+public class ReactEditHintTypefaceSpan extends MetricAffectingSpan {
+    private final Typeface typeface;
+
+    public ReactEditHintTypefaceSpan(Typeface typeface) {
+        this.typeface = typeface;
+    }
+
+    @Override
+    public void updateDrawState(TextPaint paint) {
+        paint.setTypeface(typeface);
+    }
+
+    @Override
+    public void updateMeasureState(TextPaint paint) {
+        paint.setTypeface(typeface);
+    }
+}
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
index a037077..b3fdcb7 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
@@ -21,6 +21,7 @@ import android.os.Bundle;
 import android.text.Editable;
 import android.text.InputType;
 import android.text.Spannable;
+import android.text.SpannableString;
 import android.text.SpannableStringBuilder;
 import android.text.Spanned;
 import android.text.TextPaint;
@@ -125,9 +126,11 @@ public class ReactEditText extends AppCompatEditText {
   private boolean mOnKeyPress = false;
   private TextAttributes mTextAttributes;
   private boolean mTypefaceDirty = false;
+  private boolean mForceSetTypeFaceOnDraw = false;
   private @Nullable String mFontFamily = null;
   private int mFontWeight = ReactConstants.UNSET;
   private int mFontStyle = ReactConstants.UNSET;
+  private @Nullable Typeface mTypeface = null;
   private boolean mAutoFocus = false;
   private boolean mContextMenuHidden = false;
   private boolean mDidAttachToWindow = false;
@@ -613,10 +616,17 @@ public class ReactEditText extends AppCompatEditText {
 
     mTypefaceDirty = false;
 
-    Typeface newTypeface =
+    mTypeface =
         ReactTypefaceUtils.applyStyles(
             getTypeface(), mFontStyle, mFontWeight, mFontFamily, getContext().getAssets());
-    setTypeface(newTypeface);
+    setTypeface(mTypeface);
+
+    // Ensure the hint uses the same typeface
+    if (getHint() != null) {
+      SpannableString hintSpan = new SpannableString(getHint());
+      hintSpan.setSpan(new ReactEditHintTypefaceSpan(mTypeface), 0, hintSpan.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
+      setHint(hintSpan);
+    }
 
     // Match behavior of CustomStyleSpan and enable SUBPIXEL_TEXT_FLAG when setting anything
     // nonstandard
@@ -628,6 +638,8 @@ public class ReactEditText extends AppCompatEditText {
     } else {
       setPaintFlags(getPaintFlags() & (~Paint.SUBPIXEL_TEXT_FLAG));
     }
+
+    mForceSetTypeFaceOnDraw = true;
   }
 
   // VisibleForTesting from {@link TextInputEventsTestCase}.
@@ -1302,6 +1314,11 @@ public class ReactEditText extends AppCompatEditText {
       BackgroundStyleApplicator.clipToPaddingBox(this, canvas);
     }
 
+    if (mForceSetTypeFaceOnDraw) {
+      mForceSetTypeFaceOnDraw = false;
+      setTypeface(mTypeface);
+    }
+
     super.onDraw(canvas);
   }
 

```

Will try to create PR this week :)

**Comment by lorenc-tomasz** [comment]
Bump the issue

**Comment by dilanbopanna** [comment]
I encountered a similar issue: the placeholder text in TextInput was not applying the custom font. After setting autoCapitalize="none", it started working.
However, for Input fields with type 'password', the problem persists even after setting autoCapitalize="none".

**Comment by sayan-avantai** [comment]
Any update?

**Comment by olegmelnyk123** [comment]
any solution to this ?

**Comment by rifadhkp-circles** [comment]
Any update here?
