### ISSUE TITLE
EXC_BAD_ACCESS in -[RCTSRWebSocket stream:handleEvent:]

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#5198]
Running a react native application in simulator. I saw this after a few hours:
```
* thread #18: tid = 0x201272c, 0x0000000108103d10 libobjc.A.dylib`objc_retain + 16, name = 'com.squareup.SocketRocket.NetworkThread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000108103d10 libobjc.A.dylib`objc_retain + 16
    frame #1: 0x0000000108103d4a libobjc.A.dylib`objc_storeStrong + 32
    frame #2: 0x0000000106be4731 my_app`__copy_helper_block_((null)=0x00007f8948b0e7b0, (null)=0x000000011c563ae8) + 113 at RCTSRWebSocket.m:0
    frame #3: 0x000000010bfdb59d libsystem_blocks.dylib`_Block_copy_internal + 325
    frame #4: 0x000000010bf43e45 libdispatch.dylib`_dispatch_Block_copy + 43
    frame #5: 0x000000010bf47b4a libdispatch.dylib`dispatch_async + 57
  * frame #6: 0x0000000106be3a6b my_app`-[RCTSRWebSocket stream:handleEvent:](self=0x00007f8948979250, _cmd="stream:handleEvent:", aStream=0x00007f8948979bb0, eventCode=NSStreamEventErrorOccurred) + 1611 at RCTSRWebSocket.m:1351
    frame #7: 0x0000000109211024 CoreFoundation`_signalEventSync + 180
    frame #8: 0x000000010924532e CoreFoundation`_cfstream_shared_signalEventSync + 478
    frame #9: 0x00000001091d3011 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #10: 0x00000001091c8f3c CoreFoundation`__CFRunLoopDoSources0 + 556
    frame #11: 0x00000001091c83f3 CoreFoundation`__CFRunLoopRun + 867
    frame #12: 0x00000001091c7e08 CoreFoundation`CFRunLoopRunSpecific + 488
    frame #13: 0x0000000107cdd3a1 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
    frame #14: 0x0000000106be5958 my_app`-[_RCTSRRunLoopThread main](self=0x00007f894841e000, _cmd="main") + 376 at RCTSRWebSocket.m:1620
    frame #15: 0x0000000107d7aeab Foundation`__NSThread__start__ + 1198
    frame #16: 0x000000010c29605a libsystem_pthread.dylib`_pthread_body + 131
    frame #17: 0x000000010c295fd7 libsystem_pthread.dylib`_pthread_start + 176
    frame #18: 0x000000010c2933ed libsystem_pthread.dylib`thread_start + 13
```

**Comment by JakeRawr** [comment]
Not sure if it's related. Sometimes I get this error when I run the app on the simulator. It's after I let the simulator sit for a while. The error doesn't immediately pop up. 

<img width="539" alt="screen shot 2016-01-11 at 10 19 51 am" src="https://cloud.githubusercontent.com/assets/7199499/12242327/4d697532-b84d-11e5-9ce7-508544457898.png">

**Comment by deju** [comment]
@cancan101 I have the problems too!

**Comment by deju** [comment]
@cancan101 Do you have some warning in application? like Warning: Each child in an array or iterator should have a unique "key" prop.  Fix it and will be ok. This work for me.

**Comment by richardtreichel** [comment]
Similar to what @JakeRawr, @deju, and @cancan101 have reported: After running the simulator for a while, this error popped up for me as well. @deju has posted a Stack Overflow question [here](http://stackoverflow.com/questions/34783048/com-squareup-socketrocket-networkthread18-exc-bad-access) (no answers so far though).

**Comment by joshbuchea** [comment]
Same experience here after app is running in the simulator for several hours.

**Comment by danleveille** [comment]
Has anyone seen these crashes on a live, production version of their app? Not sure if I should be worried about submitting to the App Store.

**Comment by richardtreichel** [comment]
@danleveille I have not deployed a production version yet. This error has been appearing for me during development.

**Comment by LiZunYuan** [comment]
hello, in url address append "&dev=false" . This error has not appear.

**Comment by joshbuchea** [comment]
@danleveille 👍 I think you're good. I deployed a production version of a React Native app last week ([My IP](https://itunes.apple.com/app/id1031729525?mt=8)), and I haven't had any crashes. Also, when I bypassed Xcode (with either [react-native-nurse]() or [Fk Xcode](https://github.com/tylerbuchea/fkxcode)), the issue did not seem to present itself.

**Comment by danleveille** [comment]
@joshbuchea Yep, same here. No crashes on the App Store version. :)

**Comment by epaga** [comment]
If it's the same problem (looks like it is), it's best to upvote the issue at Product Pains: https://productpains.com/post/react-native/crash-in-rctsrwebsocketm

**Comment by javache** [comment]
I didn't fix the underlying issue here, but it seems it was exacerbate by a really short timeout in React devtools. I increased the timeout in v25 https://github.com/facebook/react-native/commit/b00c77af8066cf74f05ccaca2b08c8952e1ae8a6

**Comment by lacker** [comment]
Since there hasn't been any activity since that last comment improving the timeout, it seems like in practice this is no longer an issue. I'm going to close this issue but folks should feel free to open a new one if a problem like this exists in newer RN versions.
