### ISSUE TITLE
New Architecture not enabled in android

### ISSUE THREAD

**Issue by FrancMihani** [facebook/react-native#52375]
### Description

When  initializing a new app, in android even why the `newArchEnabled=true  hermesEnabled=true`, app runs using the Legacy Architecture.

### Steps to reproduce

1. react-native run-android
2. open debugger
3. see the message: `The app is running using the Legacy Architecture`

### React Native Version

0.80.1

### Affected Platforms

Runtime - Android

### Areas

Fabric - The New Renderer

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.5
  CPU: (8) arm64 Apple M1
  Memory: 114.80 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.14.0
    path: ~/.nvm/versions/node/v20.14.0/bin/node
  Yarn:
    version: 4.5.1
    path: ~/.nvm/versions/node/v20.14.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.14.0/bin/npm
  Watchman:
    version: 2025.06.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/francmihani/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
      - "36"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
      - 36.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2025.1 AI-251.25410.109.2511.13665796
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/francmihani/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 19.0.0
    wanted: 19.0.0
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.80.1
    wanted: 0.80.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
2025-07-02 16:21:31.973  2697-6432  WindowManager           system_server                        E  win=Window{7b7f1eb u0 com.pluggo/com.pluggo.MainActivity} destroySurfaces: appStopped=true cleanupOnResume=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6509 com.android.server.wm.ActivityRecord.destroySurfaces:6490 com.android.server.wm.ActivityRecord.notifyAppStopped:6554 com.android.server.wm.ActivityRecord.activityStopped:7142 com.android.server.wm.ActivityClientController.activityStopped:258 android.app.IActivityClientController$Stub.onTransact:613 com.android.server.wm.ActivityClientController.onTransact:136 
2025-07-02 16:22:31.206  2697-6432  WindowManager           system_server                        E  win=Window{7b7f1eb u0 com.pluggo/com.pluggo.MainActivity} destroySurfaces: appStopped=true cleanupOnResume=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6509 com.android.server.wm.ActivityRecord.destroySurfaces:6490 com.android.server.wm.ActivityRecord.notifyAppStopped:6554 com.android.server.wm.ActivityRecord.activityStopped:7142 com.android.server.wm.ActivityClientController.activityStopped:258 android.app.IActivityClientController$Stub.onTransact:613 com.android.server.wm.ActivityClientController.onTransact:136
```

### MANDATORY Reproducer

https://github.com/FrancMihani/react-native-new-arch-not-enabled-report

### Screenshots and Videos

![Image](https://github.com/user-attachments/assets/114ec19c-e456-4e45-9d88-548a68902007)

**Comment by devanshsaini11** [comment]
@FrancMihani It seems like this issue might be related to your setup. Could you try verifying it on a clean build? Additionally, you can try cleaning the Metro cache by running `yarn start --reset-cache` to see if that resolves the issue.

**Comment by FrancMihani** [comment]
@devanshsaini11 I tried with `--reset-cache`, still the same problem. Is there anything I can try to enable newArch, in the native side?

**Comment by dentemm** [comment]
I'm seeing this same warning on iOS, RN version 0.80. All my dependencies support the new architecture, and I cannot figure out where it's coming from. 

Could it be that the warning is incorrect on v0.80?

**Comment by cipolleschi** [comment]
I just tried to create an app using the following steps:

```
npx @react-native-community/cli init RN080 --version latest --skip-install
cd RN080
yarn install
yarn android
```

And it starts with the New architecture enabled as you can see from the `fabric: true` log in the console:

<img width="1632" height="952" alt="Image" src="https://github.com/user-attachments/assets/b10318b6-9689-42dd-9b8f-3ca9255b4e49" />

It might be that you guys has some system level setting that forces the legacy architecture.
For android it might be some other `build.gradle` file that specifies that the `newArch` is off.
For iOS, you might have `ENV['RCT_NEW_ARCH_ENABLED'] = 0` hardcoded in the Podfile, for example, or in a zshrc/bashrc file.

**Comment by spyshower** [comment]
Could it be that the log message itself is reporting falsely that it uses legacy arch?

**Comment by FrancMihani** [comment]
@cipolleschi what system level settings could affect the app to start in the old arch ?

**Comment by trickyc0d3r** [comment]
SAme problem (((

**Comment by LJoel23** [comment]
I ran into the same issue, and in my case, the cause was a conflicting setting in my global Gradle properties.

💡 Solution:
Check your ~/.gradle/gradle.properties file or local.properties — I had the following line there:

newArchEnabled=false

This overrides the project-level setting and disables the new architecture even if it's enabled in your project’s gradle.properties.

✅ After removing or updating this value in the global config, the issue was resolved.

Hope this helps others who might be stuck on the same problem!

**Comment by cipolleschi** [comment]
@FrancMihani what @LJoel23 is saying. Check your `~/.gradle/gradle.properties` or your `local.properties` files

**Comment by cortinico** [comment]
> [@cipolleschi](https://github.com/cipolleschi) what system level settings could affect the app to start in the old arch ?

To verify if this is the case, you can do the following:

```
cd android && ./gradlew installDebug -PnewArchEnabled=true
```

That will override any other property you might have set somewhere else.

Please report back if this was the issue @FrancMihani

**Comment by FrancMihani** [comment]
@LJoel23  @cortinico @cipolleschi thank you guys, yes that was the problem.

**Comment by Kushagraagarwal** [comment]
Facing the same issue on 0.81.1, have hardcoded ENV['RCT_NEW_ARCH_ENABLED'] = '1', but still seeing this warning only on iOS
