### ISSUE TITLE
[Andriod] Can't build RN@0.80.x with a new library (codegen have to be run manually)

### ISSUE THREAD

**Issue by retyui** [facebook/react-native#52955]
### Description

After upgrade to RN@0.80.2, Android builds start to fail with the next error:

```
> Task :app:configureCMakeRelWithDebInfo[x86_64] FAILED
C/C++: CMake Error at /Users/i/tmp/is1/Rn80/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:9 (add_subdirectory):
C/C++:   add_subdirectory given source
C/C++:   "/Users/i/tmp/is1/Rn80/node_modules/react-native-awesome-library/android/build/generated/source/codegen/jni/"
C/C++:   which is not an existing directory.
```

So I have to run `./android/gradlew generateCodegenArtifactsFromSchema -p android` first to fix it

### Steps to reproduce

you can use the next cmds to reproduce the issue 
```bash
npx create-react-native-library@latest react-native-awesome-library # create a simple `Turbo module`
npx @react-native-community/cli init Rn80

cd Rn80
yarn add file:../react-native-awesome-library # please use yarn v1
./android/gradlew assembleRelease -p android -PreactNativeArchitectures=x86_64
```

### React Native Version

0.80.2

### Affected Platforms

Runtime - Android

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.4.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 846.58 MB / 36.00 GB
  Shell:
    version: 4.0.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 20.19.3
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2025.06.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/davyd.narbutovich/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2025.1 AI-251.25410.109.2511.13752376
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/davyd.narbutovich/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 19.1.1
    wanted: 19.1.1
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.80.2
    wanted: 0.80.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
> Task :app:configureCMakeRelWithDebInfo[x86_64] FAILED
C/C++: CMake Error at /Users/davyd.narbutovich/tmp/is1/Rn80/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:9 (add_subdirectory):
C/C++:   add_subdirectory given source
C/C++:   "/Users/davyd.narbutovich/tmp/is1/Rn80/node_modules/react-native-awesome-library/android/build/generated/source/codegen/jni/"
C/C++:   which is not an existing directory.
C/C++: Call Stack (most recent call first):
C/C++:   /Users/davyd.narbutovich/tmp/is1/Rn80/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:94 (include)
C/C++:   CMakeLists.txt:31 (include)
C/C++: CMake Error at /Users/davyd.narbutovich/tmp/is1/Rn80/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:97 (target_link_libraries):
C/C++:   Cannot specify link libraries for target "react_codegen_AwesomeLibrarySpec"
C/C++:   which is not built by this project.
C/C++: Call Stack (most recent call first):
C/C++:   CMakeLists.txt:31 (include)

[Incubating] Problems report is available at: file:///Users/davyd.narbutovich/tmp/is1/Rn80/android/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.
```

### MANDATORY Reproducer

https://github.com/please_use_commands_above

**Comment by cortinico** [comment]
This is fixed by:
- #52803 

We should cherry pick that inside 0.80 also. Here the pick request:

- https://github.com/reactwg/react-native-releases/issues/1069

**Comment by Francesco-Voto** [comment]
@cortinico sorry to ping you in a closed issue, any chance we can have this pick released for 0.80.x any time soon?

**Comment by cortinico** [comment]
@Francesco-Voto It will be included in the next 0.80 we'll publish soon

**Comment by sindiAsx** [comment]
to me this doesn't happen just with a new library, but with multiple existing libraries once I upgraded from 0.73 to 0.80.2
I can't build Android at all because of this issue and at the same time can't jump to 0.81 for compatibility issues
@cortinico please keep us posted and maybe reopen this issue?

**Comment by sindiAsx** [comment]
any news here? @cortinico or anyone with a workaround?

**Comment by cortinico** [comment]
> any news here? [@cortinico](https://github.com/cortinico) or anyone with a workaround?

This is fixed in 0.81.

It will be included in 0.80 as soon as we do a point release for it

**Comment by liangskyli** [comment]
0.80 not fix this issues, i must upgrade to 0.81?

**Comment by Stautvis** [comment]
It happens that not all projects run the `:generateCodegenArtifactsFromSchema` task before running the `app:configureCMakeRelWithDebInfo` task. Try adding this code snippet to the `android/app/build/gradle` file:

```gradle

afterEvaluate {
  tasks.matching { it.name.startsWith('configureCMakeRelWithDebInfo') }.configureEach { cmakeTask ->
    rootProject.allprojects.each { project ->
      if (project.tasks?.findByName("generateCodegenArtifactsFromSchema")) {
        println "CUSTOM TASK DEPENDENCY → ${cmakeTask.name} depends on :${project.name}:generateCodegenArtifactsFromSchema"
        cmakeTask.dependsOn(":${project.name}:generateCodegenArtifactsFromSchema")
      }
    }
  }
}

```

**Comment by cortinico** [comment]
> 0.80 not fix this issues, i must upgrade to 0.81?

Yes please upgarde to 0.81

**Comment by rokkoo** [comment]
I just updated to `0.80.3` after the fix but the problem still there, so the only solutions is justo upgrade to `v0.81` ?  Sorry for ping when is closed
