### ISSUE TITLE
[Android] Error after upgrading to 0.18/0.18.1 & clean install on device/emulator

### ISSUE THREAD

**Issue by pewh** [facebook/react-native#5570]
Upgrading RN to 0.18/0.18.1 and got error below on real device/genymotion.

![screenshot_2016-01-27-11-01-46_com pazeonative](https://cloud.githubusercontent.com/assets/881358/12603471/986731b0-c4e5-11e5-9727-ac75ba1bc7f5.png)
Click 'Reload JS' or press back button will throw new error.

![screenshot_2016-01-27-11-01-50_com pazeonative](https://cloud.githubusercontent.com/assets/881358/12603473/a1c8bfd0-c4e5-11e5-86e7-c799767e13fd.png)

Sometimes the error show 'Unable to connect packager'. So I think I should configure IP server in 'Dev Settings'.
I can open Dev Menu, but when I click 'Debug in Chrome' or 'Dev Settings', the app exit immediately. My console still running `react-native start` and no error.

```
[11:07:09] <START> Building Dependency Graph
[11:07:11] <START> Crawling File System
[11:07:11] <START> Loading bundles layout
[11:07:11] <END>   Loading bundles layout (1ms)

React packager ready.

[11:08:51] <END>   Crawling File System (100828ms)
[11:08:51] <START> Building in-memory fs for JavaScript
[11:08:52] <END>   Building in-memory fs for JavaScript (723ms) [11:08:52] <START> Building in-memory fs for Assets
[11:08:53] <END>   Building in-memory fs for Assets (747ms)
[11:08:53] <START> Building Haste Map
[11:08:53] <START> Building (deprecated) Asset Map
[11:08:54] <END>   Building (deprecated) Asset Map (421ms)
[11:09:02] <END>   Building Haste Map (9332ms)
[11:09:02] <END>   Building Dependency Graph (113372ms)
```

Tested on Mac and Windows machine.

**Comment by MrPluto** [comment]
+1

**Comment by MrPluto** [comment]
i solved by restart my package server. maybe you can have a try

**Comment by pewh** [comment]
Yes, it's work on emulator by restart package server, open app, then change 'Debug server host & port device'.
But it doesn't work on my phone. It's exit immediately if I click 'Debug server host & port device'.

Tested on phone: Xiaomi Redmi Note 3G (Android 4.4.2)
Previously no error occured on RN < 0.18.

**Comment by MrPluto** [comment]
i think it's the cache package,do you try rm all react-* in you $TMPDIR dir.and restart you server?  it works on my android phone

**Comment by pewh** [comment]
Hei @MrPluto, thanks for the response.
Unfortunately, it still doesn't work :/
What I've done is:
1. `cd $TMPDIR`
2. `rm react-*`
3. `cd /go/to/project/folder`
4. `react-native start`
5. check the app & still doesn't work
6. `cd android/ && ./gradlew clean && cd .. && react-native run-android`
7. `react-native start`
8. check again & still error :sob:

I've tested to my friend's phone (with the same Android version but Acer), and show the same errors.

**Comment by MrPluto** [comment]
try  just stoping  the package server and run-android directly ?

**Comment by pewh** [comment]
Still same error like the first post. It's weird because I can make it work and access 'Debug server host & port device' without crash on emulator.
Unfortunately, I don't have any iOS device. I also work on OS X Mavericks (10.9.5), so I'm unable to open Xcode 7 which is minimum version for setup iOS app.

**Comment by pewh** [comment]
I've experiment by creating init new RN 0.18 project and it's work on my device. It seems the problem caused by third-party plugins. I need more experiment to figure out the problem & will post it later.

**Comment by MrPluto** [comment]
can you tell me what's plugins you used?

**Comment by pewh** [comment]
```
  "dependencies": {
    "@remobile/react-native-splashscreen": "^1.0.3",
    "immutable": "^3.7.6",
    "moment": "^2.10.6",
    "react": "^0.14.6",
    "react-native": "^0.18.1",
    "react-native-accordion": "^0.2.4",
    "react-native-action-button": "^1.1.1",
    "react-native-activity-android": "^0.17.3",
    "react-native-dropdown-android": "^0.0.9",
    "react-native-fs": "^1.1.0",
    "react-native-gcm-android": "^0.1.9",
    "react-native-image-picker": "^0.10.0",
    "react-native-material-design": "^0.3.1",
    "react-native-mimetype": "0.0.7",
    "react-native-router-flux": "^2.1.3",
    "react-native-simple-store": "^0.1.0",
    "react-native-system-notification": "^0.0.8",
    "react-native-tabs": "^0.1.10",
    "react-redux": "^3.1.0",
    "redux": "^3.0.5",
    "redux-logger": "^2.3.1",
    "redux-thunk": "^1.0.3"
  },
```

**Comment by MrPluto** [comment]
i am not sure whether the plugins issue or not, i still think it's about the package. did you check the file when you upgrade? i mean they changed a lot android files in 0.18. sorry can't do any other help. please let me know if you catch this error :pray:

**Comment by pewh** [comment]
No problem, @MrPluto.
I've tried several experiments and now I've fix this problem by deleting file `android/app/src/main/assets/index.android.bundle`. I have been generate this file by doing `curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"` when I'm working project with RN 0.14.

You right. They changed a lot android files and also mechanism on bundling the script in 0.18. Anyway thanks for your assist :+1:

**Comment by MrPluto** [comment]
:beers:
