### ISSUE TITLE
NavigationExperimental can not found in React Native 0.20.0

### ISSUE THREAD

**Issue by niklaus0823** [facebook/react-native#6003]
code in examples/UIExplorer/NavigationExperimental/NavigationExampleTabBar.js line 18

<code>
var {
  NavigationExperimental,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} = React;
</code>

And in `react-native.js`, i can't find this component

Has someone find this problem?

**Comment by gre** [comment]
```
var NavigationExperimental = require("NavigationExperimental");
```

**Comment by satya164** [comment]
@gre We shouldn't encourage people to use this pattern.

**Comment by gre** [comment]
true. but this is a workaround

**Comment by satya164** [comment]
@gre If people start using this, if we change something, their code will break.

**Comment by gre** [comment]
@satya164 not sure to get what you meant. In both cases if you rename `NavigationExperimental` into something else, code will break, right?

Personally I prefer my code to break at compile time that having bad surprise at runtime.

`import {NavigationExperimental} from "react-native"` *oops NavigationExperimental undefined, breaks at runtime when you start using it.*

`import NavigationExperimental from "NavigationExperimental"` *breaks at compile time. packager explicitely will say it doesn't exist* (as soon as when the thing is renamed).


But I agree that relying on an internal require() mecanism is not recommended. 
in the meantime we have no other choice for NavigationExperimental.

**Comment by satya164** [comment]
> @satya164 not sure to get what you meant. In both cases if you rename NavigationExperimental into something else, code will break, right?

@gre When we rename, we will still expose it with the same name and show a warning to help people to transition to the new one. If people directly use this, and we change it, it'll just break without no helpful warnings.

> Personally I prefer my code to break at compile time that having bad surprise at runtime.

Code breaking is ok. But it should give helpful error messages so that people can fix whatever broke. Right now it doesn't tell you how to fix it either. And that's a problem, as the user reported above.

> But I agree that relying on an internal require() mecanism is not recommended. 
in the meantime we have no other choice for NavigationExperimental.

You can always install from master, or we're soon releasing an RC which you can try out.

For now I'm closing this issue as it has been fixed in master.

**Comment by bmeraz-phunware** [comment]
Satya, 
I'm still getting this error. What do you recommend? I'm using the latest versions of RN.
![screen shot 2016-02-26 at 2 46 20 pm](https://cloud.githubusercontent.com/assets/10731056/13367477/d2f985b6-dc97-11e5-82e8-8c9a2263dbd6.png)
