### ISSUE TITLE
Firebase doesn't work with RN 0.22.0

### ISSUE THREAD

**Issue by milasevicius** [facebook/react-native#6566]
Hello, I am getting 
`Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference`.
Package.json: `"firebase": "^2.4.1", "react": "^0.14.7", "react-native": "^0.22.0" `

**Comment by holyxiaoxin** [comment]
I am getting the same error.  I realise that I only get this error when I'm call 
`this.ref = new Firebase("https://somevalidapp.firebaseio.com/");`

This was working at v0.21 prior to v0.22 upgrade.

**Comment by holyxiaoxin** [comment]
I have checked that `~v0.21` does not cause this. `^v0.22` indeed causes this.

**Comment by asubota** [comment]
same here

**Comment by milasevicius** [comment]
+1

**Comment by abehaskins** [comment]
@jwngr - any thoughts on this?

**Comment by jwngr** [comment]
No, but @mikelehen is probably a better person to ask.

Could either of you provide a minimal repro? Or is calling `new Firebase` anywhere in your code literally all you need to do make this happen?

**Comment by holyxiaoxin** [comment]
Commening out `new Firebase` works alright. Adding it back in will throw the null object reference error.

**Comment by mikelehen** [comment]
Anybody have a stacktrace for the error handy by chance?

**Comment by phonghho** [comment]
Not sure if it's related, but this is what happens when I just import firebase into my react native project using 0.22
<img width="423" alt="screen shot 2016-03-22 at 10 16 03 pm" src="https://cloud.githubusercontent.com/assets/107421/13976466/48bfce7e-f07d-11e5-8446-46921686183e.png">

**Comment by mkonicek** [comment]
@mikelehen Would it be possible for you to set up CI that tests against every commit made to React Native master? That way you could ping us quickly when there's a commit that breaks the Firebase integration, and since we'd have a single commit it should be easy to fix.

Alternatively, do you test the React Native RC releases as soon as they come out?

**Comment by holyxiaoxin** [comment]
@mkonicek do you mean [this](https://travis-ci.org/facebook/react-native/branches)?

**Comment by hyphenbash** [comment]
@phonghho I have exactly the same error on 0.22. However, I setup a complete new project with 0.21 as well and the moment i import firebase, it throws the same error.

**Comment by hyphenbash** [comment]
I have tested earlier version of react-native. Surprisingly, the issue doesn't occur on 0.18

**Comment by jwngr** [comment]
Possibly related to [this thread on `use strict` + Firebase](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/gFtK1YoRUoE/EF5nW8AYBQAJ)...

**Comment by keeth** [comment]
This is related to babel-preset-react-native 1.5.3 enabling strict mode.  I hit this bug in 0.21 when preset 1.5.3 was released (not found until CI picked up the new patch version and broke our app in production :cry: ).  My workaround is:

echo node_modules/firebase/lib/firebase-web.js > .babelignore

(restart packager, etc)

For more context:

https://github.com/facebook/react-native/commit/36893ecfa06797a18f4ae892905101d5dec31e26#commitcomment-16820362

**Comment by satya164** [comment]
@keeth Can you create a new issue regarding a custom preset not overriding the default one?

As mentioned in https://github.com/facebook/react-native/issues/6566#issuecomment-200485343 , the correct way to fix this is by adding `node_modules/firebase/` to your `.gitignore`.

We should eventually ship a pre-built version of React Native and avoid transforming files under `node_modules`. cc @martinbigio

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by keeth** [comment]
@satya164 yep, just filed #6611

**Comment by justinr1234** [comment]
@satya164 - @keeth  workaround doesn't work for me. Still broken.

**Comment by satya164** [comment]
You need to run the packager with `--reset-cache` after that. Otherwise it won't work.

**Comment by justinr1234** [comment]
@satya164 I have done that, no dice. I've restarted the packager, deleted all xcode caches, tried putting the ignore in my babelrc under "ignore", tried just ignore of "firebase-web.js" ... running out of ideas

**Comment by jwngr** [comment]
The `.babelignore` file works very similar to the `.gitignore` file. You should make sure that the paths you put in the `.babelignore` file are relative paths from the `.babelignore` file. So, if your `node_modules/` directory is in the same directory of your `.babelignore` file and `node_modules/firebase` exists, then adding `node_modules/firebase` should solve your problem. You also need to make sure the `.babelignore` file is actually getting picked up by Babel. Make sure you aren't overriding it anywhere and that it is at the directory where you are doing your build.

**Comment by justinr1234** [comment]
@jwngr verified all that, barring anything I'm missing. I double checked by putting nonsense in my file and it threw a compilation error in the react packager.

The only thing I might be confused by is what happens with doing "bundle" instead of the packager server?

**Comment by satya164** [comment]
@justinr1234 Unfortunately with the bundler, you need to use `--resetCache`

**Comment by justinr1234** [comment]
@satya164 No luck modifying the react-native-xcode.sh

```
$NODE_BINARY "$REACT_NATIVE_DIR/local-cli/cli.js" bundle \
  --entry-file index.ios.js \
  --platform ios \
  --resetCache \
  --dev $DEV \
  --bundle-output "$DEST/main.jsbundle" \
  --assets-dest "$DEST"
```

```
$NODE_BINARY "$REACT_NATIVE_DIR/local-cli/cli.js" bundle \
  --entry-file index.ios.js \
  --platform ios \
  --reset-cache \
  --dev $DEV \
  --bundle-output "$DEST/main.jsbundle" \
  --assets-dest "$DEST"
```

**Comment by satya164** [comment]
@justinr1234 Pretty sure it's caching issue. @martinbigio Any idea here?

**Comment by justinr1234** [comment]
@satya164 Where would the "cache" be stored? I can manually go delete it.

Also searched my whole system for anything related to .jsbundle and removed it before building.

I'm also running this manually with gulp before trying to build in xcode:
```
gulp.task('clear-react-packager-cache', () => {
  // Clear react-packager cache
  const tempDir = os.tmpdir();

  const cacheFiles = fs.readdirSync(tempDir).filter(
    fileName => fileName.indexOf('react-packager-cache') === 0
  );

  cacheFiles.forEach(cacheFile => {
    const cacheFilePath = path.join(tempDir, cacheFile);
    fs.unlinkSync(cacheFilePath);
    console.log('Deleted cache: ', cacheFilePath);
  });

  if (!cacheFiles.length) {
    console.log('No cache files found!');
  }
});
```

**Comment by satya164** [comment]
@justinr1234 It used to be in `$TMPDIR/react*`, but not sure if it's still the case.

**Comment by justinr1234** [comment]
Tried the aforementioned xcode bundler change, and the following:

```
watchman watch-del-all
node_modules/react-native/packager/packager.sh --reset-cache
rm -fr $TMPDIR/react-*
```

**Comment by lneves12** [comment]
I tried everything said in this issue and still having the same problem. It runs well on IOS but fails on Android.

<img width="305" alt="rn-firebase-error" src="https://cloud.githubusercontent.com/assets/1140720/14057855/98425032-f304-11e5-95e8-30dc0032fb1f.png">

**Comment by mikelehen** [comment]
Thanks for the callstack @lneves12!  Very helpful.  It looks to me like that was a bug in react native fixed by [this commit](https://github.com/facebook/react-native/commit/13c49e200615d9f04a272c3d3d76f8b6fc56417c).

Can you try updating your react-native dependency to 0.23.0-rc1 which I think has the fix?  Thanks!

**Comment by lneves12** [comment]
This issue seems to be fixed with the version 0.23.0-rc1 :+1:  Thanks :)

**Comment by mikelehen** [comment]
Great to hear!  Thanks for confirming.

**Comment by rsflow** [comment]
Hey @mikelehen,
So I changed the source code directly on `node_modules/react-native` but the error still persist. 
Maybe because of this #4698.

**Comment by mikelehen** [comment]
Hey @rsflow, this issue has two different problems being discussed.  I'm guessing you're hitting the property 'navigator' of undefined one?  Can you try keeth's fix above?  https://github.com/facebook/react-native/issues/6566#issuecomment-200485343

**Comment by giacomorebonato** [comment]
For me the error is still present in 0.23.0-rc1

**Comment by mikelehen** [comment]
@giacomorebonato Which error?  This issue has conflated two separate problems.

**Comment by rsflow** [comment]
Hey @mikelehen, no I'm getting the `Timing` error.

**Comment by giacomorebonato** [comment]
This is the error and my dependencies

```javascript
"firebase": "^2.4.1",  
"react": "^0.14.7",  
"react-native": "^0.23.0-rc1",  
"react-native-router-flux": "^3.2.3",  
"realm": "^0.11.0",  
"tcomb-form-native": "^0.4.0"`  
```

<img width="390" alt="screen shot 2016-03-27 at 20 44 10" src="https://cloud.githubusercontent.com/assets/630796/14067402/1e034f02-f45c-11e5-8f26-8bbede17f44d.png">

**Comment by mikelehen** [comment]
@rsflow Did you run "npm install" after updating the dependency in your package.json?

@giacomorebonato Did you try keeth's fix above?  https://github.com/facebook/react-native/issues/6566#issuecomment-200485343

**Comment by rsflow** [comment]
@mikelehen I changed the file directly on the `node_modules/react-native` directory, I didn't change the RN version.

**Comment by giacomorebonato** [comment]
@mikelehen same error after creating babelignore. I am available for more test

**Comment by hmm29** [comment]
does firebase still not work with 0.22.2?

**Comment by dlidstrom** [comment]
Works fine with `0.23.0-rc1`.

**Comment by gojohnnygo** [comment]
@rsflow / @giacomorebonato - Not sure if you guys are still having issues, but this did the trick for me.

1. `react-native init MyProject`
2. 'npm uninstall react-native --save`
3. 'npm install react-native@0.23.0-rc1`
4. 'npm install firebase --save`
5. Add `const Firebase = require('firebase');` to index.ios.js 
6. Run project from Xcode

**Comment by rsflow** [comment]
Hey @gojohnnygo thanks for your help. I did change my `node_modules/react-native` files manually but the error is the same .. I will update it to `23` now and probably it will work.

**Comment by justinr1234** [comment]
@gojohnnygo Worked for me, but now my SideMenu component won't work :cry: ... but that's another issue to solve :smile: thanks for your help!

**Comment by grabbou** [comment]
@facebook-github-bot answered 

Looks like most of the issues has been resolved. If you encounter similar problem, please try the steps above outlined by the community and in case no-one works for you - let us know to reopen :)

**Comment by mkonicek** [comment]
Ah, it indeed looks like the bot is not working!

**Comment by mkonicek** [comment]
@facebook-github-bot answered

**Comment by steida** [comment]
Should be closed imho.

**Comment by jean9696** [comment]
Hi, sorry to reopen an old issue but I have the exact same problem.. I tried everything said above but still the same issue... I'm on windows for android, I'm using redux... Here are my dependencies : 
```json
 "dependencies": {
    "eslint": "^3.19.0",
    "firebase": "^4.1.1",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.2",
    "react-native-android-back-button": "^0.3.0",
    "react-native-barcodescanner": "^3.1.1",
    "react-native-material-ui": "^1.11.1",
    "react-native-vector-icons": "^4.1.1",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-eslint": "^6.1.2",
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.0.1",
    "eslint-plugin-react-native": "^2.3.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6",
    "remote-redux-devtools": "0.5.0"
  },
```

**Comment by mikelehen** [comment]
FYI- This issue is a year old, has some 40+ comments on it, and was used to discuss at least 2 completely separate issues.  You'll have much better luck opening a new issue with specific repro steps and error details.  Feel free to cc me on it so I see it.
