### ISSUE TITLE
Hot reloading while debugging in chrome fails with "cannot read property length of undefined"

### ISSUE THREAD

**Issue by kkirby** [facebook/react-native#7199]
If I modify a file and save it, the function `acceptAll` fails with `Cannot read property 'length' of undefined`. It appears to only happen when debugging in chrome.

**Comment by grabbou** [comment]
cc: @martinbigio

**Comment by martinbigio** [comment]
Hmm couldn't repro on master. Which version of react-native are you running?

**Comment by kkirby** [comment]
Sorry. I meant to include this in an edit yesterday since I realized I forgot to.

react-native-cli: 0.2.0
react-native: 0.24.1

Running on OS X 10.10.5
Chrome 50.0.2661.86 (64-bit)

I'm actually completely unable to reproduce this issue. I'm not sure if we'd want to keep it open incase it pops back up, or just close it and if it comes back I can add more info.

**Comment by martinbigio** [comment]
Thanks for trying to repro again. As per the source code this could only be happening when something that's not required by a react component is hot reloaded. I'm glad you reported it!.

The only line on `acceptAll` that could fail with the provided error is this one: https://github.com/facebook/react-native/blob/887c275bcfe1525665732d14062ed3a571527cb2/packager/react-packager/src/Resolver/polyfills/require.js#L163

To fix the very rare edge case we could simply turn the conditional from:

```
if (inverseDependencies[notAccepted[i]].length === 0) {
  return false;
}
```

into:

```
if (!inverseDependencies[notAccepted[i]] || inverseDependencies[notAccepted[i]].length === 0) {
  return false;
}
```

This way if the file that it's being tried to be hot reloaded but couldn't be accepted doesn't have any parent we bail.

I think this could repro if you try to hot reload the root of the bundle (which is not a react component). Do you mind trying to repro with it?

**Comment by grabbou** [comment]
@martinbigio shall we print a message like Webpack that a full reload is required? (not sure if we do already)

**Comment by martinbigio** [comment]
@grabbou we're not doing that but would be great. We'd need to create a native module with both Android and iOS implementations to display a message if this line returns false: https://github.com/facebook/react-native/blob/887c275bcfe1525665732d14062ed3a571527cb2/packager/react-packager/src/Resolver/polyfills/require.js#L147

**Comment by grabbou** [comment]
Okay, sounds great! I'll try to dive in into HMR internals and see if I can figure out an easy way to make that working. We could probably forward that to YellowBox.

**Comment by martinbigio** [comment]
Oh true, we could simply do `console.warn('....');` if `acceptAll` returns `false` on the line I mentioned above :). Looking forward for your PR ;).

**Comment by grabbou** [comment]
I am actually getting yet another error `undefined is not an object (evaluating mod.factory.call)` with the following:

index.ios.js
```
require('./UIExplorerApp') // this calls AppRegistry on its own
require('./dummyFile');
```
Dummy file has a console.log - any change to it causes the above crash.

**Comment by grabbou** [comment]
Also another thing we might improve is:
```
TypeError: Cannot read property 'dependencyOffsets' of undefined
    at HMRBundle.addModule (HMRBundle.js:28:7)
    at index.js:274:18
    at Array.map (native)
    at finalizeBundle (index.js:273:28)
    at index.js:420:13
    at tryCallOne (/Users/grabbou/Repositories/react-native-oss/node_modules/promise/lib/core.js:37:12)
    at /Users/grabbou/Repositories/react-native-oss/node_modules/promise/lib/core.js:123:15
    at flush (/Users/grabbou/Repositories/react-native-oss/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
```
Happens when I cut the content of entry file, save it, paste old content and hit save

**Comment by tadeuzagallo** [comment]
Yep, that makes sense, HMR will re-run the factory, but at that time it has already been released... maybe we can release it only if `!__DEV__`?! That'd keep the nice memory win we had in production builds and not break the DX...

**Comment by martinbigio** [comment]
> maybe we can release it only if !__DEV__?! 

Sounds good to me.

In regards the other error, it happens because meta is `undefined` though not sure why that's the case.

@bestander what's the ETA for the e2e test?

**Comment by grabbou** [comment]
@tadeuzagallo is that something you'd like to take care of? I could potentially include it in the HMR PR I am planning to send out soon(ish)

**Comment by martinbigio** [comment]
Yeah, that makes sense. Assets have no dependencies so besides `AssetsRegistry` so it's not crazy to have an `undefined` meta attribute. This has recently changed though as this attribute was always defined a couple of weeks ago. I haven't been following the changes done to the packager lately but replacing https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/packager/react-packager/src/Bundler/HMRBundle.js#L28 for this should fix the issue:

```
moduleTransport.meta ? moduleTransport.meta.dependencyOffsets : []
```

**Comment by kkirby** [comment]
Totally my bad, I actually am able to re-create the issue. I forgot to enable hot reloading (I had enabled live reloading). At any rate, I am unable to re-create the issue using the default template (`react-native init AwesomeProject`). So it's certainly something with my project. I super simplified my `index.ios.js` file:

```javascript
import React, {View, Text, AppRegistry} from 'react-native';

const AwesomeProject = () => (
	<Text></Text>
);

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

And the issue was still occurring. Even after restarting the server. When I have some more time I'll dig into this more.

**Comment by bestander** [comment]
| @bestander what's the ETA for the e2e test?

@martinbigio, we already have a simple Hot Reloading test already running on CI https://github.com/facebook/react-native/blob/master/scripts/android-e2e-test.js#L90

It just checks the most simple scenario of HMR.
But we don't test Chrome Debugging beyond just switching it from dev menu.

Do you reckon this bug would be called if we had an app test executing both HMR and Chrome Debugging?

**Comment by martinbigio** [comment]
@bestander I'm not sure what the bug is because I couldn't repro so I wouldn't know :/.

@kkirby could you try changing the line I mentioned above and see if it fixes the problem? I don't see how this could only repro when running on the debugger.

https://github.com/facebook/react-native/blob/887c275bcfe1525665732d14062ed3a571527cb2/packager/react-packager/src/Resolver/polyfills/require.js#L163

**Comment by martinbigio** [comment]
@grabbou any progress on the hot reloading issues? :)

**Comment by kkirby** [comment]
@martinbigio Your code patch did not fix the issue:

```javascript
if (!inverseDependencies[notAccepted[i]] || inverseDependencies[notAccepted[i]].length === 0) {
  return false;
}
```

The error is occurring on this line:

```javascript
function acceptAll(modules, inverseDependencies) {
    if (modules.length === 0) { // < --- This line. modules is undefined.
```

**Comment by fab1an** [comment]
I have this error without debugging in chrome. My index.android.js:

```javascript
'use strict';

import {AppRegistry} from 'react-native';
import {App} from './App';

AppRegistry.registerComponent('App', () => App);
```

My App.jsx:
```javascript
class Base extends React.Component {
}

class App extends Base {
}
```

When I let App extends from `React.Component` it works fine, when I change something in App's render method. When I let it extend from my BaseClass, I get the error upon change.

**Comment by kyle-ssg** [comment]
I found the same as above - it seems your components have to directly extend React.Component ?

**Comment by fab1an** [comment]
With the new version (0.25.1, react 0.14.8) the crash seems to have disappeared, but reload won't work with extension.

**Comment by lacker** [comment]
This issue now appears to be an agglomeration of related problems, some of which are fixed, so I'm going to close this issue. If people run into similar bugs then I encourage the opening of new issues to report them.
