### ISSUE TITLE
[Modal-StatusBar-Android] Statusbar shows up with setHidden(true)

### ISSUE THREAD

**Issue by duketwo** [facebook/react-native#7474]
While the modal component is open on an android device with StatusBar.setHidden(true) the StatusBar still shows up. 

Is this intended? If yes, is there any workaround?

Edit: On iOS the StatusBar remains hidden when a modal component is open.

**Comment by janicduplessis** [comment]
Looks like a bug, I never tested StatusBar + Modal, I'll take a look at it when I get some time.

**Comment by sktaylor** [comment]
Any idea about this? I lose background color and translucent properties as well. It looks pretty bad.

**Comment by timvanp** [comment]
I have the same problem, iOS works fine indeed

**Comment by nihgwu** [comment]
check my comments on #8627 if have any help

**Comment by ggordan** [comment]
Any updates on this?

**Comment by benhurott** [comment]
I have the same problem.

- ReactNative 0.32
- Android 6+

**Comment by scerelli** [comment]
Idem, same problem.

**Comment by BeckZero** [comment]
Component 01 (showBar Hide): 
```
componentWillUnmount() {
  StatusBar.setHidden(true)
}
```

TO 

Component 02:
```
componentWillMount() {
  StatusBar.setHidden(false)
}
```
 
result: ShowBar SHOW

But

Component 01 (showBar Hide): 
```
componentWillUnmount() {
  AppActions.showBar(true)
}
```

TO 

Component 02:
```
componentDidMount() {
  AppActions.showBar(false)
}
```

result: ShowBar HIDE

**Comment by jasongaare** [comment]
Also noticed that if you highlight some text in the modal, the 'Text Selection' menu has a very undesirable transparent look that shows the view below.

Any ideas how to fix this appearance?

Screen shot:

![screen shot](https://cloud.githubusercontent.com/assets/15896334/20066617/bcc7847e-a4d7-11e6-936d-23502997f079.jpg)

**Comment by scerelli** [comment]
It's amazing that this issue was opened the May 9th and nobody still figured out why it has this behaviour!

**Comment by nihgwu** [comment]
@scerelli I've answered months ago to see my answer in #8627, so why this issue is still opening?

**Comment by scerelli** [comment]
@nihgwu honestly i don't know, and the fact that you answered to it's even stranger.
This fix/feature is not in roadmap at the moment and it's not a good thing since it brings a lot of inconsistency between scenes.

**Comment by janicduplessis** [comment]
I think there are still cases where the statusbar is not updated properly bacause the activity was null at the time it was updated, I think this happens mostly when moving the app from the background to foreground. I haven't really hit this issue yet since I'm not changing the statusbar much in my apps so I don't have a repro case to try to fix it. If someone wants to spend some time looking into why it happens and possible fixes it would be great.

I quick fix I can think of would be to subscribe to AppState and force an update of the statusbar native values at that time when we are sure the activity is available.

**Comment by janicduplessis** [comment]
I don't have much time to look into this at the moment, I suspect we'd want to change the dialog window flags to match the current statusbar config. We already set some flags here https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java#L199

**Comment by edencakir** [comment]
+1 RNv: 0.40

**Comment by Swordsman-Inaction** [comment]
@janicduplessis  I already checked this issue. The reason it doesn't work is because `WindowInsets` is been set to the wrong `window`. `Modal` is implemented with `Dialog`, `Dialog` will create a `window` on the top of `Activity`'s `Window`. So it won't work for now. But I couldn't find a good way to get the `Window` of `Dialog`, do you have any idea?

**Comment by omerdn1** [comment]
Any news about this issue? Still getting it with RN 0.4.2

**Comment by Traviskn** [comment]
I was able to work around this issue by going into my app's `android/app/src/main/res/values/styles.xml` file and changing the parent theme to `Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen`.  This essentially disables the status bar by default for your entire app, including for the modal. If you have other screens that need to show the status bar then you can still use the normal StatusBar api to show it if you want.

Here's my full styles.xml file for reference: 
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen">
        <!-- Customize your theme here. -->
    </style>
    <style name="AppTheme.Launcher">
        <item name="android:windowBackground">@drawable/launch_screen</item>
    </style>
</resources>
```

**Comment by yijian166** [comment]
@Traviskn This solution also has a issue, in some time, at bottom of the Modal has a transparent bar , and height equal to StartBar height.

**Comment by AdriaRios** [comment]
Still happens at 0.43 version.

Any updates?

**Comment by gezichenshan** [comment]
Mark!

**Comment by carlesnunez** [comment]
Any updates on this?

**Comment by mbashiq** [comment]
Okay So I found a solution for having the hidden status bar along with react native modal.

My previous code was like this : 

```
<View style={styles.container}>
  <StatusBar hidden={true}/>
  <View style={styles.content}>
  <Modal animation={fade} transparent={true}>
          {/*Modal Contents Here*/}
  </Modal>
</View>
```
 This code used to give me issues with UI views outside modal with position absolute and the above mentioned issue with Status Bar which shows up.

Replacing the above code layout into a new one where all the current contents come inside a New container outside helped me overcome both these problems. In my case the new formatted code that works is given below : 

```
<View style={styles.outerContainer}
  <View style={styles.container}>
    <StatusBar hidden={true}/>
    <View style={styles.content}>
  </View>
  <Modal animation={fade} transparent={true}>
          {/*Modal Contents Here*/}
  </Modal>
</View>
```


Hope this helps whoever is having this issue 🍺 🍺 🍺

**Comment by prince8verma** [comment]
I have the same issue , so i hide the status bar from styles.xml using "windowFullscreen" property setting to true, but doing so,  at bottom of the Modal has a transparent bar , and height equal to StartBar height.

**Comment by srameshr** [comment]
Any updates on this? Still see the status bar when the modal opens.

**Comment by EugeneBichel** [comment]
**"react-native": "0.44.2"**

- Set StatusBar.setHidden(true) in ComponentWillMount() - it is not working.
- Added StatusBar `<StatusBar hidden/>` - it is working until the first page refresh

**Comment by RavishankarR** [comment]
Any time frame by which this issue will be solved? RN 0.47 has been released now!

**Comment by EugeneBichel** [comment]
@RavishankarR, thanks for the reply. I has tried to check it, but 0.47 has changes, which broke many packages. Please take a look https://github.com/airbnb/lottie-react-native/issues/166

**Comment by EugeneBichel** [comment]
"react-native": "0.44.2"
It is working for me now. The issue was related with navigation and a view updation. But I can see jumping when I moving from some page with status bar to other page, where its status bar is hidden.

**Comment by RavishankarR** [comment]
@EugeneBichel  Could you explain how you got it to work in RN 0.44? 

I am trying to hide the statusbar only when opening a modal, which does not work in Android. 

Lastly, is there a way to set an offset value to the statusbar?

**Comment by SirNeuman** [comment]
This is an issue for me on Android in RN 0.47.1

**Comment by SirNeuman** [comment]
Just checked in RN 0.48.0 and it's still an issue

**Comment by dantman** [comment]
I fixed a different issue with the StatusBar handling on Android awhile ago.

For anyone interested in trying to fix this issue here is the code responsible for setting the various Android properties on the "Dialog" layer that is opened by Modal.
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java#L246-L282

Modal seems to be a layer of its own on top of the main layer/window and I think has it's own set of status bar properties separate from the main ones in the main activity.

**Comment by gregblass** [comment]
Just wondering if anyone has figured out a workaround for this? Looks like it was opened in May, 2016. It's almost November, 2017. Has anyone successfully hid the status bar in on Android?

**Comment by ryanlynnhorlacher** [comment]
The solution from @Traviskn  worked for me!  I don't have any gap at the bottom as some people described.

**Comment by husnainafzal86** [comment]
@Traviskn, Your solution worked for me as well like a charm. Thanks!

**Comment by khrizt** [comment]
@Traviskn solution didn't worked for me, any hint on what I may doing wrong?

**Comment by yelkamel** [comment]
Having the same issue, any idea how to fix it ?

**Comment by Traviskn** [comment]
@khrizt I'm not sure why it wouldn't be working, are you on a newer version of React Native?  It's also important to re-install the application because changing the theme in the styles.xml file is a native change and won't take effect until you actually re-install the app, a simple refresh won't work.

**Comment by khrizt** [comment]
@Traviskn Sorry, I was doing it totally wrong. It works! But the thing now is that I want to hide the status bar only in some modals, but not in all of them, I've tried to add the StatusBar to the Modals but it didn't work, If you have any ideas it'd be great :)

**Comment by soundstage** [comment]
@Traviskn Your work around works. Let us hope there will be a proper fix released soon.

**Comment by ShaikhKabeer** [comment]
@Traviskn  Thanks, it works for me

**Comment by davychhouk405** [comment]
@Traviskn's solution solved the problem for me perfectly. Thank you.

**Comment by fedegl** [comment]
@Traviskn's solution worked for me but only to hide the status bar. The Navigation bar at the right hand side (landscape mode) is still there. Anyone has a solution for this?

**Comment by zanchee** [comment]
+1 Still an issue.

I don't understand why the modal goes behind the status bar on iOS and not on Android. Very inconsistent and annoying!

**Comment by lcd11001** [comment]
Hello,
    Here is my solution

1. Overwrite file <node_modules>\react-native\ReactAndroid\src\main\res\views\modal\values\themes.xml
[themes.xml.txt](https://github.com/facebook/react-native/files/1667163/themes.xml.txt)

2. cd your project/android
        + change android SDK & NDK path in local.properties file
[local.properties.txt](https://github.com/facebook/react-native/files/1667173/local.properties.txt)
        + call command:
            gradlew ReactAndroid:installArchives

3. cd Root Project
        + call command:
            react-native run-android

Hope it helps!
Regards,
LCD

**Comment by zanchee** [comment]
@lcd11001 I'm using EXPO, and am not in a position to eject, so sadly, that is not an option for me.

**Comment by psegalen** [comment]
@Traviskn solution is functional but when you show a StatusBar and you open a Modal, the statusbar collapses up making all the app body going up 12 pixels, really awkward!
It's weird that when the modal opens it kills the underlying statusbar... 😢

**Comment by t4deu** [comment]
Hi everyone, just sent a PR with a fix, hope it helps to close this old issue!
@janicduplessis could you please review if everything is ok, anything just let me know, thanks :wink:!

**Comment by netsmertia** [comment]
I am still facing the same issue. Is there any react-native solution.

**Comment by Zanchee** [comment]
@netsmertia the pull request is not approved yet.

**Comment by liuqiang1357** [comment]
Still have the same issue.

**Comment by t4deu** [comment]
You are building from master? because the fix was not released yet!

**Comment by Letty-Liang** [comment]
@t4deu build with your commit; Still the same issue

**Comment by eQuinox-l** [comment]
Same issue where ...

**Comment by jaychenjun** [comment]
Please release the fix.

**Comment by axsann** [comment]
+1
Please release the fix.

**Comment by fungilation** [comment]
I confirm @Traviskn's workaround works.

Pretty incredible this issue is still around, now in RN 0.54.4 for my app, after 2 years.

**Comment by beevivo6** [comment]
@janicduplessis        It doesn't work.When the Modal show Statubar still apper ! How can I do ?

**Comment by iamcxa** [comment]
I confirm @Traviskn 's way too. this workaround may produce some issue at a particular scene(such as you need status bar display more than hidden),  but it still may be the best way to solve modal status bar problem once for all.

**Comment by banli17** [comment]
can use  origin android to resolve it ?

**Comment by beevivo6** [comment]
It's resolved,thank you!




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            魅璃儿
                            
                            
                                
                                    邮箱：beevivo6@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


On 07/17/2018 20:32, 板栗17 wrote: can use  origin android to resolve it ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/facebook/react-native","title":"facebook/react-native","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/facebook/react-native"}},"updates":{"snippets":[{"icon":"PERSON","message":"@banli17 in #7474: can use  origin android to resolve it ?"}],"action":{"name":"View Issue","url":"https://github.com/facebook/react-native/issues/7474#issuecomment-405565237"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/facebook/react-native/issues/7474#issuecomment-405565237",
"url": "https://github.com/facebook/react-native/issues/7474#issuecomment-405565237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [facebook/react-native] [Modal-StatusBar-Android] Statusbar shows up with setHidden(true) (#7474)",
"sections": [
{
"text": "",
"activityTitle": "**板栗17**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@banli17",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"facebook/react-native\",\n\"issueId\": 7474,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/facebook/react-native/issues/7474#issuecomment-405565237"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 141108329\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jdnichollsc** [comment]
@t4deu I can see the issue with react-native `0.56.0` from Android, any solution to fix the issue of the bottom of the modal?
Thanks in advance

**Comment by jdnichollsc** [comment]
Ok, fixed after use
`<style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen">`
instead of
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`

**Comment by farzd** [comment]
still an issue, using expo so cant change android specific xml files etc

**Comment by lyseiha** [comment]
When will you fixed this issue ?

**Comment by andrewzey** [comment]
The better solution is to not use the native React Modal. Use this library instead: https://github.com/maxs15/react-native-modalbox

**Comment by a-koka** [comment]
There is still a problem with devices that have a soft menu bar like the Samsung Galaxy S8 and no solution solves the problem with the soft menu bar region not being drawn over by the Modal.

**Comment by wayne214** [comment]
ok,fixed by using 
`
    <style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen">
        
        <item name="android:windowTranslucentStatus">true</item> // 设置状态栏不占据空间
    </style>`

**Comment by pablobrodt** [comment]
I used https://github.com/listenzz/react-native-modal-translucent, and worked like a charm.

```
settings.gradle
include ':modal-translucent'
project(':modal-translucent').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-modal-translucent/android')
```

```
build.gradle
implementation project(":modal-translucent")
```

```
MainApplication
import me.listenzz.modal.TranslucentModalReactPackage;

@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(new MainReactPackage(), ..., new TranslucentModalReactPackage());
}
```

**Comment by pablobrodt** [comment]
@Jelomite I just linked this https://github.com/listenzz/react-native-modal-translucent manually, like i said above, then used the react-native Modal with `transparent` prop.

**Comment by Jelomite** [comment]
I see, thanks 😄

**Comment by wkmcyz** [comment]
I changed the default Modal implementation of react-native and solved this problem. What I do is to replace the official Modal package with one a-little-modified Modal package which shows Modal in full screen with status bar above, you can refer to https://www.cnblogs.com/wkmcyz/articles/10277436.html for details.

**Comment by Cyphexl** [comment]
Honestly, never use react-native if you care about good visual experience.

**Comment by nihp** [comment]
I need to hide the iOS status bar of my app in some screens and not for all screens. Any solution for this.

I tried this but it did not work for me.

<StatusBar hidden={true} />

**Comment by arfa123** [comment]
Still happening in RN 0.60.5.

**Comment by arfa123** [comment]
react-native-modal-translucent solved my problem https://github.com/listenzz/react-native-modal-translucent

**Comment by joaodematejr** [comment]
+1

**Comment by cristianoccazinsp** [comment]
+1

**Comment by snamstorm** [comment]
+1

**Comment by AndreyPatseiko** [comment]
Used this [https://github.com/23mf/react-native-translucent-modal](https://github.com/23mf/react-native-translucent-modal)
