### ISSUE TITLE
TextInput's content is not center vertical

### ISSUE THREAD

**Issue by Yorkey** [facebook/react-native#7823]
Hi, I found the TextInput's content is not center vertical (in some android devices like HUAWEI),when the TextInput's parent sytle is{**flexDirection: 'row'**},
It looks like the baseline is center,and text is more upper.
![textinput_bug](https://cloud.githubusercontent.com/assets/1419481/15632153/dbe591e8-25bb-11e6-8d18-6f19b717027d.png)

**Comment by Yorkey** [comment]
I fixed the bug,this is because TextInput has default padding,
My solution is add paddingTop: 0,paddingBottom: 0,to the TextInput style.

**Comment by liuyanhongwl** [comment]
why paddingVertical not useful

**Comment by SargTeX** [comment]
I've just encountered this bug again. The placeholders of my TextInputs where on the emulator perfectly centered, but not on my device. Adding `paddingTop: 0, paddingBottom: 0` to the TextInput styles solved the problem - now, the placeholders are centered vertically on both, emulator and device.

Interesting, though, that this bug still occures (RN 0.54.2) and that setting `textAlignVertical: 'center',` does not help at all.
