### ISSUE TITLE
[iOS] RCTWebSocket does not build on Xcode Version 8.0 beta (8S128d)

### ISSUE THREAD

**Issue by ppong** [facebook/react-native#8108]
Does anyone have problem building React Native on the Xcode 8.0 beta?
<img width="260" alt="screen shot 2016-06-14 at 9 48 32 am" src="https://cloud.githubusercontent.com/assets/1063140/16051626/5aabb31c-3215-11e6-8c05-75aa18f59027.png">
<img width="1021" alt="screen shot 2016-06-14 at 9 50 00 am" src="https://cloud.githubusercontent.com/assets/1063140/16051633/62cb435a-3215-11e6-8db2-c06b957b4a42.png">

**Comment by alexanderniebuhr** [comment]
Yeah same Problem

**Comment by HughLi** [comment]
Same Problem  +1

**Comment by finalquest** [comment]
Yep. In iOS 10, SecRandomCopyBytes has a new attribute
__attribute__ ((warn_unused_result)).

**Comment by nickstamas** [comment]
How should we handle this? Has anyone had luck building for iOS10? I saw @vjeux's tweet [here](https://twitter.com/Vjeux/status/742651239922606080) and was hoping that change was the only one needed.

**Comment by mskalra** [comment]
Not sure if this is the right fix but I was able to get around this by casting SecRandomCopyBytes as void: 

  (void)SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
  (void)SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);

This + what nickstamas linked was enough to get it to build and deploy on ios10.

**Comment by nickstamas** [comment]
@mskalra With the combination of the changes to RCTScrollView and RCTSRWebSocket, I can get an app to build, but I'm seeing a lot of console output like this:

`nw_endpoint_flow_protocol_disconnected [1.1 ::1.8081 cancelled socket-flow (null)] Output protocol disconnected`

There's other weirdness too. I have to run the packager manually, it doesn't run automatically when I hit Play in Xcode. Also, the app seems unresponsive in the Simulator.

**Comment by mskalra** [comment]
@nickstamas strange, it seems to build and deploy like normal for me, both on my device and in the simulator.

Will probably have to wait for an official fix.. Shouldn't be too long hopefully. Good luck!

**Comment by stefanfisk** [comment]
Wrapping `SecRandomCopyBytes()` with a call to `assert(0 == ...)` is probably a marginally better idea, so that if it against all odds fails it does not do so silently.

**Comment by batuhan** [comment]
Is there an update on this?

**Comment by ammichael** [comment]
I've tried @mskalra solution, and it seems to work.. but then I've received another error related to RCTScrollView:

![error1](https://cloud.githubusercontent.com/assets/6873880/16244271/9a63ea30-37d1-11e6-8e95-06cd029308f6.png)
![error2](https://cloud.githubusercontent.com/assets/6873880/16244272/9a929ce0-37d1-11e6-96ae-9176e85b15df.png)

**Comment by mskalra** [comment]
@ammichael add these changes as well and you should be good: https://github.com/facebook/react-native/commit/7c8b91442b3547cf94c752f234210bef0848c00a

**Comment by ammichael** [comment]
@mskalra Well, it did helped to stop building errors, but when it runs in simulator,
 the screen is scaled down and I'm receiving errors.

I've created a gist with the Xcode and RN Packager logs: https://gist.github.com/ammichael/0c7c915216c30c7d156ffb3bc44f938d

Here how the screen is scaled:

![rn-ios10-screen](https://cloud.githubusercontent.com/assets/6873880/16269600/589ba244-3869-11e6-94b1-9a69d4466da2.png)

**Comment by javache** [comment]
Could you please send a pull-request with these changes? Thanks!

**Comment by antoor** [comment]
Hi, guys!
**I have successfully fix this bug!**

## Principle:
Copy Xcode Beta.app (xcode_8_beta.xip) in IOS10 device support files to Xcode.app (7.3.1 xcode), and then connect the device to success in ios10 version of the real machine debugging equipment

## Operating:
1. Install `xcode 8 beta`
2. Backup the ios10-support file
3. Remove xcode 8 beta, and then install xcode 7.3.1
4. Copy the backup file to xcode 7.3.1
5. Restart xcode

## Examples of command:
``` sh
cp -r /Applications/Xcode_beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.0\ \(14A5261u\) /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
```

> Facilitate, I upload the supporting documents, copies of xcode 7.3.1 to use!

## 中文
嗨，大家好
我已经成功解决该错误了！

## 原理：
复制Xcode Beta.app(xcode_8_beta.xip)中的IOS10设备支持文件到Xcode.app(xcode 7.3.1)中，然后连接设备即可成功在ios10版本的设备上进行真机调试

## 操作：
1. 安装xcode 8 beta
2. 拷贝ios10支持文件备份
3. 删除xcode 8 beta，安装xcode 7.3.1
4. 拷贝ios10支持文件备份到xcode 7.3.1中
5. 重启xcode

## 示例命令
``` sh
cp -r /Applications/Xcode_beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.0\ \(14A5261u\) /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
```

方便大家，我上传了该支持文件，拷贝到xcode 7.3.1对应目录即可使用！

![image](https://cloud.githubusercontent.com/assets/13709206/16356481/e31372e0-3b0b-11e6-8d0b-9a32e26e9e27.png)

![image](https://cloud.githubusercontent.com/assets/13709206/16356474/a9b178b2-3b0b-11e6-86c2-e3f53b836f7e.png)


[10.0 (14A5261u).zip](https://github.com/facebook/react-native/files/333040/10.0.14A5261u.zip)

**Comment by ppong** [comment]
Thanks @antoor this works for me!

**Comment by imjakechapman** [comment]
@antoor Worked for me as well.

**Comment by kobePer** [comment]
Great workaround! thanks, @antoor !

**Comment by cloudrave** [comment]
Thanks, @antoor!  Is anyone working on supporting Xcode 8?

**Comment by Druux** [comment]
I just followed your instructions @antoor, but I can't switch the Deployment Target of my application to iOS 10.0. In my case there ins't a selectable deployment target option in the dropdown. Do you have any advices?

**Comment by dama2716588** [comment]
@TimBroddin

**Comment by dama2716588** [comment]
@TimBroddin  : Thank you !

**Comment by Erwin11** [comment]
@ammichael  
My porblem sames to you.
It works for me. 
link:http://blog.csdn.net/jeikerxiao/article/details/53183375

## **by English:**
All the React Native Projects Written by Xcode7, When you Update to Xcode8 will get some Error, need to fix it, follow these steps.

### 1. RCTSRWebSocket.m Error
**Error：**  

`SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`    

**Fix it：**  
add: *（void）*

`(void)SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`


**Or，Plan B（PS:I used it ,worked out!）：**   
fix it：
 
```
int result = SecRandomCopyBytes(kSecRandomDefault,sizeof(uint32_t), (uint8_t *)mask_key);
assert(result == 0);
```
    
    

### 2.  RCTScrollView.m Error

1.How to fix：

Open **RCTSCrollView.m** ,Command+F Search：

`@implementation RCTCustomScrollView`

You will find one result, and fix it：


```
@implementation RCTCustomScrollView
{
  __weak UIView *_dockedHeaderView;
  RCTRefreshControl *_refreshControl;  
}
```

Done.

## **by 中文：**
Xcode7写的所有React Native项目，在升级到Xcode8都会报错，需要做以下修改。

### 一、RCTSRWebSocket.m 报错
**错误位置：**  

`SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`    

**解决方法（一）：**  
加入: *（void）*

`(void)SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`


**或者，解决方法（二，PS:我用的是这种）：**   
修改为：给一个int对象接受SecRandomCopyBytes 函数并且用assert检查函数对象。 
 
```
int result = SecRandomCopyBytes(kSecRandomDefault,sizeof(uint32_t), (uint8_t *)mask_key);
assert(result == 0);
```
    
    

### 二、RCTScrollView.m 报错

1.解决方法：

打开 **RCTSCrollView.m** Command+F 搜索：

`@implementation RCTCustomScrollView`

会搜索到一个结果，然后增加一行代码：
修改为：

```
@implementation RCTCustomScrollView
{
  __weak UIView *_dockedHeaderView;
  RCTRefreshControl *_refreshControl;  
}
```

完成。

## I Hope this works for you. ^U^

**Comment by Balasnest** [comment]
Tried with all solutions. Still getting this error every time for all fresh project and running project also.

![screen shot 2017-08-11 at 1 46 44 pm](https://user-images.githubusercontent.com/6050520/29205667-faa18878-7e9b-11e7-87d3-17916551a5d1.png)

**Comment by DanielRuf** [comment]
This is still an issue. So far React Native has many issues related to Xcode 8 and iOS 10(.2+) and even deprecated packages and thrir alternatives are not really compatible with most old setups.

How did others solve this in new projects?
