### ISSUE TITLE
PushNotificationIOS.requestPermissions promise never resolves

### ISSUE THREAD

**Issue by chandlervdw** [facebook/react-native#9105]
I'm confused as to how this is supposed to be used. The [RN PushNotificationIOS docs](https://facebook.github.io/react-native/docs/pushnotificationios.html#requestpermissions) say:

> This method returns a promise that will resolve when the user accepts, rejects, or if the permissions were previously rejected. The promise resolves to the current state of the permission.

But when I use the following, `console.log()` is never hit.

```
PushNotificationIOS.requestPermissions().then((permissions) => console.log(permissions));
```

What am I missing?

**Comment by nazywamsiepawel** [comment]
+1, I'm facing the same issue

**Comment by upgle** [comment]
plz check it #8622

**Comment by mikelovesrobots** [comment]
+1 

I thought I was missing something really obvious. Glad I'm not.

**Comment by ambarc** [comment]
+1

**Comment by joshuapinter** [comment]
Same here. The commit that added the promise for `requestPermissions()` has been in there since 0.28 but I've never had it working. Now trying on 0.33.0 and it's still not working.

**Comment by joshuapinter** [comment]
Figured out something very strange...

In order for `PushNotificationIOS.requestPermissions()` to resolve the `Promise`, you _need_ to add an event listener, like this: 

```js
PushNotificationIOS.addEventListener('register', (token) => {});
```

What's even more interesting is that it doesn't even have to be the `'register'` event, it could be `'notification'` or `'localNotification'` as well and they all work.

So this is what I ended up using anywhere I needed to get and handle the `requestPermissions()` Promise resolve:

```js
componentWillMount() {
  // NOTE: You absolutely need this for requestPermissions() promise to resolve.   
  PushNotificationIOS.addEventListener('register', (token) => {});
}

componentWillUnmount() {
  PushNotificationIOS.removeEventListener('register', (token) => {});
}
```

Can at least a couple of you test this and confirm the behaviour. Once it's reproducible on more than just my machine, I'll dig deeper and see what's the cause and issue a PR to fix it.

Thanks.

**Comment by superandrew213** [comment]
[#8622](https://github.com/facebook/react-native/pull/8622) fixes this

**Comment by joshuapinter** [comment]
@superandrew213 Are you sure, because they seem to be related, but different, issues. That issue seems to be regarding calling `requestPermissions()` before the first one has be resolved.

**Comment by onpaws** [comment]
Today I included
`PushNotificationIOS.requestPermissions().then((perms) => console.log(perms));`
on app startup and I got the standard iOS permissions prompt as expected. 
Seems like maybe RN 0.33 included whatever was needed to fix?
RN 0.33, OS X 10.11.6, iOS Simulator on 9.3

**Comment by joshuapinter** [comment]
@onpaws Try denying permission and running this again to see if you get the promise resolved.

**Comment by onpaws** [comment]
@joshuapinter ah, gotcha. 
i was able to report - denying perms and running app again never resolves promise. 
The [fix](https://github.com/facebook/react-native/issues/9105#issuecomment-246180895) also works on my end

**Comment by joshuapinter** [comment]
Thanks for confirming, @onpaws!

**Comment by krishangupta** [comment]
@joshuapinter's solution works perfectly for me. Thanks!

**Comment by joshuapinter** [comment]
Thanks for also confirming, @krishangupta! 

I'll wait to hear from a React Native core team member before I write the PR as those take a long time to write and get approved so I'd like their alignment on this issue.

**Comment by abazlinton** [comment]
PR #13263 should resolve this I think

**Comment by joshuapinter** [comment]
@abazlinton Sweet, let's hope it gets into 0.44.

**Comment by ggaabe** [comment]
@joshuapinter your fix didn't work for me. I put the register function in the constructor, the componentWillMount, and in the constructor and componentWillMount of a child component that can also call the requestPermissions function if the user decides to turn on notifications inside of that. 

The promise still doesn't resolve though, as I still get the "cannot call requestpermissions twice before the first has returned" if I try to request permissions from the child component. (requestPermissions is initially called inside the constructor of the parent).

Any ideas?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by onpaws** [comment]
@joshuapinter would you happen to know if this has been resolved?

**Comment by joshuapinter** [comment]
@onpaws I doubt it. Haven't tested it in a long time, though. If you check, post back here to let me know.

**Comment by Rested** [comment]
Still getting this problem on 0.50.0

**Comment by onpaws** [comment]
Haven't tried this in a while but a shame to hear that it's still an issue.

**Comment by remigallego** [comment]
Still happening on 0.55.1 😞
